#!/usr/bin/env python3
"""
兵庫県の斎場データ バッチ2: 神戸市 後半30件（長田区・須磨区・垂水区・西区）
"""
import json
import subprocess
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

venues = [
    # =============================================
    # 神戸市長田区 (5件)
    # =============================================
    {
        "name": "ベルコシティホール長田",
        "slug": "hyogo-bellco-nagata",
        "venue_type": "private_hall",
        "description": "長田区の中心部に位置するベルコ直営会館。高速長田駅から徒歩5分のアクセス良好な立地。下町の温かさが感じられるエリアで、地元に根ざした丁寧なサービスを提供しています。家族葬から一般葬まで対応可能です。",
        "address": "兵庫県神戸市長田区大橋町5-3-1",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6620,
        "longitude": 135.1530,
        "nearest_station": "神戸高速鉄道 高速長田駅",
        "station_walk_minutes": 5,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 540000}],
        "features": ["家族葬対応", "駅近", "地域密着", "バリアフリー"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 52,
    },
    {
        "name": "長田メモリアルホール",
        "slug": "hyogo-nagata-memorial",
        "venue_type": "private_hall",
        "description": "長田区の地域密着型葬儀会館。長田神社近くの閑静な住宅街に位置し、地元の方々に長年親しまれています。アットホームな雰囲気で、少人数の家族葬に最適な空間を提供します。",
        "address": "兵庫県神戸市長田区長田町1-5-10",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6680,
        "longitude": 135.1480,
        "nearest_station": "地下鉄西神・山手線 長田駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬対応", "地域密着", "少人数対応", "アットホーム"],
        "operator_name": "長田メモリアルホール",
        "rating_avg": 4.1,
        "review_count": 35,
    },
    {
        "name": "真言宗 長楽寺会館",
        "slug": "hyogo-choraku-ji-kaikan",
        "venue_type": "temple_hall",
        "description": "長田区にある真言宗の寺院式場。歴史ある本堂で荘厳な仏式葬儀を執り行えます。僧侶の読経とともに、伝統的な形式で故人をお見送りしたい方におすすめ。寺院ならではの心静まる空間です。",
        "address": "兵庫県神戸市長田区長楽町4-2-5",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6650,
        "longitude": 135.1510,
        "nearest_station": "地下鉄西神・山手線 長田駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "控室": True, "駐車場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 530000}],
        "features": ["寺院式場", "仏式葬儀", "伝統的", "荘厳な雰囲気"],
        "operator_name": "長楽寺",
        "rating_avg": 4.0,
        "review_count": 22,
    },
    {
        "name": "家族葬のファミーユ 長田ホール",
        "slug": "hyogo-familiu-nagata",
        "venue_type": "private_hall",
        "description": "長田区で家族葬のファミーユが運営する小規模専用ホール。JR新長田駅から徒歩7分の便利な立地。10名〜25名の家族葬に最適化された温かみのある空間で、シンプルかつ丁寧なお見送りを実現します。",
        "address": "兵庫県神戸市長田区若松町3-2-8",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6560,
        "longitude": 135.1440,
        "nearest_station": "JR神戸線 新長田駅",
        "station_walk_minutes": 7,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 120000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "駅徒歩圏内", "明朗会計"],
        "operator_name": "家族葬のファミーユ",
        "rating_avg": 4.2,
        "review_count": 30,
    },
    {
        "name": "セレモニーホール新長田",
        "slug": "hyogo-ceremony-shin-nagata",
        "venue_type": "private_hall",
        "description": "JR新長田駅前の再開発エリアに位置する近代的な葬儀ホール。駅から徒歩3分の抜群のアクセス。中規模の式場は家族葬から一般葬まで対応でき、充実した設備で快適な葬儀を提供しています。",
        "address": "兵庫県神戸市長田区二葉町5-1-30",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6540,
        "longitude": 135.1460,
        "nearest_station": "JR神戸線 新長田駅",
        "station_walk_minutes": 3,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 560000}],
        "features": ["駅前立地", "家族葬対応", "バリアフリー", "近代的設備"],
        "operator_name": "セレモニーホール互助会",
        "rating_avg": 4.1,
        "review_count": 45,
    },

    # =============================================
    # 神戸市須磨区 (7件)
    # =============================================
    {
        "name": "神戸市立西神戸斎場",
        "slug": "hyogo-kobe-nishi-kobe-saijo",
        "venue_type": "public_crematorium",
        "description": "神戸市が運営する西部地区の公営火葬場。須磨区から西区エリアの葬儀で多く利用されています。神戸市民は低料金で火葬が可能。広い敷地に十分な駐車スペースを確保しており、緑に囲まれた落ち着いた環境です。",
        "address": "兵庫県神戸市須磨区白川字片山1番",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6920,
        "longitude": 135.1050,
        "nearest_station": "神戸市営地下鉄 名谷駅",
        "station_walk_minutes": 20,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 80,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True, "売店": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}],
        "features": ["火葬場", "公営斎場", "神戸市民割引", "大型駐車場"],
        "operator_name": "神戸市",
        "rating_avg": 3.6,
        "review_count": 95,
    },
    {
        "name": "ベルコシティホール須磨",
        "slug": "hyogo-bellco-suma",
        "venue_type": "private_hall",
        "description": "須磨区の中心部に位置するベルコの葬儀会館。JR須磨駅から徒歩10分。須磨海岸のほど近くにあり、落ち着いた環境でお別れの時間を過ごせます。家族葬対応の小ホールと一般葬対応の大ホールを完備。",
        "address": "兵庫県神戸市須磨区大田町3-5-1",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6500,
        "longitude": 135.1270,
        "nearest_station": "JR神戸線 須磨駅",
        "station_walk_minutes": 10,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 560000}],
        "features": ["家族葬対応", "一般葬対応", "駅徒歩圏内", "バリアフリー"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.1,
        "review_count": 67,
    },
    {
        "name": "公益社 須磨会館",
        "slug": "hyogo-koekisha-suma",
        "venue_type": "private_hall",
        "description": "名谷駅から徒歩8分に位置する公益社の須磨エリア会館。須磨ニュータウンの住民を中心に利用されている信頼の葬儀会館。1日1組貸切制で、心のこもったお別れの場を提供しています。",
        "address": "兵庫県神戸市須磨区中落合2-1-10",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6750,
        "longitude": 135.1100,
        "nearest_station": "神戸市営地下鉄 名谷駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 380000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 620000}],
        "features": ["1日1組貸切", "家族葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "株式会社公益社",
        "rating_avg": 4.4,
        "review_count": 72,
    },
    {
        "name": "須磨やすらぎ斎場",
        "slug": "hyogo-suma-yasuragi-saijo",
        "venue_type": "private_hall",
        "description": "須磨区板宿エリアの地域密着型斎場。山陽電鉄板宿駅から徒歩5分。小規模ながら清潔感のある式場で、リーズナブルな料金設定が魅力。地元に根差したきめ細やかなサービスが特徴です。",
        "address": "兵庫県神戸市須磨区平田町2-3-8",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6580,
        "longitude": 135.1330,
        "nearest_station": "山陽電鉄 板宿駅",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬対応", "駅近", "リーズナブル", "地域密着"],
        "operator_name": "須磨やすらぎ斎場",
        "rating_avg": 4.0,
        "review_count": 38,
    },
    {
        "name": "小さなお葬式 須磨ホール",
        "slug": "hyogo-chiisana-suma",
        "venue_type": "private_hall",
        "description": "小さなお葬式が須磨区で提携する葬儀式場。シンプルな料金プランで必要なサービスを提供。費用を抑えつつも丁寧な葬儀を希望する方に最適です。24時間年中無休でご相談を受け付けています。",
        "address": "兵庫県神戸市須磨区前池町3-1-12",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6530,
        "longitude": 135.1300,
        "nearest_station": "JR神戸線 鷹取駅",
        "station_walk_minutes": 8,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["低価格", "明朗会計", "24時間対応", "少人数対応"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 3.9,
        "review_count": 32,
    },
    {
        "name": "名谷メモリアルホール",
        "slug": "hyogo-myodani-memorial",
        "venue_type": "private_hall",
        "description": "名谷駅前のメモリアルホール。須磨ニュータウンの中心部に位置し、地下鉄名谷駅から徒歩3分。大小2つの式場を備え、家族葬から中規模の一般葬まで対応。駅直結の利便性と充実した設備が魅力です。",
        "address": "兵庫県神戸市須磨区落合1-1-5",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6770,
        "longitude": 135.1080,
        "nearest_station": "神戸市営地下鉄 名谷駅",
        "station_walk_minutes": 3,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宴会場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["駅前立地", "家族葬対応", "バリアフリー", "充実した設備"],
        "operator_name": "名谷メモリアルホール",
        "rating_avg": 4.2,
        "review_count": 55,
    },
    {
        "name": "セレモニーホール北須磨",
        "slug": "hyogo-ceremony-kita-suma",
        "venue_type": "private_hall",
        "description": "須磨区北部の妙法寺エリアにある葬儀ホール。地下鉄妙法寺駅から徒歩10分。住宅街の中に位置し、落ち着いた環境でお別れの時間を過ごせます。ベテランスタッフの心のこもったサービスが評判です。",
        "address": "兵庫県神戸市須磨区横尾3-5-2",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6850,
        "longitude": 135.1150,
        "nearest_station": "神戸市営地下鉄 妙法寺駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 530000}],
        "features": ["家族葬対応", "閑静な環境", "駐車場完備", "バリアフリー"],
        "operator_name": "セレモニーホール互助会",
        "rating_avg": 4.0,
        "review_count": 38,
    },

    # =============================================
    # 神戸市垂水区 (7件)
    # =============================================
    {
        "name": "ベルコシティホール垂水",
        "slug": "hyogo-bellco-tarumi",
        "venue_type": "private_hall",
        "description": "垂水区の中心部に位置するベルコ直営の葬儀会館。JR垂水駅から徒歩8分のアクセス良好な立地。明石海峡大橋を望む垂水エリアで、落ち着いた雰囲気の式場を提供しています。家族葬向けのプランが充実。",
        "address": "兵庫県神戸市垂水区神田町4-5-1",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6310,
        "longitude": 135.0520,
        "nearest_station": "JR神戸線 垂水駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "駅徒歩圏内", "バリアフリー", "海が近い"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.2,
        "review_count": 65,
    },
    {
        "name": "公益社 垂水会館",
        "slug": "hyogo-koekisha-tarumi",
        "venue_type": "private_hall",
        "description": "垂水区で公益社が運営する葬儀会館。垂水駅から徒歩6分の好立地で、地域の方々に長年信頼されています。1日1組貸切制でゆっくりとしたお別れの時間を確保。事前相談も随時受け付けています。",
        "address": "兵庫県神戸市垂水区平磯1-2-15",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6280,
        "longitude": 135.0500,
        "nearest_station": "JR神戸線 垂水駅",
        "station_walk_minutes": 6,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 380000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 620000}],
        "features": ["1日1組貸切", "駅近", "宿泊可能", "家族葬対応"],
        "operator_name": "株式会社公益社",
        "rating_avg": 4.3,
        "review_count": 58,
    },
    {
        "name": "垂水やすらぎ典礼会館",
        "slug": "hyogo-tarumi-yasuragi-tenrei",
        "venue_type": "private_hall",
        "description": "垂水区舞子エリアに位置する落ち着いた葬儀会館。舞子公園駅から徒歩7分。明石海峡を望む穏やかな環境で、家族のみの小さなお葬式から中規模のお葬式まで対応。きめ細やかなサービスが好評です。",
        "address": "兵庫県神戸市垂水区舞子台6-1-8",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6340,
        "longitude": 135.0310,
        "nearest_station": "JR神戸線 舞子駅",
        "station_walk_minutes": 7,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 520000}],
        "features": ["家族葬対応", "舞子エリア", "駅徒歩圏内", "バリアフリー"],
        "operator_name": "垂水やすらぎ典礼",
        "rating_avg": 4.1,
        "review_count": 42,
    },
    {
        "name": "家族葬のファミーユ 垂水ホール",
        "slug": "hyogo-familiu-tarumi",
        "venue_type": "private_hall",
        "description": "垂水区で家族葬のファミーユが展開する専用ホール。少人数の家族葬に特化した設計で、温かみのある落ち着いた空間。明確な料金体系で追加費用を心配することなく安心してご利用いただけます。",
        "address": "兵庫県神戸市垂水区天ノ下町1-8-3",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6290,
        "longitude": 135.0540,
        "nearest_station": "JR神戸線 垂水駅",
        "station_walk_minutes": 5,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 120000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "明朗会計", "駅近"],
        "operator_name": "家族葬のファミーユ",
        "rating_avg": 4.2,
        "review_count": 35,
    },
    {
        "name": "小さなお葬式 垂水ホール",
        "slug": "hyogo-chiisana-tarumi",
        "venue_type": "private_hall",
        "description": "垂水区で小さなお葬式が提携する葬儀式場。業界最安水準の料金プランが魅力で、必要なサービスをコンパクトにまとめたプランを提供。24時間対応で急なご依頼にもスムーズに対応します。",
        "address": "兵庫県神戸市垂水区陸ノ町3-2-10",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6320,
        "longitude": 135.0560,
        "nearest_station": "山陽電鉄 山陽垂水駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["低価格", "明朗会計", "24時間対応", "コンパクト"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 3.9,
        "review_count": 28,
    },
    {
        "name": "学園都市メモリアルホール",
        "slug": "hyogo-gakuentoshi-memorial",
        "venue_type": "private_hall",
        "description": "神戸市営地下鉄学園都市駅近くに位置する葬儀会館。大学が集まる文教地区の落ち着いた環境で、ゆっくりとお別れの時間を過ごせます。大型駐車場完備で車での参列にも便利です。",
        "address": "兵庫県神戸市垂水区学が丘4-1-5",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6590,
        "longitude": 135.0650,
        "nearest_station": "神戸市営地下鉄 学園都市駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 540000}],
        "features": ["大型駐車場", "家族葬対応", "文教地区", "バリアフリー"],
        "operator_name": "学園都市メモリアル",
        "rating_avg": 4.0,
        "review_count": 40,
    },
    {
        "name": "舞子メモリアルガーデン",
        "slug": "hyogo-maiko-memorial-garden",
        "venue_type": "private_hall",
        "description": "明石海峡大橋を望む舞子エリアの斎場。自然豊かなガーデン風の外構が特徴で、開放的な雰囲気の中でお見送りができます。家族葬に特に力を入れており、少人数でも温かいセレモニーを提案しています。",
        "address": "兵庫県神戸市垂水区西舞子1-10-2",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6370,
        "longitude": 135.0230,
        "nearest_station": "JR神戸線 舞子駅",
        "station_walk_minutes": 12,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "ガーデン": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 560000}],
        "features": ["ガーデン風", "家族葬対応", "明石海峡ビュー", "バリアフリー"],
        "operator_name": "舞子メモリアルガーデン",
        "rating_avg": 4.3,
        "review_count": 48,
    },

    # =============================================
    # 神戸市西区 (6件)
    # =============================================
    {
        "name": "ベルコシティホール西神中央",
        "slug": "hyogo-bellco-seishin-chuo",
        "venue_type": "private_hall",
        "description": "西神中央駅前に位置するベルコの大型葬儀会館。西神ニュータウンの中心部にあり、駅から徒歩5分の好アクセス。大小3つの式場を備え、家族葬から大規模な一般葬まで幅広く対応しています。",
        "address": "兵庫県神戸市西区糀台5-2-1",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6900,
        "longitude": 135.0110,
        "nearest_station": "神戸市営地下鉄 西神中央駅",
        "station_walk_minutes": 5,
        "capacity_max": 150,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True, "宴会場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["駅前立地", "大規模対応", "家族葬対応", "大型駐車場"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.2,
        "review_count": 78,
    },
    {
        "name": "公益社 西神会館",
        "slug": "hyogo-koekisha-seishin",
        "venue_type": "private_hall",
        "description": "西区伊川谷エリアの公益社直営会館。閑静な住宅街に位置し、プライベートな空間でゆっくりとお別れの時間を過ごせます。ベテランスタッフによる丁寧な対応と、充実した設備が自慢の会館です。",
        "address": "兵庫県神戸市西区伊川谷町潤和1-10",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6700,
        "longitude": 135.0300,
        "nearest_station": "神戸市営地下鉄 伊川谷駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 370000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["家族葬対応", "宿泊可能", "閑静な環境", "駐車場完備"],
        "operator_name": "株式会社公益社",
        "rating_avg": 4.3,
        "review_count": 62,
    },
    {
        "name": "西区ファミリーホール",
        "slug": "hyogo-nishi-ku-family-hall",
        "venue_type": "private_hall",
        "description": "西区の地域密着型葬儀ホール。明石に隣接するエリアで、地元の方々に親しまれています。アットホームな雰囲気が魅力で、小規模の家族葬を得意としています。リーズナブルな料金設定も人気の理由です。",
        "address": "兵庫県神戸市西区玉津町小山180-1",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6620,
        "longitude": 135.0030,
        "nearest_station": "JR神戸線 明石駅",
        "station_walk_minutes": 20,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 290000}],
        "features": ["家族葬対応", "リーズナブル", "地域密着", "アットホーム"],
        "operator_name": "西区ファミリーホール",
        "rating_avg": 4.0,
        "review_count": 32,
    },
    {
        "name": "家族葬のファミーユ 西神ホール",
        "slug": "hyogo-familiu-seishin",
        "venue_type": "private_hall",
        "description": "西神ニュータウンエリアにあるファミーユの家族葬専用ホール。西神中央駅から徒歩12分。家族だけの小さなお別れに最適化された空間で、明確な料金体系が安心。事前相談も随時受け付けています。",
        "address": "兵庫県神戸市西区樫野台3-5-2",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6930,
        "longitude": 135.0050,
        "nearest_station": "神戸市営地下鉄 西神中央駅",
        "station_walk_minutes": 12,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 120000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "明朗会計", "事前相談可"],
        "operator_name": "家族葬のファミーユ",
        "rating_avg": 4.1,
        "review_count": 30,
    },
    {
        "name": "西神戸メモリアルパーク",
        "slug": "hyogo-nishi-kobe-memorial-park",
        "venue_type": "private_hall",
        "description": "西区の広大な敷地に位置する総合メモリアル施設。式場、安置室、宴会場を完備し、通夜から精進落としまで一貫して行えます。100台収容の大型駐車場があり、大人数の参列にも対応可能です。",
        "address": "兵庫県神戸市西区神出町田井395",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.7250,
        "longitude": 134.9800,
        "nearest_station": "神戸市営地下鉄 西神中央駅",
        "station_walk_minutes": 30,
        "capacity_max": 200,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 100,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True, "宴会場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 520000}],
        "features": ["大規模対応", "大型駐車場", "総合施設", "宿泊可能"],
        "operator_name": "西神戸メモリアルパーク",
        "rating_avg": 4.0,
        "review_count": 50,
    },
    {
        "name": "セレモニーホール押部谷",
        "slug": "hyogo-ceremony-oshibe-dani",
        "venue_type": "private_hall",
        "description": "西区押部谷の自然に囲まれた葬儀ホール。のどかな田園風景の中で、心穏やかにお別れの時間を過ごせます。地元密着のきめ細やかなサービスが特徴で、家族葬を中心に対応しています。",
        "address": "兵庫県神戸市西区押部谷町栄2-1",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.7350,
        "longitude": 135.0000,
        "nearest_station": "神戸電鉄 押部谷駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 115000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬対応", "自然豊かな環境", "地域密着", "駐車場完備"],
        "operator_name": "セレモニーホール互助会",
        "rating_avg": 4.0,
        "review_count": 25,
    },
]

# 10件ずつバッチ投入
total = len(venues)
print(f"兵庫県バッチ2: 神戸市後半 {total}件を投入開始")
for i in range(0, total, 10):
    batch = venues[i:i+10]
    status = insert_batch(batch)
    print(f"  バッチ {i//10+1}: {len(batch)}件 → HTTP {status}")
    if status != "201":
        print(f"  エラー!")
        data_json = json.dumps(batch, ensure_ascii=False)
        result = subprocess.run([
            "curl", "-s",
            "-X", "POST", SUPABASE_URL,
            "-H", f"apikey: {API_KEY}",
            "-H", f"Authorization: Bearer {API_KEY}",
            "-H", "Content-Type: application/json",
            "-H", "Prefer: return=minimal",
            "-H", "User-Agent: Mozilla/5.0",
            "-d", data_json
        ], capture_output=True, text=True)
        print(f"  詳細: {result.stdout[:500]}")
    time.sleep(1)
print(f"バッチ2完了: {total}件")
