# -*- coding: utf-8 -*-
import json, subprocess, time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

venues = [
    # === 伊勢市 5件 ===
    {"name":"ティア伊勢","slug":"mie-tier-ise","venue_type":"private_hall","description":"伊勢神宮の門前町・伊勢市の中核斎場。近鉄宇治山田駅から近く、アクセス便利です。","address":"三重県伊勢市岩渕1-4-28","prefecture_slug":"mie","city_slug":"ise","latitude":34.487,"longitude":136.711,"nearest_station":"近鉄山田線 宇治山田駅","station_walk_minutes":8,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":348000},{"type":"ippanso","label":"一般葬プラン","priceFrom":650000}],"features":["家族葬対応","駅近"],"operator_name":"ティア","rating_avg":4.2,"review_count":30},
    {"name":"紫雲殿伊勢","slug":"mie-shiunden-ise","venue_type":"private_hall","description":"伊勢市の紫雲殿。外宮参道にも近い格式ある立地の式場です。","address":"三重県伊勢市本町18-20","prefecture_slug":"mie","city_slug":"ise","latitude":34.490,"longitude":136.708,"nearest_station":"JR参宮線 伊勢市駅","station_walk_minutes":5,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":340000},{"type":"ippanso","label":"一般葬プラン","priceFrom":640000}],"features":["家族葬対応","駅近"],"operator_name":"紫雲殿","rating_avg":4.0,"review_count":22},
    {"name":"伊勢市斎場","slug":"mie-ise-saijo","venue_type":"public_crematorium","description":"伊勢市が運営する公営火葬場。市民料金で利用できます。","address":"三重県伊勢市鹿海町字大谷山2091","prefecture_slug":"mie","city_slug":"ise","latitude":34.470,"longitude":136.690,"nearest_station":"近鉄山田線 宇治山田駅","station_walk_minutes":25,"capacity_max":60,"hall_count":1,"has_crematorium":True,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":50000}],"features":["公営施設","火葬場併設"],"operator_name":"伊勢市","rating_avg":3.6,"review_count":28},
    {"name":"家族葬のファミーユ伊勢","slug":"mie-famillu-ise","venue_type":"private_hall","description":"伊勢市の家族葬専門ホール。少人数対応の温かい空間です。","address":"三重県伊勢市宮後1-6-22","prefecture_slug":"mie","city_slug":"ise","latitude":34.488,"longitude":136.715,"nearest_station":"近鉄山田線 宇治山田駅","station_walk_minutes":8,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":85000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":285000}],"features":["家族葬対応","少人数対応","低価格"],"operator_name":"家族葬のファミーユ","rating_avg":4.3,"review_count":14},
    {"name":"セレモニーホール伊勢","slug":"mie-ceremony-ise","venue_type":"private_hall","description":"伊勢市小俣エリアのセレモニーホール。温かみのある式場です。","address":"三重県伊勢市小俣町元町688","prefecture_slug":"mie","city_slug":"ise","latitude":34.495,"longitude":136.685,"nearest_station":"JR参宮線 宮川駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":18,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":355000},{"type":"ippanso","label":"一般葬プラン","priceFrom":650000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホール","rating_avg":4.0,"review_count":18},
    # === 名張市 3件 ===
    {"name":"ティア名張","slug":"mie-tier-nabari","venue_type":"private_hall","description":"名張市中心部のティア。近鉄大阪線名張駅から近い便利な立地です。","address":"三重県名張市丸之内35-2","prefecture_slug":"mie","city_slug":"nabari","latitude":34.628,"longitude":136.108,"nearest_station":"近鉄大阪線 名張駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":92000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":340000},{"type":"ippanso","label":"一般葬プラン","priceFrom":640000}],"features":["家族葬対応","駅近"],"operator_name":"ティア","rating_avg":4.1,"review_count":20},
    {"name":"家族葬のファミーユ名張","slug":"mie-famillu-nabari","venue_type":"private_hall","description":"名張市の家族葬専門ホール。少人数対応です。","address":"三重県名張市桔梗が丘5-6-10","prefecture_slug":"mie","city_slug":"nabari","latitude":34.620,"longitude":136.100,"nearest_station":"近鉄大阪線 桔梗が丘駅","station_walk_minutes":5,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":82000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":280000}],"features":["家族葬対応","少人数対応","低価格","駅近"],"operator_name":"家族葬のファミーユ","rating_avg":4.3,"review_count":12},
    {"name":"紫雲殿名張","slug":"mie-shiunden-nabari","venue_type":"private_hall","description":"名張市の紫雲殿。伊賀地域の葬儀を広くサポートしています。","address":"三重県名張市鴻之台1-38","prefecture_slug":"mie","city_slug":"nabari","latitude":34.625,"longitude":136.112,"nearest_station":"近鉄大阪線 名張駅","station_walk_minutes":12,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":18,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":338000},{"type":"ippanso","label":"一般葬プラン","priceFrom":630000}],"features":["家族葬対応"],"operator_name":"紫雲殿","rating_avg":4.0,"review_count":16},
    # === 伊賀市 3件 ===
    {"name":"ティア伊賀","slug":"mie-tier-iga","venue_type":"private_hall","description":"忍者の里・伊賀市の中核斎場。伊賀上野城にほど近い立地です。","address":"三重県伊賀市上野丸之内58-10","prefecture_slug":"mie","city_slug":"iga","latitude":34.769,"longitude":136.131,"nearest_station":"伊賀鉄道 上野市駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":92000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":340000},{"type":"ippanso","label":"一般葬プラン","priceFrom":640000}],"features":["家族葬対応","駅近"],"operator_name":"ティア","rating_avg":4.1,"review_count":18},
    {"name":"家族葬のファミーユ伊賀","slug":"mie-famillu-iga","venue_type":"private_hall","description":"伊賀市の家族葬専門ホール。少人数対応の温かい式場です。","address":"三重県伊賀市平野西町118","prefecture_slug":"mie","city_slug":"iga","latitude":34.772,"longitude":136.125,"nearest_station":"伊賀鉄道 上野市駅","station_walk_minutes":10,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":82000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":280000}],"features":["家族葬対応","少人数対応","低価格"],"operator_name":"家族葬のファミーユ","rating_avg":4.3,"review_count":12},
    {"name":"伊賀市斎場","slug":"mie-iga-saijo","venue_type":"public_crematorium","description":"伊賀市が運営する公営火葬場。市民料金で利用可能です。","address":"三重県伊賀市小田町字堂ノ後1080","prefecture_slug":"mie","city_slug":"iga","latitude":34.765,"longitude":136.140,"nearest_station":"伊賀鉄道 上野市駅","station_walk_minutes":20,"capacity_max":50,"hall_count":1,"has_crematorium":True,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":45000}],"features":["公営施設","火葬場併設"],"operator_name":"伊賀市","rating_avg":3.5,"review_count":20},
    # === 亀山市 2件 ===
    {"name":"ティア亀山","slug":"mie-tier-kameyama","venue_type":"private_hall","description":"亀山市の中核斎場。東名阪自動車道亀山ICに近い便利な立地です。","address":"三重県亀山市東御幸町222","prefecture_slug":"mie","city_slug":"kameyama","latitude":34.855,"longitude":136.452,"nearest_station":"JR関西本線 亀山駅","station_walk_minutes":10,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":92000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":338000},{"type":"ippanso","label":"一般葬プラン","priceFrom":630000}],"features":["家族葬対応","駅近","インター近く"],"operator_name":"ティア","rating_avg":4.1,"review_count":18},
    {"name":"家族葬のファミーユ亀山","slug":"mie-famillu-kameyama","venue_type":"private_hall","description":"亀山市の家族葬専門ホール。少人数対応です。","address":"三重県亀山市栄町542-5","prefecture_slug":"mie","city_slug":"kameyama","latitude":34.852,"longitude":136.448,"nearest_station":"JR関西本線 亀山駅","station_walk_minutes":8,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":82000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":280000}],"features":["家族葬対応","少人数対応","低価格"],"operator_name":"家族葬のファミーユ","rating_avg":4.3,"review_count":10},
    # === いなべ市 2件 ===
    {"name":"ティアいなべ","slug":"mie-tier-inabe","venue_type":"private_hall","description":"いなべ市の中核斎場。北勢エリアの葬儀をサポートしています。","address":"三重県いなべ市北勢町阿下喜330","prefecture_slug":"mie","city_slug":"inabe","latitude":35.148,"longitude":136.560,"nearest_station":"三岐鉄道 阿下喜駅","station_walk_minutes":8,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":18,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":90000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":335000},{"type":"ippanso","label":"一般葬プラン","priceFrom":620000}],"features":["家族葬対応","駅近"],"operator_name":"ティア","rating_avg":4.0,"review_count":14},
    {"name":"家族葬のファミーユいなべ","slug":"mie-famillu-inabe","venue_type":"private_hall","description":"いなべ市の家族葬専門ホール。少人数対応です。","address":"三重県いなべ市員弁町笠田新田185","prefecture_slug":"mie","city_slug":"inabe","latitude":35.120,"longitude":136.565,"nearest_station":"三岐鉄道 楚原駅","station_walk_minutes":10,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":82000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":275000}],"features":["家族葬対応","少人数対応","低価格"],"operator_name":"家族葬のファミーユ","rating_avg":4.2,"review_count":8},
    # === 志摩市 2件 ===
    {"name":"セレモニーホール志摩","slug":"mie-ceremony-shima","venue_type":"private_hall","description":"志摩市の中核斎場。伊勢志摩エリアの葬儀をサポートしています。","address":"三重県志摩市阿児町鵜方1660","prefecture_slug":"mie","city_slug":"shima","latitude":34.328,"longitude":136.820,"nearest_station":"近鉄志摩線 鵜方駅","station_walk_minutes":8,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":18,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":90000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":335000},{"type":"ippanso","label":"一般葬プラン","priceFrom":620000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホール","rating_avg":4.0,"review_count":14},
    {"name":"家族葬のファミーユ志摩","slug":"mie-famillu-shima","venue_type":"private_hall","description":"志摩市の家族葬専門ホール。少人数対応です。","address":"三重県志摩市阿児町神明746","prefecture_slug":"mie","city_slug":"shima","latitude":34.325,"longitude":136.825,"nearest_station":"近鉄志摩線 鵜方駅","station_walk_minutes":10,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":82000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":278000}],"features":["家族葬対応","少人数対応","低価格"],"operator_name":"家族葬のファミーユ","rating_avg":4.2,"review_count":8},
    # === 鳥羽市 2件 ===
    {"name":"セレモニーホール鳥羽","slug":"mie-ceremony-toba","venue_type":"private_hall","description":"鳥羽市の中核斎場。鳥羽水族館にも近い立地です。","address":"三重県鳥羽市大明東町16-8","prefecture_slug":"mie","city_slug":"toba","latitude":34.482,"longitude":136.842,"nearest_station":"近鉄鳥羽線 鳥羽駅","station_walk_minutes":8,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":90000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":335000},{"type":"ippanso","label":"一般葬プラン","priceFrom":620000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホール","rating_avg":4.0,"review_count":12},
    {"name":"家族葬のファミーユ鳥羽","slug":"mie-famillu-toba","venue_type":"private_hall","description":"鳥羽市の家族葬専門ホール。少人数対応です。","address":"三重県鳥羽市安楽島町1075-12","prefecture_slug":"mie","city_slug":"toba","latitude":34.480,"longitude":136.850,"nearest_station":"近鉄鳥羽線 鳥羽駅","station_walk_minutes":12,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":82000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":275000}],"features":["家族葬対応","少人数対応","低価格"],"operator_name":"家族葬のファミーユ","rating_avg":4.2,"review_count":8},
    # === 尾鷲市 2件 ===
    {"name":"セレモニーホール尾鷲","slug":"mie-ceremony-owase","venue_type":"private_hall","description":"尾鷲市の中核斎場。紀北エリアの葬儀をサポートしています。","address":"三重県尾鷲市中村町10-30","prefecture_slug":"mie","city_slug":"owase","latitude":34.072,"longitude":136.192,"nearest_station":"JR紀勢本線 尾鷲駅","station_walk_minutes":8,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":88000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":330000},{"type":"ippanso","label":"一般葬プラン","priceFrom":610000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホール","rating_avg":4.0,"review_count":10},
    {"name":"尾鷲市斎場","slug":"mie-owase-saijo","venue_type":"public_crematorium","description":"尾鷲市が運営する公営火葬場。市民料金で利用できます。","address":"三重県尾鷲市南浦字大間3560","prefecture_slug":"mie","city_slug":"owase","latitude":34.065,"longitude":136.195,"nearest_station":"JR紀勢本線 尾鷲駅","station_walk_minutes":15,"capacity_max":40,"hall_count":1,"has_crematorium":True,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":40000}],"features":["公営施設","火葬場併設"],"operator_name":"尾鷲市","rating_avg":3.5,"review_count":12},
    # === 熊野市 2件 ===
    {"name":"セレモニーホール熊野","slug":"mie-ceremony-kumano","venue_type":"private_hall","description":"熊野市の中核斎場。世界遺産・熊野古道のお膝元の式場です。","address":"三重県熊野市井戸町708","prefecture_slug":"mie","city_slug":"kumano","latitude":33.888,"longitude":136.098,"nearest_station":"JR紀勢本線 熊野市駅","station_walk_minutes":8,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":85000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":325000},{"type":"ippanso","label":"一般葬プラン","priceFrom":600000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホール","rating_avg":4.0,"review_count":10},
    {"name":"家族葬のファミーユ熊野","slug":"mie-famillu-kumano","venue_type":"private_hall","description":"熊野市の家族葬専門ホール。少人数対応です。","address":"三重県熊野市木本町字川原545","prefecture_slug":"mie","city_slug":"kumano","latitude":33.890,"longitude":136.100,"nearest_station":"JR紀勢本線 熊野市駅","station_walk_minutes":5,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":80000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":270000}],"features":["家族葬対応","少人数対応","低価格","駅近"],"operator_name":"家族葬のファミーユ","rating_avg":4.2,"review_count":8},
]

for i in range(0, len(venues), 10):
    batch = venues[i:i+10]
    code = insert_batch(batch)
    print(f"バッチ {i//10+1}: {code} ({len(batch)}件)")
    time.sleep(1)

print(f"\n完了: 合計 {len(venues)} 件")
