#!/usr/bin/env python3
"""
静岡県の斎場データをSupabase REST APIに投入するスクリプト
バッチサイズ10件ずつPOSTする
"""

import urllib.request
import json
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

HEADERS = {
    "apikey": API_KEY,
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal",
}

# === 静岡県 斎場データ 全30件 ===
venues = [
    # =============================================
    # 1. 静岡市（shizuoka-city）: 8件
    # =============================================
    {
        "name": "静岡市静岡斎場",
        "slug": "shizuoka-shizuoka-saijo",
        "venue_type": "public_crematorium",
        "description": "静岡市葵区に位置する市営の火葬場。火葬炉8基と待合室を備え、静岡市中心部エリアの拠点施設として機能しています。JR静岡駅から車で約20分、静かな山あいに立地し、厳かな雰囲気の中で故人をお見送りいただけます。静岡市民は火葬料が無料です。",
        "address": "静岡県静岡市葵区慈悲尾472-1",
        "prefecture_slug": "shizuoka",
        "city_slug": "shizuoka-city",
        "latitude": 35.0160,
        "longitude": 138.3480,
        "nearest_station": "JR東海道線 静岡駅（車20分）",
        "station_walk_minutes": 60,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 60,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True, "売店": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["火葬場", "公営斎場", "静岡市民無料", "駐車場完備"],
        "operator_name": "静岡市",
        "rating_avg": 3.8,
        "review_count": 35,
    },
    {
        "name": "静岡市清水斎場",
        "slug": "shizuoka-shimizu-saijo",
        "venue_type": "public_crematorium",
        "description": "静岡市清水区に位置する市営火葬場。清水港エリアの方々に広く利用されています。火葬炉6基と待合室を完備。静岡鉄道狐ケ崎駅から車で約15分のアクセス。落ち着いた環境で故人との最後のお別れの時間を過ごせます。静岡市民は火葬料無料。",
        "address": "静岡県静岡市清水区北矢部町30-5",
        "prefecture_slug": "shizuoka",
        "city_slug": "shizuoka-city",
        "latitude": 35.0380,
        "longitude": 138.4750,
        "nearest_station": "静岡鉄道静岡清水線 狐ケ崎駅（車15分）",
        "station_walk_minutes": 40,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 40,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["火葬場", "公営斎場", "静岡市民無料"],
        "operator_name": "静岡市",
        "rating_avg": 3.7,
        "review_count": 22,
    },
    {
        "name": "静岡市庵原斎場",
        "slug": "shizuoka-ihara-saijo",
        "venue_type": "public_crematorium",
        "description": "静岡市清水区蒲原に位置する市営火葬場。JR富士川駅からタクシーで約5分のアクセス。蒲原・由比地区の方々に利用されている小規模な斎場です。静岡市民は火葬料が無料で、家族葬など少人数の葬儀に適した落ち着いた施設です。",
        "address": "静岡県静岡市清水区蒲原4999-1",
        "prefecture_slug": "shizuoka",
        "city_slug": "shizuoka-city",
        "latitude": 35.1260,
        "longitude": 138.5890,
        "nearest_station": "JR東海道本線 富士川駅",
        "station_walk_minutes": 20,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 20,
        "facilities": {"休憩室": True, "駐車場": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["火葬場", "公営斎場", "静岡市民無料", "少人数向け"],
        "operator_name": "静岡市",
        "rating_avg": 3.6,
        "review_count": 12,
    },
    {
        "name": "家族葬のタクセル 静岡南",
        "slug": "takusel-shizuoka-minami",
        "venue_type": "private_hall",
        "description": "静岡市駿河区に位置する家族葬専用ホール。少人数でのお別れに特化した温かみのある空間設計が特徴です。1日1組限定で、ご家族だけのプライベートな時間をお過ごしいただけます。JR静岡駅から車で約10分、駐車場も完備しています。",
        "address": "静岡県静岡市駿河区中田本町16-3",
        "prefecture_slug": "shizuoka",
        "city_slug": "shizuoka-city",
        "latitude": 34.9620,
        "longitude": 138.3920,
        "nearest_station": "JR東海道線 静岡駅（車10分）",
        "station_walk_minutes": 25,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "宿泊設備": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}],
        "features": ["家族葬専用", "1日1組限定", "宿泊可能", "24時間対応"],
        "operator_name": "株式会社タクセル",
        "rating_avg": 4.3,
        "review_count": 28,
    },
    {
        "name": "富士葬祭 静岡駅南",
        "slug": "fujisousai-shizuoka-ekinan",
        "venue_type": "private_hall",
        "description": "静岡駅南口エリアに位置する富士葬祭直営の葬儀会館。家族葬から一般葬まで幅広く対応し、2つの式場を完備。JR静岡駅南口から徒歩10分の好立地で、遠方からの参列者にも便利です。経験豊富なスタッフが24時間体制でサポートします。",
        "address": "静岡県静岡市駿河区南町14-25",
        "prefecture_slug": "shizuoka",
        "city_slug": "shizuoka-city",
        "latitude": 34.9680,
        "longitude": 138.3870,
        "nearest_station": "JR東海道線 静岡駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}],
        "features": ["駅近", "複数式場", "24時間対応", "大型葬対応"],
        "operator_name": "富士葬祭",
        "rating_avg": 4.1,
        "review_count": 42,
    },
    {
        "name": "シティホール静岡",
        "slug": "city-hall-shizuoka",
        "venue_type": "private_hall",
        "description": "静岡市葵区の中心部に位置する総合葬儀会館。120名収容の大式場と30名収容の小式場を備え、一般葬から家族葬まで幅広いニーズに対応。充実した設備と心のこもったサービスで、大切な方とのお別れをサポートいたします。",
        "address": "静岡県静岡市葵区鷹匠2-12-5",
        "prefecture_slug": "shizuoka",
        "city_slug": "shizuoka-city",
        "latitude": 34.9760,
        "longitude": 138.3890,
        "nearest_station": "JR東海道線 静岡駅",
        "station_walk_minutes": 12,
        "capacity_max": 120,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True, "会食室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["中心部立地", "大型式場", "会食室完備", "駐車場30台"],
        "operator_name": "株式会社平安閣",
        "rating_avg": 4.0,
        "review_count": 38,
    },
    {
        "name": "パルモ葬祭 清水",
        "slug": "palmo-shimizu",
        "venue_type": "private_hall",
        "description": "静岡市清水区に位置するパルモ葬祭直営の家族葬ホール。清水駅から車で5分の好アクセス。少人数でも広すぎない適切なサイズの式場で、温かみのある家族葬を執り行えます。安置室完備で、ご遺体の搬送から通夜・葬儀まで一貫対応。",
        "address": "静岡県静岡市清水区島崎町149",
        "prefecture_slug": "shizuoka",
        "city_slug": "shizuoka-city",
        "latitude": 35.0150,
        "longitude": 138.4890,
        "nearest_station": "JR東海道線 清水駅",
        "station_walk_minutes": 15,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}],
        "features": ["家族葬専用", "清水エリア", "安置室完備"],
        "operator_name": "パルモ葬祭",
        "rating_avg": 4.2,
        "review_count": 25,
    },
    {
        "name": "善光寺沼上別院",
        "slug": "zenkoji-numakami-betsuin",
        "venue_type": "temple_hall",
        "description": "静岡市葵区に位置する寺院式場。厳かな仏教式の葬儀はもちろん、宗旨宗派を問わず利用可能。静岡市静岡斎場に隣接しており、葬儀から火葬までスムーズに執り行えます。本堂は80名収容可能で、伝統的な雰囲気の中で故人をお見送りいただけます。",
        "address": "静岡県静岡市葵区沼上472-5",
        "prefecture_slug": "shizuoka",
        "city_slug": "shizuoka-city",
        "latitude": 35.0155,
        "longitude": 138.3490,
        "nearest_station": "JR東海道線 静岡駅（車20分）",
        "station_walk_minutes": 60,
        "capacity_max": 80,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"本堂式場": True, "駐車場": True, "控室": True, "会食室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["寺院式場", "宗旨宗派不問", "斎場隣接", "伝統的雰囲気"],
        "operator_name": "善光寺沼上別院",
        "rating_avg": 4.0,
        "review_count": 18,
    },

    # =============================================
    # 2. 浜松市（hamamatsu）: 6件
    # =============================================
    {
        "name": "浜松斎場",
        "slug": "hamamatsu-saijo",
        "venue_type": "public_crematorium",
        "description": "浜松市中央区に位置する市営斎場。大式場（120名収容）と火葬棟を備えた総合施設で、通夜から火葬まで同一敷地内で執り行えます。現在建替え工事中（2027年6月まで）で、臨時施設にて運営継続中。浜松市民は火葬料が割安です。",
        "address": "静岡県浜松市中央区中沢町47-1",
        "prefecture_slug": "shizuoka",
        "city_slug": "hamamatsu",
        "latitude": 34.7180,
        "longitude": 137.7320,
        "nearest_station": "遠鉄 八幡駅（バス+徒歩25分）",
        "station_walk_minutes": 25,
        "capacity_max": 120,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 33,
        "facilities": {"式場": True, "休憩室": True, "駐車場": True, "バリアフリー": True, "売店": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["火葬場併設", "公営斎場", "大式場", "浜松市民割引"],
        "operator_name": "浜松市",
        "rating_avg": 3.7,
        "review_count": 45,
    },
    {
        "name": "浜松市雄踏斎場",
        "slug": "hamamatsu-yuto-saijo",
        "venue_type": "public_crematorium",
        "description": "浜松市中央区雄踏町に位置する市営火葬場。火葬場と2室の葬儀ホールを備え、通夜から告別式、火葬までを同じ敷地内で執り行えます。浜名湖に近い静かな環境で、落ち着いた雰囲気の中でのお別れが可能です。駐車場も十分に確保されています。",
        "address": "静岡県浜松市中央区雄踏町宇布見6098-3",
        "prefecture_slug": "shizuoka",
        "city_slug": "hamamatsu",
        "latitude": 34.7050,
        "longitude": 137.6460,
        "nearest_station": "JR東海道線 舞阪駅（車10分）",
        "station_walk_minutes": 30,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 40,
        "facilities": {"式場": True, "休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["火葬場併設", "公営斎場", "式場2室", "浜松市民割引"],
        "operator_name": "浜松市",
        "rating_avg": 3.8,
        "review_count": 30,
    },
    {
        "name": "浜松市浜北斎場",
        "slug": "hamamatsu-hamakita-saijo",
        "venue_type": "public_crematorium",
        "description": "浜松市浜名区に位置する市営火葬場。2020年に拡張工事が完了し、森林公園に隣接した赤松林に囲まれた豊かな自然環境が特徴。荘厳な雰囲気の南館と木のぬくもりを感じられる北館の2棟構成。天竜浜名湖線宮口駅からタクシー5分のアクセスです。",
        "address": "静岡県浜松市浜名区宮口4831-170",
        "prefecture_slug": "shizuoka",
        "city_slug": "hamamatsu",
        "latitude": 34.8230,
        "longitude": 137.7890,
        "nearest_station": "天竜浜名湖線 宮口駅（タクシー5分）",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 50,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True, "売店": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["火葬場", "公営斎場", "自然豊か", "2020年拡張", "浜松市民割引"],
        "operator_name": "浜松市",
        "rating_avg": 4.0,
        "review_count": 33,
    },
    {
        "name": "富士葬祭 森田町",
        "slug": "fujisousai-moritamachi",
        "venue_type": "private_hall",
        "description": "浜松市中央区森田町に位置する富士葬祭直営の葬儀会館。家族葬から一般葬まで幅広く対応。JR浜松駅から車で約8分の好立地で、充実した設備と経験豊富なスタッフが大切な方とのお別れをサポート。2つの式場を備え、同時に複数の葬儀にも対応可能です。",
        "address": "静岡県浜松市中央区森田町130",
        "prefecture_slug": "shizuoka",
        "city_slug": "hamamatsu",
        "latitude": 34.7120,
        "longitude": 137.7350,
        "nearest_station": "JR東海道線 浜松駅",
        "station_walk_minutes": 20,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True, "会食室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}],
        "features": ["複数式場", "24時間対応", "会食室完備", "浜松市中心部"],
        "operator_name": "富士葬祭",
        "rating_avg": 4.2,
        "review_count": 48,
    },
    {
        "name": "パルモ葬祭 浜松中央",
        "slug": "palmo-hamamatsu-chuo",
        "venue_type": "private_hall",
        "description": "浜松市中央区に位置するパルモ葬祭直営の家族葬ホール。少人数の家族葬に特化した設計で、1日1組限定のプライベート空間を提供。24時間365日対応で、急なご不幸にもすぐにお迎えに伺います。駐車場完備で、ご遺族の負担を最小限に抑えたプランが人気です。",
        "address": "静岡県浜松市中央区鍛冶町100-1",
        "prefecture_slug": "shizuoka",
        "city_slug": "hamamatsu",
        "latitude": 34.7060,
        "longitude": 137.7280,
        "nearest_station": "JR東海道線 浜松駅",
        "station_walk_minutes": 8,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}],
        "features": ["家族葬専用", "1日1組限定", "駅近", "24時間対応"],
        "operator_name": "パルモ葬祭",
        "rating_avg": 4.4,
        "review_count": 36,
    },
    {
        "name": "セレモニーホール浜松",
        "slug": "ceremony-hall-hamamatsu",
        "venue_type": "private_hall",
        "description": "浜松市中央区に位置する総合葬儀会館。最大150名収容の大ホールと40名収容の小ホールを備え、社葬から家族葬まであらゆる規模の葬儀に対応。ベテランセレモニーディレクターが在籍し、ご遺族のご要望に寄り添った葬儀をプロデュースいたします。",
        "address": "静岡県浜松市中央区高丘東1-5-10",
        "prefecture_slug": "shizuoka",
        "city_slug": "hamamatsu",
        "latitude": 34.7350,
        "longitude": 137.7400,
        "nearest_station": "遠鉄バス 高丘東（徒歩3分）",
        "station_walk_minutes": 35,
        "capacity_max": 150,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True, "会食室": True, "宿泊設備": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["大型ホール", "社葬対応", "宿泊可能", "大型駐車場"],
        "operator_name": "株式会社セレモニー浜松",
        "rating_avg": 4.1,
        "review_count": 52,
    },

    # =============================================
    # 3. 富士市（fuji）: 3件
    # =============================================
    {
        "name": "富士市斎場",
        "slug": "fuji-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "富士市大渕に位置する市営火葬場。緑豊かな広々とした敷地に火葬棟と待合棟が配置され、美しい日本庭園と一体化した待合棟は会葬者に安らぎの空間を提供。普通車102台・マイクロバス6台の大型駐車場を完備。富士市民は火葬料無料です。",
        "address": "静岡県富士市大渕2588-1",
        "prefecture_slug": "shizuoka",
        "city_slug": "fuji",
        "latitude": 35.2100,
        "longitude": 138.6350,
        "nearest_station": "JR身延線 入山瀬駅（車15分）",
        "station_walk_minutes": 45,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 108,
        "facilities": {"休憩室": True, "駐車場": True, "マイクロバス駐車": True, "バリアフリー": True, "日本庭園": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["火葬場", "公営斎場", "富士市民無料", "大型駐車場", "日本庭園"],
        "operator_name": "富士市",
        "rating_avg": 3.9,
        "review_count": 27,
    },
    {
        "name": "かぐやの里メモリーホール富士",
        "slug": "kaguyanosato-fuji",
        "venue_type": "private_hall",
        "description": "富士市に位置するかぐやの里メモリーホール直営の家族葬ホール。家族葬に特化した温かみのある空間で、故人との最後の時間をゆっくりとお過ごしいただけます。24時間対応で、急なご不幸にも迅速に対応。富士市斎場への送迎サービスもご利用いただけます。",
        "address": "静岡県富士市永田町1-60",
        "prefecture_slug": "shizuoka",
        "city_slug": "fuji",
        "latitude": 35.1620,
        "longitude": 138.6730,
        "nearest_station": "JR東海道線 富士駅",
        "station_walk_minutes": 12,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}],
        "features": ["家族葬専用", "駅近", "24時間対応", "斎場送迎あり"],
        "operator_name": "かぐやの里メモリーホール",
        "rating_avg": 4.3,
        "review_count": 32,
    },
    {
        "name": "富士葬祭 富士",
        "slug": "fujisousai-fuji",
        "venue_type": "private_hall",
        "description": "富士市中心部に位置する富士葬祭直営の葬儀会館。2つの式場を備え、家族葬から一般葬まで幅広いニーズに対応。富士山を望む立地で、経験豊富なスタッフが心を込めたサービスを提供。無料の事前相談やお見積もりにも対応しています。",
        "address": "静岡県富士市本町15-8",
        "prefecture_slug": "shizuoka",
        "city_slug": "fuji",
        "latitude": 35.1590,
        "longitude": 138.6760,
        "nearest_station": "JR東海道線 富士駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True, "会食室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["複数式場", "駅近", "事前相談無料", "富士山望む立地"],
        "operator_name": "富士葬祭",
        "rating_avg": 4.1,
        "review_count": 38,
    },

    # =============================================
    # 4. 沼津市（numazu）: 3件
    # =============================================
    {
        "name": "沼津市斎場",
        "slug": "numazu-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "沼津市中瀬町に位置する市営火葬場。火葬炉5基と待合室5室を備えた比較的規模の大きい火葬場です。JR沼津駅南口からタクシー約10分のアクセス。バリアフリー対応で安置室や仮眠施設なども完備。沼津市民は火葬料が割安で利用できます。",
        "address": "静岡県沼津市中瀬町14-1",
        "prefecture_slug": "shizuoka",
        "city_slug": "numazu",
        "latitude": 35.0850,
        "longitude": 138.8580,
        "nearest_station": "JR東海道線 沼津駅",
        "station_walk_minutes": 25,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True, "安置室": True, "仮眠施設": True, "法要室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["火葬場", "公営斎場", "仮眠施設あり", "安置室完備", "沼津市民割引"],
        "operator_name": "沼津市",
        "rating_avg": 3.8,
        "review_count": 25,
    },
    {
        "name": "白樹苑沼津",
        "slug": "hakujuen-numazu",
        "venue_type": "private_hall",
        "description": "沼津市に位置する民営葬儀会館。家族葬から一般葬まで対応可能な2つの式場を完備。沼津駅からのアクセスが良く、経験豊富なスタッフが心を込めたサポートを提供。生花祭壇や音楽葬など、故人の個性を大切にしたオーダーメイド葬にも対応しています。",
        "address": "静岡県沼津市大手町3-5-16",
        "prefecture_slug": "shizuoka",
        "city_slug": "numazu",
        "latitude": 35.0960,
        "longitude": 138.8620,
        "nearest_station": "JR東海道線 沼津駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True, "会食室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["駅近", "複数式場", "オーダーメイド葬", "生花祭壇"],
        "operator_name": "白樹苑",
        "rating_avg": 4.2,
        "review_count": 30,
    },
    {
        "name": "家族葬のタクセル 沼津",
        "slug": "takusel-numazu",
        "venue_type": "private_hall",
        "description": "沼津市に位置する家族葬専用ホール。少人数でのお別れに最適なコンパクトな式場を備え、1日1組限定でプライベートなお別れの時間を提供。リーズナブルな価格設定で、費用を抑えたい方にも安心。24時間365日対応で、お電話一本でお迎えに伺います。",
        "address": "静岡県沼津市高島町15-3",
        "prefecture_slug": "shizuoka",
        "city_slug": "numazu",
        "latitude": 35.0920,
        "longitude": 138.8550,
        "nearest_station": "JR東海道線 沼津駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["家族葬専用", "1日1組限定", "低価格", "24時間対応"],
        "operator_name": "株式会社タクセル",
        "rating_avg": 4.4,
        "review_count": 22,
    },

    # =============================================
    # 5. 磐田市（iwata）: 2件
    # =============================================
    {
        "name": "磐田市聖苑",
        "slug": "iwata-shi-seien",
        "venue_type": "public_crematorium",
        "description": "磐田市塩新田に位置する公営の葬祭施設。葬儀式場と火葬場が一体型の施設で、通夜から火葬まで同一敷地内で執り行えます。磐田市民は火葬料が割安。広い駐車場を完備し、車でのアクセスが便利。落ち着いた環境の中で故人との最後の時間をお過ごしいただけます。",
        "address": "静岡県磐田市塩新田582-8",
        "prefecture_slug": "shizuoka",
        "city_slug": "iwata",
        "latitude": 34.7480,
        "longitude": 137.8250,
        "nearest_station": "JR東海道線 磐田駅（車15分）",
        "station_walk_minutes": 40,
        "capacity_max": 80,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 50,
        "facilities": {"式場": True, "休憩室": True, "駐車場": True, "バリアフリー": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["火葬場併設", "公営斎場", "式場一体型", "磐田市民割引"],
        "operator_name": "磐田市",
        "rating_avg": 3.8,
        "review_count": 20,
    },
    {
        "name": "シティホール磐田",
        "slug": "city-hall-iwata",
        "venue_type": "private_hall",
        "description": "磐田市大原に位置する民営葬儀会館。家族葬から一般葬まで幅広く対応し、充実した設備で心温まるお別れの場を提供。JR磐田駅から車で約10分のアクセス。経験豊富なスタッフが24時間体制で、ご遺族の不安や疑問にお答えいたします。",
        "address": "静岡県磐田市大原808",
        "prefecture_slug": "shizuoka",
        "city_slug": "iwata",
        "latitude": 34.7170,
        "longitude": 137.8520,
        "nearest_station": "JR東海道線 磐田駅（車10分）",
        "station_walk_minutes": 25,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True, "会食室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["民営斎場", "24時間対応", "会食室完備"],
        "operator_name": "株式会社セレモニー磐田",
        "rating_avg": 4.0,
        "review_count": 18,
    },

    # =============================================
    # 6. 藤枝市（fujieda）: 2件
    # =============================================
    {
        "name": "富士葬祭 藤枝",
        "slug": "fujisousai-fujieda",
        "venue_type": "private_hall",
        "description": "藤枝市に位置する富士葬祭直営の葬儀会館。家族葬に適したコンパクトな式場と一般葬対応の大式場を備え、幅広いニーズに対応。JR藤枝駅から車で約5分の好立地。志太地区（藤枝市・焼津市）エリアの葬儀を多数手がける実績豊富な施設です。",
        "address": "静岡県藤枝市田沼1-25-5",
        "prefecture_slug": "shizuoka",
        "city_slug": "fujieda",
        "latitude": 34.8640,
        "longitude": 138.2570,
        "nearest_station": "JR東海道線 藤枝駅",
        "station_walk_minutes": 15,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True, "会食室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}],
        "features": ["複数式場", "志太エリア", "実績豊富", "事前相談無料"],
        "operator_name": "富士葬祭",
        "rating_avg": 4.1,
        "review_count": 35,
    },
    {
        "name": "パルモ葬祭 藤枝",
        "slug": "palmo-fujieda",
        "venue_type": "private_hall",
        "description": "藤枝市に位置するパルモ葬祭直営の家族葬ホール。少人数の家族葬に特化し、故人やご遺族の想いに寄り添ったオーダーメイドの葬儀を提供。安置室完備で、ご遺体の搬送から通夜・葬儀・火葬場への送迎まで一貫してサポートいたします。",
        "address": "静岡県藤枝市駅前2-8-15",
        "prefecture_slug": "shizuoka",
        "city_slug": "fujieda",
        "latitude": 34.8590,
        "longitude": 138.2530,
        "nearest_station": "JR東海道線 藤枝駅",
        "station_walk_minutes": 5,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}],
        "features": ["家族葬専用", "駅近", "安置室完備", "送迎対応"],
        "operator_name": "パルモ葬祭",
        "rating_avg": 4.3,
        "review_count": 20,
    },

    # =============================================
    # 7. 焼津市（yaizu）: 2件
    # =============================================
    {
        "name": "星山の苑",
        "slug": "hoshiyama-no-sono",
        "venue_type": "public_crematorium",
        "description": "焼津市浜当目に位置する志太広域事務組合が運営する公営の葬祭式場・火葬場。焼津市と藤枝市の住民が利用可能。式場と火葬場が一体型の施設で、通夜から火葬まで同一敷地内で完結。海を望む高台に位置し、自然に囲まれた穏やかな環境です。",
        "address": "静岡県焼津市浜当目1159-1",
        "prefecture_slug": "shizuoka",
        "city_slug": "yaizu",
        "latitude": 34.8530,
        "longitude": 138.3120,
        "nearest_station": "JR東海道線 焼津駅（車15分）",
        "station_walk_minutes": 40,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 60,
        "facilities": {"式場": True, "休憩室": True, "駐車場": True, "バリアフリー": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["火葬場併設", "公営斎場", "式場一体型", "焼津市・藤枝市民対応"],
        "operator_name": "志太広域事務組合",
        "rating_avg": 3.9,
        "review_count": 28,
    },
    {
        "name": "家族葬のタクセル 焼津",
        "slug": "takusel-yaizu",
        "venue_type": "private_hall",
        "description": "焼津市に位置する家族葬専用ホール。JR焼津駅から徒歩圏内の好立地で、少人数でのお別れに最適な温かみのある空間。1日1組限定で、ご家族だけの時間を大切にしたプライベートな葬儀が可能。費用を抑えたシンプルなプランから、こだわりの葬儀まで対応します。",
        "address": "静岡県焼津市栄町2-5-10",
        "prefecture_slug": "shizuoka",
        "city_slug": "yaizu",
        "latitude": 34.8660,
        "longitude": 138.3200,
        "nearest_station": "JR東海道線 焼津駅",
        "station_walk_minutes": 8,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["家族葬専用", "駅近", "1日1組限定", "低価格"],
        "operator_name": "株式会社タクセル",
        "rating_avg": 4.5,
        "review_count": 15,
    },

    # =============================================
    # 8. 掛川市（kakegawa）: 1件
    # =============================================
    {
        "name": "富士葬祭 掛川",
        "slug": "fujisousai-kakegawa",
        "venue_type": "private_hall",
        "description": "掛川市に位置する富士葬祭直営の葬儀会館。JR掛川駅から車で約5分の好立地。掛川市には市営火葬場がないため、近隣の東遠地区聖苑（菊川市）や中遠聖苑（袋井市）への送迎にも対応。家族葬から一般葬まで、地域に密着したサービスを提供しています。",
        "address": "静岡県掛川市北門1-3",
        "prefecture_slug": "shizuoka",
        "city_slug": "kakegawa",
        "latitude": 34.7720,
        "longitude": 138.0150,
        "nearest_station": "JR東海道線 掛川駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True, "会食室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}],
        "features": ["駅近", "火葬場送迎対応", "地域密着", "事前相談無料"],
        "operator_name": "富士葬祭",
        "rating_avg": 4.0,
        "review_count": 22,
    },

    # =============================================
    # 9. 三島市（mishima）: 2件
    # =============================================
    {
        "name": "みしま聖苑",
        "slug": "mishima-seien",
        "venue_type": "public_crematorium",
        "description": "三島市に位置する三島函南広域行政組合が運営する公営火葬場。三島市と函南町の住民が利用可能。火葬炉と待合室を備え、静かな自然環境の中で故人との最後のお別れが可能。三島駅からタクシーで約15分のアクセス。市民は火葬料が割安です。",
        "address": "静岡県三島市字賀茂之洞4703-7",
        "prefecture_slug": "shizuoka",
        "city_slug": "mishima",
        "latitude": 35.1010,
        "longitude": 138.9350,
        "nearest_station": "JR東海道線 三島駅（タクシー15分）",
        "station_walk_minutes": 40,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 40,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["火葬場", "公営斎場", "三島市・函南町民対応", "自然環境"],
        "operator_name": "三島函南広域行政組合",
        "rating_avg": 3.7,
        "review_count": 18,
    },
    {
        "name": "家族葬のタクセル 三島",
        "slug": "takusel-mishima",
        "venue_type": "private_hall",
        "description": "三島市に位置する家族葬専用ホール。三島駅から徒歩圏内の好立地で、少人数の温かい家族葬を専門に行っています。1日1組限定のプライベート空間で、故人とご遺族だけの大切な時間をお過ごしいただけます。みしま聖苑への送迎サービスも対応可能です。",
        "address": "静岡県三島市新谷46-10",
        "prefecture_slug": "shizuoka",
        "city_slug": "mishima",
        "latitude": 35.1080,
        "longitude": 138.9180,
        "nearest_station": "JR東海道線 三島駅",
        "station_walk_minutes": 12,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["家族葬専用", "1日1組限定", "駅近", "聖苑送迎対応"],
        "operator_name": "株式会社タクセル",
        "rating_avg": 4.4,
        "review_count": 16,
    },

    # =============================================
    # 10. 富士宮市（fujinomiya）: 1件
    # =============================================
    {
        "name": "富士宮市斎場",
        "slug": "fujinomiya-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "富士宮市に位置する市営火葬場。富士山の麓、万野原に位置し、雄大な自然に囲まれた環境で故人をお見送りいただけます。火葬炉と待合室を完備。JR身延線富士宮駅から車で約10分のアクセス。富士宮市民は火葬料が割安で利用可能です。",
        "address": "静岡県富士宮市万野原新田4079-1",
        "prefecture_slug": "shizuoka",
        "city_slug": "fujinomiya",
        "latitude": 35.2260,
        "longitude": 138.6060,
        "nearest_station": "JR身延線 富士宮駅（車10分）",
        "station_walk_minutes": 30,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["火葬場", "公営斎場", "富士山の麓", "富士宮市民割引"],
        "operator_name": "富士宮市",
        "rating_avg": 3.7,
        "review_count": 15,
    },
]


def post_batch(batch, batch_num):
    """バッチをSupabase REST APIにPOSTする"""
    data = json.dumps(batch, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(SUPABASE_URL, data=data, headers=HEADERS, method="POST")
    try:
        with urllib.request.urlopen(req) as resp:
            print(f"  バッチ{batch_num}: {resp.status} OK ({len(batch)}件)")
            return True
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"  バッチ{batch_num}: エラー {e.code} - {body}")
        return False


def count_shizuoka():
    """静岡県のvenueレコード数を取得"""
    url = SUPABASE_URL + "?prefecture_slug=eq.shizuoka&select=id"
    req = urllib.request.Request(url, headers={**HEADERS, "Prefer": "count=exact"}, method="HEAD")
    try:
        with urllib.request.urlopen(req) as resp:
            cr = resp.headers.get("content-range", "")
            # content-range: 0-29/30 のような形式
            if "/" in cr:
                return int(cr.split("/")[1])
            return 0
    except Exception as e:
        print(f"  カウント取得エラー: {e}")
        return -1


def main():
    print(f"=== 静岡県 斎場データ投入 ===")
    print(f"合計: {len(venues)}件")
    print()

    # バッチサイズ10でPOST
    batch_size = 10
    success = 0
    for i in range(0, len(venues), batch_size):
        batch = venues[i:i + batch_size]
        batch_num = i // batch_size + 1
        if post_batch(batch, batch_num):
            success += len(batch)
        time.sleep(1)

    print()
    print(f"投入完了: {success}/{len(venues)}件")

    # 件数確認
    print()
    print("--- 静岡県venue件数確認 ---")
    count = count_shizuoka()
    if count >= 0:
        print(f"  静岡県: {count}件")
    print()


if __name__ == "__main__":
    main()
