#!/usr/bin/env python3
"""
宮城県の斎場データ Part1: 仙台市 前半40件
バッチサイズ10件ずつPOSTする
"""

import urllib.request
import json
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

HEADERS = {
    "apikey": API_KEY,
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal",
    "User-Agent": "Mozilla/5.0",
}

venues = [
    # =============================================
    # 仙台市青葉区（16件）
    # =============================================
    {
        "name": "仙台市葛岡斎場",
        "slug": "miyagi-sendai-kuzuoka-saijo",
        "venue_type": "public_crematorium",
        "description": "仙台市青葉区に位置する市営火葬場。火葬炉16基を備え、仙台市民の火葬を一手に担う基幹施設です。式場2室を併設し、通夜・告別式から火葬まで同一施設内で執り行えます。仙台市民は割安料金で利用可能。大型駐車場を完備しています。",
        "address": "宮城県仙台市青葉区郷六字葛岡25",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2690,
        "longitude": 140.8180,
        "nearest_station": "JR仙山線 葛岡駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 120,
        "facilities": {"式場": True, "休憩室": True, "駐車場": True, "バリアフリー": True, "売店": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}],
        "features": ["火葬場", "公営斎場", "仙台市民割引", "式場併設", "大型駐車場"],
        "operator_name": "仙台市",
        "rating_avg": 3.9,
        "review_count": 52,
    },
    {
        "name": "清月記 本館",
        "slug": "miyagi-seigetuki-honkan",
        "venue_type": "private_hall",
        "description": "仙台最大手の葬儀社「清月記」の本館。仙台市青葉区中心部に位置し、家族葬から大規模な一般葬まで幅広く対応。格式高い式場と充実した設備が特徴で、年間3,000件以上の葬儀実績を誇ります。24時間対応の相談窓口も完備。",
        "address": "宮城県仙台市青葉区中央2-5-10",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2600,
        "longitude": 140.8720,
        "nearest_station": "JR仙台駅",
        "station_walk_minutes": 8,
        "capacity_max": 200,
        "hall_count": 4,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True, "24時間対応": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 698000},
        ],
        "features": ["仙台最大手", "24時間対応", "家族葬対応", "大規模葬対応", "駅近"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.3,
        "review_count": 145,
    },
    {
        "name": "清月記 北山ホール",
        "slug": "miyagi-seigetuki-kitayama",
        "venue_type": "private_hall",
        "description": "仙台市青葉区北山エリアに位置する清月記の斎場。閑静な住宅街にあり、落ち着いた雰囲気の中でお別れの時間を過ごせます。家族葬専用の小規模ホールと一般葬対応の大ホールを備え、ご要望に合わせた葬儀プランを提供。北山五山の寺院群にも近く、菩提寺との連携もスムーズです。",
        "address": "宮城県仙台市青葉区北山1-3-1",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2780,
        "longitude": 140.8650,
        "nearest_station": "JR仙山線 北山駅",
        "station_walk_minutes": 7,
        "capacity_max": 120,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000},
        ],
        "features": ["家族葬対応", "駅近", "閑静な環境", "寺院近接"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.2,
        "review_count": 78,
    },
    {
        "name": "清月記 青葉の杜",
        "slug": "miyagi-seigetuki-aoba-no-mori",
        "venue_type": "private_hall",
        "description": "仙台市青葉区の広瀬川沿いに佇む清月記の上質な斎場。自然に囲まれた静かな環境で、故人とゆっくりお別れができます。全館バリアフリー対応で、高齢の参列者にも配慮。貸切対応のため、プライベートな空間で心のこもった葬儀を行えます。",
        "address": "宮城県仙台市青葉区霊屋下23-5",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2520,
        "longitude": 140.8580,
        "nearest_station": "仙台市営地下鉄東西線 大町西公園駅",
        "station_walk_minutes": 12,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 628000},
        ],
        "features": ["貸切対応", "自然豊かな環境", "バリアフリー完備", "家族葬対応"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.4,
        "review_count": 92,
    },
    {
        "name": "葬祭会館ティア仙台青葉",
        "slug": "miyagi-tier-sendai-aoba",
        "venue_type": "private_hall",
        "description": "全国チェーンの葬祭会館ティアが仙台市青葉区に展開する斎場。明朗会計と事前相談の充実が特徴で、追加料金なしの安心プランが好評。地下鉄南北線勾当台公園駅から徒歩圏内の好立地。少人数の家族葬から一般葬まで対応可能です。",
        "address": "宮城県仙台市青葉区上杉3-8-20",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2680,
        "longitude": 140.8740,
        "nearest_station": "仙台市営地下鉄南北線 北四番丁駅",
        "station_walk_minutes": 6,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000},
        ],
        "features": ["明朗会計", "駅近", "家族葬対応", "事前相談充実", "全国チェーン"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.1,
        "review_count": 67,
    },
    {
        "name": "セレモニーホール紫雲閣 仙台中央",
        "slug": "miyagi-shiunkan-sendai-chuo",
        "venue_type": "private_hall",
        "description": "紫雲閣グループの仙台中央ホール。仙台市青葉区の中心部に位置し、交通アクセスに優れた立地です。格調高い式場は最大150名収容可能で、大規模な一般葬にも対応。家族葬専用の小ホールも備え、あらゆるご要望に柔軟に対応します。",
        "address": "宮城県仙台市青葉区本町2-10-15",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2630,
        "longitude": 140.8700,
        "nearest_station": "仙台市営地下鉄南北線 広瀬通駅",
        "station_walk_minutes": 5,
        "capacity_max": 150,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True, "僧侶控室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 658000},
        ],
        "features": ["駅近", "大規模対応", "家族葬対応", "好立地"],
        "operator_name": "紫雲閣グループ",
        "rating_avg": 4.0,
        "review_count": 55,
    },
    {
        "name": "メモリアルホール仙台",
        "slug": "miyagi-memorial-sendai",
        "venue_type": "private_hall",
        "description": "仙台市青葉区の国分町エリアに位置する民営斎場。モダンな内装と充実した設備が特徴で、ホテルのような快適な空間を提供。家族葬に最適な小規模ホールから、社葬にも対応できる大ホールまで、3つの式場を完備しています。",
        "address": "宮城県仙台市青葉区国分町3-1-18",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2650,
        "longitude": 140.8680,
        "nearest_station": "仙台市営地下鉄南北線 勾当台公園駅",
        "station_walk_minutes": 4,
        "capacity_max": 180,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 115000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 628000},
        ],
        "features": ["駅近", "モダンな設備", "社葬対応", "家族葬対応"],
        "operator_name": "メモリアルホール",
        "rating_avg": 4.2,
        "review_count": 63,
    },
    {
        "name": "花についた 仙台青葉",
        "slug": "miyagi-hana-ni-tsuta-aoba",
        "venue_type": "private_hall",
        "description": "仙台を拠点に展開する葬儀社「花についた」の青葉ホール。花祭壇の美しさに定評があり、故人を華やかに見送りたい方に選ばれています。温かみのある木目調の内装と季節の花で彩られた式場が特徴。少人数の家族葬プランが人気です。",
        "address": "宮城県仙台市青葉区旭ケ丘3-25-10",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2780,
        "longitude": 140.8720,
        "nearest_station": "仙台市営地下鉄南北線 旭ケ丘駅",
        "station_walk_minutes": 5,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000},
        ],
        "features": ["花祭壇が美しい", "駅近", "家族葬専門", "温かい雰囲気"],
        "operator_name": "花についた",
        "rating_avg": 4.3,
        "review_count": 71,
    },
    {
        "name": "やすらぎホール仙台北",
        "slug": "miyagi-yasuragi-sendai-kita",
        "venue_type": "private_hall",
        "description": "仙台市青葉区北部に位置する家族葬専門のホール。1日1組限定の貸切対応で、ゆったりとした時間の中で故人を偲ぶことができます。リビングのような温かい空間は、少人数でのお別れに最適。事前相談会も定期開催しています。",
        "address": "宮城県仙台市青葉区台原5-15-8",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2810,
        "longitude": 140.8760,
        "nearest_station": "仙台市営地下鉄南北線 台原駅",
        "station_walk_minutes": 6,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000},
        ],
        "features": ["家族葬専門", "1日1組貸切", "駅近", "事前相談"],
        "operator_name": "やすらぎホール",
        "rating_avg": 4.1,
        "review_count": 38,
    },
    {
        "name": "アークベル仙台",
        "slug": "miyagi-arcbell-sendai",
        "venue_type": "private_hall",
        "description": "結婚式場としても知られるアークベルが運営する葬儀会館。仙台市青葉区の一番町エリアに位置し、ホスピタリティの高いサービスが特徴。洗練された空間で格式ある葬儀を執り行えます。宴会場としての設備を活かした充実の会食スペースも魅力です。",
        "address": "宮城県仙台市青葉区一番町4-6-1",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2610,
        "longitude": 140.8690,
        "nearest_station": "仙台市営地下鉄南北線 勾当台公園駅",
        "station_walk_minutes": 3,
        "capacity_max": 250,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True, "会食スペース": True},
        "price_plans": [
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 698000},
        ],
        "features": ["駅近", "格式高い", "大規模対応", "会食充実", "ホスピタリティ"],
        "operator_name": "アークベル株式会社",
        "rating_avg": 4.0,
        "review_count": 48,
    },
    {
        "name": "清月記 愛子ホール",
        "slug": "miyagi-seigetuki-ayashi",
        "venue_type": "private_hall",
        "description": "仙台市青葉区愛子エリアに位置する清月記の郊外型斎場。広々とした敷地に100台収容の大型駐車場を完備し、車でのアクセスに便利。自然に囲まれた落ち着いた環境で、ゆったりとしたお別れの時間を提供します。",
        "address": "宮城県仙台市青葉区愛子中央1-10-5",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2700,
        "longitude": 140.7680,
        "nearest_station": "JR仙山線 愛子駅",
        "station_walk_minutes": 8,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 100,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000},
        ],
        "features": ["大型駐車場", "郊外型", "自然豊か", "家族葬対応"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.1,
        "review_count": 56,
    },
    {
        "name": "セレモニーホール紫雲閣 八幡",
        "slug": "miyagi-shiunkan-hachiman",
        "venue_type": "private_hall",
        "description": "仙台市青葉区八幡町に位置する紫雲閣の斎場。大崎八幡宮の近くにあり、歴史ある街並みに調和した落ち着いた外観が特徴。少人数から中規模の葬儀に対応し、地域に根差したサービスを提供しています。",
        "address": "宮城県仙台市青葉区八幡4-8-12",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2680,
        "longitude": 140.8540,
        "nearest_station": "JR仙山線 東北福祉大前駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000},
        ],
        "features": ["地域密着", "家族葬対応", "落ち着いた環境"],
        "operator_name": "紫雲閣グループ",
        "rating_avg": 3.9,
        "review_count": 42,
    },
    {
        "name": "輪王寺 式場",
        "slug": "miyagi-rinouji-shikijo",
        "venue_type": "temple_hall",
        "description": "伊達政宗ゆかりの名刹・輪王寺が運営する寺院式場。仙台市青葉区北山に位置し、美しい日本庭園に囲まれた荘厳な雰囲気の中で葬儀を執り行えます。仏式葬儀に特化しており、寺院ならではの丁寧な読経が特徴です。",
        "address": "宮城県仙台市青葉区北山1-14-1",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2800,
        "longitude": 140.8630,
        "nearest_station": "JR仙山線 北山駅",
        "station_walk_minutes": 5,
        "capacity_max": 100,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "控室": True, "駐車場": True, "庭園": True},
        "price_plans": [
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 380000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 650000},
        ],
        "features": ["寺院式場", "日本庭園", "仏式専門", "歴史ある寺院", "駅近"],
        "operator_name": "輪王寺",
        "rating_avg": 4.3,
        "review_count": 35,
    },
    {
        "name": "資福寺 式場",
        "slug": "miyagi-shifukuji-shikijo",
        "venue_type": "temple_hall",
        "description": "「あじさい寺」として知られる資福寺の式場。仙台市青葉区北山に位置し、四季折々の花に彩られた境内が美しい寺院です。落ち着いた雰囲気の中で、心のこもった仏式葬儀を執り行えます。",
        "address": "宮城県仙台市青葉区北山1-13-1",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2790,
        "longitude": 140.8620,
        "nearest_station": "JR仙山線 北山駅",
        "station_walk_minutes": 6,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "控室": True, "駐車場": True},
        "price_plans": [
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000},
        ],
        "features": ["寺院式場", "あじさい寺", "仏式専門", "少人数向け"],
        "operator_name": "資福寺",
        "rating_avg": 4.0,
        "review_count": 18,
    },
    {
        "name": "仙台市民葬儀 青葉ホール",
        "slug": "miyagi-shiminsougi-aoba",
        "venue_type": "private_hall",
        "description": "仙台市青葉区で市民葬を執り行える民営斎場。リーズナブルな価格設定と分かりやすい料金体系が特徴で、経済的な負担を抑えたい方に選ばれています。小規模な家族葬に適したアットホームな空間です。",
        "address": "宮城県仙台市青葉区五橋2-11-1",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2550,
        "longitude": 140.8730,
        "nearest_station": "仙台市営地下鉄南北線 五橋駅",
        "station_walk_minutes": 3,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000},
        ],
        "features": ["低価格", "駅近", "家族葬専門", "明朗会計"],
        "operator_name": "仙台市民葬儀",
        "rating_avg": 3.8,
        "review_count": 29,
    },
    {
        "name": "清月記 落合ホール",
        "slug": "miyagi-seigetuki-ochiai",
        "venue_type": "private_hall",
        "description": "仙台市青葉区落合エリアに位置する清月記の斎場。仙台西部の住宅街にあり、地域住民に親しまれています。広々とした駐車場を完備し、車でのアクセスに便利。家族葬から一般葬まで幅広く対応しています。",
        "address": "宮城県仙台市青葉区落合3-15-22",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2740,
        "longitude": 140.8100,
        "nearest_station": "JR仙山線 陸前落合駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000},
        ],
        "features": ["地域密着", "広い駐車場", "家族葬対応"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.0,
        "review_count": 44,
    },
    # =============================================
    # 仙台市宮城野区（16件）
    # =============================================
    {
        "name": "清月記 宮城野ホール",
        "slug": "miyagi-seigetuki-miyagino",
        "venue_type": "private_hall",
        "description": "仙台市宮城野区に位置する清月記の斎場。仙台駅東口エリアからのアクセスが良く、JR仙石線を利用した参列にも便利。2つの式場を備え、家族葬から一般葬まで対応可能です。24時間対応の相談窓口があり、急なご不幸にも迅速に対応します。",
        "address": "宮城県仙台市宮城野区榴岡4-6-15",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2600,
        "longitude": 140.8880,
        "nearest_station": "JR仙石線 榴ケ岡駅",
        "station_walk_minutes": 5,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True, "24時間対応": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000},
        ],
        "features": ["駅近", "24時間対応", "家族葬対応", "仙台駅東口エリア"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.2,
        "review_count": 72,
    },
    {
        "name": "葬祭会館ティア宮城野",
        "slug": "miyagi-tier-miyagino",
        "venue_type": "private_hall",
        "description": "仙台市宮城野区に展開するティアの斎場。原町エリアに位置し、地域に根差したサービスを提供。コストパフォーマンスの良さが評判で、明朗会計と充実したサポート体制が特徴です。",
        "address": "宮城県仙台市宮城野区原町2-3-18",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2640,
        "longitude": 140.9010,
        "nearest_station": "JR仙石線 陸前原ノ町駅",
        "station_walk_minutes": 7,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000},
        ],
        "features": ["明朗会計", "地域密着", "家族葬対応", "全国チェーン"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.0,
        "review_count": 45,
    },
    {
        "name": "セレモニーホール紫雲閣 宮城野",
        "slug": "miyagi-shiunkan-miyagino",
        "venue_type": "private_hall",
        "description": "仙台市宮城野区岩切エリアに位置する紫雲閣の斎場。国道4号線沿いでアクセスが良く、広い駐車場を完備。落ち着いた和モダンの内装が特徴で、家族葬から一般葬まで対応しています。",
        "address": "宮城県仙台市宮城野区岩切字三所南50-1",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2860,
        "longitude": 140.9280,
        "nearest_station": "JR東北本線 岩切駅",
        "station_walk_minutes": 10,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000},
        ],
        "features": ["国道沿い", "広い駐車場", "和モダン", "家族葬対応"],
        "operator_name": "紫雲閣グループ",
        "rating_avg": 3.9,
        "review_count": 38,
    },
    {
        "name": "メモリアルホール宮城野",
        "slug": "miyagi-memorial-miyagino",
        "venue_type": "private_hall",
        "description": "仙台市宮城野区小鶴新田エリアに位置する斎場。仙台東部エリアの拠点施設として、地域住民に親しまれています。充実した設備と丁寧なスタッフ対応で、安心して葬儀を任せられると好評です。",
        "address": "宮城県仙台市宮城野区新田東2-8-1",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2680,
        "longitude": 140.9150,
        "nearest_station": "JR仙石線 小鶴新田駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 568000},
        ],
        "features": ["地域密着", "丁寧なサービス", "家族葬対応"],
        "operator_name": "メモリアルホール",
        "rating_avg": 4.1,
        "review_count": 41,
    },
    {
        "name": "花についた 宮城野",
        "slug": "miyagi-hana-ni-tsuta-miyagino",
        "venue_type": "private_hall",
        "description": "仙台市宮城野区の福室エリアに位置する「花についた」の斎場。花に囲まれた温かい空間で、心のこもったお別れを演出します。産業道路沿いでアクセスが良く、駐車場も完備しています。",
        "address": "宮城県仙台市宮城野区福室2-7-25",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2620,
        "longitude": 140.9320,
        "nearest_station": "JR仙石線 福田町駅",
        "station_walk_minutes": 12,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000},
        ],
        "features": ["花祭壇が美しい", "アットホーム", "家族葬対応"],
        "operator_name": "花についた",
        "rating_avg": 4.2,
        "review_count": 36,
    },
    {
        "name": "やすらぎホール仙台東",
        "slug": "miyagi-yasuragi-sendai-higashi",
        "venue_type": "private_hall",
        "description": "仙台市宮城野区の中野エリアに位置する家族葬対応の斎場。仙台東部道路ICから近く、車でのアクセスが便利。リーズナブルな価格設定と温かいスタッフ対応が特徴で、少人数のお別れに最適な空間です。",
        "address": "宮城県仙台市宮城野区中野字上小袋田30-1",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2680,
        "longitude": 140.9480,
        "nearest_station": "JR仙石線 中野栄駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000},
        ],
        "features": ["低価格", "IC近接", "家族葬対応", "少人数向け"],
        "operator_name": "やすらぎホール",
        "rating_avg": 3.9,
        "review_count": 27,
    },
    {
        "name": "清月記 幸町ホール",
        "slug": "miyagi-seigetuki-saiwaicho",
        "venue_type": "private_hall",
        "description": "仙台市宮城野区幸町に位置する清月記の地域密着型斎場。住宅街の中にあり、近隣住民に親しまれています。コンパクトながら充実した設備を備え、アットホームな雰囲気の中で葬儀を執り行えます。",
        "address": "宮城県仙台市宮城野区幸町3-18-2",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2620,
        "longitude": 140.9020,
        "nearest_station": "JR仙石線 陸前原ノ町駅",
        "station_walk_minutes": 12,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 578000},
        ],
        "features": ["地域密着", "アットホーム", "家族葬対応"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.0,
        "review_count": 33,
    },
    {
        "name": "セレモニーホール紫雲閣 苦竹",
        "slug": "miyagi-shiunkan-nigatake",
        "venue_type": "private_hall",
        "description": "仙台市宮城野区苦竹エリアに位置する紫雲閣の斎場。仙台バイパス沿いで車でのアクセスが良好。広い式場と充実した設備で、中規模から大規模の葬儀にも対応可能です。",
        "address": "宮城県仙台市宮城野区苦竹1-5-30",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2660,
        "longitude": 140.9100,
        "nearest_station": "JR仙石線 苦竹駅",
        "station_walk_minutes": 5,
        "capacity_max": 120,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000},
        ],
        "features": ["駅近", "バイパス沿い", "大規模対応", "家族葬対応"],
        "operator_name": "紫雲閣グループ",
        "rating_avg": 4.0,
        "review_count": 47,
    },
    {
        "name": "仙台典礼 宮城野会館",
        "slug": "miyagi-tenrei-miyagino",
        "venue_type": "private_hall",
        "description": "仙台市宮城野区で長年にわたり地域の葬儀を支えてきた斎場。温かみのあるスタッフ対応と丁寧なサービスが特徴で、リピーターも多い信頼の斎場です。宮城野通エリアの便利な立地にあります。",
        "address": "宮城県仙台市宮城野区宮城野1-12-5",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2580,
        "longitude": 140.8950,
        "nearest_station": "JR仙石線 宮城野原駅",
        "station_walk_minutes": 6,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000},
        ],
        "features": ["地域密着", "駅近", "丁寧なサービス", "老舗"],
        "operator_name": "仙台典礼",
        "rating_avg": 4.1,
        "review_count": 39,
    },
    {
        "name": "孝勝寺 式場",
        "slug": "miyagi-koshoji-shikijo",
        "venue_type": "temple_hall",
        "description": "仙台市宮城野区の日蓮宗寺院・孝勝寺が運営する式場。仙台藩ゆかりの歴史ある寺院で、荘厳な本堂での葬儀が可能。仏式の伝統を大切にしながら、現代のニーズにも対応しています。",
        "address": "宮城県仙台市宮城野区榴岡3-1-11",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2590,
        "longitude": 140.8850,
        "nearest_station": "JR仙石線 榴ケ岡駅",
        "station_walk_minutes": 3,
        "capacity_max": 80,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "控室": True, "駐車場": True},
        "price_plans": [
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000},
        ],
        "features": ["寺院式場", "仏式専門", "歴史ある寺院", "駅近"],
        "operator_name": "孝勝寺",
        "rating_avg": 4.0,
        "review_count": 22,
    },
    {
        "name": "清月記 燕沢ホール",
        "slug": "miyagi-seigetuki-tsubamesawa",
        "venue_type": "private_hall",
        "description": "仙台市宮城野区燕沢エリアの清月記斎場。東仙台駅から近く、国道45号線沿いでアクセスが便利。コンパクトながらも温かみのある式場で、家族葬を中心に丁寧なサービスを提供しています。",
        "address": "宮城県仙台市宮城野区燕沢東3-2-15",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2740,
        "longitude": 140.9080,
        "nearest_station": "JR東北本線 東仙台駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000},
        ],
        "features": ["家族葬中心", "駅近", "国道沿い", "コンパクト"],
        "operator_name": "株式会社清月記",
        "rating_avg": 3.9,
        "review_count": 28,
    },
    {
        "name": "メモリアルホール仙台港",
        "slug": "miyagi-memorial-sendai-ko",
        "venue_type": "private_hall",
        "description": "仙台市宮城野区の仙台港エリアに位置する大型斎場。広々とした敷地に大型駐車場を完備し、遠方からの参列者にも便利。複数の式場を備え、大規模な社葬にも対応可能です。",
        "address": "宮城県仙台市宮城野区港3-1-3",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2640,
        "longitude": 140.9600,
        "nearest_station": "JR仙石線 中野栄駅",
        "station_walk_minutes": 15,
        "capacity_max": 200,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 80,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True, "会食スペース": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 115000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 658000},
        ],
        "features": ["大型駐車場", "大規模対応", "社葬対応", "仙台港エリア"],
        "operator_name": "メモリアルホール",
        "rating_avg": 4.0,
        "review_count": 35,
    },
    # =============================================
    # 仙台市若林区（16件）
    # =============================================
    {
        "name": "清月記 若林ホール",
        "slug": "miyagi-seigetuki-wakabayashi",
        "venue_type": "private_hall",
        "description": "仙台市若林区の連坊エリアに位置する清月記の斎場。仙台市中心部から近く、地下鉄東西線でのアクセスも良好。家族葬に最適なサイズの式場で、温かみのあるお別れの場を提供しています。",
        "address": "宮城県仙台市若林区連坊2-8-15",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2530,
        "longitude": 140.8830,
        "nearest_station": "仙台市営地下鉄東西線 連坊駅",
        "station_walk_minutes": 4,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000},
        ],
        "features": ["駅近", "地下鉄東西線", "家族葬対応", "好立地"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.1,
        "review_count": 52,
    },
    {
        "name": "葬祭会館ティア若林",
        "slug": "miyagi-tier-wakabayashi",
        "venue_type": "private_hall",
        "description": "仙台市若林区河原町に位置するティアの斎場。地下鉄南北線河原町駅から近く、交通アクセスに優れています。追加料金のない明朗会計と丁寧なスタッフ対応で、安心して葬儀を任せられます。",
        "address": "宮城県仙台市若林区河原町1-5-10",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2480,
        "longitude": 140.8750,
        "nearest_station": "仙台市営地下鉄南北線 河原町駅",
        "station_walk_minutes": 5,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000},
        ],
        "features": ["駅近", "明朗会計", "家族葬対応", "全国チェーン"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.0,
        "review_count": 40,
    },
    {
        "name": "セレモニーホール紫雲閣 若林",
        "slug": "miyagi-shiunkan-wakabayashi",
        "venue_type": "private_hall",
        "description": "仙台市若林区大和町に位置する紫雲閣の斎場。若林区の住宅街にあり、地域住民に親しまれています。和モダンの落ち着いた内装と丁寧なサービスが特徴です。",
        "address": "宮城県仙台市若林区大和町4-15-20",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2500,
        "longitude": 140.8950,
        "nearest_station": "仙台市営地下鉄東西線 薬師堂駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000},
        ],
        "features": ["地域密着", "和モダン", "家族葬対応"],
        "operator_name": "紫雲閣グループ",
        "rating_avg": 3.9,
        "review_count": 36,
    },
    {
        "name": "花についた 若林",
        "slug": "miyagi-hana-ni-tsuta-wakabayashi",
        "venue_type": "private_hall",
        "description": "仙台市若林区荒町に位置する「花についた」の斎場。季節の花を使った花祭壇が美しく、温かい雰囲気の中で故人を見送れます。少人数の家族葬に特化した式場です。",
        "address": "宮城県仙台市若林区荒町50-2",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2510,
        "longitude": 140.8780,
        "nearest_station": "仙台市営地下鉄東西線 連坊駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000},
        ],
        "features": ["花祭壇", "家族葬専門", "少人数向け", "温かい雰囲気"],
        "operator_name": "花についた",
        "rating_avg": 4.2,
        "review_count": 30,
    },
    {
        "name": "やすらぎホール若林",
        "slug": "miyagi-yasuragi-wakabayashi",
        "venue_type": "private_hall",
        "description": "仙台市若林区六丁の目エリアに位置する家族葬対応の斎場。地下鉄東西線六丁の目駅から徒歩圏内。1日1組貸切のプライベートな空間で、ゆっくりとしたお別れの時間を提供しています。",
        "address": "宮城県仙台市若林区六丁の目中町1-20",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2490,
        "longitude": 140.9120,
        "nearest_station": "仙台市営地下鉄東西線 六丁の目駅",
        "station_walk_minutes": 7,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000},
        ],
        "features": ["1日1組貸切", "駅近", "家族葬専門", "低価格"],
        "operator_name": "やすらぎホール",
        "rating_avg": 4.0,
        "review_count": 25,
    },
    {
        "name": "清月記 荒井ホール",
        "slug": "miyagi-seigetuki-arai",
        "venue_type": "private_hall",
        "description": "仙台市若林区荒井エリアに2020年オープンした清月記の新しい斎場。地下鉄東西線荒井駅から近く、最新の設備を備えたモダンな施設です。仙台東部エリアの新しい拠点として利用者が増えています。",
        "address": "宮城県仙台市若林区荒井東1-3-8",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2470,
        "longitude": 140.9280,
        "nearest_station": "仙台市営地下鉄東西線 荒井駅",
        "station_walk_minutes": 5,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000},
        ],
        "features": ["新しい施設", "駅近", "最新設備", "家族葬対応"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.3,
        "review_count": 48,
    },
    {
        "name": "仙台典礼 若林会館",
        "slug": "miyagi-tenrei-wakabayashi",
        "venue_type": "private_hall",
        "description": "仙台市若林区南小泉に位置する老舗の斎場。長年にわたり地域の葬儀を支え、信頼と実績のあるサービスを提供。リーズナブルな価格と親切なスタッフ対応で地域住民から支持されています。",
        "address": "宮城県仙台市若林区南小泉1-8-12",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2470,
        "longitude": 140.8880,
        "nearest_station": "仙台市営地下鉄東西線 薬師堂駅",
        "station_walk_minutes": 12,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000},
        ],
        "features": ["老舗", "低価格", "地域密着"],
        "operator_name": "仙台典礼",
        "rating_avg": 3.8,
        "review_count": 31,
    },
    {
        "name": "メモリアルホール薬師堂",
        "slug": "miyagi-memorial-yakushido",
        "venue_type": "private_hall",
        "description": "仙台市若林区の薬師堂エリアに位置する斎場。地下鉄東西線薬師堂駅から近く、落ち着いた住宅街の中にあります。中規模の式場で家族葬から一般葬まで対応可能。周辺には薬師堂や陸奥国分寺跡があり、歴史ある街並みに溶け込んでいます。",
        "address": "宮城県仙台市若林区木ノ下2-5-10",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2490,
        "longitude": 140.8920,
        "nearest_station": "仙台市営地下鉄東西線 薬師堂駅",
        "station_walk_minutes": 5,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 578000},
        ],
        "features": ["駅近", "歴史ある街", "家族葬対応"],
        "operator_name": "メモリアルホール",
        "rating_avg": 4.0,
        "review_count": 34,
    },
    # =============================================
    # 仙台市太白区（16件）
    # =============================================
    {
        "name": "清月記 長町ホール",
        "slug": "miyagi-seigetuki-nagamachi",
        "venue_type": "private_hall",
        "description": "仙台市太白区長町に位置する清月記の斎場。地下鉄南北線長町駅から徒歩圏内で、仙台南部エリアの拠点施設です。再開発が進む長町エリアにあり、新しい街並みの中にある清潔感のある斎場。家族葬から一般葬まで幅広く対応しています。",
        "address": "宮城県仙台市太白区長町5-3-18",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2280,
        "longitude": 140.8760,
        "nearest_station": "仙台市営地下鉄南北線 長町駅",
        "station_walk_minutes": 6,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000},
        ],
        "features": ["駅近", "仙台南部拠点", "家族葬対応", "新しい街"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.2,
        "review_count": 65,
    },
    {
        "name": "葬祭会館ティア太白",
        "slug": "miyagi-tier-taihaku",
        "venue_type": "private_hall",
        "description": "仙台市太白区鹿野に位置するティアの斎場。住宅街の中にあり、アットホームな雰囲気が特徴。明朗会計で追加料金のない安心プランが好評です。少人数から中規模の葬儀に対応しています。",
        "address": "宮城県仙台市太白区鹿野3-15-8",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2350,
        "longitude": 140.8680,
        "nearest_station": "仙台市営地下鉄南北線 長町南駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000},
        ],
        "features": ["明朗会計", "アットホーム", "家族葬対応", "全国チェーン"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.0,
        "review_count": 42,
    },
    {
        "name": "セレモニーホール紫雲閣 太白",
        "slug": "miyagi-shiunkan-taihaku",
        "venue_type": "private_hall",
        "description": "仙台市太白区西多賀に位置する紫雲閣の斎場。仙台南環状線沿いでアクセスが良く、広い駐車場を完備。格式高い式場と充実した付帯設備で、安心の葬儀サービスを提供しています。",
        "address": "宮城県仙台市太白区西多賀5-20-1",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2200,
        "longitude": 140.8500,
        "nearest_station": "JR東北本線 太子堂駅（バス10分）",
        "station_walk_minutes": 25,
        "capacity_max": 120,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 628000},
        ],
        "features": ["広い駐車場", "環状線沿い", "大規模対応", "家族葬対応"],
        "operator_name": "紫雲閣グループ",
        "rating_avg": 4.0,
        "review_count": 43,
    },
    {
        "name": "花についた 太白",
        "slug": "miyagi-hana-ni-tsuta-taihaku",
        "venue_type": "private_hall",
        "description": "仙台市太白区中田エリアに位置する「花についた」の斎場。JR南仙台駅から近く、仙台南部の住宅街に溶け込む温かい雰囲気の斎場。花祭壇の美しさに定評があり、季節の花で彩られた式場が好評です。",
        "address": "宮城県仙台市太白区中田5-18-10",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2100,
        "longitude": 140.8850,
        "nearest_station": "JR東北本線 南仙台駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000},
        ],
        "features": ["花祭壇", "駅近", "温かい雰囲気", "家族葬対応"],
        "operator_name": "花についた",
        "rating_avg": 4.2,
        "review_count": 38,
    },
    {
        "name": "やすらぎホール仙台南",
        "slug": "miyagi-yasuragi-sendai-minami",
        "venue_type": "private_hall",
        "description": "仙台市太白区富沢エリアに位置する家族葬専門のホール。地下鉄南北線富沢駅から徒歩圏内。1日1組限定の完全貸切対応で、プライベートな空間でゆっくりとお別れができます。",
        "address": "宮城県仙台市太白区富沢南1-8-5",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2180,
        "longitude": 140.8680,
        "nearest_station": "仙台市営地下鉄南北線 富沢駅",
        "station_walk_minutes": 7,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000},
        ],
        "features": ["家族葬専門", "1日1組貸切", "駅近", "プライベート空間"],
        "operator_name": "やすらぎホール",
        "rating_avg": 4.1,
        "review_count": 28,
    },
    {
        "name": "清月記 秋保ホール",
        "slug": "miyagi-seigetuki-akiu",
        "venue_type": "private_hall",
        "description": "仙台市太白区秋保エリアに位置する清月記の郊外型斎場。秋保温泉郷にほど近い自然豊かな環境で、心安らぐお別れの時間を提供。広い駐車場を完備し、遠方からの参列者にも対応しています。",
        "address": "宮城県仙台市太白区秋保町長袋字大原45-1",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2300,
        "longitude": 140.7380,
        "nearest_station": "JR仙山線 愛子駅（バス20分）",
        "station_walk_minutes": 60,
        "capacity_max": 80,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 60,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000},
        ],
        "features": ["自然豊か", "大型駐車場", "秋保エリア", "郊外型"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.0,
        "review_count": 20,
    },
    {
        "name": "メモリアルホール長町",
        "slug": "miyagi-memorial-nagamachi",
        "venue_type": "private_hall",
        "description": "仙台市太白区あすと長町に位置する斎場。長町副都心の再開発エリアにあり、近代的な設備を備えています。大型ショッピングモールに隣接し、参列者の利便性も高い立地です。",
        "address": "宮城県仙台市太白区あすと長町1-5-20",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2250,
        "longitude": 140.8800,
        "nearest_station": "JR東北本線 長町駅",
        "station_walk_minutes": 5,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 608000},
        ],
        "features": ["駅近", "再開発エリア", "近代的設備", "家族葬対応"],
        "operator_name": "メモリアルホール",
        "rating_avg": 4.1,
        "review_count": 40,
    },
    {
        "name": "仙台典礼 太白会館",
        "slug": "miyagi-tenrei-taihaku",
        "venue_type": "private_hall",
        "description": "仙台市太白区向山エリアに位置する老舗斎場。愛宕神社の麓にあり、緑に囲まれた落ち着いた環境。地域に根差した丁寧なサービスで、長年にわたり信頼を得ています。",
        "address": "宮城県仙台市太白区向山2-18-5",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2400,
        "longitude": 140.8620,
        "nearest_station": "仙台市営地下鉄南北線 愛宕橋駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000},
        ],
        "features": ["老舗", "地域密着", "緑豊かな環境"],
        "operator_name": "仙台典礼",
        "rating_avg": 3.9,
        "review_count": 33,
    },
]


def post_batch(batch, batch_num):
    """バッチをPOSTする"""
    data = json.dumps(batch).encode("utf-8")
    req = urllib.request.Request(SUPABASE_URL, data=data, headers=HEADERS, method="POST")
    try:
        resp = urllib.request.urlopen(req)
        print(f"  バッチ {batch_num}: {len(batch)}件 投入成功 (HTTP {resp.status})")
        return True
    except urllib.error.HTTPError as e:
        error_body = e.read().decode("utf-8")
        print(f"  バッチ {batch_num}: エラー (HTTP {e.code})")
        print(f"  エラー詳細: {error_body}")
        return False


def main():
    print(f"=== 宮城県 斎場データ Part1 投入開始 ===")
    print(f"総件数: {len(venues)}件")

    # スラッグの重複チェック
    slugs = [v["slug"] for v in venues]
    if len(slugs) != len(set(slugs)):
        duplicates = [s for s in slugs if slugs.count(s) > 1]
        print(f"エラー: スラッグに重複があります: {set(duplicates)}")
        return

    # 市区町村ごとの件数を表示
    city_counts = {}
    for v in venues:
        city = v["city_slug"]
        city_counts[city] = city_counts.get(city, 0) + 1
    print("\n市区町村別件数:")
    for city, count in sorted(city_counts.items(), key=lambda x: -x[1]):
        print(f"  {city}: {count}件")

    # バッチサイズ10件ずつ投入
    batch_size = 10
    total_batches = (len(venues) + batch_size - 1) // batch_size
    success_count = 0

    print(f"\n{total_batches}バッチに分けて投入します...")
    for i in range(0, len(venues), batch_size):
        batch = venues[i : i + batch_size]
        batch_num = i // batch_size + 1
        print(f"\nバッチ {batch_num}/{total_batches} ({len(batch)}件):")
        for v in batch:
            print(f"  - {v['name']} ({v['slug']})")

        if post_batch(batch, batch_num):
            success_count += len(batch)

        # API負荷軽減のため少し待つ
        if i + batch_size < len(venues):
            time.sleep(0.5)

    print(f"\n=== 投入完了 ===")
    print(f"成功: {success_count}/{len(venues)}件")


if __name__ == "__main__":
    main()
