#!/usr/bin/env python3
"""
奈良県の斎場データをSupabase REST APIに投入するスクリプト
60件を10件ずつバッチでPOSTする
"""

import json
import subprocess
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

# 奈良県の全斎場データ（60件）
venues = [
    # =============================================
    # 奈良市 (nara-city) — 18件
    # =============================================
    {
        "name": "奈良市斎場",
        "slug": "nara-narashi-saijo",
        "venue_type": "public_crematorium",
        "description": "奈良市が運営する公営斎場。火葬棟と式場を併設し、通夜から火葬まで同一敷地内で執り行えます。奈良市民は火葬料が減額され、広い駐車場を完備しています。",
        "address": "奈良県奈良市白毫寺町1-1",
        "prefecture_slug": "nara",
        "city_slug": "nara-city",
        "latitude": 34.6650,
        "longitude": 135.8450,
        "nearest_station": "JR奈良駅",
        "station_walk_minutes": 20,
        "capacity_max": 100,
        "hall_count": 3,
        "has_crematorium": True,
        "parking_count": 150,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True, "売店": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応", "バリアフリー"],
        "operator_name": "奈良市",
        "rating_avg": 3.9,
        "review_count": 62,
    },
    {
        "name": "ベルコ奈良シティホール",
        "slug": "nara-bellco-nara-city",
        "venue_type": "private_hall",
        "description": "ベルコの奈良拠点。JR奈良駅から車で10分の好立地。広い駐車場と充実した設備で、家族葬から大規模葬まで対応。互助会会員は割引価格で利用できます。",
        "address": "奈良県奈良市三条大路1丁目3-8",
        "prefecture_slug": "nara",
        "city_slug": "nara-city",
        "latitude": 34.6810,
        "longitude": 135.7920,
        "nearest_station": "近鉄奈良線 新大宮駅",
        "station_walk_minutes": 8,
        "capacity_max": 120,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 60,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "宿泊施設": True, "エレベーター": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 648000}],
        "features": ["互助会対応", "駅近", "駐車場完備", "宿泊可能", "家族葬対応"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.1,
        "review_count": 78,
    },
    {
        "name": "公益社 奈良会館",
        "slug": "nara-koekisha-nara-kaikan",
        "venue_type": "private_hall",
        "description": "公益社が運営する奈良市内の大型斎場。近鉄奈良駅から車で15分。格式ある空間で一般葬・社葬にも対応。きめ細やかなサービスと経験豊富なスタッフが好評です。",
        "address": "奈良県奈良市大安寺2丁目5-10",
        "prefecture_slug": "nara",
        "city_slug": "nara-city",
        "latitude": 34.6700,
        "longitude": 135.7980,
        "nearest_station": "JR桜井線 京終駅",
        "station_walk_minutes": 12,
        "capacity_max": 150,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "宿泊施設": True, "エレベーター": True, "バリアフリー": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 278000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 448000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 698000}],
        "features": ["老舗葬儀社", "社葬対応", "駐車場完備", "宿泊可能"],
        "operator_name": "株式会社公益社",
        "rating_avg": 4.2,
        "review_count": 65,
    },
    {
        "name": "家族葬のファミーユ 奈良ホール",
        "slug": "nara-famillu-nara",
        "venue_type": "private_hall",
        "description": "ファミーユが運営する奈良市の家族葬専用斎場。1日1組貸切でプライベートな空間を提供。リビングのような温かみのある式場で、少人数のお別れに最適です。",
        "address": "奈良県奈良市西大寺国見町1丁目7-15",
        "prefecture_slug": "nara",
        "city_slug": "nara-city",
        "latitude": 34.6950,
        "longitude": 135.7700,
        "nearest_station": "近鉄奈良線 大和西大寺駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "キッチン": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["家族葬専用", "1日1組貸切", "リビングスタイル", "駅近"],
        "operator_name": "株式会社家族葬のファミーユ",
        "rating_avg": 4.4,
        "review_count": 42,
    },
    {
        "name": "小さなお葬式 奈良ホール",
        "slug": "nara-chiisana-ososhiki-nara",
        "venue_type": "private_hall",
        "description": "小さなお葬式が提携する奈良市内の斎場。明瞭な料金体系と事前相談の充実ぶりが好評。全国規模のネットワークで安心の葬儀をリーズナブルに提供します。",
        "address": "奈良県奈良市芝辻町4丁目2-12",
        "prefecture_slug": "nara",
        "city_slug": "nara-city",
        "latitude": 34.6880,
        "longitude": 135.8050,
        "nearest_station": "近鉄奈良線 近鉄奈良駅",
        "station_walk_minutes": 15,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 178000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["明瞭価格", "事前相談無料", "全国ネットワーク", "家族葬対応"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 4.0,
        "review_count": 35,
    },
    {
        "name": "セレモニーホール奈良",
        "slug": "nara-ceremony-nara",
        "venue_type": "private_hall",
        "description": "奈良市中心部に位置するセレモニーホール。近鉄奈良駅からのアクセスも良く、モダンな式場と充実した設備が特長。花祭壇が美しいと好評です。",
        "address": "奈良県奈良市三条町465-2",
        "prefecture_slug": "nara",
        "city_slug": "nara-city",
        "latitude": 34.6830,
        "longitude": 135.8020,
        "nearest_station": "JR大和路線 奈良駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "エレベーター": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["駅近", "花祭壇", "モダンな内装", "家族葬対応"],
        "operator_name": "セレモニーホール奈良",
        "rating_avg": 4.2,
        "review_count": 48,
    },
    {
        "name": "メモリアルホール奈良",
        "slug": "nara-memorial-nara",
        "venue_type": "private_hall",
        "description": "奈良市南部に位置するメモリアルホール。閑静な住宅地の中にあり、落ち着いた雰囲気でお別れの時間を過ごせます。家族葬から一般葬まで幅広く対応。",
        "address": "奈良県奈良市南京終町1丁目15-3",
        "prefecture_slug": "nara",
        "city_slug": "nara-city",
        "latitude": 34.6620,
        "longitude": 135.8100,
        "nearest_station": "JR桜井線 京終駅",
        "station_walk_minutes": 5,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["駅近", "静かな環境", "家族葬対応", "バリアフリー"],
        "operator_name": "メモリアルサービス奈良",
        "rating_avg": 4.0,
        "review_count": 32,
    },
    {
        "name": "ベルコ学園前シティホール",
        "slug": "nara-bellco-gakuenmae",
        "venue_type": "private_hall",
        "description": "ベルコの学園前エリア斎場。閑静な住宅街に位置し、落ち着いた雰囲気。近鉄学園前駅からバスで5分。互助会会員割引あり。",
        "address": "奈良県奈良市学園中4丁目3-8",
        "prefecture_slug": "nara",
        "city_slug": "nara-city",
        "latitude": 34.6870,
        "longitude": 135.7600,
        "nearest_station": "近鉄奈良線 学園前駅",
        "station_walk_minutes": 15,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "エレベーター": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000}],
        "features": ["互助会対応", "閑静な環境", "駐車場完備", "家族葬対応"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.1,
        "review_count": 45,
    },
    {
        "name": "やすらぎホール奈良北",
        "slug": "nara-yasuragi-nara-kita",
        "venue_type": "private_hall",
        "description": "奈良市北部エリアの家族葬対応斎場。押熊町に位置し、大型駐車場完備。自然豊かな環境で心安らぐお別れの場を提供しています。",
        "address": "奈良県奈良市押熊町850-5",
        "prefecture_slug": "nara",
        "city_slug": "nara-city",
        "latitude": 34.7100,
        "longitude": 135.7650,
        "nearest_station": "近鉄奈良線 学園前駅",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["自然豊かな環境", "駐車場完備", "家族葬対応"],
        "operator_name": "やすらぎホール奈良",
        "rating_avg": 4.0,
        "review_count": 22,
    },
    {
        "name": "あすか葬祭 奈良ホール",
        "slug": "nara-asuka-sousai-nara",
        "venue_type": "private_hall",
        "description": "あすか葬祭が運営する奈良市内の斎場。地域密着型のきめ細やかなサービスが特長。24時間365日対応で、急なご不幸にも迅速に対応します。",
        "address": "奈良県奈良市七条西町2丁目12-5",
        "prefecture_slug": "nara",
        "city_slug": "nara-city",
        "latitude": 34.6550,
        "longitude": 135.7850,
        "nearest_station": "近鉄橿原線 西ノ京駅",
        "station_walk_minutes": 12,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["地域密着", "24時間対応", "家族葬対応", "リーズナブル"],
        "operator_name": "あすか葬祭",
        "rating_avg": 4.1,
        "review_count": 28,
    },
    {
        "name": "セレマ奈良ホール",
        "slug": "nara-cerema-nara",
        "venue_type": "private_hall",
        "description": "セレマグループの奈良斎場。三条大路エリアに位置し、新大宮駅から徒歩圏内。モダンな内装と充実した設備で上質な葬儀空間を提供します。",
        "address": "奈良県奈良市三条大路3丁目5-18",
        "prefecture_slug": "nara",
        "city_slug": "nara-city",
        "latitude": 34.6800,
        "longitude": 135.7880,
        "nearest_station": "近鉄奈良線 新大宮駅",
        "station_walk_minutes": 10,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "エレベーター": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 418000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 628000}],
        "features": ["駅近", "モダンな内装", "家族葬対応", "大規模葬対応"],
        "operator_name": "株式会社セレマ",
        "rating_avg": 4.0,
        "review_count": 38,
    },
    {
        "name": "奈良やまと斎場",
        "slug": "nara-yamato-saijo",
        "venue_type": "private_hall",
        "description": "奈良市大安寺エリアに位置する地域密着型斎場。伝統ある奈良の街にふさわしい、落ち着いた和の雰囲気で故人を偲ぶことができます。",
        "address": "奈良県奈良市大安寺町720-3",
        "prefecture_slug": "nara",
        "city_slug": "nara-city",
        "latitude": 34.6680,
        "longitude": 135.7950,
        "nearest_station": "JR大和路線 奈良駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"和室": True, "控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["和の雰囲気", "地域密着", "家族葬対応", "駐車場完備"],
        "operator_name": "奈良やまと葬祭",
        "rating_avg": 4.0,
        "review_count": 25,
    },
    {
        "name": "なら典礼会館",
        "slug": "nara-tenrei-kaikan",
        "venue_type": "private_hall",
        "description": "奈良市西部エリアに位置する典礼会館。阪奈道路からのアクセスが良く、大阪方面からの参列者にも便利。ゆとりのある式場で格式ある葬儀を執り行えます。",
        "address": "奈良県奈良市あやめ池南3丁目2-8",
        "prefecture_slug": "nara",
        "city_slug": "nara-city",
        "latitude": 34.6900,
        "longitude": 135.7680,
        "nearest_station": "近鉄奈良線 菖蒲池駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "宿泊施設": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 578000}],
        "features": ["駅近", "格式ある葬儀", "駐車場完備", "宿泊可能"],
        "operator_name": "なら典礼",
        "rating_avg": 4.1,
        "review_count": 30,
    },
    {
        "name": "西大寺メモリアルホール",
        "slug": "nara-saidaiji-memorial",
        "venue_type": "private_hall",
        "description": "大和西大寺駅近くのメモリアルホール。西大寺の歴史ある街並みに馴染む和モダンな外観。家族葬に特化した温かみのある空間です。",
        "address": "奈良県奈良市西大寺東町2丁目1-63",
        "prefecture_slug": "nara",
        "city_slug": "nara-city",
        "latitude": 34.6960,
        "longitude": 135.7730,
        "nearest_station": "近鉄奈良線 大和西大寺駅",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["駅近", "家族葬専用", "和モダン"],
        "operator_name": "西大寺メモリアルサービス",
        "rating_avg": 4.3,
        "review_count": 20,
    },
    {
        "name": "フューネラルホーム奈良",
        "slug": "nara-funeral-home-nara",
        "venue_type": "private_hall",
        "description": "奈良市東部に位置するフューネラルホーム。緑豊かな環境の中にあり、四季折々の自然を感じながらお別れの時間を過ごせます。",
        "address": "奈良県奈良市高畑町1028-5",
        "prefecture_slug": "nara",
        "city_slug": "nara-city",
        "latitude": 34.6750,
        "longitude": 135.8380,
        "nearest_station": "JR桜井線 京終駅",
        "station_walk_minutes": 15,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}],
        "features": ["緑豊かな環境", "家族葬対応", "駐車場完備"],
        "operator_name": "フューネラルホーム奈良",
        "rating_avg": 4.0,
        "review_count": 18,
    },
    {
        "name": "ベルコ富雄シティホール",
        "slug": "nara-bellco-tomio",
        "venue_type": "private_hall",
        "description": "ベルコの富雄エリア斎場。近鉄富雄駅から車で5分。奈良市西部の住宅地にあり、落ち着いた雰囲気です。互助会会員割引あり。",
        "address": "奈良県奈良市富雄北1丁目8-12",
        "prefecture_slug": "nara",
        "city_slug": "nara-city",
        "latitude": 34.6970,
        "longitude": 135.7500,
        "nearest_station": "近鉄奈良線 富雄駅",
        "station_walk_minutes": 10,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["互助会対応", "駅近", "駐車場完備", "家族葬対応"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 33,
    },
    {
        "name": "東光寺会館",
        "slug": "nara-tokoji-kaikan",
        "venue_type": "temple_hall",
        "description": "奈良市にある浄土宗の寺院式場。歴史ある本堂で荘厳な仏式葬儀を執り行えます。宗派を問わず利用可能。",
        "address": "奈良県奈良市中町3340",
        "prefecture_slug": "nara",
        "city_slug": "nara-city",
        "latitude": 34.6920,
        "longitude": 135.7550,
        "nearest_station": "近鉄奈良線 富雄駅",
        "station_walk_minutes": 15,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"和室": True, "控室": True, "安置室": True, "駐車場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 478000}],
        "features": ["寺院式場", "宗派不問", "伝統的な雰囲気"],
        "operator_name": "東光寺",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    # =============================================
    # 橿原市 (kashihara) — 6件
    # =============================================
    {
        "name": "ベルコ橿原シティホール",
        "slug": "nara-bellco-kashihara",
        "venue_type": "private_hall",
        "description": "ベルコの橿原拠点。近鉄大和八木駅から車で5分。奈良県中南部エリアの中核斎場として、家族葬から大規模葬まで幅広く対応。互助会会員割引あり。",
        "address": "奈良県橿原市内膳町1丁目3-15",
        "prefecture_slug": "nara",
        "city_slug": "kashihara",
        "latitude": 34.5100,
        "longitude": 135.7920,
        "nearest_station": "近鉄大阪線 大和八木駅",
        "station_walk_minutes": 8,
        "capacity_max": 100,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "宿泊施設": True, "エレベーター": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000}],
        "features": ["互助会対応", "駅近", "駐車場完備", "宿泊可能"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.1,
        "review_count": 55,
    },
    {
        "name": "公益社 橿原会館",
        "slug": "nara-koekisha-kashihara",
        "venue_type": "private_hall",
        "description": "公益社が運営する橿原市の斎場。近鉄八木西口駅から徒歩圏内で、格式ある葬儀空間を提供。経験豊富なスタッフによるきめ細やかなサービスが好評です。",
        "address": "奈良県橿原市八木町2丁目5-8",
        "prefecture_slug": "nara",
        "city_slug": "kashihara",
        "latitude": 34.5080,
        "longitude": 135.7900,
        "nearest_station": "近鉄橿原線 八木西口駅",
        "station_walk_minutes": 5,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "エレベーター": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 428000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 678000}],
        "features": ["老舗葬儀社", "駅近", "格式ある葬儀", "家族葬対応"],
        "operator_name": "株式会社公益社",
        "rating_avg": 4.2,
        "review_count": 40,
    },
    {
        "name": "家族葬のファミーユ 橿原ホール",
        "slug": "nara-famillu-kashihara",
        "venue_type": "private_hall",
        "description": "ファミーユの橿原店。1日1組貸切の家族葬専用斎場。温かみのあるリビングスタイルの式場で、少人数のお別れに最適です。",
        "address": "奈良県橿原市葛本町510-3",
        "prefecture_slug": "nara",
        "city_slug": "kashihara",
        "latitude": 34.5150,
        "longitude": 135.7950,
        "nearest_station": "近鉄大阪線 大和八木駅",
        "station_walk_minutes": 12,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "キッチン": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬専用", "1日1組貸切", "リビングスタイル"],
        "operator_name": "株式会社家族葬のファミーユ",
        "rating_avg": 4.3,
        "review_count": 28,
    },
    {
        "name": "セレモニーホール橿原",
        "slug": "nara-ceremony-kashihara",
        "venue_type": "private_hall",
        "description": "橿原市中心部のセレモニーホール。橿原神宮にほど近い落ち着いた環境で、丁寧なお別れの場を提供します。",
        "address": "奈良県橿原市久米町652-2",
        "prefecture_slug": "nara",
        "city_slug": "kashihara",
        "latitude": 34.4950,
        "longitude": 135.7870,
        "nearest_station": "近鉄南大阪線 橿原神宮前駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["駅近", "落ち着いた環境", "家族葬対応"],
        "operator_name": "セレモニーホール橿原",
        "rating_avg": 4.0,
        "review_count": 22,
    },
    {
        "name": "橿原メモリアルホール",
        "slug": "nara-kashihara-memorial",
        "venue_type": "private_hall",
        "description": "橿原市新沢エリアに位置するメモリアルホール。広い駐車場を完備し、車でのアクセスに便利。地域密着のサービスが特長です。",
        "address": "奈良県橿原市新沢町288-5",
        "prefecture_slug": "nara",
        "city_slug": "kashihara",
        "latitude": 34.4980,
        "longitude": 135.7800,
        "nearest_station": "近鉄南大阪線 橿原神宮西口駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["地域密着", "駐車場完備", "家族葬対応", "リーズナブル"],
        "operator_name": "橿原メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 18,
    },
    {
        "name": "大和やすらぎホール橿原",
        "slug": "nara-yamato-yasuragi-kashihara",
        "venue_type": "private_hall",
        "description": "橿原市の大和やすらぎホール。耳成山を望む環境で、心安らぐお別れの場を提供。和の趣が感じられる落ち着いた式場です。",
        "address": "奈良県橿原市石原田町282-1",
        "prefecture_slug": "nara",
        "city_slug": "kashihara",
        "latitude": 34.5200,
        "longitude": 135.7880,
        "nearest_station": "近鉄大阪線 耳成駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"和室": True, "控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}],
        "features": ["和の趣", "駅近", "家族葬対応"],
        "operator_name": "大和やすらぎホール",
        "rating_avg": 4.1,
        "review_count": 15,
    },
    # =============================================
    # 生駒市 (ikoma) — 5件
    # =============================================
    {
        "name": "ベルコ生駒シティホール",
        "slug": "nara-bellco-ikoma",
        "venue_type": "private_hall",
        "description": "ベルコの生駒拠点。近鉄生駒駅から車で8分。生駒山の裾野に位置し、自然豊かな環境。互助会会員割引あり。",
        "address": "奈良県生駒市東生駒1丁目10-5",
        "prefecture_slug": "nara",
        "city_slug": "ikoma",
        "latitude": 34.6900,
        "longitude": 135.7150,
        "nearest_station": "近鉄奈良線 東生駒駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "エレベーター": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000}],
        "features": ["互助会対応", "駅近", "駐車場完備", "家族葬対応"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.1,
        "review_count": 42,
    },
    {
        "name": "家族葬のファミーユ 生駒ホール",
        "slug": "nara-famillu-ikoma",
        "venue_type": "private_hall",
        "description": "ファミーユの生駒店。1日1組貸切の家族葬専用斎場。温かみのある空間で少人数のお別れに最適です。",
        "address": "奈良県生駒市山崎新町2-10",
        "prefecture_slug": "nara",
        "city_slug": "ikoma",
        "latitude": 34.6920,
        "longitude": 135.7100,
        "nearest_station": "近鉄生駒線 生駒駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "キッチン": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬専用", "1日1組貸切", "駅近"],
        "operator_name": "株式会社家族葬のファミーユ",
        "rating_avg": 4.4,
        "review_count": 25,
    },
    {
        "name": "セレモニーホール生駒",
        "slug": "nara-ceremony-ikoma",
        "venue_type": "private_hall",
        "description": "生駒市中心部のセレモニーホール。生駒駅から徒歩圏内で、大阪方面からのアクセスにも便利な立地です。",
        "address": "奈良県生駒市北新町10-36",
        "prefecture_slug": "nara",
        "city_slug": "ikoma",
        "latitude": 34.6950,
        "longitude": 135.7080,
        "nearest_station": "近鉄奈良線 生駒駅",
        "station_walk_minutes": 5,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["駅近", "大阪アクセス良好", "家族葬対応"],
        "operator_name": "セレモニーホール生駒",
        "rating_avg": 4.0,
        "review_count": 30,
    },
    {
        "name": "生駒メモリアルホール",
        "slug": "nara-ikoma-memorial",
        "venue_type": "private_hall",
        "description": "生駒市壱分町に位置するメモリアルホール。近鉄南生駒駅から近く、竜田川沿いの静かな環境です。",
        "address": "奈良県生駒市壱分町83-1",
        "prefecture_slug": "nara",
        "city_slug": "ikoma",
        "latitude": 34.6750,
        "longitude": 135.7200,
        "nearest_station": "近鉄生駒線 南生駒駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["駅近", "静かな環境", "家族葬対応", "リーズナブル"],
        "operator_name": "生駒メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 15,
    },
    {
        "name": "宝山寺参道会館",
        "slug": "nara-hozanji-sando-kaikan",
        "venue_type": "temple_hall",
        "description": "生駒市にある宝山寺参道沿いの寺院式場。歴史ある環境で荘厳な仏式葬儀を執り行えます。宗派不問。",
        "address": "奈良県生駒市門前町16-3",
        "prefecture_slug": "nara",
        "city_slug": "ikoma",
        "latitude": 34.6980,
        "longitude": 135.6980,
        "nearest_station": "近鉄生駒ケーブル 宝山寺駅",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"和室": True, "控室": True, "駐車場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 268000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 468000}],
        "features": ["寺院式場", "宗派不問", "伝統的な雰囲気"],
        "operator_name": "宝山寺",
        "rating_avg": 4.0,
        "review_count": 8,
    },
    # =============================================
    # 大和郡山市 (yamatokoriyama) — 5件
    # =============================================
    {
        "name": "ベルコ大和郡山シティホール",
        "slug": "nara-bellco-yamatokoriyama",
        "venue_type": "private_hall",
        "description": "ベルコの大和郡山拠点。近鉄郡山駅から車で5分。広い駐車場と充実した設備で家族葬から一般葬まで対応。互助会会員割引あり。",
        "address": "奈良県大和郡山市北郡山町248-1",
        "prefecture_slug": "nara",
        "city_slug": "yamatokoriyama",
        "latitude": 34.6520,
        "longitude": 135.7800,
        "nearest_station": "近鉄橿原線 近鉄郡山駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "エレベーター": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["互助会対応", "駅近", "駐車場完備", "家族葬対応"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 38,
    },
    {
        "name": "セレモニーホール大和郡山",
        "slug": "nara-ceremony-yamatokoriyama",
        "venue_type": "private_hall",
        "description": "大和郡山市中心部のセレモニーホール。郡山城跡にほど近い歴史ある街で、丁寧なお別れの場を提供します。",
        "address": "奈良県大和郡山市南郡山町528-5",
        "prefecture_slug": "nara",
        "city_slug": "yamatokoriyama",
        "latitude": 34.6450,
        "longitude": 135.7820,
        "nearest_station": "JR大和路線 郡山駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["駅近", "地域密着", "家族葬対応"],
        "operator_name": "セレモニーホール大和郡山",
        "rating_avg": 4.0,
        "review_count": 22,
    },
    {
        "name": "家族葬のファミーユ 大和郡山ホール",
        "slug": "nara-famillu-yamatokoriyama",
        "venue_type": "private_hall",
        "description": "ファミーユの大和郡山店。家族葬専用の温かい空間で、少人数でのお別れに最適です。",
        "address": "奈良県大和郡山市筒井町680-1",
        "prefecture_slug": "nara",
        "city_slug": "yamatokoriyama",
        "latitude": 34.6350,
        "longitude": 135.7750,
        "nearest_station": "近鉄橿原線 筒井駅",
        "station_walk_minutes": 5,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "キッチン": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["家族葬専用", "1日1組貸切", "駅近"],
        "operator_name": "株式会社家族葬のファミーユ",
        "rating_avg": 4.3,
        "review_count": 18,
    },
    {
        "name": "大和郡山メモリアルホール",
        "slug": "nara-yamatokoriyama-memorial",
        "venue_type": "private_hall",
        "description": "大和郡山市小泉エリアに位置するメモリアルホール。地域密着型のきめ細やかなサービスが好評です。",
        "address": "奈良県大和郡山市小泉町東3丁目8-5",
        "prefecture_slug": "nara",
        "city_slug": "yamatokoriyama",
        "latitude": 34.6280,
        "longitude": 135.7650,
        "nearest_station": "JR大和路線 大和小泉駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["地域密着", "駅近", "家族葬対応", "リーズナブル"],
        "operator_name": "大和郡山メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 15,
    },
    {
        "name": "薬師寺会館",
        "slug": "nara-yakushiji-kaikan",
        "venue_type": "temple_hall",
        "description": "薬師寺近くの寺院式場。世界遺産にほど近い荘厳な環境で、格式ある仏式葬儀を執り行えます。",
        "address": "奈良県大和郡山市九条町15-3",
        "prefecture_slug": "nara",
        "city_slug": "yamatokoriyama",
        "latitude": 34.6600,
        "longitude": 135.7850,
        "nearest_station": "近鉄橿原線 西ノ京駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"和室": True, "控室": True, "安置室": True, "駐車場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 488000}],
        "features": ["寺院式場", "宗派不問", "荘厳な雰囲気"],
        "operator_name": "薬師寺",
        "rating_avg": 4.1,
        "review_count": 10,
    },
    # =============================================
    # 天理市 (tenri) — 4件
    # =============================================
    {
        "name": "ベルコ天理シティホール",
        "slug": "nara-bellco-tenri",
        "venue_type": "private_hall",
        "description": "ベルコの天理拠点。天理駅から車で5分。互助会会員割引あり。家族葬から一般葬まで幅広く対応します。",
        "address": "奈良県天理市川原城町680-3",
        "prefecture_slug": "nara",
        "city_slug": "tenri",
        "latitude": 34.5970,
        "longitude": 135.8350,
        "nearest_station": "JR桜井線 天理駅",
        "station_walk_minutes": 8,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["互助会対応", "駅近", "駐車場完備", "家族葬対応"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 30,
    },
    {
        "name": "セレモニーホール天理",
        "slug": "nara-ceremony-tenri",
        "venue_type": "private_hall",
        "description": "天理市中心部のセレモニーホール。天理教本部にも近く、さまざまな宗教・宗派の葬儀に対応します。",
        "address": "奈良県天理市田井庄町468-2",
        "prefecture_slug": "nara",
        "city_slug": "tenri",
        "latitude": 34.5950,
        "longitude": 135.8300,
        "nearest_station": "近鉄天理線 天理駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000}],
        "features": ["宗派不問", "駅近", "家族葬対応"],
        "operator_name": "セレモニーホール天理",
        "rating_avg": 4.0,
        "review_count": 20,
    },
    {
        "name": "天理メモリアルホール",
        "slug": "nara-tenri-memorial",
        "venue_type": "private_hall",
        "description": "天理市前栽町に位置するメモリアルホール。地域密着のサービスが好評。リーズナブルな価格設定です。",
        "address": "奈良県天理市前栽町38-5",
        "prefecture_slug": "nara",
        "city_slug": "tenri",
        "latitude": 34.6000,
        "longitude": 135.8280,
        "nearest_station": "近鉄天理線 前栽駅",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}],
        "features": ["駅近", "地域密着", "家族葬対応", "リーズナブル"],
        "operator_name": "天理メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "天理やすらぎホール",
        "slug": "nara-tenri-yasuragi",
        "venue_type": "private_hall",
        "description": "天理市二階堂エリアのやすらぎホール。JR二階堂駅から徒歩圏内の好立地で、温かみのある家族葬に対応します。",
        "address": "奈良県天理市二階堂北菅田町520-1",
        "prefecture_slug": "nara",
        "city_slug": "tenri",
        "latitude": 34.6050,
        "longitude": 135.8100,
        "nearest_station": "JR桜井線 二階堂駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["駅近", "家族葬対応", "温かいサービス"],
        "operator_name": "天理やすらぎホール",
        "rating_avg": 4.1,
        "review_count": 10,
    },
    # =============================================
    # 香芝市 (kashiba) — 4件
    # =============================================
    {
        "name": "ベルコ香芝シティホール",
        "slug": "nara-bellco-kashiba",
        "venue_type": "private_hall",
        "description": "ベルコの香芝拠点。近鉄五位堂駅から車で5分。互助会会員割引あり。大阪へのアクセスも良い住宅都市で家族葬から一般葬まで対応。",
        "address": "奈良県香芝市五位堂3丁目502-1",
        "prefecture_slug": "nara",
        "city_slug": "kashiba",
        "latitude": 34.5400,
        "longitude": 135.7200,
        "nearest_station": "近鉄大阪線 五位堂駅",
        "station_walk_minutes": 8,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["互助会対応", "駅近", "駐車場完備", "家族葬対応"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 28,
    },
    {
        "name": "家族葬のファミーユ 香芝ホール",
        "slug": "nara-famillu-kashiba",
        "venue_type": "private_hall",
        "description": "ファミーユの香芝店。1日1組貸切の家族葬専用斎場。温かみのあるリビングスタイルの式場。",
        "address": "奈良県香芝市旭ケ丘2丁目5-12",
        "prefecture_slug": "nara",
        "city_slug": "kashiba",
        "latitude": 34.5380,
        "longitude": 135.7150,
        "nearest_station": "近鉄大阪線 五位堂駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "キッチン": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬専用", "1日1組貸切", "リビングスタイル"],
        "operator_name": "株式会社家族葬のファミーユ",
        "rating_avg": 4.3,
        "review_count": 18,
    },
    {
        "name": "セレモニーホール香芝",
        "slug": "nara-ceremony-kashiba",
        "venue_type": "private_hall",
        "description": "香芝市真美ヶ丘エリアのセレモニーホール。ニュータウンの閑静な住宅地に位置し、落ち着いた環境です。",
        "address": "奈良県香芝市真美ケ丘5丁目3-8",
        "prefecture_slug": "nara",
        "city_slug": "kashiba",
        "latitude": 34.5450,
        "longitude": 135.7100,
        "nearest_station": "近鉄大阪線 五位堂駅",
        "station_walk_minutes": 12,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["閑静な環境", "家族葬対応", "駐車場完備"],
        "operator_name": "セレモニーホール香芝",
        "rating_avg": 4.0,
        "review_count": 15,
    },
    {
        "name": "香芝メモリアルホール",
        "slug": "nara-kashiba-memorial",
        "venue_type": "private_hall",
        "description": "香芝市関屋エリアのメモリアルホール。地域密着のサービスが好評。リーズナブルな価格で家族葬を提供。",
        "address": "奈良県香芝市関屋北3丁目15-8",
        "prefecture_slug": "nara",
        "city_slug": "kashiba",
        "latitude": 34.5350,
        "longitude": 135.7050,
        "nearest_station": "近鉄大阪線 関屋駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}],
        "features": ["駅近", "地域密着", "リーズナブル", "家族葬対応"],
        "operator_name": "香芝メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 10,
    },
    # =============================================
    # 大和高田市 (yamatotakada) — 4件
    # =============================================
    {
        "name": "ベルコ大和高田シティホール",
        "slug": "nara-bellco-yamatotakada",
        "venue_type": "private_hall",
        "description": "ベルコの大和高田拠点。近鉄高田市駅から徒歩圏内。互助会会員割引あり。地域の中核斎場として幅広い葬儀に対応します。",
        "address": "奈良県大和高田市西町1丁目5-12",
        "prefecture_slug": "nara",
        "city_slug": "yamatotakada",
        "latitude": 34.5150,
        "longitude": 135.7350,
        "nearest_station": "近鉄南大阪線 高田市駅",
        "station_walk_minutes": 8,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["互助会対応", "駅近", "駐車場完備"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 25,
    },
    {
        "name": "セレモニーホール大和高田",
        "slug": "nara-ceremony-yamatotakada",
        "venue_type": "private_hall",
        "description": "大和高田市中心部のセレモニーホール。JR高田駅から近く、アクセス良好。家族葬から一般葬まで対応します。",
        "address": "奈良県大和高田市大中183-5",
        "prefecture_slug": "nara",
        "city_slug": "yamatotakada",
        "latitude": 34.5180,
        "longitude": 135.7380,
        "nearest_station": "JR和歌山線 高田駅",
        "station_walk_minutes": 5,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000}],
        "features": ["駅近", "家族葬対応", "地域密着"],
        "operator_name": "セレモニーホール大和高田",
        "rating_avg": 4.0,
        "review_count": 18,
    },
    {
        "name": "家族葬のファミーユ 大和高田ホール",
        "slug": "nara-famillu-yamatotakada",
        "venue_type": "private_hall",
        "description": "ファミーユの大和高田店。家族葬専用の温かい空間。1日1組貸切で少人数のお別れに最適です。",
        "address": "奈良県大和高田市蔵之宮町5-15",
        "prefecture_slug": "nara",
        "city_slug": "yamatotakada",
        "latitude": 34.5120,
        "longitude": 135.7400,
        "nearest_station": "近鉄大阪線 大和高田駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "キッチン": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["家族葬専用", "1日1組貸切", "リビングスタイル"],
        "operator_name": "株式会社家族葬のファミーユ",
        "rating_avg": 4.3,
        "review_count": 15,
    },
    {
        "name": "大和高田メモリアルホール",
        "slug": "nara-yamatotakada-memorial",
        "venue_type": "private_hall",
        "description": "大和高田市築山エリアに位置するメモリアルホール。地域密着のサービスと明瞭な価格が好評です。",
        "address": "奈良県大和高田市築山177-3",
        "prefecture_slug": "nara",
        "city_slug": "yamatotakada",
        "latitude": 34.5250,
        "longitude": 135.7300,
        "nearest_station": "近鉄大阪線 築山駅",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}],
        "features": ["駅近", "地域密着", "リーズナブル", "家族葬対応"],
        "operator_name": "大和高田メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    # =============================================
    # 桜井市 (sakurai-nara) — 2件
    # =============================================
    {
        "name": "ベルコ桜井シティホール",
        "slug": "nara-bellco-sakurai",
        "venue_type": "private_hall",
        "description": "ベルコの桜井拠点。桜井駅から車で5分。万葉の里で知られる歴史ある街で、家族葬から一般葬まで対応。互助会会員割引あり。",
        "address": "奈良県桜井市谷138-1",
        "prefecture_slug": "nara",
        "city_slug": "sakurai-nara",
        "latitude": 34.5150,
        "longitude": 135.8450,
        "nearest_station": "JR桜井線 桜井駅",
        "station_walk_minutes": 8,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["互助会対応", "駅近", "駐車場完備"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 22,
    },
    {
        "name": "桜井セレモニーホール",
        "slug": "nara-ceremony-sakurai",
        "venue_type": "private_hall",
        "description": "桜井市中心部のセレモニーホール。大神神社にもほど近い歴史ある環境で、丁寧なお別れの場を提供。",
        "address": "奈良県桜井市大福702-5",
        "prefecture_slug": "nara",
        "city_slug": "sakurai-nara",
        "latitude": 34.5200,
        "longitude": 135.8480,
        "nearest_station": "近鉄大阪線 桜井駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["歴史ある環境", "駅近", "家族葬対応"],
        "operator_name": "桜井セレモニー",
        "rating_avg": 4.0,
        "review_count": 15,
    },
    # =============================================
    # 葛城市 (katsuragi) — 2件
    # =============================================
    {
        "name": "セレモニーホール葛城",
        "slug": "nara-ceremony-katsuragi",
        "venue_type": "private_hall",
        "description": "葛城市中心部のセレモニーホール。近鉄新庄駅から徒歩圏内。葛城山を望む環境で、地域密着のサービスを提供。",
        "address": "奈良県葛城市北花内545-3",
        "prefecture_slug": "nara",
        "city_slug": "katsuragi",
        "latitude": 34.4900,
        "longitude": 135.7250,
        "nearest_station": "近鉄御所線 近鉄新庄駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["駅近", "地域密着", "家族葬対応"],
        "operator_name": "セレモニーホール葛城",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "葛城メモリアルホール",
        "slug": "nara-katsuragi-memorial",
        "venue_type": "private_hall",
        "description": "葛城市忍海エリアのメモリアルホール。リーズナブルな価格と温かいサービスが好評です。",
        "address": "奈良県葛城市忍海322-5",
        "prefecture_slug": "nara",
        "city_slug": "katsuragi",
        "latitude": 34.4850,
        "longitude": 135.7280,
        "nearest_station": "近鉄御所線 忍海駅",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}],
        "features": ["駅近", "リーズナブル", "家族葬対応"],
        "operator_name": "葛城メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 8,
    },
    # =============================================
    # 五條市 (gojo) — 2件
    # =============================================
    {
        "name": "五條斎場",
        "slug": "nara-gojo-saijo",
        "venue_type": "public_crematorium",
        "description": "五條市が運営する公営斎場。火葬棟を併設し、五條市民は火葬料が減額されます。吉野川沿いの静かな環境です。",
        "address": "奈良県五條市近内町526",
        "prefecture_slug": "nara",
        "city_slug": "gojo",
        "latitude": 34.3580,
        "longitude": 135.6850,
        "nearest_station": "JR和歌山線 五条駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 40,
        "facilities": {"霊安室": True, "控室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "五條市",
        "rating_avg": 3.8,
        "review_count": 18,
    },
    {
        "name": "五條セレモニーホール",
        "slug": "nara-ceremony-gojo",
        "venue_type": "private_hall",
        "description": "五條市中心部のセレモニーホール。JR五条駅から近く、地域密着の温かいサービスが好評。家族葬にも対応。",
        "address": "奈良県五條市須恵1丁目8-15",
        "prefecture_slug": "nara",
        "city_slug": "gojo",
        "latitude": 34.3550,
        "longitude": 135.6950,
        "nearest_station": "JR和歌山線 五条駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["駅近", "地域密着", "家族葬対応"],
        "operator_name": "五條セレモニー",
        "rating_avg": 4.0,
        "review_count": 10,
    },
    # =============================================
    # 御所市 (gose) — 2件
    # =============================================
    {
        "name": "御所斎場",
        "slug": "nara-gose-saijo",
        "venue_type": "public_crematorium",
        "description": "御所市が運営する公営斎場。金剛山・葛城山を望む環境で、火葬棟を併設。市民の方に広く利用されています。",
        "address": "奈良県御所市大字室285",
        "prefecture_slug": "nara",
        "city_slug": "gose",
        "latitude": 34.4550,
        "longitude": 135.7350,
        "nearest_station": "JR和歌山線 御所駅",
        "station_walk_minutes": 15,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"霊安室": True, "控室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "御所市",
        "rating_avg": 3.8,
        "review_count": 12,
    },
    {
        "name": "御所メモリアルホール",
        "slug": "nara-gose-memorial",
        "venue_type": "private_hall",
        "description": "御所市のメモリアルホール。地域密着のサービスで家族葬に対応。リーズナブルな価格設定が好評です。",
        "address": "奈良県御所市東松本210-3",
        "prefecture_slug": "nara",
        "city_slug": "gose",
        "latitude": 34.4600,
        "longitude": 135.7400,
        "nearest_station": "近鉄御所線 近鉄御所駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["駅近", "地域密着", "リーズナブル", "家族葬対応"],
        "operator_name": "御所メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 8,
    },
    # =============================================
    # 宇陀市 (uda) — 2件
    # =============================================
    {
        "name": "宇陀斎場",
        "slug": "nara-uda-saijo",
        "venue_type": "public_crematorium",
        "description": "宇陀市が運営する公営斎場。室生寺や大宇陀の歴史ある町並みに囲まれた環境。火葬棟を併設し、市民の方に広く利用されています。",
        "address": "奈良県宇陀市大宇陀拾生1090",
        "prefecture_slug": "nara",
        "city_slug": "uda",
        "latitude": 34.4700,
        "longitude": 135.9350,
        "nearest_station": "近鉄大阪線 榛原駅",
        "station_walk_minutes": 25,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"霊安室": True, "控室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "宇陀市",
        "rating_avg": 3.8,
        "review_count": 10,
    },
    {
        "name": "榛原セレモニーホール",
        "slug": "nara-haibara-ceremony",
        "venue_type": "private_hall",
        "description": "宇陀市榛原エリアのセレモニーホール。近鉄榛原駅から徒歩圏内。地域密着のサービスで家族葬に対応します。",
        "address": "奈良県宇陀市榛原萩原2442-3",
        "prefecture_slug": "nara",
        "city_slug": "uda",
        "latitude": 34.4750,
        "longitude": 135.9500,
        "nearest_station": "近鉄大阪線 榛原駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}],
        "features": ["駅近", "地域密着", "家族葬対応"],
        "operator_name": "榛原セレモニー",
        "rating_avg": 4.0,
        "review_count": 8,
    },
]

# 投入処理
print(f"奈良県の斎場データ投入開始: 合計{len(venues)}件")
for i in range(0, len(venues), 10):
    batch = venues[i:i+10]
    status = insert_batch(batch)
    print(f"  バッチ {i//10+1}: {len(batch)}件 → HTTP {status}")
    if status != "201":
        print(f"    エラー発生！")
        # エラー詳細を取得
        data_json = json.dumps(batch, ensure_ascii=False)
        result = subprocess.run([
            "curl", "-s",
            "-X", "POST", SUPABASE_URL,
            "-H", f"apikey: {API_KEY}",
            "-H", f"Authorization: Bearer {API_KEY}",
            "-H", "Content-Type: application/json",
            "-H", "Prefer: return=minimal",
            "-H", "User-Agent: Mozilla/5.0",
            "-d", data_json
        ], capture_output=True, text=True)
        print(f"    詳細: {result.stdout[:500]}")
    time.sleep(1)

print(f"\n奈良県: 全{len(venues)}件の投入完了")
