# -*- coding: utf-8 -*-
import json, subprocess, time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

# 三重県 バッチ1: 四日市市18件 + 津市2件 = 20件
venues = [
    # === 四日市市 18件 ===
    {"name":"ティア四日市中央","slug":"mie-tier-yokkaichi-chuo","venue_type":"private_hall","description":"四日市市中心部に位置するティアの大型葬儀ホール。近鉄四日市駅から徒歩圏内で、三重県北部の中核斎場です。","address":"三重県四日市市諏訪町2-8","prefecture_slug":"mie","city_slug":"yokkaichi","latitude":34.967,"longitude":136.620,"nearest_station":"近鉄名古屋線 近鉄四日市駅","station_walk_minutes":8,"capacity_max":120,"hall_count":3,"has_crematorium":False,"parking_count":40,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":98000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":358000},{"type":"ippanso","label":"一般葬プラン","priceFrom":680000}],"features":["家族葬対応","駅近","大規模対応"],"operator_name":"ティア","rating_avg":4.2,"review_count":55},
    {"name":"紫雲殿四日市北","slug":"mie-shiunden-yokkaichi-kita","venue_type":"private_hall","description":"四日市市北部の紫雲殿。国道1号線沿いでお車でのアクセスが便利。桑名方面からの利用も多い式場です。","address":"三重県四日市市富田2-15-30","prefecture_slug":"mie","city_slug":"yokkaichi","latitude":34.990,"longitude":136.630,"nearest_station":"JR関西本線 富田駅","station_walk_minutes":8,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":345000},{"type":"ippanso","label":"一般葬プラン","priceFrom":650000}],"features":["家族葬対応","駅近","大駐車場"],"operator_name":"紫雲殿","rating_avg":4.1,"review_count":38},
    {"name":"紫雲殿四日市南","slug":"mie-shiunden-yokkaichi-minami","venue_type":"private_hall","description":"四日市市南部の紫雲殿。東名阪自動車道四日市ICに近くアクセス良好です。","address":"三重県四日市市日永5-10-18","prefecture_slug":"mie","city_slug":"yokkaichi","latitude":34.940,"longitude":136.608,"nearest_station":"あすなろう鉄道 日永駅","station_walk_minutes":5,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":338000},{"type":"ippanso","label":"一般葬プラン","priceFrom":630000}],"features":["家族葬対応","駅近","インター近く"],"operator_name":"紫雲殿","rating_avg":4.0,"review_count":30},
    {"name":"セレモニーホール四日市","slug":"mie-ceremony-yokkaichi","venue_type":"private_hall","description":"四日市市中央通り沿いのセレモニーホール。近鉄四日市駅から近く、公共交通でのアクセスに優れています。","address":"三重県四日市市中央通5-3","prefecture_slug":"mie","city_slug":"yokkaichi","latitude":34.970,"longitude":136.618,"nearest_station":"近鉄名古屋線 近鉄四日市駅","station_walk_minutes":5,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":100000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":368000},{"type":"ippanso","label":"一般葬プラン","priceFrom":680000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホール","rating_avg":4.1,"review_count":35},
    {"name":"四日市市斎場","slug":"mie-yokkaichi-saijo","venue_type":"public_crematorium","description":"四日市市が運営する公営火葬場・斎場。市民料金で火葬と告別式が行える公営施設です。","address":"三重県四日市市大字塩浜字大治田878-1","prefecture_slug":"mie","city_slug":"yokkaichi","latitude":34.935,"longitude":136.638,"nearest_station":"近鉄名古屋線 塩浜駅","station_walk_minutes":15,"capacity_max":100,"hall_count":2,"has_crematorium":True,"parking_count":60,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":55000}],"features":["公営施設","火葬場併設","大駐車場"],"operator_name":"四日市市","rating_avg":3.7,"review_count":60},
    {"name":"家族葬のファミーユ四日市","slug":"mie-famillu-yokkaichi","venue_type":"private_hall","description":"四日市市の家族葬専門ホール。少人数でのアットホームなお別れに特化した施設です。","address":"三重県四日市市松本3-8-17","prefecture_slug":"mie","city_slug":"yokkaichi","latitude":34.960,"longitude":136.615,"nearest_station":"近鉄名古屋線 近鉄四日市駅","station_walk_minutes":12,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":85000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":290000}],"features":["家族葬対応","少人数対応","低価格"],"operator_name":"家族葬のファミーユ","rating_avg":4.4,"review_count":22},
    {"name":"JA葬祭四日市","slug":"mie-ja-yokkaichi","venue_type":"private_hall","description":"JA三重四日市が運営する葬祭ホール。組合員割引があり、地域に根差した適正価格のサービスが特徴です。","address":"三重県四日市市西新地14-10","prefecture_slug":"mie","city_slug":"yokkaichi","latitude":34.965,"longitude":136.612,"nearest_station":"近鉄名古屋線 近鉄四日市駅","station_walk_minutes":10,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":298000},{"type":"ippanso","label":"一般葬プラン","priceFrom":540000}],"features":["家族葬対応","低価格"],"operator_name":"JA三重四日市","rating_avg":3.9,"review_count":25},
    {"name":"ティア四日市西","slug":"mie-tier-yokkaichi-nishi","venue_type":"private_hall","description":"四日市市西部のティア。三滝通り沿いの閑静なエリアに位置し、落ち着いた雰囲気の式場です。","address":"京都府四日市市三滝台2-1-15","prefecture_slug":"mie","city_slug":"yokkaichi","latitude":34.955,"longitude":136.595,"nearest_station":"近鉄湯の山線 桜駅","station_walk_minutes":10,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":18,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":92000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":340000}],"features":["家族葬対応","駅近"],"operator_name":"ティア","rating_avg":4.2,"review_count":20},
    {"name":"紫雲殿四日市羽津","slug":"mie-shiunden-yokkaichi-hazu","venue_type":"private_hall","description":"四日市市羽津エリアの紫雲殿。国道23号線沿いでアクセスが便利です。","address":"三重県四日市市羽津中2-12-30","prefecture_slug":"mie","city_slug":"yokkaichi","latitude":34.985,"longitude":136.625,"nearest_station":"近鉄名古屋線 霞ヶ浦駅","station_walk_minutes":8,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":348000},{"type":"ippanso","label":"一般葬プラン","priceFrom":650000}],"features":["家族葬対応","駅近"],"operator_name":"紫雲殿","rating_avg":4.0,"review_count":28},
    {"name":"メモリアルホール四日市","slug":"mie-memorial-yokkaichi","venue_type":"private_hall","description":"四日市市笹川エリアのメモリアルホール。清潔感のある近代的な施設で、幅広い規模の葬儀に対応しています。","address":"三重県四日市市笹川5-68","prefecture_slug":"mie","city_slug":"yokkaichi","latitude":34.945,"longitude":136.600,"nearest_station":"あすなろう鉄道 西日野駅","station_walk_minutes":10,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":98000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":355000},{"type":"ippanso","label":"一般葬プラン","priceFrom":660000}],"features":["家族葬対応"],"operator_name":"メモリアルホール","rating_avg":4.0,"review_count":22},
    {"name":"ベルコ四日市シティホール","slug":"mie-bellco-yokkaichi","venue_type":"private_hall","description":"四日市市のベルコ葬儀会館。国道1号線沿いの立地で広い駐車場を完備しています。","address":"三重県四日市市城東町8-15","prefecture_slug":"mie","city_slug":"yokkaichi","latitude":34.972,"longitude":136.628,"nearest_station":"JR関西本線 四日市駅","station_walk_minutes":10,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":98000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":360000},{"type":"ippanso","label":"一般葬プラン","priceFrom":680000}],"features":["家族葬対応","大駐車場"],"operator_name":"ベルコ","rating_avg":4.1,"review_count":30},
    {"name":"家族葬のファミーユ四日市北","slug":"mie-famillu-yokkaichi-kita","venue_type":"private_hall","description":"四日市市北部の家族葬専門ホール。富田エリアの静かな環境でお見送りができます。","address":"三重県四日市市富田3-1-22","prefecture_slug":"mie","city_slug":"yokkaichi","latitude":34.992,"longitude":136.632,"nearest_station":"JR関西本線 富田駅","station_walk_minutes":5,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":85000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":288000}],"features":["家族葬対応","少人数対応","低価格","駅近"],"operator_name":"家族葬のファミーユ","rating_avg":4.3,"review_count":15},
    {"name":"ティア四日市南","slug":"mie-tier-yokkaichi-minami","venue_type":"private_hall","description":"四日市市南部のティア。小古曽エリアに位置し、鈴鹿市方面からの利用も便利です。","address":"三重県四日市市小古曽3-5-25","prefecture_slug":"mie","city_slug":"yokkaichi","latitude":34.932,"longitude":136.610,"nearest_station":"あすなろう鉄道 小古曽駅","station_walk_minutes":5,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":90000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":335000}],"features":["家族葬対応","駅近"],"operator_name":"ティア","rating_avg":4.2,"review_count":18},
    {"name":"セレモニーホール四日市西","slug":"mie-ceremony-yokkaichi-nishi","venue_type":"private_hall","description":"四日市市西部のセレモニーホール。菰野町方面からのアクセスも便利な立地です。","address":"三重県四日市市山之一色町200","prefecture_slug":"mie","city_slug":"yokkaichi","latitude":34.975,"longitude":136.590,"nearest_station":"近鉄湯の山線 伊勢松本駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":358000},{"type":"ippanso","label":"一般葬プラン","priceFrom":650000}],"features":["家族葬対応"],"operator_name":"セレモニーホール","rating_avg":4.0,"review_count":18},
    {"name":"やすらぎ会館四日市","slug":"mie-yasuragi-yokkaichi","venue_type":"private_hall","description":"四日市市常磐エリアのやすらぎ会館。落ち着いた住宅街に位置する温かみのある式場です。","address":"三重県四日市市城西町4-22","prefecture_slug":"mie","city_slug":"yokkaichi","latitude":34.962,"longitude":136.608,"nearest_station":"近鉄名古屋線 近鉄四日市駅","station_walk_minutes":15,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":12,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":340000},{"type":"ippanso","label":"一般葬プラン","priceFrom":620000}],"features":["家族葬対応"],"operator_name":"やすらぎ会館","rating_avg":3.9,"review_count":16},
    {"name":"法要殿四日市","slug":"mie-hoyoden-yokkaichi","venue_type":"private_hall","description":"四日市市赤堀エリアの法要殿。地域密着型の丁寧なサービスが評判の式場です。","address":"三重県四日市市赤堀2-5-18","prefecture_slug":"mie","city_slug":"yokkaichi","latitude":34.958,"longitude":136.625,"nearest_station":"近鉄名古屋線 赤堀駅","station_walk_minutes":5,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":350000},{"type":"ippanso","label":"一般葬プラン","priceFrom":640000}],"features":["家族葬対応","駅近"],"operator_name":"法要殿","rating_avg":4.0,"review_count":20},
    {"name":"こころ斎苑四日市","slug":"mie-kokorosaien-yokkaichi","venue_type":"private_hall","description":"四日市市高角エリアのこころ斎苑。木のぬくもりを感じる内装で、温かいお別れを提供しています。","address":"三重県四日市市高角町字焼谷2668-1","prefecture_slug":"mie","city_slug":"yokkaichi","latitude":34.950,"longitude":136.580,"nearest_station":"近鉄湯の山線 高角駅","station_walk_minutes":8,"capacity_max":40,"hall_count":1,"has_crematorium":False,"parking_count":12,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":88000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":310000}],"features":["家族葬対応","少人数対応"],"operator_name":"こころ斎苑","rating_avg":4.3,"review_count":14},
    {"name":"四日市葬祭会館","slug":"mie-sousai-yokkaichi","venue_type":"private_hall","description":"四日市市川島町の葬祭会館。国道477号線沿いで駐車場完備の便利な立地です。","address":"三重県四日市市川島町6053","prefecture_slug":"mie","city_slug":"yokkaichi","latitude":34.978,"longitude":136.598,"nearest_station":"近鉄湯の山線 伊勢川島駅","station_walk_minutes":5,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":345000},{"type":"ippanso","label":"一般葬プラン","priceFrom":630000}],"features":["家族葬対応","駅近","駐車場完備"],"operator_name":"四日市葬祭","rating_avg":4.0,"review_count":16},
    # === 津市 最初の2件 ===
    {"name":"ティア津中央","slug":"mie-tier-tsu-chuo","venue_type":"private_hall","description":"津市の中心部に位置するティアの大型ホール。県庁所在地の中核斎場として、家族葬から大規模葬まで対応しています。","address":"三重県津市丸之内養正町4-10","prefecture_slug":"mie","city_slug":"tsu","latitude":34.719,"longitude":136.508,"nearest_station":"近鉄名古屋線 津駅","station_walk_minutes":10,"capacity_max":100,"hall_count":2,"has_crematorium":False,"parking_count":35,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":98000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":355000},{"type":"ippanso","label":"一般葬プラン","priceFrom":670000}],"features":["家族葬対応","駅近"],"operator_name":"ティア","rating_avg":4.2,"review_count":42},
    {"name":"紫雲殿津","slug":"mie-shiunden-tsu","venue_type":"private_hall","description":"津市大谷エリアの紫雲殿。伊勢自動車道津ICに近く、広い駐車場を完備しています。","address":"三重県津市大谷町230","prefecture_slug":"mie","city_slug":"tsu","latitude":34.725,"longitude":136.500,"nearest_station":"近鉄名古屋線 津新町駅","station_walk_minutes":10,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":345000},{"type":"ippanso","label":"一般葬プラン","priceFrom":650000}],"features":["家族葬対応","大駐車場","インター近く"],"operator_name":"紫雲殿","rating_avg":4.1,"review_count":35},
]

for i in range(0, len(venues), 10):
    batch = venues[i:i+10]
    code = insert_batch(batch)
    print(f"バッチ {i//10+1}: {code} ({len(batch)}件)")
    time.sleep(1)

print(f"\n完了: 合計 {len(venues)} 件")
