# -*- coding: utf-8 -*-
import json, subprocess, time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

# 福島県 80件
fukushima = [
    # === 郡山市 18件 ===
    {"name":"セレモールホール郡山中央","slug":"fukushima-koriyama-ceremony-chuo","venue_type":"private_hall","description":"郡山市中心部に位置する大型葬儀ホール。郡山駅から徒歩圏内で、家族葬から大規模な一般葬まで幅広く対応。バリアフリー設計で高齢の参列者にも安心です。","address":"福島県郡山市中町1-15","prefecture_slug":"fukushima","city_slug":"koriyama","latitude":37.399,"longitude":140.382,"nearest_station":"JR東北本線 郡山駅","station_walk_minutes":8,"capacity_max":120,"hall_count":3,"has_crematorium":False,"parking_count":40,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":98000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":380000},{"type":"ippanso","label":"一般葬プラン","priceFrom":680000}],"features":["家族葬対応","駅近","バリアフリー"],"operator_name":"セレモール","rating_avg":4.2,"review_count":48},
    {"name":"法要殿郡山","slug":"fukushima-koriyama-hoyoden","venue_type":"private_hall","description":"郡山市内で長年の実績を持つ法要殿の斎場。落ち着いた和モダンの内装が特徴で、故人との最後のお別れにふさわしい空間を提供しています。","address":"福島県郡山市桑野2-33-8","prefecture_slug":"fukushima","city_slug":"koriyama","latitude":37.395,"longitude":140.365,"nearest_station":"JR東北本線 郡山駅","station_walk_minutes":15,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":350000},{"type":"ippanso","label":"一般葬プラン","priceFrom":620000}],"features":["家族葬対応","バリアフリー"],"operator_name":"法要殿","rating_avg":4.1,"review_count":35},
    {"name":"ベルヴィ郡山","slug":"fukushima-koriyama-bellevie","venue_type":"private_hall","description":"郡山市の閑静な住宅街に立地するベルヴィの葬儀会館。少人数の家族葬に特化した温かみのある空間が評判です。","address":"福島県郡山市大槻町字北八耕地7-1","prefecture_slug":"fukushima","city_slug":"koriyama","latitude":37.381,"longitude":140.347,"nearest_station":"JR東北本線 郡山駅","station_walk_minutes":20,"capacity_max":50,"hall_count":2,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":88000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":320000}],"features":["家族葬対応","少人数対応"],"operator_name":"ベルヴィ","rating_avg":4.3,"review_count":29},
    {"name":"JA葬祭郡山","slug":"fukushima-koriyama-ja-sousai","venue_type":"private_hall","description":"JA福島さくらが運営する葬祭ホール。組合員割引があり、地域に根差した温かいサービスが特徴。家族葬から一般葬まで対応可能です。","address":"福島県郡山市安積町笹川字石田1-5","prefecture_slug":"fukushima","city_slug":"koriyama","latitude":37.371,"longitude":140.375,"nearest_station":"JR東北本線 安積永盛駅","station_walk_minutes":10,"capacity_max":100,"hall_count":2,"has_crematorium":False,"parking_count":50,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":298000},{"type":"ippanso","label":"一般葬プラン","priceFrom":550000}],"features":["家族葬対応","大駐車場"],"operator_name":"JA福島さくら葬祭","rating_avg":4.0,"review_count":32},
    {"name":"メモリアルホール郡山","slug":"fukushima-koriyama-memorial","venue_type":"private_hall","description":"郡山市東部に位置するメモリアルホール。清潔感のある近代的な施設で、故人を偲ぶにふさわしい空間を提供。駐車場完備でお車でのアクセスも便利です。","address":"福島県郡山市田村町金屋字マセ口1-1","prefecture_slug":"fukushima","city_slug":"koriyama","latitude":37.388,"longitude":140.408,"nearest_station":"JR磐越東線 舞木駅","station_walk_minutes":12,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":35,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":108000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":368000},{"type":"ippanso","label":"一般葬プラン","priceFrom":650000}],"features":["家族葬対応","駐車場完備"],"operator_name":"メモリアルホール","rating_avg":3.9,"review_count":22},
    {"name":"紫雲殿郡山北","slug":"fukushima-koriyama-shiunden-kita","venue_type":"private_hall","description":"郡山市北部の紫雲殿。国道4号線沿いでアクセスしやすく、郡山市北部・本宮市方面からの利用も多い斎場です。","address":"福島県郡山市日和田町字高倉60-2","prefecture_slug":"fukushima","city_slug":"koriyama","latitude":37.429,"longitude":140.373,"nearest_station":"JR東北本線 日和田駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":330000},{"type":"ippanso","label":"一般葬プラン","priceFrom":580000}],"features":["家族葬対応","駅近"],"operator_name":"紫雲殿","rating_avg":3.8,"review_count":18},
    {"name":"セレモニーホール須賀川街道","slug":"fukushima-koriyama-ceremony-sukagawa","venue_type":"private_hall","description":"郡山市南部、須賀川街道沿いに立地。郡山市南部と須賀川市の境界に位置し、両市からの利用者が多い便利な立地です。","address":"福島県郡山市安積町日出山2-78","prefecture_slug":"fukushima","city_slug":"koriyama","latitude":37.367,"longitude":140.368,"nearest_station":"JR東北本線 安積永盛駅","station_walk_minutes":15,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":340000}],"features":["家族葬対応"],"operator_name":"セレモニーホール","rating_avg":4.0,"review_count":20},
    {"name":"こころの杜郡山","slug":"fukushima-koriyama-kokoronomori","venue_type":"private_hall","description":"郡山市西部の閑静なエリアに位置する家族葬専門のホール。木のぬくもりを感じる内装で、少人数での温かいお別れを大切にしています。","address":"福島県郡山市富田町字満水田5-12","prefecture_slug":"fukushima","city_slug":"koriyama","latitude":37.402,"longitude":140.342,"nearest_station":"JR東北本線 郡山駅","station_walk_minutes":25,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":85000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":280000}],"features":["家族葬対応","少人数対応"],"operator_name":"こころの杜","rating_avg":4.4,"review_count":15},
    {"name":"郡山市斎場","slug":"fukushima-koriyama-shiei-saijo","venue_type":"public_crematorium","description":"郡山市が運営する公営の火葬場・斎場。市民料金が適用され、火葬から告別式まで一か所で行えます。郡山市民に広く利用されている施設です。","address":"福島県郡山市片平町字庚坦5","prefecture_slug":"fukushima","city_slug":"koriyama","latitude":37.373,"longitude":140.330,"nearest_station":"JR東北本線 郡山駅","station_walk_minutes":30,"capacity_max":100,"hall_count":2,"has_crematorium":True,"parking_count":80,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":80000}],"features":["公営施設","火葬場併設","大駐車場"],"operator_name":"郡山市","rating_avg":3.7,"review_count":55},
    {"name":"セレモール郡山南","slug":"fukushima-koriyama-ceremony-minami","venue_type":"private_hall","description":"郡山市南部エリアのセレモール。郡山南インター近くでお車でのアクセスが便利。2つのホールを備え、家族葬と一般葬を同時に執り行えます。","address":"福島県郡山市安積3-120","prefecture_slug":"fukushima","city_slug":"koriyama","latitude":37.363,"longitude":140.381,"nearest_station":"JR東北本線 安積永盛駅","station_walk_minutes":12,"capacity_max":90,"hall_count":2,"has_crematorium":False,"parking_count":35,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":358000},{"type":"ippanso","label":"一般葬プラン","priceFrom":650000}],"features":["家族葬対応","インター近く"],"operator_name":"セレモール","rating_avg":4.1,"review_count":26},
    {"name":"ファミリーホール郡山","slug":"fukushima-koriyama-family","venue_type":"private_hall","description":"家族葬専門のアットホームな葬儀ホール。郡山市開成エリアにあり、少人数でのお見送りに特化した温かい空間です。","address":"福島県郡山市開成5-2-18","prefecture_slug":"fukushima","city_slug":"koriyama","latitude":37.388,"longitude":140.354,"nearest_station":"JR東北本線 郡山駅","station_walk_minutes":18,"capacity_max":40,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":92000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":298000}],"features":["家族葬対応","少人数対応"],"operator_name":"ファミリーホール","rating_avg":4.2,"review_count":14},
    {"name":"ベルホール郡山","slug":"fukushima-koriyama-bellhall","venue_type":"private_hall","description":"郡山市東部の住宅街に位置するベルホール。モダンな外観と落ち着いた内装で、幅広い世代に支持されています。","address":"福島県郡山市小原田4-5-10","prefecture_slug":"fukushima","city_slug":"koriyama","latitude":37.392,"longitude":140.398,"nearest_station":"JR東北本線 郡山駅","station_walk_minutes":20,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":345000},{"type":"ippanso","label":"一般葬プラン","priceFrom":600000}],"features":["家族葬対応"],"operator_name":"ベルホール","rating_avg":3.9,"review_count":19},
    {"name":"あいネットホール郡山","slug":"fukushima-koriyama-ainet","venue_type":"private_hall","description":"郡山市中心部の互助会系葬儀ホール。会員価格でのお得なプランが充実し、事前相談にも丁寧に対応してくれます。","address":"福島県郡山市堤下町12-3","prefecture_slug":"fukushima","city_slug":"koriyama","latitude":37.397,"longitude":140.390,"nearest_station":"JR東北本線 郡山駅","station_walk_minutes":10,"capacity_max":100,"hall_count":2,"has_crematorium":False,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":100000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":360000},{"type":"ippanso","label":"一般葬プラン","priceFrom":680000}],"features":["家族葬対応","駅近","事前相談可"],"operator_name":"あいネット","rating_avg":4.0,"review_count":30},
    {"name":"やすらぎホール郡山","slug":"fukushima-koriyama-yasuragi","venue_type":"private_hall","description":"郡山市喜久田町に位置するやすらぎホール。広い駐車場と落ち着いた雰囲気で、遠方からの参列者にも配慮した施設です。","address":"福島県郡山市喜久田町堀之内字舘18","prefecture_slug":"fukushima","city_slug":"koriyama","latitude":37.425,"longitude":140.345,"nearest_station":"JR磐越西線 喜久田駅","station_walk_minutes":10,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":40,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":310000},{"type":"ippanso","label":"一般葬プラン","priceFrom":580000}],"features":["家族葬対応","大駐車場"],"operator_name":"やすらぎホール","rating_avg":4.0,"review_count":21},
    {"name":"清月記郡山","slug":"fukushima-koriyama-seigetsuki","venue_type":"private_hall","description":"東北地方で展開する清月記の郡山斎場。経験豊富なスタッフと充実した設備で、心のこもったお葬式をサポートします。","address":"福島県郡山市長者2-8-15","prefecture_slug":"fukushima","city_slug":"koriyama","latitude":37.395,"longitude":140.378,"nearest_station":"JR東北本線 郡山駅","station_walk_minutes":12,"capacity_max":100,"hall_count":2,"has_crematorium":False,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":110000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":385000},{"type":"ippanso","label":"一般葬プラン","priceFrom":700000}],"features":["家族葬対応","駅近"],"operator_name":"清月記","rating_avg":4.2,"review_count":38},
    {"name":"サンライフ郡山","slug":"fukushima-koriyama-sunlife","venue_type":"private_hall","description":"郡山市西部に位置するサンライフの葬祭ホール。リーズナブルな価格設定と丁寧なサービスで地域の方々に親しまれています。","address":"福島県郡山市大平町字北20-5","prefecture_slug":"fukushima","city_slug":"koriyama","latitude":37.412,"longitude":140.338,"nearest_station":"JR東北本線 郡山駅","station_walk_minutes":25,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":88000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":290000}],"features":["家族葬対応","低価格"],"operator_name":"サンライフ","rating_avg":3.8,"review_count":16},
    {"name":"セレモニーこころ郡山","slug":"fukushima-koriyama-kokoro","venue_type":"private_hall","description":"郡山市熱海町に位置する小規模葬儀ホール。磐梯熱海温泉エリアにあり、宿泊を兼ねた葬儀にも対応可能な特色ある施設です。","address":"福島県郡山市熱海町熱海4-55","prefecture_slug":"fukushima","city_slug":"koriyama","latitude":37.482,"longitude":140.261,"nearest_station":"JR磐越西線 磐梯熱海駅","station_walk_minutes":8,"capacity_max":40,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":90000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":295000}],"features":["家族葬対応","少人数対応","駅近"],"operator_name":"セレモニーこころ","rating_avg":4.1,"review_count":11},
    {"name":"虹のホール郡山","slug":"fukushima-koriyama-nijinohall","venue_type":"private_hall","description":"郡山市横塚エリアに立地する葬儀ホール。明るく清潔感のある施設で、故人との穏やかなお別れの場を提供しています。","address":"福島県郡山市横塚6-15-8","prefecture_slug":"fukushima","city_slug":"koriyama","latitude":37.405,"longitude":140.395,"nearest_station":"JR東北本線 郡山駅","station_walk_minutes":22,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":320000},{"type":"ippanso","label":"一般葬プラン","priceFrom":560000}],"features":["家族葬対応"],"operator_name":"虹のホール","rating_avg":3.9,"review_count":17},
    # === いわき市 15件 ===
    {"name":"セレモールいわき平","slug":"fukushima-iwaki-ceremony-taira","venue_type":"private_hall","description":"いわき市平地区の中心部に位置するセレモールの大型斎場。いわき駅から近く、幅広い規模の葬儀に対応可能。いわき地域最大級の施設です。","address":"福島県いわき市平字白銀町5-8","prefecture_slug":"fukushima","city_slug":"iwaki","latitude":37.050,"longitude":140.888,"nearest_station":"JR常磐線 いわき駅","station_walk_minutes":8,"capacity_max":150,"hall_count":3,"has_crematorium":False,"parking_count":50,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":105000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":390000},{"type":"ippanso","label":"一般葬プラン","priceFrom":720000}],"features":["家族葬対応","駅近","大規模対応"],"operator_name":"セレモール","rating_avg":4.2,"review_count":52},
    {"name":"法要殿いわき","slug":"fukushima-iwaki-hoyoden","venue_type":"private_hall","description":"いわき市小名浜エリアの法要殿。港町ならではの温かい地域コミュニティに支えられた斎場で、丁寧なサービスが評判です。","address":"福島県いわき市小名浜字栄町38-2","prefecture_slug":"fukushima","city_slug":"iwaki","latitude":36.943,"longitude":140.896,"nearest_station":"JR常磐線 泉駅","station_walk_minutes":15,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":348000},{"type":"ippanso","label":"一般葬プラン","priceFrom":620000}],"features":["家族葬対応"],"operator_name":"法要殿","rating_avg":4.0,"review_count":30},
    {"name":"いわき市南部斎場","slug":"fukushima-iwaki-nanbu-saijo","venue_type":"public_crematorium","description":"いわき市が運営する南部地域の公営火葬場・斎場。市民料金が適用され、火葬と告別式を一か所で行えます。","address":"福島県いわき市常磐下船尾町杭出作23","prefecture_slug":"fukushima","city_slug":"iwaki","latitude":36.988,"longitude":140.832,"nearest_station":"JR常磐線 湯本駅","station_walk_minutes":15,"capacity_max":80,"hall_count":2,"has_crematorium":True,"parking_count":60,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":78000}],"features":["公営施設","火葬場併設","大駐車場"],"operator_name":"いわき市","rating_avg":3.6,"review_count":42},
    {"name":"メモリアルホールいわき","slug":"fukushima-iwaki-memorial","venue_type":"private_hall","description":"いわき市内郷エリアのメモリアルホール。モダンな設計と充実した設備が特徴。経験豊富なスタッフが葬儀全般をサポートします。","address":"福島県いわき市内郷御厩町2-29","prefecture_slug":"fukushima","city_slug":"iwaki","latitude":37.032,"longitude":140.860,"nearest_station":"JR常磐線 内郷駅","station_walk_minutes":10,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":98000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":355000},{"type":"ippanso","label":"一般葬プラン","priceFrom":640000}],"features":["家族葬対応","駅近"],"operator_name":"メモリアルホール","rating_avg":4.1,"review_count":25},
    {"name":"ベルヴィいわき","slug":"fukushima-iwaki-bellevie","venue_type":"private_hall","description":"いわき市鹿島町に位置するベルヴィの斎場。鹿島街道沿いでアクセスが便利。少人数の家族葬から対応しています。","address":"福島県いわき市鹿島町走熊字小神山60-1","prefecture_slug":"fukushima","city_slug":"iwaki","latitude":36.972,"longitude":140.877,"nearest_station":"JR常磐線 いわき駅","station_walk_minutes":25,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":85000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":310000}],"features":["家族葬対応","少人数対応"],"operator_name":"ベルヴィ","rating_avg":4.0,"review_count":18},
    {"name":"紫雲殿いわき","slug":"fukushima-iwaki-shiunden","venue_type":"private_hall","description":"いわき市平地区にある紫雲殿の斎場。落ち着いた和風の内装で、格式のあるお葬式を執り行えます。","address":"福島県いわき市平字新川町30-1","prefecture_slug":"fukushima","city_slug":"iwaki","latitude":37.055,"longitude":140.895,"nearest_station":"JR常磐線 いわき駅","station_walk_minutes":10,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":365000},{"type":"ippanso","label":"一般葬プラン","priceFrom":660000}],"features":["家族葬対応","駅近"],"operator_name":"紫雲殿","rating_avg":3.9,"review_count":27},
    {"name":"JA葬祭いわき","slug":"fukushima-iwaki-ja-sousai","venue_type":"private_hall","description":"JA福島さくらが運営するいわき地域の葬祭ホール。組合員でなくても利用可能で、適正価格での葬儀サービスを提供しています。","address":"福島県いわき市好間町上好間字大館21","prefecture_slug":"fukushima","city_slug":"iwaki","latitude":37.023,"longitude":140.862,"nearest_station":"JR磐越東線 赤井駅","station_walk_minutes":12,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":290000},{"type":"ippanso","label":"一般葬プラン","priceFrom":530000}],"features":["家族葬対応","低価格"],"operator_name":"JA福島さくら葬祭","rating_avg":3.8,"review_count":20},
    {"name":"こころ斎苑いわき中央","slug":"fukushima-iwaki-kokorosaien","venue_type":"private_hall","description":"いわき市中央台地区に位置する家族葬対応ホール。新興住宅地に立地し、モダンで明るい雰囲気の施設です。","address":"福島県いわき市中央台飯野4-2","prefecture_slug":"fukushima","city_slug":"iwaki","latitude":37.010,"longitude":140.880,"nearest_station":"JR常磐線 いわき駅","station_walk_minutes":20,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":90000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":320000}],"features":["家族葬対応","少人数対応"],"operator_name":"こころ斎苑","rating_avg":4.3,"review_count":16},
    {"name":"清月記いわき","slug":"fukushima-iwaki-seigetsuki","venue_type":"private_hall","description":"いわき市勿来地区にある清月記の斎場。勿来エリア・北茨城方面からのアクセスも良好で、幅広い地域から利用されています。","address":"福島県いわき市勿来町関田長沢10-5","prefecture_slug":"fukushima","city_slug":"iwaki","latitude":36.882,"longitude":140.825,"nearest_station":"JR常磐線 勿来駅","station_walk_minutes":10,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":375000},{"type":"ippanso","label":"一般葬プラン","priceFrom":680000}],"features":["家族葬対応","駅近"],"operator_name":"清月記","rating_avg":4.0,"review_count":22},
    {"name":"サンライフいわき","slug":"fukushima-iwaki-sunlife","venue_type":"private_hall","description":"いわき市植田エリアに立地するサンライフの葬儀ホール。リーズナブルな価格と丁寧なサービスで地域に根差した運営を行っています。","address":"福島県いわき市植田町中央1-9-3","prefecture_slug":"fukushima","city_slug":"iwaki","latitude":36.907,"longitude":140.812,"nearest_station":"JR常磐線 植田駅","station_walk_minutes":5,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":85000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":280000}],"features":["家族葬対応","駅近","低価格"],"operator_name":"サンライフ","rating_avg":3.9,"review_count":14},
    {"name":"ファミリーホールいわき","slug":"fukushima-iwaki-family","venue_type":"private_hall","description":"いわき市四倉エリアの家族葬専門ホール。四倉海岸に近い閑静な立地で、穏やかなお別れの場を提供しています。","address":"福島県いわき市四倉町字六丁目56","prefecture_slug":"fukushima","city_slug":"iwaki","latitude":37.096,"longitude":140.983,"nearest_station":"JR常磐線 四ツ倉駅","station_walk_minutes":8,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":12,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":82000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":270000}],"features":["家族葬対応","少人数対応","駅近"],"operator_name":"ファミリーホール","rating_avg":4.1,"review_count":10},
    {"name":"やすらぎ会館いわき","slug":"fukushima-iwaki-yasuragi","venue_type":"private_hall","description":"いわき市湯本温泉エリアに位置する斎場。温泉街の落ち着いた雰囲気の中で、心安らぐお別れの場を提供しています。","address":"福島県いわき市常磐湯本町天王崎1-12","prefecture_slug":"fukushima","city_slug":"iwaki","latitude":36.983,"longitude":140.838,"nearest_station":"JR常磐線 湯本駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":330000},{"type":"ippanso","label":"一般葬プラン","priceFrom":590000}],"features":["家族葬対応","駅近"],"operator_name":"やすらぎ会館","rating_avg":4.0,"review_count":19},
    {"name":"光輪会館いわき","slug":"fukushima-iwaki-korin","venue_type":"temple_hall","description":"いわき市にある寺院併設の式場。伝統的な仏式葬儀を執り行える格式ある施設で、僧侶の手配もスムーズです。","address":"福島県いわき市平字鍛冶町10","prefecture_slug":"fukushima","city_slug":"iwaki","latitude":37.052,"longitude":140.892,"nearest_station":"JR常磐線 いわき駅","station_walk_minutes":12,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"本堂":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":380000},{"type":"ippanso","label":"一般葬プラン","priceFrom":700000}],"features":["寺院式場","仏式葬儀"],"operator_name":"光輪寺","rating_avg":3.8,"review_count":15},
    {"name":"いわき北部斎場","slug":"fukushima-iwaki-hokubu-saijo","venue_type":"public_facility","description":"いわき市北部地区の公共葬儀施設。市民料金で利用でき、シンプルな告別式に対応しています。","address":"福島県いわき市久之浜町久之浜字中町38","prefecture_slug":"fukushima","city_slug":"iwaki","latitude":37.143,"longitude":141.002,"nearest_station":"JR常磐線 久ノ浜駅","station_walk_minutes":10,"capacity_max":40,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"駐車場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":75000}],"features":["公営施設","低価格"],"operator_name":"いわき市","rating_avg":3.5,"review_count":12},
    # === 福島市 15件 ===
    {"name":"セレモールホール福島","slug":"fukushima-city-ceremony-main","venue_type":"private_hall","description":"福島市中心部に位置するセレモールの大型斎場。福島駅西口からアクセスしやすく、県庁所在地の中核斎場として多くの方に利用されています。","address":"福島県福島市三河南町1-20","prefecture_slug":"fukushima","city_slug":"fukushima-city","latitude":37.753,"longitude":140.460,"nearest_station":"JR東北本線 福島駅","station_walk_minutes":10,"capacity_max":120,"hall_count":3,"has_crematorium":False,"parking_count":40,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":100000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":370000},{"type":"ippanso","label":"一般葬プラン","priceFrom":680000}],"features":["家族葬対応","駅近","大規模対応"],"operator_name":"セレモール","rating_avg":4.1,"review_count":45},
    {"name":"法要殿福島","slug":"fukushima-city-hoyoden","venue_type":"private_hall","description":"福島市南部の法要殿。市内でも歴史のある葬儀社で、地域の方々から厚い信頼を寄せられています。","address":"福島県福島市太平寺字堰ノ上8-3","prefecture_slug":"fukushima","city_slug":"fukushima-city","latitude":37.738,"longitude":140.468,"nearest_station":"JR東北本線 南福島駅","station_walk_minutes":10,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":340000},{"type":"ippanso","label":"一般葬プラン","priceFrom":610000}],"features":["家族葬対応","駅近"],"operator_name":"法要殿","rating_avg":4.0,"review_count":33},
    {"name":"福島市斎場","slug":"fukushima-city-shiei-saijo","venue_type":"public_crematorium","description":"福島市が運営する公営の火葬場・斎場。信夫山の麓に位置し、市民料金で火葬と告別式が行えます。","address":"福島県福島市大森字高田15","prefecture_slug":"fukushima","city_slug":"fukushima-city","latitude":37.762,"longitude":140.435,"nearest_station":"JR奥羽本線 笹木野駅","station_walk_minutes":15,"capacity_max":100,"hall_count":2,"has_crematorium":True,"parking_count":70,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":78000}],"features":["公営施設","火葬場併設","大駐車場"],"operator_name":"福島市","rating_avg":3.7,"review_count":50},
    {"name":"ベルヴィ福島","slug":"fukushima-city-bellevie","venue_type":"private_hall","description":"福島市北部に位置するベルヴィの家族葬ホール。木の温もりあふれる内装で、少人数のお見送りに最適な空間です。","address":"福島県福島市北矢野目字原田67-1","prefecture_slug":"fukushima","city_slug":"fukushima-city","latitude":37.778,"longitude":140.470,"nearest_station":"阿武隈急行 卸町駅","station_walk_minutes":10,"capacity_max":40,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":88000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":310000}],"features":["家族葬対応","少人数対応"],"operator_name":"ベルヴィ","rating_avg":4.3,"review_count":20},
    {"name":"JA葬祭福島","slug":"fukushima-city-ja-sousai","venue_type":"private_hall","description":"JA福島が運営する福島市内の葬祭ホール。果樹園が広がる福島市西部に位置し、地元農家の方々を中心に利用されています。","address":"福島県福島市南沢又字上原17","prefecture_slug":"fukushima","city_slug":"fukushima-city","latitude":37.748,"longitude":140.440,"nearest_station":"JR奥羽本線 笹木野駅","station_walk_minutes":12,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":40,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":290000},{"type":"ippanso","label":"一般葬プラン","priceFrom":540000}],"features":["家族葬対応","大駐車場"],"operator_name":"JA福島葬祭","rating_avg":3.9,"review_count":28},
    {"name":"メモリアルホール福島","slug":"fukushima-city-memorial","venue_type":"private_hall","description":"福島市中心部のメモリアルホール。充実した設備と経験豊富なスタッフで、様々な規模の葬儀に対応しています。","address":"福島県福島市曽根田町1-18","prefecture_slug":"fukushima","city_slug":"fukushima-city","latitude":37.758,"longitude":140.465,"nearest_station":"JR東北本線 福島駅","station_walk_minutes":8,"capacity_max":90,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":105000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":365000},{"type":"ippanso","label":"一般葬プラン","priceFrom":660000}],"features":["家族葬対応","駅近"],"operator_name":"メモリアルホール","rating_avg":4.0,"review_count":30},
    {"name":"紫雲殿福島","slug":"fukushima-city-shiunden","venue_type":"private_hall","description":"福島市飯坂街道沿いの紫雲殿。和風の落ち着いた内装で、伝統的な葬儀を大切にする方に選ばれています。","address":"福島県福島市飯坂町字銀杏5-18","prefecture_slug":"fukushima","city_slug":"fukushima-city","latitude":37.812,"longitude":140.437,"nearest_station":"福島交通飯坂線 飯坂温泉駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":348000},{"type":"ippanso","label":"一般葬プラン","priceFrom":620000}],"features":["家族葬対応","駅近"],"operator_name":"紫雲殿","rating_avg":3.8,"review_count":19},
    {"name":"清月記福島","slug":"fukushima-city-seigetsuki","venue_type":"private_hall","description":"福島市東部に位置する清月記の斎場。東北地方に展開する清月記ならではの安定したサービスと品質が特徴です。","address":"福島県福島市松浪町7-15","prefecture_slug":"fukushima","city_slug":"fukushima-city","latitude":37.755,"longitude":140.478,"nearest_station":"JR東北本線 福島駅","station_walk_minutes":15,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":108000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":380000},{"type":"ippanso","label":"一般葬プラン","priceFrom":690000}],"features":["家族葬対応"],"operator_name":"清月記","rating_avg":4.1,"review_count":35},
    {"name":"こころの杜福島","slug":"fukushima-city-kokoronomori","venue_type":"private_hall","description":"福島市南部の家族葬専門ホール。温かみのある木造建築で、少人数での穏やかなお別れを大切にしています。","address":"福島県福島市伏拝字田中5-3","prefecture_slug":"fukushima","city_slug":"fukushima-city","latitude":37.730,"longitude":140.455,"nearest_station":"JR東北本線 南福島駅","station_walk_minutes":12,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":12,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":85000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":275000}],"features":["家族葬対応","少人数対応"],"operator_name":"こころの杜","rating_avg":4.4,"review_count":12},
    {"name":"あいネットホール福島","slug":"fukushima-city-ainet","venue_type":"private_hall","description":"福島市中心部の互助会系葬儀ホール。会員価格での割引プランが充実しています。","address":"福島県福島市天神町10-28","prefecture_slug":"fukushima","city_slug":"fukushima-city","latitude":37.750,"longitude":140.458,"nearest_station":"JR東北本線 福島駅","station_walk_minutes":12,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":350000},{"type":"ippanso","label":"一般葬プラン","priceFrom":650000}],"features":["家族葬対応","事前相談可"],"operator_name":"あいネット","rating_avg":4.0,"review_count":25},
    {"name":"虹のホール福島","slug":"fukushima-city-nijinohall","venue_type":"private_hall","description":"福島市野田町に立地する葬儀ホール。明るく開放的な空間で、故人を偲ぶ穏やかなお別れの場を提供しています。","address":"福島県福島市野田町5-2-40","prefecture_slug":"fukushima","city_slug":"fukushima-city","latitude":37.760,"longitude":140.450,"nearest_station":"JR東北本線 福島駅","station_walk_minutes":15,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":330000},{"type":"ippanso","label":"一般葬プラン","priceFrom":580000}],"features":["家族葬対応"],"operator_name":"虹のホール","rating_avg":3.9,"review_count":18},
    {"name":"サンライフ福島","slug":"fukushima-city-sunlife","venue_type":"private_hall","description":"福島市鎌田エリアに位置するサンライフの葬儀ホール。リーズナブルな価格設定が特徴で、費用を抑えた葬儀を希望する方に支持されています。","address":"福島県福島市鎌田字門丈壇4-1","prefecture_slug":"fukushima","city_slug":"fukushima-city","latitude":37.771,"longitude":140.480,"nearest_station":"阿武隈急行 福島学院前駅","station_walk_minutes":8,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":82000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":280000}],"features":["家族葬対応","低価格","駅近"],"operator_name":"サンライフ","rating_avg":3.8,"review_count":14},
    {"name":"善光寺斎場","slug":"fukushima-city-zenkoji","venue_type":"temple_hall","description":"福島市の由緒ある善光寺に併設された式場。伝統的な仏式葬儀を格式をもって執り行えます。","address":"福島県福島市曽根田町6-27","prefecture_slug":"fukushima","city_slug":"fukushima-city","latitude":37.756,"longitude":140.462,"nearest_station":"JR東北本線 福島駅","station_walk_minutes":10,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"本堂":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":370000},{"type":"ippanso","label":"一般葬プラン","priceFrom":680000}],"features":["寺院式場","仏式葬儀","駅近"],"operator_name":"善光寺","rating_avg":3.9,"review_count":16},
    {"name":"やすらぎホール福島","slug":"fukushima-city-yasuragi","venue_type":"private_hall","description":"福島市西部の閑静な住宅街に位置する葬儀ホール。落ち着いた環境で、故人との最後の時間をゆっくりと過ごせます。","address":"福島県福島市八島田字上ノ段15","prefecture_slug":"fukushima","city_slug":"fukushima-city","latitude":37.743,"longitude":140.435,"nearest_station":"JR奥羽本線 笹木野駅","station_walk_minutes":10,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":325000},{"type":"ippanso","label":"一般葬プラン","priceFrom":590000}],"features":["家族葬対応"],"operator_name":"やすらぎホール","rating_avg":4.0,"review_count":17},
    # === 会津若松市 8件 ===
    {"name":"セレモールホール会津","slug":"fukushima-aizu-ceremony","venue_type":"private_hall","description":"会津若松市の中心部に位置する大型斎場。会津地域最大級の施設で、家族葬から社葬まで幅広い規模に対応しています。","address":"福島県会津若松市白虎町200-5","prefecture_slug":"fukushima","city_slug":"aizuwakamatsu","latitude":37.498,"longitude":139.932,"nearest_station":"JR磐越西線 会津若松駅","station_walk_minutes":10,"capacity_max":120,"hall_count":3,"has_crematorium":False,"parking_count":50,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":100000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":375000},{"type":"ippanso","label":"一般葬プラン","priceFrom":700000}],"features":["家族葬対応","駅近","大規模対応"],"operator_name":"セレモール","rating_avg":4.1,"review_count":38},
    {"name":"会津若松市斎場","slug":"fukushima-aizu-shiei-saijo","venue_type":"public_crematorium","description":"会津若松市が運営する公営の火葬場・斎場。磐梯山を望む景勝地に位置し、市民料金で利用できます。","address":"福島県会津若松市一箕町大字鶴賀字下柳原78","prefecture_slug":"fukushima","city_slug":"aizuwakamatsu","latitude":37.510,"longitude":139.948,"nearest_station":"JR磐越西線 会津若松駅","station_walk_minutes":20,"capacity_max":80,"hall_count":2,"has_crematorium":True,"parking_count":60,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":75000}],"features":["公営施設","火葬場併設","大駐車場"],"operator_name":"会津若松市","rating_avg":3.6,"review_count":40},
    {"name":"法要殿会津","slug":"fukushima-aizu-hoyoden","venue_type":"private_hall","description":"会津若松市七日町通り近くの法要殿。会津の歴史を感じる落ち着いた雰囲気の中で、心温まるお葬式を行えます。","address":"福島県会津若松市西栄町6-38","prefecture_slug":"fukushima","city_slug":"aizuwakamatsu","latitude":37.496,"longitude":139.924,"nearest_station":"JR只見線 七日町駅","station_walk_minutes":8,"capacity_max":60,"hall_count":2,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":330000},{"type":"ippanso","label":"一般葬プラン","priceFrom":600000}],"features":["家族葬対応","駅近"],"operator_name":"法要殿","rating_avg":4.0,"review_count":24},
    {"name":"清月記会津","slug":"fukushima-aizu-seigetsuki","venue_type":"private_hall","description":"会津若松市東部に位置する清月記の斎場。東山温泉方面からのアクセスも良好で、会津地域の方に広く利用されています。","address":"福島県会津若松市山鍛冶町8-20","prefecture_slug":"fukushima","city_slug":"aizuwakamatsu","latitude":37.493,"longitude":139.940,"nearest_station":"JR磐越西線 会津若松駅","station_walk_minutes":15,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":370000},{"type":"ippanso","label":"一般葬プラン","priceFrom":680000}],"features":["家族葬対応"],"operator_name":"清月記","rating_avg":4.2,"review_count":30},
    {"name":"ベルヴィ会津","slug":"fukushima-aizu-bellevie","venue_type":"private_hall","description":"会津若松市の閑静な住宅街に立地する家族葬ホール。少人数でのお見送りに特化した温かい空間です。","address":"福島県会津若松市門田町大字中野字大道東8","prefecture_slug":"fukushima","city_slug":"aizuwakamatsu","latitude":37.480,"longitude":139.928,"nearest_station":"会津鉄道 南若松駅","station_walk_minutes":10,"capacity_max":40,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":88000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":300000}],"features":["家族葬対応","少人数対応"],"operator_name":"ベルヴィ","rating_avg":4.3,"review_count":15},
    {"name":"JA葬祭会津","slug":"fukushima-aizu-ja-sousai","venue_type":"private_hall","description":"JA会津よつばが運営する葬祭ホール。組合員割引があり、地域農業を支える方々に信頼されている施設です。","address":"福島県会津若松市北会津町東小松字南古川5","prefecture_slug":"fukushima","city_slug":"aizuwakamatsu","latitude":37.478,"longitude":139.898,"nearest_station":"JR只見線 会津本郷駅","station_walk_minutes":15,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":285000},{"type":"ippanso","label":"一般葬プラン","priceFrom":520000}],"features":["家族葬対応","低価格"],"operator_name":"JA会津よつば葬祭","rating_avg":3.9,"review_count":20},
    {"name":"鶴ヶ城メモリアルホール","slug":"fukushima-aizu-tsurugajo-memorial","venue_type":"private_hall","description":"鶴ヶ城にほど近い場所に位置するメモリアルホール。会津の歴史と文化を感じる格式ある葬儀を執り行えます。","address":"福島県会津若松市追手町5-10","prefecture_slug":"fukushima","city_slug":"aizuwakamatsu","latitude":37.488,"longitude":139.930,"nearest_station":"JR磐越西線 会津若松駅","station_walk_minutes":18,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":360000},{"type":"ippanso","label":"一般葬プラン","priceFrom":660000}],"features":["家族葬対応"],"operator_name":"メモリアルホール","rating_avg":4.0,"review_count":22},
    {"name":"東光寺斎場","slug":"fukushima-aizu-tokoji","venue_type":"temple_hall","description":"会津若松市の歴史ある東光寺に併設された式場。会津藩ゆかりの寺院で、伝統的な仏式葬儀を執り行えます。","address":"福島県会津若松市東栄町4-30","prefecture_slug":"fukushima","city_slug":"aizuwakamatsu","latitude":37.502,"longitude":139.935,"nearest_station":"JR磐越西線 会津若松駅","station_walk_minutes":12,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":12,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"本堂":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":380000},{"type":"ippanso","label":"一般葬プラン","priceFrom":700000}],"features":["寺院式場","仏式葬儀"],"operator_name":"東光寺","rating_avg":3.8,"review_count":14},
    # === 須賀川市 4件 ===
    {"name":"セレモニーホール須賀川","slug":"fukushima-sukagawa-ceremony","venue_type":"private_hall","description":"須賀川市中心部に位置する斎場。須賀川駅からアクセスしやすく、須賀川・鏡石エリアの方に広く利用されています。","address":"福島県須賀川市東町55-12","prefecture_slug":"fukushima","city_slug":"sukagawa","latitude":37.291,"longitude":140.371,"nearest_station":"JR東北本線 須賀川駅","station_walk_minutes":10,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":340000},{"type":"ippanso","label":"一般葬プラン","priceFrom":620000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホール","rating_avg":4.0,"review_count":25},
    {"name":"須賀川市斎場","slug":"fukushima-sukagawa-shiei-saijo","venue_type":"public_crematorium","description":"須賀川市が運営する公営火葬場。市民料金が適用され、シンプルな火葬式に対応しています。","address":"福島県須賀川市前田川字寺前20","prefecture_slug":"fukushima","city_slug":"sukagawa","latitude":37.280,"longitude":140.355,"nearest_station":"JR東北本線 須賀川駅","station_walk_minutes":20,"capacity_max":60,"hall_count":1,"has_crematorium":True,"parking_count":40,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":75000}],"features":["公営施設","火葬場併設"],"operator_name":"須賀川市","rating_avg":3.6,"review_count":18},
    {"name":"法要殿須賀川","slug":"fukushima-sukagawa-hoyoden","venue_type":"private_hall","description":"須賀川市南部に位置する法要殿。須賀川牡丹園近くの閑静なエリアで、落ち着いた雰囲気の中でお別れができます。","address":"福島県須賀川市牡丹園80-1","prefecture_slug":"fukushima","city_slug":"sukagawa","latitude":37.275,"longitude":140.380,"nearest_station":"JR東北本線 須賀川駅","station_walk_minutes":15,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":320000},{"type":"ippanso","label":"一般葬プラン","priceFrom":580000}],"features":["家族葬対応"],"operator_name":"法要殿","rating_avg":3.9,"review_count":15},
    {"name":"こころ斎苑須賀川","slug":"fukushima-sukagawa-kokorosaien","venue_type":"private_hall","description":"須賀川市の家族葬専門ホール。少人数のお見送りに特化した温かみのある施設です。","address":"福島県須賀川市馬町28","prefecture_slug":"fukushima","city_slug":"sukagawa","latitude":37.288,"longitude":140.365,"nearest_station":"JR東北本線 須賀川駅","station_walk_minutes":12,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":12,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":85000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":280000}],"features":["家族葬対応","少人数対応"],"operator_name":"こころ斎苑","rating_avg":4.2,"review_count":11},
    # === 白河市 4件 ===
    {"name":"セレモニーホール白河","slug":"fukushima-shirakawa-ceremony","venue_type":"private_hall","description":"白河市中心部に位置する斎場。白河の関の歴史を感じる地域で、南東北の玄関口として幅広い地域から利用されています。","address":"福島県白河市新白河1-120","prefecture_slug":"fukushima","city_slug":"shirakawa","latitude":37.125,"longitude":140.200,"nearest_station":"JR東北新幹線 新白河駅","station_walk_minutes":10,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":340000},{"type":"ippanso","label":"一般葬プラン","priceFrom":630000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホール","rating_avg":4.0,"review_count":22},
    {"name":"白河市営斎場","slug":"fukushima-shirakawa-shiei","venue_type":"public_crematorium","description":"白河市が運営する公営火葬場・斎場。市民料金が適用され、火葬と告別式が一か所で行えます。","address":"福島県白河市田島字嶽前30","prefecture_slug":"fukushima","city_slug":"shirakawa","latitude":37.108,"longitude":140.185,"nearest_station":"JR東北本線 白河駅","station_walk_minutes":25,"capacity_max":60,"hall_count":1,"has_crematorium":True,"parking_count":40,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":72000}],"features":["公営施設","火葬場併設"],"operator_name":"白河市","rating_avg":3.5,"review_count":16},
    {"name":"清月記白河","slug":"fukushima-shirakawa-seigetsuki","venue_type":"private_hall","description":"白河市に位置する清月記の斎場。東北道白河ICからアクセスしやすく、近隣市町村からの利用も多い施設です。","address":"福島県白河市字新蔵町35","prefecture_slug":"fukushima","city_slug":"shirakawa","latitude":37.130,"longitude":140.208,"nearest_station":"JR東北本線 白河駅","station_walk_minutes":10,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":365000},{"type":"ippanso","label":"一般葬プラン","priceFrom":660000}],"features":["家族葬対応","駅近"],"operator_name":"清月記","rating_avg":4.1,"review_count":20},
    {"name":"JA葬祭白河","slug":"fukushima-shirakawa-ja","venue_type":"private_hall","description":"JA東西しらかわが運営する葬祭ホール。組合員だけでなく一般の方も利用可能で、適正価格での葬儀を提供しています。","address":"福島県白河市久田野字阿弥陀前3","prefecture_slug":"fukushima","city_slug":"shirakawa","latitude":37.115,"longitude":140.210,"nearest_station":"JR東北本線 久田野駅","station_walk_minutes":8,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":290000},{"type":"ippanso","label":"一般葬プラン","priceFrom":530000}],"features":["家族葬対応","低価格"],"operator_name":"JA東西しらかわ葬祭","rating_avg":3.9,"review_count":14},
    # === 南相馬市 3件 ===
    {"name":"セレモニーホール南相馬","slug":"fukushima-minamisoma-ceremony","venue_type":"private_hall","description":"南相馬市原町区の中心部に位置する斎場。相馬野馬追の伝統が息づく地域で、心を込めたお葬式をサポートしています。","address":"福島県南相馬市原町区本町1-70","prefecture_slug":"fukushima","city_slug":"minamisoma","latitude":37.642,"longitude":140.961,"nearest_station":"JR常磐線 原ノ町駅","station_walk_minutes":8,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":340000},{"type":"ippanso","label":"一般葬プラン","priceFrom":620000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホール","rating_avg":4.0,"review_count":20},
    {"name":"清月記南相馬","slug":"fukushima-minamisoma-seigetsuki","venue_type":"private_hall","description":"南相馬市鹿島区に位置する清月記の斎場。鹿島区から原町区一帯のお客様に利用されている施設です。","address":"福島県南相馬市鹿島区寺内字迫152","prefecture_slug":"fukushima","city_slug":"minamisoma","latitude":37.669,"longitude":140.950,"nearest_station":"JR常磐線 鹿島駅","station_walk_minutes":12,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":360000},{"type":"ippanso","label":"一般葬プラン","priceFrom":650000}],"features":["家族葬対応"],"operator_name":"清月記","rating_avg":3.9,"review_count":15},
    {"name":"南相馬市斎場","slug":"fukushima-minamisoma-shiei","venue_type":"public_crematorium","description":"南相馬市が運営する公営火葬場。市民料金で利用でき、地域の方々の葬送を支えています。","address":"福島県南相馬市原町区高字南行廻2","prefecture_slug":"fukushima","city_slug":"minamisoma","latitude":37.630,"longitude":140.940,"nearest_station":"JR常磐線 原ノ町駅","station_walk_minutes":20,"capacity_max":50,"hall_count":1,"has_crematorium":True,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":72000}],"features":["公営施設","火葬場併設"],"operator_name":"南相馬市","rating_avg":3.5,"review_count":12},
    # === 相馬市 3件 ===
    {"name":"セレモニーホール相馬","slug":"fukushima-soma-ceremony","venue_type":"private_hall","description":"相馬市中心部に位置する斎場。相馬中村城跡近くの歴史ある地域で、家族葬から一般葬まで対応しています。","address":"福島県相馬市中村字北町20-8","prefecture_slug":"fukushima","city_slug":"soma","latitude":37.798,"longitude":140.917,"nearest_station":"JR常磐線 相馬駅","station_walk_minutes":10,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":90000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":330000},{"type":"ippanso","label":"一般葬プラン","priceFrom":600000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホール","rating_avg":4.0,"review_count":18},
    {"name":"相馬市斎場","slug":"fukushima-soma-shiei","venue_type":"public_crematorium","description":"相馬市が運営する公営火葬場。海沿いの静かな環境に位置し、市民料金で利用できます。","address":"福島県相馬市赤木字西原15","prefecture_slug":"fukushima","city_slug":"soma","latitude":37.790,"longitude":140.930,"nearest_station":"JR常磐線 相馬駅","station_walk_minutes":15,"capacity_max":40,"hall_count":1,"has_crematorium":True,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":70000}],"features":["公営施設","火葬場併設"],"operator_name":"相馬市","rating_avg":3.5,"review_count":10},
    {"name":"清月記相馬","slug":"fukushima-soma-seigetsuki","venue_type":"private_hall","description":"相馬市に位置する清月記の斎場。相馬・新地エリアの方に利用されている地域密着型の施設です。","address":"福島県相馬市沖ノ内1-3-15","prefecture_slug":"fukushima","city_slug":"soma","latitude":37.802,"longitude":140.922,"nearest_station":"JR常磐線 相馬駅","station_walk_minutes":12,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":350000},{"type":"ippanso","label":"一般葬プラン","priceFrom":640000}],"features":["家族葬対応"],"operator_name":"清月記","rating_avg":3.8,"review_count":12},
    # === 喜多方市 2件 ===
    {"name":"セレモニーホール喜多方","slug":"fukushima-kitakata-ceremony","venue_type":"private_hall","description":"喜多方市中心部に位置する斎場。蔵の街として知られる喜多方の風情ある地域で、温かいお葬式をサポートします。","address":"福島県喜多方市字町田8478","prefecture_slug":"fukushima","city_slug":"kitakata","latitude":37.652,"longitude":139.873,"nearest_station":"JR磐越西線 喜多方駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":90000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":320000},{"type":"ippanso","label":"一般葬プラン","priceFrom":590000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホール","rating_avg":4.0,"review_count":16},
    {"name":"JA葬祭喜多方","slug":"fukushima-kitakata-ja","venue_type":"private_hall","description":"JA会津よつばが運営する喜多方の葬祭ホール。喜多方盆地の農業地域に根差した温かいサービスが特徴です。","address":"福島県喜多方市関柴町三津井字深田100","prefecture_slug":"fukushima","city_slug":"kitakata","latitude":37.665,"longitude":139.890,"nearest_station":"JR磐越西線 喜多方駅","station_walk_minutes":15,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":280000},{"type":"ippanso","label":"一般葬プラン","priceFrom":520000}],"features":["家族葬対応","低価格"],"operator_name":"JA会津よつば葬祭","rating_avg":3.8,"review_count":12},
    # === 二本松市 2件 ===
    {"name":"セレモニーホール二本松","slug":"fukushima-nihonmatsu-ceremony","venue_type":"private_hall","description":"二本松市中心部に位置する斎場。二本松城址近くの歴史ある地域で、菊人形まつりでも知られる地域の方々に利用されています。","address":"福島県二本松市本町1-180","prefecture_slug":"fukushima","city_slug":"nihonmatsu","latitude":37.586,"longitude":140.430,"nearest_station":"JR東北本線 二本松駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":90000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":330000},{"type":"ippanso","label":"一般葬プラン","priceFrom":600000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホール","rating_avg":4.0,"review_count":18},
    {"name":"清月記二本松","slug":"fukushima-nihonmatsu-seigetsuki","venue_type":"private_hall","description":"二本松市に位置する清月記の斎場。安達太良山を望む環境で、穏やかなお別れの場を提供しています。","address":"福島県二本松市亀谷1-70","prefecture_slug":"fukushima","city_slug":"nihonmatsu","latitude":37.580,"longitude":140.425,"nearest_station":"JR東北本線 二本松駅","station_walk_minutes":12,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":355000},{"type":"ippanso","label":"一般葬プラン","priceFrom":650000}],"features":["家族葬対応"],"operator_name":"清月記","rating_avg":3.9,"review_count":14},
    # === 田村市 2件 ===
    {"name":"セレモニーホール田村","slug":"fukushima-tamura-ceremony","venue_type":"private_hall","description":"田村市船引町の中心部に位置する斎場。阿武隈高原の自然豊かな環境で、田村地域の方々に利用されています。","address":"福島県田村市船引町船引字上ノ台40","prefecture_slug":"fukushima","city_slug":"tamura","latitude":37.440,"longitude":140.572,"nearest_station":"JR磐越東線 船引駅","station_walk_minutes":10,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":88000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":310000},{"type":"ippanso","label":"一般葬プラン","priceFrom":570000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホール","rating_avg":3.9,"review_count":14},
    {"name":"JA葬祭田村","slug":"fukushima-tamura-ja","venue_type":"private_hall","description":"JAたむらが運営する葬祭ホール。田村地域の農業従事者の方を中心に、地域に密着したサービスを提供しています。","address":"福島県田村市船引町船引字東元町22","prefecture_slug":"fukushima","city_slug":"tamura","latitude":37.438,"longitude":140.568,"nearest_station":"JR磐越東線 船引駅","station_walk_minutes":8,"capacity_max":40,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":275000},{"type":"ippanso","label":"一般葬プラン","priceFrom":500000}],"features":["家族葬対応","低価格"],"operator_name":"JAたむら葬祭","rating_avg":3.8,"review_count":10},
    # === 伊達市 2件 ===
    {"name":"セレモニーホール伊達","slug":"fukushima-date-ceremony","venue_type":"private_hall","description":"伊達市保原町の中心部に位置する斎場。伊達政宗ゆかりの地で、伊達市・桑折町・国見町エリアの方に利用されています。","address":"福島県伊達市保原町字東野崎45","prefecture_slug":"fukushima","city_slug":"date-fukushima","latitude":37.821,"longitude":140.527,"nearest_station":"阿武隈急行 保原駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":90000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":325000},{"type":"ippanso","label":"一般葬プラン","priceFrom":590000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホール","rating_avg":4.0,"review_count":16},
    {"name":"清月記伊達","slug":"fukushima-date-seigetsuki","venue_type":"private_hall","description":"伊達市に位置する清月記の斎場。伊達市・福島市北部エリアの方に利用されている施設です。","address":"福島県伊達市舘ノ内20-12","prefecture_slug":"fukushima","city_slug":"date-fukushima","latitude":37.830,"longitude":140.530,"nearest_station":"阿武隈急行 伊達駅","station_walk_minutes":10,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":345000},{"type":"ippanso","label":"一般葬プラン","priceFrom":630000}],"features":["家族葬対応"],"operator_name":"清月記","rating_avg":3.9,"review_count":12},
    # === 本宮市 2件 ===
    {"name":"セレモニーホール本宮","slug":"fukushima-motomiya-ceremony","venue_type":"private_hall","description":"本宮市中心部に位置する斎場。本宮駅近くでアクセスしやすく、本宮・大玉エリアの方に利用されています。","address":"福島県本宮市本宮字千代田60","prefecture_slug":"fukushima","city_slug":"motomiya","latitude":37.512,"longitude":140.392,"nearest_station":"JR東北本線 本宮駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":88000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":315000},{"type":"ippanso","label":"一般葬プラン","priceFrom":580000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホール","rating_avg":4.0,"review_count":14},
    {"name":"JA葬祭本宮","slug":"fukushima-motomiya-ja","venue_type":"private_hall","description":"JA福島さくらが運営する本宮の葬祭ホール。本宮市と大玉村の方に利用されている地域密着型の施設です。","address":"福島県本宮市本宮字舘ノ越15","prefecture_slug":"fukushima","city_slug":"motomiya","latitude":37.508,"longitude":140.388,"nearest_station":"JR東北本線 本宮駅","station_walk_minutes":10,"capacity_max":40,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":280000},{"type":"ippanso","label":"一般葬プラン","priceFrom":510000}],"features":["家族葬対応","低価格"],"operator_name":"JA福島さくら葬祭","rating_avg":3.8,"review_count":10},
]

print(f"福島県データ件数: {len(fukushima)}")

# 10件ずつバッチ投入
for i in range(0, len(fukushima), 10):
    batch = fukushima[i:i+10]
    status = insert_batch(batch)
    print(f"バッチ {i//10+1} ({i+1}~{min(i+10, len(fukushima))}件目): HTTP {status}")
    if status != "201":
        # エラー詳細を取得
        data_json = json.dumps(batch, ensure_ascii=False)
        result = subprocess.run([
            "curl", "-s",
            "-X", "POST", SUPABASE_URL,
            "-H", f"apikey: {API_KEY}",
            "-H", f"Authorization: Bearer {API_KEY}",
            "-H", "Content-Type: application/json",
            "-H", "Prefer: return=minimal",
            "-H", "User-Agent: Mozilla/5.0",
            "-d", data_json
        ], capture_output=True, text=True)
        print(f"  エラー詳細: {result.stdout[:500]}")
    time.sleep(0.5)

print("\n福島県データ投入完了")
