# -*- coding: utf-8 -*-
import json, subprocess, time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

# 京都府 バッチ2: 下京区・南区・右京区・伏見区前半 (25件)
kyoto_batch2 = [
    # === 京都市下京区 5件 ===
    {"name":"京都市中央斎場","slug":"kyoto-chuo-saijo","venue_type":"public_crematorium","description":"京都市が運営する中央斎場。五条通沿いに位置し、京都市民の火葬・告別式に広く利用されている公営施設です。市民料金で利用できます。","address":"京都府京都市下京区柿本町590","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.996,"longitude":135.746,"nearest_station":"JR山陰本線 丹波口駅","station_walk_minutes":10,"capacity_max":100,"hall_count":3,"has_crematorium":True,"parking_count":50,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":60000}],"features":["公営施設","火葬場併設","大駐車場"],"operator_name":"京都市","rating_avg":3.7,"review_count":85},
    {"name":"公益社 京都駅前ホール","slug":"kyoto-koekisha-ekimae","venue_type":"private_hall","description":"京都駅から徒歩圏内の公益社ホール。新幹線でのアクセスも便利で、遠方からの参列者が多い葬儀にも最適です。","address":"京都府京都市下京区東塩小路町735-1","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.986,"longitude":135.759,"nearest_station":"JR京都駅","station_walk_minutes":5,"capacity_max":100,"hall_count":2,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":115000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":405000},{"type":"ippanso","label":"一般葬プラン","priceFrom":730000}],"features":["家族葬対応","駅近","アクセス抜群"],"operator_name":"公益社","rating_avg":4.2,"review_count":48},
    {"name":"五条会館 本店","slug":"kyoto-gojo-honten","venue_type":"private_hall","description":"五条通の老舗葬儀社・五条会館の本店。京都で長年の実績を持ち、地域の方々から厚い信頼を寄せられています。","address":"京都府京都市下京区五条通大宮西入堀之上町512","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.997,"longitude":135.744,"nearest_station":"JR山陰本線 丹波口駅","station_walk_minutes":8,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":105000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":385000},{"type":"ippanso","label":"一般葬プラン","priceFrom":690000}],"features":["家族葬対応","老舗葬儀社"],"operator_name":"五条会館","rating_avg":4.1,"review_count":42},
    {"name":"洛王セレモニー京都駅南","slug":"kyoto-rakuo-ekiminami","venue_type":"private_hall","description":"京都駅南側に位置する洛王セレモニー。京都駅八条口から近く、市バスや近鉄でのアクセスも便利です。","address":"京都府京都市下京区東塩小路向畑町48","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.982,"longitude":135.758,"nearest_station":"JR京都駅","station_walk_minutes":7,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":12,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":375000},{"type":"ippanso","label":"一般葬プラン","priceFrom":670000}],"features":["家族葬対応","駅近"],"operator_name":"洛王セレモニー","rating_avg":4.0,"review_count":32},
    {"name":"西本願寺会館","slug":"kyoto-nishihonganji-kaikan","venue_type":"temple_hall","description":"浄土真宗本願寺派の本山・西本願寺に併設された式場。国宝の御影堂を望む荘厳な環境で、伝統ある仏式葬儀を執り行えます。","address":"京都府京都市下京区堀川通花屋町下ル本願寺門前町60","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.991,"longitude":135.751,"nearest_station":"JR京都駅","station_walk_minutes":10,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"本堂":True,"バリアフリー":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":450000},{"type":"ippanso","label":"一般葬プラン","priceFrom":800000}],"features":["寺院式場","仏式葬儀","本山"],"operator_name":"西本願寺","rating_avg":4.2,"review_count":20},
    # === 京都市南区 5件 ===
    {"name":"ベルコ南京都シティホール","slug":"kyoto-bellco-minami","venue_type":"private_hall","description":"京都市南区・十条通沿いのベルコ葬儀会館。国道1号線からのアクセスも良好で、お車でお越しの方にも便利です。","address":"京都府京都市南区東九条南河辺町28","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.979,"longitude":135.762,"nearest_station":"京都市営地下鉄烏丸線 十条駅","station_walk_minutes":5,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":98000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":358000},{"type":"ippanso","label":"一般葬プラン","priceFrom":680000}],"features":["家族葬対応","駅近","大駐車場"],"operator_name":"ベルコ","rating_avg":4.1,"review_count":35},
    {"name":"公益社 吉祥院ホール","slug":"kyoto-koekisha-kisshoin","venue_type":"private_hall","description":"吉祥院エリアに位置する公益社のホール。京都南インターに近く、広い駐車場を完備しています。","address":"京都府京都市南区吉祥院石原南町16","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.973,"longitude":135.737,"nearest_station":"JR東海道本線 西大路駅","station_walk_minutes":12,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":105000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":380000},{"type":"ippanso","label":"一般葬プラン","priceFrom":690000}],"features":["家族葬対応","大駐車場","インター近く"],"operator_name":"公益社","rating_avg":4.0,"review_count":30},
    {"name":"家族葬のファミーユ南区","slug":"kyoto-famillu-minami","venue_type":"private_hall","description":"京都市南区の家族葬専門ホール。リーズナブルな価格設定で、少人数のお見送りに特化しています。","address":"京都府京都市南区西九条東比永城町78","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.976,"longitude":135.744,"nearest_station":"近鉄京都線 東寺駅","station_walk_minutes":8,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":89000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":298000}],"features":["家族葬対応","少人数対応","低価格","駅近"],"operator_name":"家族葬のファミーユ","rating_avg":4.3,"review_count":18},
    {"name":"洛王セレモニー久世","slug":"kyoto-rakuo-kuze","venue_type":"private_hall","description":"久世エリアの洛王セレモニー。国道171号線沿いでお車でのアクセスが便利。向日市・長岡京市方面からの利用も多い式場です。","address":"京都府京都市南区久世上久世町450","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.955,"longitude":135.727,"nearest_station":"JR東海道本線 桂川駅","station_walk_minutes":10,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":98000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":360000},{"type":"ippanso","label":"一般葬プラン","priceFrom":650000}],"features":["家族葬対応","駅近"],"operator_name":"洛王セレモニー","rating_avg":4.0,"review_count":22},
    {"name":"東寺会館","slug":"kyoto-toji-kaikan","venue_type":"temple_hall","description":"世界遺産・東寺（教王護国寺）に併設された式場。五重塔を望む荘厳な環境で、真言宗の伝統に基づく葬儀を執り行えます。","address":"京都府京都市南区九条町1","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.980,"longitude":135.748,"nearest_station":"近鉄京都線 東寺駅","station_walk_minutes":5,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":10,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"本堂":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":430000},{"type":"ippanso","label":"一般葬プラン","priceFrom":760000}],"features":["寺院式場","仏式葬儀","世界遺産","駅近"],"operator_name":"東寺","rating_avg":4.1,"review_count":14},
    # === 京都市右京区 5件 ===
    {"name":"公益社 太秦ホール","slug":"kyoto-koekisha-uzumasa","venue_type":"private_hall","description":"太秦エリアに位置する公益社の大型ホール。太秦映画村近くの立地で、広い駐車場を完備。右京区の中核斎場です。","address":"京都府京都市右京区太秦堀ケ内町30-18","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.013,"longitude":135.714,"nearest_station":"JR山陰本線 太秦駅","station_walk_minutes":8,"capacity_max":100,"hall_count":2,"has_crematorium":False,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":105000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":385000},{"type":"ippanso","label":"一般葬プラン","priceFrom":700000}],"features":["家族葬対応","駅近","大駐車場"],"operator_name":"公益社","rating_avg":4.2,"review_count":38},
    {"name":"ベルコ嵯峨野シティホール","slug":"kyoto-bellco-sagano","venue_type":"private_hall","description":"嵐山・嵯峨野エリアに位置するベルコの葬儀会館。自然豊かな環境で、穏やかなお別れの場を提供しています。","address":"京都府京都市右京区嵯峨野開町28-5","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.020,"longitude":135.700,"nearest_station":"JR山陰本線 嵯峨嵐山駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":98000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":365000}],"features":["家族葬対応","駅近","自然豊かな環境"],"operator_name":"ベルコ","rating_avg":4.3,"review_count":25},
    {"name":"洛王セレモニー西院","slug":"kyoto-rakuo-saiin","venue_type":"private_hall","description":"西院駅近くの洛王セレモニー。阪急京都線とJR山陰本線の2駅利用可能で、交通アクセスに優れています。","address":"京都府京都市右京区西院清水町25","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.005,"longitude":135.730,"nearest_station":"阪急京都線 西院駅","station_walk_minutes":5,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":100000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":370000},{"type":"ippanso","label":"一般葬プラン","priceFrom":670000}],"features":["家族葬対応","駅近","2駅利用可"],"operator_name":"洛王セレモニー","rating_avg":4.1,"review_count":30},
    {"name":"家族葬のファミーユ右京","slug":"kyoto-famillu-ukyo","venue_type":"private_hall","description":"京都市右京区の家族葬専門ホール。花園エリアの閑静な住宅街に位置し、少人数での温かいお別れに最適です。","address":"京都府京都市右京区花園木辻南町14","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.010,"longitude":135.720,"nearest_station":"JR山陰本線 花園駅","station_walk_minutes":5,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":89000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":298000}],"features":["家族葬対応","少人数対応","低価格","駅近"],"operator_name":"家族葬のファミーユ","rating_avg":4.4,"review_count":16},
    {"name":"妙心寺会館","slug":"kyoto-myoshinji-kaikan","venue_type":"temple_hall","description":"臨済宗妙心寺派の大本山・妙心寺に併設された式場。広大な境内を擁する名刹で、禅の精神に基づく厳かな葬儀を執り行えます。","address":"京都府京都市右京区花園妙心寺町64","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.014,"longitude":135.718,"nearest_station":"JR山陰本線 花園駅","station_walk_minutes":8,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":10,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"本堂":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":420000},{"type":"ippanso","label":"一般葬プラン","priceFrom":750000}],"features":["寺院式場","仏式葬儀","駅近"],"operator_name":"妙心寺","rating_avg":4.0,"review_count":14},
    # === 京都市伏見区 前半5件 ===
    {"name":"公益社 伏見ホール","slug":"kyoto-koekisha-fushimi","venue_type":"private_hall","description":"伏見区の中心部に位置する公益社の大型ホール。近鉄・京阪の2路線利用可能で、伏見区の中核斎場として多くの方に利用されています。","address":"京都府京都市伏見区東大手町744","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.934,"longitude":135.762,"nearest_station":"近鉄京都線 桃山御陵前駅","station_walk_minutes":5,"capacity_max":100,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":108000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":390000},{"type":"ippanso","label":"一般葬プラン","priceFrom":710000}],"features":["家族葬対応","駅近","2路線利用可"],"operator_name":"公益社","rating_avg":4.2,"review_count":42},
    {"name":"ベルコ伏見シティホール","slug":"kyoto-bellco-fushimi","venue_type":"private_hall","description":"伏見稲荷大社エリアに位置するベルコの葬儀会館。深草の落ち着いた環境で、温かみのあるお別れを提供しています。","address":"京都府京都市伏見区深草直違橋7-236","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.960,"longitude":135.769,"nearest_station":"京阪本線 藤森駅","station_walk_minutes":8,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":98000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":358000},{"type":"ippanso","label":"一般葬プラン","priceFrom":680000}],"features":["家族葬対応","駅近"],"operator_name":"ベルコ","rating_avg":4.1,"review_count":32},
    {"name":"洛王セレモニー醍醐","slug":"kyoto-rakuo-daigo","venue_type":"private_hall","description":"醍醐エリアの洛王セレモニー。地下鉄東西線醍醐駅から近く、山科方面からのアクセスも良好です。","address":"京都府京都市伏見区醍醐池田町3","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.951,"longitude":135.818,"nearest_station":"京都市営地下鉄東西線 醍醐駅","station_walk_minutes":5,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":368000},{"type":"ippanso","label":"一般葬プラン","priceFrom":660000}],"features":["家族葬対応","駅近"],"operator_name":"洛王セレモニー","rating_avg":4.0,"review_count":25},
    {"name":"家族葬のファミーユ伏見","slug":"kyoto-famillu-fushimi","venue_type":"private_hall","description":"伏見区の家族葬専門ホール。中書島駅近くの水辺の街並みが美しいエリアに位置し、少人数のお見送りに最適です。","address":"京都府京都市伏見区南浜町263","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.929,"longitude":135.756,"nearest_station":"京阪本線 中書島駅","station_walk_minutes":5,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":89000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":298000}],"features":["家族葬対応","少人数対応","低価格","駅近"],"operator_name":"家族葬のファミーユ","rating_avg":4.3,"review_count":18},
    {"name":"五条会館 伏見","slug":"kyoto-gojo-fushimi","venue_type":"private_hall","description":"伏見桃山エリアの五条会館。大手筋商店街に近く、地元密着型の温かいサービスが特徴です。","address":"京都府京都市伏見区桃山筒井伊賀西町46","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.936,"longitude":135.770,"nearest_station":"近鉄京都線 桃山御陵前駅","station_walk_minutes":8,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":102000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":375000},{"type":"ippanso","label":"一般葬プラン","priceFrom":670000}],"features":["家族葬対応","駅近"],"operator_name":"五条会館","rating_avg":4.0,"review_count":28},
]

for i in range(0, len(kyoto_batch2), 10):
    batch = kyoto_batch2[i:i+10]
    code = insert_batch(batch)
    print(f"バッチ {i//10+1}: {code} ({len(batch)}件)")
    time.sleep(1)

print(f"\n完了: 合計 {len(kyoto_batch2)} 件")
