#!/usr/bin/env python3
"""
兵庫県の斎場データ バッチ1: 神戸市 前半30件（東灘区・灘区・中央区・兵庫区・北区）
"""
import json
import subprocess
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

venues = [
    # =============================================
    # 神戸市東灘区 (7件)
    # =============================================
    {
        "name": "ベルコシティホール東灘",
        "slug": "hyogo-bellco-higashinada",
        "venue_type": "private_hall",
        "description": "神戸市東灘区に位置するベルコ直営の葬儀会館。阪神御影駅から徒歩8分の好立地で、少人数の家族葬から100名規模の一般葬まで対応可能。洗練された内装と充実した設備で、心温まるお別れの場を提供しています。",
        "address": "兵庫県神戸市東灘区御影本町4-10-1",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.7190,
        "longitude": 135.2530,
        "nearest_station": "阪神本線 御影駅",
        "station_walk_minutes": 8,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "駅徒歩圏内", "バリアフリー", "安置室完備"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.2,
        "review_count": 78,
    },
    {
        "name": "公益社 東灘会館",
        "slug": "hyogo-koekisha-higashinada",
        "venue_type": "private_hall",
        "description": "関西最大手の葬儀社・公益社が運営する東灘区の葬儀会館。JR住吉駅から徒歩5分のアクセス至便な立地。1日1組貸切で、家族葬専用のアットホームな空間。経験豊富なスタッフが24時間体制でサポートいたします。",
        "address": "兵庫県神戸市東灘区住吉宮町3-7-2",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.7250,
        "longitude": 135.2640,
        "nearest_station": "JR神戸線 住吉駅",
        "station_walk_minutes": 5,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 380000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 620000}],
        "features": ["家族葬対応", "駅近", "1日1組貸切", "宿泊可能", "24時間対応"],
        "operator_name": "株式会社公益社",
        "rating_avg": 4.4,
        "review_count": 95,
    },
    {
        "name": "家族葬のファミーユ 東灘ホール",
        "slug": "hyogo-familiu-higashinada",
        "venue_type": "private_hall",
        "description": "家族葬専門のファミーユが運営する東灘区の小規模斎場。10名〜30名程度の家族葬に最適化された設計で、温かみのある空間を実現。明確な料金体系で追加費用の心配なく安心してご利用いただけます。",
        "address": "兵庫県神戸市東灘区本山中町3-1-15",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.7270,
        "longitude": 135.2700,
        "nearest_station": "JR神戸線 摂津本山駅",
        "station_walk_minutes": 6,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 120000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "明朗会計", "駅徒歩圏内"],
        "operator_name": "家族葬のファミーユ",
        "rating_avg": 4.3,
        "review_count": 62,
    },
    {
        "name": "小さなお葬式 岡本ホール",
        "slug": "hyogo-chiisana-okamoto",
        "venue_type": "private_hall",
        "description": "全国展開の小さなお葬式が提携する岡本エリアの葬儀式場。コストを抑えた明確な料金プランが特徴で、火葬式から家族葬まで幅広い選択肢を用意。阪急岡本駅徒歩圏内の便利な立地です。",
        "address": "兵庫県神戸市東灘区岡本1-8-20",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.7310,
        "longitude": 135.2620,
        "nearest_station": "阪急神戸線 岡本駅",
        "station_walk_minutes": 7,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["低価格", "明朗会計", "少人数対応", "駅徒歩圏内"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 4.0,
        "review_count": 45,
    },
    {
        "name": "セレモニーホール深江",
        "slug": "hyogo-ceremony-fukae",
        "venue_type": "private_hall",
        "description": "神戸市東灘区深江に位置する互助会系の葬儀ホール。阪神深江駅から徒歩3分の駅前立地が魅力。大小2つの式場を備え、家族葬から200名規模の社葬まで幅広く対応。充実した設備とベテランスタッフの手厚いサポートが好評です。",
        "address": "兵庫県神戸市東灘区深江本町2-5-8",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.7170,
        "longitude": 135.2790,
        "nearest_station": "阪神本線 深江駅",
        "station_walk_minutes": 3,
        "capacity_max": 200,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 380000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 650000}],
        "features": ["大規模対応", "駅前立地", "宿泊可能", "バリアフリー"],
        "operator_name": "セレモニーホール互助会",
        "rating_avg": 4.1,
        "review_count": 67,
    },
    {
        "name": "東灘やすらぎ会館",
        "slug": "hyogo-higashinada-yasuragi",
        "venue_type": "private_hall",
        "description": "東灘区の閑静な住宅街にたたずむ家族葬専用の小規模会館。木のぬくもりを感じる和モダンの内装が特徴で、故人との最後のお別れを穏やかな雰囲気の中で行えます。バリアフリー完備で高齢の参列者にも安心です。",
        "address": "兵庫県神戸市東灘区魚崎南町4-2-10",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.7140,
        "longitude": 135.2680,
        "nearest_station": "阪神本線 魚崎駅",
        "station_walk_minutes": 5,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 128000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}],
        "features": ["家族葬専門", "少人数対応", "和モダン", "バリアフリー"],
        "operator_name": "東灘やすらぎ会館",
        "rating_avg": 4.2,
        "review_count": 38,
    },
    {
        "name": "ベルコシティホール甲南",
        "slug": "hyogo-bellco-konan",
        "venue_type": "private_hall",
        "description": "ベルコ直営の甲南エリアにある葬儀会館。JR甲南山手駅から徒歩10分。中規模の式場は家族葬から一般葬まで対応可能で、落ち着いた雰囲気の中でお見送りができます。24時間対応の相談窓口も設置。",
        "address": "兵庫県神戸市東灘区本山南町8-3-18",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.7220,
        "longitude": 135.2580,
        "nearest_station": "JR神戸線 甲南山手駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 18,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 560000}],
        "features": ["家族葬対応", "一般葬対応", "24時間対応", "駐車場完備"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.1,
        "review_count": 55,
    },

    # =============================================
    # 神戸市灘区 (6件)
    # =============================================
    {
        "name": "ベルコシティホール灘",
        "slug": "hyogo-bellco-nada",
        "venue_type": "private_hall",
        "description": "JR灘駅から徒歩7分に位置するベルコ直営の葬儀会館。灘区の中心部にあり、公共交通でのアクセスが良好。家族葬向けの落ち着いた式場を完備し、少人数でも丁寧なお見送りができます。ベルコならではの安心のサポート体制。",
        "address": "兵庫県神戸市灘区岩屋北町1-8-1",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.7070,
        "longitude": 135.2260,
        "nearest_station": "JR神戸線 灘駅",
        "station_walk_minutes": 7,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "駅徒歩圏内", "バリアフリー", "24時間対応"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.2,
        "review_count": 64,
    },
    {
        "name": "公益社 灘会館",
        "slug": "hyogo-koekisha-nada",
        "venue_type": "private_hall",
        "description": "阪急王子公園駅から徒歩5分の公益社直営会館。1日1組貸切制で、プライベートな空間でお別れの時間を過ごせます。豊富な経験を持つスタッフが事前相談から当日まで手厚くサポート。安心の明朗会計で追加費用の心配がありません。",
        "address": "兵庫県神戸市灘区王子町1-3-15",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.7120,
        "longitude": 135.2180,
        "nearest_station": "阪急神戸線 王子公園駅",
        "station_walk_minutes": 5,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 390000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 630000}],
        "features": ["家族葬対応", "駅近", "1日1組貸切", "宿泊可能"],
        "operator_name": "株式会社公益社",
        "rating_avg": 4.5,
        "review_count": 82,
    },
    {
        "name": "灘区民ホール葬儀式場",
        "slug": "hyogo-nada-kumin-hall",
        "venue_type": "public_facility",
        "description": "神戸市灘区の区民ホールを利用した葬儀式場。公共施設のため利用料がリーズナブルで、費用を抑えたい方に人気です。最寄り駅から徒歩圏内のアクセス良好な立地。式場は清潔感があり、シンプルながら落ち着いた空間です。",
        "address": "兵庫県神戸市灘区稗原町2-1-10",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.7100,
        "longitude": 135.2320,
        "nearest_station": "JR神戸線 六甲道駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "控室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 250000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 450000}],
        "features": ["公共施設", "低価格", "駅徒歩圏内", "バリアフリー"],
        "operator_name": "神戸市",
        "rating_avg": 3.8,
        "review_count": 35,
    },
    {
        "name": "家族葬のファミーユ 灘ホール",
        "slug": "hyogo-familiu-nada",
        "venue_type": "private_hall",
        "description": "家族葬専門のファミーユが灘区に展開する小規模ホール。六甲道駅近くの利便性の高いエリアに位置し、5名〜30名程度の家族葬に特化。温かみのあるインテリアと行き届いたサービスで、多くのご遺族に選ばれています。",
        "address": "兵庫県神戸市灘区桜口町4-5-1",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.7130,
        "longitude": 135.2350,
        "nearest_station": "JR神戸線 六甲道駅",
        "station_walk_minutes": 4,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 120000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "明朗会計", "駅近"],
        "operator_name": "家族葬のファミーユ",
        "rating_avg": 4.3,
        "review_count": 47,
    },
    {
        "name": "六甲メモリアルホール",
        "slug": "hyogo-rokko-memorial",
        "venue_type": "private_hall",
        "description": "六甲山麓の静かな環境に位置する格式ある葬儀会館。大小3つの式場を備え、20名程度の家族葬から300名規模の大規模葬まで対応。広い駐車場と充実した宴会設備で、お清めの席も安心して行えます。",
        "address": "兵庫県神戸市灘区六甲台町6-2",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.7250,
        "longitude": 135.2380,
        "nearest_station": "阪急神戸線 六甲駅",
        "station_walk_minutes": 12,
        "capacity_max": 300,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True, "宴会場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 380000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["大規模対応", "家族葬対応", "宿泊可能", "大型駐車場"],
        "operator_name": "六甲メモリアルホール",
        "rating_avg": 4.0,
        "review_count": 56,
    },
    {
        "name": "セレモニーホール灘",
        "slug": "hyogo-ceremony-nada",
        "venue_type": "private_hall",
        "description": "灘区中心部の互助会系葬儀ホール。阪急六甲駅から徒歩8分のアクセス良好な立地。中規模の式場は50名程度の家族葬に最適で、落ち着いた木目調の内装が好評です。事前相談も随時受け付けています。",
        "address": "兵庫県神戸市灘区山田町2-1-20",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.7180,
        "longitude": 135.2300,
        "nearest_station": "阪急神戸線 六甲駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "駅徒歩圏内", "事前相談可", "バリアフリー"],
        "operator_name": "セレモニーホール互助会",
        "rating_avg": 4.1,
        "review_count": 42,
    },

    # =============================================
    # 神戸市中央区 (7件)
    # =============================================
    {
        "name": "ベルコシティホール三宮",
        "slug": "hyogo-bellco-sannomiya",
        "venue_type": "private_hall",
        "description": "神戸の中心地・三宮に位置するベルコのフラッグシップ会館。JR三ノ宮駅から徒歩10分。大小4つの式場を備え、少人数の家族葬から500名規模の大型葬・社葬まで対応可能。神戸を代表する格式高い葬儀会館です。",
        "address": "兵庫県神戸市中央区琴ノ緒町3-2-1",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6960,
        "longitude": 135.1980,
        "nearest_station": "JR神戸線 三ノ宮駅",
        "station_walk_minutes": 10,
        "capacity_max": 500,
        "hall_count": 4,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True, "宴会場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 380000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 650000}],
        "features": ["大規模対応", "社葬対応", "駅徒歩圏内", "宿泊可能", "バリアフリー"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.3,
        "review_count": 112,
    },
    {
        "name": "公益社 三宮駅前ホール",
        "slug": "hyogo-koekisha-sannomiya",
        "venue_type": "private_hall",
        "description": "三宮駅前の好立地にある公益社の葬儀ホール。各線三宮駅から徒歩5分以内で、遠方からの参列者にも便利です。洗練されたモダンな内装が特徴で、家族葬から一般葬まで高品質なサービスを提供しています。",
        "address": "兵庫県神戸市中央区御幸通6-1-20",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6930,
        "longitude": 135.1960,
        "nearest_station": "JR神戸線 三ノ宮駅",
        "station_walk_minutes": 5,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 650000}],
        "features": ["駅前立地", "家族葬対応", "1日1組貸切", "宿泊可能"],
        "operator_name": "株式会社公益社",
        "rating_avg": 4.5,
        "review_count": 98,
    },
    {
        "name": "神戸ポートメモリアルホール",
        "slug": "hyogo-port-memorial",
        "venue_type": "private_hall",
        "description": "神戸港を望む中央区のメモリアルホール。海を見渡せるロビーと開放的な式場が特徴。神戸らしいモダンなデザインの建物で、故人への感謝の気持ちを込めたお別れの場を提供します。大型駐車場完備で参列者の利便性も高い施設です。",
        "address": "兵庫県神戸市中央区波止場町5-3",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6850,
        "longitude": 135.1890,
        "nearest_station": "地下鉄海岸線 みなと元町駅",
        "station_walk_minutes": 8,
        "capacity_max": 150,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宴会場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 360000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["大規模対応", "駐車場完備", "モダン建築", "バリアフリー"],
        "operator_name": "神戸ポートメモリアル",
        "rating_avg": 4.1,
        "review_count": 65,
    },
    {
        "name": "小さなお葬式 神戸中央ホール",
        "slug": "hyogo-chiisana-kobe-chuo",
        "venue_type": "private_hall",
        "description": "神戸市中央区で「小さなお葬式」が提携する葬儀式場。シンプルな火葬式から家族葬まで、全国統一の明瞭価格で安心。必要なものだけを含んだセットプランで、追加費用を最小限に抑えられます。24時間受付対応。",
        "address": "兵庫県神戸市中央区浜辺通4-1-15",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6890,
        "longitude": 135.2000,
        "nearest_station": "JR神戸線 三ノ宮駅",
        "station_walk_minutes": 12,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["低価格", "明朗会計", "24時間対応", "少人数対応"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 4.0,
        "review_count": 52,
    },
    {
        "name": "家族葬のファミーユ 神戸中央ホール",
        "slug": "hyogo-familiu-kobe-chuo",
        "venue_type": "private_hall",
        "description": "元町エリアに位置するファミーユの家族葬専用ホール。JR元町駅から徒歩6分。家族だけの静かなお別れの場として設計された温かみのある空間で、丁寧なお見送りをサポートします。シンプルな料金設定で安心です。",
        "address": "兵庫県神戸市中央区元町通3-8-5",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6900,
        "longitude": 135.1850,
        "nearest_station": "JR神戸線 元町駅",
        "station_walk_minutes": 6,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 120000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "駅徒歩圏内", "明朗会計"],
        "operator_name": "家族葬のファミーユ",
        "rating_avg": 4.2,
        "review_count": 41,
    },
    {
        "name": "神戸北野メモリアルホール",
        "slug": "hyogo-kitano-memorial",
        "venue_type": "private_hall",
        "description": "北野異人館街近くに位置する上質な葬儀会館。神戸らしいおしゃれな外観と格式ある内装が特徴。少人数から中規模の葬儀に対応し、きめ細やかなサービスで故人を偲ぶ時間を大切にした葬儀を執り行えます。",
        "address": "兵庫県神戸市中央区北野町2-10-8",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.7000,
        "longitude": 135.1920,
        "nearest_station": "各線 三宮駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 420000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 680000}],
        "features": ["上質な空間", "家族葬対応", "北野エリア", "バリアフリー"],
        "operator_name": "北野メモリアルホール",
        "rating_avg": 4.4,
        "review_count": 48,
    },
    {
        "name": "セレモニーホール花隈",
        "slug": "hyogo-ceremony-hanakuma",
        "venue_type": "private_hall",
        "description": "神戸市中央区花隈に位置する老舗の葬儀会館。神戸高速鉄道花隈駅から徒歩2分の駅前立地。地域に密着した葬儀社として長年の信頼と実績があり、お見積もりからアフターケアまでトータルにサポートします。",
        "address": "兵庫県神戸市中央区花隈町15-10",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6920,
        "longitude": 135.1780,
        "nearest_station": "神戸高速鉄道 花隈駅",
        "station_walk_minutes": 2,
        "capacity_max": 70,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 530000}],
        "features": ["駅前立地", "地域密着", "家族葬対応", "アフターケア充実"],
        "operator_name": "セレモニーホール花隈",
        "rating_avg": 4.0,
        "review_count": 39,
    },

    # =============================================
    # 神戸市兵庫区 (5件)
    # =============================================
    {
        "name": "ベルコシティホール兵庫",
        "slug": "hyogo-bellco-hyogo-ku",
        "venue_type": "private_hall",
        "description": "神戸市兵庫区のベルコ直営葬儀会館。JR兵庫駅から徒歩6分で下町の温かみが感じられるエリアに立地。中規模の式場で家族葬から一般葬まで対応。地元の方々に親しまれてきた信頼の会館です。",
        "address": "兵庫県神戸市兵庫区駅南通1-3-5",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6730,
        "longitude": 135.1700,
        "nearest_station": "JR神戸線 兵庫駅",
        "station_walk_minutes": 6,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 18,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "駅徒歩圏内", "地域密着", "バリアフリー"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.1,
        "review_count": 58,
    },
    {
        "name": "公益社 兵庫会館",
        "slug": "hyogo-koekisha-hyogo-ku",
        "venue_type": "private_hall",
        "description": "兵庫区湊川エリアの公益社直営会館。神戸高速湊川駅から徒歩3分の好アクセス。ベテランスタッフの丁寧な対応が好評で、宗派を問わず様々な葬儀形式に対応。1日1組貸切でゆっくりとお別れの時間を過ごせます。",
        "address": "兵庫県神戸市兵庫区湊川町3-5-8",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6780,
        "longitude": 135.1650,
        "nearest_station": "神戸高速鉄道 湊川駅",
        "station_walk_minutes": 3,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 380000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 620000}],
        "features": ["駅近", "1日1組貸切", "宿泊可能", "宗派不問"],
        "operator_name": "株式会社公益社",
        "rating_avg": 4.3,
        "review_count": 72,
    },
    {
        "name": "兵庫やすらぎホール",
        "slug": "hyogo-hyogo-ku-yasuragi",
        "venue_type": "private_hall",
        "description": "兵庫区の地域密着型葬儀ホール。和田岬駅から徒歩8分に位置し、地元の方に長年愛されてきた会館です。小規模ながら清潔感のある式場で、家族葬を中心に丁寧なお見送りを提供しています。",
        "address": "兵庫県神戸市兵庫区和田宮通6-2-15",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6660,
        "longitude": 135.1630,
        "nearest_station": "地下鉄海岸線 和田岬駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 128000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}],
        "features": ["家族葬対応", "地域密着", "少人数対応", "バリアフリー"],
        "operator_name": "兵庫やすらぎホール",
        "rating_avg": 4.0,
        "review_count": 33,
    },
    {
        "name": "能福寺 会館",
        "slug": "hyogo-nofukuji-kaikan",
        "venue_type": "temple_hall",
        "description": "兵庫大仏で有名な能福寺に併設された寺院式場。歴史ある寺院の荘厳な雰囲気の中で仏式の葬儀を執り行えます。寺院ならではの読経と厳かな空間で、故人を丁寧に送り出します。仏式葬儀をご希望の方におすすめです。",
        "address": "兵庫県神戸市兵庫区北逆瀬川町1-39",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6740,
        "longitude": 135.1680,
        "nearest_station": "JR神戸線 兵庫駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "控室": True, "駐車場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["寺院式場", "仏式葬儀", "歴史ある寺院", "荘厳な雰囲気"],
        "operator_name": "能福寺",
        "rating_avg": 4.2,
        "review_count": 28,
    },
    {
        "name": "小さなお葬式 兵庫駅前ホール",
        "slug": "hyogo-chiisana-hyogo-ekimae",
        "venue_type": "private_hall",
        "description": "JR兵庫駅前で小さなお葬式が提携する葬儀式場。駅前の便利な立地で、参列者にも優しいアクセス。費用を抑えたシンプルな葬儀プランが充実しており、必要最低限のサービスをリーズナブルに提供します。",
        "address": "兵庫県神戸市兵庫区駅前通2-1-8",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6750,
        "longitude": 135.1710,
        "nearest_station": "JR神戸線 兵庫駅",
        "station_walk_minutes": 3,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 6,
        "facilities": {"式場": True, "親族控室": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["低価格", "駅前立地", "明朗会計", "少人数対応"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 3.9,
        "review_count": 36,
    },

    # =============================================
    # 神戸市北区 (5件)
    # =============================================
    {
        "name": "神戸市立鵯越斎場",
        "slug": "hyogo-kobe-hiyodorigoe",
        "venue_type": "public_crematorium",
        "description": "神戸市が運営する公営火葬場で、北区鵯越に位置します。火葬炉12基を備え、神戸市民は低料金で利用可能。緑豊かな山間部に立地し、静かな環境でお見送りができます。神戸市内の葬儀で最も多く利用される火葬施設です。",
        "address": "兵庫県神戸市北区山田町下谷上字中一里山14-1",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.7220,
        "longitude": 135.1470,
        "nearest_station": "神戸電鉄 鵯越駅",
        "station_walk_minutes": 15,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 100,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True, "売店": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}],
        "features": ["火葬場", "公営斎場", "神戸市民割引", "大型駐車場"],
        "operator_name": "神戸市",
        "rating_avg": 3.7,
        "review_count": 120,
    },
    {
        "name": "ベルコシティホール北神戸",
        "slug": "hyogo-bellco-kita-kobe",
        "venue_type": "private_hall",
        "description": "北区鈴蘭台エリアのベルコ直営会館。神戸電鉄鈴蘭台駅から徒歩5分。北区の方々に長年親しまれてきた葬儀会館で、家族葬から一般葬まで柔軟に対応。広い駐車場を完備し、車での来場にも便利です。",
        "address": "兵庫県神戸市北区鈴蘭台北町1-10-2",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.7300,
        "longitude": 135.1220,
        "nearest_station": "神戸電鉄 鈴蘭台駅",
        "station_walk_minutes": 5,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 540000}],
        "features": ["家族葬対応", "駅近", "大型駐車場", "バリアフリー"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.1,
        "review_count": 63,
    },
    {
        "name": "公益社 北神戸会館",
        "slug": "hyogo-koekisha-kita-kobe",
        "venue_type": "private_hall",
        "description": "神戸市北区で公益社が運営する葬儀会館。谷上駅から車で5分の閑静なエリアに位置。自然に囲まれた穏やかな環境で、落ち着いたお別れの時間を過ごせます。ベテランスタッフの手厚いサポートが好評です。",
        "address": "兵庫県神戸市北区谷上東町1-5-12",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.7450,
        "longitude": 135.1560,
        "nearest_station": "神戸電鉄・北神急行 谷上駅",
        "station_walk_minutes": 12,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 370000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["家族葬対応", "宿泊可能", "駐車場完備", "自然豊かな環境"],
        "operator_name": "株式会社公益社",
        "rating_avg": 4.3,
        "review_count": 55,
    },
    {
        "name": "家族葬のファミーユ 北神戸ホール",
        "slug": "hyogo-familiu-kita-kobe",
        "venue_type": "private_hall",
        "description": "北区の住宅街に位置する家族葬専門のホール。岡場駅から徒歩10分。少人数の家族葬に特化した落ち着いた空間で、ご家族だけのプライベートなお別れを大切にしています。明瞭な料金設定で安心です。",
        "address": "兵庫県神戸市北区藤原台北町2-8-3",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.7940,
        "longitude": 135.1710,
        "nearest_station": "神戸電鉄 岡場駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 120000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "明朗会計", "駐車場完備"],
        "operator_name": "家族葬のファミーユ",
        "rating_avg": 4.2,
        "review_count": 38,
    },
    {
        "name": "北区やすらぎ典礼会館",
        "slug": "hyogo-kita-yasuragi-tenrei",
        "venue_type": "private_hall",
        "description": "有馬温泉にほど近い北区の葬儀会館。緑豊かな環境に囲まれた穏やかなロケーションで、ゆっくりとお別れの時間を過ごせます。50台収容の大型駐車場を備え、車での参列にも便利な施設です。",
        "address": "兵庫県神戸市北区有馬町1050-8",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.7970,
        "longitude": 135.2470,
        "nearest_station": "神戸電鉄 有馬温泉駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 520000}],
        "features": ["大型駐車場", "宿泊可能", "自然豊かな環境", "家族葬対応"],
        "operator_name": "北区やすらぎ典礼会館",
        "rating_avg": 4.0,
        "review_count": 42,
    },
]

# 10件ずつバッチ投入
total = len(venues)
print(f"兵庫県バッチ1: 神戸市前半 {total}件を投入開始")
for i in range(0, total, 10):
    batch = venues[i:i+10]
    status = insert_batch(batch)
    print(f"  バッチ {i//10+1}: {len(batch)}件 → HTTP {status}")
    if status != "201":
        print(f"  エラー! レスポンス: {status}")
        # エラー詳細を取得
        data_json = json.dumps(batch, ensure_ascii=False)
        result = subprocess.run([
            "curl", "-s",
            "-X", "POST", SUPABASE_URL,
            "-H", f"apikey: {API_KEY}",
            "-H", f"Authorization: Bearer {API_KEY}",
            "-H", "Content-Type: application/json",
            "-H", "Prefer: return=minimal",
            "-H", "User-Agent: Mozilla/5.0",
            "-d", data_json
        ], capture_output=True, text=True)
        print(f"  詳細: {result.stdout[:500]}")
    time.sleep(1)
print(f"バッチ1完了: {total}件")
