#!/usr/bin/env python3
"""
北海道・主要都市: 旭川市15件 + 函館市15件 = 30件
"""

import json
import urllib.request
import urllib.error
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

HEADERS = {
    "apikey": API_KEY,
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal",
}

venues = [
    # =============================================
    # 旭川市 — 15件
    # =============================================
    {
        "name": "やわらぎ斎場 旭川",
        "slug": "yawaragi-asahikawa",
        "venue_type": "private_hall",
        "description": "やわらぎ斎場の旭川エリア拠点。旭川市中心部に位置し、JR旭川駅からもアクセス可能。家族葬から一般葬まで幅広く対応する大型施設で、旭川市を代表する葬儀場の一つです。",
        "address": "北海道旭川市3条通15丁目左1号",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7700,
        "longitude": 142.3600,
        "nearest_station": "JR函館本線 旭川駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["大型式場", "家族葬対応", "一般葬対応", "駐車場完備"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.1,
        "review_count": 24,
    },
    {
        "name": "ウィズハウス 永山",
        "slug": "withhouse-nagayama-asahikawa",
        "venue_type": "private_hall",
        "description": "コープの家族葬ウィズハウスの旭川永山店。永山エリアに位置し、1日1組貸切の家族葬ホール。コープ会員割引あり。温かみのある空間で少人数の家族葬に最適。",
        "address": "北海道旭川市永山2条16丁目4-11",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7950,
        "longitude": 142.3900,
        "nearest_station": "JR宗谷本線 永山駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["コープ会員割引", "1日1組貸切", "家族葬専用"],
        "operator_name": "めもるホールディングス",
        "rating_avg": 4.2,
        "review_count": 16,
    },
    {
        "name": "ウィズハウス 末広",
        "slug": "withhouse-suehiro-asahikawa",
        "venue_type": "private_hall",
        "description": "コープの家族葬ウィズハウスの旭川末広店。末広エリアに位置し、モダンな内装の家族葬専用ホール。1日1組貸切でプライバシーに配慮した空間を提供します。",
        "address": "北海道旭川市末広2条3丁目3-15",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7900,
        "longitude": 142.3500,
        "nearest_station": "JR宗谷本線 新旭川駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["コープ会員割引", "1日1組貸切", "家族葬専用", "モダン内装"],
        "operator_name": "めもるホールディングス",
        "rating_avg": 4.1,
        "review_count": 14,
    },
    {
        "name": "ウィズハウス 東光",
        "slug": "withhouse-toko-asahikawa",
        "venue_type": "private_hall",
        "description": "コープの家族葬ウィズハウスの旭川東光店。東光エリアの住宅街に位置し、落ち着いた環境で家族葬を執り行えます。コープ会員は特別料金で利用可能です。",
        "address": "北海道旭川市東光3条7丁目1-18",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7550,
        "longitude": 142.3850,
        "nearest_station": "JR富良野線 旭川駅",
        "station_walk_minutes": 20,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["コープ会員割引", "家族葬専用", "閑静な立地"],
        "operator_name": "めもるホールディングス",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "ウィズハウス 神楽",
        "slug": "withhouse-kagura-asahikawa",
        "venue_type": "private_hall",
        "description": "コープの家族葬ウィズハウスの旭川神楽店。旭川市南部の神楽エリアに位置。温かみのある木調の内装で、くつろぎの空間を提供。少人数の家族葬に最適です。",
        "address": "北海道旭川市神楽4条4丁目2-12",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7500,
        "longitude": 142.3700,
        "nearest_station": "JR富良野線 神楽岡駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["コープ会員割引", "家族葬専用", "駅近"],
        "operator_name": "めもるホールディングス",
        "rating_avg": 4.1,
        "review_count": 13,
    },
    {
        "name": "旭川市斎場",
        "slug": "asahikawa-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "旭川市が運営する公営火葬場。旭川市東旭川に位置し、火葬炉を複数備えています。旭川市民は市民料金で利用可能。通夜室・待合室も完備された総合施設です。",
        "address": "北海道旭川市東旭川北3条6丁目4",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7800,
        "longitude": 142.4200,
        "nearest_station": "JR石北本線 東旭川駅",
        "station_walk_minutes": 15,
        "capacity_max": 40,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 100,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "通夜室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 0}],
        "features": ["火葬場", "公営斎場", "駐車場完備", "市民料金あり"],
        "operator_name": "旭川市",
        "rating_avg": 3.7,
        "review_count": 20,
    },
    {
        "name": "公益社 メモリアルホール旭川",
        "slug": "koekisha-memorial-asahikawa",
        "venue_type": "private_hall",
        "description": "公益社が運営する旭川市の大型メモリアルホール。旭川市中心部に位置し、通夜から告別式まで一貫対応。複数の式場を持ち、家族葬から大規模な一般葬・社葬まで幅広く対応します。",
        "address": "北海道旭川市4条通17丁目右2号",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7720,
        "longitude": 142.3550,
        "nearest_station": "JR函館本線 旭川駅",
        "station_walk_minutes": 12,
        "capacity_max": 100,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True, "ロビー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 500000}],
        "features": ["大型式場", "一般葬対応", "社葬対応", "駐車場完備"],
        "operator_name": "公益社",
        "rating_avg": 4.0,
        "review_count": 22,
    },
    {
        "name": "公益社 家族葬ホール めもりある 旭川",
        "slug": "koekisha-memoriaru-asahikawa",
        "venue_type": "private_hall",
        "description": "公益社が運営する旭川の家族葬専用ホール。少人数のアットホームな家族葬に特化し、温かみのある空間で故人とのお別れの時間を大切にします。リーズナブルな価格設定も魅力。",
        "address": "北海道旭川市豊岡3条3丁目2-10",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7600,
        "longitude": 142.3900,
        "nearest_station": "JR函館本線 旭川駅",
        "station_walk_minutes": 18,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}],
        "features": ["家族葬専用", "少人数対応", "低価格", "アットホーム"],
        "operator_name": "公益社",
        "rating_avg": 4.1,
        "review_count": 11,
    },
    {
        "name": "やわらぎ斎場 旭川永山",
        "slug": "yawaragi-asahikawa-nagayama",
        "venue_type": "private_hall",
        "description": "やわらぎ斎場の旭川永山エリア店。永山地区は旭川市の人口密集地域で、多くの方に利用されています。広々とした式場と充実した駐車場を備え、冬場の除雪も万全です。",
        "address": "北海道旭川市永山4条5丁目1-20",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7980,
        "longitude": 142.3800,
        "nearest_station": "JR宗谷本線 永山駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["駅近", "一般葬対応", "駐車場完備", "除雪対応"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.0,
        "review_count": 16,
    },
    {
        "name": "やわらぎ斎場 旭川春光",
        "slug": "yawaragi-asahikawa-shunko",
        "venue_type": "private_hall",
        "description": "やわらぎ斎場の旭川春光エリア店。旭川市西部の春光地区に位置し、地域の方に親しまれている葬儀場。家族葬に適した落ち着いた雰囲気の式場を備えています。",
        "address": "北海道旭川市春光5条5丁目3-8",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7850,
        "longitude": 142.3350,
        "nearest_station": "JR函館本線 旭川駅",
        "station_walk_minutes": 25,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}],
        "features": ["地域密着", "家族葬対応", "駐車場完備"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 3.9,
        "review_count": 10,
    },
    {
        "name": "香華殿 旭川斎場",
        "slug": "kokaden-asahikawa-saijo",
        "venue_type": "private_hall",
        "description": "香華殿グループが運営する旭川の総合葬儀場。格式のある落ち着いた雰囲気と丁寧なサービスが特徴。家族葬から一般葬まで幅広く対応し、旭川市内で信頼されている葬儀場です。",
        "address": "北海道旭川市大雪通5丁目407-48",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7650,
        "longitude": 142.3750,
        "nearest_station": "JR函館本線 旭川駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 520000}],
        "features": ["格式高い", "一般葬対応", "家族葬対応", "駐車場完備"],
        "operator_name": "香華殿",
        "rating_avg": 4.1,
        "review_count": 15,
    },
    {
        "name": "小さなお葬式 旭川ホール",
        "slug": "chiisana-ososhiki-asahikawa",
        "venue_type": "private_hall",
        "description": "小さなお葬式が提携する旭川の家族葬ホール。追加料金なしの明朗会計が特徴で、火葬式から家族葬まで低価格で対応。初めての方でも安心して利用できます。",
        "address": "北海道旭川市6条通7丁目左8号",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7680,
        "longitude": 142.3650,
        "nearest_station": "JR函館本線 旭川駅",
        "station_walk_minutes": 8,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["低価格", "明朗会計", "家族葬専用", "24時間対応"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 3.8,
        "review_count": 12,
    },
    {
        "name": "セレモニーホール旭川中央",
        "slug": "ceremony-asahikawa-chuo",
        "venue_type": "private_hall",
        "description": "旭川市中心部に位置するセレモニーホール。JR旭川駅から近く、広い式場と充実した設備を持つ葬儀場。家族葬から一般葬まで、地域の方に幅広く利用されています。",
        "address": "北海道旭川市2条通8丁目左3号",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7710,
        "longitude": 142.3620,
        "nearest_station": "JR函館本線 旭川駅",
        "station_walk_minutes": 5,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 500000}],
        "features": ["駅近", "家族葬対応", "一般葬対応", "地域密着"],
        "operator_name": "セレモニーホール旭川",
        "rating_avg": 4.0,
        "review_count": 14,
    },
    {
        "name": "よりそうお葬式 旭川ホール",
        "slug": "yorisou-asahikawa",
        "venue_type": "private_hall",
        "description": "よりそうお葬式が提携する旭川の葬儀ホール。定額プランで追加費用の心配なし。旭川市内で経済的な家族葬を希望する方に選ばれています。24時間365日電話相談可能。",
        "address": "北海道旭川市忠和5条5丁目2-18",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7800,
        "longitude": 142.3300,
        "nearest_station": "JR函館本線 旭川駅",
        "station_walk_minutes": 20,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89100}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["定額プラン", "明朗会計", "24時間対応", "家族葬対応"],
        "operator_name": "株式会社よりそう",
        "rating_avg": 3.9,
        "review_count": 9,
    },
    {
        "name": "公益社やわらぎ斎場 岩見沢西",
        "slug": "koekisha-yawaragi-iwamizawa",
        "venue_type": "private_hall",
        "description": "公益社とやわらぎが共同で運営する岩見沢西の葬儀場。旭川方面との中間に位置し、岩見沢市を中心に周辺地域からも利用可能。広い駐車場と落ち着いた式場を備えています。",
        "address": "北海道岩見沢市9条西15丁目1-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.2050,
        "longitude": 141.7550,
        "nearest_station": "JR函館本線 岩見沢駅",
        "station_walk_minutes": 15,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 480000}],
        "features": ["駐車場完備", "一般葬対応", "地域密着"],
        "operator_name": "公益社・やわらぎ",
        "rating_avg": 3.9,
        "review_count": 12,
    },
    # =============================================
    # 函館市 — 15件
    # =============================================
    {
        "name": "ウィズハウス 花園",
        "slug": "withhouse-hanazono-hakodate",
        "venue_type": "private_hall",
        "description": "コープの家族葬ウィズハウスの函館花園店。函館市花園町に位置し、1日1組貸切の家族葬ホール。コープ会員割引あり。温かみのある空間で心安らぐお別れの時間を提供します。",
        "address": "北海道函館市花園町27-2",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.7820,
        "longitude": 140.7580,
        "nearest_station": "JR函館本線 五稜郭駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["コープ会員割引", "1日1組貸切", "家族葬専用"],
        "operator_name": "めもるホールディングス",
        "rating_avg": 4.2,
        "review_count": 18,
    },
    {
        "name": "ウィズハウス 海岸町",
        "slug": "withhouse-kaigamachi-hakodate",
        "venue_type": "private_hall",
        "description": "コープの家族葬ウィズハウスの函館海岸町店。函館港に近い海岸町エリアに位置。函館駅からもアクセス可能で、少人数の家族葬に特化した温かな空間です。",
        "address": "北海道函館市海岸町18-27",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.7710,
        "longitude": 140.7280,
        "nearest_station": "JR函館本線 函館駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["コープ会員割引", "家族葬専用", "駅近"],
        "operator_name": "めもるホールディングス",
        "rating_avg": 4.1,
        "review_count": 15,
    },
    {
        "name": "ウィズハウス 神山",
        "slug": "withhouse-kamiyama-hakodate",
        "venue_type": "private_hall",
        "description": "コープの家族葬ウィズハウスの函館神山店。函館市郊外の神山エリアに位置し、広い駐車場を完備。自然に囲まれた落ち着いた環境で、ゆったりとした家族葬を執り行えます。",
        "address": "北海道函館市神山2丁目1-5",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.8000,
        "longitude": 140.7800,
        "nearest_station": "JR函館本線 五稜郭駅",
        "station_walk_minutes": 20,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["コープ会員割引", "駐車場完備", "自然豊か", "家族葬専用"],
        "operator_name": "めもるホールディングス",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "函館市斎場",
        "slug": "hakodate-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "函館市が運営する公営火葬場。函館市民の火葬を担う中核施設で、火葬炉を複数備えています。待合室や通夜室も完備。函館市民は割安な市民料金で利用可能です。",
        "address": "北海道函館市亀田中野町70-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.8100,
        "longitude": 140.7500,
        "nearest_station": "JR函館本線 五稜郭駅",
        "station_walk_minutes": 25,
        "capacity_max": 40,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 80,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "通夜室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 0}],
        "features": ["火葬場", "公営斎場", "駐車場完備", "市民料金あり"],
        "operator_name": "函館市",
        "rating_avg": 3.7,
        "review_count": 18,
    },
    {
        "name": "高龍寺 音羽ホール",
        "slug": "koryuji-otowa-hakodate",
        "venue_type": "temple_hall",
        "description": "函館の名刹・高龍寺が運営する葬儀ホール。歴史ある寺院の格式と現代的な設備を兼ね備え、厳かな雰囲気の中で葬儀を執り行えます。宗派を問わず利用可能。",
        "address": "北海道函館市若松町1-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.7750,
        "longitude": 140.7260,
        "nearest_station": "JR函館本線 函館駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 120000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["寺院式場", "宗派不問", "駅近", "格式高い"],
        "operator_name": "高龍寺",
        "rating_avg": 4.1,
        "review_count": 16,
    },
    {
        "name": "セレモニーホール白雲殿",
        "slug": "hakuunden-hakodate",
        "venue_type": "private_hall",
        "description": "函館市大縄町に位置するセレモニーホール白雲殿。函館地区で長年の実績を持つ葬儀場で、通夜から告別式まで一貫したサービスを提供。広い式場と充実した設備が特徴です。",
        "address": "北海道函館市大縄町16-28",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.7900,
        "longitude": 140.7550,
        "nearest_station": "JR函館本線 五稜郭駅",
        "station_walk_minutes": 12,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 500000}],
        "features": ["一般葬対応", "駐車場完備", "地域密着", "実績豊富"],
        "operator_name": "白雲殿",
        "rating_avg": 4.0,
        "review_count": 19,
    },
    {
        "name": "小田桐葬儀社 本館",
        "slug": "odagiri-honkan-hakodate",
        "venue_type": "private_hall",
        "description": "函館で長年の実績を持つ小田桐葬儀社の本館。家族葬に力を入れており、少人数でのアットホームな葬儀を得意としています。函館の気候を考慮した充実した施設設備が特徴。",
        "address": "北海道函館市杉並町22-15",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.7680,
        "longitude": 140.7400,
        "nearest_station": "市電 杉並町停留場",
        "station_walk_minutes": 3,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}],
        "features": ["家族葬対応", "駅近", "地域密着", "実績豊富"],
        "operator_name": "小田桐葬儀社",
        "rating_avg": 4.2,
        "review_count": 14,
    },
    {
        "name": "函館平安システム 昭和斎場",
        "slug": "heian-showa-hakodate",
        "venue_type": "private_hall",
        "description": "函館平安システムが運営する昭和エリアの葬儀場。函館市郊外に位置し、広い駐車場と大型の式場を備えた総合施設。互助会会員は特別料金で利用可能。一般葬にも対応。",
        "address": "北海道函館市昭和4丁目35-15",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.8050,
        "longitude": 140.7650,
        "nearest_station": "JR函館本線 五稜郭駅",
        "station_walk_minutes": 18,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True, "ロビー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 530000}],
        "features": ["大型式場", "互助会割引", "一般葬対応", "駐車場完備"],
        "operator_name": "函館平安システム",
        "rating_avg": 4.0,
        "review_count": 20,
    },
    {
        "name": "函館平安システム 花園斎場",
        "slug": "heian-hanazono-hakodate",
        "venue_type": "private_hall",
        "description": "函館平安システムが運営する花園エリアの葬儀場。家族葬から一般葬まで対応可能で、互助会会員には特別割引あり。函館市中心部に近い便利な立地です。",
        "address": "北海道函館市花園町25-3",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.7830,
        "longitude": 140.7560,
        "nearest_station": "JR函館本線 五稜郭駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 530000}],
        "features": ["互助会割引", "家族葬対応", "一般葬対応", "駅近"],
        "operator_name": "函館平安システム",
        "rating_avg": 4.0,
        "review_count": 17,
    },
    {
        "name": "鳴瀬葬儀社 大澗ホール",
        "slug": "naruse-oma-hakodate",
        "venue_type": "private_hall",
        "description": "鳴瀬葬儀社が運営する函館市の葬儀ホール。函館市西部エリアに位置し、地域密着型のきめ細かなサービスが好評。家族葬を中心に、温かみのある対応をしています。",
        "address": "北海道函館市大澗町232",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.7550,
        "longitude": 140.7100,
        "nearest_station": "市電 谷地頭停留場",
        "station_walk_minutes": 15,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 290000}],
        "features": ["家族葬対応", "地域密着", "丁寧な対応"],
        "operator_name": "鳴瀬葬儀社",
        "rating_avg": 4.1,
        "review_count": 10,
    },
    {
        "name": "小さなお葬式 函館ホール",
        "slug": "chiisana-ososhiki-hakodate",
        "venue_type": "private_hall",
        "description": "小さなお葬式が提携する函館の家族葬ホール。追加料金なしの明朗会計が特徴で、火葬式から家族葬まで低価格で対応。函館市内で経済的な葬儀を希望する方に選ばれています。",
        "address": "北海道函館市五稜郭町35-10",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.7960,
        "longitude": 140.7530,
        "nearest_station": "市電 五稜郭公園前停留場",
        "station_walk_minutes": 5,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["低価格", "明朗会計", "家族葬専用", "駅近"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 3.8,
        "review_count": 11,
    },
    {
        "name": "柴田葬儀社 旭町ホール",
        "slug": "shibata-asahimachi-hakodate",
        "venue_type": "private_hall",
        "description": "柴田葬儀社が運営する函館市旭町の葬儀場。函館で老舗の葬儀社で、伝統的な葬儀から現代的な家族葬まで柔軟に対応。丁寧できめ細かなサポートが特徴です。",
        "address": "北海道函館市旭町12-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.7700,
        "longitude": 140.7350,
        "nearest_station": "市電 宝来町停留場",
        "station_walk_minutes": 5,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 480000}],
        "features": ["老舗葬儀社", "駅近", "家族葬対応", "一般葬対応"],
        "operator_name": "柴田葬儀社",
        "rating_avg": 4.0,
        "review_count": 13,
    },
    {
        "name": "セレモニーホール函館北斗",
        "slug": "ceremony-hakodate-hokuto",
        "venue_type": "private_hall",
        "description": "函館市と北斗市の境界付近に位置する葬儀場。新函館北斗駅にも近く、北斗市・函館市北部エリアの方に便利。広い駐車場と清潔感のある式場を備えています。",
        "address": "北海道函館市桔梗5丁目20-10",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.8200,
        "longitude": 140.7300,
        "nearest_station": "JR函館本線 桔梗駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 490000}],
        "features": ["駅近", "駐車場完備", "家族葬対応", "一般葬対応"],
        "operator_name": "セレモニーホール函館",
        "rating_avg": 3.9,
        "review_count": 11,
    },
    {
        "name": "香華殿 函館斎場",
        "slug": "kokaden-hakodate-saijo",
        "venue_type": "private_hall",
        "description": "香華殿グループが運営する函館の葬儀場。格式ある落ち着いた式場と丁寧なサービスが特徴。家族葬から一般葬まで幅広く対応し、函館エリアで信頼されている葬儀場です。",
        "address": "北海道函館市美原3丁目50-10",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.7950,
        "longitude": 140.7700,
        "nearest_station": "JR函館本線 五稜郭駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 520000}],
        "features": ["格式高い", "一般葬対応", "家族葬対応", "駐車場完備"],
        "operator_name": "香華殿",
        "rating_avg": 4.0,
        "review_count": 14,
    },
]

def insert_batch(batch):
    data_json = json.dumps(batch, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(SUPABASE_URL, data=data_json, headers=HEADERS, method="POST")
    try:
        with urllib.request.urlopen(req) as res:
            return res.status
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"  HTTPError {e.code}: {body[:300]}")
        return e.code

total = len(venues)
print(f"北海道・旭川市+函館市: {total}件を投入開始")

ok = 0
for i in range(0, total, 10):
    batch = venues[i:i+10]
    code = insert_batch(batch)
    names = ", ".join(v["name"] for v in batch)
    print(f"  バッチ {i//10+1}: {code} ({len(batch)}件) — {names}")
    if code in (200, 201):
        ok += len(batch)
    time.sleep(0.5)

print(f"\n完了: {ok}/{total}件 投入成功")
