# -*- coding: utf-8 -*-
import json, subprocess, time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

venues = [
    # === 鈴鹿市 残り3件 ===
    {"name":"メモリアルホール鈴鹿","slug":"mie-memorial-suzuka","venue_type":"private_hall","description":"鈴鹿市旭が丘エリアのメモリアルホール。モダンな設計の温かい式場です。","address":"三重県鈴鹿市旭が丘3-8-15","prefecture_slug":"mie","city_slug":"suzuka","latitude":34.840,"longitude":136.565,"nearest_station":"近鉄鈴鹿線 平田町駅","station_walk_minutes":10,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":348000},{"type":"ippanso","label":"一般葬プラン","priceFrom":640000}],"features":["家族葬対応"],"operator_name":"メモリアルホール","rating_avg":4.0,"review_count":16},
    {"name":"こころ斎苑鈴鹿","slug":"mie-kokorosaien-suzuka","venue_type":"private_hall","description":"鈴鹿市の家族葬対応ホール。木のぬくもりを感じる温かい空間です。","address":"三重県鈴鹿市道伯1-16-8","prefecture_slug":"mie","city_slug":"suzuka","latitude":34.835,"longitude":136.582,"nearest_station":"近鉄名古屋線 白子駅","station_walk_minutes":10,"capacity_max":40,"hall_count":1,"has_crematorium":False,"parking_count":12,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":88000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":310000}],"features":["家族葬対応","少人数対応"],"operator_name":"こころ斎苑","rating_avg":4.3,"review_count":12},
    {"name":"やすらぎ会館鈴鹿","slug":"mie-yasuragi-suzuka","venue_type":"private_hall","description":"鈴鹿市のやすらぎ会館。落ち着いた環境で心温まるお別れを提供しています。","address":"三重県鈴鹿市南堀江1-2-8","prefecture_slug":"mie","city_slug":"suzuka","latitude":34.828,"longitude":136.572,"nearest_station":"近鉄鈴鹿線 鈴鹿市駅","station_walk_minutes":10,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":340000},{"type":"ippanso","label":"一般葬プラン","priceFrom":630000}],"features":["家族葬対応"],"operator_name":"やすらぎ会館","rating_avg":4.0,"review_count":14},
    # === 松阪市 8件 ===
    {"name":"ティア松阪","slug":"mie-tier-matsusaka","venue_type":"private_hall","description":"松阪市中心部のティア。松阪牛で有名な城下町エリアの中核斎場です。","address":"三重県松阪市日野町788","prefecture_slug":"mie","city_slug":"matsusaka","latitude":34.579,"longitude":136.530,"nearest_station":"近鉄山田線 松阪駅","station_walk_minutes":8,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":348000},{"type":"ippanso","label":"一般葬プラン","priceFrom":650000}],"features":["家族葬対応","駅近"],"operator_name":"ティア","rating_avg":4.2,"review_count":30},
    {"name":"紫雲殿松阪","slug":"mie-shiunden-matsusaka","venue_type":"private_hall","description":"松阪市の紫雲殿。国道42号線沿いの便利な立地です。","address":"三重県松阪市大黒田町1730","prefecture_slug":"mie","city_slug":"matsusaka","latitude":34.575,"longitude":136.525,"nearest_station":"近鉄山田線 松阪駅","station_walk_minutes":12,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":340000},{"type":"ippanso","label":"一般葬プラン","priceFrom":640000}],"features":["家族葬対応","大駐車場"],"operator_name":"紫雲殿","rating_avg":4.0,"review_count":25},
    {"name":"セレモニーホール松阪","slug":"mie-ceremony-matsusaka","venue_type":"private_hall","description":"松阪市のセレモニーホール。JR松阪駅に近い便利な立地です。","address":"三重県松阪市京町一区15-3","prefecture_slug":"mie","city_slug":"matsusaka","latitude":34.577,"longitude":136.533,"nearest_station":"JR紀勢本線 松阪駅","station_walk_minutes":5,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":18,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":355000},{"type":"ippanso","label":"一般葬プラン","priceFrom":650000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホール","rating_avg":4.1,"review_count":22},
    {"name":"松阪市斎場","slug":"mie-matsusaka-saijo","venue_type":"public_crematorium","description":"松阪市が運営する公営火葬場・斎場。市民料金で利用可能です。","address":"三重県松阪市荒木町字松枝140","prefecture_slug":"mie","city_slug":"matsusaka","latitude":34.590,"longitude":136.510,"nearest_station":"近鉄山田線 松阪駅","station_walk_minutes":20,"capacity_max":60,"hall_count":1,"has_crematorium":True,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":50000}],"features":["公営施設","火葬場併設"],"operator_name":"松阪市","rating_avg":3.6,"review_count":30},
    {"name":"家族葬のファミーユ松阪","slug":"mie-famillu-matsusaka","venue_type":"private_hall","description":"松阪市の家族葬専門ホール。少人数対応の温かい式場です。","address":"三重県松阪市下村町988-3","prefecture_slug":"mie","city_slug":"matsusaka","latitude":34.572,"longitude":136.528,"nearest_station":"近鉄山田線 松阪駅","station_walk_minutes":10,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":85000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":285000}],"features":["家族葬対応","少人数対応","低価格"],"operator_name":"家族葬のファミーユ","rating_avg":4.4,"review_count":14},
    {"name":"JA葬祭松阪","slug":"mie-ja-matsusaka","venue_type":"private_hall","description":"JA松阪が運営する葬祭ホール。地域に根差した適正価格サービスです。","address":"三重県松阪市嬉野中川新町3-55","prefecture_slug":"mie","city_slug":"matsusaka","latitude":34.610,"longitude":136.490,"nearest_station":"近鉄山田線 伊勢中川駅","station_walk_minutes":10,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":285000},{"type":"ippanso","label":"一般葬プラン","priceFrom":520000}],"features":["家族葬対応","低価格"],"operator_name":"JA松阪","rating_avg":3.9,"review_count":18},
    {"name":"ベルコ松阪シティホール","slug":"mie-bellco-matsusaka","venue_type":"private_hall","description":"松阪市のベルコ葬儀会館。広い駐車場を完備しています。","address":"三重県松阪市末広町1-167","prefecture_slug":"mie","city_slug":"matsusaka","latitude":34.582,"longitude":136.535,"nearest_station":"近鉄山田線 松阪駅","station_walk_minutes":10,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":350000}],"features":["家族葬対応"],"operator_name":"ベルコ","rating_avg":4.1,"review_count":20},
    {"name":"メモリアルホール松阪","slug":"mie-memorial-matsusaka","venue_type":"private_hall","description":"松阪市南部のメモリアルホール。温かみのある式場です。","address":"三重県松阪市田村町235-1","prefecture_slug":"mie","city_slug":"matsusaka","latitude":34.565,"longitude":136.535,"nearest_station":"近鉄山田線 松阪駅","station_walk_minutes":15,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":348000},{"type":"ippanso","label":"一般葬プラン","priceFrom":640000}],"features":["家族葬対応"],"operator_name":"メモリアルホール","rating_avg":4.0,"review_count":16},
    # === 桑名市 6件 ===
    {"name":"ティア桑名","slug":"mie-tier-kuwana","venue_type":"private_hall","description":"桑名市中心部のティア。東海道の宿場町として歴史ある桑名の中核斎場です。","address":"三重県桑名市中央町5-30","prefecture_slug":"mie","city_slug":"kuwana","latitude":35.063,"longitude":136.692,"nearest_station":"近鉄名古屋線 桑名駅","station_walk_minutes":10,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":350000},{"type":"ippanso","label":"一般葬プラン","priceFrom":660000}],"features":["家族葬対応","駅近"],"operator_name":"ティア","rating_avg":4.2,"review_count":28},
    {"name":"紫雲殿桑名","slug":"mie-shiunden-kuwana","venue_type":"private_hall","description":"桑名市の紫雲殿。国道1号線沿いの便利な立地です。","address":"三重県桑名市大字安永1055-1","prefecture_slug":"mie","city_slug":"kuwana","latitude":35.060,"longitude":136.688,"nearest_station":"近鉄名古屋線 桑名駅","station_walk_minutes":12,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":340000},{"type":"ippanso","label":"一般葬プラン","priceFrom":640000}],"features":["家族葬対応","大駐車場"],"operator_name":"紫雲殿","rating_avg":4.0,"review_count":22},
    {"name":"セレモニーホール桑名","slug":"mie-ceremony-kuwana","venue_type":"private_hall","description":"桑名市のセレモニーホール。落ち着いた環境の式場です。","address":"三重県桑名市新西方5-68","prefecture_slug":"mie","city_slug":"kuwana","latitude":35.067,"longitude":136.695,"nearest_station":"JR関西本線 桑名駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":18,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":358000},{"type":"ippanso","label":"一般葬プラン","priceFrom":650000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホール","rating_avg":4.1,"review_count":20},
    {"name":"家族葬のファミーユ桑名","slug":"mie-famillu-kuwana","venue_type":"private_hall","description":"桑名市の家族葬専門ホール。少人数対応の温かい空間です。","address":"三重県桑名市三ツ矢橋14","prefecture_slug":"mie","city_slug":"kuwana","latitude":35.058,"longitude":136.690,"nearest_station":"近鉄名古屋線 桑名駅","station_walk_minutes":8,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":85000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":288000}],"features":["家族葬対応","少人数対応","低価格"],"operator_name":"家族葬のファミーユ","rating_avg":4.4,"review_count":14},
    {"name":"桑名市斎場","slug":"mie-kuwana-saijo","venue_type":"public_crematorium","description":"桑名市運営の公営火葬場。市民料金で利用できる施設です。","address":"三重県桑名市大字桑部字大坪1084","prefecture_slug":"mie","city_slug":"kuwana","latitude":35.055,"longitude":136.678,"nearest_station":"三岐鉄道 蓮花寺駅","station_walk_minutes":15,"capacity_max":50,"hall_count":1,"has_crematorium":True,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":50000}],"features":["公営施設","火葬場併設"],"operator_name":"桑名市","rating_avg":3.6,"review_count":25},
    {"name":"ベルコ桑名シティホール","slug":"mie-bellco-kuwana","venue_type":"private_hall","description":"桑名市のベルコ葬儀会館。広い駐車場を完備しています。","address":"三重県桑名市新矢田1-28","prefecture_slug":"mie","city_slug":"kuwana","latitude":35.065,"longitude":136.700,"nearest_station":"近鉄名古屋線 桑名駅","station_walk_minutes":15,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":348000}],"features":["家族葬対応"],"operator_name":"ベルコ","rating_avg":4.1,"review_count":18},
]

for i in range(0, len(venues), 10):
    batch = venues[i:i+10]
    code = insert_batch(batch)
    print(f"バッチ {i//10+1}: {code} ({len(batch)}件)")
    time.sleep(1)

print(f"\n完了: 合計 {len(venues)} 件")
