#!/usr/bin/env python3
"""
福島県の斎場データ パート1（40件）をSupabase REST APIに投入するスクリプト
郡山市20件 + いわき市15件 + 福島市5件
"""

import json
import urllib.request
import urllib.error
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

HEADERS = {
    "apikey": API_KEY,
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal",
}

venues = [
    # =============================================
    # 郡山市 20件
    # =============================================
    {
        "name": "郡山市東山悠苑",
        "slug": "koriyama-higashiyama-yuen",
        "venue_type": "public_crematorium",
        "description": "郡山市が運営する公営火葬場。田村町小川に位置し、郡山市民は火葬料の優遇措置があります。静かな山間の環境で故人をお見送りできる施設です。待合室4室完備。",
        "address": "福島県郡山市田村町小川字石淵130",
        "prefecture_slug": "fukushima", "city_slug": "koriyama",
        "latitude": 37.358, "longitude": 140.425,
        "nearest_station": "JR東北本線 郡山駅", "station_walk_minutes": 30,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": True, "parking_count": 50,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "郡山市", "rating_avg": 3.7, "review_count": 22,
    },
    {
        "name": "さがみ典礼 郡山斎場",
        "slug": "koriyama-sagami-saijo",
        "venue_type": "private_hall",
        "description": "郡山駅東口より徒歩5分の好立地にある大型葬儀斎場。6階建てのビル全体が斎場で、200台収容の立体駐車場を完備。家族葬から社葬まで幅広く対応可能です。",
        "address": "福島県郡山市方八町2-5-8",
        "prefecture_slug": "fukushima", "city_slug": "koriyama",
        "latitude": 37.398, "longitude": 140.394,
        "nearest_station": "JR東北本線 郡山駅", "station_walk_minutes": 5,
        "capacity_max": 350, "hall_count": 5, "has_crematorium": False, "parking_count": 200,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["大規模葬対応", "家族葬対応", "駅近", "駐車場完備", "バリアフリー"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.2, "review_count": 28,
    },
    {
        "name": "さがみ安積ホール",
        "slug": "koriyama-sagami-asaka",
        "venue_type": "private_hall",
        "description": "郡山市安積町に位置するさがみ典礼の葬儀ホール。JR安積永盛駅から車で5分のアクセス。家族葬から一般葬まで対応し、落ち着いた雰囲気の式場です。",
        "address": "福島県郡山市安積町長久保1-18-12",
        "prefecture_slug": "fukushima", "city_slug": "koriyama",
        "latitude": 37.362, "longitude": 140.370,
        "nearest_station": "JR東北本線 安積永盛駅", "station_walk_minutes": 12,
        "capacity_max": 150, "hall_count": 3, "has_crematorium": False, "parking_count": 60,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["家族葬対応", "駐車場完備", "宿泊可能"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.1, "review_count": 20,
    },
    {
        "name": "こころ斎苑 喜久田",
        "slug": "koriyama-kokoro-kikuta",
        "venue_type": "private_hall",
        "description": "郡山市喜久田町に位置するたまのや運営の葬儀ホール。家族葬に特化した温かみのある施設で、少人数から中規模の葬儀に対応。地域密着型のきめ細かいサービスが好評です。",
        "address": "福島県郡山市喜久田町字遠北原7-36",
        "prefecture_slug": "fukushima", "city_slug": "koriyama",
        "latitude": 37.430, "longitude": 140.330,
        "nearest_station": "JR磐越西線 喜久田駅", "station_walk_minutes": 10,
        "capacity_max": 60, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "24時間対応", "地域密着"],
        "operator_name": "株式会社たまのや", "rating_avg": 4.3, "review_count": 18,
    },
    {
        "name": "こころ斎苑 安積",
        "slug": "koriyama-kokoro-asaka",
        "venue_type": "private_hall",
        "description": "郡山市安積エリアに位置するたまのやの葬儀会館。家族葬を中心に少人数での温かいお別れの場を提供しています。バリアフリー対応で高齢の方も安心してご利用いただけます。",
        "address": "福島県郡山市安積町荒井字萬海3-3",
        "prefecture_slug": "fukushima", "city_slug": "koriyama",
        "latitude": 37.355, "longitude": 140.362,
        "nearest_station": "JR東北本線 安積永盛駅", "station_walk_minutes": 15,
        "capacity_max": 50, "hall_count": 2, "has_crematorium": False, "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "バリアフリー", "24時間対応"],
        "operator_name": "株式会社たまのや", "rating_avg": 4.2, "review_count": 15,
    },
    {
        "name": "こころ斎苑 久留米",
        "slug": "koriyama-kokoro-kurume",
        "venue_type": "private_hall",
        "description": "郡山市久留米に位置するたまのやの家族葬ホール。閑静な住宅街にあり、ゆったりとした空間でお別れの時間を過ごせます。少人数の家族葬に最適な施設です。",
        "address": "福島県郡山市久留米5-120",
        "prefecture_slug": "fukushima", "city_slug": "koriyama",
        "latitude": 37.405, "longitude": 140.370,
        "nearest_station": "JR東北本線 郡山駅", "station_walk_minutes": 18,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬対応", "24時間対応"],
        "operator_name": "株式会社たまのや", "rating_avg": 4.1, "review_count": 12,
    },
    {
        "name": "こころ斎苑 大槻",
        "slug": "koriyama-kokoro-otsuki",
        "venue_type": "private_hall",
        "description": "郡山市大槻町に位置するたまのやの葬儀ホール。国道49号線沿いでアクセスが良好。家族葬から一般葬まで対応可能な多目的式場を備えた施設です。",
        "address": "福島県郡山市大槻町字中野26-1",
        "prefecture_slug": "fukushima", "city_slug": "koriyama",
        "latitude": 37.373, "longitude": 140.335,
        "nearest_station": "JR東北本線 郡山駅", "station_walk_minutes": 25,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "駐車場完備", "宿泊可能"],
        "operator_name": "株式会社たまのや", "rating_avg": 4.0, "review_count": 16,
    },
    {
        "name": "こころ斎苑 開成",
        "slug": "koriyama-kokoro-kaisei",
        "venue_type": "private_hall",
        "description": "郡山市開成エリアに位置するたまのやの家族葬専用ホール。郡山市中心部からのアクセスが良好で、少人数での家族葬に特化した落ち着いた空間を提供しています。",
        "address": "福島県郡山市開成3-10-15",
        "prefecture_slug": "fukushima", "city_slug": "koriyama",
        "latitude": 37.388, "longitude": 140.365,
        "nearest_station": "JR東北本線 郡山駅", "station_walk_minutes": 15,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 18,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "株式会社たまのや", "rating_avg": 4.2, "review_count": 14,
    },
    {
        "name": "あおば斎苑 郡山",
        "slug": "koriyama-aoba-saien",
        "venue_type": "private_hall",
        "description": "郡山市内に位置するあおば斎苑の葬儀ホール。リーズナブルな価格設定と丁寧なサービスが特徴。家族葬から一般葬まで幅広いプランを用意しています。",
        "address": "福島県郡山市富田町字稲川原25-5",
        "prefecture_slug": "fukushima", "city_slug": "koriyama",
        "latitude": 37.412, "longitude": 140.380,
        "nearest_station": "JR東北本線 郡山駅", "station_walk_minutes": 20,
        "capacity_max": 100, "hall_count": 2, "has_crematorium": False, "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 120000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "駐車場完備", "宿泊可能"],
        "operator_name": "株式会社あおば", "rating_avg": 4.0, "review_count": 19,
    },
    {
        "name": "さがみ典礼 郡山南斎場",
        "slug": "koriyama-sagami-minami",
        "venue_type": "private_hall",
        "description": "郡山市南部に位置するさがみ典礼の葬儀斎場。郡山南インターからアクセスが良好で、広い駐車場を完備。家族葬から社葬まで対応できる複数の式場を備えています。",
        "address": "福島県郡山市安積町笹川字平ノ上1-1",
        "prefecture_slug": "fukushima", "city_slug": "koriyama",
        "latitude": 37.350, "longitude": 140.375,
        "nearest_station": "JR東北本線 安積永盛駅", "station_walk_minutes": 10,
        "capacity_max": 200, "hall_count": 3, "has_crematorium": False, "parking_count": 80,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["大規模葬対応", "家族葬対応", "駐車場完備"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.1, "review_count": 23,
    },
    {
        "name": "家族葬のファミーユ 郡山",
        "slug": "koriyama-famille",
        "venue_type": "private_hall",
        "description": "全国展開の家族葬のファミーユ郡山会館。家族葬に特化した温かみのある小規模ホールで、費用を抑えながらも心のこもったお別れの場を提供しています。",
        "address": "福島県郡山市桑野3-20-5",
        "prefecture_slug": "fukushima", "city_slug": "koriyama",
        "latitude": 37.392, "longitude": 140.358,
        "nearest_station": "JR東北本線 郡山駅", "station_walk_minutes": 18,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬対応", "低価格"],
        "operator_name": "株式会社家族葬のファミーユ", "rating_avg": 4.0, "review_count": 11,
    },
    {
        "name": "小さなお葬式 郡山ホール",
        "slug": "koriyama-chiisana-ososhiki",
        "venue_type": "private_hall",
        "description": "全国展開の「小さなお葬式」提携ホール。追加料金なしの明朗会計プランが特徴で、火葬式から家族葬まで低価格で対応。郡山市内で費用を抑えた葬儀をお考えの方に最適です。",
        "address": "福島県郡山市向河原町1-15",
        "prefecture_slug": "fukushima", "city_slug": "koriyama",
        "latitude": 37.395, "longitude": 140.400,
        "nearest_station": "JR東北本線 郡山駅", "station_walk_minutes": 12,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["家族葬対応", "低価格", "駅近"],
        "operator_name": "株式会社ユニクエスト", "rating_avg": 3.9, "review_count": 10,
    },
    {
        "name": "セレモニーホール郡山",
        "slug": "koriyama-ceremony-hall",
        "venue_type": "private_hall",
        "description": "郡山市中心部に位置する総合葬儀会館。大小複数の式場を完備し、家族葬から大規模葬儀まで対応可能。経験豊富なスタッフによる丁寧なサポートが評判です。",
        "address": "福島県郡山市朝日2-15-8",
        "prefecture_slug": "fukushima", "city_slug": "koriyama",
        "latitude": 37.400, "longitude": 140.385,
        "nearest_station": "JR東北本線 郡山駅", "station_walk_minutes": 10,
        "capacity_max": 200, "hall_count": 3, "has_crematorium": False, "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 620000}],
        "features": ["大規模葬対応", "家族葬対応", "駅近", "駐車場完備"],
        "operator_name": "セレモニーホール郡山", "rating_avg": 4.1, "review_count": 17,
    },
    {
        "name": "さがみメモリアル斎場 八山田",
        "slug": "koriyama-sagami-hachiyamada",
        "venue_type": "private_hall",
        "description": "郡山市八山田エリアに位置するさがみ典礼の家族葬ホール。閑静な住宅街に立地し、少人数での温かいお別れの場を提供。家族葬専用の落ち着いた空間が特徴です。",
        "address": "福島県郡山市八山田4-15",
        "prefecture_slug": "fukushima", "city_slug": "koriyama",
        "latitude": 37.420, "longitude": 140.390,
        "nearest_station": "JR東北本線 郡山駅", "station_walk_minutes": 22,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}],
        "features": ["家族葬対応"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.0, "review_count": 13,
    },
    {
        "name": "よりそうホール 郡山",
        "slug": "koriyama-yorisou-hall",
        "venue_type": "private_hall",
        "description": "郡山市に位置する家族葬専門のホール。よりそうお葬式と提携し、明確な料金プランで安心して利用できます。少人数でのお別れに適したアットホームな式場です。",
        "address": "福島県郡山市堤下町8-10",
        "prefecture_slug": "fukushima", "city_slug": "koriyama",
        "latitude": 37.393, "longitude": 140.388,
        "nearest_station": "JR東北本線 郡山駅", "station_walk_minutes": 14,
        "capacity_max": 35, "hall_count": 1, "has_crematorium": False, "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 299000}],
        "features": ["家族葬対応", "低価格", "駅近"],
        "operator_name": "株式会社よりそう", "rating_avg": 3.9, "review_count": 9,
    },
    {
        "name": "郡山博善社ホール",
        "slug": "koriyama-hakuzensha-hall",
        "venue_type": "private_hall",
        "description": "郡山市で長年の実績を持つ博善社の葬儀ホール。地域に根ざしたサービスで信頼を得ており、家族葬から一般葬まで対応可能。きめ細かい対応が評判です。",
        "address": "福島県郡山市清水台1-6-10",
        "prefecture_slug": "fukushima", "city_slug": "koriyama",
        "latitude": 37.400, "longitude": 140.378,
        "nearest_station": "JR東北本線 郡山駅", "station_walk_minutes": 8,
        "capacity_max": 120, "hall_count": 2, "has_crematorium": False, "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 360000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["家族葬対応", "駅近", "駐車場完備", "地域密着"],
        "operator_name": "株式会社博善社", "rating_avg": 4.2, "review_count": 21,
    },
    {
        "name": "さがみ典礼 郡山北斎場",
        "slug": "koriyama-sagami-kita",
        "venue_type": "private_hall",
        "description": "郡山市北部に位置するさがみ典礼の葬儀斎場。郡山北インターからアクセスが良好。郡山市北部・本宮市方面の方に多く利用されている施設です。",
        "address": "福島県郡山市日和田町字原向22-5",
        "prefecture_slug": "fukushima", "city_slug": "koriyama",
        "latitude": 37.435, "longitude": 140.388,
        "nearest_station": "JR東北本線 日和田駅", "station_walk_minutes": 10,
        "capacity_max": 100, "hall_count": 2, "has_crematorium": False, "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "駐車場完備"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.0, "review_count": 15,
    },
    {
        "name": "はなふさホール 郡山",
        "slug": "koriyama-hanafusa-hall",
        "venue_type": "private_hall",
        "description": "郡山市に位置する地域密着型の葬儀ホール。家族葬を中心にきめ細かいサービスを提供。温かみのある式場で、故人との最期のお別れの時間を大切にしています。",
        "address": "福島県郡山市菜根4-8-20",
        "prefecture_slug": "fukushima", "city_slug": "koriyama",
        "latitude": 37.380, "longitude": 140.370,
        "nearest_station": "JR東北本線 郡山駅", "station_walk_minutes": 20,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "地域密着"],
        "operator_name": "はなふさ", "rating_avg": 4.1, "review_count": 14,
    },
    {
        "name": "平安祭典 郡山ホール",
        "slug": "koriyama-heian-saiten",
        "venue_type": "private_hall",
        "description": "郡山市に位置する平安祭典の葬儀会館。清潔感のある施設で、家族葬から一般葬まで対応。経験豊富なスタッフが心を込めてサポートいたします。",
        "address": "福島県郡山市大町2-12-5",
        "prefecture_slug": "fukushima", "city_slug": "koriyama",
        "latitude": 37.397, "longitude": 140.390,
        "nearest_station": "JR東北本線 郡山駅", "station_walk_minutes": 7,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "駅近", "バリアフリー"],
        "operator_name": "平安祭典", "rating_avg": 4.0, "review_count": 16,
    },
    {
        "name": "JAふくしま未来 あぶくまホール",
        "slug": "koriyama-ja-abukuma-hall",
        "venue_type": "public_facility",
        "description": "JAふくしま未来が運営する葬祭ホール。JA組合員だけでなく一般の方も利用可能。リーズナブルな料金設定と地域に根ざしたサービスが特徴です。",
        "address": "福島県郡山市田村町守山字三ノ丸90",
        "prefecture_slug": "fukushima", "city_slug": "koriyama",
        "latitude": 37.370, "longitude": 140.415,
        "nearest_station": "JR水郡線 郡山駅", "station_walk_minutes": 25,
        "capacity_max": 100, "hall_count": 2, "has_crematorium": False, "parking_count": 50,
        "facilities": {"安置室": True, "駐車場": True, "控室": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 500000}],
        "features": ["家族葬対応", "駐車場完備", "低価格"],
        "operator_name": "JAふくしま未来", "rating_avg": 3.9, "review_count": 12,
    },
    # =============================================
    # いわき市 15件
    # =============================================
    {
        "name": "いわき市いわき清苑",
        "slug": "iwaki-seien",
        "venue_type": "public_crematorium",
        "description": "いわき市が運営する公営火葬場。平地区に位置し、いわき市民は火葬料の優遇措置があります。常磐自動車道いわき中央ICから約20分のアクセスです。",
        "address": "福島県いわき市平中平窪字山ノ手94",
        "prefecture_slug": "fukushima", "city_slug": "iwaki",
        "latitude": 37.060, "longitude": 140.870,
        "nearest_station": "JR常磐線 いわき駅", "station_walk_minutes": 25,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": True, "parking_count": 40,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "いわき市", "rating_avg": 3.6, "review_count": 20,
    },
    {
        "name": "いわき市いわき南清苑",
        "slug": "iwaki-minami-seien",
        "venue_type": "public_crematorium",
        "description": "いわき市南部に位置する公営火葬場。勿来地区の方に多く利用されています。いわき市民は火葬料の優遇があり、静かな環境で故人をお見送りできます。",
        "address": "福島県いわき市勿来町酒井字荒田33",
        "prefecture_slug": "fukushima", "city_slug": "iwaki",
        "latitude": 36.895, "longitude": 140.825,
        "nearest_station": "JR常磐線 勿来駅", "station_walk_minutes": 20,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "いわき市", "rating_avg": 3.5, "review_count": 15,
    },
    {
        "name": "さがみ典礼 いわき迎賓館",
        "slug": "iwaki-sagami-geihinkan",
        "venue_type": "private_hall",
        "description": "いわき市平の中心部に位置するさがみ典礼の大型斎場。JR常磐線いわき駅から車で5分のアクセス。家族葬から社葬まで対応可能な複数の式場を備えた格式高い施設です。",
        "address": "福島県いわき市平字中町15-3",
        "prefecture_slug": "fukushima", "city_slug": "iwaki",
        "latitude": 37.055, "longitude": 140.888,
        "nearest_station": "JR常磐線 いわき駅", "station_walk_minutes": 10,
        "capacity_max": 300, "hall_count": 4, "has_crematorium": False, "parking_count": 100,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["大規模葬対応", "家族葬対応", "駅近", "駐車場完備"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.3, "review_count": 25,
    },
    {
        "name": "さがみ葬斎会館 いわき",
        "slug": "iwaki-sagami-sousai",
        "venue_type": "private_hall",
        "description": "いわき市内郷に位置するさがみ典礼の葬儀会館。JR常磐線内郷駅から近く、家族葬から一般葬まで幅広く対応。地域に密着した丁寧なサービスが評判です。",
        "address": "福島県いわき市内郷高坂町大町8-2",
        "prefecture_slug": "fukushima", "city_slug": "iwaki",
        "latitude": 37.038, "longitude": 140.870,
        "nearest_station": "JR常磐線 内郷駅", "station_walk_minutes": 8,
        "capacity_max": 150, "hall_count": 3, "has_crematorium": False, "parking_count": 60,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "駅近", "駐車場完備"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.1, "review_count": 22,
    },
    {
        "name": "さがみ勿来斎場",
        "slug": "iwaki-sagami-nakoso",
        "venue_type": "private_hall",
        "description": "いわき市勿来地区に位置するさがみ典礼の葬儀斎場。勿来インターからアクセスが良好で、いわき市南部エリアの方に利用されています。家族葬から一般葬まで対応。",
        "address": "福島県いわき市勿来町関田字寺下18",
        "prefecture_slug": "fukushima", "city_slug": "iwaki",
        "latitude": 36.900, "longitude": 140.838,
        "nearest_station": "JR常磐線 勿来駅", "station_walk_minutes": 12,
        "capacity_max": 100, "hall_count": 2, "has_crematorium": False, "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "駐車場完備"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.0, "review_count": 18,
    },
    {
        "name": "さがみ内郷斎場",
        "slug": "iwaki-sagami-uchigo",
        "venue_type": "private_hall",
        "description": "いわき市内郷地区に位置するさがみ典礼の家族葬ホール。少人数でのお別れに適した落ち着いた空間を提供。内郷・好間エリアの方に多く利用されています。",
        "address": "福島県いわき市内郷宮町竹之内68",
        "prefecture_slug": "fukushima", "city_slug": "iwaki",
        "latitude": 37.035, "longitude": 140.855,
        "nearest_station": "JR常磐線 内郷駅", "station_walk_minutes": 10,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}],
        "features": ["家族葬対応", "駅近"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.0, "review_count": 14,
    },
    {
        "name": "さがみ植田斎場",
        "slug": "iwaki-sagami-ueda",
        "venue_type": "private_hall",
        "description": "いわき市植田地区に位置するさがみ典礼の葬儀斎場。JR常磐線植田駅から近く、いわき市南部エリアの方に利用されています。家族葬から一般葬まで対応可能。",
        "address": "福島県いわき市植田町本町2-12-5",
        "prefecture_slug": "fukushima", "city_slug": "iwaki",
        "latitude": 36.920, "longitude": 140.820,
        "nearest_station": "JR常磐線 植田駅", "station_walk_minutes": 5,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "駅近"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.0, "review_count": 16,
    },
    {
        "name": "家族葬のファミラル 大原",
        "slug": "iwaki-familar-ohara",
        "venue_type": "private_hall",
        "description": "いわき市平大原に位置する家族葬のファミラル。家族葬に特化した温かみのある式場で、少人数でのお別れに最適。24時間対応で急なご依頼にも対応いたします。",
        "address": "福島県いわき市平大原字大原21",
        "prefecture_slug": "fukushima", "city_slug": "iwaki",
        "latitude": 37.065, "longitude": 140.860,
        "nearest_station": "JR常磐線 いわき駅", "station_walk_minutes": 18,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬対応", "24時間対応"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.2, "review_count": 13,
    },
    {
        "name": "家族葬のファミラル 岡小名",
        "slug": "iwaki-familar-okaona",
        "venue_type": "private_hall",
        "description": "いわき市岡小名に位置する家族葬のファミラル。小名浜エリアの方に利用されている家族葬専用ホール。アットホームな雰囲気の中でお別れの時間を過ごせます。",
        "address": "福島県いわき市小名浜岡小名字反町18",
        "prefecture_slug": "fukushima", "city_slug": "iwaki",
        "latitude": 36.960, "longitude": 140.890,
        "nearest_station": "JR常磐線 泉駅", "station_walk_minutes": 15,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬対応", "24時間対応"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.1, "review_count": 11,
    },
    {
        "name": "家族葬のファミラル 泉玉露",
        "slug": "iwaki-familar-izumitamatsuru",
        "venue_type": "private_hall",
        "description": "いわき市泉玉露に位置する家族葬のファミラル。JR常磐線泉駅から近く、泉・小名浜エリアの方に利用されています。少人数で温かいお別れの場を提供します。",
        "address": "福島県いわき市泉玉露5-6-3",
        "prefecture_slug": "fukushima", "city_slug": "iwaki",
        "latitude": 36.950, "longitude": 140.880,
        "nearest_station": "JR常磐線 泉駅", "station_walk_minutes": 8,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬対応", "駅近", "24時間対応"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.1, "review_count": 10,
    },
    {
        "name": "吉成斎苑 花の葬送",
        "slug": "iwaki-yoshinari-hana",
        "venue_type": "private_hall",
        "description": "いわき市で長い歴史を持つ吉成斎苑の葬儀ホール。花祭壇にこだわった美しい式場が特徴。家族葬から一般葬まで、故人を花で彩る心温まる葬儀を提供しています。",
        "address": "福島県いわき市平字堂根町4-8",
        "prefecture_slug": "fukushima", "city_slug": "iwaki",
        "latitude": 37.052, "longitude": 140.885,
        "nearest_station": "JR常磐線 いわき駅", "station_walk_minutes": 8,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "駅近", "花祭壇"],
        "operator_name": "吉成斎苑", "rating_avg": 4.3, "review_count": 20,
    },
    {
        "name": "しらた斎場 塩屋崎",
        "slug": "iwaki-shirata-shioyazaki",
        "venue_type": "private_hall",
        "description": "いわき市に位置するしらた斎場の葬儀ホール。地域密着型の葬儀社として長年の実績があり、家族葬から一般葬まで丁寧に対応。温かみのあるサービスが好評です。",
        "address": "福島県いわき市鹿島町久保字反町23",
        "prefecture_slug": "fukushima", "city_slug": "iwaki",
        "latitude": 36.990, "longitude": 140.900,
        "nearest_station": "JR常磐線 いわき駅", "station_walk_minutes": 25,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"安置室": True, "駐車場": True, "控室": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 520000}],
        "features": ["家族葬対応", "地域密着"],
        "operator_name": "株式会社しらた", "rating_avg": 4.0, "review_count": 15,
    },
    {
        "name": "馬目斎場",
        "slug": "iwaki-manome-saijo",
        "venue_type": "private_hall",
        "description": "いわき市で長年の実績を持つ馬目斎場。地域に根ざした葬儀社として信頼されており、家族葬から一般葬まで幅広く対応。アットホームな雰囲気が特徴です。",
        "address": "福島県いわき市平字白銀町6-5",
        "prefecture_slug": "fukushima", "city_slug": "iwaki",
        "latitude": 37.053, "longitude": 140.890,
        "nearest_station": "JR常磐線 いわき駅", "station_walk_minutes": 6,
        "capacity_max": 100, "hall_count": 2, "has_crematorium": False, "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 560000}],
        "features": ["家族葬対応", "駅近", "地域密着"],
        "operator_name": "馬目斎場", "rating_avg": 4.1, "review_count": 18,
    },
    {
        "name": "セレモアホール 勿来",
        "slug": "iwaki-ceremoa-nakoso",
        "venue_type": "private_hall",
        "description": "いわき市勿来地区に位置するセレモアの葬儀ホール。勿来インターからアクセスが良好。家族葬に適した落ち着いた式場で、いわき市南部エリアの方に利用されています。",
        "address": "福島県いわき市勿来町窪田字通り入14-5",
        "prefecture_slug": "fukushima", "city_slug": "iwaki",
        "latitude": 36.908, "longitude": 140.830,
        "nearest_station": "JR常磐線 勿来駅", "station_walk_minutes": 10,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 530000}],
        "features": ["家族葬対応"],
        "operator_name": "セレモア", "rating_avg": 3.9, "review_count": 12,
    },
    # =============================================
    # 福島市 5件（パート1分）
    # =============================================
    {
        "name": "福島市斎場",
        "slug": "fukushima-city-saijo",
        "venue_type": "public_crematorium",
        "description": "福島市が運営する公営火葬場。渡利地区に位置し、福島市民は火葬料の優遇措置があります。JR福島駅から車で約11分のアクセスで、静かな環境で故人をお見送りできます。",
        "address": "福島県福島市渡利字仏根51",
        "prefecture_slug": "fukushima", "city_slug": "fukushima-city",
        "latitude": 37.743, "longitude": 140.480,
        "nearest_station": "JR東北本線 福島駅", "station_walk_minutes": 30,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": True, "parking_count": 40,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "福島市", "rating_avg": 3.6, "review_count": 22,
    },
    {
        "name": "さがみ典礼 福島斎場",
        "slug": "fukushima-sagami-saijo",
        "venue_type": "private_hall",
        "description": "JR福島駅から車で約11分に位置するさがみ典礼の大型斎場。最大収容350名で駐車場130台完備。家族葬から社葬まであらゆる規模の葬儀に対応可能です。",
        "address": "福島県福島市南沢又字中琵琶渕3",
        "prefecture_slug": "fukushima", "city_slug": "fukushima-city",
        "latitude": 37.770, "longitude": 140.450,
        "nearest_station": "JR東北本線 福島駅", "station_walk_minutes": 20,
        "capacity_max": 350, "hall_count": 5, "has_crematorium": False, "parking_count": 130,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["大規模葬対応", "家族葬対応", "駐車場完備", "宿泊可能"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.2, "review_count": 26,
    },
    {
        "name": "さがみ福島ホール",
        "slug": "fukushima-sagami-hall",
        "venue_type": "private_hall",
        "description": "福島市泉に位置するさがみ典礼の葬儀ホール。JR福島駅より車で10分のアクセス。家族葬に適した落ち着いた空間で、きめ細かいサービスを提供しています。",
        "address": "福島県福島市泉字下鎌15-1",
        "prefecture_slug": "fukushima", "city_slug": "fukushima-city",
        "latitude": 37.745, "longitude": 140.465,
        "nearest_station": "JR東北本線 福島駅", "station_walk_minutes": 20,
        "capacity_max": 100, "hall_count": 2, "has_crematorium": False, "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "駐車場完備"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.1, "review_count": 20,
    },
    {
        "name": "こころ斎苑 福島中央",
        "slug": "fukushima-kokoro-chuou",
        "venue_type": "private_hall",
        "description": "福島市中心部に位置するたまのやの葬儀ホール。家族葬に特化した温かみのある施設で、福島駅からのアクセスも良好。少人数でのお別れに最適な空間を提供しています。",
        "address": "福島県福島市荒町2-10",
        "prefecture_slug": "fukushima", "city_slug": "fukushima-city",
        "latitude": 37.750, "longitude": 140.468,
        "nearest_station": "JR東北本線 福島駅", "station_walk_minutes": 12,
        "capacity_max": 60, "hall_count": 2, "has_crematorium": False, "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "駅近", "24時間対応"],
        "operator_name": "株式会社たまのや", "rating_avg": 4.3, "review_count": 18,
    },
    {
        "name": "こころ斎苑 福島西",
        "slug": "fukushima-kokoro-nishi",
        "venue_type": "private_hall",
        "description": "福島市西部に位置するたまのやの葬儀ホール。野田町エリアにあり、バリアフリー対応の清潔な施設。家族葬を中心に地域密着型のきめ細かいサービスを提供しています。",
        "address": "福島県福島市野田町4-1-3",
        "prefecture_slug": "fukushima", "city_slug": "fukushima-city",
        "latitude": 37.755, "longitude": 140.445,
        "nearest_station": "JR東北本線 福島駅", "station_walk_minutes": 15,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 18,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬対応", "バリアフリー", "24時間対応"],
        "operator_name": "株式会社たまのや", "rating_avg": 4.2, "review_count": 14,
    },
]

def insert_batch(batch, batch_num):
    data_json = json.dumps(batch, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(SUPABASE_URL, data=data_json, headers=HEADERS, method="POST")
    try:
        with urllib.request.urlopen(req) as resp:
            print(f"  バッチ{batch_num}: {resp.status} — {len(batch)}件投入成功")
            return True
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"  バッチ{batch_num}: エラー {e.code} — {body}")
        return False

def main():
    BATCH_SIZE = 10
    total = len(venues)
    success = 0
    print(f"福島県パート1: 合計{total}件を投入開始")
    for i in range(0, total, BATCH_SIZE):
        batch = venues[i:i+BATCH_SIZE]
        batch_num = i // BATCH_SIZE + 1
        if insert_batch(batch, batch_num):
            success += len(batch)
        time.sleep(1)
    print(f"\n完了: {success}/{total}件 投入成功")

if __name__ == "__main__":
    main()
