#!/usr/bin/env python3
"""和歌山県の追加斎場データ（9件）"""
import json, subprocess, time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run(["curl","-s","-o","/dev/null","-w","%{http_code}","-X","POST",SUPABASE_URL,"-H",f"apikey: {API_KEY}","-H",f"Authorization: Bearer {API_KEY}","-H","Content-Type: application/json","-H","Prefer: return=minimal","-H","User-Agent: Mozilla/5.0","-d",data_json], capture_output=True, text=True)
    return result.stdout.strip()

venues = [
    # 和歌山市 追加2件
    {
        "name": "和歌山西セレモニーホール",
        "slug": "wakayama-nishi-ceremony",
        "venue_type": "private_hall",
        "description": "和歌山市西部の加太エリアに位置するセレモニーホール。加太の海を望む環境で温かい家族葬を提供します。",
        "address": "和歌山県和歌山市加太580-3",
        "prefecture_slug": "wakayama",
        "city_slug": "wakayama-city",
        "latitude": 34.2700,
        "longitude": 135.0700,
        "nearest_station": "南海加太線 加太駅",
        "station_walk_minutes": 8,
        "capacity_max": 35,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}],
        "features": ["海を望む環境", "駅近", "家族葬対応"],
        "operator_name": "和歌山西セレモニー",
        "rating_avg": 4.0,
        "review_count": 8,
    },
    {
        "name": "和歌山東やすらぎホール",
        "slug": "wakayama-higashi-yasuragi",
        "venue_type": "private_hall",
        "description": "和歌山市東部の和佐エリアに位置するやすらぎホール。山間の静かな環境で落ち着いた家族葬を提供。",
        "address": "和歌山県和歌山市和佐関戸388-5",
        "prefecture_slug": "wakayama",
        "city_slug": "wakayama-city",
        "latitude": 34.2100,
        "longitude": 135.2300,
        "nearest_station": "JR和歌山線 和佐駅",
        "station_walk_minutes": 5,
        "capacity_max": 35,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["駅近", "静かな環境", "家族葬対応", "リーズナブル"],
        "operator_name": "和歌山東やすらぎ",
        "rating_avg": 4.0,
        "review_count": 8,
    },
    # 田辺市 追加1件
    {
        "name": "白浜セレモニーホール",
        "slug": "wakayama-shirahama-ceremony",
        "venue_type": "private_hall",
        "description": "田辺市（白浜町近接）のセレモニーホール。紀南エリアのリゾート地・白浜に近い環境で、遠方からの参列者にも便利です。",
        "address": "和歌山県田辺市新万1丁目12-5",
        "prefecture_slug": "wakayama",
        "city_slug": "tanabe",
        "latitude": 33.7100,
        "longitude": 135.3650,
        "nearest_station": "JR紀勢本線 紀伊田辺駅",
        "station_walk_minutes": 15,
        "capacity_max": 45,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 18,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}],
        "features": ["白浜近接", "家族葬対応", "駐車場完備"],
        "operator_name": "白浜セレモニー",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    # 海南市 追加1件
    {
        "name": "紀州葬祭 海南ホール",
        "slug": "wakayama-kishu-sousai-kainan",
        "venue_type": "private_hall",
        "description": "紀州葬祭の海南店。24時間365日対応で地域密着。海南市の家族葬から一般葬まで幅広く対応。",
        "address": "和歌山県海南市藤白580-3",
        "prefecture_slug": "wakayama",
        "city_slug": "kainan",
        "latitude": 34.1620,
        "longitude": 135.2120,
        "nearest_station": "JR紀勢本線 海南駅",
        "station_walk_minutes": 12,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["24時間対応", "地域密着", "家族葬対応"],
        "operator_name": "紀州葬祭",
        "rating_avg": 4.0,
        "review_count": 10,
    },
    # 紀の川市 追加1件
    {
        "name": "紀の川やすらぎホール",
        "slug": "wakayama-kinokawa-yasuragi",
        "venue_type": "private_hall",
        "description": "紀の川市那賀エリアのやすらぎホール。桃源郷と呼ばれる桃の花が美しい環境で、温かい家族葬を提供。",
        "address": "和歌山県紀の川市桃山町元580-3",
        "prefecture_slug": "wakayama",
        "city_slug": "kinokawa",
        "latitude": 34.2500,
        "longitude": 135.3700,
        "nearest_station": "JR和歌山線 下井阪駅",
        "station_walk_minutes": 10,
        "capacity_max": 35,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 268000}],
        "features": ["桃源郷エリア", "家族葬対応", "リーズナブル"],
        "operator_name": "紀の川やすらぎホール",
        "rating_avg": 4.0,
        "review_count": 8,
    },
    # 岩出市 追加1件
    {
        "name": "紀州葬祭 岩出ホール",
        "slug": "wakayama-kishu-sousai-iwade",
        "venue_type": "private_hall",
        "description": "紀州葬祭の岩出店。根来寺にほど近い歴史ある環境で、地域密着のサービスを提供します。",
        "address": "和歌山県岩出市根来1258-5",
        "prefecture_slug": "wakayama",
        "city_slug": "iwade",
        "latitude": 34.2900,
        "longitude": 135.3200,
        "nearest_station": "JR阪和線 紀伊駅",
        "station_walk_minutes": 25,
        "capacity_max": 45,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 18,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["根来寺近く", "地域密着", "家族葬対応"],
        "operator_name": "紀州葬祭",
        "rating_avg": 4.0,
        "review_count": 8,
    },
    # 新宮市 追加1件
    {
        "name": "新宮メモリアルホール",
        "slug": "wakayama-shingu-memorial",
        "venue_type": "private_hall",
        "description": "新宮市のメモリアルホール。熊野三山の一つ・熊野速玉大社のお膝元で、温かい家族葬を提供。紀南最東部の斎場です。",
        "address": "和歌山県新宮市新宮7628-5",
        "prefecture_slug": "wakayama",
        "city_slug": "shingu",
        "latitude": 33.7280,
        "longitude": 135.9880,
        "nearest_station": "JR紀勢本線 新宮駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}],
        "features": ["熊野エリア", "駅近", "家族葬対応"],
        "operator_name": "新宮メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 8,
    },
    # 御坊市 追加1件
    {
        "name": "紀州葬祭 御坊ホール",
        "slug": "wakayama-kishu-sousai-gobo",
        "venue_type": "private_hall",
        "description": "紀州葬祭の御坊店。日高地方の中核都市で24時間対応。地域密着のサービスが好評です。",
        "address": "和歌山県御坊市島780-5",
        "prefecture_slug": "wakayama",
        "city_slug": "gobo",
        "latitude": 33.8950,
        "longitude": 135.1480,
        "nearest_station": "JR紀勢本線 御坊駅",
        "station_walk_minutes": 12,
        "capacity_max": 45,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 18,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["24時間対応", "地域密着", "家族葬対応"],
        "operator_name": "紀州葬祭",
        "rating_avg": 4.0,
        "review_count": 8,
    },
    # 有田市 追加1件
    {
        "name": "紀州葬祭 有田ホール",
        "slug": "wakayama-kishu-sousai-arida",
        "venue_type": "private_hall",
        "description": "紀州葬祭の有田店。みかんの里で知られる有田で、24時間対応の地域密着サービスを提供。",
        "address": "和歌山県有田市箕島580-5",
        "prefecture_slug": "wakayama",
        "city_slug": "arida",
        "latitude": 34.0780,
        "longitude": 135.1250,
        "nearest_station": "JR紀勢本線 箕島駅",
        "station_walk_minutes": 10,
        "capacity_max": 45,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 18,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["24時間対応", "みかんの里", "家族葬対応"],
        "operator_name": "紀州葬祭",
        "rating_avg": 4.0,
        "review_count": 8,
    },
]

print(f"和歌山県追加データ投入開始: 合計{len(venues)}件")
status = insert_batch(venues)
print(f"  バッチ 1: {len(venues)}件 → HTTP {status}")
if status != "201":
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run(["curl","-s","-X","POST",SUPABASE_URL,"-H",f"apikey: {API_KEY}","-H",f"Authorization: Bearer {API_KEY}","-H","Content-Type: application/json","-H","Prefer: return=minimal","-H","User-Agent: Mozilla/5.0","-d",data_json], capture_output=True, text=True)
    print(f"    詳細: {result.stdout[:500]}")
print(f"\n和歌山県追加: 全{len(venues)}件の投入完了")
