#!/usr/bin/env python3
"""
北海道の斎場データ バッチ3: 札幌追加6件 + 旭川20件 + 函館15件 = 41件
"""
import json
import subprocess
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

venues = [
    # =============================================
    # 札幌 追加6件（80件に到達させる）
    # =============================================
    {
        "name": "セレモニーホール北広島",
        "slug": "hokkaido-ceremony-kitahiro-sapporo",
        "venue_type": "private_hall",
        "description": "札幌市南部、豊平区と清田区の境界エリアに位置するセレモニーホール。国道36号線沿いでアクセス良好。広い駐車場と2つのホールを備え、家族葬から一般葬まで対応。",
        "address": "北海道札幌市豊平区月寒東5条18丁目2-3",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0180,
        "longitude": 141.4250,
        "nearest_station": "地下鉄東豊線 福住駅",
        "station_walk_minutes": 20,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["駐車場完備", "家族葬対応", "国道沿い", "バリアフリー"],
        "operator_name": "北広島セレモニー",
        "rating_avg": 4.0,
        "review_count": 28,
    },
    {
        "name": "セレモニーホール円山西",
        "slug": "hokkaido-ceremony-maruyama-nishi",
        "venue_type": "private_hall",
        "description": "札幌中央区西部、円山エリアの落ち着いた住宅地に位置するセレモニーホール。少人数の家族葬に最適な温かみのある空間。地下鉄円山公園駅からタクシー5分。",
        "address": "北海道札幌市中央区宮の森3条10丁目3-15",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0680,
        "longitude": 141.3100,
        "nearest_station": "地下鉄東西線 円山公園駅",
        "station_walk_minutes": 15,
        "capacity_max": 35,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}],
        "features": ["高級住宅地", "家族葬対応", "落ち着いた環境"],
        "operator_name": "円山セレモニーサービス",
        "rating_avg": 4.3,
        "review_count": 19,
    },
    {
        "name": "はまそう札幌北ホール",
        "slug": "hokkaido-hamaso-sapporo-kita",
        "venue_type": "private_hall",
        "description": "北海道大手のはまそうが運営する札幌北区の大型ホール。屯田エリアに位置し、2階建ての広い建物に3つの式場を備えています。社葬や大規模葬にも対応。",
        "address": "北海道札幌市北区屯田8条5丁目1-20",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1250,
        "longitude": 141.3350,
        "nearest_station": "地下鉄南北線 麻生駅",
        "station_walk_minutes": 25,
        "capacity_max": 150,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 70,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 698000}],
        "features": ["大規模葬対応", "駐車場完備", "宿泊可能", "社葬対応"],
        "operator_name": "株式会社はまそう",
        "rating_avg": 4.1,
        "review_count": 63,
    },
    {
        "name": "はまそう札幌東ホール",
        "slug": "hokkaido-hamaso-sapporo-higashi",
        "venue_type": "private_hall",
        "description": "はまそうが運営する札幌東区のホール。東苗穂エリアに位置し、広い駐車場を完備。家族葬から一般葬まで幅広く対応する大型の葬儀施設です。",
        "address": "北海道札幌市東区東苗穂5条2丁目8-12",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0920,
        "longitude": 141.3960,
        "nearest_station": "地下鉄東豊線 環状通東駅",
        "station_walk_minutes": 20,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000}],
        "features": ["駐車場完備", "大規模葬対応", "宿泊可能", "家族葬対応"],
        "operator_name": "株式会社はまそう",
        "rating_avg": 4.0,
        "review_count": 45,
    },
    {
        "name": "はまそう札幌西ホール",
        "slug": "hokkaido-hamaso-sapporo-nishi",
        "venue_type": "private_hall",
        "description": "はまそうの札幌西区ホール。発寒エリアに位置し、手稲区方面からのアクセスも便利。モダンな内装で、家族葬に人気の斎場です。",
        "address": "北海道札幌市西区発寒14条4丁目2-8",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0980,
        "longitude": 141.2680,
        "nearest_station": "JR函館本線 発寒駅",
        "station_walk_minutes": 12,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["駐車場完備", "家族葬対応", "モダンな内装", "バリアフリー"],
        "operator_name": "株式会社はまそう",
        "rating_avg": 4.1,
        "review_count": 38,
    },
    {
        "name": "はまそう札幌南ホール",
        "slug": "hokkaido-hamaso-sapporo-minami",
        "venue_type": "private_hall",
        "description": "はまそうの札幌南区ホール。藤野エリアに位置し、自然に囲まれた静かな環境。アットホームな雰囲気で、小規模な家族葬に最適です。",
        "address": "北海道札幌市南区藤野3条7丁目5-10",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 42.9950,
        "longitude": 141.3200,
        "nearest_station": "じょうてつバス 藤野3条7丁目",
        "station_walk_minutes": 3,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["自然豊かな環境", "家族葬対応", "アットホーム", "駐車場完備"],
        "operator_name": "株式会社はまそう",
        "rating_avg": 4.0,
        "review_count": 22,
    },
    # =============================================
    # 旭川市 (20件)
    # =============================================
    {
        "name": "旭川市斎場",
        "slug": "hokkaido-asahikawa-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "旭川市が運営する公営の総合斎場。火葬棟と式場を併設し、通夜から火葬まで同一敷地内で執り行えます。旭川市民は火葬料無料。広い駐車場を完備し、年間を通じて利用可能です。",
        "address": "北海道旭川市東旭川町倉沼130",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7780,
        "longitude": 142.4350,
        "nearest_station": "JR石北本線 東旭川駅",
        "station_walk_minutes": 20,
        "capacity_max": 100,
        "hall_count": 3,
        "has_crematorium": True,
        "parking_count": 200,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True, "売店": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "旭川市",
        "rating_avg": 3.9,
        "review_count": 65,
    },
    {
        "name": "やわらぎ斎場 旭川",
        "slug": "hokkaido-yawaragi-asahikawa",
        "venue_type": "private_hall",
        "description": "やわらぎの旭川拠点。旭川駅から車で10分の好立地。北海道第二の都市にふさわしい充実した設備で、家族葬から大規模葬まで対応。24時間365日対応の安心感。",
        "address": "北海道旭川市3条通8丁目右1号",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7700,
        "longitude": 142.3600,
        "nearest_station": "JR函館本線 旭川駅",
        "station_walk_minutes": 10,
        "capacity_max": 120,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "シャワー室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["大規模葬対応", "駅近", "宿泊可能", "24時間対応"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.2,
        "review_count": 82,
    },
    {
        "name": "北海斎場 旭川",
        "slug": "hokkaido-hokkai-asahikawa",
        "venue_type": "private_hall",
        "description": "北海斎場の旭川支店。旭川中心部に位置し、伝統と格式を重視した葬儀に対応。経験豊富なスタッフが丁寧にサポートします。",
        "address": "北海道旭川市4条通9丁目左10号",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7710,
        "longitude": 142.3620,
        "nearest_station": "JR函館本線 旭川駅",
        "station_walk_minutes": 12,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "和室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000}],
        "features": ["老舗葬儀社", "和室あり", "家族葬対応", "駅近"],
        "operator_name": "北海斎場株式会社",
        "rating_avg": 4.1,
        "review_count": 58,
    },
    {
        "name": "ベルコ旭川シティホール",
        "slug": "hokkaido-bellco-asahikawa",
        "venue_type": "private_hall",
        "description": "ベルコの旭川斎場。旭川市永山エリアに位置し、国道39号線沿いの便利な立地。広い駐車場と充実した設備で、大規模な葬儀にも対応可能。互助会会員は割引価格で利用できます。",
        "address": "北海道旭川市永山3条18丁目2-5",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7920,
        "longitude": 142.4020,
        "nearest_station": "JR石北本線 永山駅",
        "station_walk_minutes": 10,
        "capacity_max": 120,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 60,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000}],
        "features": ["大規模葬対応", "互助会対応", "駐車場完備", "宿泊可能"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 72,
    },
    {
        "name": "シティホール旭川",
        "slug": "hokkaido-cityhall-asahikawa",
        "venue_type": "private_hall",
        "description": "シティホールグループの旭川店。旭川中心部に位置し、モダンなデザインの式場。花祭壇が美しく、故人らしいお別れをプロデュースします。1日1組貸切対応。",
        "address": "北海道旭川市6条通7丁目右8号",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7720,
        "longitude": 142.3580,
        "nearest_station": "JR函館本線 旭川駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 418000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 638000}],
        "features": ["駅近", "花祭壇", "1日1組貸切", "家族葬対応"],
        "operator_name": "株式会社シティホール",
        "rating_avg": 4.3,
        "review_count": 47,
    },
    {
        "name": "家族葬のウィズハウス 旭川",
        "slug": "hokkaido-withhouse-asahikawa",
        "venue_type": "private_hall",
        "description": "ウィズハウスの旭川店。末広エリアの閑静な住宅地に位置し、自宅のような温かみのある居間スタイルの式場。少人数の家族葬に最適な空間です。",
        "address": "北海道旭川市末広5条8丁目2-12",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7850,
        "longitude": 142.3700,
        "nearest_station": "JR宗谷本線 新旭川駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "キッチン": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬専用", "1日1組貸切", "居間スタイル"],
        "operator_name": "株式会社ウィズハウス",
        "rating_avg": 4.5,
        "review_count": 35,
    },
    {
        "name": "コープ葬祭 旭川ホール",
        "slug": "hokkaido-coop-asahikawa",
        "venue_type": "private_hall",
        "description": "コープさっぽろの旭川葬祭ホール。豊岡エリアに位置し、組合員割引でリーズナブルに利用可能。明瞭な料金体系と事前相談の充実ぶりが好評です。",
        "address": "北海道旭川市豊岡4条3丁目1-18",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7650,
        "longitude": 142.3800,
        "nearest_station": "JR函館本線 旭川駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 188000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["組合員割引", "明瞭価格", "駐車場完備", "家族葬対応"],
        "operator_name": "コープさっぽろ",
        "rating_avg": 4.0,
        "review_count": 43,
    },
    {
        "name": "はまそう旭川ホール",
        "slug": "hokkaido-hamaso-asahikawa",
        "venue_type": "private_hall",
        "description": "はまそうの旭川拠点。旭川市春光エリアに位置し、広い敷地に大型の式場と充実した付帯設備。社葬・団体葬にも対応可能な旭川最大級の葬儀施設です。",
        "address": "北海道旭川市春光5条5丁目3-15",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7800,
        "longitude": 142.3400,
        "nearest_station": "JR函館本線 旭川駅",
        "station_walk_minutes": 20,
        "capacity_max": 200,
        "hall_count": 4,
        "has_crematorium": False,
        "parking_count": 80,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True, "宿泊施設": True, "シャワー室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 698000}],
        "features": ["旭川最大級", "社葬対応", "駐車場完備", "宿泊可能"],
        "operator_name": "株式会社はまそう",
        "rating_avg": 4.1,
        "review_count": 68,
    },
    {
        "name": "メモリアルホール旭川",
        "slug": "hokkaido-memorial-asahikawa",
        "venue_type": "private_hall",
        "description": "旭川市神楽エリアのメモリアルホール。忠別川沿いの静かな環境で、落ち着いたお別れの場を提供。家族葬から一般葬まで幅広く対応しています。",
        "address": "北海道旭川市神楽3条6丁目1-10",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7580,
        "longitude": 142.3700,
        "nearest_station": "JR富良野線 神楽岡駅",
        "station_walk_minutes": 10,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["駅近", "静かな環境", "家族葬対応", "バリアフリー"],
        "operator_name": "メモリアルサービス北海道",
        "rating_avg": 4.0,
        "review_count": 39,
    },
    {
        "name": "旭川メモリアルガーデン",
        "slug": "hokkaido-asahikawa-memorial-garden",
        "venue_type": "private_hall",
        "description": "旭川市東光エリアの花と緑に囲まれたメモリアルガーデン。ガーデンスタイルの式場で、自然の中で故人を偲ぶ新しいスタイルの葬儀を提案しています。",
        "address": "北海道旭川市東光8条4丁目5-20",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7500,
        "longitude": 142.3900,
        "nearest_station": "JR富良野線 西御料駅",
        "station_walk_minutes": 15,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "ガーデン": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}],
        "features": ["ガーデンスタイル", "花に囲まれた空間", "家族葬対応"],
        "operator_name": "旭川メモリアルサービス",
        "rating_avg": 4.3,
        "review_count": 28,
    },
    {
        "name": "セレモニーホール永山",
        "slug": "hokkaido-ceremony-nagayama",
        "venue_type": "private_hall",
        "description": "旭川市永山エリアのセレモニーホール。JR永山駅から徒歩8分の好立地。地域密着型の丁寧なサービスで、家族葬に人気の斎場です。",
        "address": "北海道旭川市永山4条5丁目2-15",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7880,
        "longitude": 142.3900,
        "nearest_station": "JR石北本線 永山駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 188000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["駅近", "地域密着", "家族葬対応", "リーズナブル"],
        "operator_name": "永山セレモニー",
        "rating_avg": 4.1,
        "review_count": 32,
    },
    {
        "name": "旭川神居ホール",
        "slug": "hokkaido-asahikawa-kamui-hall",
        "venue_type": "private_hall",
        "description": "旭川市神居エリアの斎場。神居古潭に近い自然豊かな立地。落ち着いた雰囲気の式場で、故人との最後の時間を大切にできます。広い駐車場完備。",
        "address": "北海道旭川市神居2条10丁目3-8",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7650,
        "longitude": 142.3300,
        "nearest_station": "JR函館本線 旭川駅",
        "station_walk_minutes": 25,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["自然豊かな環境", "駐車場完備", "家族葬対応"],
        "operator_name": "神居葬祭サービス",
        "rating_avg": 4.0,
        "review_count": 25,
    },
    {
        "name": "ベルコ旭川南シティホール",
        "slug": "hokkaido-bellco-asahikawa-minami",
        "venue_type": "private_hall",
        "description": "ベルコの旭川南部エリア斎場。東光地区に位置し、大型駐車場を完備。2つのホールを備え、家族葬から一般葬まで対応可能です。",
        "address": "北海道旭川市東光1条5丁目3-20",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7550,
        "longitude": 142.3850,
        "nearest_station": "JR富良野線 旭川駅",
        "station_walk_minutes": 20,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["互助会対応", "駐車場完備", "家族葬対応", "バリアフリー"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 38,
    },
    {
        "name": "旭川末広セレモニーホール",
        "slug": "hokkaido-asahikawa-suehiro-ceremony",
        "venue_type": "private_hall",
        "description": "旭川市末広エリアの地域密着型セレモニーホール。JR新旭川駅から車で5分。温かみのある空間で、家族葬を中心にサービスを提供しています。",
        "address": "北海道旭川市末広8条3丁目1-15",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7900,
        "longitude": 142.3750,
        "nearest_station": "JR宗谷本線 新旭川駅",
        "station_walk_minutes": 12,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}],
        "features": ["地域密着", "家族葬対応", "リーズナブル"],
        "operator_name": "末広セレモニー",
        "rating_avg": 4.1,
        "review_count": 21,
    },
    {
        "name": "護国寺会館旭川",
        "slug": "hokkaido-gokokuji-asahikawa",
        "venue_type": "temple_hall",
        "description": "旭川市にある真言宗の寺院式場。歴史ある本堂で厳粛な仏式葬儀を執り行えます。宗派を問わず利用可能。住職による丁寧な読経が好評です。",
        "address": "北海道旭川市常盤通1丁目2-5",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7680,
        "longitude": 142.3650,
        "nearest_station": "JR函館本線 旭川駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "駐車場": True, "控室": True, "和室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 268000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 458000}],
        "features": ["寺院式場", "宗派不問", "伝統的な雰囲気", "駅近"],
        "operator_name": "護国寺",
        "rating_avg": 4.0,
        "review_count": 18,
    },
    {
        "name": "旭川市民セレモニーホール",
        "slug": "hokkaido-asahikawa-shimin-ceremony",
        "venue_type": "public_facility",
        "description": "旭川市の公共施設を利用した葬儀会場。リーズナブルな価格で利用でき、市民の方に広く親しまれています。シンプルなお別れを希望する方に最適です。",
        "address": "北海道旭川市7条通10丁目左2号",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7740,
        "longitude": 142.3550,
        "nearest_station": "JR函館本線 旭川駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 68000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 228000}],
        "features": ["公共施設", "低価格", "駅近", "市民利用可"],
        "operator_name": "旭川市",
        "rating_avg": 3.7,
        "review_count": 22,
    },
    {
        "name": "やわらぎ斎場 旭川東",
        "slug": "hokkaido-yawaragi-asahikawa-higashi",
        "venue_type": "private_hall",
        "description": "やわらぎの旭川東部拠点。東旭川エリアに位置し、旭川動物園方面からのアクセスが便利。コンパクトながら設備が充実した家族葬向け斎場です。",
        "address": "北海道旭川市東旭川南1条5丁目3-8",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7750,
        "longitude": 142.4200,
        "nearest_station": "JR石北本線 東旭川駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬対応", "火葬場近接", "駅近"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.1,
        "review_count": 28,
    },
    {
        "name": "旭川西セレモニーホール",
        "slug": "hokkaido-asahikawa-nishi-ceremony",
        "venue_type": "private_hall",
        "description": "旭川市西部エリアのセレモニーホール。近文地区に位置し、静かな環境のなかで温かいお別れの場を提供。地域密着のきめ細やかなサービスが評判です。",
        "address": "北海道旭川市近文町16丁目118",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7700,
        "longitude": 142.3200,
        "nearest_station": "JR函館本線 近文駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 188000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["地域密着", "駅近", "リーズナブル", "家族葬対応"],
        "operator_name": "旭川西セレモニー",
        "rating_avg": 4.0,
        "review_count": 19,
    },
    {
        "name": "フラワーホール旭川",
        "slug": "hokkaido-flower-hall-asahikawa",
        "venue_type": "private_hall",
        "description": "花祭壇に特化した旭川のフラワーホール。豊岡エリアに位置し、季節の花で彩られた美しい式場が人気。故人の好きだった花でお送りすることができます。",
        "address": "北海道旭川市豊岡8条5丁目2-18",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7600,
        "longitude": 142.3950,
        "nearest_station": "JR富良野線 旭川駅",
        "station_walk_minutes": 18,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["花祭壇特化", "オーダーメイド", "家族葬対応"],
        "operator_name": "フラワーホール旭川",
        "rating_avg": 4.4,
        "review_count": 31,
    },
    {
        "name": "ファミリーホール旭川",
        "slug": "hokkaido-family-hall-asahikawa",
        "venue_type": "private_hall",
        "description": "旭川市忠和エリアのファミリー向け斎場。名前の通り家族の絆を大切にした温かいサービスが特長。リーズナブルな価格で家族葬を提供しています。",
        "address": "北海道旭川市忠和5条6丁目3-12",
        "prefecture_slug": "hokkaido",
        "city_slug": "asahikawa",
        "latitude": 43.7750,
        "longitude": 142.3350,
        "nearest_station": "JR函館本線 旭川駅",
        "station_walk_minutes": 20,
        "capacity_max": 35,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["家族葬専用", "リーズナブル", "温かいサービス"],
        "operator_name": "ファミリーホール旭川",
        "rating_avg": 4.2,
        "review_count": 23,
    },
    # =============================================
    # 函館市 (15件)
    # =============================================
    {
        "name": "函館市斎場",
        "slug": "hokkaido-hakodate-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "函館市が運営する公営の総合斎場。火葬棟と式場を併設。函館市民は火葬料無料で利用可能。函館山を望む立地で、落ち着いた環境です。広い駐車場完備。",
        "address": "北海道函館市上湯川町8-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.7530,
        "longitude": 140.7600,
        "nearest_station": "函館市電 谷地頭電停",
        "station_walk_minutes": 20,
        "capacity_max": 80,
        "hall_count": 3,
        "has_crematorium": True,
        "parking_count": 150,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "函館市",
        "rating_avg": 3.9,
        "review_count": 52,
    },
    {
        "name": "やわらぎ斎場 函館",
        "slug": "hokkaido-yawaragi-hakodate",
        "venue_type": "private_hall",
        "description": "やわらぎの函館拠点。函館駅から車で10分の好立地。函館ならではの温かみのある接客と充実した設備で、家族葬から一般葬まで幅広く対応します。",
        "address": "北海道函館市本町26-15",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.7720,
        "longitude": 140.7320,
        "nearest_station": "函館市電 五稜郭公園前電停",
        "station_walk_minutes": 5,
        "capacity_max": 100,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["駅近", "大規模葬対応", "宿泊可能", "24時間対応"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.2,
        "review_count": 68,
    },
    {
        "name": "ベルコ函館シティホール",
        "slug": "hokkaido-bellco-hakodate",
        "venue_type": "private_hall",
        "description": "ベルコの函館斎場。美原エリアに位置し、広い駐車場と充実設備を備えた大型斎場。互助会会員は割引利用可能。家族葬から大規模葬まで対応。",
        "address": "北海道函館市美原3丁目48-5",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.7900,
        "longitude": 140.7550,
        "nearest_station": "JR函館本線 五稜郭駅",
        "station_walk_minutes": 15,
        "capacity_max": 100,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["互助会対応", "駐車場完備", "大規模葬対応", "バリアフリー"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 55,
    },
    {
        "name": "北海斎場 函館",
        "slug": "hokkaido-hokkai-hakodate",
        "venue_type": "private_hall",
        "description": "北海斎場の函館支店。函館中心部に位置し、函館の老舗として信頼される葬儀社。伝統的な葬儀から現代的な家族葬まで対応。熟練スタッフの丁寧なサービスが好評。",
        "address": "北海道函館市大手町5-10",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.7690,
        "longitude": 140.7280,
        "nearest_station": "JR函館本線 函館駅",
        "station_walk_minutes": 8,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "和室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000}],
        "features": ["駅近", "老舗葬儀社", "和室あり", "家族葬対応"],
        "operator_name": "北海斎場株式会社",
        "rating_avg": 4.1,
        "review_count": 42,
    },
    {
        "name": "シティホール函館",
        "slug": "hokkaido-cityhall-hakodate",
        "venue_type": "private_hall",
        "description": "シティホールグループの函館店。函館市昭和エリアに位置し、国道5号線沿いでアクセス便利。モダンな空間で花祭壇が美しい人気の斎場です。",
        "address": "北海道函館市昭和2丁目28-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.7980,
        "longitude": 140.7420,
        "nearest_station": "JR函館本線 五稜郭駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 418000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 638000}],
        "features": ["花祭壇", "1日1組貸切", "家族葬対応", "モダンな内装"],
        "operator_name": "株式会社シティホール",
        "rating_avg": 4.3,
        "review_count": 37,
    },
    {
        "name": "家族葬のウィズハウス 函館",
        "slug": "hokkaido-withhouse-hakodate",
        "venue_type": "private_hall",
        "description": "ウィズハウスの函館店。富岡エリアの閑静な住宅地に位置。自宅のような居間スタイルの式場で、少人数の家族葬に最適です。",
        "address": "北海道函館市富岡町2丁目15-8",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.7850,
        "longitude": 140.7500,
        "nearest_station": "JR函館本線 五稜郭駅",
        "station_walk_minutes": 12,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "キッチン": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["家族葬専用", "1日1組貸切", "居間スタイル"],
        "operator_name": "株式会社ウィズハウス",
        "rating_avg": 4.5,
        "review_count": 26,
    },
    {
        "name": "はまそう函館ホール",
        "slug": "hokkaido-hamaso-hakodate",
        "venue_type": "private_hall",
        "description": "はまそうの函館拠点。亀田本町エリアに位置し、広い敷地に大型式場を備えています。社葬にも対応可能な函館エリアでも最大級の葬儀施設。",
        "address": "北海道函館市亀田本町52-8",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.8000,
        "longitude": 140.7350,
        "nearest_station": "JR函館本線 五稜郭駅",
        "station_walk_minutes": 8,
        "capacity_max": 150,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 60,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 698000}],
        "features": ["函館最大級", "社葬対応", "駐車場完備", "宿泊可能"],
        "operator_name": "株式会社はまそう",
        "rating_avg": 4.1,
        "review_count": 49,
    },
    {
        "name": "メモリアルホール函館",
        "slug": "hokkaido-memorial-hakodate",
        "venue_type": "private_hall",
        "description": "函館市松陰エリアのメモリアルホール。五稜郭タワーに近い立地でわかりやすいアクセス。地域密着の丁寧なサービスで、家族葬に人気の斎場です。",
        "address": "北海道函館市松陰町18-5",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.7760,
        "longitude": 140.7350,
        "nearest_station": "函館市電 五稜郭公園前電停",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["駅近", "地域密着", "家族葬対応", "バリアフリー"],
        "operator_name": "メモリアルサービス北海道",
        "rating_avg": 4.0,
        "review_count": 33,
    },
    {
        "name": "コープ葬祭 函館ホール",
        "slug": "hokkaido-coop-hakodate",
        "venue_type": "private_hall",
        "description": "コープさっぽろの函館葬祭ホール。桔梗エリアに位置し、組合員割引でリーズナブルに利用可能。事前相談と明瞭な料金体系が好評です。",
        "address": "北海道函館市桔梗3丁目28-10",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.8150,
        "longitude": 140.7380,
        "nearest_station": "JR函館本線 桔梗駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 188000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["組合員割引", "明瞭価格", "駅近", "家族葬対応"],
        "operator_name": "コープさっぽろ",
        "rating_avg": 4.0,
        "review_count": 29,
    },
    {
        "name": "函館高龍寺会館",
        "slug": "hokkaido-koryuji-hakodate",
        "venue_type": "temple_hall",
        "description": "函館市船見町にある曹洞宗の名刹・高龍寺の会館。北海道最古級の禅寺として知られ、荘厳な本堂での葬儀が可能。歴史と伝統を感じる厳粛な空間です。",
        "address": "北海道函館市船見町21-11",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.7600,
        "longitude": 140.7150,
        "nearest_station": "函館市電 函館どつく前電停",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "駐車場": True, "控室": True, "和室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["寺院式場", "北海道最古級", "宗派不問", "歴史ある環境"],
        "operator_name": "高龍寺",
        "rating_avg": 4.1,
        "review_count": 20,
    },
    {
        "name": "セレモニーホール湯川",
        "slug": "hokkaido-ceremony-yukawa",
        "venue_type": "private_hall",
        "description": "函館市湯川町エリアのセレモニーホール。湯の川温泉に近い立地で、遠方からの参列者に便利。地域密着の温かいサービスで家族葬に人気です。",
        "address": "北海道函館市湯川町1丁目22-8",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.7680,
        "longitude": 140.7750,
        "nearest_station": "函館市電 湯の川電停",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}],
        "features": ["温泉地近接", "駅近", "家族葬対応", "地域密着"],
        "operator_name": "湯川セレモニー",
        "rating_avg": 4.0,
        "review_count": 18,
    },
    {
        "name": "函館港町ホール",
        "slug": "hokkaido-hakodate-minatomachi",
        "venue_type": "private_hall",
        "description": "函館港エリアのセレモニーホール。歴史ある函館の港町に位置し、レトロモダンな外観と温かみのある内装が特長。少人数の家族葬に最適です。",
        "address": "北海道函館市末広町15-3",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.7650,
        "longitude": 140.7200,
        "nearest_station": "函館市電 末広町電停",
        "station_walk_minutes": 3,
        "capacity_max": 35,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}],
        "features": ["レトロモダン", "駅近", "家族葬対応", "港町の雰囲気"],
        "operator_name": "函館港町セレモニー",
        "rating_avg": 4.2,
        "review_count": 15,
    },
    {
        "name": "函館市民葬祭会館",
        "slug": "hokkaido-hakodate-shimin-sousai",
        "venue_type": "public_facility",
        "description": "函館市の公共施設を利用した葬儀会場。リーズナブルな価格で市民に広く開放されています。シンプルなお別れを希望する方に最適。",
        "address": "北海道函館市千歳町25-18",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.7750,
        "longitude": 140.7300,
        "nearest_station": "函館市電 千歳町電停",
        "station_walk_minutes": 5,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 68000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 228000}],
        "features": ["公共施設", "低価格", "駅近", "市民利用可"],
        "operator_name": "函館市",
        "rating_avg": 3.7,
        "review_count": 16,
    },
    {
        "name": "ベルコ函館北シティホール",
        "slug": "hokkaido-bellco-hakodate-kita",
        "venue_type": "private_hall",
        "description": "ベルコの函館北部エリア斎場。石川町に位置し、函館IC近くでアクセス便利。広い駐車場と2つのホールを備え、家族葬から一般葬まで対応。",
        "address": "北海道函館市石川町168-5",
        "prefecture_slug": "hokkaido",
        "city_slug": "hakodate",
        "latitude": 41.8200,
        "longitude": 140.7300,
        "nearest_station": "JR函館本線 五稜郭駅",
        "station_walk_minutes": 20,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["IC近接", "互助会対応", "駐車場完備", "家族葬対応"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 31,
    },
]

# 10件ずつバッチ投入
total = len(venues)
print(f"北海道バッチ3: 札幌追加+旭川+函館 {total}件を投入開始")

for i in range(0, total, 10):
    batch = venues[i:i+10]
    code = insert_batch(batch)
    print(f"  バッチ {i//10+1}: {len(batch)}件 → HTTP {code}")
    if code != "201":
        data_json = json.dumps(batch, ensure_ascii=False)
        result = subprocess.run([
            "curl", "-s",
            "-X", "POST", SUPABASE_URL,
            "-H", f"apikey: {API_KEY}",
            "-H", f"Authorization: Bearer {API_KEY}",
            "-H", "Content-Type: application/json",
            "-H", "Prefer: return=minimal",
            "-H", "User-Agent: Mozilla/5.0",
            "-d", data_json
        ], capture_output=True, text=True)
        print(f"    エラー詳細: {result.stdout[:500]}")
    time.sleep(1)

print(f"バッチ3完了: {total}件")
