#!/usr/bin/env python3
"""
青森県の斎場データをSupabase REST APIに投入するスクリプト
40件を10件ずつバッチでPOSTする
"""

import json
import subprocess
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

venues = [
    # =============================================
    # 青森市 (aomori-city) — 10件
    # =============================================
    {
        "name": "青森市斎場",
        "slug": "aomori-aomori-city-saijo",
        "venue_type": "public_crematorium",
        "description": "青森市が運営する公営の火葬場。新町野地区に位置し、青森市民は低料金で利用可能。火葬棟と待合室を備え、ねぶたの里・青森の市民の火葬を担う中心施設です。青森駅から車で約15分。",
        "address": "青森県青森市大字新町野字菅谷138-1",
        "prefecture_slug": "aomori",
        "city_slug": "aomori-city",
        "latitude": 40.8350,
        "longitude": 140.7500,
        "nearest_station": "JR奥羽本線 青森駅",
        "station_walk_minutes": 35,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 60,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応", "バリアフリー"],
        "operator_name": "青森市",
        "rating_avg": 3.9,
        "review_count": 22,
    },
    {
        "name": "青森セレモニーホール",
        "slug": "aomori-ceremony-hall-aomori",
        "venue_type": "private_hall",
        "description": "青森市中心部にある大型の民営葬儀会館。青森駅から車で10分の好アクセス。家族葬から大規模な一般葬まで幅広く対応。充実した設備と経験豊富なスタッフが、格式ある葬儀をサポートします。",
        "address": "青森県青森市浪打1-16-25",
        "prefecture_slug": "aomori",
        "city_slug": "aomori-city",
        "latitude": 40.8250,
        "longitude": 140.7600,
        "nearest_station": "JR東北本線 青森駅",
        "station_walk_minutes": 20,
        "capacity_max": 150,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 60,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 115000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 278000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 408000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000}],
        "features": ["大規模葬対応", "家族葬対応", "宿泊可能", "駐車場完備", "バリアフリー"],
        "operator_name": "青森セレモニーホール",
        "rating_avg": 4.2,
        "review_count": 20,
    },
    {
        "name": "家族葬のファミリア青森",
        "slug": "aomori-familia-aomori",
        "venue_type": "private_hall",
        "description": "青森市の家族葬専用ホール。少人数でのアットホームな葬儀に特化し、1日1組限定の貸切空間で故人との最後の時間をゆっくり過ごせます。安置施設完備。",
        "address": "青森県青森市桂木4-5-18",
        "prefecture_slug": "aomori",
        "city_slug": "aomori-city",
        "latitude": 40.8200,
        "longitude": 140.7400,
        "nearest_station": "JR奥羽本線 青森駅",
        "station_walk_minutes": 18,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["家族葬専用", "1日1組限定", "安置施設あり", "少人数葬対応"],
        "operator_name": "ファミリア",
        "rating_avg": 4.3,
        "review_count": 15,
    },
    {
        "name": "青森典礼会館",
        "slug": "aomori-tenrei-kaikan",
        "venue_type": "private_hall",
        "description": "青森市の老舗葬儀式場。家族葬から一般葬まで、津軽地方の葬儀文化に精通したスタッフが丁寧にサポート。広い駐車場を完備し、冬季の雪にも対応した施設です。",
        "address": "青森県青森市松原2-8-30",
        "prefecture_slug": "aomori",
        "city_slug": "aomori-city",
        "latitude": 40.8180,
        "longitude": 140.7550,
        "nearest_station": "JR奥羽本線 青森駅",
        "station_walk_minutes": 22,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 45,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["家族葬対応", "一般葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "青森典礼会館",
        "rating_avg": 4.0,
        "review_count": 16,
    },
    {
        "name": "コープ葬祭青森",
        "slug": "aomori-coop-aomori",
        "venue_type": "private_hall",
        "description": "青森県生協が運営する青森市の葬祭センター。組合員価格で明瞭な料金体系が特徴。家族葬から一般葬まで、地域に根差したサービスを提供しています。",
        "address": "青森県青森市千刈1-12-8",
        "prefecture_slug": "aomori",
        "city_slug": "aomori-city",
        "latitude": 40.8280,
        "longitude": 140.7650,
        "nearest_station": "JR東北本線 青森駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 488000}],
        "features": ["生協運営", "組合員割引", "家族葬対応", "駐車場完備"],
        "operator_name": "青森県生活協同組合",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "青森やすらぎホール",
        "slug": "aomori-yasuragi-hall",
        "venue_type": "private_hall",
        "description": "青森市内の民営葬儀ホール。家族葬を中心に、温かみのある空間で故人を偲べます。冬季も安心の暖房完備で、バリアフリー設計です。",
        "address": "青森県青森市緑3-10-15",
        "prefecture_slug": "aomori",
        "city_slug": "aomori-city",
        "latitude": 40.8150,
        "longitude": 140.7480,
        "nearest_station": "JR奥羽本線 青森駅",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬対応", "少人数葬対応", "バリアフリー", "駐車場完備"],
        "operator_name": "青森やすらぎホール",
        "rating_avg": 3.9,
        "review_count": 10,
    },
    {
        "name": "サンセルモ玉泉院青森会館",
        "slug": "aomori-sunselmo-aomori",
        "venue_type": "private_hall",
        "description": "全国展開のサンセルモ玉泉院が青森で運営する葬儀会館。豊富な経験とノウハウで、家族葬から一般葬まで幅広く対応。充実した設備が整った格式ある式場です。",
        "address": "青森県青森市中央1-22-8",
        "prefecture_slug": "aomori",
        "city_slug": "aomori-city",
        "latitude": 40.8230,
        "longitude": 140.7520,
        "nearest_station": "JR東北本線 青森駅",
        "station_walk_minutes": 12,
        "capacity_max": 120,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 115000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 278000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 408000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000}],
        "features": ["大規模葬対応", "家族葬対応", "宿泊可能", "駅近", "駐車場完備"],
        "operator_name": "株式会社サンセルモ",
        "rating_avg": 4.1,
        "review_count": 14,
    },
    {
        "name": "浪岡斎場",
        "slug": "aomori-namioka-saijo",
        "venue_type": "public_crematorium",
        "description": "青森市浪岡地区にある公営火葬場。旧浪岡町エリアの市民の火葬を担い、低料金で利用可能。りんご畑に囲まれた静かな環境で故人を見送れます。",
        "address": "青森県青森市浪岡大字女鹿沢字平野155",
        "prefecture_slug": "aomori",
        "city_slug": "aomori-city",
        "latitude": 40.7200,
        "longitude": 140.5900,
        "nearest_station": "JR奥羽本線 浪岡駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 20,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "青森市",
        "rating_avg": 3.5,
        "review_count": 5,
    },
    {
        "name": "青森メモリアルガーデン",
        "slug": "aomori-memorial-garden",
        "venue_type": "private_hall",
        "description": "青森市郊外にある葬儀ホール。陸奥湾を望む環境で、家族葬から中規模の葬儀まで対応。自然に囲まれた落ち着いた空間で心温まるお別れの場を提供します。",
        "address": "青森県青森市浜田3-5-20",
        "prefecture_slug": "aomori",
        "city_slug": "aomori-city",
        "latitude": 40.8300,
        "longitude": 140.7350,
        "nearest_station": "JR奥羽本線 青森駅",
        "station_walk_minutes": 25,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "一般葬対応", "駐車場完備", "自然環境"],
        "operator_name": "青森メモリアルガーデン",
        "rating_avg": 4.0,
        "review_count": 9,
    },
    {
        "name": "東青森典礼ホール",
        "slug": "aomori-higashi-aomori-tenrei",
        "venue_type": "private_hall",
        "description": "青森市東部に位置する葬儀式場。東北自動車道青森ICからのアクセスが良く、遠方からの参列者にも便利。家族葬から一般葬まで幅広く対応します。",
        "address": "青森県青森市八重田1-6-30",
        "prefecture_slug": "aomori",
        "city_slug": "aomori-city",
        "latitude": 40.8220,
        "longitude": 140.7700,
        "nearest_station": "青い森鉄道 筒井駅",
        "station_walk_minutes": 12,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 568000}],
        "features": ["家族葬対応", "一般葬対応", "IC近い", "宿泊可能", "駐車場完備"],
        "operator_name": "東青森典礼ホール",
        "rating_avg": 4.0,
        "review_count": 11,
    },

    # =============================================
    # 八戸市 (hachinohe) — 8件
    # =============================================
    {
        "name": "八戸市斎場",
        "slug": "aomori-hachinohe-saijo",
        "venue_type": "public_crematorium",
        "description": "八戸市が運営する公営の火葬場。下長地区に位置し、八戸市民は低料金で利用可能。JR本八戸駅からタクシーで約20分。火葬棟と待合室を備えた静かな環境です。",
        "address": "青森県八戸市下長4-22-12",
        "prefecture_slug": "aomori",
        "city_slug": "hachinohe",
        "latitude": 40.5100,
        "longitude": 141.5100,
        "nearest_station": "JR八戸線 本八戸駅",
        "station_walk_minutes": 35,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 50,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 245000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応", "バリアフリー"],
        "operator_name": "八戸市",
        "rating_avg": 3.8,
        "review_count": 18,
    },
    {
        "name": "八戸セレモニーホール",
        "slug": "aomori-ceremony-hall-hachinohe",
        "venue_type": "private_hall",
        "description": "八戸市中心部にある大型の民営葬儀会館。JR本八戸駅から車で10分。家族葬から大規模な一般葬まで対応し、南部地方の葬儀文化に精通したスタッフが丁寧にサポートします。",
        "address": "青森県八戸市城下1-12-5",
        "prefecture_slug": "aomori",
        "city_slug": "hachinohe",
        "latitude": 40.5120,
        "longitude": 141.4900,
        "nearest_station": "JR八戸線 本八戸駅",
        "station_walk_minutes": 12,
        "capacity_max": 120,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["大規模葬対応", "家族葬対応", "駅近", "宿泊可能", "駐車場完備"],
        "operator_name": "八戸セレモニーホール",
        "rating_avg": 4.2,
        "review_count": 19,
    },
    {
        "name": "家族葬のファミリア八戸",
        "slug": "aomori-familia-hachinohe",
        "venue_type": "private_hall",
        "description": "八戸市の家族葬専用ホール。1日1組限定の貸切空間で、少人数のアットホームな葬儀に最適。安置施設完備で、故人と家族の大切な時間を守ります。",
        "address": "青森県八戸市柏崎3-8-12",
        "prefecture_slug": "aomori",
        "city_slug": "hachinohe",
        "latitude": 40.5080,
        "longitude": 141.4950,
        "nearest_station": "JR八戸線 本八戸駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬専用", "1日1組限定", "安置施設あり", "少人数葬対応"],
        "operator_name": "ファミリア",
        "rating_avg": 4.3,
        "review_count": 13,
    },
    {
        "name": "八戸典礼会館",
        "slug": "aomori-hachinohe-tenrei-kaikan",
        "venue_type": "private_hall",
        "description": "八戸市の葬儀式場。家族葬から一般葬まで幅広く対応し、充実した設備で心のこもったサービスを提供。八戸自動車道からのアクセスも便利です。",
        "address": "青森県八戸市沼館4-3-25",
        "prefecture_slug": "aomori",
        "city_slug": "hachinohe",
        "latitude": 40.5050,
        "longitude": 141.5050,
        "nearest_station": "JR八戸線 小中野駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 568000}],
        "features": ["家族葬対応", "一般葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "八戸典礼会館",
        "rating_avg": 4.0,
        "review_count": 14,
    },
    {
        "name": "サンセルモ玉泉院八戸会館",
        "slug": "aomori-sunselmo-hachinohe",
        "venue_type": "private_hall",
        "description": "サンセルモ玉泉院が八戸で運営する葬儀会館。全国チェーンの安心感と地域密着のサービスを両立。家族葬から一般葬まで豊富な実績で対応します。",
        "address": "青森県八戸市吹上2-10-18",
        "prefecture_slug": "aomori",
        "city_slug": "hachinohe",
        "latitude": 40.5150,
        "longitude": 141.4850,
        "nearest_station": "JR八戸線 本八戸駅",
        "station_walk_minutes": 10,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 45,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 112000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 275000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 405000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 608000}],
        "features": ["大規模葬対応", "家族葬対応", "駅近", "宿泊可能", "駐車場完備"],
        "operator_name": "株式会社サンセルモ",
        "rating_avg": 4.1,
        "review_count": 13,
    },
    {
        "name": "コープ葬祭八戸",
        "slug": "aomori-coop-hachinohe",
        "venue_type": "private_hall",
        "description": "生協が運営する八戸市の葬祭センター。組合員価格で明瞭な料金体系。家族葬から一般葬まで、地域に根差した安心のサービスを提供しています。",
        "address": "青森県八戸市根城5-12-8",
        "prefecture_slug": "aomori",
        "city_slug": "hachinohe",
        "latitude": 40.5200,
        "longitude": 141.4800,
        "nearest_station": "JR八戸線 本八戸駅",
        "station_walk_minutes": 18,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 285000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 485000}],
        "features": ["生協運営", "組合員割引", "家族葬対応", "駐車場完備"],
        "operator_name": "青森県生活協同組合",
        "rating_avg": 3.9,
        "review_count": 9,
    },
    {
        "name": "八戸メモリアルホール",
        "slug": "aomori-hachinohe-memorial-hall",
        "venue_type": "private_hall",
        "description": "八戸市の葬儀ホール。三陸海岸に近い環境で、家族葬から中規模の葬儀まで対応。地域に密着したきめ細かなサービスが特徴です。",
        "address": "青森県八戸市湊町字大沢12-8",
        "prefecture_slug": "aomori",
        "city_slug": "hachinohe",
        "latitude": 40.5030,
        "longitude": 141.5200,
        "nearest_station": "JR八戸線 陸奥湊駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "駐車場完備"],
        "operator_name": "八戸メモリアルホール",
        "rating_avg": 3.9,
        "review_count": 10,
    },
    {
        "name": "八戸南部家族葬ホール",
        "slug": "aomori-hachinohe-nanbu-kazokuso",
        "venue_type": "private_hall",
        "description": "八戸市南部の家族葬専用ホール。南部せんべいの里で、少人数でのアットホームな葬儀に特化。故人と家族の大切な時間を守る温かい空間です。",
        "address": "青森県八戸市新井田字松山下2-5",
        "prefecture_slug": "aomori",
        "city_slug": "hachinohe",
        "latitude": 40.4950,
        "longitude": 141.5150,
        "nearest_station": "JR八戸線 白銀駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専用", "少人数葬対応", "安置施設あり", "駐車場完備"],
        "operator_name": "八戸南部家族葬ホール",
        "rating_avg": 4.1,
        "review_count": 8,
    },

    # =============================================
    # 弘前市 (hirosaki) — 8件
    # =============================================
    {
        "name": "弘前市斎場",
        "slug": "aomori-hirosaki-saijo",
        "venue_type": "public_crematorium",
        "description": "弘前市が運営する公営の火葬場。桜の名所・弘前城で知られる弘前市民の火葬を担い、低料金で利用可能。弘南鉄道弘高下駅からタクシーで約8分。",
        "address": "青森県弘前市大字八幡町3-4-9",
        "prefecture_slug": "aomori",
        "city_slug": "hirosaki",
        "latitude": 40.5800,
        "longitude": 140.4750,
        "nearest_station": "弘南鉄道大鰐線 弘高下駅",
        "station_walk_minutes": 20,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 40,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 245000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応", "バリアフリー"],
        "operator_name": "弘前市",
        "rating_avg": 3.8,
        "review_count": 16,
    },
    {
        "name": "ファミリ庵弘前",
        "slug": "aomori-familian-hirosaki",
        "venue_type": "private_hall",
        "description": "弘前市で人気の家族葬対応ホール。津軽の城下町にふさわしい落ち着いた雰囲気で、家族葬から一般葬まで幅広く対応。経験豊富なスタッフが心のこもったサービスを提供します。",
        "address": "青森県弘前市土手町75-1",
        "prefecture_slug": "aomori",
        "city_slug": "hirosaki",
        "latitude": 40.5920,
        "longitude": 140.4700,
        "nearest_station": "JR奥羽本線 弘前駅",
        "station_walk_minutes": 15,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 568000}],
        "features": ["家族葬対応", "一般葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "ファミリ庵",
        "rating_avg": 4.3,
        "review_count": 18,
    },
    {
        "name": "松安閣弘前",
        "slug": "aomori-shoankan-hirosaki",
        "venue_type": "private_hall",
        "description": "弘前市で人気の葬儀会館。弘前城近くの好立地で、格式ある一般葬から家族葬まで対応。津軽の伝統を大切にしたサービスで、地域住民から高い評価を得ています。",
        "address": "青森県弘前市城東中央3-5-15",
        "prefecture_slug": "aomori",
        "city_slug": "hirosaki",
        "latitude": 40.5900,
        "longitude": 140.4800,
        "nearest_station": "JR奥羽本線 弘前駅",
        "station_walk_minutes": 12,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 45,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["大規模葬対応", "家族葬対応", "駅近", "宿泊可能", "駐車場完備"],
        "operator_name": "松安閣",
        "rating_avg": 4.2,
        "review_count": 20,
    },
    {
        "name": "弘前家族葬ホール",
        "slug": "aomori-hirosaki-kazokuso-hall",
        "venue_type": "private_hall",
        "description": "弘前市の家族葬専用ホール。少人数でのアットホームな葬儀に特化。桜の街・弘前で、故人と家族の大切な時間を守る温かい空間です。",
        "address": "青森県弘前市早稲田2-3-8",
        "prefecture_slug": "aomori",
        "city_slug": "hirosaki",
        "latitude": 40.5850,
        "longitude": 140.4650,
        "nearest_station": "JR奥羽本線 弘前駅",
        "station_walk_minutes": 18,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬専用", "少人数葬対応", "安置施設あり", "駐車場完備"],
        "operator_name": "弘前家族葬ホール",
        "rating_avg": 4.1,
        "review_count": 12,
    },
    {
        "name": "コープ葬祭弘前",
        "slug": "aomori-coop-hirosaki",
        "venue_type": "private_hall",
        "description": "生協が運営する弘前市の葬祭センター。組合員価格で明瞭な料金体系。家族葬から一般葬まで、津軽地方に根差したサービスを提供しています。",
        "address": "青森県弘前市大字駅前町11-5",
        "prefecture_slug": "aomori",
        "city_slug": "hirosaki",
        "latitude": 40.5930,
        "longitude": 140.4850,
        "nearest_station": "JR奥羽本線 弘前駅",
        "station_walk_minutes": 5,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 285000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 485000}],
        "features": ["生協運営", "組合員割引", "駅近", "家族葬対応"],
        "operator_name": "青森県生活協同組合",
        "rating_avg": 4.0,
        "review_count": 10,
    },
    {
        "name": "弘前やすらぎホール",
        "slug": "aomori-hirosaki-yasuragi-hall",
        "venue_type": "private_hall",
        "description": "弘前市の民営葬儀ホール。岩木山を望む環境で、家族葬を中心に温かみのある空間で故人を偲べます。バリアフリー設計で高齢者にも配慮した施設です。",
        "address": "青森県弘前市石渡3-2-18",
        "prefecture_slug": "aomori",
        "city_slug": "hirosaki",
        "latitude": 40.5870,
        "longitude": 140.4600,
        "nearest_station": "JR奥羽本線 弘前駅",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬対応", "少人数葬対応", "バリアフリー", "駐車場完備"],
        "operator_name": "弘前やすらぎホール",
        "rating_avg": 3.9,
        "review_count": 8,
    },
    {
        "name": "サンセルモ玉泉院弘前会館",
        "slug": "aomori-sunselmo-hirosaki",
        "venue_type": "private_hall",
        "description": "サンセルモ玉泉院が弘前で運営する葬儀会館。全国チェーンの安定感と津軽地方の葬儀文化への理解を両立。家族葬から一般葬まで幅広く対応します。",
        "address": "青森県弘前市大字田園1-8-5",
        "prefecture_slug": "aomori",
        "city_slug": "hirosaki",
        "latitude": 40.5950,
        "longitude": 140.4900,
        "nearest_station": "JR奥羽本線 弘前駅",
        "station_walk_minutes": 10,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 112000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 275000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 405000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 608000}],
        "features": ["大規模葬対応", "家族葬対応", "駅近", "宿泊可能", "駐車場完備"],
        "operator_name": "株式会社サンセルモ",
        "rating_avg": 4.1,
        "review_count": 11,
    },
    {
        "name": "弘前南典礼ホール",
        "slug": "aomori-hirosaki-minami-tenrei",
        "venue_type": "private_hall",
        "description": "弘前市南部に位置する葬儀式場。弘前公園や岩木山を背景に、家族葬から中規模の葬儀まで対応。地域に密着したサービスで温かいお別れの場を提供します。",
        "address": "青森県弘前市千年3-5-12",
        "prefecture_slug": "aomori",
        "city_slug": "hirosaki",
        "latitude": 40.5780,
        "longitude": 140.4720,
        "nearest_station": "弘南鉄道大鰐線 千年駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "駐車場完備"],
        "operator_name": "弘前南典礼ホール",
        "rating_avg": 3.9,
        "review_count": 9,
    },

    # =============================================
    # 十和田市 (towada) — 3件
    # =============================================
    {
        "name": "十和田市斎場",
        "slug": "aomori-towada-saijo",
        "venue_type": "public_crematorium",
        "description": "十和田市が運営する公営の火葬場。十和田湖で有名な十和田市民の火葬を担い、低料金で利用可能。自然に囲まれた静かな環境です。",
        "address": "青森県十和田市大字三本木字野崎40-1",
        "prefecture_slug": "aomori",
        "city_slug": "towada",
        "latitude": 40.6100,
        "longitude": 141.2050,
        "nearest_station": "青い森鉄道 三沢駅",
        "station_walk_minutes": 40,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応"],
        "operator_name": "十和田市",
        "rating_avg": 3.6,
        "review_count": 8,
    },
    {
        "name": "十和田セレモニーホール",
        "slug": "aomori-towada-ceremony-hall",
        "venue_type": "private_hall",
        "description": "十和田市の民営葬儀会館。十和田湖の観光地として知られる十和田市で、家族葬から一般葬まで対応。地域に密着したきめ細かなサービスを提供します。",
        "address": "青森県十和田市稲生町15-30",
        "prefecture_slug": "aomori",
        "city_slug": "towada",
        "latitude": 40.6120,
        "longitude": 141.2100,
        "nearest_station": "青い森鉄道 三沢駅",
        "station_walk_minutes": 35,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["家族葬対応", "一般葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "十和田セレモニーホール",
        "rating_avg": 4.0,
        "review_count": 10,
    },
    {
        "name": "十和田家族葬ホール",
        "slug": "aomori-towada-kazokuso-hall",
        "venue_type": "private_hall",
        "description": "十和田市の家族葬専用ホール。少人数でのアットホームな葬儀に特化。十和田の自然に囲まれた穏やかな環境で、故人と家族の大切な時間を守ります。",
        "address": "青森県十和田市西二番町5-8",
        "prefecture_slug": "aomori",
        "city_slug": "towada",
        "latitude": 40.6080,
        "longitude": 141.2000,
        "nearest_station": "青い森鉄道 三沢駅",
        "station_walk_minutes": 38,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専用", "少人数葬対応", "安置施設あり", "駐車場完備"],
        "operator_name": "十和田家族葬ホール",
        "rating_avg": 4.0,
        "review_count": 7,
    },

    # =============================================
    # むつ市 (mutsu) — 2件
    # =============================================
    {
        "name": "むつ市斎場",
        "slug": "aomori-mutsu-saijo",
        "venue_type": "public_crematorium",
        "description": "むつ市が運営する公営の火葬場。下北半島の中心都市・むつ市民の火葬を担い、低料金で利用可能。恐山で知られる下北の自然の中で故人を見送れます。",
        "address": "青森県むつ市大字田名部字赤川ノ内尻35-80",
        "prefecture_slug": "aomori",
        "city_slug": "mutsu",
        "latitude": 41.2850,
        "longitude": 141.1800,
        "nearest_station": "JR大湊線 下北駅",
        "station_walk_minutes": 20,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 25,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応"],
        "operator_name": "むつ市",
        "rating_avg": 3.6,
        "review_count": 7,
    },
    {
        "name": "むつセレモニーホール",
        "slug": "aomori-mutsu-ceremony-hall",
        "venue_type": "private_hall",
        "description": "むつ市の民営葬儀会館。下北半島の中心で、家族葬から一般葬まで対応。地域の風習に精通したスタッフが、心のこもったサービスを提供します。",
        "address": "青森県むつ市中央1-5-20",
        "prefecture_slug": "aomori",
        "city_slug": "mutsu",
        "latitude": 41.2900,
        "longitude": 141.1850,
        "nearest_station": "JR大湊線 下北駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "駐車場完備"],
        "operator_name": "むつセレモニーホール",
        "rating_avg": 3.9,
        "review_count": 8,
    },

    # =============================================
    # その他の市（三沢市、五所川原市、黒石市、つがる市、平川市）— 計9件
    # =============================================

    # 三沢市 (misawa) — 2件
    {
        "name": "三沢市斎場",
        "slug": "aomori-misawa-saijo",
        "venue_type": "public_crematorium",
        "description": "三沢市が運営する公営の火葬場。航空自衛隊基地で知られる三沢市民の火葬を担い、低料金で利用可能。静かな環境で故人を見送れます。",
        "address": "青森県三沢市大字三沢字堀口164-560",
        "prefecture_slug": "aomori",
        "city_slug": "misawa",
        "latitude": 40.6800,
        "longitude": 141.3700,
        "nearest_station": "青い森鉄道 三沢駅",
        "station_walk_minutes": 20,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 20,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "三沢市",
        "rating_avg": 3.5,
        "review_count": 6,
    },
    {
        "name": "三沢セレモニーホール",
        "slug": "aomori-misawa-ceremony-hall",
        "venue_type": "private_hall",
        "description": "三沢市の民営葬儀ホール。家族葬から一般葬まで対応し、地域に密着したきめ細かなサービスを提供。三沢駅からのアクセスも良好です。",
        "address": "青森県三沢市中央町2-8-15",
        "prefecture_slug": "aomori",
        "city_slug": "misawa",
        "latitude": 40.6830,
        "longitude": 141.3750,
        "nearest_station": "青い森鉄道 三沢駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "駐車場完備"],
        "operator_name": "三沢セレモニーホール",
        "rating_avg": 3.9,
        "review_count": 7,
    },

    # 五所川原市 (goshogawara) — 2件
    {
        "name": "五所川原市斎場",
        "slug": "aomori-goshogawara-saijo",
        "venue_type": "public_crematorium",
        "description": "五所川原市が運営する公営の火葬場。立佞武多で知られる五所川原市民の火葬を担い、低料金で利用可能。津軽平野の静かな環境で故人を見送れます。",
        "address": "青森県五所川原市大字松島字大溜7-41",
        "prefecture_slug": "aomori",
        "city_slug": "goshogawara",
        "latitude": 40.8050,
        "longitude": 140.4400,
        "nearest_station": "JR五能線 五所川原駅",
        "station_walk_minutes": 20,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 20,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "五所川原市",
        "rating_avg": 3.6,
        "review_count": 6,
    },
    {
        "name": "五所川原セレモニーホール",
        "slug": "aomori-goshogawara-ceremony-hall",
        "venue_type": "private_hall",
        "description": "五所川原市の民営葬儀ホール。立佞武多の街で、家族葬から一般葬まで対応。津軽地方の葬儀文化に精通したスタッフが丁寧にサポートします。",
        "address": "青森県五所川原市字栄町55-3",
        "prefecture_slug": "aomori",
        "city_slug": "goshogawara",
        "latitude": 40.8080,
        "longitude": 140.4450,
        "nearest_station": "JR五能線 五所川原駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "駐車場完備"],
        "operator_name": "五所川原セレモニーホール",
        "rating_avg": 3.9,
        "review_count": 7,
    },

    # 黒石市 (kuroishi) — 2件
    {
        "name": "黒石市斎場",
        "slug": "aomori-kuroishi-saijo",
        "venue_type": "public_crematorium",
        "description": "黒石市が運営する公営の火葬場。こみせ通りで知られる城下町・黒石の市民の火葬を担い、低料金で利用可能。りんご畑に囲まれた環境です。",
        "address": "青森県黒石市大字浅瀬石字龍ノ口63",
        "prefecture_slug": "aomori",
        "city_slug": "kuroishi",
        "latitude": 40.6450,
        "longitude": 140.5950,
        "nearest_station": "弘南鉄道弘南線 黒石駅",
        "station_walk_minutes": 20,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 20,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 72000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 268000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "黒石市",
        "rating_avg": 3.5,
        "review_count": 5,
    },
    {
        "name": "黒石家族葬ホール",
        "slug": "aomori-kuroishi-kazokuso-hall",
        "venue_type": "private_hall",
        "description": "黒石市の家族葬専用ホール。城下町の落ち着いた環境で、少人数のアットホームな葬儀に特化。地域に密着したサービスを提供します。",
        "address": "青森県黒石市甲徳兵衛町3-12",
        "prefecture_slug": "aomori",
        "city_slug": "kuroishi",
        "latitude": 40.6480,
        "longitude": 140.5900,
        "nearest_station": "弘南鉄道弘南線 黒石駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専用", "少人数葬対応", "駅近", "駐車場完備"],
        "operator_name": "黒石家族葬ホール",
        "rating_avg": 3.9,
        "review_count": 6,
    },

    # つがる市 (tsugaru) — 1件
    {
        "name": "つがる市営斎場",
        "slug": "aomori-tsugaru-saijo",
        "venue_type": "public_crematorium",
        "description": "つがる市が運営する公営の火葬場。亀ヶ岡遺跡で知られるつがる市の市民の火葬を担い、低料金で利用可能。津軽平野の広大な自然の中で故人を見送れます。",
        "address": "青森県つがる市木造宮崎1-2",
        "prefecture_slug": "aomori",
        "city_slug": "tsugaru",
        "latitude": 40.8100,
        "longitude": 140.3800,
        "nearest_station": "JR五能線 木造駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 15,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 70000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 258000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "つがる市",
        "rating_avg": 3.5,
        "review_count": 5,
    },

    # 平川市 (hirakawa) — 2件
    {
        "name": "平川市斎場",
        "slug": "aomori-hirakawa-saijo",
        "venue_type": "public_crematorium",
        "description": "平川市が運営する公営の火葬場。猿賀神社で知られる平川市民の火葬を担い、低料金で利用可能。津軽富士・岩木山を望む静かな環境です。",
        "address": "青森県平川市尾上字丸山下127",
        "prefecture_slug": "aomori",
        "city_slug": "hirakawa",
        "latitude": 40.5700,
        "longitude": 140.5500,
        "nearest_station": "弘南鉄道弘南線 尾上高校前駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 20,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 72000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 268000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "平川市",
        "rating_avg": 3.5,
        "review_count": 5,
    },
    {
        "name": "平川家族葬ホール",
        "slug": "aomori-hirakawa-kazokuso-hall",
        "venue_type": "private_hall",
        "description": "平川市の家族葬専用ホール。りんごと温泉の街で、少人数のアットホームな葬儀に特化。地域に密着したサービスで、故人と家族の大切な時間を守ります。",
        "address": "青森県平川市本町北柳田12-5",
        "prefecture_slug": "aomori",
        "city_slug": "hirakawa",
        "latitude": 40.5750,
        "longitude": 140.5550,
        "nearest_station": "弘南鉄道弘南線 平賀駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専用", "少人数葬対応", "駅近", "駐車場完備"],
        "operator_name": "平川家族葬ホール",
        "rating_avg": 3.9,
        "review_count": 6,
    },
]

# 件数を確認
print(f"青森県の斎場データ: 合計 {len(venues)} 件")

# 10件ずつバッチで投入
batch_size = 10
for i in range(0, len(venues), batch_size):
    batch = venues[i:i+batch_size]
    code = insert_batch(batch)
    print(f"  バッチ {i//batch_size + 1} ({len(batch)}件): HTTP {code}")
    if code != "201":
        data_json = json.dumps(batch, ensure_ascii=False)
        result = subprocess.run([
            "curl", "-s",
            "-X", "POST", SUPABASE_URL,
            "-H", f"apikey: {API_KEY}",
            "-H", f"Authorization: Bearer {API_KEY}",
            "-H", "Content-Type: application/json",
            "-H", "Prefer: return=minimal",
            "-H", "User-Agent: Mozilla/5.0",
            "-d", data_json
        ], capture_output=True, text=True)
        print(f"    エラー詳細: {result.stdout[:500]}")
    time.sleep(1)

print("青森県の投入完了!")
