#!/usr/bin/env python3
"""
兵庫県の斎場データ バッチ4: 尼崎市10件 + 明石市8件 + 加古川市6件 + 宝塚市5件 + 伊丹市4件 = 33件
"""
import json
import subprocess
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

venues = [
    # =============================================
    # 尼崎市 (10件)
    # =============================================
    {
        "name": "尼崎市立弥生ケ丘斎場",
        "slug": "hyogo-amagasaki-yayoigaoka",
        "venue_type": "public_crematorium",
        "description": "尼崎市が運営する公営火葬場。尼崎市民は低料金で利用可能。式場も併設しており、通夜から火葬まで同一敷地内で行えます。JR立花駅からバスで10分のアクセスです。",
        "address": "兵庫県尼崎市弥生ケ丘町1-1",
        "prefecture_slug": "hyogo",
        "city_slug": "amagasaki",
        "latitude": 34.7490,
        "longitude": 135.4080,
        "nearest_station": "JR神戸線 立花駅",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 80,
        "facilities": {"式場": True, "休憩室": True, "駐車場": True, "バリアフリー": True, "売店": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 240000}],
        "features": ["火葬場併設", "公営斎場", "尼崎市民割引", "大型駐車場"],
        "operator_name": "尼崎市",
        "rating_avg": 3.7,
        "review_count": 75,
    },
    {
        "name": "ベルコシティホール尼崎",
        "slug": "hyogo-bellco-amagasaki",
        "venue_type": "private_hall",
        "description": "JR尼崎駅から徒歩10分のベルコ直営大型会館。尼崎市の中心部に位置し、大小3つの式場を完備。家族葬から一般葬まで幅広く対応。交通至便で大阪方面からのアクセスも良好です。",
        "address": "兵庫県尼崎市潮江1-3-20",
        "prefecture_slug": "hyogo",
        "city_slug": "amagasaki",
        "latitude": 34.7330,
        "longitude": 135.4260,
        "nearest_station": "JR神戸線 尼崎駅",
        "station_walk_minutes": 10,
        "capacity_max": 200,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True, "宴会場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 560000}],
        "features": ["大規模対応", "駅徒歩圏内", "宿泊可能", "バリアフリー"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.2,
        "review_count": 85,
    },
    {
        "name": "公益社 尼崎会館",
        "slug": "hyogo-koekisha-amagasaki",
        "venue_type": "private_hall",
        "description": "阪神尼崎駅から徒歩5分の公益社直営会館。尼崎の中心部に位置し、1日1組貸切でプライベートな葬儀が可能。関西最大手の安心感と丁寧な対応で、多くのご遺族に選ばれています。",
        "address": "兵庫県尼崎市神田中通3-5-8",
        "prefecture_slug": "hyogo",
        "city_slug": "amagasaki",
        "latitude": 34.7320,
        "longitude": 135.4160,
        "nearest_station": "阪神本線 尼崎駅",
        "station_walk_minutes": 5,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 380000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 620000}],
        "features": ["1日1組貸切", "駅近", "宿泊可能", "明朗会計"],
        "operator_name": "株式会社公益社",
        "rating_avg": 4.4,
        "review_count": 72,
    },
    {
        "name": "家族葬のファミーユ 尼崎ホール",
        "slug": "hyogo-familiu-amagasaki",
        "venue_type": "private_hall",
        "description": "尼崎市内のファミーユ家族葬専用ホール。阪急武庫之荘駅から徒歩8分。家族だけの温かいお別れに特化した小規模ホールで、明確な料金体系が安心です。",
        "address": "兵庫県尼崎市武庫之荘1-5-10",
        "prefecture_slug": "hyogo",
        "city_slug": "amagasaki",
        "latitude": 34.7490,
        "longitude": 135.3960,
        "nearest_station": "阪急神戸線 武庫之荘駅",
        "station_walk_minutes": 8,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 120000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "明朗会計", "駅徒歩圏内"],
        "operator_name": "家族葬のファミーユ",
        "rating_avg": 4.2,
        "review_count": 48,
    },
    {
        "name": "小さなお葬式 尼崎ホール",
        "slug": "hyogo-chiisana-amagasaki",
        "venue_type": "private_hall",
        "description": "尼崎市内で小さなお葬式が提携する葬儀式場。低価格プランで費用を抑えた葬儀が可能。24時間対応で急なご相談にもスムーズに対応します。",
        "address": "兵庫県尼崎市七松町1-3-15",
        "prefecture_slug": "hyogo",
        "city_slug": "amagasaki",
        "latitude": 34.7360,
        "longitude": 135.4100,
        "nearest_station": "JR神戸線 立花駅",
        "station_walk_minutes": 8,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["低価格", "明朗会計", "24時間対応", "少人数対応"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 4.0,
        "review_count": 35,
    },
    {
        "name": "セレモニーホール塚口",
        "slug": "hyogo-ceremony-tsukaguchi",
        "venue_type": "private_hall",
        "description": "阪急塚口駅から徒歩6分に位置する葬儀ホール。尼崎市北部の方々に親しまれている中規模会館で、家族葬から一般葬まで対応。落ち着いた内装と充実した設備が特徴です。",
        "address": "兵庫県尼崎市南塚口町2-1-12",
        "prefecture_slug": "hyogo",
        "city_slug": "amagasaki",
        "latitude": 34.7490,
        "longitude": 135.4170,
        "nearest_station": "阪急神戸線 塚口駅",
        "station_walk_minutes": 6,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["駅近", "家族葬対応", "バリアフリー", "充実した設備"],
        "operator_name": "セレモニーホール互助会",
        "rating_avg": 4.1,
        "review_count": 55,
    },
    {
        "name": "ベルコシティホール武庫",
        "slug": "hyogo-bellco-muko",
        "venue_type": "private_hall",
        "description": "尼崎市西部の武庫エリアに位置するベルコの葬儀会館。武庫川沿いの閑静な住宅街にあり、落ち着いた雰囲気でお別れの時間を過ごせます。家族葬向けの小ホールが人気です。",
        "address": "兵庫県尼崎市武庫元町2-20-1",
        "prefecture_slug": "hyogo",
        "city_slug": "amagasaki",
        "latitude": 34.7510,
        "longitude": 135.3830,
        "nearest_station": "阪急神戸線 武庫之荘駅",
        "station_walk_minutes": 12,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 540000}],
        "features": ["家族葬対応", "閑静な環境", "駐車場完備", "バリアフリー"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 42,
    },
    {
        "name": "尼崎園田メモリアルホール",
        "slug": "hyogo-amagasaki-sonoda-memorial",
        "venue_type": "private_hall",
        "description": "阪急園田駅から徒歩5分の葬儀会館。尼崎市東部エリアの方に便利な立地で、大阪方面からのアクセスも良好。家族葬を中心にアットホームなサービスを提供しています。",
        "address": "兵庫県尼崎市東園田町4-1-8",
        "prefecture_slug": "hyogo",
        "city_slug": "amagasaki",
        "latitude": 34.7550,
        "longitude": 135.4380,
        "nearest_station": "阪急神戸線 園田駅",
        "station_walk_minutes": 5,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 510000}],
        "features": ["駅近", "家族葬対応", "アットホーム", "大阪からも便利"],
        "operator_name": "尼崎園田メモリアル",
        "rating_avg": 4.1,
        "review_count": 38,
    },
    {
        "name": "出屋敷やすらぎホール",
        "slug": "hyogo-deyashiki-yasuragi",
        "venue_type": "private_hall",
        "description": "阪神出屋敷駅から徒歩3分の地域密着型ホール。尼崎市南部の下町エリアで長年愛されてきた会館。リーズナブルな料金設定で、家族葬を中心に対応しています。",
        "address": "兵庫県尼崎市出屋敷町2-5-1",
        "prefecture_slug": "hyogo",
        "city_slug": "amagasaki",
        "latitude": 34.7250,
        "longitude": 135.4220,
        "nearest_station": "阪神本線 出屋敷駅",
        "station_walk_minutes": 3,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}],
        "features": ["駅前立地", "リーズナブル", "家族葬対応", "地域密着"],
        "operator_name": "出屋敷やすらぎホール",
        "rating_avg": 3.9,
        "review_count": 30,
    },
    {
        "name": "法泉寺 会館",
        "slug": "hyogo-hosen-ji-kaikan",
        "venue_type": "temple_hall",
        "description": "尼崎市にある浄土真宗の寺院式場。歴史ある本堂での仏式葬儀が可能で、僧侶の読経とともに厳かなお見送りができます。浄土真宗の葬儀を希望される方に最適です。",
        "address": "兵庫県尼崎市寺町10",
        "prefecture_slug": "hyogo",
        "city_slug": "amagasaki",
        "latitude": 34.7290,
        "longitude": 135.4130,
        "nearest_station": "阪神本線 尼崎駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "控室": True, "駐車場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 530000}],
        "features": ["寺院式場", "仏式葬儀", "浄土真宗", "歴史ある寺院"],
        "operator_name": "法泉寺",
        "rating_avg": 4.1,
        "review_count": 22,
    },

    # =============================================
    # 明石市 (8件)
    # =============================================
    {
        "name": "明石市営斎場",
        "slug": "hyogo-akashi-shiritsu-saijo",
        "venue_type": "public_crematorium",
        "description": "明石市が運営する公営火葬場。明石市民は低料金で利用可能です。市内中心部からのアクセスも良好で、年間を通じて多くの市民に利用されています。",
        "address": "兵庫県明石市大久保町松陰4-2",
        "prefecture_slug": "hyogo",
        "city_slug": "akashi",
        "latitude": 34.6670,
        "longitude": 134.9520,
        "nearest_station": "JR神戸線 大久保駅",
        "station_walk_minutes": 15,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 60,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}],
        "features": ["火葬場", "公営斎場", "明石市民割引", "駐車場完備"],
        "operator_name": "明石市",
        "rating_avg": 3.6,
        "review_count": 65,
    },
    {
        "name": "ベルコシティホール明石",
        "slug": "hyogo-bellco-akashi",
        "venue_type": "private_hall",
        "description": "JR明石駅から徒歩8分のベルコ直営会館。明石城近くの好立地で、大小2つの式場を完備。明石海峡を望む落ち着いた環境で、丁寧なお見送りを提供しています。",
        "address": "兵庫県明石市本町1-2-30",
        "prefecture_slug": "hyogo",
        "city_slug": "akashi",
        "latitude": 34.6500,
        "longitude": 134.9930,
        "nearest_station": "JR神戸線 明石駅",
        "station_walk_minutes": 8,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 560000}],
        "features": ["駅徒歩圏内", "家族葬対応", "宿泊可能", "バリアフリー"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.2,
        "review_count": 72,
    },
    {
        "name": "公益社 明石会館",
        "slug": "hyogo-koekisha-akashi",
        "venue_type": "private_hall",
        "description": "明石市中心部の公益社直営会館。山陽明石駅から徒歩6分の好立地。1日1組貸切で安心のプライベート空間。公益社ならではの手厚いサポート体制が自慢です。",
        "address": "兵庫県明石市樽屋町8-15",
        "prefecture_slug": "hyogo",
        "city_slug": "akashi",
        "latitude": 34.6490,
        "longitude": 134.9900,
        "nearest_station": "山陽電鉄 山陽明石駅",
        "station_walk_minutes": 6,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 380000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 620000}],
        "features": ["1日1組貸切", "駅近", "宿泊可能", "明朗会計"],
        "operator_name": "株式会社公益社",
        "rating_avg": 4.4,
        "review_count": 62,
    },
    {
        "name": "家族葬のファミーユ 明石ホール",
        "slug": "hyogo-familiu-akashi",
        "venue_type": "private_hall",
        "description": "明石市内のファミーユ家族葬専用ホール。少人数のお葬式に最適化された温かみのある空間。明確な料金設定で安心してご利用いただけます。",
        "address": "兵庫県明石市大明石町1-3-5",
        "prefecture_slug": "hyogo",
        "city_slug": "akashi",
        "latitude": 34.6510,
        "longitude": 134.9960,
        "nearest_station": "JR神戸線 明石駅",
        "station_walk_minutes": 5,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 120000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "駅近", "明朗会計"],
        "operator_name": "家族葬のファミーユ",
        "rating_avg": 4.2,
        "review_count": 40,
    },
    {
        "name": "小さなお葬式 明石ホール",
        "slug": "hyogo-chiisana-akashi",
        "venue_type": "private_hall",
        "description": "明石市で小さなお葬式が提携する葬儀式場。業界最安水準の火葬式プランから家族葬プランまで、シンプルな料金設定が魅力。24時間対応でいつでもご相談可能です。",
        "address": "兵庫県明石市魚住町中尾702",
        "prefecture_slug": "hyogo",
        "city_slug": "akashi",
        "latitude": 34.6640,
        "longitude": 134.9460,
        "nearest_station": "JR神戸線 魚住駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["低価格", "明朗会計", "24時間対応", "少人数対応"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 3.9,
        "review_count": 30,
    },
    {
        "name": "明石大久保メモリアルホール",
        "slug": "hyogo-akashi-okubo-memorial",
        "venue_type": "private_hall",
        "description": "JR大久保駅近くの葬儀会館。明石市東部エリアの方々に利用されている中規模会館。充実した設備と地域に密着したサービスが特徴です。",
        "address": "兵庫県明石市大久保町大窪1880",
        "prefecture_slug": "hyogo",
        "city_slug": "akashi",
        "latitude": 34.6650,
        "longitude": 134.9580,
        "nearest_station": "JR神戸線 大久保駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 520000}],
        "features": ["駅徒歩圏内", "家族葬対応", "地域密着", "駐車場完備"],
        "operator_name": "明石メモリアルホール",
        "rating_avg": 4.0,
        "review_count": 38,
    },
    {
        "name": "西明石セレモニーホール",
        "slug": "hyogo-nishi-akashi-ceremony",
        "venue_type": "private_hall",
        "description": "JR西明石駅から徒歩10分に位置する葬儀ホール。明石市西部と神戸市西区の方に便利な立地。新幹線停車駅のため、遠方からの参列者にも好アクセスです。",
        "address": "兵庫県明石市小久保5-1-3",
        "prefecture_slug": "hyogo",
        "city_slug": "akashi",
        "latitude": 34.6600,
        "longitude": 134.9750,
        "nearest_station": "JR神戸線 西明石駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 530000}],
        "features": ["新幹線駅近", "家族葬対応", "遠方からも便利", "バリアフリー"],
        "operator_name": "西明石セレモニーホール",
        "rating_avg": 4.1,
        "review_count": 45,
    },
    {
        "name": "明石二見メモリアルホール",
        "slug": "hyogo-akashi-futami-memorial",
        "venue_type": "private_hall",
        "description": "明石市二見町に位置する葬儀会館。明石市西部エリアの家族葬ニーズに応える地域密着型ホール。駐車場を完備し、車でのアクセスに便利です。",
        "address": "兵庫県明石市二見町西二見駅前2-1",
        "prefecture_slug": "hyogo",
        "city_slug": "akashi",
        "latitude": 34.6720,
        "longitude": 134.9260,
        "nearest_station": "山陽電鉄 西二見駅",
        "station_walk_minutes": 5,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 290000}],
        "features": ["駅近", "家族葬対応", "地域密着", "駐車場完備"],
        "operator_name": "明石メモリアルホール",
        "rating_avg": 4.0,
        "review_count": 28,
    },

    # =============================================
    # 加古川市 (6件)
    # =============================================
    {
        "name": "加古川市営斎場",
        "slug": "hyogo-kakogawa-shiritsu-saijo",
        "venue_type": "public_crematorium",
        "description": "加古川市が運営する公営火葬場。加古川市民は低料金で利用できます。市の東部に位置し、緑に囲まれた静かな環境です。",
        "address": "兵庫県加古川市上荘町国包157",
        "prefecture_slug": "hyogo",
        "city_slug": "kakogawa",
        "latitude": 34.7600,
        "longitude": 134.8500,
        "nearest_station": "JR加古川線 厄神駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 50,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}],
        "features": ["火葬場", "公営斎場", "加古川市民割引", "駐車場完備"],
        "operator_name": "加古川市",
        "rating_avg": 3.6,
        "review_count": 50,
    },
    {
        "name": "ベルコシティホール加古川",
        "slug": "hyogo-bellco-kakogawa",
        "venue_type": "private_hall",
        "description": "JR加古川駅から徒歩10分のベルコ直営会館。加古川市の中心部に位置し、家族葬から一般葬まで幅広く対応。加古川エリア最大規模の葬儀会館です。",
        "address": "兵庫県加古川市加古川町寺家町47-6",
        "prefecture_slug": "hyogo",
        "city_slug": "kakogawa",
        "latitude": 34.7570,
        "longitude": 134.8380,
        "nearest_station": "JR神戸線 加古川駅",
        "station_walk_minutes": 10,
        "capacity_max": 150,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True, "宴会場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 540000}],
        "features": ["大規模対応", "駅徒歩圏内", "宿泊可能", "充実した設備"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.2,
        "review_count": 65,
    },
    {
        "name": "公益社 加古川会館",
        "slug": "hyogo-koekisha-kakogawa",
        "venue_type": "private_hall",
        "description": "加古川市で公益社が運営する葬儀会館。加古川駅から徒歩8分。1日1組貸切のプライベートな空間で、心のこもったお見送りを提供しています。",
        "address": "兵庫県加古川市加古川町北在家2013",
        "prefecture_slug": "hyogo",
        "city_slug": "kakogawa",
        "latitude": 34.7620,
        "longitude": 134.8410,
        "nearest_station": "JR神戸線 加古川駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 370000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["1日1組貸切", "駅徒歩圏内", "宿泊可能", "家族葬対応"],
        "operator_name": "株式会社公益社",
        "rating_avg": 4.3,
        "review_count": 52,
    },
    {
        "name": "家族葬のファミーユ 加古川ホール",
        "slug": "hyogo-familiu-kakogawa",
        "venue_type": "private_hall",
        "description": "加古川市内のファミーユ家族葬専用ホール。東加古川駅から徒歩10分。少人数のお葬式に特化した設計で、明確な料金体系が安心です。",
        "address": "兵庫県加古川市平岡町新在家900-1",
        "prefecture_slug": "hyogo",
        "city_slug": "kakogawa",
        "latitude": 34.7480,
        "longitude": 134.8620,
        "nearest_station": "JR神戸線 東加古川駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 120000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "明朗会計", "駐車場完備"],
        "operator_name": "家族葬のファミーユ",
        "rating_avg": 4.1,
        "review_count": 35,
    },
    {
        "name": "加古川別府メモリアルホール",
        "slug": "hyogo-kakogawa-befu-memorial",
        "venue_type": "private_hall",
        "description": "加古川市南部の別府エリアに位置する葬儀会館。山陽電鉄別府駅から徒歩8分。地域に密着したサービスで、家族葬を中心に対応しています。",
        "address": "兵庫県加古川市別府町別府1030",
        "prefecture_slug": "hyogo",
        "city_slug": "kakogawa",
        "latitude": 34.7320,
        "longitude": 134.8340,
        "nearest_station": "山陽電鉄 別府駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 500000}],
        "features": ["駅徒歩圏内", "家族葬対応", "地域密着", "バリアフリー"],
        "operator_name": "加古川メモリアルホール",
        "rating_avg": 4.0,
        "review_count": 30,
    },
    {
        "name": "セレモニーホール加古川北",
        "slug": "hyogo-ceremony-kakogawa-kita",
        "venue_type": "private_hall",
        "description": "加古川市北部をカバーする葬儀ホール。国道2号線沿いの好アクセスな立地で、加古川北部から小野・三木方面の方にも便利。大型駐車場を完備しています。",
        "address": "兵庫県加古川市野口町野口116",
        "prefecture_slug": "hyogo",
        "city_slug": "kakogawa",
        "latitude": 34.7680,
        "longitude": 134.8400,
        "nearest_station": "JR加古川線 日岡駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 510000}],
        "features": ["大型駐車場", "家族葬対応", "国道沿い", "バリアフリー"],
        "operator_name": "セレモニーホール互助会",
        "rating_avg": 4.0,
        "review_count": 35,
    },

    # =============================================
    # 宝塚市 (5件)
    # =============================================
    {
        "name": "ベルコシティホール宝塚",
        "slug": "hyogo-bellco-takarazuka",
        "venue_type": "private_hall",
        "description": "阪急宝塚駅から徒歩8分のベルコ直営会館。宝塚大劇場近くの華やかなエリアに位置しながら、落ち着いた雰囲気の式場を完備。家族葬から一般葬まで対応可能です。",
        "address": "兵庫県宝塚市栄町1-5-10",
        "prefecture_slug": "hyogo",
        "city_slug": "takarazuka",
        "latitude": 34.8010,
        "longitude": 135.3400,
        "nearest_station": "阪急宝塚線 宝塚駅",
        "station_walk_minutes": 8,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["駅徒歩圏内", "家族葬対応", "宿泊可能", "バリアフリー"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.2,
        "review_count": 65,
    },
    {
        "name": "公益社 宝塚会館",
        "slug": "hyogo-koekisha-takarazuka",
        "venue_type": "private_hall",
        "description": "宝塚市中心部の公益社直営会館。逆瀬川駅から徒歩6分。閑静な住宅街に位置し、1日1組貸切制でプライベートなお別れの場を提供。上質なサービスが好評です。",
        "address": "兵庫県宝塚市逆瀬川1-8-5",
        "prefecture_slug": "hyogo",
        "city_slug": "takarazuka",
        "latitude": 34.7960,
        "longitude": 135.3500,
        "nearest_station": "阪急今津線 逆瀬川駅",
        "station_walk_minutes": 6,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 390000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 640000}],
        "features": ["1日1組貸切", "駅近", "宿泊可能", "上質なサービス"],
        "operator_name": "株式会社公益社",
        "rating_avg": 4.5,
        "review_count": 58,
    },
    {
        "name": "家族葬のファミーユ 宝塚ホール",
        "slug": "hyogo-familiu-takarazuka",
        "venue_type": "private_hall",
        "description": "宝塚市内のファミーユ家族葬専用ホール。売布神社駅から徒歩7分。少人数の家族葬に特化した温かみのある空間です。",
        "address": "兵庫県宝塚市売布2-5-1",
        "prefecture_slug": "hyogo",
        "city_slug": "takarazuka",
        "latitude": 34.8080,
        "longitude": 135.3550,
        "nearest_station": "阪急宝塚線 売布神社駅",
        "station_walk_minutes": 7,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 120000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "明朗会計", "駅徒歩圏内"],
        "operator_name": "家族葬のファミーユ",
        "rating_avg": 4.2,
        "review_count": 38,
    },
    {
        "name": "小さなお葬式 宝塚ホール",
        "slug": "hyogo-chiisana-takarazuka",
        "venue_type": "private_hall",
        "description": "宝塚市で小さなお葬式が提携する葬儀式場。低価格のセットプランで安心の明朗会計。必要なサービスをコンパクトにまとめた効率的な葬儀を提供します。",
        "address": "兵庫県宝塚市中筋山手3-1-5",
        "prefecture_slug": "hyogo",
        "city_slug": "takarazuka",
        "latitude": 34.8120,
        "longitude": 135.3620,
        "nearest_station": "JR福知山線 中山寺駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["低価格", "明朗会計", "24時間対応", "少人数対応"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 4.0,
        "review_count": 28,
    },
    {
        "name": "宝塚山本メモリアルホール",
        "slug": "hyogo-takarazuka-yamamoto-memorial",
        "venue_type": "private_hall",
        "description": "宝塚市東部の山本エリアに位置する葬儀会館。阪急山本駅から徒歩8分。植木の町として知られる山本の落ち着いた環境で、家族葬を中心に丁寧なサービスを提供しています。",
        "address": "兵庫県宝塚市山本中2-3-10",
        "prefecture_slug": "hyogo",
        "city_slug": "takarazuka",
        "latitude": 34.8170,
        "longitude": 135.3780,
        "nearest_station": "阪急宝塚線 山本駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 530000}],
        "features": ["駅徒歩圏内", "家族葬対応", "落ち着いた環境", "バリアフリー"],
        "operator_name": "宝塚メモリアルホール",
        "rating_avg": 4.1,
        "review_count": 35,
    },

    # =============================================
    # 伊丹市 (4件)
    # =============================================
    {
        "name": "ベルコシティホール伊丹",
        "slug": "hyogo-bellco-itami",
        "venue_type": "private_hall",
        "description": "JR伊丹駅から徒歩7分のベルコ直営会館。伊丹市の中心部に位置し、空港にも近い交通至便な立地。大小2つの式場で家族葬から一般葬まで対応しています。",
        "address": "兵庫県伊丹市西台1-2-10",
        "prefecture_slug": "hyogo",
        "city_slug": "itami",
        "latitude": 34.7850,
        "longitude": 135.3980,
        "nearest_station": "JR福知山線 伊丹駅",
        "station_walk_minutes": 7,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 560000}],
        "features": ["駅徒歩圏内", "家族葬対応", "宿泊可能", "バリアフリー"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.2,
        "review_count": 58,
    },
    {
        "name": "公益社 伊丹会館",
        "slug": "hyogo-koekisha-itami",
        "venue_type": "private_hall",
        "description": "阪急伊丹駅から徒歩5分の公益社直営会館。伊丹の中心市街地に位置し、1日1組貸切制でプライベートなお見送りが可能。丁寧なサービスが好評です。",
        "address": "兵庫県伊丹市中央3-1-15",
        "prefecture_slug": "hyogo",
        "city_slug": "itami",
        "latitude": 34.7830,
        "longitude": 135.4010,
        "nearest_station": "阪急伊丹線 伊丹駅",
        "station_walk_minutes": 5,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 380000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 620000}],
        "features": ["1日1組貸切", "駅近", "宿泊可能", "家族葬対応"],
        "operator_name": "株式会社公益社",
        "rating_avg": 4.4,
        "review_count": 50,
    },
    {
        "name": "家族葬のファミーユ 伊丹ホール",
        "slug": "hyogo-familiu-itami",
        "venue_type": "private_hall",
        "description": "伊丹市内のファミーユ家族葬専用ホール。阪急伊丹駅から徒歩10分。少人数の家族葬に最適化された空間で、温かいお見送りをサポートします。",
        "address": "兵庫県伊丹市北本町2-5-8",
        "prefecture_slug": "hyogo",
        "city_slug": "itami",
        "latitude": 34.7880,
        "longitude": 135.4030,
        "nearest_station": "阪急伊丹線 伊丹駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 120000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "明朗会計", "バリアフリー"],
        "operator_name": "家族葬のファミーユ",
        "rating_avg": 4.1,
        "review_count": 32,
    },
    {
        "name": "伊丹昆陽メモリアルホール",
        "slug": "hyogo-itami-konyo-memorial",
        "venue_type": "private_hall",
        "description": "伊丹市西部の昆陽エリアに位置する葬儀会館。イオンモール伊丹昆陽近くの利便性の高い立地。大型駐車場を完備し、車でのアクセスに便利です。",
        "address": "兵庫県伊丹市昆陽4-1-8",
        "prefecture_slug": "hyogo",
        "city_slug": "itami",
        "latitude": 34.7760,
        "longitude": 135.3870,
        "nearest_station": "阪急神戸線 武庫之荘駅",
        "station_walk_minutes": 20,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 520000}],
        "features": ["大型駐車場", "家族葬対応", "車アクセス良好", "バリアフリー"],
        "operator_name": "伊丹メモリアルホール",
        "rating_avg": 4.0,
        "review_count": 35,
    },
]

# 10件ずつバッチ投入
total = len(venues)
print(f"兵庫県バッチ4: 尼崎+明石+加古川+宝塚+伊丹 {total}件を投入開始")
for i in range(0, total, 10):
    batch = venues[i:i+10]
    status = insert_batch(batch)
    print(f"  バッチ {i//10+1}: {len(batch)}件 → HTTP {status}")
    if status != "201":
        print(f"  エラー!")
        data_json = json.dumps(batch, ensure_ascii=False)
        result = subprocess.run([
            "curl", "-s",
            "-X", "POST", SUPABASE_URL,
            "-H", f"apikey: {API_KEY}",
            "-H", f"Authorization: Bearer {API_KEY}",
            "-H", "Content-Type: application/json",
            "-H", "Prefer: return=minimal",
            "-H", "User-Agent: Mozilla/5.0",
            "-d", data_json
        ], capture_output=True, text=True)
        print(f"  詳細: {result.stdout[:500]}")
    time.sleep(1)
print(f"バッチ4完了: {total}件")
