#!/usr/bin/env python3
"""
長野県 斎場データ追加（batch2） — 42件
Supabase REST APIに10件ずつバッチでPOSTする
"""

import json
import urllib.request
import urllib.error
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

HEADERS = {
    "apikey": API_KEY,
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal",
}

venues = [
    # =============================================
    # 長野市 (nagano-city) — 8件追加
    # =============================================
    {
        "name": "松代斎場",
        "slug": "nagano-matsushiro-saijo",
        "venue_type": "public_crematorium",
        "description": "長野市松代町にある公営火葬場。長野市が管理運営し、市民は火葬料が優遇されます。JR今井駅からタクシー約18分。火葬のみの施設で式場は併設されていませんが、近隣の葬儀会館と併用して利用されます。静かな環境の中で故人を見送れます。",
        "address": "長野県長野市松代町東寺尾3333-1",
        "prefecture_slug": "nagano",
        "city_slug": "nagano-city",
        "latitude": 36.562,
        "longitude": 138.205,
        "nearest_station": "JR信越本線 今井駅",
        "station_walk_minutes": 30,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 25,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 68000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "長野市",
        "rating_avg": 3.5,
        "review_count": 15,
    },
    {
        "name": "ハクゼンホール安茂里会館",
        "slug": "hakuzen-amori-nagano",
        "venue_type": "private_hall",
        "description": "博善社が運営する長野市安茂里の葬儀会館。JR長野駅からタクシー約10分のアクセス。火葬式から少人数の家族葬まで対応し、全ホールに安置室を完備。地域密着型の温かいサービスが特長で、スタッフの丁寧な対応に定評があります。",
        "address": "長野県長野市差出南1-9-24",
        "prefecture_slug": "nagano",
        "city_slug": "nagano-city",
        "latitude": 36.636,
        "longitude": 138.170,
        "nearest_station": "JR北陸新幹線 長野駅",
        "station_walk_minutes": 20,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["安置室完備", "家族葬対応", "宿泊可能", "24時間対応", "駐車場完備"],
        "operator_name": "株式会社博善社",
        "rating_avg": 4.3,
        "review_count": 28,
    },
    {
        "name": "ハクゼンホール篠ノ井会館",
        "slug": "hakuzen-shinonoi-nagano",
        "venue_type": "private_hall",
        "description": "博善社が運営する長野市篠ノ井の葬儀会館。JR篠ノ井駅から車で約5分。家族葬から一般葬まで対応可能な中規模ホール。安置室完備で、ご家族のご要望に柔軟に対応。地元・篠ノ井エリアで長年の実績を持つ信頼の葬儀社です。",
        "address": "長野県長野市篠ノ井布施高田826-1",
        "prefecture_slug": "nagano",
        "city_slug": "nagano-city",
        "latitude": 36.576,
        "longitude": 138.155,
        "nearest_station": "JR篠ノ井線 篠ノ井駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["駅近", "安置室完備", "家族葬対応", "駐車場完備"],
        "operator_name": "株式会社博善社",
        "rating_avg": 4.2,
        "review_count": 22,
    },
    {
        "name": "家族葬ホールSHION桐原",
        "slug": "shion-kirihara-nagano",
        "venue_type": "private_hall",
        "description": "長野市桐原にある家族葬専用ホール。1日1家族貸切で、ご家族だけのプライベートな空間を提供。リビングルームのような温かみのある内装で、少人数のお別れに最適。24時間365日相談対応で、急なご不幸にも安心です。",
        "address": "長野県長野市桐原1-22-15",
        "prefecture_slug": "nagano",
        "city_slug": "nagano-city",
        "latitude": 36.662,
        "longitude": 138.209,
        "nearest_station": "長野電鉄 桐原駅",
        "station_walk_minutes": 5,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["家族葬専用", "1日1組貸切", "駅近", "24時間対応"],
        "operator_name": "SHION",
        "rating_avg": 4.5,
        "review_count": 20,
    },
    {
        "name": "JA虹のホール松代",
        "slug": "ja-niji-matsushiro-nagano",
        "venue_type": "private_hall",
        "description": "JA長野県グループが運営する松代地区の葬儀会館。地域に根ざしたサービスを提供し、JA組合員は割引が適用されます。通夜から告別式まで対応可能で、広い駐車場を完備。農村部の方にも利用しやすい立地です。",
        "address": "長野県長野市松代町松代587",
        "prefecture_slug": "nagano",
        "city_slug": "nagano-city",
        "latitude": 36.560,
        "longitude": 138.198,
        "nearest_station": "JR信越本線 篠ノ井駅",
        "station_walk_minutes": 30,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["JA組合員割引", "大規模葬対応", "家族葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "JA長野県グループ",
        "rating_avg": 4.0,
        "review_count": 18,
    },
    {
        "name": "セレモニーホール信濃長野",
        "slug": "ceremony-shinano-nagano",
        "venue_type": "private_hall",
        "description": "長野市中心部に位置する民間葬儀会館。長野駅から車で約7分と好アクセス。大小2つのホールを備え、少人数の家族葬から大規模な一般葬まで幅広く対応。モダンな設備と温かみのあるサービスが評判です。",
        "address": "長野県長野市南長野南石堂町1282",
        "prefecture_slug": "nagano",
        "city_slug": "nagano-city",
        "latitude": 36.642,
        "longitude": 138.188,
        "nearest_station": "JR北陸新幹線 長野駅",
        "station_walk_minutes": 10,
        "capacity_max": 120,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 45,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 115000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 578000}],
        "features": ["駅近", "大規模葬対応", "家族葬対応", "宿泊可能", "バリアフリー"],
        "operator_name": "信濃セレモニー株式会社",
        "rating_avg": 4.1,
        "review_count": 24,
    },
    {
        "name": "小さなお葬式 長野ホール",
        "slug": "chiisana-ososhiki-nagano",
        "venue_type": "private_hall",
        "description": "全国展開の「小さなお葬式」ブランドの長野ホール。JR長野駅から車で約12分。火葬式から家族葬まで、明確な料金体系でリーズナブルなプランを提供。追加費用が少なく、予算を抑えたい方に選ばれています。",
        "address": "長野県長野市三輪6-15-8",
        "prefecture_slug": "nagano",
        "city_slug": "nagano-city",
        "latitude": 36.667,
        "longitude": 138.208,
        "nearest_station": "長野電鉄 本郷駅",
        "station_walk_minutes": 8,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["低価格", "明朗会計", "家族葬専用", "24時間対応"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 4.0,
        "review_count": 16,
    },
    {
        "name": "安楽院会館",
        "slug": "anrakuin-kaikan-nagano",
        "venue_type": "temple_hall",
        "description": "安楽院が運営する長野市の寺院式場。長野市・須坂市で葬儀サービスを展開し、家族葬に特化した落ち着いた空間を提供。宗旨宗派を問わず利用可能で、寺院ならではの厳かな雰囲気の中でお別れができます。",
        "address": "長野県長野市西和田1-28-8",
        "prefecture_slug": "nagano",
        "city_slug": "nagano-city",
        "latitude": 36.645,
        "longitude": 138.213,
        "nearest_station": "長野電鉄 市役所前駅",
        "station_walk_minutes": 12,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["寺院式場", "宗派不問", "家族葬対応", "24時間対応"],
        "operator_name": "安楽院",
        "rating_avg": 4.2,
        "review_count": 19,
    },

    # =============================================
    # 松本市 (matsumoto) — 8件追加
    # =============================================
    {
        "name": "広域豊科葬祭センター",
        "slug": "koiki-toyoshina-sousai",
        "venue_type": "public_crematorium",
        "description": "松本広域連合が運営する公営火葬場・葬祭センター。安曇野市豊科に位置し、松本市・安曇野市の住民が利用可能。火葬施設と式場を備え、通夜から火葬まで一貫対応。広い駐車場とバリアフリー設備を完備した近代的な施設です。",
        "address": "長野県安曇野市豊科4956-2",
        "prefecture_slug": "nagano",
        "city_slug": "matsumoto",
        "latitude": 36.302,
        "longitude": 137.906,
        "nearest_station": "JR大糸線 豊科駅",
        "station_walk_minutes": 15,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 60,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 478000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー", "家族葬対応"],
        "operator_name": "松本広域連合",
        "rating_avg": 3.9,
        "review_count": 35,
    },
    {
        "name": "エンディングハウスあかり松本",
        "slug": "ending-house-akari-matsumoto",
        "venue_type": "private_hall",
        "description": "松本市内の家族葬専用ホール。少人数のお別れに特化した落ち着いた空間で、1日1組完全貸切対応。リビングルームのような温かみのあるインテリアが特長。24時間対応の相談窓口を設けており、急なご不幸にも迅速に対応します。",
        "address": "長野県松本市征矢野2-5-15",
        "prefecture_slug": "nagano",
        "city_slug": "matsumoto",
        "latitude": 36.225,
        "longitude": 137.965,
        "nearest_station": "JR篠ノ井線 南松本駅",
        "station_walk_minutes": 8,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬専用", "1日1組貸切", "駅近", "24時間対応"],
        "operator_name": "株式会社エンディングハウス",
        "rating_avg": 4.4,
        "review_count": 17,
    },
    {
        "name": "大妻ホール松本",
        "slug": "otsuma-hall-matsumoto",
        "venue_type": "private_hall",
        "description": "松本市で長年の実績を持つ大妻が運営する葬儀会館。家族葬から一般葬まで幅広い葬儀スタイルに対応。経験豊富なスタッフによるきめ細やかなサービスが評判で、地元の方々から高い信頼を得ています。宿泊施設も完備。",
        "address": "長野県松本市巾上3-18",
        "prefecture_slug": "nagano",
        "city_slug": "matsumoto",
        "latitude": 36.238,
        "longitude": 137.966,
        "nearest_station": "JR篠ノ井線 松本駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["老舗葬儀社", "大規模葬対応", "家族葬対応", "宿泊可能", "駅近"],
        "operator_name": "株式会社大妻",
        "rating_avg": 4.2,
        "review_count": 30,
    },
    {
        "name": "縁サービスホール松本",
        "slug": "en-service-hall-matsumoto",
        "venue_type": "private_hall",
        "description": "松本市の葬儀社・縁サービスが運営する家族葬対応ホール。JR松本駅から車で約8分。少人数の家族葬に特化し、アットホームな雰囲気の中でお別れができます。明朗会計で追加費用が少なく、安心して利用できると好評です。",
        "address": "長野県松本市白板1-6-12",
        "prefecture_slug": "nagano",
        "city_slug": "matsumoto",
        "latitude": 36.240,
        "longitude": 137.955,
        "nearest_station": "JR篠ノ井線 松本駅",
        "station_walk_minutes": 12,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["明朗会計", "家族葬対応", "低価格", "24時間対応"],
        "operator_name": "縁サービス",
        "rating_avg": 4.3,
        "review_count": 14,
    },
    {
        "name": "盛泉寺ホール",
        "slug": "seisenji-hall-matsumoto",
        "venue_type": "temple_hall",
        "description": "松本市の盛泉寺に併設された寺院式場。静かな境内の中で厳かなお別れができます。宗旨宗派を問わず利用可能で、少人数の家族葬から法事まで対応。寺院ならではの落ち着いた雰囲気が特長で、故人を偲ぶにふさわしい空間です。",
        "address": "長野県松本市大村681",
        "prefecture_slug": "nagano",
        "city_slug": "matsumoto",
        "latitude": 36.218,
        "longitude": 137.975,
        "nearest_station": "JR篠ノ井線 村井駅",
        "station_walk_minutes": 15,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["寺院式場", "宗派不問", "家族葬対応", "駐車場完備"],
        "operator_name": "盛泉寺",
        "rating_avg": 4.1,
        "review_count": 12,
    },
    {
        "name": "メモリアルホール松本北",
        "slug": "memorial-hall-matsumoto-kita",
        "venue_type": "private_hall",
        "description": "松本市北部に位置する中規模葬儀会館。家族葬から一般葬まで幅広く対応し、バリアフリー完備の近代的な施設。充実した控室と駐車場を備え、遠方からの参列者にも配慮した設備が整っています。",
        "address": "長野県松本市島内4462-3",
        "prefecture_slug": "nagano",
        "city_slug": "matsumoto",
        "latitude": 36.258,
        "longitude": 137.948,
        "nearest_station": "JR大糸線 島内駅",
        "station_walk_minutes": 8,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000}],
        "features": ["駅近", "大規模葬対応", "家族葬対応", "宿泊可能", "バリアフリー"],
        "operator_name": "メモリアルホール松本",
        "rating_avg": 4.0,
        "review_count": 20,
    },
    {
        "name": "小さなお葬式 松本ホール",
        "slug": "chiisana-ososhiki-matsumoto",
        "venue_type": "private_hall",
        "description": "全国展開の「小さなお葬式」ブランドの松本ホール。火葬式から家族葬まで明確な料金体系で提供。追加費用が少なく、シンプルで温かみのある葬儀を実現。松本市内のアクセスしやすい場所に位置しています。",
        "address": "長野県松本市中央2-1-18",
        "prefecture_slug": "nagano",
        "city_slug": "matsumoto",
        "latitude": 36.234,
        "longitude": 137.970,
        "nearest_station": "JR篠ノ井線 松本駅",
        "station_walk_minutes": 7,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["低価格", "明朗会計", "駅近", "家族葬対応"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 4.0,
        "review_count": 13,
    },
    {
        "name": "松本葬祭ホール梓",
        "slug": "matsumoto-sousai-azusa",
        "venue_type": "private_hall",
        "description": "松本市西部の葬儀ホール。北アルプスを望むロケーションで、家族葬に最適な落ち着いた空間を提供。1日1組貸切で、ご家族のペースでお別れの時間を過ごせます。経験豊富なスタッフが細やかにサポートします。",
        "address": "長野県松本市波田5215-3",
        "prefecture_slug": "nagano",
        "city_slug": "matsumoto",
        "latitude": 36.218,
        "longitude": 137.880,
        "nearest_station": "アルピコ交通上高地線 波田駅",
        "station_walk_minutes": 10,
        "capacity_max": 35,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["1日1組貸切", "家族葬対応", "自然環境", "駐車場完備"],
        "operator_name": "松本葬祭",
        "rating_avg": 4.1,
        "review_count": 10,
    },

    # =============================================
    # 上田市 (ueda) — 4件追加
    # =============================================
    {
        "name": "上田法事センター",
        "slug": "ueda-houji-center",
        "venue_type": "private_hall",
        "description": "上田市の葬儀・法事専用ホール。しなの鉄道「上田駅」から車で約8分。家族葬から一般葬まで対応可能で、法事にも利用される多目的施設。地域密着型のサービスと丁寧な対応で、地元の方々に親しまれています。",
        "address": "長野県上田市住吉306-9",
        "prefecture_slug": "nagano",
        "city_slug": "ueda",
        "latitude": 36.398,
        "longitude": 138.260,
        "nearest_station": "しなの鉄道線 上田駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 508000}],
        "features": ["法事対応", "家族葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "上田法事センター",
        "rating_avg": 4.0,
        "review_count": 16,
    },
    {
        "name": "家族葬のSHION上田",
        "slug": "shion-ueda",
        "venue_type": "private_hall",
        "description": "SHIONが展開する上田市の家族葬専用ホール。少人数のお別れに特化した落ち着いた空間で、1日1組完全貸切。24時間365日対応で、急な場合にも安心。上田市内の住宅街に位置し、静かな環境でゆっくりとお別れができます。",
        "address": "長野県上田市中央北1-8-15",
        "prefecture_slug": "nagano",
        "city_slug": "ueda",
        "latitude": 36.403,
        "longitude": 138.252,
        "nearest_station": "しなの鉄道線 上田駅",
        "station_walk_minutes": 10,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["家族葬専用", "1日1組貸切", "駅近", "24時間対応"],
        "operator_name": "SHION",
        "rating_avg": 4.4,
        "review_count": 14,
    },
    {
        "name": "ベルホール吉池 上田店",
        "slug": "bellhall-yoshiike-ueda",
        "venue_type": "private_hall",
        "description": "長野県の老舗葬儀社・吉池が運営する上田市の葬儀ホール。家族葬から一般葬まで幅広く対応し、経験豊富なスタッフが丁寧にサポート。上田市内のアクセスしやすい立地で、広い駐車場を完備しています。",
        "address": "長野県上田市天神3-5-1",
        "prefecture_slug": "nagano",
        "city_slug": "ueda",
        "latitude": 36.400,
        "longitude": 138.245,
        "nearest_station": "しなの鉄道線 上田駅",
        "station_walk_minutes": 12,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 115000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 578000}],
        "features": ["老舗葬儀社", "大規模葬対応", "家族葬対応", "宿泊可能"],
        "operator_name": "株式会社吉池",
        "rating_avg": 4.3,
        "review_count": 22,
    },
    {
        "name": "メモリアルホール上田",
        "slug": "memorial-hall-ueda",
        "venue_type": "private_hall",
        "description": "上田市の中規模葬儀会館。通夜から告別式まで対応可能で、家族葬にも最適。清潔感のある近代的な設備とバリアフリー対応が特長。遠方からの参列者向けの宿泊施設も備えています。",
        "address": "長野県上田市材木町2-3-20",
        "prefecture_slug": "nagano",
        "city_slug": "ueda",
        "latitude": 36.405,
        "longitude": 138.255,
        "nearest_station": "しなの鉄道線 上田駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["駅近", "家族葬対応", "宿泊可能", "バリアフリー"],
        "operator_name": "メモリアルホール上田",
        "rating_avg": 4.1,
        "review_count": 18,
    },

    # =============================================
    # 飯田市 (iida) — 3件追加
    # =============================================
    {
        "name": "伊那谷セレモニーホール",
        "slug": "inatani-ceremony-iida",
        "venue_type": "private_hall",
        "description": "飯田市の民間葬儀会館。南信州エリアで実績のある葬儀社が運営。家族葬から一般葬まで対応可能で、南アルプスを望む自然豊かな環境。地域の風習に精通したスタッフが丁寧にサポートします。",
        "address": "長野県飯田市鼎上山2877",
        "prefecture_slug": "nagano",
        "city_slug": "iida",
        "latitude": 35.510,
        "longitude": 137.824,
        "nearest_station": "JR飯田線 鼎駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["家族葬対応", "大規模葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "伊那谷セレモニー",
        "rating_avg": 4.1,
        "review_count": 15,
    },
    {
        "name": "家族葬ホール飯田",
        "slug": "kazokuso-hall-iida",
        "venue_type": "private_hall",
        "description": "飯田市の家族葬専用ホール。少人数のお別れに最適な落ち着いた空間。1日1組貸切で、ご家族のペースでゆっくりとお別れができます。飯田IC近くでアクセスも便利。24時間対応の相談窓口があります。",
        "address": "長野県飯田市座光寺3256",
        "prefecture_slug": "nagano",
        "city_slug": "iida",
        "latitude": 35.500,
        "longitude": 137.842,
        "nearest_station": "JR飯田線 元善光寺駅",
        "station_walk_minutes": 8,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["家族葬専用", "1日1組貸切", "24時間対応", "IC近く"],
        "operator_name": "飯田葬祭",
        "rating_avg": 4.3,
        "review_count": 11,
    },
    {
        "name": "セレモニーホール南信",
        "slug": "ceremony-hall-nanshin",
        "venue_type": "private_hall",
        "description": "飯田市中心部の葬儀会館。JR飯田駅から車で約5分。中規模の式場を備え、一般葬から家族葬まで幅広く対応。南信地域で長年の実績を持ち、地域の葬儀文化に精通したスタッフが丁寧にサポートします。",
        "address": "長野県飯田市本町3-15",
        "prefecture_slug": "nagano",
        "city_slug": "iida",
        "latitude": 35.515,
        "longitude": 137.821,
        "nearest_station": "JR飯田線 飯田駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["老舗葬儀社", "大規模葬対応", "家族葬対応", "宿泊可能"],
        "operator_name": "南信セレモニー",
        "rating_avg": 4.0,
        "review_count": 17,
    },

    # =============================================
    # 諏訪市 (suwa) — 3件
    # =============================================
    {
        "name": "諏訪市斎場",
        "slug": "suwa-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "諏訪市が運営する公営火葬場。諏訪湖を望む高台に位置し、静かな環境で故人を見送れます。火葬施設を備え、諏訪市民は利用料が優遇されます。待合室と駐車場を完備したバリアフリー対応の施設です。",
        "address": "長野県諏訪市大字中洲5386",
        "prefecture_slug": "nagano",
        "city_slug": "suwa",
        "latitude": 36.038,
        "longitude": 138.115,
        "nearest_station": "JR中央本線 上諏訪駅",
        "station_walk_minutes": 20,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 72000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "諏訪市",
        "rating_avg": 3.7,
        "review_count": 18,
    },
    {
        "name": "えこうホール諏訪",
        "slug": "ekou-hall-suwa",
        "venue_type": "private_hall",
        "description": "諏訪市の民間葬儀会館。JR上諏訪駅からタクシー約8分。家族葬から一般葬まで対応可能で、落ち着いた雰囲気の式場を備えています。諏訪湖周辺エリアで実績のある葬儀社が運営し、地域の風習に配慮したサービスを提供。",
        "address": "長野県諏訪市四賀赤沼1545-1",
        "prefecture_slug": "nagano",
        "city_slug": "suwa",
        "latitude": 36.045,
        "longitude": 138.098,
        "nearest_station": "JR中央本線 上諏訪駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["家族葬対応", "大規模葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "株式会社えこう",
        "rating_avg": 4.2,
        "review_count": 20,
    },
    {
        "name": "セイ・ホール諏訪",
        "slug": "sei-hall-suwa",
        "venue_type": "private_hall",
        "description": "諏訪市の家族葬対応ホール。「ふれ愛空間」をコンセプトに、温かみのあるサービスを提供。少人数のお別れに適した落ち着いた空間で、1日1組貸切対応。上諏訪エリアからアクセスしやすい立地です。",
        "address": "長野県諏訪市大字上諏訪12-8",
        "prefecture_slug": "nagano",
        "city_slug": "suwa",
        "latitude": 36.043,
        "longitude": 138.113,
        "nearest_station": "JR中央本線 上諏訪駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬専用", "1日1組貸切", "駅近", "24時間対応"],
        "operator_name": "株式会社セイホール",
        "rating_avg": 4.3,
        "review_count": 14,
    },

    # =============================================
    # 佐久市 (saku) — 2件
    # =============================================
    {
        "name": "佐久斎場",
        "slug": "saku-saijo",
        "venue_type": "public_crematorium",
        "description": "佐久広域連合が運営する公営火葬場。佐久市・小諸市・軽井沢町など広域の住民が利用可能。火葬施設と待合室を備え、広い駐車場を完備。浅間山を望む静かな環境で、故人を厳かに見送れる施設です。",
        "address": "長野県佐久市大字岩村田3162-1",
        "prefecture_slug": "nagano",
        "city_slug": "saku",
        "latitude": 36.249,
        "longitude": 138.475,
        "nearest_station": "JR小海線 佐久平駅",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 40,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "佐久広域連合",
        "rating_avg": 3.8,
        "review_count": 20,
    },
    {
        "name": "セレモニーホール佐久",
        "slug": "ceremony-hall-saku",
        "venue_type": "private_hall",
        "description": "佐久市の民間葬儀会館。JR佐久平駅から車で約10分。家族葬から一般葬まで対応可能な充実した施設。経験豊富なスタッフが東信エリアの葬儀文化に配慮したサービスを提供しています。",
        "address": "長野県佐久市猿久保28-1",
        "prefecture_slug": "nagano",
        "city_slug": "saku",
        "latitude": 36.251,
        "longitude": 138.468,
        "nearest_station": "JR小海線 佐久平駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["家族葬対応", "大規模葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "佐久セレモニー",
        "rating_avg": 4.1,
        "review_count": 16,
    },

    # =============================================
    # 安曇野市 (azumino) — 2件
    # =============================================
    {
        "name": "安曇野セレモニーホール",
        "slug": "azumino-ceremony-hall",
        "venue_type": "private_hall",
        "description": "安曇野市の民間葬儀会館。北アルプスを望む自然豊かな環境に位置。家族葬から一般葬まで幅広く対応し、温かみのあるサービスが特長。広い駐車場を完備し、遠方からの参列者にも配慮しています。",
        "address": "長野県安曇野市穂高5156-2",
        "prefecture_slug": "nagano",
        "city_slug": "azumino",
        "latitude": 36.338,
        "longitude": 137.883,
        "nearest_station": "JR大糸線 穂高駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["自然環境", "家族葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "安曇野セレモニー",
        "rating_avg": 4.2,
        "review_count": 15,
    },
    {
        "name": "家族葬ホール安曇野",
        "slug": "kazokuso-hall-azumino",
        "venue_type": "private_hall",
        "description": "安曇野市の家族葬専用ホール。少人数のお別れに特化した落ち着いた空間で、1日1組完全貸切。北アルプスの眺望が美しい立地で、穏やかな雰囲気の中お別れの時間を過ごせます。",
        "address": "長野県安曇野市三郷明盛2815",
        "prefecture_slug": "nagano",
        "city_slug": "azumino",
        "latitude": 36.290,
        "longitude": 137.868,
        "nearest_station": "JR大糸線 一日市場駅",
        "station_walk_minutes": 12,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["家族葬専用", "1日1組貸切", "自然環境", "24時間対応"],
        "operator_name": "安曇野葬祭",
        "rating_avg": 4.3,
        "review_count": 11,
    },

    # =============================================
    # その他の市 — 各1〜2件（合計約12件）
    # =============================================

    # 須坂市 (suzaka) — 1件
    {
        "name": "ハクゼンホール須坂会館",
        "slug": "hakuzen-suzaka",
        "venue_type": "private_hall",
        "description": "博善社が運営する須坂市の葬儀会館。家族葬から一般葬まで対応可能。安置室完備で、須坂市・中野市エリアの方々に利用されています。地域に根ざした丁寧なサービスが特長です。",
        "address": "長野県須坂市大字須坂1239-1",
        "prefecture_slug": "nagano",
        "city_slug": "suzaka",
        "latitude": 36.651,
        "longitude": 138.307,
        "nearest_station": "長野電鉄 須坂駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["安置室完備", "家族葬対応", "駅近", "駐車場完備"],
        "operator_name": "株式会社博善社",
        "rating_avg": 4.1,
        "review_count": 14,
    },

    # 小諸市 (komoro) — 1件
    {
        "name": "小諸市営火葬場",
        "slug": "komoro-shiee-kasoba",
        "venue_type": "public_crematorium",
        "description": "小諸市が運営する公営火葬場。浅間山の麓に位置し、自然に囲まれた静かな環境。市民は利用料が優遇されます。待合室と駐車場を完備し、バリアフリーにも対応しています。",
        "address": "長野県小諸市大字諸198-2",
        "prefecture_slug": "nagano",
        "city_slug": "komoro",
        "latitude": 36.325,
        "longitude": 138.425,
        "nearest_station": "しなの鉄道線 小諸駅",
        "station_walk_minutes": 20,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 20,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 68000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "小諸市",
        "rating_avg": 3.6,
        "review_count": 10,
    },

    # 伊那市 (ina) — 2件
    {
        "name": "伊那市火葬場",
        "slug": "ina-shi-kasoba",
        "venue_type": "public_crematorium",
        "description": "伊那市が運営する公営火葬場。南アルプスと中央アルプスに挟まれた伊那谷の自然豊かな環境。市民は利用料が優遇されます。火葬施設と待合室を備え、穏やかな場所で故人を見送れます。",
        "address": "長野県伊那市大字伊那3556",
        "prefecture_slug": "nagano",
        "city_slug": "ina",
        "latitude": 35.832,
        "longitude": 137.954,
        "nearest_station": "JR飯田線 伊那市駅",
        "station_walk_minutes": 20,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 72000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "伊那市",
        "rating_avg": 3.7,
        "review_count": 15,
    },
    {
        "name": "セレモニーホール伊那",
        "slug": "ceremony-hall-ina",
        "venue_type": "private_hall",
        "description": "伊那市の民間葬儀会館。JR伊那市駅から車で約8分。上伊那エリアで実績のある葬儀社が運営し、家族葬から一般葬まで幅広く対応。アルプスの眺望が美しい立地で、落ち着いた雰囲気の中お別れができます。",
        "address": "長野県伊那市荒井3413-1",
        "prefecture_slug": "nagano",
        "city_slug": "ina",
        "latitude": 35.840,
        "longitude": 137.958,
        "nearest_station": "JR飯田線 伊那市駅",
        "station_walk_minutes": 12,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["家族葬対応", "大規模葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "伊那セレモニー",
        "rating_avg": 4.1,
        "review_count": 17,
    },

    # 駒ヶ根市 (komagane) — 1件
    {
        "name": "駒ヶ根市斎場",
        "slug": "komagane-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "駒ヶ根市が運営する公営火葬場。中央アルプス千畳敷を望む自然豊かな環境。市民は火葬料が優遇されます。火葬施設と待合室を備え、静かな場所で故人を見送れます。駐車場完備でバリアフリー対応です。",
        "address": "長野県駒ヶ根市赤穂8118",
        "prefecture_slug": "nagano",
        "city_slug": "komagane",
        "latitude": 35.729,
        "longitude": 137.932,
        "nearest_station": "JR飯田線 駒ヶ根駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 25,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 70000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "駒ヶ根市",
        "rating_avg": 3.7,
        "review_count": 12,
    },

    # 中野市 (nakano-nagano) — 1件
    {
        "name": "中野市斎場",
        "slug": "nakano-nagano-saijo",
        "venue_type": "public_crematorium",
        "description": "中野市が運営する公営火葬場。北信濃の自然に囲まれた静かな環境。市民は利用料が優遇されます。火葬施設と待合室を備え、駐車場を完備。バリアフリー対応で安心して利用できます。",
        "address": "長野県中野市大字岩船316-1",
        "prefecture_slug": "nagano",
        "city_slug": "nakano-nagano",
        "latitude": 36.742,
        "longitude": 138.368,
        "nearest_station": "長野電鉄 信州中野駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 20,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 70000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "中野市",
        "rating_avg": 3.6,
        "review_count": 10,
    },

    # 茅野市 (chino) — 1件
    {
        "name": "茅野市営火葬場",
        "slug": "chino-shiee-kasoba",
        "venue_type": "public_crematorium",
        "description": "茅野市が運営する公営火葬場。八ヶ岳の麓に位置し、自然豊かな環境。市民は利用料が優遇されます。火葬施設と待合室を備え、静かな場所で故人を見送れます。蓼科高原エリアからのアクセスも良好です。",
        "address": "長野県茅野市宮川2581-1",
        "prefecture_slug": "nagano",
        "city_slug": "chino",
        "latitude": 35.995,
        "longitude": 138.155,
        "nearest_station": "JR中央本線 茅野駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 25,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 72000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "茅野市",
        "rating_avg": 3.7,
        "review_count": 12,
    },

    # 塩尻市 (shiojiri) — 2件
    {
        "name": "塩尻市斎場",
        "slug": "shiojiri-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "塩尻市が運営する公営火葬場。松本盆地南部に位置し、アルプスを望む静かな環境。市民は火葬料が優遇されます。火葬施設と待合室を備え、バリアフリー対応。近代的な設備で安心して利用できます。",
        "address": "長野県塩尻市大字広丘吉田880-1",
        "prefecture_slug": "nagano",
        "city_slug": "shiojiri",
        "latitude": 36.107,
        "longitude": 137.955,
        "nearest_station": "JR篠ノ井線 塩尻駅",
        "station_walk_minutes": 15,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 72000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "塩尻市",
        "rating_avg": 3.8,
        "review_count": 15,
    },
    {
        "name": "家族葬ホール塩尻",
        "slug": "kazokuso-hall-shiojiri",
        "venue_type": "private_hall",
        "description": "塩尻市の家族葬専用ホール。少人数のお別れに最適な落ち着いた空間。1日1組貸切で、ご家族のペースでゆっくりとお別れができます。JR塩尻駅から車で約5分の好立地。24時間対応の相談窓口があります。",
        "address": "長野県塩尻市大門一番町9-5",
        "prefecture_slug": "nagano",
        "city_slug": "shiojiri",
        "latitude": 36.111,
        "longitude": 137.953,
        "nearest_station": "JR篠ノ井線 塩尻駅",
        "station_walk_minutes": 8,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["家族葬専用", "1日1組貸切", "駅近", "24時間対応"],
        "operator_name": "塩尻葬祭",
        "rating_avg": 4.2,
        "review_count": 10,
    },

    # 千曲市 (chikuma) — 1件
    {
        "name": "千曲市営斎場",
        "slug": "chikuma-shiee-saijo",
        "venue_type": "public_crematorium",
        "description": "千曲市が運営する公営火葬場。善光寺平を望む高台に位置し、静かな環境。市民は火葬料が優遇されます。しなの鉄道「屋代駅」からタクシー約10分。待合室と駐車場を完備したバリアフリー対応施設です。",
        "address": "長野県千曲市大字屋代2251-1",
        "prefecture_slug": "nagano",
        "city_slug": "chikuma",
        "latitude": 36.530,
        "longitude": 138.128,
        "nearest_station": "しなの鉄道線 屋代駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 20,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 70000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "千曲市",
        "rating_avg": 3.6,
        "review_count": 10,
    },

    # 大町市 (omachi) — 1件
    {
        "name": "大町市斎場",
        "slug": "omachi-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "大町市が運営する公営火葬場。北アルプスの麓・大町に位置し、雄大な自然に囲まれた環境。市民は火葬料が優遇されます。JR信濃大町駅からタクシー約10分。待合室と駐車場を備えたバリアフリー施設です。",
        "address": "長野県大町市大字大町4528",
        "prefecture_slug": "nagano",
        "city_slug": "omachi",
        "latitude": 36.505,
        "longitude": 137.852,
        "nearest_station": "JR大糸線 信濃大町駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 20,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 68000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "自然環境"],
        "operator_name": "大町市",
        "rating_avg": 3.6,
        "review_count": 8,
    },

    # 飯山市 (iiyama) — 1件
    {
        "name": "飯山市斎場",
        "slug": "iiyama-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "飯山市が運営する公営火葬場。北信濃の奥座敷・飯山に位置し、四季折々の自然に囲まれた環境。市民は火葬料が優遇されます。JR飯山駅からタクシー約10分。待合室と駐車場を完備しています。",
        "address": "長野県飯山市大字飯山2820",
        "prefecture_slug": "nagano",
        "city_slug": "iiyama",
        "latitude": 36.851,
        "longitude": 138.362,
        "nearest_station": "JR北陸新幹線 飯山駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 20,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 68000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "飯山市",
        "rating_avg": 3.6,
        "review_count": 8,
    },

    # 東御市 (tomi) — 1件
    {
        "name": "東御市斎場",
        "slug": "tomi-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "東御市が運営する公営火葬場。浅間連峰を望む東信エリアに位置。市民は利用料が優遇されます。しなの鉄道「田中駅」からタクシー約10分。火葬施設と待合室を備えた近代的な施設です。",
        "address": "長野県東御市滋野乙3236",
        "prefecture_slug": "nagano",
        "city_slug": "tomi",
        "latitude": 36.355,
        "longitude": 138.341,
        "nearest_station": "しなの鉄道線 田中駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 20,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 68000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "東御市",
        "rating_avg": 3.6,
        "review_count": 7,
    },
]

def insert_batch(batch, batch_num, total_batches):
    data = json.dumps(batch, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(SUPABASE_URL, data=data, headers=HEADERS, method="POST")
    try:
        with urllib.request.urlopen(req) as resp:
            print(f"  バッチ {batch_num}/{total_batches}: HTTP {resp.status} OK ({len(batch)}件)")
            return True
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")
        print(f"  バッチ {batch_num}/{total_batches}: HTTP {e.code} ERROR")
        print(f"  レスポンス: {body[:500]}")
        return False

def main():
    print(f"=== 長野県 斎場データ追加 (batch2) ===")
    print(f"合計: {len(venues)}件")
    print()

    batch_size = 10
    total_batches = (len(venues) + batch_size - 1) // batch_size
    success_count = 0
    fail_count = 0

    for i in range(0, len(venues), batch_size):
        batch = venues[i:i + batch_size]
        batch_num = i // batch_size + 1
        ok = insert_batch(batch, batch_num, total_batches)
        if ok:
            success_count += len(batch)
        else:
            fail_count += len(batch)
        time.sleep(0.5)

    print()
    print(f"=== 完了 ===")
    print(f"成功: {success_count}件 / 失敗: {fail_count}件")

if __name__ == "__main__":
    main()
