#!/usr/bin/env python3
"""
福島県の斎場データ パート2（41件）をSupabase REST APIに投入するスクリプト
福島市10件 + 会津若松市8件 + 須賀川市4件 + 白河市3件 + その他16件
"""

import json
import urllib.request
import urllib.error
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

HEADERS = {
    "apikey": API_KEY,
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal",
}

venues = [
    # =============================================
    # 福島市 追加10件（パート1の5件に追加）
    # =============================================
    {
        "name": "こころ斎苑 さつき",
        "slug": "fukushima-kokoro-satsuki",
        "venue_type": "private_hall",
        "description": "福島市五月町に位置するたまのやの家族葬ホール。福島市中心部にあり、アクセスが良好。少人数での温かいお別れの場を提供しています。24時間対応で安心です。",
        "address": "福島県福島市五月町1-19",
        "prefecture_slug": "fukushima", "city_slug": "fukushima-city",
        "latitude": 37.753, "longitude": 140.472,
        "nearest_station": "JR東北本線 福島駅", "station_walk_minutes": 10,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬対応", "駅近", "24時間対応"],
        "operator_name": "株式会社たまのや", "rating_avg": 4.1, "review_count": 12,
    },
    {
        "name": "こころ斎苑 きずな",
        "slug": "fukushima-kokoro-kizuna",
        "venue_type": "private_hall",
        "description": "福島市五月町に位置するたまのやの葬儀ホール。「きずな」の名の通り、家族の絆を大切にした温かみのある葬儀を提供。家族葬から一般葬まで対応可能です。",
        "address": "福島県福島市五月町11-15",
        "prefecture_slug": "fukushima", "city_slug": "fukushima-city",
        "latitude": 37.752, "longitude": 140.470,
        "nearest_station": "JR東北本線 福島駅", "station_walk_minutes": 12,
        "capacity_max": 60, "hall_count": 2, "has_crematorium": False, "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "駅近"],
        "operator_name": "株式会社たまのや", "rating_avg": 4.2, "review_count": 16,
    },
    {
        "name": "こころ斎苑 黒岩",
        "slug": "fukushima-kokoro-kuroiwa",
        "venue_type": "private_hall",
        "description": "福島市黒岩に位置するたまのやの家族葬ホール。福島市南部エリアの方に利用されている落ち着いた雰囲気の施設。バリアフリー対応で高齢の方も安心です。",
        "address": "福島県福島市黒岩字堂ノ後35",
        "prefecture_slug": "fukushima", "city_slug": "fukushima-city",
        "latitude": 37.730, "longitude": 140.475,
        "nearest_station": "JR東北本線 南福島駅", "station_walk_minutes": 12,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "株式会社たまのや", "rating_avg": 4.0, "review_count": 11,
    },
    {
        "name": "こころ斎苑 まつかわ",
        "slug": "fukushima-kokoro-matsukawa",
        "venue_type": "private_hall",
        "description": "福島市松川町に位置するたまのやの葬儀ホール。松川・二本松方面の方に利用されている施設。家族葬に適した温かみのある空間を提供しています。",
        "address": "福島県福島市松川町美郷3-22-5",
        "prefecture_slug": "fukushima", "city_slug": "fukushima-city",
        "latitude": 37.700, "longitude": 140.440,
        "nearest_station": "JR東北本線 松川駅", "station_walk_minutes": 8,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬対応", "駅近"],
        "operator_name": "株式会社たまのや", "rating_avg": 4.0, "review_count": 10,
    },
    {
        "name": "こころ斎苑 飯坂",
        "slug": "fukushima-kokoro-iizaka",
        "venue_type": "private_hall",
        "description": "福島市飯坂町に位置するたまのやの家族葬ホール。飯坂温泉エリアに近く、福島市北部の方に利用されています。24時間対応で急なご依頼にも対応いたします。",
        "address": "福島県福島市飯坂町平野字堂天前5-2",
        "prefecture_slug": "fukushima", "city_slug": "fukushima-city",
        "latitude": 37.810, "longitude": 140.445,
        "nearest_station": "福島交通飯坂線 飯坂温泉駅", "station_walk_minutes": 10,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬対応", "24時間対応"],
        "operator_name": "株式会社たまのや", "rating_avg": 4.0, "review_count": 9,
    },
    {
        "name": "さがみメモリアル斎場 野田",
        "slug": "fukushima-sagami-noda",
        "venue_type": "private_hall",
        "description": "福島駅西口より徒歩10分に位置するさがみ典礼の斎場。駅からのアクセスが抜群で、家族葬に適したコンパクトな式場を備えています。清潔感のある施設が好評です。",
        "address": "福島県福島市野田町5-2-33",
        "prefecture_slug": "fukushima", "city_slug": "fukushima-city",
        "latitude": 37.756, "longitude": 140.448,
        "nearest_station": "JR東北本線 福島駅", "station_walk_minutes": 10,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}],
        "features": ["家族葬対応", "駅近"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.1, "review_count": 15,
    },
    {
        "name": "家族葬のファミラル 御山",
        "slug": "fukushima-familar-oyama",
        "venue_type": "private_hall",
        "description": "福島市御山エリアに位置する家族葬のファミラル。少人数でのお別れに特化した温かみのあるホール。信夫山のふもとに位置し、静かな環境で故人を偲ぶことができます。",
        "address": "福島県福島市御山字三本松20-3",
        "prefecture_slug": "fukushima", "city_slug": "fukushima-city",
        "latitude": 37.775, "longitude": 140.460,
        "nearest_station": "JR東北本線 福島駅", "station_walk_minutes": 18,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬対応", "24時間対応"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.1, "review_count": 11,
    },
    {
        "name": "さがみ福島北斎場",
        "slug": "fukushima-sagami-kita",
        "venue_type": "private_hall",
        "description": "福島市北部に位置するさがみ典礼の葬儀斎場。国道13号線沿いでアクセスが良好。福島市北部・伊達市方面の方に多く利用されている施設です。",
        "address": "福島県福島市北矢野目字坂東7-1",
        "prefecture_slug": "fukushima", "city_slug": "fukushima-city",
        "latitude": 37.785, "longitude": 140.455,
        "nearest_station": "福島交通飯坂線 岩代清水駅", "station_walk_minutes": 12,
        "capacity_max": 100, "hall_count": 2, "has_crematorium": False, "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "駐車場完備"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.0, "review_count": 17,
    },
    {
        "name": "さがみ福島南斎場",
        "slug": "fukushima-sagami-minami",
        "venue_type": "private_hall",
        "description": "福島市南部に位置するさがみ典礼の葬儀斎場。福島南バイパス沿いで車でのアクセスが良好。福島市南部・二本松市方面の方に利用されています。",
        "address": "福島県福島市太平寺字堰ノ上58-1",
        "prefecture_slug": "fukushima", "city_slug": "fukushima-city",
        "latitude": 37.725, "longitude": 140.460,
        "nearest_station": "JR東北本線 南福島駅", "station_walk_minutes": 10,
        "capacity_max": 100, "hall_count": 2, "has_crematorium": False, "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "駐車場完備"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.0, "review_count": 18,
    },
    {
        "name": "小さなお葬式 福島ホール",
        "slug": "fukushima-chiisana-ososhiki",
        "venue_type": "private_hall",
        "description": "全国展開の「小さなお葬式」提携ホール。追加料金なしの明朗会計プランが特徴。福島市内で費用を抑えた葬儀をお考えの方に最適な施設です。",
        "address": "福島県福島市本町5-8",
        "prefecture_slug": "fukushima", "city_slug": "fukushima-city",
        "latitude": 37.755, "longitude": 140.465,
        "nearest_station": "JR東北本線 福島駅", "station_walk_minutes": 8,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["家族葬対応", "低価格", "駅近"],
        "operator_name": "株式会社ユニクエスト", "rating_avg": 3.9, "review_count": 8,
    },
    # =============================================
    # 会津若松市 8件
    # =============================================
    {
        "name": "会津若松市斎場",
        "slug": "aizuwakamatsu-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "会津若松市が運営する公営火葬場。門田町黒岩に位置し、標準炉4基・大型炉2基を備えています。会津若松市民は火葬料の優遇措置があります。待合室4室完備。",
        "address": "福島県会津若松市門田町黒岩字石高甲807",
        "prefecture_slug": "fukushima", "city_slug": "aizuwakamatsu",
        "latitude": 37.472, "longitude": 139.932,
        "nearest_station": "JR磐越西線 会津若松駅", "station_walk_minutes": 25,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": True, "parking_count": 40,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "会津若松市", "rating_avg": 3.6, "review_count": 20,
    },
    {
        "name": "さがみ典礼 会津斎場",
        "slug": "aizuwakamatsu-sagami-saijo",
        "venue_type": "private_hall",
        "description": "会津若松市宮町に位置するさがみ典礼の葬儀斎場。最大200名収容可能で、駐車場も完備。家族葬から大規模葬儀まで対応可能な会津地域の中核的な葬儀施設です。",
        "address": "福島県会津若松市宮町5-25",
        "prefecture_slug": "fukushima", "city_slug": "aizuwakamatsu",
        "latitude": 37.500, "longitude": 139.935,
        "nearest_station": "JR磐越西線 会津若松駅", "station_walk_minutes": 12,
        "capacity_max": 200, "hall_count": 3, "has_crematorium": False, "parking_count": 60,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["大規模葬対応", "家族葬対応", "駐車場完備", "宿泊可能"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.2, "review_count": 22,
    },
    {
        "name": "さがみ門田斎場",
        "slug": "aizuwakamatsu-sagami-monden",
        "venue_type": "private_hall",
        "description": "会津若松市門田エリアに位置するさがみ典礼の葬儀斎場。最大250名収容可能な大型施設。会津若松市南部の方に多く利用されています。",
        "address": "福島県会津若松市西年貢1-7-6",
        "prefecture_slug": "fukushima", "city_slug": "aizuwakamatsu",
        "latitude": 37.485, "longitude": 139.920,
        "nearest_station": "会津鉄道 西若松駅", "station_walk_minutes": 10,
        "capacity_max": 250, "hall_count": 3, "has_crematorium": False, "parking_count": 80,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["大規模葬対応", "家族葬対応", "駐車場完備"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.1, "review_count": 19,
    },
    {
        "name": "こころ斎苑 会津",
        "slug": "aizuwakamatsu-kokoro",
        "venue_type": "private_hall",
        "description": "会津若松市に位置するたまのやの葬儀ホール。家族葬に特化した温かみのある施設で、鶴ヶ城からほど近い歴史ある街中に立地。24時間対応で安心です。",
        "address": "福島県会津若松市八角町13-36",
        "prefecture_slug": "fukushima", "city_slug": "aizuwakamatsu",
        "latitude": 37.495, "longitude": 139.940,
        "nearest_station": "JR磐越西線 会津若松駅", "station_walk_minutes": 15,
        "capacity_max": 50, "hall_count": 2, "has_crematorium": False, "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "24時間対応"],
        "operator_name": "株式会社たまのや", "rating_avg": 4.2, "review_count": 15,
    },
    {
        "name": "こころ斎苑 門田",
        "slug": "aizuwakamatsu-kokoro-monden",
        "venue_type": "private_hall",
        "description": "会津若松市門田町に位置するたまのやの家族葬ホール。門田町黒岩エリアにあり、落ち着いた環境で故人を偲ぶことができます。少人数でのお別れに最適です。",
        "address": "福島県会津若松市門田町黒岩字大坪239",
        "prefecture_slug": "fukushima", "city_slug": "aizuwakamatsu",
        "latitude": 37.478, "longitude": 139.928,
        "nearest_station": "会津鉄道 西若松駅", "station_walk_minutes": 12,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "株式会社たまのや", "rating_avg": 4.0, "review_count": 11,
    },
    {
        "name": "とわノイエ 門田",
        "slug": "aizuwakamatsu-towanoie-monden",
        "venue_type": "private_hall",
        "description": "会津若松市に位置する家族葬専用ホール。「永遠の家」をコンセプトに、自宅のような温かみのある空間でお別れの時間を過ごせます。少人数の家族葬に最適です。",
        "address": "福島県会津若松市山見町24-13",
        "prefecture_slug": "fukushima", "city_slug": "aizuwakamatsu",
        "latitude": 37.490, "longitude": 139.925,
        "nearest_station": "JR磐越西線 会津若松駅", "station_walk_minutes": 18,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}],
        "features": ["家族葬対応", "低価格"],
        "operator_name": "とわノイエ", "rating_avg": 4.3, "review_count": 10,
    },
    {
        "name": "平安祭典 会津ホール",
        "slug": "aizuwakamatsu-heian-saiten",
        "venue_type": "private_hall",
        "description": "会津若松市中心部に位置する平安祭典の葬儀会館。家族葬から一般葬まで幅広く対応。会津地域で長年の実績を持つ信頼の葬儀社が運営する施設です。",
        "address": "福島県会津若松市馬場町1-35",
        "prefecture_slug": "fukushima", "city_slug": "aizuwakamatsu",
        "latitude": 37.498, "longitude": 139.932,
        "nearest_station": "JR磐越西線 会津若松駅", "station_walk_minutes": 10,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "駅近", "駐車場完備"],
        "operator_name": "平安祭典", "rating_avg": 4.0, "review_count": 16,
    },
    {
        "name": "JAあいづ 葬祭ホール",
        "slug": "aizuwakamatsu-ja-aizu",
        "venue_type": "public_facility",
        "description": "JAあいづが運営する葬祭ホール。JA組合員だけでなく一般の方も利用可能。リーズナブルな価格設定が特徴で、会津地域の方に広く利用されています。",
        "address": "福島県会津若松市神指町大字中四合字伊丹堰33",
        "prefecture_slug": "fukushima", "city_slug": "aizuwakamatsu",
        "latitude": 37.510, "longitude": 139.910,
        "nearest_station": "JR磐越西線 会津若松駅", "station_walk_minutes": 25,
        "capacity_max": 80, "hall_count": 1, "has_crematorium": False, "parking_count": 40,
        "facilities": {"安置室": True, "駐車場": True, "控室": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 480000}],
        "features": ["家族葬対応", "低価格", "駐車場完備"],
        "operator_name": "JAあいづ", "rating_avg": 3.9, "review_count": 13,
    },
    # =============================================
    # 須賀川市 4件
    # =============================================
    {
        "name": "須賀川市斎場",
        "slug": "sukagawa-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "須賀川市が運営する公営火葬場。須賀川市民は火葬料の優遇措置があります。東北自動車道須賀川ICから近く、アクセスが良好な施設です。",
        "address": "福島県須賀川市大字浜尾字小貫44-1",
        "prefecture_slug": "fukushima", "city_slug": "sukagawa",
        "latitude": 37.275, "longitude": 140.355,
        "nearest_station": "JR東北本線 須賀川駅", "station_walk_minutes": 20,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "須賀川市", "rating_avg": 3.5, "review_count": 15,
    },
    {
        "name": "さがみ典礼 須賀川斎場",
        "slug": "sukagawa-sagami-saijo",
        "venue_type": "private_hall",
        "description": "須賀川市中心部に位置するさがみ典礼の葬儀斎場。JR須賀川駅から車で5分のアクセス。家族葬から一般葬まで対応可能な充実した設備の施設です。",
        "address": "福島県須賀川市東町57-1",
        "prefecture_slug": "fukushima", "city_slug": "sukagawa",
        "latitude": 37.288, "longitude": 140.376,
        "nearest_station": "JR東北本線 須賀川駅", "station_walk_minutes": 10,
        "capacity_max": 120, "hall_count": 2, "has_crematorium": False, "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "駐車場完備"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.1, "review_count": 17,
    },
    {
        "name": "こころ斎苑 須賀川",
        "slug": "sukagawa-kokoro",
        "venue_type": "private_hall",
        "description": "須賀川市に位置するたまのやの家族葬ホール。家族葬に特化した落ち着いた空間で、須賀川市・鏡石町エリアの方に利用されています。24時間対応です。",
        "address": "福島県須賀川市池下町18-5",
        "prefecture_slug": "fukushima", "city_slug": "sukagawa",
        "latitude": 37.285, "longitude": 140.368,
        "nearest_station": "JR東北本線 須賀川駅", "station_walk_minutes": 12,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬対応", "24時間対応"],
        "operator_name": "株式会社たまのや", "rating_avg": 4.1, "review_count": 12,
    },
    {
        "name": "須賀川典礼会館",
        "slug": "sukagawa-tenrei-kaikan",
        "venue_type": "private_hall",
        "description": "須賀川市に位置する地域密着型の葬儀会館。長年にわたり須賀川地域の葬儀を担ってきた実績のある施設。家族葬から一般葬まで丁寧に対応します。",
        "address": "福島県須賀川市南上町80",
        "prefecture_slug": "fukushima", "city_slug": "sukagawa",
        "latitude": 37.282, "longitude": 140.372,
        "nearest_station": "JR東北本線 須賀川駅", "station_walk_minutes": 8,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "駅近", "地域密着"],
        "operator_name": "須賀川典礼会館", "rating_avg": 4.0, "review_count": 14,
    },
    # =============================================
    # 白河市 3件
    # =============================================
    {
        "name": "白河市斎場",
        "slug": "shirakawa-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "白河市が運営する公営火葬場。白河の関で知られる歴史ある街に位置し、白河市民は火葬料の優遇措置があります。静かな環境で故人をお見送りできます。",
        "address": "福島県白河市大信隈戸字岩崎山1-5",
        "prefecture_slug": "fukushima", "city_slug": "shirakawa",
        "latitude": 37.120, "longitude": 140.180,
        "nearest_station": "JR東北本線 白河駅", "station_walk_minutes": 30,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 25,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "白河市", "rating_avg": 3.5, "review_count": 12,
    },
    {
        "name": "さがみ典礼 白河斎場",
        "slug": "shirakawa-sagami-saijo",
        "venue_type": "private_hall",
        "description": "白河市に位置するさがみ典礼の葬儀斎場。白河駅から近くアクセスが良好。白河市・西郷村エリアの方に利用されている施設で、家族葬から一般葬まで対応可能です。",
        "address": "福島県白河市新白河3-67",
        "prefecture_slug": "fukushima", "city_slug": "shirakawa",
        "latitude": 37.118, "longitude": 140.210,
        "nearest_station": "JR東北本線 新白河駅", "station_walk_minutes": 8,
        "capacity_max": 120, "hall_count": 2, "has_crematorium": False, "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "駅近", "駐車場完備"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.1, "review_count": 16,
    },
    {
        "name": "こころ斎苑 白河",
        "slug": "shirakawa-kokoro",
        "venue_type": "private_hall",
        "description": "白河市に位置するたまのやの家族葬ホール。小峰城に近い市街地に立地し、白河市エリアの方に利用されています。家族葬に特化した温かみのある施設です。",
        "address": "福島県白河市道場小路96-5",
        "prefecture_slug": "fukushima", "city_slug": "shirakawa",
        "latitude": 37.125, "longitude": 140.205,
        "nearest_station": "JR東北本線 白河駅", "station_walk_minutes": 10,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬対応", "駅近", "24時間対応"],
        "operator_name": "株式会社たまのや", "rating_avg": 4.0, "review_count": 10,
    },
    # =============================================
    # 喜多方市 3件
    # =============================================
    {
        "name": "喜多方市斎場",
        "slug": "kitakata-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "喜多方市が運営する公営火葬場。ラーメンの街として知られる喜多方市に位置し、市民は火葬料の優遇措置があります。山々に囲まれた静かな環境の施設です。",
        "address": "福島県喜多方市松山町鳥見山字三吉5830",
        "prefecture_slug": "fukushima", "city_slug": "kitakata",
        "latitude": 37.660, "longitude": 139.875,
        "nearest_station": "JR磐越西線 喜多方駅", "station_walk_minutes": 20,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 25,
        "facilities": {"霊安室": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "喜多方市", "rating_avg": 3.5, "review_count": 10,
    },
    {
        "name": "さがみ典礼 喜多方斎場",
        "slug": "kitakata-sagami-saijo",
        "venue_type": "private_hall",
        "description": "喜多方市中心部に位置するさがみ典礼の葬儀斎場。喜多方駅から近くアクセスが良好。喜多方市・北塩原村エリアの方に利用されている施設です。",
        "address": "福島県喜多方市町田字下遠田甲978",
        "prefecture_slug": "fukushima", "city_slug": "kitakata",
        "latitude": 37.648, "longitude": 139.872,
        "nearest_station": "JR磐越西線 喜多方駅", "station_walk_minutes": 10,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "駅近"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.0, "review_count": 14,
    },
    {
        "name": "こころ斎苑 喜多方",
        "slug": "kitakata-kokoro",
        "venue_type": "private_hall",
        "description": "喜多方市に位置するたまのやの家族葬ホール。蔵の街・喜多方の中心部に立地し、地域の方に親しまれている施設。少人数での温かいお別れの場を提供しています。",
        "address": "福島県喜多方市字天満前8919",
        "prefecture_slug": "fukushima", "city_slug": "kitakata",
        "latitude": 37.652, "longitude": 139.878,
        "nearest_station": "JR磐越西線 喜多方駅", "station_walk_minutes": 8,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬対応", "駅近", "24時間対応"],
        "operator_name": "株式会社たまのや", "rating_avg": 4.1, "review_count": 11,
    },
    # =============================================
    # 相馬市 2件
    # =============================================
    {
        "name": "相馬市斎場",
        "slug": "soma-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "相馬市が運営する公営火葬場。相馬中村城跡にほど近い場所に位置し、相馬市民は火葬料の優遇措置があります。浜通り北部エリアの方に利用されています。",
        "address": "福島県相馬市石上字南蛯沢214",
        "prefecture_slug": "fukushima", "city_slug": "soma",
        "latitude": 37.795, "longitude": 140.918,
        "nearest_station": "JR常磐線 相馬駅", "station_walk_minutes": 18,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 25,
        "facilities": {"霊安室": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "相馬市", "rating_avg": 3.5, "review_count": 10,
    },
    {
        "name": "セレモニーホール相馬",
        "slug": "soma-ceremony-hall",
        "venue_type": "private_hall",
        "description": "相馬市に位置する地域密着型の葬儀ホール。家族葬から一般葬まで対応可能。浜通り地域で長年の実績を持ち、丁寧なサービスで地域の方に信頼されています。",
        "address": "福島県相馬市中村字北町55-1",
        "prefecture_slug": "fukushima", "city_slug": "soma",
        "latitude": 37.800, "longitude": 140.920,
        "nearest_station": "JR常磐線 相馬駅", "station_walk_minutes": 8,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 520000}],
        "features": ["家族葬対応", "駅近", "地域密着"],
        "operator_name": "セレモニーホール相馬", "rating_avg": 4.0, "review_count": 12,
    },
    # =============================================
    # 二本松市 2件
    # =============================================
    {
        "name": "二本松市斎場",
        "slug": "nihonmatsu-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "二本松市が運営する公営火葬場。二本松城跡にほど近い場所に位置し、菊人形祭りで有名な街にあります。二本松市民は火葬料の優遇措置があります。",
        "address": "福島県二本松市渋川字大壇18",
        "prefecture_slug": "fukushima", "city_slug": "nihonmatsu",
        "latitude": 37.590, "longitude": 140.430,
        "nearest_station": "JR東北本線 二本松駅", "station_walk_minutes": 18,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 20,
        "facilities": {"霊安室": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "二本松市", "rating_avg": 3.5, "review_count": 10,
    },
    {
        "name": "さがみ典礼 二本松斎場",
        "slug": "nihonmatsu-sagami-saijo",
        "venue_type": "private_hall",
        "description": "二本松市に位置するさがみ典礼の葬儀斎場。JR二本松駅から車で5分のアクセス。二本松市・本宮市エリアの方に利用されている施設です。",
        "address": "福島県二本松市榎戸1-81-1",
        "prefecture_slug": "fukushima", "city_slug": "nihonmatsu",
        "latitude": 37.585, "longitude": 140.435,
        "nearest_station": "JR東北本線 二本松駅", "station_walk_minutes": 10,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "駅近"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.0, "review_count": 14,
    },
    # =============================================
    # 田村市 1件
    # =============================================
    {
        "name": "田村市斎場",
        "slug": "tamura-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "田村市が運営する公営火葬場。阿武隈高原に位置する自然豊かな環境の施設。田村市民は火葬料の優遇措置があります。",
        "address": "福島県田村市船引町船引字南元町15",
        "prefecture_slug": "fukushima", "city_slug": "tamura",
        "latitude": 37.440, "longitude": 140.565,
        "nearest_station": "JR磐越東線 船引駅", "station_walk_minutes": 15,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": True, "parking_count": 20,
        "facilities": {"霊安室": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "田村市", "rating_avg": 3.5, "review_count": 8,
    },
    # =============================================
    # 南相馬市 2件
    # =============================================
    {
        "name": "南相馬市斎場",
        "slug": "minamisoma-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "南相馬市が運営する公営火葬場。相馬野馬追で有名な南相馬市に位置し、市民は火葬料の優遇措置があります。原ノ町駅からアクセス可能です。",
        "address": "福島県南相馬市原町区大木戸字西原1-1",
        "prefecture_slug": "fukushima", "city_slug": "minamisoma",
        "latitude": 37.640, "longitude": 140.960,
        "nearest_station": "JR常磐線 原ノ町駅", "station_walk_minutes": 20,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 25,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "南相馬市", "rating_avg": 3.5, "review_count": 12,
    },
    {
        "name": "さがみ典礼 原町斎場",
        "slug": "minamisoma-sagami-haramachi",
        "venue_type": "private_hall",
        "description": "南相馬市原町区に位置するさがみ典礼の葬儀斎場。JR原ノ町駅から近くアクセスが良好。南相馬市エリアの方に利用されている施設です。",
        "address": "福島県南相馬市原町区二見町1-80-1",
        "prefecture_slug": "fukushima", "city_slug": "minamisoma",
        "latitude": 37.637, "longitude": 140.965,
        "nearest_station": "JR常磐線 原ノ町駅", "station_walk_minutes": 8,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "駅近"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.0, "review_count": 14,
    },
    # =============================================
    # 伊達市 2件
    # =============================================
    {
        "name": "伊達市斎場",
        "slug": "date-fukushima-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "伊達市が運営する公営火葬場。伊達政宗ゆかりの地に位置する施設。伊達市民は火葬料の優遇措置があります。",
        "address": "福島県伊達市保原町大字上保原字中ノ台1-10",
        "prefecture_slug": "fukushima", "city_slug": "date-fukushima",
        "latitude": 37.825, "longitude": 140.530,
        "nearest_station": "阿武隈急行 保原駅", "station_walk_minutes": 15,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 20,
        "facilities": {"霊安室": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "伊達市", "rating_avg": 3.5, "review_count": 10,
    },
    {
        "name": "さがみ典礼 伊達斎場",
        "slug": "date-fukushima-sagami",
        "venue_type": "private_hall",
        "description": "伊達市に位置するさがみ典礼の葬儀斎場。伊達市・桑折町エリアの方に利用されている施設。家族葬から一般葬まで対応可能です。",
        "address": "福島県伊達市前川原75-1",
        "prefecture_slug": "fukushima", "city_slug": "date-fukushima",
        "latitude": 37.822, "longitude": 140.525,
        "nearest_station": "阿武隈急行 伊達駅", "station_walk_minutes": 10,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "駅近"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.0, "review_count": 12,
    },
    # =============================================
    # 本宮市 2件
    # =============================================
    {
        "name": "本宮市斎場",
        "slug": "motomiya-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "本宮市が運営する公営火葬場。安達太良山のふもとに位置する自然豊かな環境の施設。本宮市民は火葬料の優遇措置があります。",
        "address": "福島県本宮市本宮字樋ノ口10",
        "prefecture_slug": "fukushima", "city_slug": "motomiya",
        "latitude": 37.510, "longitude": 140.395,
        "nearest_station": "JR東北本線 本宮駅", "station_walk_minutes": 15,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": True, "parking_count": 15,
        "facilities": {"霊安室": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "本宮市", "rating_avg": 3.5, "review_count": 8,
    },
    {
        "name": "さがみ典礼 本宮斎場",
        "slug": "motomiya-sagami-saijo",
        "venue_type": "private_hall",
        "description": "本宮市に位置するさがみ典礼の葬儀斎場。JR本宮駅から車で5分のアクセス。本宮市・大玉村エリアの方に利用されている施設です。",
        "address": "福島県本宮市本宮字舘ノ越190",
        "prefecture_slug": "fukushima", "city_slug": "motomiya",
        "latitude": 37.512, "longitude": 140.400,
        "nearest_station": "JR東北本線 本宮駅", "station_walk_minutes": 10,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "駅近"],
        "operator_name": "アルファクラブ株式会社", "rating_avg": 4.0, "review_count": 10,
    },
]

def insert_batch(batch, batch_num):
    data_json = json.dumps(batch, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(SUPABASE_URL, data=data_json, headers=HEADERS, method="POST")
    try:
        with urllib.request.urlopen(req) as resp:
            print(f"  バッチ{batch_num}: {resp.status} — {len(batch)}件投入成功")
            return True
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"  バッチ{batch_num}: エラー {e.code} — {body}")
        return False

def main():
    BATCH_SIZE = 10
    total = len(venues)
    success = 0
    print(f"福島県パート2: 合計{total}件を投入開始")
    for i in range(0, total, BATCH_SIZE):
        batch = venues[i:i+BATCH_SIZE]
        batch_num = i // BATCH_SIZE + 1
        if insert_batch(batch, batch_num):
            success += len(batch)
        time.sleep(1)
    print(f"\n完了: {success}/{total}件 投入成功")

if __name__ == "__main__":
    main()
