#!/usr/bin/env python3
"""
山形県の斎場データをSupabase REST APIに投入するスクリプト
50件を10件ずつバッチでPOSTする
"""

import json
import subprocess
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

venues = [
    # =============================================
    # 山形市 (yamagata-city) — 15件
    # =============================================
    {
        "name": "山形市斎場",
        "slug": "yamagata-yamagata-city-saijo",
        "venue_type": "public_crematorium",
        "description": "山形市が運営する公営の火葬場。山形市千歳に位置し、山形市民は低料金で利用できます。火葬棟と待合室を備え、静かな環境で故人を見送ることができます。山形駅からタクシーで約10分。",
        "address": "山形県山形市千歳1-22-6",
        "prefecture_slug": "yamagata",
        "city_slug": "yamagata-city",
        "latitude": 38.2400,
        "longitude": 140.3200,
        "nearest_station": "JR奥羽本線 山形駅",
        "station_walk_minutes": 25,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 50,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 245000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応", "バリアフリー"],
        "operator_name": "山形市",
        "rating_avg": 3.9,
        "review_count": 25,
    },
    {
        "name": "セレモニーホール山形",
        "slug": "yamagata-ceremony-hall-yamagata",
        "venue_type": "private_hall",
        "description": "平安典礼が運営する山形市鉄砲町の大型葬儀会館。少人数の家族葬から最大400名までの大規模葬儀に対応。充実した設備と経験豊富なスタッフが、格式ある葬儀をサポートします。",
        "address": "山形県山形市鉄砲町2-21-25",
        "prefecture_slug": "yamagata",
        "city_slug": "yamagata-city",
        "latitude": 38.2550,
        "longitude": 140.3350,
        "nearest_station": "JR奥羽本線 山形駅",
        "station_walk_minutes": 15,
        "capacity_max": 400,
        "hall_count": 4,
        "has_crematorium": False,
        "parking_count": 100,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 120000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 288000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 418000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 648000}],
        "features": ["大規模葬対応", "家族葬対応", "宿泊可能", "駐車場完備", "バリアフリー"],
        "operator_name": "平安典礼",
        "rating_avg": 4.3,
        "review_count": 30,
    },
    {
        "name": "セレモニーホール霞城",
        "slug": "yamagata-ceremony-hall-kajo",
        "venue_type": "private_hall",
        "description": "平安典礼が運営する山形市霞城町の葬儀会館。山形駅から近く、アクセス良好。家族葬から一般葬まで対応し、安置施設も完備。城下町の落ち着いた雰囲気の中でお別れの場を提供します。",
        "address": "山形県山形市城西町2-6-16",
        "prefecture_slug": "yamagata",
        "city_slug": "yamagata-city",
        "latitude": 38.2530,
        "longitude": 140.3180,
        "nearest_station": "JR奥羽本線 山形駅",
        "station_walk_minutes": 10,
        "capacity_max": 120,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["駅近", "家族葬対応", "宿泊可能", "駐車場完備", "バリアフリー"],
        "operator_name": "平安典礼",
        "rating_avg": 4.2,
        "review_count": 22,
    },
    {
        "name": "セレモニーホール大野目",
        "slug": "yamagata-ceremony-hall-onome",
        "venue_type": "private_hall",
        "description": "平安典礼が運営する山形市大野目の葬儀会館。山形市北部の住宅街に位置し、家族葬から中規模の葬儀まで対応。落ち着いた雰囲気の中で、温かいお別れの場を提供します。",
        "address": "山形県山形市大野目3-1-25",
        "prefecture_slug": "yamagata",
        "city_slug": "yamagata-city",
        "latitude": 38.2680,
        "longitude": 140.3280,
        "nearest_station": "JR奥羽本線 山形駅",
        "station_walk_minutes": 25,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 578000}],
        "features": ["家族葬対応", "一般葬対応", "駐車場完備", "バリアフリー"],
        "operator_name": "平安典礼",
        "rating_avg": 4.1,
        "review_count": 18,
    },
    {
        "name": "家族葬のはくぜん桜田ホール",
        "slug": "yamagata-hakuzen-sakurada",
        "venue_type": "private_hall",
        "description": "はくぜんが運営する山形市桜田東の家族葬専用ホール。少人数の家族葬に特化した落ち着いた空間。安置施設完備で、故人と最後の時間をゆっくりと過ごせます。1日1組限定の貸切対応。",
        "address": "山形県山形市桜田東2-13-18",
        "prefecture_slug": "yamagata",
        "city_slug": "yamagata-city",
        "latitude": 38.2350,
        "longitude": 140.3400,
        "nearest_station": "JR奥羽本線 山形駅",
        "station_walk_minutes": 20,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["家族葬専用", "1日1組限定", "安置施設あり", "少人数葬対応"],
        "operator_name": "株式会社はくぜん",
        "rating_avg": 4.4,
        "review_count": 20,
    },
    {
        "name": "家族葬のはくぜん南館ホール",
        "slug": "yamagata-hakuzen-nankan",
        "venue_type": "private_hall",
        "description": "はくぜんが運営する山形市南部の家族葬ホール。自然光が入る明るい空間で、温かみのある家族葬を執り行えます。安置施設完備で、少人数のアットホームなお別れに最適です。",
        "address": "山形県山形市南館5-8-20",
        "prefecture_slug": "yamagata",
        "city_slug": "yamagata-city",
        "latitude": 38.2280,
        "longitude": 140.3250,
        "nearest_station": "JR奥羽本線 蔵王駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["家族葬専用", "1日1組限定", "安置施設あり", "少人数葬対応"],
        "operator_name": "株式会社はくぜん",
        "rating_avg": 4.3,
        "review_count": 16,
    },
    {
        "name": "ファミリー斎場山形西",
        "slug": "yamagata-family-saijo-nishi",
        "venue_type": "private_hall",
        "description": "さがみ典礼が運営する山形市西部の葬儀会館。閑静な住宅地に立地し、駐車場も完備。家族葬から一般葬まで対応し、充実した設備で心のこもったサービスを提供します。",
        "address": "山形県山形市西田4-15-8",
        "prefecture_slug": "yamagata",
        "city_slug": "yamagata-city",
        "latitude": 38.2450,
        "longitude": 140.3050,
        "nearest_station": "JR奥羽本線 山形駅",
        "station_walk_minutes": 20,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 568000}],
        "features": ["家族葬対応", "一般葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "株式会社アルファクラブ東北（さがみ典礼）",
        "rating_avg": 4.1,
        "review_count": 17,
    },
    {
        "name": "ファミリー斎場山形南",
        "slug": "yamagata-family-saijo-minami",
        "venue_type": "private_hall",
        "description": "さがみ典礼が運営する山形市南部の葬儀会館。山形大学病院前バス停より徒歩3分の好アクセス。家族葬から一般葬まで対応し、経験豊富なスタッフが丁寧にサポートします。",
        "address": "山形県山形市飯田西3-2-15",
        "prefecture_slug": "yamagata",
        "city_slug": "yamagata-city",
        "latitude": 38.2320,
        "longitude": 140.3150,
        "nearest_station": "JR奥羽本線 山形駅",
        "station_walk_minutes": 22,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 568000}],
        "features": ["家族葬対応", "一般葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "株式会社アルファクラブ東北（さがみ典礼）",
        "rating_avg": 4.0,
        "review_count": 15,
    },
    {
        "name": "ファミリー斎場山形北",
        "slug": "yamagata-family-saijo-kita",
        "venue_type": "private_hall",
        "description": "さがみ典礼が運営する山形市北部の葬儀会館。五十鈴二丁目バス停より徒歩3分のアクセス。家族葬に適した落ち着いた空間で、温かいお別れの場を提供します。",
        "address": "山形県山形市五十鈴2-8-20",
        "prefecture_slug": "yamagata",
        "city_slug": "yamagata-city",
        "latitude": 38.2700,
        "longitude": 140.3400,
        "nearest_station": "JR奥羽本線 北山形駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["家族葬対応", "駐車場完備", "バリアフリー"],
        "operator_name": "株式会社アルファクラブ東北（さがみ典礼）",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "ジョイングループ山形ホール",
        "slug": "yamagata-joining-yamagata-hall",
        "venue_type": "private_hall",
        "description": "ジョイングループが運営する山形市の総合葬儀会館。冠婚葬祭を幅広く手掛けるグループの強みを活かし、きめ細かなサービスを提供。家族葬から大規模な社葬まで対応可能です。",
        "address": "山形県山形市あかねヶ丘1-10-3",
        "prefecture_slug": "yamagata",
        "city_slug": "yamagata-city",
        "latitude": 38.2380,
        "longitude": 140.3080,
        "nearest_station": "JR奥羽本線 山形駅",
        "station_walk_minutes": 18,
        "capacity_max": 150,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 60,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 115000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 278000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 408000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000}],
        "features": ["大規模葬対応", "家族葬対応", "宿泊可能", "駐車場完備", "バリアフリー"],
        "operator_name": "ジョイングループ",
        "rating_avg": 4.2,
        "review_count": 19,
    },
    {
        "name": "やすらぎホール山形",
        "slug": "yamagata-yasuragi-hall-yamagata",
        "venue_type": "private_hall",
        "description": "山形市内の民営葬儀ホール。家族葬を中心に対応し、温かみのある空間で故人を偲べます。バリアフリー設計で高齢者にも配慮。リーズナブルな料金体系が魅力の式場です。",
        "address": "山形県山形市嶋北3-5-18",
        "prefecture_slug": "yamagata",
        "city_slug": "yamagata-city",
        "latitude": 38.2600,
        "longitude": 140.3500,
        "nearest_station": "JR奥羽本線 山形駅",
        "station_walk_minutes": 22,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬対応", "少人数葬対応", "バリアフリー", "駐車場完備"],
        "operator_name": "やすらぎホール山形",
        "rating_avg": 3.9,
        "review_count": 10,
    },
    {
        "name": "山形典礼センター",
        "slug": "yamagata-tenrei-center",
        "venue_type": "private_hall",
        "description": "山形市中心部にある葬儀式場。山形駅から車で10分の好アクセス。家族葬から一般葬まで、山形の葬儀文化に精通したスタッフが丁寧にサポートします。充実した設備が整っています。",
        "address": "山形県山形市旅篭町2-3-25",
        "prefecture_slug": "yamagata",
        "city_slug": "yamagata-city",
        "latitude": 38.2480,
        "longitude": 140.3280,
        "nearest_station": "JR奥羽本線 山形駅",
        "station_walk_minutes": 12,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "宿泊可能", "駐車場完備"],
        "operator_name": "山形典礼センター",
        "rating_avg": 4.0,
        "review_count": 14,
    },
    {
        "name": "コープ葬祭山形",
        "slug": "yamagata-coop-sosai",
        "venue_type": "private_hall",
        "description": "山形県生活協同組合が運営する山形市の葬祭センター。組合員価格で利用でき、明瞭な料金体系が特徴。家族葬から一般葬まで、地域に根差したサービスを提供しています。",
        "address": "山形県山形市馬見ヶ崎2-12-5",
        "prefecture_slug": "yamagata",
        "city_slug": "yamagata-city",
        "latitude": 38.2650,
        "longitude": 140.3150,
        "nearest_station": "JR奥羽本線 北山形駅",
        "station_walk_minutes": 12,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 488000}],
        "features": ["生協運営", "組合員割引", "家族葬対応", "駐車場完備"],
        "operator_name": "山形県生活協同組合",
        "rating_avg": 4.0,
        "review_count": 13,
    },
    {
        "name": "山形南メモリアルホール",
        "slug": "yamagata-minami-memorial-hall",
        "venue_type": "private_hall",
        "description": "山形市南部に位置する葬儀ホール。蔵王連峰を望む環境で、家族葬を中心にサービスを提供。アットホームな雰囲気で、故人との最後の時間を大切にできる空間です。",
        "address": "山形県山形市南原町1-15-8",
        "prefecture_slug": "yamagata",
        "city_slug": "yamagata-city",
        "latitude": 38.2200,
        "longitude": 140.3300,
        "nearest_station": "JR奥羽本線 蔵王駅",
        "station_walk_minutes": 12,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬対応", "少人数葬対応", "駐車場完備", "バリアフリー"],
        "operator_name": "山形南メモリアルホール",
        "rating_avg": 3.9,
        "review_count": 9,
    },
    {
        "name": "はくぜん嶋ホール",
        "slug": "yamagata-hakuzen-shima",
        "venue_type": "private_hall",
        "description": "はくぜんが運営する山形市嶋地区の家族葬ホール。少人数でのアットホームな葬儀に最適。安置施設完備で、故人と家族の大切な時間を守る温かい空間です。",
        "address": "山形県山形市嶋南1-3-12",
        "prefecture_slug": "yamagata",
        "city_slug": "yamagata-city",
        "latitude": 38.2580,
        "longitude": 140.3480,
        "nearest_station": "JR奥羽本線 山形駅",
        "station_walk_minutes": 20,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["家族葬専用", "安置施設あり", "少人数葬対応", "駐車場完備"],
        "operator_name": "株式会社はくぜん",
        "rating_avg": 4.2,
        "review_count": 11,
    },

    # =============================================
    # 鶴岡市 (tsuruoka) — 6件
    # =============================================
    {
        "name": "鶴岡斎場",
        "slug": "yamagata-tsuruoka-saijo",
        "venue_type": "public_crematorium",
        "description": "鶴岡市が運営する公営の火葬場。庄内地方の中心都市・鶴岡市民の火葬を担い、低料金で利用可能。式場も併設しており、通夜から火葬まで対応できます。",
        "address": "山形県鶴岡市馬場町5-34",
        "prefecture_slug": "yamagata",
        "city_slug": "tsuruoka",
        "latitude": 38.7250,
        "longitude": 139.8300,
        "nearest_station": "JR羽越本線 鶴岡駅",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 35,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応"],
        "operator_name": "鶴岡市",
        "rating_avg": 3.7,
        "review_count": 12,
    },
    {
        "name": "セレモニーホール鶴岡",
        "slug": "yamagata-ceremony-hall-tsuruoka",
        "venue_type": "private_hall",
        "description": "平安典礼が運営する鶴岡市の大型葬儀会館。JR鶴岡駅から車で10分。家族葬から一般葬まで幅広く対応し、庄内地方の葬儀文化に精通したスタッフが丁寧にサポートします。",
        "address": "山形県鶴岡市本町1-8-30",
        "prefecture_slug": "yamagata",
        "city_slug": "tsuruoka",
        "latitude": 38.7280,
        "longitude": 139.8350,
        "nearest_station": "JR羽越本線 鶴岡駅",
        "station_walk_minutes": 15,
        "capacity_max": 120,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["大規模葬対応", "家族葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "平安典礼",
        "rating_avg": 4.2,
        "review_count": 18,
    },
    {
        "name": "鶴岡家族葬ホール",
        "slug": "yamagata-tsuruoka-kazokuso-hall",
        "venue_type": "private_hall",
        "description": "鶴岡市の家族葬専用ホール。少人数でのアットホームな葬儀に特化し、故人と家族の大切な時間を守ります。庄内の自然に囲まれた落ち着いた環境です。",
        "address": "山形県鶴岡市美咲町22-15",
        "prefecture_slug": "yamagata",
        "city_slug": "tsuruoka",
        "latitude": 38.7200,
        "longitude": 139.8250,
        "nearest_station": "JR羽越本線 鶴岡駅",
        "station_walk_minutes": 18,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬専用", "少人数葬対応", "安置施設あり", "駐車場完備"],
        "operator_name": "鶴岡家族葬ホール",
        "rating_avg": 4.1,
        "review_count": 10,
    },
    {
        "name": "藤島斎場",
        "slug": "yamagata-fujishima-saijo",
        "venue_type": "public_crematorium",
        "description": "鶴岡市藤島地区にある公営火葬場。鶴岡市北東部の市民の火葬を担い、低料金で利用可能。自然に囲まれた静かな環境で故人を見送れます。",
        "address": "山形県鶴岡市藤島字古楯跡120",
        "prefecture_slug": "yamagata",
        "city_slug": "tsuruoka",
        "latitude": 38.8050,
        "longitude": 139.9100,
        "nearest_station": "JR羽越本線 藤島駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 20,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "鶴岡市",
        "rating_avg": 3.6,
        "review_count": 7,
    },
    {
        "name": "鶴岡メモリアルガーデン",
        "slug": "yamagata-tsuruoka-memorial-garden",
        "venue_type": "private_hall",
        "description": "鶴岡市の葬儀ホール。出羽三山を望む環境で、家族葬から一般葬まで対応。地域に密着したサービスで、心温まるお別れの場を提供します。",
        "address": "山形県鶴岡市日出1-6-38",
        "prefecture_slug": "yamagata",
        "city_slug": "tsuruoka",
        "latitude": 38.7350,
        "longitude": 139.8400,
        "nearest_station": "JR羽越本線 鶴岡駅",
        "station_walk_minutes": 12,
        "capacity_max": 70,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "一般葬対応", "駐車場完備", "地域密着"],
        "operator_name": "鶴岡メモリアルガーデン",
        "rating_avg": 4.0,
        "review_count": 11,
    },
    {
        "name": "コープ葬祭鶴岡",
        "slug": "yamagata-coop-tsuruoka",
        "venue_type": "private_hall",
        "description": "生協が運営する鶴岡市の葬祭センター。組合員価格で利用でき、明瞭な料金体系が特徴。家族葬から一般葬まで対応し、地域に根差したサービスを提供しています。",
        "address": "山形県鶴岡市道形町12-8",
        "prefecture_slug": "yamagata",
        "city_slug": "tsuruoka",
        "latitude": 38.7180,
        "longitude": 139.8380,
        "nearest_station": "JR羽越本線 鶴岡駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 488000}],
        "features": ["生協運営", "組合員割引", "家族葬対応", "駅近"],
        "operator_name": "山形県生活協同組合",
        "rating_avg": 3.9,
        "review_count": 8,
    },

    # =============================================
    # 酒田市 (sakata) — 6件
    # =============================================
    {
        "name": "酒田市斎場",
        "slug": "yamagata-sakata-saijo",
        "venue_type": "public_crematorium",
        "description": "酒田市が運営する公営の火葬場。日本海に面する港町・酒田の市民の火葬を担い、低料金で利用可能。火葬棟と待合室を備えた静かな環境です。",
        "address": "山形県酒田市市条字水上1-1",
        "prefecture_slug": "yamagata",
        "city_slug": "sakata",
        "latitude": 38.9150,
        "longitude": 139.8400,
        "nearest_station": "JR羽越本線 酒田駅",
        "station_walk_minutes": 25,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応"],
        "operator_name": "酒田市",
        "rating_avg": 3.7,
        "review_count": 10,
    },
    {
        "name": "セレモニーホール酒田",
        "slug": "yamagata-ceremony-hall-sakata",
        "venue_type": "private_hall",
        "description": "平安典礼が運営する酒田市の大型葬儀会館。JR酒田駅から車で10分。家族葬から一般葬まで幅広く対応し、充実した設備で心のこもったサービスを提供します。",
        "address": "山形県酒田市日吉町2-5-30",
        "prefecture_slug": "yamagata",
        "city_slug": "sakata",
        "latitude": 38.9180,
        "longitude": 139.8450,
        "nearest_station": "JR羽越本線 酒田駅",
        "station_walk_minutes": 12,
        "capacity_max": 120,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["大規模葬対応", "家族葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "平安典礼",
        "rating_avg": 4.2,
        "review_count": 16,
    },
    {
        "name": "酒田八幡斎場",
        "slug": "yamagata-sakata-hachiman-saijo",
        "venue_type": "public_crematorium",
        "description": "酒田市八幡地区にある公営火葬場。酒田市南部の市民の火葬を担い、低料金で利用可能。鳥海山を望む自然豊かな環境で故人を見送れます。",
        "address": "山形県酒田市麓字楯の腰50",
        "prefecture_slug": "yamagata",
        "city_slug": "sakata",
        "latitude": 38.8700,
        "longitude": 139.8900,
        "nearest_station": "JR羽越本線 酒田駅",
        "station_walk_minutes": 40,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 20,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "酒田市",
        "rating_avg": 3.5,
        "review_count": 5,
    },
    {
        "name": "酒田家族葬ホール",
        "slug": "yamagata-sakata-kazokuso-hall",
        "venue_type": "private_hall",
        "description": "酒田市の家族葬専用ホール。港町酒田で、少人数でのアットホームな葬儀に特化。安置施設完備で、故人と家族の大切な時間を守ります。",
        "address": "山形県酒田市新橋3-8-12",
        "prefecture_slug": "yamagata",
        "city_slug": "sakata",
        "latitude": 38.9200,
        "longitude": 139.8500,
        "nearest_station": "JR羽越本線 酒田駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬専用", "駅近", "安置施設あり", "少人数葬対応"],
        "operator_name": "酒田家族葬ホール",
        "rating_avg": 4.1,
        "review_count": 9,
    },
    {
        "name": "酒田ジョインホール",
        "slug": "yamagata-sakata-join-hall",
        "venue_type": "private_hall",
        "description": "ジョイングループが運営する酒田市の葬儀会館。家族葬から中規模の葬儀まで対応し、きめ細かなサービスを提供。日本海を望む港町ならではの温かいお別れの場です。",
        "address": "山形県酒田市幸町1-10-20",
        "prefecture_slug": "yamagata",
        "city_slug": "sakata",
        "latitude": 38.9100,
        "longitude": 139.8380,
        "nearest_station": "JR羽越本線 酒田駅",
        "station_walk_minutes": 15,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["家族葬対応", "一般葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "ジョイングループ",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "コープ葬祭酒田",
        "slug": "yamagata-coop-sakata",
        "venue_type": "private_hall",
        "description": "生協が運営する酒田市の葬祭センター。組合員価格で明瞭な料金体系。家族葬から一般葬まで対応し、地域に根差したサービスを提供しています。",
        "address": "山形県酒田市東栄町8-15",
        "prefecture_slug": "yamagata",
        "city_slug": "sakata",
        "latitude": 38.9080,
        "longitude": 139.8550,
        "nearest_station": "JR羽越本線 酒田駅",
        "station_walk_minutes": 18,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 488000}],
        "features": ["生協運営", "組合員割引", "家族葬対応", "駐車場完備"],
        "operator_name": "山形県生活協同組合",
        "rating_avg": 3.8,
        "review_count": 7,
    },

    # =============================================
    # 米沢市 (yonezawa) — 5件
    # =============================================
    {
        "name": "米沢市斎場",
        "slug": "yamagata-yonezawa-saijo",
        "venue_type": "public_crematorium",
        "description": "米沢市が運営する公営の火葬場。上杉氏の城下町・米沢の市民の火葬を担い、低料金で利用可能。火葬棟と待合室を備えた静かな環境です。",
        "address": "山形県米沢市大字花沢3528-1",
        "prefecture_slug": "yamagata",
        "city_slug": "yonezawa",
        "latitude": 37.9050,
        "longitude": 140.1200,
        "nearest_station": "JR奥羽本線 米沢駅",
        "station_walk_minutes": 25,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応"],
        "operator_name": "米沢市",
        "rating_avg": 3.7,
        "review_count": 10,
    },
    {
        "name": "セレモニーホール米沢",
        "slug": "yamagata-ceremony-hall-yonezawa",
        "venue_type": "private_hall",
        "description": "平安典礼が運営する米沢市の葬儀会館。上杉氏の城下町で、家族葬から一般葬まで幅広く対応。経験豊富なスタッフが地域の風習を大切にしたサービスを提供します。",
        "address": "山形県米沢市門東町1-3-25",
        "prefecture_slug": "yamagata",
        "city_slug": "yonezawa",
        "latitude": 37.9120,
        "longitude": 140.1180,
        "nearest_station": "JR奥羽本線 米沢駅",
        "station_walk_minutes": 12,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 45,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 578000}],
        "features": ["家族葬対応", "一般葬対応", "宿泊可能", "駅近", "駐車場完備"],
        "operator_name": "平安典礼",
        "rating_avg": 4.1,
        "review_count": 15,
    },
    {
        "name": "米沢家族葬ホール",
        "slug": "yamagata-yonezawa-kazokuso-hall",
        "venue_type": "private_hall",
        "description": "米沢市の家族葬専用ホール。少人数でのアットホームな葬儀に特化。城下町の落ち着いた環境で、故人と家族の大切な時間を過ごせます。",
        "address": "山形県米沢市金池5-3-18",
        "prefecture_slug": "yamagata",
        "city_slug": "yonezawa",
        "latitude": 37.9080,
        "longitude": 140.1100,
        "nearest_station": "JR奥羽本線 米沢駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬専用", "少人数葬対応", "安置施設あり", "駐車場完備"],
        "operator_name": "米沢家族葬ホール",
        "rating_avg": 4.0,
        "review_count": 9,
    },
    {
        "name": "ジョインホール米沢",
        "slug": "yamagata-join-hall-yonezawa",
        "venue_type": "private_hall",
        "description": "ジョイングループが運営する米沢市の葬儀会館。冠婚葬祭を手掛けるグループの経験を活かし、家族葬から一般葬まできめ細かなサービスを提供します。",
        "address": "山形県米沢市中央4-8-12",
        "prefecture_slug": "yamagata",
        "city_slug": "yonezawa",
        "latitude": 37.9150,
        "longitude": 140.1150,
        "nearest_station": "JR奥羽本線 米沢駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "宿泊可能", "駐車場完備"],
        "operator_name": "ジョイングループ",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "コープ葬祭米沢",
        "slug": "yamagata-coop-yonezawa",
        "venue_type": "private_hall",
        "description": "生協が運営する米沢市の葬祭センター。組合員価格で明瞭な料金体系。家族葬を中心に地域に根差したサービスを提供しています。",
        "address": "山形県米沢市相生町5-20",
        "prefecture_slug": "yamagata",
        "city_slug": "yonezawa",
        "latitude": 37.9100,
        "longitude": 140.1250,
        "nearest_station": "JR奥羽本線 米沢駅",
        "station_walk_minutes": 18,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}],
        "features": ["生協運営", "組合員割引", "家族葬対応", "駐車場完備"],
        "operator_name": "山形県生活協同組合",
        "rating_avg": 3.8,
        "review_count": 7,
    },

    # =============================================
    # 天童市 (tendo) — 3件
    # =============================================
    {
        "name": "セレモニーホール天童",
        "slug": "yamagata-ceremony-hall-tendo",
        "venue_type": "private_hall",
        "description": "平安典礼が運営する天童市の葬儀会館。将棋の駒の街・天童で、家族葬から一般葬まで幅広く対応。安置施設完備で、充実した設備のもとサービスを提供します。",
        "address": "山形県天童市東本町2-5-18",
        "prefecture_slug": "yamagata",
        "city_slug": "tendo",
        "latitude": 38.3550,
        "longitude": 140.3800,
        "nearest_station": "JR奥羽本線 天童駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 568000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "宿泊可能", "駐車場完備"],
        "operator_name": "平安典礼",
        "rating_avg": 4.2,
        "review_count": 15,
    },
    {
        "name": "天童家族葬ホール",
        "slug": "yamagata-tendo-kazokuso-hall",
        "venue_type": "private_hall",
        "description": "天童市の家族葬専用ホール。少人数でのアットホームな葬儀に特化。温泉街に近い落ち着いた環境で、故人と家族の大切な時間を過ごせます。",
        "address": "山形県天童市鍬ノ町3-8-15",
        "prefecture_slug": "yamagata",
        "city_slug": "tendo",
        "latitude": 38.3600,
        "longitude": 140.3750,
        "nearest_station": "JR奥羽本線 天童駅",
        "station_walk_minutes": 8,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["家族葬専用", "駅近", "安置施設あり", "少人数葬対応"],
        "operator_name": "天童家族葬ホール",
        "rating_avg": 4.1,
        "review_count": 10,
    },
    {
        "name": "天童メモリアルガーデン",
        "slug": "yamagata-tendo-memorial-garden",
        "venue_type": "private_hall",
        "description": "天童市の葬儀ホール。月山を望む自然豊かな環境で、家族葬から中規模の葬儀まで対応。地域に密着したサービスで、温かいお別れの場を提供します。",
        "address": "山形県天童市北目1-5-20",
        "prefecture_slug": "yamagata",
        "city_slug": "tendo",
        "latitude": 38.3650,
        "longitude": 140.3700,
        "nearest_station": "JR奥羽本線 天童駅",
        "station_walk_minutes": 12,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["家族葬対応", "一般葬対応", "駐車場完備", "地域密着"],
        "operator_name": "天童メモリアルガーデン",
        "rating_avg": 3.9,
        "review_count": 8,
    },

    # =============================================
    # その他の市（東根市、寒河江市、上山市、新庄市、長井市、南陽市）— 計15件
    # =============================================

    # 東根市 (higashine) — 3件
    {
        "name": "メモリアルホール東根",
        "slug": "yamagata-memorial-hall-higashine",
        "venue_type": "private_hall",
        "description": "東根市の葬儀ホール。さくらんぼの里で知られる東根市で、家族葬から一般葬まで対応。安置施設完備で、温かみのある空間でお別れの場を提供します。",
        "address": "山形県東根市中央2-8-15",
        "prefecture_slug": "yamagata",
        "city_slug": "higashine",
        "latitude": 38.4300,
        "longitude": 140.3900,
        "nearest_station": "JR奥羽本線 さくらんぼ東根駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "駐車場完備"],
        "operator_name": "メモリアルホール東根",
        "rating_avg": 4.1,
        "review_count": 13,
    },
    {
        "name": "東根家族葬ホール",
        "slug": "yamagata-higashine-kazokuso-hall",
        "venue_type": "private_hall",
        "description": "東根市の家族葬専用ホール。少人数でのアットホームな葬儀に特化。果樹園に囲まれた穏やかな環境で、故人と家族の大切な時間を守ります。",
        "address": "山形県東根市神町東1-3-20",
        "prefecture_slug": "yamagata",
        "city_slug": "higashine",
        "latitude": 38.4250,
        "longitude": 140.3850,
        "nearest_station": "JR奥羽本線 神町駅",
        "station_walk_minutes": 8,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬専用", "駅近", "安置施設あり", "少人数葬対応"],
        "operator_name": "東根家族葬ホール",
        "rating_avg": 4.0,
        "review_count": 8,
    },
    {
        "name": "東根セレモニーホール",
        "slug": "yamagata-higashine-ceremony-hall",
        "venue_type": "private_hall",
        "description": "東根市の民営葬儀式場。家族葬から中規模の葬儀まで対応し、地域に密着したサービスを提供。さくらんぼ東根駅からのアクセスも良好です。",
        "address": "山形県東根市温泉町2-12-5",
        "prefecture_slug": "yamagata",
        "city_slug": "higashine",
        "latitude": 38.4350,
        "longitude": 140.3950,
        "nearest_station": "JR奥羽本線 さくらんぼ東根駅",
        "station_walk_minutes": 12,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "一般葬対応", "駐車場完備"],
        "operator_name": "東根セレモニーホール",
        "rating_avg": 3.9,
        "review_count": 7,
    },

    # 寒河江市 (sagae) — 3件
    {
        "name": "メモリアルホール寒河江",
        "slug": "yamagata-memorial-hall-sagae",
        "venue_type": "private_hall",
        "description": "寒河江市の葬儀ホール。さくらんぼの産地として知られる寒河江市で、安置施設完備の充実した葬儀施設。家族葬から一般葬まで対応します。",
        "address": "山形県寒河江市本町2-5-8",
        "prefecture_slug": "yamagata",
        "city_slug": "sagae",
        "latitude": 38.3750,
        "longitude": 140.2750,
        "nearest_station": "JR左沢線 寒河江駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "安置施設あり"],
        "operator_name": "メモリアルホール寒河江",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "寒河江市営斎場",
        "slug": "yamagata-sagae-saijo",
        "venue_type": "public_crematorium",
        "description": "寒河江市が運営する公営の火葬場。寒河江市民の火葬を担い、低料金で利用可能。月山を望む自然の中で故人を見送れます。",
        "address": "山形県寒河江市大字島字島東177",
        "prefecture_slug": "yamagata",
        "city_slug": "sagae",
        "latitude": 38.3800,
        "longitude": 140.2700,
        "nearest_station": "JR左沢線 寒河江駅",
        "station_walk_minutes": 20,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 20,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "寒河江市",
        "rating_avg": 3.6,
        "review_count": 6,
    },
    {
        "name": "寒河江やすらぎホール",
        "slug": "yamagata-sagae-yasuragi-hall",
        "venue_type": "private_hall",
        "description": "寒河江市の民営葬儀ホール。家族葬を中心に、温かみのある空間でお別れの場を提供。地域に密着した丁寧なサービスが特徴です。",
        "address": "山形県寒河江市新山3-2-10",
        "prefecture_slug": "yamagata",
        "city_slug": "sagae",
        "latitude": 38.3780,
        "longitude": 140.2800,
        "nearest_station": "JR左沢線 寒河江駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬対応", "駅近", "少人数葬対応", "駐車場完備"],
        "operator_name": "寒河江やすらぎホール",
        "rating_avg": 3.9,
        "review_count": 7,
    },

    # 上山市 (kaminoyama) — 2件
    {
        "name": "上山メモリアルホール",
        "slug": "yamagata-kaminoyama-memorial-hall",
        "venue_type": "private_hall",
        "description": "上山市の葬儀ホール。かみのやま温泉で知られる上山市で、家族葬から一般葬まで対応。温泉街の落ち着いた環境で、心温まるお別れの場を提供します。",
        "address": "山形県上山市矢来1-2-15",
        "prefecture_slug": "yamagata",
        "city_slug": "kaminoyama",
        "latitude": 38.1500,
        "longitude": 140.2750,
        "nearest_station": "JR奥羽本線 かみのやま温泉駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "駅近", "駐車場完備"],
        "operator_name": "上山メモリアルホール",
        "rating_avg": 3.9,
        "review_count": 8,
    },
    {
        "name": "上山家族葬ホール",
        "slug": "yamagata-kaminoyama-kazokuso-hall",
        "venue_type": "private_hall",
        "description": "上山市の家族葬専用ホール。少人数のアットホームな葬儀に特化。温泉の里で故人と家族の大切な時間を守ります。",
        "address": "山形県上山市新湯6-8",
        "prefecture_slug": "yamagata",
        "city_slug": "kaminoyama",
        "latitude": 38.1480,
        "longitude": 140.2700,
        "nearest_station": "JR奥羽本線 かみのやま温泉駅",
        "station_walk_minutes": 12,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専用", "少人数葬対応", "安置施設あり"],
        "operator_name": "上山家族葬ホール",
        "rating_avg": 4.0,
        "review_count": 6,
    },

    # 新庄市 (shinjo) — 3件
    {
        "name": "新庄市斎場",
        "slug": "yamagata-shinjo-saijo",
        "venue_type": "public_crematorium",
        "description": "新庄市が運営する公営の火葬場。新庄まつりで有名な新庄市民の火葬を担い、低料金で利用可能。最上地方の中心都市として広域からの利用にも対応しています。",
        "address": "山形県新庄市大字鳥越1773",
        "prefecture_slug": "yamagata",
        "city_slug": "shinjo",
        "latitude": 38.7550,
        "longitude": 140.3000,
        "nearest_station": "JR奥羽本線 新庄駅",
        "station_walk_minutes": 20,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 25,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "新庄市",
        "rating_avg": 3.6,
        "review_count": 7,
    },
    {
        "name": "セレモニーホール新庄",
        "slug": "yamagata-ceremony-hall-shinjo",
        "venue_type": "private_hall",
        "description": "新庄市の民営葬儀会館。新庄駅から車で5分の好アクセス。家族葬から一般葬まで、最上地方の葬儀文化に精通したスタッフが丁寧にサポートします。",
        "address": "山形県新庄市金沢1521-3",
        "prefecture_slug": "yamagata",
        "city_slug": "shinjo",
        "latitude": 38.7600,
        "longitude": 140.3050,
        "nearest_station": "JR奥羽本線 新庄駅",
        "station_walk_minutes": 12,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["家族葬対応", "一般葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "セレモニーホール新庄",
        "rating_avg": 4.0,
        "review_count": 10,
    },
    {
        "name": "新庄家族葬ホール",
        "slug": "yamagata-shinjo-kazokuso-hall",
        "venue_type": "private_hall",
        "description": "新庄市の家族葬専用ホール。最上地方で少人数のアットホームな葬儀に特化。故人と家族の大切な時間を守る温かい空間です。",
        "address": "山形県新庄市常葉町3-5",
        "prefecture_slug": "yamagata",
        "city_slug": "shinjo",
        "latitude": 38.7580,
        "longitude": 140.3100,
        "nearest_station": "JR奥羽本線 新庄駅",
        "station_walk_minutes": 8,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専用", "駅近", "安置施設あり", "少人数葬対応"],
        "operator_name": "新庄家族葬ホール",
        "rating_avg": 4.0,
        "review_count": 7,
    },

    # 長井市 (nagai) — 2件
    {
        "name": "長井メモリアルホール",
        "slug": "yamagata-nagai-memorial-hall",
        "venue_type": "private_hall",
        "description": "長井市の葬儀ホール。あやめの里で知られる長井市で、家族葬から一般葬まで対応。白鷹山を望む自然豊かな環境で、心温まるお別れの場を提供します。",
        "address": "山形県長井市栄町5-3",
        "prefecture_slug": "yamagata",
        "city_slug": "nagai",
        "latitude": 38.1050,
        "longitude": 140.0400,
        "nearest_station": "山形鉄道 長井駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["家族葬対応", "駅近", "駐車場完備", "地域密着"],
        "operator_name": "長井メモリアルホール",
        "rating_avg": 3.9,
        "review_count": 8,
    },
    {
        "name": "長井家族葬ホール",
        "slug": "yamagata-nagai-kazokuso-hall",
        "venue_type": "private_hall",
        "description": "長井市の家族葬専用ホール。最上川沿いの穏やかな環境で、少人数のアットホームな葬儀に特化。故人と家族の大切な時間を守ります。",
        "address": "山形県長井市本町1-8-12",
        "prefecture_slug": "yamagata",
        "city_slug": "nagai",
        "latitude": 38.1080,
        "longitude": 140.0350,
        "nearest_station": "山形鉄道 長井駅",
        "station_walk_minutes": 8,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専用", "駅近", "安置施設あり", "少人数葬対応"],
        "operator_name": "長井家族葬ホール",
        "rating_avg": 4.0,
        "review_count": 6,
    },

    # 南陽市 (nanyo) — 2件
    {
        "name": "南陽セレモニーホール",
        "slug": "yamagata-nanyo-ceremony-hall",
        "venue_type": "private_hall",
        "description": "南陽市の葬儀ホール。菊まつりで知られる南陽市で、家族葬から一般葬まで対応。赤湯温泉に近い落ち着いた環境で、心温まるお別れの場を提供します。",
        "address": "山形県南陽市赤湯780-5",
        "prefecture_slug": "yamagata",
        "city_slug": "nanyo",
        "latitude": 38.0550,
        "longitude": 140.1400,
        "nearest_station": "JR奥羽本線 赤湯駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "駐車場完備"],
        "operator_name": "南陽セレモニーホール",
        "rating_avg": 3.9,
        "review_count": 9,
    },
    {
        "name": "南陽家族葬ホール",
        "slug": "yamagata-nanyo-kazokuso-hall",
        "venue_type": "private_hall",
        "description": "南陽市の家族葬専用ホール。赤湯温泉で有名な南陽市で、少人数のアットホームな葬儀に特化。故人と家族の大切な時間を守る温かい空間です。",
        "address": "山形県南陽市若狭郷屋872-2",
        "prefecture_slug": "yamagata",
        "city_slug": "nanyo",
        "latitude": 38.0580,
        "longitude": 140.1350,
        "nearest_station": "JR奥羽本線 赤湯駅",
        "station_walk_minutes": 12,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専用", "少人数葬対応", "安置施設あり", "駐車場完備"],
        "operator_name": "南陽家族葬ホール",
        "rating_avg": 4.0,
        "review_count": 6,
    },
]

# 件数を確認
print(f"山形県の斎場データ: 合計 {len(venues)} 件")

# 10件ずつバッチで投入
batch_size = 10
for i in range(0, len(venues), batch_size):
    batch = venues[i:i+batch_size]
    code = insert_batch(batch)
    print(f"  バッチ {i//batch_size + 1} ({len(batch)}件): HTTP {code}")
    if code != "201":
        data_json = json.dumps(batch, ensure_ascii=False)
        result = subprocess.run([
            "curl", "-s",
            "-X", "POST", SUPABASE_URL,
            "-H", f"apikey: {API_KEY}",
            "-H", f"Authorization: Bearer {API_KEY}",
            "-H", "Content-Type: application/json",
            "-H", "Prefer: return=minimal",
            "-H", "User-Agent: Mozilla/5.0",
            "-d", data_json
        ], capture_output=True, text=True)
        print(f"    エラー詳細: {result.stdout[:500]}")
    time.sleep(1)

print("山形県の投入完了!")
