#!/usr/bin/env python3
"""
北海道・札幌市（前半40件）の斎場データをSupabase REST APIに投入するスクリプト
"""

import json
import urllib.request
import urllib.error
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

HEADERS = {
    "apikey": API_KEY,
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal",
}

venues = [
    # =============================================
    # 札幌市中央区 — 8件
    # =============================================
    {
        "name": "やわらぎ斎場 センティア28",
        "slug": "yawaragi-sentia28-sapporo",
        "venue_type": "private_hall",
        "description": "やわらぎ斎場が運営する札幌中心部の大型斎場。大通公園至近で交通アクセス抜群。最大100名収容の式場と充実した設備を備え、家族葬から一般葬まで幅広く対応。24時間365日相談受付。",
        "address": "北海道札幌市中央区南2条西8丁目12-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0570,
        "longitude": 141.3460,
        "nearest_station": "地下鉄東西線 大通駅",
        "station_walk_minutes": 7,
        "capacity_max": 100,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["駅近", "大型式場", "24時間対応", "家族葬対応", "バリアフリー"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.2,
        "review_count": 28,
    },
    {
        "name": "やわらぎ斎場 山鼻",
        "slug": "yawaragi-yamahana-sapporo",
        "venue_type": "private_hall",
        "description": "札幌市中央区山鼻エリアに位置するやわらぎ斎場。閑静な住宅街にあり落ち着いた雰囲気。家族葬に適した温かみのある空間で、少人数から50名程度まで対応可能。駐車場完備。",
        "address": "北海道札幌市中央区南20条西11丁目2-3",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0380,
        "longitude": 141.3400,
        "nearest_station": "市電 石山通停留場",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}],
        "features": ["家族葬対応", "駐車場完備", "閑静な立地", "バリアフリー"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.1,
        "review_count": 19,
    },
    {
        "name": "やわらぎ伏見別邸",
        "slug": "yawaragi-fushimi-bettei-sapporo",
        "venue_type": "private_hall",
        "description": "やわらぎ斎場の別邸ブランド。伏見エリアの高級住宅街に位置し、邸宅のような温かみある空間で故人を送ることができます。完全貸切対応で1日1組限定。プライバシーに配慮した家族葬専用施設。",
        "address": "北海道札幌市中央区南13条西21丁目3-5",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0420,
        "longitude": 141.3280,
        "nearest_station": "市電 西線14条停留場",
        "station_walk_minutes": 12,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "キッチン": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 275000}],
        "features": ["1日1組貸切", "家族葬専用", "邸宅型ホール", "バリアフリー"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.4,
        "review_count": 15,
    },
    {
        "name": "やわらぎ北円山別邸",
        "slug": "yawaragi-kitamaruyama-bettei",
        "venue_type": "private_hall",
        "description": "札幌市中央区北円山の閑静なエリアに佇む邸宅型葬儀場。1日1組完全貸切で、ゆったりとした時間の中で故人とのお別れができます。自然光が差し込む明るい空間が特徴。",
        "address": "北海道札幌市中央区北5条西22丁目1-10",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0660,
        "longitude": 141.3280,
        "nearest_station": "地下鉄東西線 西28丁目駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 275000}],
        "features": ["1日1組貸切", "家族葬専用", "邸宅型ホール", "自然光"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.3,
        "review_count": 12,
    },
    {
        "name": "地蔵寺 光明殿",
        "slug": "jizoji-komyoden-sapporo",
        "venue_type": "temple_hall",
        "description": "札幌市中央区にある地蔵寺の葬儀式場。やわらぎ斎場専属施設として運営され、伝統的な寺院の雰囲気の中で厳かな葬儀を執り行えます。宗派を問わず利用可能で、少人数から中規模の葬儀に対応。",
        "address": "北海道札幌市中央区双子山1丁目10-12",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0440,
        "longitude": 141.3520,
        "nearest_station": "地下鉄南北線 中島公園駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 120000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 500000}],
        "features": ["寺院式場", "宗派不問", "伝統的雰囲気", "駐車場完備"],
        "operator_name": "地蔵寺",
        "rating_avg": 4.0,
        "review_count": 14,
    },
    {
        "name": "メモリアホール中央",
        "slug": "memoria-chuo-sapporo",
        "venue_type": "private_hall",
        "description": "メモリアホール（現ティア）が運営する札幌中央区の葬儀場。交通アクセス良好で、少人数の家族葬から大規模な一般葬まで柔軟に対応。清潔感のある明るい内装と充実した設備が特徴です。",
        "address": "北海道札幌市中央区南6条西10丁目1005-6",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0520,
        "longitude": 141.3380,
        "nearest_station": "市電 東本願寺前停留場",
        "station_walk_minutes": 5,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "ロビー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["駅近", "家族葬対応", "一般葬対応", "バリアフリー"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.0,
        "review_count": 22,
    },
    {
        "name": "小さなお葬式 二十四軒ホール",
        "slug": "chiisana-ososhiki-nijuyonken",
        "venue_type": "private_hall",
        "description": "小さなお葬式が提携する札幌市中央区の家族葬向けホール。二十四軒エリアに位置し、地下鉄東西線二十四軒駅から徒歩圏内。少人数の家族葬に特化したコンパクトな施設で、費用を抑えた葬儀が可能。",
        "address": "北海道札幌市中央区北5条西19丁目1-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0660,
        "longitude": 141.3310,
        "nearest_station": "地下鉄東西線 二十四軒駅",
        "station_walk_minutes": 5,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["低価格", "駅近", "家族葬専用", "24時間対応"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 3.9,
        "review_count": 18,
    },
    {
        "name": "香華殿 札幌中央斎場",
        "slug": "kokaden-sapporo-chuo",
        "venue_type": "private_hall",
        "description": "香華殿グループが運営する札幌中央区の総合斎場。格式高い内装と充実した設備を備え、伝統的な葬儀から現代的な家族葬まで幅広く対応。経験豊富なスタッフが丁寧にサポートします。",
        "address": "北海道札幌市中央区南11条西8丁目2-12",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0460,
        "longitude": 141.3420,
        "nearest_station": "市電 中島公園通停留場",
        "station_walk_minutes": 6,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 520000}],
        "features": ["格式高い", "家族葬対応", "一般葬対応", "駐車場完備"],
        "operator_name": "香華殿",
        "rating_avg": 4.1,
        "review_count": 16,
    },
    # =============================================
    # 札幌市北区 — 8件
    # =============================================
    {
        "name": "やわらぎ斎場 新琴似",
        "slug": "yawaragi-shinkotoni-sapporo",
        "venue_type": "private_hall",
        "description": "札幌市北区新琴似に位置するやわらぎ斎場。住宅街の中にあり、地域に根差した温かみのある葬儀場です。家族葬から一般葬まで対応可能で、広々とした駐車場を完備しています。",
        "address": "北海道札幌市北区新琴似5条7丁目7-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1100,
        "longitude": 141.3380,
        "nearest_station": "JR学園都市線 新琴似駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["駐車場完備", "家族葬対応", "一般葬対応", "地域密着"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.1,
        "review_count": 21,
    },
    {
        "name": "やわらぎ斎場 篠路",
        "slug": "yawaragi-shinoro-sapporo",
        "venue_type": "private_hall",
        "description": "札幌市北区篠路エリアのやわらぎ斎場。JR篠路駅から近く、北区北部の方に便利な立地です。落ち着いた雰囲気の式場で、故人との大切な時間を過ごせます。家族葬に最適。",
        "address": "北海道札幌市北区篠路8条5丁目3-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1300,
        "longitude": 141.3600,
        "nearest_station": "JR学園都市線 篠路駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}],
        "features": ["駅近", "家族葬対応", "駐車場完備"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.0,
        "review_count": 13,
    },
    {
        "name": "やわらぎ斎場 幌北",
        "slug": "yawaragi-horohoku-sapporo",
        "venue_type": "private_hall",
        "description": "札幌市北区北23条エリアのやわらぎ斎場。地下鉄南北線北24条駅から徒歩圏内で、公共交通機関でのアクセスも便利。北大周辺の方に親しまれている地域密着型の葬儀場です。",
        "address": "北海道札幌市北区北23条西9丁目2-13",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0880,
        "longitude": 141.3400,
        "nearest_station": "地下鉄南北線 北24条駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["駅近", "家族葬対応", "地域密着", "バリアフリー"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.0,
        "review_count": 17,
    },
    {
        "name": "やわらぎ新川別邸",
        "slug": "yawaragi-shinkawa-bettei",
        "venue_type": "private_hall",
        "description": "やわらぎ斎場の別邸ブランド、新川エリア。1日1組完全貸切の邸宅型ホールで、まるで自宅のようなくつろぎの空間で家族葬を執り行えます。木のぬくもりを感じるモダンな内装が人気。",
        "address": "北海道札幌市北区新川5条4丁目1-10",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0950,
        "longitude": 141.3150,
        "nearest_station": "JR学園都市線 新川駅",
        "station_walk_minutes": 12,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "キッチン": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 275000}],
        "features": ["1日1組貸切", "家族葬専用", "邸宅型ホール", "モダン内装"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.3,
        "review_count": 11,
    },
    {
        "name": "やわらぎ斎場 屯田",
        "slug": "yawaragi-tonden-sapporo",
        "venue_type": "private_hall",
        "description": "札幌市北区屯田エリアのやわらぎ斎場。新興住宅街に位置し、広い駐車場を完備。家族葬から中規模の一般葬まで対応可能で、地域の方に広く利用されています。",
        "address": "北海道札幌市北区屯田6条7丁目4-5",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1150,
        "longitude": 141.3280,
        "nearest_station": "JR学園都市線 太平駅",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}],
        "features": ["駐車場完備", "家族葬対応", "地域密着"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 3.9,
        "review_count": 14,
    },
    {
        "name": "やわらぎ斎場 あいの里",
        "slug": "yawaragi-ainosato-sapporo",
        "venue_type": "private_hall",
        "description": "札幌市北区あいの里のやわらぎ斎場。JR学園都市線あいの里教育大駅から近く、あいの里地区にお住まいの方に便利。落ち着いた住宅街の中で、心安らぐ葬儀を執り行えます。",
        "address": "北海道札幌市北区あいの里2条6丁目1-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1500,
        "longitude": 141.3700,
        "nearest_station": "JR学園都市線 あいの里教育大駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}],
        "features": ["駅近", "家族葬対応", "閑静な立地"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.0,
        "review_count": 10,
    },
    {
        "name": "ファミリア北12条",
        "slug": "familia-kita12jo-sapporo",
        "venue_type": "private_hall",
        "description": "やわらぎグループのファミリアブランド。札幌市北区北12条に位置し、地下鉄南北線北12条駅から徒歩圏内。少人数の家族葬に特化したアットホームな空間です。",
        "address": "北海道札幌市北区北12条西4丁目2-2",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0780,
        "longitude": 141.3440,
        "nearest_station": "地下鉄南北線 北12条駅",
        "station_walk_minutes": 3,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}],
        "features": ["駅近", "家族葬専用", "少人数対応", "アットホーム"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.2,
        "review_count": 9,
    },
    {
        "name": "公益社 太平斎場",
        "slug": "koekisha-taihei-sapporo",
        "venue_type": "private_hall",
        "description": "公益社が運営する札幌市北区太平の大型斎場。広々とした式場と充実した設備を持ち、家族葬から大規模な社葬まで幅広く対応。北区北部エリアの拠点的な葬儀場として多くの方に利用されています。",
        "address": "北海道札幌市北区太平7条5丁目2-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1200,
        "longitude": 141.3580,
        "nearest_station": "JR学園都市線 太平駅",
        "station_walk_minutes": 10,
        "capacity_max": 100,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True, "ロビー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 500000}],
        "features": ["大型式場", "駐車場完備", "家族葬対応", "社葬対応"],
        "operator_name": "公益社",
        "rating_avg": 4.1,
        "review_count": 25,
    },
    # =============================================
    # 札幌市東区 — 8件
    # =============================================
    {
        "name": "やわらぎ斎場 北光",
        "slug": "yawaragi-hokko-sapporo",
        "venue_type": "private_hall",
        "description": "札幌市東区北35条に位置するやわらぎ斎場。東区の中でも広い式場を持ち、一般葬にも対応可能な規模。地下鉄東豊線栄町駅からアクセスしやすく、東区全域から利用されています。",
        "address": "北海道札幌市東区北35条東8丁目2-5",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1050,
        "longitude": 141.3650,
        "nearest_station": "地下鉄東豊線 栄町駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["駐車場完備", "家族葬対応", "一般葬対応", "バリアフリー"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.1,
        "review_count": 20,
    },
    {
        "name": "やわらぎ斎場 元町",
        "slug": "yawaragi-motomachi-sapporo",
        "venue_type": "private_hall",
        "description": "札幌市東区元町エリアのやわらぎ斎場。地下鉄東豊線元町駅から近く、交通アクセス良好。清潔感のある落ち着いた内装で、家族葬を中心にご利用いただけます。",
        "address": "北海道札幌市東区北23条東23丁目2-10",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0900,
        "longitude": 141.3850,
        "nearest_station": "地下鉄東豊線 元町駅",
        "station_walk_minutes": 12,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}],
        "features": ["家族葬対応", "駐車場完備", "バリアフリー"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.0,
        "review_count": 16,
    },
    {
        "name": "ウィズハウス 北12",
        "slug": "withhouse-kita12-sapporo",
        "venue_type": "private_hall",
        "description": "コープさっぽろグループが運営する家族葬専用ホール。札幌市東区北12条に位置し、コープ会員割引が利用可能。温かみのある木調の内装で、少人数の家族葬に最適な空間を提供します。",
        "address": "北海道札幌市東区北12条東13丁目2-28",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0790,
        "longitude": 141.3700,
        "nearest_station": "地下鉄東豊線 環状通東駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["コープ会員割引", "家族葬専用", "少人数対応", "24時間対応"],
        "operator_name": "めもるホールディングス",
        "rating_avg": 4.2,
        "review_count": 23,
    },
    {
        "name": "ウィズハウス 苗穂本町",
        "slug": "withhouse-naebo-honcho",
        "venue_type": "private_hall",
        "description": "コープの家族葬ウィズハウスの苗穂本町店。札幌市東区本町に位置し、1日1組貸切の家族葬ホール。コープさっぽろ組合員なら特別料金で利用可能。安置から葬儀まで一貫して対応します。",
        "address": "北海道札幌市東区本町1条11丁目1-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0780,
        "longitude": 141.3900,
        "nearest_station": "JR函館本線 苗穂駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["コープ会員割引", "1日1組貸切", "家族葬専用", "24時間対応"],
        "operator_name": "めもるホールディングス",
        "rating_avg": 4.1,
        "review_count": 18,
    },
    {
        "name": "ウィズハウス 東苗穂",
        "slug": "withhouse-higashinaebo",
        "venue_type": "private_hall",
        "description": "コープの家族葬ウィズハウスの東苗穂店。札幌市東区東苗穂に位置し、広い駐車場を完備。冬場の雪道でも安心のアクセス。1日1組貸切で、ゆったりとしたお別れの時間を過ごせます。",
        "address": "北海道札幌市東区東苗穂8条2丁目15-20",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0900,
        "longitude": 141.4050,
        "nearest_station": "地下鉄東豊線 環状通東駅",
        "station_walk_minutes": 25,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["コープ会員割引", "1日1組貸切", "駐車場完備", "家族葬専用"],
        "operator_name": "めもるホールディングス",
        "rating_avg": 4.0,
        "review_count": 14,
    },
    {
        "name": "家族葬のディアネス 新琴似",
        "slug": "dearness-shinkotoni-sapporo",
        "venue_type": "private_hall",
        "description": "家族葬のディアネスが運営する新琴似エリアの家族葬専用ホール。木のぬくもりを感じるナチュラルな内装で、アットホームな雰囲気。少人数でのお別れに最適な空間です。",
        "address": "北海道札幌市北区新琴似2条3丁目1-5",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1030,
        "longitude": 141.3380,
        "nearest_station": "JR学園都市線 新琴似駅",
        "station_walk_minutes": 5,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}],
        "features": ["家族葬専用", "駅近", "少人数対応", "アットホーム"],
        "operator_name": "ディアネス",
        "rating_avg": 4.2,
        "review_count": 12,
    },
    {
        "name": "家族葬のディアネス 屯田",
        "slug": "dearness-tonden-sapporo",
        "venue_type": "private_hall",
        "description": "家族葬のディアネスが運営する屯田エリアの葬儀場。札幌市北区屯田の住宅街に位置し、落ち着いた環境で家族葬を執り行えます。少人数のお別れに特化した温かな空間。",
        "address": "北海道札幌市北区屯田9条2丁目8-8",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1200,
        "longitude": 141.3300,
        "nearest_station": "JR学園都市線 太平駅",
        "station_walk_minutes": 18,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}],
        "features": ["家族葬専用", "少人数対応", "駐車場完備"],
        "operator_name": "ディアネス",
        "rating_avg": 4.1,
        "review_count": 10,
    },
    {
        "name": "ミモザホール新琴似",
        "slug": "mimosa-hall-shinkotoni",
        "venue_type": "private_hall",
        "description": "ミモザホールが運営する新琴似エリアの葬儀場。家族葬から一般葬まで幅広く対応し、温かみのある落ち着いた式場が特徴。経験豊富なスタッフが心を込めてサポートします。",
        "address": "北海道札幌市北区新琴似1条11丁目10-22",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1050,
        "longitude": 141.3450,
        "nearest_station": "JR学園都市線 新琴似駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 480000}],
        "features": ["家族葬対応", "一般葬対応", "駐車場完備"],
        "operator_name": "ミモザホール",
        "rating_avg": 3.9,
        "review_count": 15,
    },
    # =============================================
    # 札幌市白石区 — 8件
    # =============================================
    {
        "name": "やわらぎ斎場 白石",
        "slug": "yawaragi-shiroishi-sapporo",
        "venue_type": "private_hall",
        "description": "札幌市白石区中央に位置するやわらぎ斎場の白石店。白石区の中心エリアにあり、地下鉄東西線白石駅からアクセス可能。家族葬から一般葬まで対応できる広々とした式場を備えています。",
        "address": "北海道札幌市白石区中央2条7丁目5-25",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0570,
        "longitude": 141.3880,
        "nearest_station": "地下鉄東西線 白石駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "一般葬対応", "駐車場完備", "バリアフリー"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.0,
        "review_count": 19,
    },
    {
        "name": "やわらぎファミリア 南郷",
        "slug": "yawaragi-familia-nango",
        "venue_type": "private_hall",
        "description": "やわらぎグループのファミリアブランド南郷店。札幌市白石区南郷通沿いに位置し、地下鉄東西線南郷18丁目駅から近い。少人数の家族葬に特化したコンパクトなホールです。",
        "address": "北海道札幌市白石区南郷通18丁目南3-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0500,
        "longitude": 141.4100,
        "nearest_station": "地下鉄東西線 南郷18丁目駅",
        "station_walk_minutes": 5,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}],
        "features": ["駅近", "家族葬専用", "少人数対応"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.1,
        "review_count": 11,
    },
    {
        "name": "白石中央斎場",
        "slug": "shiroishi-chuo-saijo",
        "venue_type": "private_hall",
        "description": "札幌市白石区中央の総合斎場。白石区民に長年親しまれている地域密着型の葬儀場で、通夜から告別式まで一貫して対応。広い式場と充実した付帯設備を持ち、大規模な葬儀にも対応可能です。",
        "address": "北海道札幌市白石区中央2条3丁目4-10",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0580,
        "longitude": 141.3830,
        "nearest_station": "地下鉄東西線 白石駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True, "ロビー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 290000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 490000}],
        "features": ["地域密着", "大型式場", "駐車場完備", "一般葬対応"],
        "operator_name": "白石中央斎場",
        "rating_avg": 4.0,
        "review_count": 22,
    },
    {
        "name": "ウィズハウス 南郷7丁目",
        "slug": "withhouse-nango7-sapporo",
        "venue_type": "private_hall",
        "description": "コープの家族葬ウィズハウスの南郷7丁目店。地下鉄東西線南郷7丁目駅から徒歩圏内。コープ会員なら特別料金で利用でき、温かみのある空間で家族葬を執り行えます。",
        "address": "北海道札幌市白石区南郷通7丁目南5番16号",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0530,
        "longitude": 141.3920,
        "nearest_station": "地下鉄東西線 南郷7丁目駅",
        "station_walk_minutes": 5,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["コープ会員割引", "駅近", "家族葬専用", "24時間対応"],
        "operator_name": "めもるホールディングス",
        "rating_avg": 4.2,
        "review_count": 17,
    },
    {
        "name": "ウィズハウス 北郷",
        "slug": "withhouse-kitago-sapporo",
        "venue_type": "private_hall",
        "description": "コープの家族葬ウィズハウスの北郷店。札幌市白石区北郷に位置し、JR白石駅からもアクセス可能。1日1組貸切の家族葬専用ホールで、心安らぐお別れの時間を提供します。",
        "address": "北海道札幌市白石区北郷7条4丁目1-9",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0650,
        "longitude": 141.3980,
        "nearest_station": "JR函館本線 白石駅",
        "station_walk_minutes": 12,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["コープ会員割引", "1日1組貸切", "家族葬専用"],
        "operator_name": "めもるホールディングス",
        "rating_avg": 4.0,
        "review_count": 14,
    },
    {
        "name": "小さなお葬式 平和通ホール",
        "slug": "chiisana-ososhiki-heiwadori",
        "venue_type": "private_hall",
        "description": "小さなお葬式が提携する白石区の葬儀ホール。費用を抑えた家族葬プランが充実。追加料金なしの明朗会計が特徴で、初めての方でも安心して利用できます。24時間相談受付。",
        "address": "北海道札幌市白石区平和通10丁目北1-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0480,
        "longitude": 141.3950,
        "nearest_station": "地下鉄東西線 南郷7丁目駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["低価格", "明朗会計", "家族葬専用", "24時間対応"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 3.8,
        "review_count": 16,
    },
    {
        "name": "家族葬のディアネス 菊水元町",
        "slug": "dearness-kikusui-motomachi",
        "venue_type": "private_hall",
        "description": "家族葬のディアネスが運営する菊水元町エリアの家族葬専用ホール。少人数でのアットホームなお別れに最適で、温かみのある木調の内装が心を癒します。",
        "address": "北海道札幌市白石区菊水元町4条2丁目6-4",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0600,
        "longitude": 141.3780,
        "nearest_station": "地下鉄東西線 菊水駅",
        "station_walk_minutes": 15,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}],
        "features": ["家族葬専用", "少人数対応", "アットホーム"],
        "operator_name": "ディアネス",
        "rating_avg": 4.1,
        "review_count": 9,
    },
    {
        "name": "公益社 南郷斎場",
        "slug": "koekisha-nango-saijo",
        "venue_type": "private_hall",
        "description": "公益社が運営する白石区南郷通の葬儀場。南郷通り沿いの便利な立地で、広い駐車場を完備。家族葬から一般葬まで幅広く対応し、地域の方に信頼されている葬儀場です。",
        "address": "北海道札幌市白石区南郷通15丁目北8-27",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0510,
        "longitude": 141.4030,
        "nearest_station": "地下鉄東西線 南郷13丁目駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 500000}],
        "features": ["駐車場完備", "家族葬対応", "一般葬対応", "地域密着"],
        "operator_name": "公益社",
        "rating_avg": 4.0,
        "review_count": 18,
    },
    # =============================================
    # 札幌市豊平区 — 8件
    # =============================================
    {
        "name": "やわらぎ斎場 月寒",
        "slug": "yawaragi-tsukisamu-sapporo",
        "venue_type": "private_hall",
        "description": "札幌市豊平区月寒中央通に位置するやわらぎ斎場。地下鉄東豊線月寒中央駅から徒歩圏内で交通アクセス良好。豊平区の中心的な葬儀場として、家族葬から一般葬まで幅広く対応しています。",
        "address": "北海道札幌市豊平区月寒中央通7丁目6-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0350,
        "longitude": 141.3950,
        "nearest_station": "地下鉄東豊線 月寒中央駅",
        "station_walk_minutes": 5,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["駅近", "家族葬対応", "一般葬対応", "バリアフリー"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.1,
        "review_count": 20,
    },
    {
        "name": "やわらぎ斎場 豊平",
        "slug": "yawaragi-toyohira-sapporo",
        "venue_type": "private_hall",
        "description": "札幌市豊平区水車町のやわらぎ斎場。豊平川沿いに位置し、静かな環境で故人とのお別れができます。地下鉄東豊線学園前駅から近く、アクセスも便利です。",
        "address": "北海道札幌市豊平区水車町3丁目3-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0480,
        "longitude": 141.3700,
        "nearest_station": "地下鉄東豊線 学園前駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}],
        "features": ["駅近", "家族葬対応", "閑静な立地"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.0,
        "review_count": 15,
    },
    {
        "name": "やわらぎ斎場 西岡",
        "slug": "yawaragi-nishioka-sapporo",
        "venue_type": "private_hall",
        "description": "札幌市豊平区西岡のやわらぎ斎場。西岡の閑静な住宅街に位置し、落ち着いた雰囲気の中で葬儀を執り行えます。駐車場を広く確保しており、車でのアクセスに便利です。",
        "address": "北海道札幌市豊平区西岡509番地",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0200,
        "longitude": 141.3800,
        "nearest_station": "地下鉄南北線 澄川駅",
        "station_walk_minutes": 20,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}],
        "features": ["駐車場完備", "家族葬対応", "閑静な立地"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 3.9,
        "review_count": 12,
    },
    {
        "name": "ウィズハウス 豊平橋",
        "slug": "withhouse-toyohirabashi",
        "venue_type": "private_hall",
        "description": "コープの家族葬ウィズハウスの豊平橋店。豊平川沿いに位置し、地下鉄東西線菊水駅や東豊線豊平公園駅からアクセス可能。コープ会員割引あり。1日1組貸切の家族葬ホール。",
        "address": "北海道札幌市豊平区豊平4条2丁目6-10",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0520,
        "longitude": 141.3700,
        "nearest_station": "地下鉄東豊線 豊平公園駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["コープ会員割引", "1日1組貸切", "家族葬専用"],
        "operator_name": "めもるホールディングス",
        "rating_avg": 4.1,
        "review_count": 19,
    },
    {
        "name": "フリエホール つきさむ",
        "slug": "furie-hall-tsukisamu",
        "venue_type": "private_hall",
        "description": "コープの家族葬フリエホールの月寒店。ウィズハウスの姉妹ブランドで、よりカジュアルで温かみのある家族葬を提供。月寒中央通に位置し、地下鉄東豊線月寒中央駅から近い。",
        "address": "北海道札幌市豊平区月寒中央通10丁目6-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0330,
        "longitude": 141.3980,
        "nearest_station": "地下鉄東豊線 月寒中央駅",
        "station_walk_minutes": 5,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["コープ会員割引", "駅近", "家族葬専用", "カジュアル"],
        "operator_name": "めもるホールディングス",
        "rating_avg": 4.0,
        "review_count": 11,
    },
    {
        "name": "北海斎場",
        "slug": "hokkai-saijo-toyohira",
        "venue_type": "private_hall",
        "description": "札幌市豊平区に位置する北海斎場。長年の実績を持つ地域密着型の葬儀場で、通夜から告別式、火葬場への送迎まで一貫してサポート。広々とした式場と充実した設備が特徴です。",
        "address": "北海道札幌市豊平区豊平4条3丁目2-5",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0510,
        "longitude": 141.3710,
        "nearest_station": "地下鉄東豊線 豊平公園駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True, "送迎バス": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 285000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 480000}],
        "features": ["地域密着", "送迎バスあり", "一般葬対応", "駐車場完備"],
        "operator_name": "北海斎場",
        "rating_avg": 4.0,
        "review_count": 24,
    },
    {
        "name": "メモリアホール美園",
        "slug": "memoria-misono-sapporo",
        "venue_type": "private_hall",
        "description": "メモリアホール（現ティア）が運営する豊平区美園エリアの葬儀場。地下鉄東豊線美園駅から近く、駅からのアクセスが便利。家族葬を中心に、丁寧なサービスを提供しています。",
        "address": "北海道札幌市豊平区美園3条5丁目1-15",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0420,
        "longitude": 141.3800,
        "nearest_station": "地下鉄東豊線 美園駅",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["駅近", "家族葬対応", "バリアフリー"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.0,
        "review_count": 13,
    },
    {
        "name": "香華殿 豊平斎場",
        "slug": "kokaden-toyohira-saijo",
        "venue_type": "private_hall",
        "description": "香華殿グループが運営する豊平区の葬儀場。格式のある落ち着いた雰囲気と、きめ細かなサービスが特徴。家族葬から一般葬まで対応し、豊平区・清田区エリアのお客様に広く利用されています。",
        "address": "北海道札幌市豊平区平岸3条5丁目4-18",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0350,
        "longitude": 141.3600,
        "nearest_station": "地下鉄南北線 平岸駅",
        "station_walk_minutes": 5,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 520000}],
        "features": ["駅近", "格式高い", "家族葬対応", "一般葬対応"],
        "operator_name": "香華殿",
        "rating_avg": 4.1,
        "review_count": 15,
    },
]

def insert_batch(batch):
    data_json = json.dumps(batch, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(SUPABASE_URL, data=data_json, headers=HEADERS, method="POST")
    try:
        with urllib.request.urlopen(req) as res:
            return res.status
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"  HTTPError {e.code}: {body[:300]}")
        return e.code

total = len(venues)
print(f"北海道・札幌市（前半）: {total}件を投入開始")

ok = 0
for i in range(0, total, 10):
    batch = venues[i:i+10]
    code = insert_batch(batch)
    names = ", ".join(v["name"] for v in batch)
    print(f"  バッチ {i//10+1}: {code} ({len(batch)}件) — {names}")
    if code in (200, 201):
        ok += len(batch)
    time.sleep(0.5)

print(f"\n完了: {ok}/{total}件 投入成功")
