#!/usr/bin/env python3
"""
宮城県の斎場データ バッチ1（40件）- 仙台市 青葉区・宮城野区・若林区
"""

import json
import urllib.request
import urllib.error
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

HEADERS = {
    "apikey": API_KEY,
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal",
}

venues = [
    # =============================================
    # 仙台市青葉区 (16件)
    # =============================================
    {
        "name": "葛岡斎場",
        "slug": "miyagi-kuzuoka-saijo",
        "venue_type": "public_crematorium",
        "description": "仙台市が運営する公営火葬場。仙台市民の火葬を中心に利用されており、年間約1万件の火葬を行っています。JR仙山線葛岡駅から徒歩圏内で、駐車場も完備。落ち着いた環境の中で故人をお見送りできます。",
        "address": "宮城県仙台市青葉区郷六字葛岡10",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.271, "longitude": 140.821,
        "nearest_station": "JR仙山線 葛岡駅", "station_walk_minutes": 10,
        "capacity_max": 100, "hall_count": 2, "has_crematorium": True, "parking_count": 80,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "待合室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}],
        "features": ["火葬場併設", "公営斎場", "バリアフリー", "大規模"],
        "operator_name": "仙台市", "rating_avg": 3.8, "review_count": 28,
    },
    {
        "name": "仙台中央斎場 清月記",
        "slug": "miyagi-seigetsuki-chuo",
        "venue_type": "private_hall",
        "description": "仙台市青葉区本町に位置する清月記の中心的斎場。仙台駅から徒歩圏内の好立地で、家族葬から一般葬まで幅広く対応。洗練された内装と充実した設備が特長で、年間を通じて多くの方に利用されています。",
        "address": "宮城県仙台市青葉区本町2-7-4",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.268, "longitude": 140.871,
        "nearest_station": "JR東北本線 仙台駅", "station_walk_minutes": 12,
        "capacity_max": 120, "hall_count": 3, "has_crematorium": False, "parking_count": 40,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "駅近", "宿泊可能", "バリアフリー"],
        "operator_name": "株式会社清月記", "rating_avg": 4.3, "review_count": 25,
    },
    {
        "name": "セレモール仙台",
        "slug": "miyagi-ceremor-sendai",
        "venue_type": "private_hall",
        "description": "仙台市青葉区郷六に位置するあいあーる葬祭会館セレモールの本館。大規模な葬儀にも対応可能な広い式場を備え、一般葬から社葬まで幅広く対応。昭和36年創業の老舗葬儀社が運営しています。",
        "address": "宮城県仙台市青葉区郷六字舘22-1",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.272, "longitude": 140.823,
        "nearest_station": "JR仙山線 葛岡駅", "station_walk_minutes": 15,
        "capacity_max": 200, "hall_count": 3, "has_crematorium": False, "parking_count": 100,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}, {"type": "shaso", "label": "社葬プラン", "priceFrom": 1200000}],
        "features": ["家族葬対応", "大規模", "宿泊可能", "バリアフリー"],
        "operator_name": "あいあーる葬祭会館", "rating_avg": 4.1, "review_count": 22,
    },
    {
        "name": "セレモール仙台別館 こもれび",
        "slug": "miyagi-ceremor-komorebi",
        "venue_type": "private_hall",
        "description": "セレモール仙台の別館として運営される家族葬専用ホール。少人数の家族葬に特化した温かみのある空間で、1日1組貸切で利用できます。プライベートな空間で故人とゆっくりお別れの時間を過ごせます。",
        "address": "宮城県仙台市青葉区郷六字舘23-5",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.272, "longitude": 140.824,
        "nearest_station": "JR仙山線 葛岡駅", "station_walk_minutes": 15,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬対応", "1日1組貸切", "少人数向け"],
        "operator_name": "あいあーる葬祭会館", "rating_avg": 4.2, "review_count": 18,
    },
    {
        "name": "青葉典礼会館",
        "slug": "miyagi-aoba-tenrei",
        "venue_type": "private_hall",
        "description": "仙台市青葉区堤町に位置する典礼会館。北仙台駅から徒歩圏内で、堤通沿いのアクセスしやすい立地です。家族葬から一般葬まで幅広く対応し、50台分の駐車場を完備しています。",
        "address": "宮城県仙台市青葉区堤町3-12-25",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.277, "longitude": 140.870,
        "nearest_station": "JR仙山線 北仙台駅", "station_walk_minutes": 8,
        "capacity_max": 100, "hall_count": 2, "has_crematorium": False, "parking_count": 50,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 380000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 650000}],
        "features": ["家族葬対応", "駅近", "バリアフリー"],
        "operator_name": "株式会社博善社", "rating_avg": 4.0, "review_count": 20,
    },
    {
        "name": "家族葬の仙和 仙台旭ヶ丘ホール",
        "slug": "miyagi-senwa-asahigaoka",
        "venue_type": "private_hall",
        "description": "仙台市青葉区旭ヶ丘に位置する家族葬の仙和の式場。地下鉄南北線旭ヶ丘駅から徒歩11分。1日1組貸切で、少人数の家族葬に特化。安置室完備で、故人との最後の時間をゆっくり過ごせます。",
        "address": "宮城県仙台市青葉区旭ヶ丘3-27-3",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.287, "longitude": 140.869,
        "nearest_station": "地下鉄南北線 旭ヶ丘駅", "station_walk_minutes": 11,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 187000}],
        "features": ["家族葬対応", "1日1組貸切", "少人数向け"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.2, "review_count": 16,
    },
    {
        "name": "家族葬の仙和 仙台宮町ホール",
        "slug": "miyagi-senwa-miyamachi",
        "venue_type": "private_hall",
        "description": "仙台市青葉区宮町に位置する家族葬の仙和の式場。東照宮駅から徒歩圏内の好立地。1日1組貸切の家族葬専用ホールで、温かみのある空間の中でお別れの時間を過ごせます。",
        "address": "宮城県仙台市青葉区宮町5-1-16",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.278, "longitude": 140.878,
        "nearest_station": "JR仙山線 東照宮駅", "station_walk_minutes": 8,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 187000}],
        "features": ["家族葬対応", "1日1組貸切", "駅近"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.1, "review_count": 14,
    },
    {
        "name": "家族葬の仙和 仙台郷六ホール",
        "slug": "miyagi-senwa-gorokku",
        "venue_type": "private_hall",
        "description": "仙台市青葉区郷六に位置する家族葬の仙和の式場。葛岡斎場に近い立地で、火葬場へのアクセスが良好です。1日1組貸切で、家族だけの静かなお別れの時間を大切にできます。",
        "address": "宮城県仙台市青葉区郷六字新々道4-12",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.270, "longitude": 140.828,
        "nearest_station": "JR仙山線 葛岡駅", "station_walk_minutes": 12,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["家族葬対応", "1日1組貸切", "火葬場近く"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.0, "review_count": 12,
    },
    {
        "name": "仙台北斎場 清月記",
        "slug": "miyagi-seigetsuki-kita",
        "venue_type": "private_hall",
        "description": "仙台市青葉区北部に位置する清月記の斎場。北仙台エリアの方に広く利用されており、家族葬から一般葬まで対応。落ち着いた雰囲気の式場で、経験豊富なスタッフが心のこもった葬儀をサポートします。",
        "address": "宮城県仙台市青葉区中山8-20-10",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.296, "longitude": 140.853,
        "nearest_station": "JR仙山線 北山駅", "station_walk_minutes": 15,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "株式会社清月記", "rating_avg": 4.1, "review_count": 19,
    },
    {
        "name": "密葬館北斎場 清月記",
        "slug": "miyagi-seigetsuki-missou-kita",
        "venue_type": "private_hall",
        "description": "清月記が運営する家族葬専用の密葬館。完全貸切型で、少人数の家族葬に特化した温かみのあるホールです。プライバシーに配慮した設計で、故人と家族だけの静かなお別れが叶います。",
        "address": "宮城県仙台市青葉区中山8-20-12",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.296, "longitude": 140.854,
        "nearest_station": "JR仙山線 北山駅", "station_walk_minutes": 15,
        "capacity_max": 20, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 275000}],
        "features": ["家族葬対応", "1日1組貸切", "少人数向け"],
        "operator_name": "株式会社清月記", "rating_avg": 4.3, "review_count": 11,
    },
    {
        "name": "ファミーユ仙台青葉",
        "slug": "miyagi-famille-aoba",
        "venue_type": "private_hall",
        "description": "仙台市青葉区に位置する家族葬のファミーユの式場。清月記グループが運営し、1日1組貸切の家族葬に特化。木のぬくもりを感じる内装で、温かみのあるお見送りを実現します。",
        "address": "宮城県仙台市青葉区上杉3-8-30",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.274, "longitude": 140.873,
        "nearest_station": "地下鉄南北線 北四番丁駅", "station_walk_minutes": 7,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬対応", "1日1組貸切", "駅近"],
        "operator_name": "株式会社清月記", "rating_avg": 4.2, "review_count": 13,
    },
    {
        "name": "仙台葬祭式場モンシエル",
        "slug": "miyagi-monciel-sendai",
        "venue_type": "private_hall",
        "description": "仙台市青葉区に位置する高級感のある葬祭式場。ホテルのような上質な空間で、格式ある葬儀を執り行えます。一般葬から社葬まで幅広く対応し、充実した設備とサービスが好評です。",
        "address": "宮城県仙台市青葉区本町1-11-1",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.268, "longitude": 140.873,
        "nearest_station": "JR東北本線 仙台駅", "station_walk_minutes": 10,
        "capacity_max": 200, "hall_count": 3, "has_crematorium": False, "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 440000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 770000}],
        "features": ["家族葬対応", "駅近", "大規模", "宿泊可能"],
        "operator_name": "仙台葬祭", "rating_avg": 4.4, "review_count": 24,
    },
    {
        "name": "てんれい仙台中央館",
        "slug": "miyagi-tenrei-sendai-chuo",
        "venue_type": "private_hall",
        "description": "仙台市青葉区に位置する仙台典礼の式場。仙台駅から車で約10分の立地で、家族葬から一般葬まで対応。地域密着型のきめ細かいサービスが特長で、仙台市民から信頼を得ています。",
        "address": "宮城県仙台市青葉区二日町12-20",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.272, "longitude": 140.869,
        "nearest_station": "地下鉄南北線 北四番丁駅", "station_walk_minutes": 5,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "駅近", "バリアフリー"],
        "operator_name": "仙台典礼", "rating_avg": 4.0, "review_count": 17,
    },
    {
        "name": "迎賓館菜園",
        "slug": "miyagi-geihinkan-saien",
        "venue_type": "private_hall",
        "description": "仙台市青葉区に位置する迎賓館サイエンの葬祭式場。ホテルのような上品な空間で、格式ある葬儀に対応。仙台駅から近く、公共交通機関でのアクセスも良好。一般葬から社葬まで幅広く利用されています。",
        "address": "宮城県仙台市青葉区花京院2-1-18",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.266, "longitude": 140.878,
        "nearest_station": "JR東北本線 仙台駅", "station_walk_minutes": 8,
        "capacity_max": 150, "hall_count": 2, "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 400000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 700000}],
        "features": ["家族葬対応", "駅近", "大規模", "宿泊可能"],
        "operator_name": "迎賓館菜園", "rating_avg": 4.3, "review_count": 21,
    },
    {
        "name": "花いちもんめ青葉",
        "slug": "miyagi-hanaichimonme-aoba",
        "venue_type": "private_hall",
        "description": "仙台市青葉区に位置する家族葬向けの小規模な葬儀場。花をテーマにした温かみのある空間で、アットホームな雰囲気の中でのお見送りが可能。少人数の家族葬に最適な施設です。",
        "address": "宮城県仙台市青葉区落合2-15-8",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.288, "longitude": 140.830,
        "nearest_station": "JR仙山線 愛子駅", "station_walk_minutes": 10,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}],
        "features": ["家族葬対応", "少人数向け"],
        "operator_name": "花いちもんめ", "rating_avg": 4.0, "review_count": 10,
    },
    {
        "name": "仙台北山イズミティホール",
        "slug": "miyagi-kitayama-izumity",
        "venue_type": "private_hall",
        "description": "仙台市青葉区北山エリアに位置する葬儀ホール。閑静な住宅街の中にあり、落ち着いた雰囲気で葬儀を執り行えます。北山駅から徒歩圏内で、家族葬を中心に利用されています。",
        "address": "宮城県仙台市青葉区北山2-5-10",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.283, "longitude": 140.860,
        "nearest_station": "JR仙山線 北山駅", "station_walk_minutes": 7,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "駅近", "バリアフリー"],
        "operator_name": "イズミティ", "rating_avg": 3.9, "review_count": 14,
    },
    # =============================================
    # 仙台市宮城野区 (12件)
    # =============================================
    {
        "name": "仙台宮城野斎場 清月記",
        "slug": "miyagi-seigetsuki-miyagino",
        "venue_type": "private_hall",
        "description": "仙台市宮城野区高砂に位置する清月記の斎場。JR仙石線中野栄駅からのアクセスが良好。家族葬から大規模な一般葬まで対応可能で、広い駐車場を完備しています。",
        "address": "宮城県仙台市宮城野区高砂1-4-5",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.268, "longitude": 140.937,
        "nearest_station": "JR仙石線 中野栄駅", "station_walk_minutes": 10,
        "capacity_max": 100, "hall_count": 2, "has_crematorium": False, "parking_count": 50,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "バリアフリー", "大規模"],
        "operator_name": "株式会社清月記", "rating_avg": 4.1, "review_count": 20,
    },
    {
        "name": "セレモール宮城野",
        "slug": "miyagi-ceremor-miyagino",
        "venue_type": "private_hall",
        "description": "仙台市宮城野区に位置するセレモールの式場。宮城野区・若林区エリアの方に広く利用されています。一般葬から家族葬まで対応可能で、地域に密着したサービスを提供しています。",
        "address": "宮城県仙台市宮城野区原町3-5-25",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.271, "longitude": 140.907,
        "nearest_station": "JR仙石線 陸前原ノ町駅", "station_walk_minutes": 7,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["家族葬対応", "駅近", "バリアフリー"],
        "operator_name": "あいあーる葬祭会館", "rating_avg": 4.0, "review_count": 18,
    },
    {
        "name": "セレモール小田原",
        "slug": "miyagi-ceremor-odawara",
        "venue_type": "private_hall",
        "description": "仙台市宮城野区小田原に位置するセレモールの式場。仙台駅東口エリアからのアクセスが良好。家族葬を中心に、少人数の葬儀に適した温かみのある空間を提供しています。",
        "address": "宮城県仙台市宮城野区小田原1-5-15",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.264, "longitude": 140.889,
        "nearest_station": "JR東北本線 仙台駅", "station_walk_minutes": 12,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "あいあーる葬祭会館", "rating_avg": 4.0, "review_count": 15,
    },
    {
        "name": "家族葬の仙和 仙台福室ホール",
        "slug": "miyagi-senwa-fukumuro",
        "venue_type": "private_hall",
        "description": "仙台市宮城野区福室に位置する家族葬の仙和の式場。1日1組貸切の家族葬専用ホールで、安置室も完備。仙石線中野栄駅から徒歩圏内で、宮城野区東部の方に利用されています。",
        "address": "宮城県仙台市宮城野区福室6-1-22",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.267, "longitude": 140.944,
        "nearest_station": "JR仙石線 中野栄駅", "station_walk_minutes": 10,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 187000}],
        "features": ["家族葬対応", "1日1組貸切", "少人数向け"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.1, "review_count": 13,
    },
    {
        "name": "家族葬の仙和 仙台幸町ホール",
        "slug": "miyagi-senwa-saiwaicho",
        "venue_type": "private_hall",
        "description": "仙台市宮城野区幸町に位置する家族葬の仙和の式場。仙石線陸前原ノ町駅から徒歩圏内。1日1組貸切の家族葬専用ホールで、プライベートな空間でのお別れが可能です。",
        "address": "宮城県仙台市宮城野区幸町3-14-15",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.270, "longitude": 140.903,
        "nearest_station": "JR仙石線 陸前原ノ町駅", "station_walk_minutes": 12,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 187000}],
        "features": ["家族葬対応", "1日1組貸切"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.0, "review_count": 12,
    },
    {
        "name": "家族葬の仙和 仙台原ノ町ホール",
        "slug": "miyagi-senwa-haranomachi",
        "venue_type": "private_hall",
        "description": "仙台市宮城野区原町に位置する家族葬の仙和の式場。陸前原ノ町駅から徒歩5分の好アクセス。1日1組貸切の家族葬ホールで、駅近のため公共交通機関での参列にも便利です。",
        "address": "宮城県仙台市宮城野区原町2-3-47",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.271, "longitude": 140.905,
        "nearest_station": "JR仙石線 陸前原ノ町駅", "station_walk_minutes": 5,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 187000}],
        "features": ["家族葬対応", "1日1組貸切", "駅近"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.2, "review_count": 15,
    },
    {
        "name": "てんれい東仙台館",
        "slug": "miyagi-tenrei-higashisendai",
        "venue_type": "private_hall",
        "description": "仙台市宮城野区に位置する仙台典礼の式場。東仙台駅から車で約5分の立地。一般葬から家族葬まで対応可能なホールを併設し、地域密着型のきめ細かいサービスを提供しています。",
        "address": "宮城県仙台市宮城野区東仙台4-7-1",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.281, "longitude": 140.909,
        "nearest_station": "JR東北本線 東仙台駅", "station_walk_minutes": 12,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "仙台典礼", "rating_avg": 3.9, "review_count": 16,
    },
    {
        "name": "ごんきや仙台荒井ホール",
        "slug": "miyagi-gonkiya-arai",
        "venue_type": "private_hall",
        "description": "仙台市宮城野区荒井エリアに位置するごんきやの葬儀ホール。地下鉄東西線荒井駅から徒歩圏内で、新興住宅地である荒井・六丁の目エリアの方に利用されています。家族葬に対応。",
        "address": "宮城県仙台市若林区荒井東1-3-5",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.248, "longitude": 140.929,
        "nearest_station": "地下鉄東西線 荒井駅", "station_walk_minutes": 8,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "駅近", "バリアフリー"],
        "operator_name": "株式会社ごんきや", "rating_avg": 4.1, "review_count": 14,
    },
    {
        "name": "花さいだん宮城野",
        "slug": "miyagi-hanasaidan-miyagino",
        "venue_type": "private_hall",
        "description": "仙台市宮城野区に位置する花さいだんの葬儀ホール。花祭壇を得意とし、美しい花に囲まれた温かみのあるお見送りが特長。家族葬から一般葬まで対応し、オリジナルの花祭壇プランが人気です。",
        "address": "宮城県仙台市宮城野区鶴ヶ谷5-22-1",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.284, "longitude": 140.914,
        "nearest_station": "JR仙石線 東仙台駅", "station_walk_minutes": 15,
        "capacity_max": 70, "hall_count": 2, "has_crematorium": False, "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["家族葬対応", "花祭壇", "バリアフリー"],
        "operator_name": "花さいだん", "rating_avg": 4.2, "review_count": 17,
    },
    {
        "name": "ほこだて仏光堂 宮城野ホール",
        "slug": "miyagi-hokodate-miyagino",
        "venue_type": "private_hall",
        "description": "仙台市宮城野区に位置するほこだて仏光堂の葬儀ホール。仏壇・仏具の老舗が運営する葬儀場で、伝統を大切にした心のこもった葬儀を提供。家族葬から一般葬まで対応しています。",
        "address": "宮城県仙台市宮城野区萩野町3-8-1",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.273, "longitude": 140.900,
        "nearest_station": "JR仙石線 宮城野原駅", "station_walk_minutes": 10,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "ほこだて仏光堂", "rating_avg": 4.0, "review_count": 13,
    },
    # =============================================
    # 仙台市若林区 (12件)
    # =============================================
    {
        "name": "仙台新寺斎場 清月記",
        "slug": "miyagi-seigetsuki-shintera",
        "venue_type": "private_hall",
        "description": "仙台市若林区新寺に位置する清月記の斎場。仙台駅東口から徒歩圏内の好アクセス。新寺通り沿いの寺町エリアに位置し、伝統的な雰囲気の中で格式ある葬儀を執り行えます。",
        "address": "宮城県仙台市若林区新寺4-4-1",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.259, "longitude": 140.892,
        "nearest_station": "JR東北本線 仙台駅", "station_walk_minutes": 15,
        "capacity_max": 100, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "宿泊可能", "バリアフリー"],
        "operator_name": "株式会社清月記", "rating_avg": 4.2, "review_count": 22,
    },
    {
        "name": "仙台若林斎場 清月記",
        "slug": "miyagi-seigetsuki-wakabayashi",
        "venue_type": "private_hall",
        "description": "仙台市若林区に位置する清月記の斎場。若林区の中心エリアに位置し、地域の方に広く利用されています。家族葬から一般葬まで対応可能な複数の式場を備えています。",
        "address": "宮城県仙台市若林区大和町4-15-25",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.255, "longitude": 140.898,
        "nearest_station": "地下鉄東西線 薬師堂駅", "station_walk_minutes": 10,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "株式会社清月記", "rating_avg": 4.0, "review_count": 18,
    },
    {
        "name": "密葬館若林斎場 清月記",
        "slug": "miyagi-seigetsuki-missou-wakabayashi",
        "venue_type": "private_hall",
        "description": "清月記が運営する若林区の家族葬専用ホール。完全貸切型の密葬館で、少人数の家族葬に特化。プライバシーに配慮された設計で、故人との最後の時間を大切に過ごせます。",
        "address": "宮城県仙台市若林区大和町4-15-27",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.255, "longitude": 140.899,
        "nearest_station": "地下鉄東西線 薬師堂駅", "station_walk_minutes": 10,
        "capacity_max": 20, "hall_count": 1, "has_crematorium": False, "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 275000}],
        "features": ["家族葬対応", "1日1組貸切", "少人数向け"],
        "operator_name": "株式会社清月記", "rating_avg": 4.3, "review_count": 10,
    },
    {
        "name": "セレモール霞目",
        "slug": "miyagi-ceremor-kasumi",
        "venue_type": "private_hall",
        "description": "仙台市若林区霞目に位置するセレモールの式場。若林区南部エリアの方に利用されており、家族葬から一般葬まで対応可能。広い駐車場を完備し、車でのアクセスが便利です。",
        "address": "宮城県仙台市若林区上飯田4-14-15",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.236, "longitude": 140.908,
        "nearest_station": "地下鉄東西線 六丁の目駅", "station_walk_minutes": 15,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 40,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "あいあーる葬祭会館", "rating_avg": 4.0, "review_count": 16,
    },
    {
        "name": "家族葬の仙和 仙台荒井ホール",
        "slug": "miyagi-senwa-arai",
        "venue_type": "private_hall",
        "description": "仙台市若林区荒井に位置する家族葬の仙和の式場。地下鉄東西線荒井駅から近く、新興住宅地エリアの方に便利な立地。1日1組貸切の家族葬ホールで、安置室も完備しています。",
        "address": "宮城県仙台市若林区荒井3-26-2",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.247, "longitude": 140.933,
        "nearest_station": "地下鉄東西線 荒井駅", "station_walk_minutes": 7,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 187000}],
        "features": ["家族葬対応", "1日1組貸切", "駅近"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.1, "review_count": 11,
    },
    {
        "name": "家族葬の仙和 仙台南小泉ホール",
        "slug": "miyagi-senwa-minamikoizumi",
        "venue_type": "private_hall",
        "description": "仙台市若林区南小泉に位置する家族葬の仙和の式場。若林区中央部の住宅街にあり、地域の方に利用されています。1日1組貸切で、静かな環境の中でのお別れが可能です。",
        "address": "宮城県仙台市若林区南小泉3-1-20",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.247, "longitude": 140.899,
        "nearest_station": "地下鉄東西線 薬師堂駅", "station_walk_minutes": 12,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["家族葬対応", "1日1組貸切"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.0, "review_count": 10,
    },
    {
        "name": "家族葬の仙和 仙台土樋ホール",
        "slug": "miyagi-senwa-tsuchitoi",
        "venue_type": "private_hall",
        "description": "仙台市若林区土樋に位置する家族葬の仙和の式場。地下鉄南北線愛宕橋駅から近く、公共交通機関でのアクセスが良好。1日1組貸切の家族葬ホールで、仙台市中心部からも近い立地です。",
        "address": "宮城県仙台市若林区土樋250-5",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.250, "longitude": 140.878,
        "nearest_station": "地下鉄南北線 愛宕橋駅", "station_walk_minutes": 5,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 187000}],
        "features": ["家族葬対応", "1日1組貸切", "駅近"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.1, "review_count": 12,
    },
    {
        "name": "ごんきや若林ホール",
        "slug": "miyagi-gonkiya-wakabayashi",
        "venue_type": "private_hall",
        "description": "仙台市若林区に位置するごんきやの葬儀ホール。若林区の住宅街に位置し、地域の方に広く利用されています。家族葬を中心に、温かみのあるサービスを提供しています。",
        "address": "宮城県仙台市若林区若林3-10-15",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.241, "longitude": 140.903,
        "nearest_station": "地下鉄東西線 連坊駅", "station_walk_minutes": 15,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "株式会社ごんきや", "rating_avg": 4.0, "review_count": 14,
    },
    {
        "name": "花さいだん六丁の目",
        "slug": "miyagi-hanasaidan-rokuchonome",
        "venue_type": "private_hall",
        "description": "仙台市若林区六丁の目エリアに位置する花さいだんの葬儀ホール。地下鉄東西線六丁の目駅から徒歩圏内。花祭壇を得意とし、美しい花に囲まれたお見送りが特長です。",
        "address": "宮城県仙台市若林区六丁の目中町8-25",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.247, "longitude": 140.920,
        "nearest_station": "地下鉄東西線 六丁の目駅", "station_walk_minutes": 5,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["家族葬対応", "花祭壇", "駅近"],
        "operator_name": "花さいだん", "rating_avg": 4.1, "review_count": 13,
    },
    {
        "name": "メモリアルサトー若林",
        "slug": "miyagi-memorial-sato-wakabayashi",
        "venue_type": "private_hall",
        "description": "仙台市若林区に位置するメモリアルサトーの葬儀場。地域に密着した葬儀社で、若林区を中心にきめ細かいサービスを提供。家族葬から一般葬まで幅広く対応しています。",
        "address": "宮城県仙台市若林区河原町1-5-40",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.245, "longitude": 140.881,
        "nearest_station": "地下鉄南北線 河原町駅", "station_walk_minutes": 5,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 500000}],
        "features": ["家族葬対応", "駅近"],
        "operator_name": "メモリアルサトー", "rating_avg": 3.9, "review_count": 11,
    },
    {
        "name": "若林セレモニーホール",
        "slug": "miyagi-wakabayashi-ceremony",
        "venue_type": "private_hall",
        "description": "仙台市若林区に位置する地域密着型のセレモニーホール。家族葬から一般葬まで対応可能で、落ち着いた雰囲気の中でのお見送りが可能。リーズナブルな価格設定も魅力です。",
        "address": "宮城県仙台市若林区遠見塚2-10-5",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.240, "longitude": 140.910,
        "nearest_station": "地下鉄東西線 卸町駅", "station_walk_minutes": 12,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 275000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 480000}],
        "features": ["家族葬対応", "低価格"],
        "operator_name": "若林セレモニー", "rating_avg": 3.8, "review_count": 9,
    },
    {
        "name": "連坊メモリアルホール",
        "slug": "miyagi-renbo-memorial",
        "venue_type": "private_hall",
        "description": "仙台市若林区連坊に位置するメモリアルホール。地下鉄東西線連坊駅から徒歩すぐの好立地。仙台駅からも近く、公共交通機関での参列に便利。家族葬を中心に利用されています。",
        "address": "宮城県仙台市若林区連坊1-4-25",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.253, "longitude": 140.890,
        "nearest_station": "地下鉄東西線 連坊駅", "station_walk_minutes": 3,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}],
        "features": ["家族葬対応", "駅近", "少人数向け"],
        "operator_name": "連坊メモリアル", "rating_avg": 4.0, "review_count": 10,
    },
]

def insert_batch(batch):
    data_json = json.dumps(batch, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(SUPABASE_URL, data=data_json, headers=HEADERS, method="POST")
    try:
        with urllib.request.urlopen(req) as resp:
            return resp.status
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"  HTTPError {e.code}: {body[:300]}")
        return e.code

total = 0
batch_size = 10
for i in range(0, len(venues), batch_size):
    batch = venues[i:i+batch_size]
    code = insert_batch(batch)
    total += len(batch)
    print(f"バッチ {i//batch_size+1}: {len(batch)}件 → HTTP {code} (累計 {total}件)")
    time.sleep(0.5)

print(f"\n完了: 合計 {total}件 投入")
