#!/usr/bin/env python3
"""
大阪府の斎場データ バッチ2: 大阪市 後半50件
港区・此花区・西成区・浪速区・西区・大正区・東成区・
"""
import json
import subprocess
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

venues = [
    # =============================================
    # 大阪市港区・此花区 (6件)
    # =============================================
    {
        "name": "港区セレモニーホール",
        "slug": "osaka-minato-ceremony",
        "venue_type": "private_hall",
        "description": "大阪市港区にある葬儀会館。大阪メトロ中央線朝潮橋駅から徒歩6分。港区の住宅街に位置し、家族葬から一般葬まで対応。地域に根差した温かみのあるサービスが特徴です。",
        "address": "大阪府大阪市港区磯路2-18-5",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6600,
        "longitude": 135.4650,
        "nearest_station": "大阪メトロ中央線 朝潮橋駅",
        "station_walk_minutes": 6,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 530000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "地域密着"],
        "operator_name": "港区セレモニー",
        "rating_avg": 3.8,
        "review_count": 31
    },
    {
        "name": "ベルコシティホール港",
        "slug": "osaka-bellco-minato",
        "venue_type": "private_hall",
        "description": "大阪市港区にあるベルコの葬儀会館。弁天町駅から徒歩7分の好立地。清潔感のある式場で家族葬・一般葬に対応。ベルコグループの安定したサービス品質が魅力です。",
        "address": "大阪府大阪市港区弁天4-6-12",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6680,
        "longitude": 135.4640,
        "nearest_station": "大阪メトロ中央線 弁天町駅",
        "station_walk_minutes": 7,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "ベルコグループ"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 47
    },
    {
        "name": "此花メモリアルホール",
        "slug": "osaka-konohana-memorial",
        "venue_type": "private_hall",
        "description": "大阪市此花区にある葬儀会館。JRゆめ咲線西九条駅から徒歩10分。此花区の住宅地に位置し、家族葬を中心に地域の方々にご利用いただいています。USJエリアにも近い場所です。",
        "address": "大阪府大阪市此花区西九条3-4-21",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6830,
        "longitude": 135.4610,
        "nearest_station": "JRゆめ咲線 西九条駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 305000}],
        "features": ["家族葬対応", "地域密着", "駐車場完備"],
        "operator_name": "此花メモリアル",
        "rating_avg": 3.7,
        "review_count": 26
    },
    {
        "name": "小さなお葬式 港ホール",
        "slug": "osaka-chiisana-minato",
        "venue_type": "private_hall",
        "description": "大阪市港区にある小さなお葬式の提携ホール。火葬式から家族葬まで、シンプルで明朗な価格設定で葬儀を提供。必要なものだけを選べるプランが好評です。",
        "address": "大阪府大阪市港区市岡1-2-18",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6720,
        "longitude": 135.4690,
        "nearest_station": "大阪メトロ中央線 弁天町駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 6,
        "facilities": {"式場": True, "親族控室": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 189000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["火葬式対応", "家族葬対応", "明朗会計"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 3.9,
        "review_count": 58
    },
    {
        "name": "家族葬のファミーユ 此花ホール",
        "slug": "osaka-famille-konohana",
        "venue_type": "private_hall",
        "description": "大阪市此花区にある家族葬専門ホール。少人数のお葬式に特化した温かみのある空間で、故人を偲ぶひとときを提供しています。佃斎場へのアクセスも良好です。",
        "address": "大阪府大阪市此花区春日出北2-1-5",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6890,
        "longitude": 135.4480,
        "nearest_station": "阪神なんば線 千鳥橋駅",
        "station_walk_minutes": 8,
        "capacity_max": 35,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "佃斎場近く"],
        "operator_name": "株式会社ファミーユ",
        "rating_avg": 4.0,
        "review_count": 35
    },
    {
        "name": "港区やすらぎ会館",
        "slug": "osaka-minato-yasuragi-kaikan",
        "venue_type": "public_facility",
        "description": "大阪市港区にある公共施設。区民向けの多目的ホールで、小規模な家族葬やお別れの会に利用されています。使用料が低廉で経済的な葬儀が可能です。",
        "address": "大阪府大阪市港区波除3-11-6",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6650,
        "longitude": 135.4580,
        "nearest_station": "大阪メトロ中央線 弁天町駅",
        "station_walk_minutes": 12,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "控室": True, "駐車場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 230000}],
        "features": ["公共施設", "低価格", "少人数対応"],
        "operator_name": "大阪市",
        "rating_avg": 3.5,
        "review_count": 12
    },

    # =============================================
    # 大阪市西成区・浪速区・大正区 (7件)
    # =============================================
    {
        "name": "西成セレモニーホール",
        "slug": "osaka-nishinari-ceremony",
        "venue_type": "private_hall",
        "description": "大阪市西成区にある地域密着型の葬儀会館。大阪メトロ四つ橋線玉出駅から徒歩5分。下町の温かみある雰囲気の中で、家族葬から一般葬まで誠実に対応しています。",
        "address": "大阪府大阪市西成区玉出中2-13-8",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6230,
        "longitude": 135.4880,
        "nearest_station": "大阪メトロ四つ橋線 玉出駅",
        "station_walk_minutes": 5,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "低価格"],
        "operator_name": "西成セレモニー",
        "rating_avg": 3.8,
        "review_count": 28
    },
    {
        "name": "なにわメモリアルホール",
        "slug": "osaka-naniwa-memorial",
        "venue_type": "private_hall",
        "description": "大阪市浪速区にある葬儀会館。なんばエリアにも近い利便性の高い立地。大阪メトロ御堂筋線大国町駅から徒歩5分。家族葬・一般葬に対応し、アクセスの良さが魅力です。",
        "address": "大阪府大阪市浪速区大国1-6-12",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6530,
        "longitude": 135.4980,
        "nearest_station": "大阪メトロ御堂筋線 大国町駅",
        "station_walk_minutes": 5,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "なんば近く"],
        "operator_name": "なにわメモリアル",
        "rating_avg": 4.0,
        "review_count": 52
    },
    {
        "name": "ベルコシティホール大正",
        "slug": "osaka-bellco-taisho",
        "venue_type": "private_hall",
        "description": "大阪市大正区にあるベルコの葬儀会館。JR大阪環状線大正駅から徒歩10分。大正区の中心部に位置し、家族葬・一般葬に対応。沖縄文化の息づく独特の地域性に配慮した葬儀サービスを提供しています。",
        "address": "大阪府大阪市大正区三軒家東1-12-8",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6520,
        "longitude": 135.4740,
        "nearest_station": "JR大阪環状線 大正駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "ベルコグループ"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 3.9,
        "review_count": 42
    },
    {
        "name": "公益社 浪速ホール",
        "slug": "osaka-koeisha-naniwa",
        "venue_type": "private_hall",
        "description": "大阪市浪速区にある公益社の葬儀会館。なんば駅からのアクセスが良く、遠方からの参列者にも便利。格式ある空間で、公益社の高品質なサービスを提供しています。",
        "address": "大阪府大阪市浪速区元町1-5-15",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6580,
        "longitude": 135.5010,
        "nearest_station": "大阪メトロ御堂筋線 なんば駅",
        "station_walk_minutes": 8,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "一般葬対応", "なんば近く", "公益社ブランド"],
        "operator_name": "公益社（燦ホールディングス）",
        "rating_avg": 4.3,
        "review_count": 85
    },
    {
        "name": "大正やすらぎホール",
        "slug": "osaka-taisho-yasuragi",
        "venue_type": "private_hall",
        "description": "大阪市大正区にある地域密着型の葬儀会館。小林斎場にもほど近く、火葬場への移動がスムーズ。下町の温かみのある雰囲気で、家族葬を中心にサービスを提供しています。",
        "address": "大阪府大阪市大正区泉尾1-23-10",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6470,
        "longitude": 135.4760,
        "nearest_station": "大阪メトロ長堀鶴見緑地線 大正駅",
        "station_walk_minutes": 12,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 290000}],
        "features": ["家族葬対応", "小林斎場近く", "地域密着", "低価格"],
        "operator_name": "やすらぎホール",
        "rating_avg": 3.7,
        "review_count": 25
    },
    {
        "name": "ティア浪速",
        "slug": "osaka-tier-naniwa",
        "venue_type": "private_hall",
        "description": "大阪市浪速区にあるティアの家族葬ホール。都心部のなんばエリアにも近く、利便性の高い場所に位置。1日1組貸切で落ち着いた家族葬を執り行えます。",
        "address": "大阪府大阪市浪速区恵美須西3-5-12",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6490,
        "longitude": 135.5050,
        "nearest_station": "大阪メトロ堺筋線 恵美須町駅",
        "station_walk_minutes": 5,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 6,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "1日1組貸切", "駅近", "明朗会計"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.0,
        "review_count": 38
    },
    {
        "name": "小さなお葬式 浪速ホール",
        "slug": "osaka-chiisana-naniwa",
        "venue_type": "private_hall",
        "description": "大阪市浪速区にある小さなお葬式の提携ホール。大阪発祥ブランドの本拠地エリアで、火葬式から家族葬まで明朗価格で提供。コストを抑えた葬儀をお望みの方に最適です。",
        "address": "大阪府大阪市浪速区日本橋東2-3-8",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6560,
        "longitude": 135.5080,
        "nearest_station": "大阪メトロ堺筋線 日本橋駅",
        "station_walk_minutes": 6,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 5,
        "facilities": {"式場": True, "親族控室": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 189000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["火葬式対応", "家族葬対応", "明朗会計", "大阪発祥"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 3.9,
        "review_count": 68
    },

    # =============================================
    # 大阪市西区・東成区 (5件)
    # =============================================
    {
        "name": "公益社 西区ホール",
        "slug": "osaka-koeisha-nishiku",
        "venue_type": "private_hall",
        "description": "大阪市西区にある公益社の葬儀会館。本町エリアのビジネス街にもアクセスが良く、社葬にも対応可能。格式ある空間と充実した設備が特徴です。",
        "address": "大阪府大阪市西区新町1-4-12",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6730,
        "longitude": 135.4920,
        "nearest_station": "大阪メトロ長堀鶴見緑地線 西大橋駅",
        "station_walk_minutes": 5,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "一般葬対応", "社葬対応", "駅近", "公益社ブランド"],
        "operator_name": "公益社（燦ホールディングス）",
        "rating_avg": 4.4,
        "review_count": 78
    },
    {
        "name": "西区メモリアルホール",
        "slug": "osaka-nishiku-memorial",
        "venue_type": "private_hall",
        "description": "大阪市西区にある都市型の葬儀会館。大阪メトロ四つ橋線四ツ橋駅から徒歩4分。コンパクトながら洗練された空間で、家族葬に最適な施設です。",
        "address": "大阪府大阪市西区北堀江1-6-24",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6700,
        "longitude": 135.4950,
        "nearest_station": "大阪メトロ四つ橋線 四ツ橋駅",
        "station_walk_minutes": 4,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 5,
        "facilities": {"式場": True, "親族控室": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["家族葬対応", "都市型", "駅近", "コンパクト"],
        "operator_name": "西区メモリアル",
        "rating_avg": 4.0,
        "review_count": 38
    },
    {
        "name": "ベルコシティホール東成",
        "slug": "osaka-bellco-higashinari",
        "venue_type": "private_hall",
        "description": "大阪市東成区にあるベルコの葬儀会館。大阪メトロ千日前線今里駅から徒歩6分。東成区の住宅街に位置し、家族葬・一般葬に充実した設備で対応しています。",
        "address": "大阪府大阪市東成区大今里西2-1-15",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6680,
        "longitude": 135.5400,
        "nearest_station": "大阪メトロ千日前線 今里駅",
        "station_walk_minutes": 6,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "ベルコグループ"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 45
    },
    {
        "name": "東成メモリアルホール",
        "slug": "osaka-higashinari-memorial",
        "venue_type": "private_hall",
        "description": "大阪市東成区にある地域密着型の葬儀会館。深江エリアの閑静な住宅街に位置し、家族葬を中心に温かなサービスを提供。地元の方々に長年利用されている施設です。",
        "address": "大阪府大阪市東成区深江北2-8-5",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6700,
        "longitude": 135.5520,
        "nearest_station": "大阪メトロ中央線 深江橋駅",
        "station_walk_minutes": 7,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 305000}],
        "features": ["家族葬対応", "地域密着", "駐車場完備"],
        "operator_name": "東成メモリアル",
        "rating_avg": 3.8,
        "review_count": 29
    },
    {
        "name": "家族葬のファミーユ 東成ホール",
        "slug": "osaka-famille-higashinari",
        "venue_type": "private_hall",
        "description": "大阪市東成区にある家族葬専門ホール。大阪メトロ今里筋線今里駅から徒歩8分。少人数のお葬式に特化し、温かみのある空間で故人を偲ぶことができます。",
        "address": "大阪府大阪市東成区大今里南3-12-18",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6620,
        "longitude": 135.5430,
        "nearest_station": "大阪メトロ今里筋線 今里駅",
        "station_walk_minutes": 8,
        "capacity_max": 35,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 6,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "明朗会計"],
        "operator_name": "株式会社ファミーユ",
        "rating_avg": 4.1,
        "review_count": 42
    },

    # =============================================
    # 大阪市 その他の区（各1-3件ずつ）合計32件
    # 北区追加、中央区追加、此花区追加 etc.
    # =============================================

    # 中央区追加
    {
        "name": "心斎橋メモリアルホール",
        "slug": "osaka-shinsaibashi-memorial",
        "venue_type": "private_hall",
        "description": "大阪市中央区心斎橋エリアにある都市型の葬儀会館。大阪メトロ御堂筋線心斎橋駅から徒歩6分。都心部の洗練された空間で、小規模な家族葬やお別れの会に最適です。",
        "address": "大阪府大阪市中央区南船場3-5-8",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6740,
        "longitude": 135.5030,
        "nearest_station": "大阪メトロ御堂筋線 心斎橋駅",
        "station_walk_minutes": 6,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 5,
        "facilities": {"式場": True, "親族控室": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}],
        "features": ["家族葬対応", "都市型", "駅近"],
        "operator_name": "心斎橋メモリアル",
        "rating_avg": 4.1,
        "review_count": 36
    },
    # 中央区寺院
    {
        "name": "法善寺 式場",
        "slug": "osaka-hozenji-shikijo",
        "venue_type": "temple_hall",
        "description": "大阪市中央区のなんばエリアにある寺院式場。法善寺横丁で知られる歴史あるお寺の境内にある式場で、伝統的な仏式葬儀を執り行えます。",
        "address": "大阪府大阪市中央区難波1-2-16",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6620,
        "longitude": 135.5040,
        "nearest_station": "大阪メトロ御堂筋線 なんば駅",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 3,
        "facilities": {"式場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 380000}],
        "features": ["寺院式場", "仏式葬儀", "駅近", "歴史ある寺院"],
        "operator_name": "法善寺",
        "rating_avg": 4.0,
        "review_count": 22
    },
    # 住之江区追加
    {
        "name": "コスモスホール住之江",
        "slug": "osaka-cosmos-suminoe",
        "venue_type": "private_hall",
        "description": "大阪市住之江区にある葬儀会館。南港エリアに近い立地で、駐車場を広く確保。家族葬から一般葬まで対応し、リーズナブルな価格設定が特徴です。",
        "address": "大阪府大阪市住之江区南加賀屋2-5-18",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6100,
        "longitude": 135.4680,
        "nearest_station": "ニュートラム 住之江公園駅",
        "station_walk_minutes": 12,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 285000}],
        "features": ["家族葬対応", "駐車場完備", "リーズナブル"],
        "operator_name": "コスモスホール",
        "rating_avg": 3.7,
        "review_count": 28
    },
    # 西淀川区追加
    {
        "name": "ティア西淀川",
        "slug": "osaka-tier-nishiyodogawa",
        "venue_type": "private_hall",
        "description": "大阪市西淀川区にあるティアの家族葬ホール。佃斎場にも近い場所に位置し、火葬場への移動がスムーズ。1日1組貸切の温かみのある空間です。",
        "address": "大阪府大阪市西淀川区姫里2-8-15",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7140,
        "longitude": 135.4650,
        "nearest_station": "阪神本線 姫島駅",
        "station_walk_minutes": 5,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "1日1組貸切", "佃斎場近く", "駅近"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.0,
        "review_count": 36
    },
    # 天王寺区寺院追加
    {
        "name": "一心寺 式場",
        "slug": "osaka-isshinji-shikijo",
        "venue_type": "temple_hall",
        "description": "大阪市天王寺区にある一心寺の式場。お骨佛（遺骨で造った阿弥陀如来像）で知られる名刹で、境内の式場で仏式葬儀を執り行えます。天王寺エリアのランドマーク的な存在です。",
        "address": "大阪府大阪市天王寺区逢阪2-8-69",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6500,
        "longitude": 135.5100,
        "nearest_station": "大阪メトロ谷町線 四天王寺前夕陽ヶ丘駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "控室": True, "駐車場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 380000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["寺院式場", "仏式葬儀", "名刹", "お骨佛"],
        "operator_name": "一心寺",
        "rating_avg": 4.2,
        "review_count": 55
    },
    # 福島区追加
    {
        "name": "家族葬のファミーユ 福島ホール",
        "slug": "osaka-famille-fukushima",
        "venue_type": "private_hall",
        "description": "大阪市福島区にある家族葬専門ホール。JR福島駅から徒歩5分の好立地。大阪キタエリアからのアクセスが良く、少人数の温かな家族葬を提供しています。",
        "address": "大阪府大阪市福島区福島7-15-4",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6970,
        "longitude": 135.4850,
        "nearest_station": "JR大阪環状線 福島駅",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 6,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "駅近", "少人数対応"],
        "operator_name": "株式会社ファミーユ",
        "rating_avg": 4.2,
        "review_count": 55
    },
    # 旭区追加
    {
        "name": "公益社 旭ホール",
        "slug": "osaka-koeisha-asahi",
        "venue_type": "private_hall",
        "description": "大阪市旭区にある公益社の葬儀会館。京阪森小路駅から徒歩6分。旭区の住宅街に位置し、家族葬から一般葬まで対応。公益社のブランドと信頼のサービスを提供しています。",
        "address": "大阪府大阪市旭区森小路1-5-22",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7250,
        "longitude": 135.5500,
        "nearest_station": "京阪本線 森小路駅",
        "station_walk_minutes": 6,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "公益社ブランド"],
        "operator_name": "公益社（燦ホールディングス）",
        "rating_avg": 4.2,
        "review_count": 52
    },
    # 生野区追加（寺院）
    {
        "name": "真田山 生野寺院式場",
        "slug": "osaka-ikuno-temple-hall",
        "venue_type": "temple_hall",
        "description": "大阪市生野区にある寺院式場。古くから多文化が共存する生野区で、仏式葬儀を伝統的な形式で執り行える場所です。僧侶の手配込みのプランも用意しています。",
        "address": "大阪府大阪市生野区生野東3-5-8",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6460,
        "longitude": 135.5400,
        "nearest_station": "JR大阪環状線 寺田町駅",
        "station_walk_minutes": 12,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 5,
        "facilities": {"式場": True, "控室": True, "駐車場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}],
        "features": ["寺院式場", "仏式葬儀", "地域密着"],
        "operator_name": "生野寺院",
        "rating_avg": 3.7,
        "review_count": 18
    },
    # 平野区追加
    {
        "name": "小さなお葬式 平野ホール",
        "slug": "osaka-chiisana-hirano",
        "venue_type": "private_hall",
        "description": "大阪市平野区にある小さなお葬式の提携ホール。大阪市最大人口の平野区で、リーズナブルな価格の葬儀を提供。火葬式から家族葬まで明朗会計のプランが揃っています。",
        "address": "大阪府大阪市平野区平野上町1-3-15",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6160,
        "longitude": 135.5580,
        "nearest_station": "大阪メトロ谷町線 平野駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 189000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["火葬式対応", "家族葬対応", "明朗会計"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 3.9,
        "review_count": 62
    },
    # 西成区追加
    {
        "name": "ベルコシティホール西成",
        "slug": "osaka-bellco-nishinari",
        "venue_type": "private_hall",
        "description": "大阪市西成区にあるベルコの葬儀会館。大阪メトロ四つ橋線岸里駅から徒歩7分。家族葬・一般葬に対応し、ベルコグループの安定したサービスを提供しています。",
        "address": "大阪府大阪市西成区岸里東1-3-15",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6310,
        "longitude": 135.4950,
        "nearest_station": "大阪メトロ四つ橋線 岸里駅",
        "station_walk_minutes": 7,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "ベルコグループ"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 3.9,
        "review_count": 38
    },
]

# 10件ずつバッチ投入
total = len(venues)
print(f"大阪市 バッチ2: 合計 {total} 件を投入開始")

for i in range(0, total, 10):
    batch = venues[i:i+10]
    status = insert_batch(batch)
    end = min(i+10, total)
    print(f"  [{i+1}-{end}] HTTP {status}")
    if status != "201":
        data_json = json.dumps(batch, ensure_ascii=False)
        result = subprocess.run([
            "curl", "-s",
            "-X", "POST", SUPABASE_URL,
            "-H", f"apikey: {API_KEY}",
            "-H", f"Authorization: Bearer {API_KEY}",
            "-H", "Content-Type: application/json",
            "-H", "Prefer: return=minimal",
            "-H", "User-Agent: Mozilla/5.0",
            "-d", data_json
        ], capture_output=True, text=True)
        print(f"  エラー詳細: {result.stdout[:500]}")
    time.sleep(0.5)

print(f"\nバッチ2完了: {total}件")
