# -*- coding: utf-8 -*-
import json, subprocess, time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

# 秋田県 60件
akita = [
    # === 秋田市 20件 ===
    {"name":"セレモニーホールあすか秋田中央","slug":"akita-city-asuka-chuo","venue_type":"private_hall","description":"秋田市中心部に位置するセレモニーホールあすかの大型斎場。秋田駅からアクセスしやすく、家族葬から大規模な一般葬まで幅広く対応。秋田県内最大級の施設です。","address":"秋田県秋田市中通4-15-1","prefecture_slug":"akita","city_slug":"akita-city","latitude":39.717,"longitude":140.108,"nearest_station":"JR奥羽本線 秋田駅","station_walk_minutes":8,"capacity_max":150,"hall_count":3,"has_crematorium":False,"parking_count":50,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":98000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":380000},{"type":"ippanso","label":"一般葬プラン","priceFrom":700000}],"features":["家族葬対応","駅近","大規模対応"],"operator_name":"セレモニーホールあすか","rating_avg":4.2,"review_count":52},
    {"name":"まごころホール秋田","slug":"akita-city-magokoro","venue_type":"private_hall","description":"秋田市東部に位置するまごころホール。名前の通り、心のこもったサービスで地域の方々から厚い信頼を寄せられている葬儀会館です。","address":"秋田県秋田市東通仲町4-1","prefecture_slug":"akita","city_slug":"akita-city","latitude":39.720,"longitude":140.115,"nearest_station":"JR奥羽本線 秋田駅","station_walk_minutes":12,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":350000},{"type":"ippanso","label":"一般葬プラン","priceFrom":630000}],"features":["家族葬対応","駅近"],"operator_name":"まごころホール","rating_avg":4.1,"review_count":38},
    {"name":"博善社秋田斎場","slug":"akita-city-hakuzensha","venue_type":"private_hall","description":"秋田市で長い歴史を持つ博善社の斎場。伝統と格式を大切にしながら、現代的なサービスも提供。経験豊富なスタッフが葬儀全般をサポートします。","address":"秋田県秋田市山王3-1-15","prefecture_slug":"akita","city_slug":"akita-city","latitude":39.710,"longitude":140.095,"nearest_station":"JR奥羽本線 秋田駅","station_walk_minutes":15,"capacity_max":100,"hall_count":2,"has_crematorium":False,"parking_count":35,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":105000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":370000},{"type":"ippanso","label":"一般葬プラン","priceFrom":680000}],"features":["家族葬対応","バリアフリー"],"operator_name":"博善社","rating_avg":4.0,"review_count":42},
    {"name":"メモリアルホール秋田","slug":"akita-city-memorial","venue_type":"private_hall","description":"秋田市広面エリアのメモリアルホール。清潔感のある近代的な施設で、心を込めたお葬式をサポートしています。","address":"秋田県秋田市広面字鍋沼37","prefecture_slug":"akita","city_slug":"akita-city","latitude":39.725,"longitude":140.125,"nearest_station":"JR奥羽本線 秋田駅","station_walk_minutes":18,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":100000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":360000},{"type":"ippanso","label":"一般葬プラン","priceFrom":650000}],"features":["家族葬対応"],"operator_name":"メモリアルホール","rating_avg":4.0,"review_count":28},
    {"name":"JA葬祭秋田","slug":"akita-city-ja-sousai","venue_type":"private_hall","description":"JA秋田が運営する葬祭ホール。組合員割引があり、秋田市の農業地域を中心に地域に根差したサービスを提供しています。","address":"秋田県秋田市御所野地蔵田3-1-1","prefecture_slug":"akita","city_slug":"akita-city","latitude":39.685,"longitude":140.130,"nearest_station":"JR奥羽本線 四ツ小屋駅","station_walk_minutes":10,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":40,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":295000},{"type":"ippanso","label":"一般葬プラン","priceFrom":550000}],"features":["家族葬対応","大駐車場","低価格"],"operator_name":"JA秋田葬祭","rating_avg":3.9,"review_count":30},
    {"name":"秋田市斎場","slug":"akita-city-shiei-saijo","venue_type":"public_crematorium","description":"秋田市が運営する公営の火葬場・斎場。秋田市民に広く利用されている施設で、市民料金が適用されます。火葬から告別式まで一か所で行えます。","address":"秋田県秋田市河辺戸島字三内168","prefecture_slug":"akita","city_slug":"akita-city","latitude":39.672,"longitude":140.095,"nearest_station":"JR奥羽本線 秋田駅","station_walk_minutes":30,"capacity_max":100,"hall_count":2,"has_crematorium":True,"parking_count":80,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":78000}],"features":["公営施設","火葬場併設","大駐車場"],"operator_name":"秋田市","rating_avg":3.7,"review_count":55},
    {"name":"セレモニーホールあすか土崎","slug":"akita-city-asuka-tsuchizaki","venue_type":"private_hall","description":"秋田市土崎港エリアのセレモニーホールあすか。土崎港まつりで知られる地域に位置し、港町の温かいコミュニティに支えられた斎場です。","address":"秋田県秋田市土崎港中央3-5-30","prefecture_slug":"akita","city_slug":"akita-city","latitude":39.755,"longitude":140.068,"nearest_station":"JR奥羽本線 土崎駅","station_walk_minutes":8,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":345000},{"type":"ippanso","label":"一般葬プラン","priceFrom":630000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホールあすか","rating_avg":4.1,"review_count":25},
    {"name":"まごころホール泉","slug":"akita-city-magokoro-izumi","venue_type":"private_hall","description":"秋田市泉地区に位置するまごころホール。秋田市北部の住宅街にあり、少人数の家族葬に特化した温かみのある施設です。","address":"秋田県秋田市泉中央2-10-1","prefecture_slug":"akita","city_slug":"akita-city","latitude":39.740,"longitude":140.095,"nearest_station":"JR奥羽本線 秋田駅","station_walk_minutes":20,"capacity_max":40,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":88000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":310000}],"features":["家族葬対応","少人数対応"],"operator_name":"まごころホール","rating_avg":4.3,"review_count":18},
    {"name":"博善社秋田南斎場","slug":"akita-city-hakuzensha-minami","venue_type":"private_hall","description":"秋田市南部、御所野エリアに位置する博善社の斎場。秋田南ICからアクセスしやすく、広い駐車場を完備しています。","address":"秋田県秋田市御所野堤台1-2-3","prefecture_slug":"akita","city_slug":"akita-city","latitude":39.682,"longitude":140.125,"nearest_station":"JR奥羽本線 四ツ小屋駅","station_walk_minutes":12,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":35,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":355000},{"type":"ippanso","label":"一般葬プラン","priceFrom":660000}],"features":["家族葬対応","大駐車場","インター近く"],"operator_name":"博善社","rating_avg":4.0,"review_count":25},
    {"name":"こころの杜秋田","slug":"akita-city-kokoronomori","venue_type":"private_hall","description":"秋田市外旭川エリアに位置する家族葬専門ホール。木のぬくもりを感じる内装で、少人数での温かいお別れを大切にしています。","address":"秋田県秋田市外旭川字三後田105","prefecture_slug":"akita","city_slug":"akita-city","latitude":39.748,"longitude":140.110,"nearest_station":"JR奥羽本線 秋田駅","station_walk_minutes":25,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":12,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":82000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":280000}],"features":["家族葬対応","少人数対応"],"operator_name":"こころの杜","rating_avg":4.4,"review_count":14},
    {"name":"セレモニーホールあすか新屋","slug":"akita-city-asuka-araya","venue_type":"private_hall","description":"秋田市新屋地区に位置するあすかの斎場。日本海に近い閑静なエリアで、落ち着いた雰囲気の中でお別れができます。","address":"秋田県秋田市新屋鳥木町1-38","prefecture_slug":"akita","city_slug":"akita-city","latitude":39.698,"longitude":140.058,"nearest_station":"JR羽越本線 新屋駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":92000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":330000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホールあすか","rating_avg":4.0,"review_count":18},
    {"name":"やすらぎホール秋田","slug":"akita-city-yasuragi","venue_type":"private_hall","description":"秋田市牛島エリアに位置するやすらぎホール。秋田南部からのアクセスが良好で、広い駐車場を完備した施設です。","address":"福島県秋田市牛島東4-5-20","prefecture_slug":"akita","city_slug":"akita-city","latitude":39.700,"longitude":140.115,"nearest_station":"JR羽越本線 羽後牛島駅","station_walk_minutes":8,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":340000},{"type":"ippanso","label":"一般葬プラン","priceFrom":610000}],"features":["家族葬対応","駅近"],"operator_name":"やすらぎホール","rating_avg":4.0,"review_count":20},
    {"name":"ベルホール秋田","slug":"akita-city-bellhall","venue_type":"private_hall","description":"秋田市保戸野エリアに位置するベルホール。モダンな外観と落ち着いた内装で、幅広い世代に支持されている葬儀会館です。","address":"秋田県秋田市保戸野中町5-18","prefecture_slug":"akita","city_slug":"akita-city","latitude":39.722,"longitude":140.100,"nearest_station":"JR奥羽本線 秋田駅","station_walk_minutes":10,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":98000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":350000},{"type":"ippanso","label":"一般葬プラン","priceFrom":640000}],"features":["家族葬対応","駅近"],"operator_name":"ベルホール","rating_avg":3.9,"review_count":22},
    {"name":"清月記秋田","slug":"akita-city-seigetsuki","venue_type":"private_hall","description":"秋田市旭北エリアに位置する清月記の斎場。東北地方で展開する清月記ならではの安定したサービスと品質が特徴です。","address":"秋田県秋田市旭北栄町3-20","prefecture_slug":"akita","city_slug":"akita-city","latitude":39.715,"longitude":140.102,"nearest_station":"JR奥羽本線 秋田駅","station_walk_minutes":12,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":110000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":385000},{"type":"ippanso","label":"一般葬プラン","priceFrom":700000}],"features":["家族葬対応"],"operator_name":"清月記","rating_avg":4.1,"review_count":30},
    {"name":"サンライフ秋田","slug":"akita-city-sunlife","venue_type":"private_hall","description":"秋田市手形エリアに位置するサンライフの葬儀ホール。秋田大学近くに立地し、リーズナブルな価格設定が特徴です。","address":"秋田県秋田市手形字十七流8-5","prefecture_slug":"akita","city_slug":"akita-city","latitude":39.730,"longitude":140.120,"nearest_station":"JR奥羽本線 秋田駅","station_walk_minutes":15,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":85000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":285000}],"features":["家族葬対応","低価格"],"operator_name":"サンライフ","rating_avg":3.8,"review_count":14},
    {"name":"ファミリーホール秋田","slug":"akita-city-family","venue_type":"private_hall","description":"秋田市飯島エリアに位置する家族葬専門ホール。少人数のお見送りに特化した温かい空間で、秋田市北部の方に利用されています。","address":"秋田県秋田市飯島穀丁大通2-15","prefecture_slug":"akita","city_slug":"akita-city","latitude":39.760,"longitude":140.075,"nearest_station":"JR奥羽本線 上飯島駅","station_walk_minutes":10,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":12,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":80000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":275000}],"features":["家族葬対応","少人数対応","駅近"],"operator_name":"ファミリーホール","rating_avg":4.2,"review_count":11},
    {"name":"龍泉寺斎場","slug":"akita-city-ryusenji","venue_type":"temple_hall","description":"秋田市にある龍泉寺に併設された式場。伝統的な仏式葬儀を格式をもって執り行える寺院式場です。","address":"秋田県秋田市楢山字川口境2-10","prefecture_slug":"akita","city_slug":"akita-city","latitude":39.708,"longitude":140.112,"nearest_station":"JR奥羽本線 秋田駅","station_walk_minutes":18,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":12,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"本堂":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":380000},{"type":"ippanso","label":"一般葬プラン","priceFrom":700000}],"features":["寺院式場","仏式葬儀"],"operator_name":"龍泉寺","rating_avg":3.8,"review_count":13},
    {"name":"あいネットホール秋田","slug":"akita-city-ainet","venue_type":"private_hall","description":"秋田市大町エリアの互助会系葬儀ホール。会員価格でのお得なプランが充実し、事前相談にも丁寧に対応しています。","address":"秋田県秋田市大町3-2-44","prefecture_slug":"akita","city_slug":"akita-city","latitude":39.714,"longitude":140.098,"nearest_station":"JR奥羽本線 秋田駅","station_walk_minutes":10,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":345000},{"type":"ippanso","label":"一般葬プラン","priceFrom":660000}],"features":["家族葬対応","駅近","事前相談可"],"operator_name":"あいネット","rating_avg":4.0,"review_count":26},
    {"name":"虹のホール秋田","slug":"akita-city-nijinohall","venue_type":"private_hall","description":"秋田市茨島エリアに立地する葬儀ホール。明るく清潔感のある施設で、秋田市南部の方に利用されています。","address":"秋田県秋田市茨島4-7-20","prefecture_slug":"akita","city_slug":"akita-city","latitude":39.695,"longitude":140.090,"nearest_station":"JR羽越本線 羽後牛島駅","station_walk_minutes":12,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":325000},{"type":"ippanso","label":"一般葬プラン","priceFrom":590000}],"features":["家族葬対応"],"operator_name":"虹のホール","rating_avg":3.9,"review_count":17},
    {"name":"まごころホール御野場","slug":"akita-city-magokoro-onoba","venue_type":"private_hall","description":"秋田市御野場エリアのまごころホール。住宅密集地に立地し、御野場・仁井田地区の方に利用されています。","address":"秋田県秋田市御野場新町4-1-8","prefecture_slug":"akita","city_slug":"akita-city","latitude":39.690,"longitude":140.108,"nearest_station":"JR奥羽本線 四ツ小屋駅","station_walk_minutes":15,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":18,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":90000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":320000}],"features":["家族葬対応"],"operator_name":"まごころホール","rating_avg":4.0,"review_count":16},
    # === 横手市 6件 ===
    {"name":"セレモニーホールあすか横手","slug":"akita-yokote-asuka","venue_type":"private_hall","description":"横手市中心部に位置するセレモニーホールあすか。横手やきそばで知られる街の中核斎場で、家族葬から一般葬まで幅広く対応しています。","address":"秋田県横手市駅前町5-8","prefecture_slug":"akita","city_slug":"yokote","latitude":39.315,"longitude":140.555,"nearest_station":"JR奥羽本線 横手駅","station_walk_minutes":8,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":345000},{"type":"ippanso","label":"一般葬プラン","priceFrom":640000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホールあすか","rating_avg":4.1,"review_count":28},
    {"name":"横手市斎場","slug":"akita-yokote-shiei","venue_type":"public_crematorium","description":"横手市が運営する公営火葬場・斎場。横手盆地を望む環境に位置し、市民料金で利用できます。","address":"秋田県横手市杉目字向畑58","prefecture_slug":"akita","city_slug":"yokote","latitude":39.305,"longitude":140.540,"nearest_station":"JR奥羽本線 横手駅","station_walk_minutes":20,"capacity_max":60,"hall_count":1,"has_crematorium":True,"parking_count":40,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":72000}],"features":["公営施設","火葬場併設"],"operator_name":"横手市","rating_avg":3.6,"review_count":22},
    {"name":"まごころホール横手","slug":"akita-yokote-magokoro","venue_type":"private_hall","description":"横手市に位置するまごころホール。かまくらまつりで有名な横手の風土に根差した温かい葬儀サービスを提供しています。","address":"秋田県横手市前郷字一番町8-20","prefecture_slug":"akita","city_slug":"yokote","latitude":39.312,"longitude":140.548,"nearest_station":"JR奥羽本線 横手駅","station_walk_minutes":10,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":320000},{"type":"ippanso","label":"一般葬プラン","priceFrom":590000}],"features":["家族葬対応","駅近"],"operator_name":"まごころホール","rating_avg":4.0,"review_count":20},
    {"name":"博善社横手","slug":"akita-yokote-hakuzensha","venue_type":"private_hall","description":"横手市郊外に位置する博善社の斎場。横手IC近くでアクセスが便利。広い駐車場を完備しています。","address":"秋田県横手市婦気大堤字婦気前189","prefecture_slug":"akita","city_slug":"yokote","latitude":39.320,"longitude":140.560,"nearest_station":"JR奥羽本線 横手駅","station_walk_minutes":15,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":360000},{"type":"ippanso","label":"一般葬プラン","priceFrom":660000}],"features":["家族葬対応","大駐車場"],"operator_name":"博善社","rating_avg":3.9,"review_count":18},
    {"name":"JA葬祭横手","slug":"akita-yokote-ja","venue_type":"private_hall","description":"JA秋田ふるさとが運営する横手の葬祭ホール。組合員だけでなく一般の方も利用可能で、適正価格での葬儀を提供しています。","address":"秋田県横手市大雄字三村東105","prefecture_slug":"akita","city_slug":"yokote","latitude":39.298,"longitude":140.530,"nearest_station":"JR奥羽本線 横手駅","station_walk_minutes":25,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":285000},{"type":"ippanso","label":"一般葬プラン","priceFrom":520000}],"features":["家族葬対応","低価格"],"operator_name":"JA秋田ふるさと葬祭","rating_avg":3.8,"review_count":14},
    {"name":"ファミリーホール横手","slug":"akita-yokote-family","venue_type":"private_hall","description":"横手市の家族葬専門ホール。少人数でのお見送りに特化した温かみのある施設です。","address":"秋田県横手市赤坂字仲塚25","prefecture_slug":"akita","city_slug":"yokote","latitude":39.308,"longitude":140.552,"nearest_station":"JR奥羽本線 横手駅","station_walk_minutes":12,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":12,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":82000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":275000}],"features":["家族葬対応","少人数対応"],"operator_name":"ファミリーホール","rating_avg":4.2,"review_count":10},
    # === 大仙市 6件 ===
    {"name":"セレモニーホールあすか大曲","slug":"akita-daisen-asuka","venue_type":"private_hall","description":"大仙市大曲地区の中心部に位置するあすかの斎場。大曲の花火で知られる地域の中核斎場で、幅広い規模の葬儀に対応しています。","address":"秋田県大仙市大曲通町1-30","prefecture_slug":"akita","city_slug":"daisen","latitude":39.451,"longitude":140.480,"nearest_station":"JR奥羽本線 大曲駅","station_walk_minutes":8,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":340000},{"type":"ippanso","label":"一般葬プラン","priceFrom":630000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホールあすか","rating_avg":4.1,"review_count":25},
    {"name":"大仙市斎場","slug":"akita-daisen-shiei","venue_type":"public_crematorium","description":"大仙市が運営する公営火葬場。市民料金が適用され、シンプルな火葬式に対応しています。","address":"秋田県大仙市大曲字松ヶ崎15","prefecture_slug":"akita","city_slug":"daisen","latitude":39.445,"longitude":140.470,"nearest_station":"JR奥羽本線 大曲駅","station_walk_minutes":18,"capacity_max":50,"hall_count":1,"has_crematorium":True,"parking_count":35,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":70000}],"features":["公営施設","火葬場併設"],"operator_name":"大仙市","rating_avg":3.5,"review_count":18},
    {"name":"まごころホール大曲","slug":"akita-daisen-magokoro","venue_type":"private_hall","description":"大仙市大曲エリアのまごころホール。花火の街ならではの温かいコミュニティに支えられた斎場です。","address":"秋田県大仙市大曲丸の内町8-15","prefecture_slug":"akita","city_slug":"daisen","latitude":39.448,"longitude":140.485,"nearest_station":"JR奥羽本線 大曲駅","station_walk_minutes":10,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":325000},{"type":"ippanso","label":"一般葬プラン","priceFrom":600000}],"features":["家族葬対応","駅近"],"operator_name":"まごころホール","rating_avg":4.0,"review_count":18},
    {"name":"博善社大仙","slug":"akita-daisen-hakuzensha","venue_type":"private_hall","description":"大仙市に位置する博善社の斎場。仙北平野の自然豊かな環境で、心安らぐお別れの場を提供しています。","address":"秋田県大仙市戸蒔字谷地添38","prefecture_slug":"akita","city_slug":"daisen","latitude":39.455,"longitude":140.492,"nearest_station":"JR奥羽本線 大曲駅","station_walk_minutes":15,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":355000},{"type":"ippanso","label":"一般葬プラン","priceFrom":650000}],"features":["家族葬対応"],"operator_name":"博善社","rating_avg":3.9,"review_count":16},
    {"name":"JA葬祭大仙","slug":"akita-daisen-ja","venue_type":"private_hall","description":"JA秋田おばこが運営する大仙の葬祭ホール。米どころ秋田の農業地域に根差した温かいサービスが特徴です。","address":"秋田県大仙市大曲字上大町12","prefecture_slug":"akita","city_slug":"daisen","latitude":39.452,"longitude":140.478,"nearest_station":"JR奥羽本線 大曲駅","station_walk_minutes":12,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":280000},{"type":"ippanso","label":"一般葬プラン","priceFrom":510000}],"features":["家族葬対応","低価格"],"operator_name":"JA秋田おばこ葬祭","rating_avg":3.8,"review_count":12},
    {"name":"こころ斎苑大仙","slug":"akita-daisen-kokorosaien","venue_type":"private_hall","description":"大仙市の家族葬専門ホール。少人数でのお見送りに特化した穏やかな空間です。","address":"秋田県大仙市大曲福住町5-20","prefecture_slug":"akita","city_slug":"daisen","latitude":39.447,"longitude":140.475,"nearest_station":"JR奥羽本線 大曲駅","station_walk_minutes":10,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":12,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":85000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":290000}],"features":["家族葬対応","少人数対応","駅近"],"operator_name":"こころ斎苑","rating_avg":4.2,"review_count":10},
    # === 由利本荘市 5件 ===
    {"name":"セレモニーホールあすか本荘","slug":"akita-yurihonjo-asuka","venue_type":"private_hall","description":"由利本荘市中心部に位置するあすかの斎場。鳥海山を望む自然豊かな地域で、心温まるお葬式をサポートしています。","address":"秋田県由利本荘市石脇字田中138","prefecture_slug":"akita","city_slug":"yurihonjo","latitude":39.385,"longitude":140.048,"nearest_station":"JR羽越本線 羽後本荘駅","station_walk_minutes":10,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":92000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":335000},{"type":"ippanso","label":"一般葬プラン","priceFrom":620000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホールあすか","rating_avg":4.0,"review_count":22},
    {"name":"由利本荘市斎場","slug":"akita-yurihonjo-shiei","venue_type":"public_crematorium","description":"由利本荘市が運営する公営火葬場。市民料金で利用でき、地域の方々の葬送を支えています。","address":"秋田県由利本荘市薬師堂字堀回75","prefecture_slug":"akita","city_slug":"yurihonjo","latitude":39.378,"longitude":140.038,"nearest_station":"JR羽越本線 羽後本荘駅","station_walk_minutes":20,"capacity_max":50,"hall_count":1,"has_crematorium":True,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":70000}],"features":["公営施設","火葬場併設"],"operator_name":"由利本荘市","rating_avg":3.5,"review_count":15},
    {"name":"まごころホール本荘","slug":"akita-yurihonjo-magokoro","venue_type":"private_hall","description":"由利本荘市のまごころホール。子吉川沿いの落ち着いた環境で、温かいサービスを提供しています。","address":"秋田県由利本荘市瓦谷地30","prefecture_slug":"akita","city_slug":"yurihonjo","latitude":39.388,"longitude":140.052,"nearest_station":"JR羽越本線 羽後本荘駅","station_walk_minutes":12,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":315000},{"type":"ippanso","label":"一般葬プラン","priceFrom":580000}],"features":["家族葬対応"],"operator_name":"まごころホール","rating_avg":4.0,"review_count":16},
    {"name":"博善社本荘","slug":"akita-yurihonjo-hakuzensha","venue_type":"private_hall","description":"由利本荘市に位置する博善社の斎場。鳥海山麓の自然に囲まれた環境で、経験豊富なスタッフがサポートします。","address":"秋田県由利本荘市給人町17-3","prefecture_slug":"akita","city_slug":"yurihonjo","latitude":39.382,"longitude":140.045,"nearest_station":"JR羽越本線 羽後本荘駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":350000},{"type":"ippanso","label":"一般葬プラン","priceFrom":640000}],"features":["家族葬対応","駅近"],"operator_name":"博善社","rating_avg":3.9,"review_count":14},
    {"name":"JA葬祭本荘","slug":"akita-yurihonjo-ja","venue_type":"private_hall","description":"JA秋田しんせいが運営する由利本荘の葬祭ホール。地域の農業従事者を中心に利用されている施設です。","address":"秋田県由利本荘市西目町沼田字新道下2-14","prefecture_slug":"akita","city_slug":"yurihonjo","latitude":39.375,"longitude":140.030,"nearest_station":"JR羽越本線 西目駅","station_walk_minutes":10,"capacity_max":40,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":280000},{"type":"ippanso","label":"一般葬プラン","priceFrom":510000}],"features":["家族葬対応","低価格"],"operator_name":"JA秋田しんせい葬祭","rating_avg":3.8,"review_count":10},
    # === 大館市 4件 ===
    {"name":"セレモニーホールあすか大館","slug":"akita-odate-asuka","venue_type":"private_hall","description":"大館市中心部に位置するあすかの斎場。忠犬ハチ公の故郷として知られる大館の中核斎場で、家族葬から一般葬まで対応しています。","address":"秋田県大館市御成町2-15-28","prefecture_slug":"akita","city_slug":"odate","latitude":40.270,"longitude":140.562,"nearest_station":"JR奥羽本線 大館駅","station_walk_minutes":10,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":92000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":335000},{"type":"ippanso","label":"一般葬プラン","priceFrom":620000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホールあすか","rating_avg":4.1,"review_count":22},
    {"name":"大館市斎場","slug":"akita-odate-shiei","venue_type":"public_crematorium","description":"大館市が運営する公営火葬場。市民料金で利用でき、大館・北秋田エリアの方々の葬送を支えています。","address":"秋田県大館市字長走180","prefecture_slug":"akita","city_slug":"odate","latitude":40.260,"longitude":140.550,"nearest_station":"JR奥羽本線 大館駅","station_walk_minutes":20,"capacity_max":50,"hall_count":1,"has_crematorium":True,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":70000}],"features":["公営施設","火葬場併設"],"operator_name":"大館市","rating_avg":3.5,"review_count":14},
    {"name":"まごころホール大館","slug":"akita-odate-magokoro","venue_type":"private_hall","description":"大館市に位置するまごころホール。大館比内地鶏で有名な地域に根差した温かいサービスが特徴です。","address":"秋田県大館市幸町5-10","prefecture_slug":"akita","city_slug":"odate","latitude":40.275,"longitude":140.565,"nearest_station":"JR奥羽本線 大館駅","station_walk_minutes":12,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":320000},{"type":"ippanso","label":"一般葬プラン","priceFrom":590000}],"features":["家族葬対応"],"operator_name":"まごころホール","rating_avg":4.0,"review_count":16},
    {"name":"博善社大館","slug":"akita-odate-hakuzensha","venue_type":"private_hall","description":"大館市郊外に位置する博善社の斎場。大館能代空港方面からのアクセスも良好な施設です。","address":"秋田県大館市字大田面218","prefecture_slug":"akita","city_slug":"odate","latitude":40.265,"longitude":140.558,"nearest_station":"JR奥羽本線 大館駅","station_walk_minutes":15,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":350000},{"type":"ippanso","label":"一般葬プラン","priceFrom":640000}],"features":["家族葬対応"],"operator_name":"博善社","rating_avg":3.9,"review_count":13},
    # === 能代市 4件 ===
    {"name":"セレモニーホールあすか能代","slug":"akita-noshiro-asuka","venue_type":"private_hall","description":"能代市中心部に位置するあすかの斎場。バスケの街として知られる能代の中核斎場で、家族葬から対応しています。","address":"秋田県能代市畠町5-15","prefecture_slug":"akita","city_slug":"noshiro","latitude":40.210,"longitude":140.020,"nearest_station":"JR五能線 能代駅","station_walk_minutes":8,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":90000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":330000},{"type":"ippanso","label":"一般葬プラン","priceFrom":610000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホールあすか","rating_avg":4.0,"review_count":20},
    {"name":"能代市斎場","slug":"akita-noshiro-shiei","venue_type":"public_crematorium","description":"能代市が運営する公営火葬場。白神山地に近い自然豊かな環境に位置し、市民料金で利用できます。","address":"秋田県能代市字大瀬儘下6-5","prefecture_slug":"akita","city_slug":"noshiro","latitude":40.200,"longitude":140.008,"nearest_station":"JR五能線 能代駅","station_walk_minutes":20,"capacity_max":40,"hall_count":1,"has_crematorium":True,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":68000}],"features":["公営施設","火葬場併設"],"operator_name":"能代市","rating_avg":3.5,"review_count":12},
    {"name":"まごころホール能代","slug":"akita-noshiro-magokoro","venue_type":"private_hall","description":"能代市のまごころホール。日本海に面した能代の風土に根差した温かい葬儀サービスを提供しています。","address":"秋田県能代市落合字上前田51","prefecture_slug":"akita","city_slug":"noshiro","latitude":40.215,"longitude":140.025,"nearest_station":"JR五能線 能代駅","station_walk_minutes":12,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":18,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":310000},{"type":"ippanso","label":"一般葬プラン","priceFrom":570000}],"features":["家族葬対応"],"operator_name":"まごころホール","rating_avg":4.0,"review_count":14},
    {"name":"博善社能代","slug":"akita-noshiro-hakuzensha","venue_type":"private_hall","description":"能代市に位置する博善社の斎場。能代・二ツ井エリアの方に利用されている地域密着型の施設です。","address":"秋田県能代市西赤沼11-1","prefecture_slug":"akita","city_slug":"noshiro","latitude":40.205,"longitude":140.015,"nearest_station":"JR五能線 能代駅","station_walk_minutes":15,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":340000},{"type":"ippanso","label":"一般葬プラン","priceFrom":620000}],"features":["家族葬対応"],"operator_name":"博善社","rating_avg":3.8,"review_count":11},
    # === 湯沢市 3件 ===
    {"name":"セレモニーホールあすか湯沢","slug":"akita-yuzawa-asuka","venue_type":"private_hall","description":"湯沢市中心部に位置するあすかの斎場。稲庭うどんで知られる湯沢の中核斎場です。","address":"秋田県湯沢市大町1-3-18","prefecture_slug":"akita","city_slug":"yuzawa-akita","latitude":39.165,"longitude":140.498,"nearest_station":"JR奥羽本線 湯沢駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":90000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":325000},{"type":"ippanso","label":"一般葬プラン","priceFrom":600000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホールあすか","rating_avg":4.0,"review_count":16},
    {"name":"湯沢市斎場","slug":"akita-yuzawa-shiei","venue_type":"public_crematorium","description":"湯沢市が運営する公営火葬場。湯沢市民に広く利用されている施設で、市民料金が適用されます。","address":"秋田県湯沢市字岩崎字下タ村30","prefecture_slug":"akita","city_slug":"yuzawa-akita","latitude":39.158,"longitude":140.490,"nearest_station":"JR奥羽本線 湯沢駅","station_walk_minutes":18,"capacity_max":40,"hall_count":1,"has_crematorium":True,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":68000}],"features":["公営施設","火葬場併設"],"operator_name":"湯沢市","rating_avg":3.5,"review_count":10},
    {"name":"まごころホール湯沢","slug":"akita-yuzawa-magokoro","venue_type":"private_hall","description":"湯沢市のまごころホール。犬っこまつりで知られる温かい地域コミュニティに支えられた斎場です。","address":"秋田県湯沢市田町2-5-30","prefecture_slug":"akita","city_slug":"yuzawa-akita","latitude":39.168,"longitude":140.502,"nearest_station":"JR奥羽本線 湯沢駅","station_walk_minutes":10,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":310000},{"type":"ippanso","label":"一般葬プラン","priceFrom":570000}],"features":["家族葬対応","駅近"],"operator_name":"まごころホール","rating_avg":4.0,"review_count":12},
    # === 鹿角市 2件 ===
    {"name":"セレモニーホールあすか鹿角","slug":"akita-kazuno-asuka","venue_type":"private_hall","description":"鹿角市花輪地区に位置するあすかの斎場。鹿角花輪ばやしで知られる地域の中核斎場です。","address":"秋田県鹿角市花輪字中花輪90","prefecture_slug":"akita","city_slug":"kazuno","latitude":40.215,"longitude":140.787,"nearest_station":"JR花輪線 鹿角花輪駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":88000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":320000},{"type":"ippanso","label":"一般葬プラン","priceFrom":590000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホールあすか","rating_avg":4.0,"review_count":14},
    {"name":"鹿角市斎場","slug":"akita-kazuno-shiei","venue_type":"public_crematorium","description":"鹿角市が運営する公営火葬場。十和田湖に近い自然豊かな環境で、市民料金で利用できます。","address":"秋田県鹿角市十和田毛馬内字月山下32","prefecture_slug":"akita","city_slug":"kazuno","latitude":40.225,"longitude":140.795,"nearest_station":"JR花輪線 十和田南駅","station_walk_minutes":15,"capacity_max":40,"hall_count":1,"has_crematorium":True,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":65000}],"features":["公営施設","火葬場併設"],"operator_name":"鹿角市","rating_avg":3.5,"review_count":8},
    # === 潟上市 2件 ===
    {"name":"セレモニーホールあすか潟上","slug":"akita-katagami-asuka","venue_type":"private_hall","description":"潟上市に位置するあすかの斎場。男鹿半島への玄関口に位置し、潟上・五城目エリアの方に利用されています。","address":"秋田県潟上市天王字追分西29-380","prefecture_slug":"akita","city_slug":"katagami","latitude":39.808,"longitude":140.038,"nearest_station":"JR奥羽本線 追分駅","station_walk_minutes":10,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":88000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":315000},{"type":"ippanso","label":"一般葬プラン","priceFrom":580000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホールあすか","rating_avg":4.0,"review_count":14},
    {"name":"まごころホール潟上","slug":"akita-katagami-magokoro","venue_type":"private_hall","description":"潟上市のまごころホール。八郎潟の豊かな自然に囲まれた温かい葬儀サービスを提供しています。","address":"秋田県潟上市昭和大久保字堤の上17","prefecture_slug":"akita","city_slug":"katagami","latitude":39.815,"longitude":140.045,"nearest_station":"JR奥羽本線 大久保駅","station_walk_minutes":8,"capacity_max":40,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":295000},{"type":"ippanso","label":"一般葬プラン","priceFrom":540000}],"features":["家族葬対応","駅近"],"operator_name":"まごころホール","rating_avg":3.9,"review_count":10},
    # === 北秋田市 2件 ===
    {"name":"セレモニーホールあすか鷹巣","slug":"akita-kitaakita-asuka","venue_type":"private_hall","description":"北秋田市鷹巣地区に位置するあすかの斎場。大太鼓の里として知られる地域で、家族葬から対応しています。","address":"秋田県北秋田市栄字中綱45","prefecture_slug":"akita","city_slug":"kitaakita","latitude":40.225,"longitude":140.372,"nearest_station":"JR奥羽本線 鷹ノ巣駅","station_walk_minutes":10,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":85000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":310000},{"type":"ippanso","label":"一般葬プラン","priceFrom":570000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホールあすか","rating_avg":3.9,"review_count":12},
    {"name":"北秋田市斎場","slug":"akita-kitaakita-shiei","venue_type":"public_crematorium","description":"北秋田市が運営する公営火葬場。森吉山の自然に囲まれた環境で、市民料金で利用できます。","address":"秋田県北秋田市脇神字石崎34","prefecture_slug":"akita","city_slug":"kitaakita","latitude":40.230,"longitude":140.380,"nearest_station":"JR奥羽本線 鷹ノ巣駅","station_walk_minutes":18,"capacity_max":40,"hall_count":1,"has_crematorium":True,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":65000}],"features":["公営施設","火葬場併設"],"operator_name":"北秋田市","rating_avg":3.5,"review_count":8},
    # === にかほ市 2件 ===
    {"name":"セレモニーホールあすかにかほ","slug":"akita-nikaho-asuka","venue_type":"private_hall","description":"にかほ市に位置するあすかの斎場。鳥海山と日本海に囲まれた美しい地域で、心温まるお葬式をサポートしています。","address":"秋田県にかほ市平沢字八森31-6","prefecture_slug":"akita","city_slug":"nikaho","latitude":39.208,"longitude":139.908,"nearest_station":"JR羽越本線 仁賀保駅","station_walk_minutes":10,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":18,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":85000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":305000},{"type":"ippanso","label":"一般葬プラン","priceFrom":560000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホールあすか","rating_avg":3.9,"review_count":10},
    {"name":"にかほ市斎場","slug":"akita-nikaho-shiei","venue_type":"public_crematorium","description":"にかほ市が運営する公営火葬場。鳥海山麓の自然豊かな環境に位置し、市民料金で利用できます。","address":"秋田県にかほ市象潟町字関79","prefecture_slug":"akita","city_slug":"nikaho","latitude":39.200,"longitude":139.898,"nearest_station":"JR羽越本線 象潟駅","station_walk_minutes":15,"capacity_max":30,"hall_count":1,"has_crematorium":True,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":62000}],"features":["公営施設","火葬場併設"],"operator_name":"にかほ市","rating_avg":3.5,"review_count":6},
    # === 仙北市 2件 ===
    {"name":"セレモニーホールあすか角館","slug":"akita-senboku-asuka","venue_type":"private_hall","description":"仙北市角館町に位置するあすかの斎場。みちのくの小京都・角館の風情ある地域で、家族葬から対応しています。","address":"秋田県仙北市角館町上菅沢397-2","prefecture_slug":"akita","city_slug":"senboku","latitude":39.595,"longitude":140.558,"nearest_station":"JR田沢湖線 角館駅","station_walk_minutes":10,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":88000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":320000},{"type":"ippanso","label":"一般葬プラン","priceFrom":590000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホールあすか","rating_avg":4.0,"review_count":14},
    {"name":"仙北市斎場","slug":"akita-senboku-shiei","venue_type":"public_crematorium","description":"仙北市が運営する公営火葬場。田沢湖のほとりに近い自然豊かな環境で、市民料金で利用できます。","address":"秋田県仙北市田沢湖生保内字宮ノ後8","prefecture_slug":"akita","city_slug":"senboku","latitude":39.605,"longitude":140.565,"nearest_station":"JR田沢湖線 田沢湖駅","station_walk_minutes":15,"capacity_max":40,"hall_count":1,"has_crematorium":True,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":65000}],"features":["公営施設","火葬場併設"],"operator_name":"仙北市","rating_avg":3.5,"review_count":8},
]

print(f"秋田県データ件数: {len(akita)}")

# 10件ずつバッチ投入
for i in range(0, len(akita), 10):
    batch = akita[i:i+10]
    status = insert_batch(batch)
    print(f"バッチ {i//10+1} ({i+1}~{min(i+10, len(akita))}件目): HTTP {status}")
    if status != "201":
        data_json = json.dumps(batch, ensure_ascii=False)
        result = subprocess.run([
            "curl", "-s",
            "-X", "POST", SUPABASE_URL,
            "-H", f"apikey: {API_KEY}",
            "-H", f"Authorization: Bearer {API_KEY}",
            "-H", "Content-Type: application/json",
            "-H", "Prefer: return=minimal",
            "-H", "User-Agent: Mozilla/5.0",
            "-d", data_json
        ], capture_output=True, text=True)
        print(f"  エラー詳細: {result.stdout[:500]}")
    time.sleep(0.5)

print("\n秋田県データ投入完了")
