#!/usr/bin/env python3
"""
宮城県の斎場データ バッチ3（46件）- 石巻市・大崎市・名取市・その他の市
"""

import json
import urllib.request
import urllib.error
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

HEADERS = {
    "apikey": API_KEY,
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal",
}

venues = [
    # =============================================
    # 石巻市 (8件)
    # =============================================
    {
        "name": "石巻斎場 清月記",
        "slug": "miyagi-seigetsuki-ishinomaki",
        "venue_type": "private_hall",
        "description": "石巻市南中里に位置する清月記の斎場。石巻エリア最大級の葬儀場で、家族葬から大規模な一般葬まで対応可能。石巻駅から車で約10分のアクセスです。",
        "address": "宮城県石巻市南中里4-7-23",
        "prefecture_slug": "miyagi", "city_slug": "ishinomaki",
        "latitude": 38.419, "longitude": 141.300,
        "nearest_station": "JR仙石線 石巻駅", "station_walk_minutes": 20,
        "capacity_max": 100, "hall_count": 2, "has_crematorium": False, "parking_count": 50,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "バリアフリー", "大規模"],
        "operator_name": "株式会社清月記", "rating_avg": 4.1, "review_count": 20,
    },
    {
        "name": "石巻みなと斎場 清月記",
        "slug": "miyagi-seigetsuki-ishinomaki-minato",
        "venue_type": "private_hall",
        "description": "石巻市湊東に位置する清月記の斎場。石巻港エリアに近く、湊・渡波方面の方に利用されています。家族葬から一般葬まで対応し、地域に密着したサービスを提供。",
        "address": "宮城県石巻市湊東2-6-1",
        "prefecture_slug": "miyagi", "city_slug": "ishinomaki",
        "latitude": 38.415, "longitude": 141.326,
        "nearest_station": "JR仙石線 石巻駅", "station_walk_minutes": 25,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "株式会社清月記", "rating_avg": 4.0, "review_count": 16,
    },
    {
        "name": "石巻大街道斎場 清月記",
        "slug": "miyagi-seigetsuki-ishinomaki-ookaidou",
        "venue_type": "private_hall",
        "description": "石巻市大街道北に位置する清月記の斎場。石巻駅から車で約5分の好アクセス。国道沿いの分かりやすい立地で、石巻市中心部の方に広く利用されています。",
        "address": "宮城県石巻市大街道北3-3-8",
        "prefecture_slug": "miyagi", "city_slug": "ishinomaki",
        "latitude": 38.430, "longitude": 141.302,
        "nearest_station": "JR仙石線 石巻駅", "station_walk_minutes": 15,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 40,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "株式会社清月記", "rating_avg": 4.0, "review_count": 18,
    },
    {
        "name": "密葬館大街道斎場 清月記",
        "slug": "miyagi-seigetsuki-missou-ookaidou",
        "venue_type": "private_hall",
        "description": "清月記が運営する石巻市の家族葬専用ホール。大街道斎場に隣接し、完全貸切型の密葬館。少人数の家族葬に特化した温かみのある空間で、プライバシーに配慮した設計です。",
        "address": "宮城県石巻市大街道北3-3-10",
        "prefecture_slug": "miyagi", "city_slug": "ishinomaki",
        "latitude": 38.430, "longitude": 141.303,
        "nearest_station": "JR仙石線 石巻駅", "station_walk_minutes": 15,
        "capacity_max": 20, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 275000}],
        "features": ["家族葬対応", "1日1組貸切", "少人数向け"],
        "operator_name": "株式会社清月記", "rating_avg": 4.2, "review_count": 11,
    },
    {
        "name": "石巻市斎場",
        "slug": "miyagi-ishinomaki-shisaijo",
        "venue_type": "public_crematorium",
        "description": "石巻市が運営する公営火葬場。石巻市民を中心に火葬場として利用されています。告別室も備えており、火葬式にも対応。市民は割引料金で利用可能です。",
        "address": "宮城県石巻市大瓜字棚橋山1",
        "prefecture_slug": "miyagi", "city_slug": "ishinomaki",
        "latitude": 38.449, "longitude": 141.277,
        "nearest_station": "JR石巻線 前谷地駅", "station_walk_minutes": 30,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": True, "parking_count": 40,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "待合室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}],
        "features": ["火葬場併設", "公営斎場", "バリアフリー"],
        "operator_name": "石巻市", "rating_avg": 3.6, "review_count": 15,
    },
    {
        "name": "家族葬の仙和 石巻ホール",
        "slug": "miyagi-senwa-ishinomaki",
        "venue_type": "private_hall",
        "description": "石巻市に位置する家族葬の仙和の式場。1日1組貸切の家族葬専用ホールで、石巻市の方に利用されています。安置室完備で、家族だけの静かなお別れが可能です。",
        "address": "宮城県石巻市中里3-8-15",
        "prefecture_slug": "miyagi", "city_slug": "ishinomaki",
        "latitude": 38.422, "longitude": 141.299,
        "nearest_station": "JR仙石線 石巻駅", "station_walk_minutes": 12,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 187000}],
        "features": ["家族葬対応", "1日1組貸切"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.1, "review_count": 13,
    },
    {
        "name": "メモリアルホール菩提樹 石巻",
        "slug": "miyagi-bodaiju-ishinomaki",
        "venue_type": "private_hall",
        "description": "石巻市に位置するメモリアルホール菩提樹。石巻駅から車で約8分の立地で、家族葬から一般葬まで対応。落ち着いた雰囲気の中で、心のこもった葬儀を提供しています。",
        "address": "宮城県石巻市蛇田字新上沼70-1",
        "prefecture_slug": "miyagi", "city_slug": "ishinomaki",
        "latitude": 38.437, "longitude": 141.281,
        "nearest_station": "JR仙石線 蛇田駅", "station_walk_minutes": 10,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 40,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "メモリアルホール菩提樹", "rating_avg": 4.0, "review_count": 16,
    },
    {
        "name": "セレモニーホールやもと",
        "slug": "miyagi-ceremony-yamoto",
        "venue_type": "private_hall",
        "description": "石巻市旧矢本エリアに位置するセレモニーホール。JR矢本駅から近い立地で、石巻市東部の方に利用されています。家族葬を中心に、地域に密着したサービスを提供。",
        "address": "宮城県石巻市門脇字浦屋敷40-1",
        "prefecture_slug": "miyagi", "city_slug": "ishinomaki",
        "latitude": 38.413, "longitude": 141.318,
        "nearest_station": "JR仙石線 石巻駅", "station_walk_minutes": 20,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 290000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 500000}],
        "features": ["家族葬対応"],
        "operator_name": "セレモニーホールやもと", "rating_avg": 3.9, "review_count": 12,
    },
    # =============================================
    # 大崎市 (5件)
    # =============================================
    {
        "name": "大崎市斎場",
        "slug": "miyagi-osaki-shisaijo",
        "venue_type": "public_crematorium",
        "description": "大崎市が運営する公営火葬場。古川駅から車で約15分の立地で、大崎市民を中心に利用されています。告別室も備えており、火葬式にも対応可能です。",
        "address": "宮城県大崎市古川小林字新南沢1",
        "prefecture_slug": "miyagi", "city_slug": "osaki",
        "latitude": 38.572, "longitude": 140.958,
        "nearest_station": "JR陸羽東線 古川駅", "station_walk_minutes": 30,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": True, "parking_count": 40,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "待合室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}],
        "features": ["火葬場併設", "公営斎場", "バリアフリー"],
        "operator_name": "大崎市", "rating_avg": 3.6, "review_count": 12,
    },
    {
        "name": "JAいしのまき古川斎場",
        "slug": "miyagi-ja-furukawa-saijo",
        "venue_type": "private_hall",
        "description": "大崎市古川に位置するJA系列の葬儀場。JAいしのまきが運営し、組合員向けの割引プランも用意。古川駅から車で約10分の立地で、大崎市の方に広く利用されています。",
        "address": "宮城県大崎市古川穂波2-8-15",
        "prefecture_slug": "miyagi", "city_slug": "osaki",
        "latitude": 38.578, "longitude": 140.960,
        "nearest_station": "JR陸羽東線 古川駅", "station_walk_minutes": 15,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 40,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 520000}],
        "features": ["家族葬対応", "バリアフリー", "JA組合員割引"],
        "operator_name": "JAいしのまき", "rating_avg": 3.9, "review_count": 15,
    },
    {
        "name": "大崎セレモニーホール",
        "slug": "miyagi-osaki-ceremony-hall",
        "venue_type": "private_hall",
        "description": "大崎市古川に位置するセレモニーホール。古川駅から車で約8分の立地。家族葬から一般葬まで対応し、大崎平野エリアの方に広く利用されている地域の代表的な葬儀場です。",
        "address": "宮城県大崎市古川李埣3-5-20",
        "prefecture_slug": "miyagi", "city_slug": "osaki",
        "latitude": 38.575, "longitude": 140.952,
        "nearest_station": "JR陸羽東線 古川駅", "station_walk_minutes": 12,
        "capacity_max": 100, "hall_count": 2, "has_crematorium": False, "parking_count": 50,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "大崎セレモニー", "rating_avg": 4.0, "review_count": 17,
    },
    {
        "name": "家族葬のファミーユ大崎",
        "slug": "miyagi-famille-osaki",
        "venue_type": "private_hall",
        "description": "大崎市に位置する家族葬のファミーユ。1日1組貸切の家族葬専用ホールで、少人数の温かい葬儀に特化。古川エリアの方に利用されています。",
        "address": "宮城県大崎市古川沢田字新大崎5-2",
        "prefecture_slug": "miyagi", "city_slug": "osaki",
        "latitude": 38.580, "longitude": 140.966,
        "nearest_station": "JR陸羽東線 古川駅", "station_walk_minutes": 15,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["家族葬対応", "1日1組貸切", "少人数向け"],
        "operator_name": "家族葬のファミーユ", "rating_avg": 4.1, "review_count": 11,
    },
    {
        "name": "鳴子温泉メモリアルホール",
        "slug": "miyagi-naruko-memorial",
        "venue_type": "private_hall",
        "description": "大崎市鳴子温泉エリアに位置するメモリアルホール。鳴子温泉駅から近い立地で、鳴子・岩出山エリアの方に利用されています。家族葬を中心にサービスを提供。",
        "address": "宮城県大崎市鳴子温泉字町58-1",
        "prefecture_slug": "miyagi", "city_slug": "osaki",
        "latitude": 38.731, "longitude": 140.728,
        "nearest_station": "JR陸羽東線 鳴子温泉駅", "station_walk_minutes": 8,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 275000}],
        "features": ["家族葬対応", "駅近"],
        "operator_name": "鳴子メモリアル", "rating_avg": 3.8, "review_count": 9,
    },
    # =============================================
    # 名取市 (4件)
    # =============================================
    {
        "name": "名取市斎場",
        "slug": "miyagi-natori-shisaijo",
        "venue_type": "public_crematorium",
        "description": "名取市が運営する公営火葬場。名取市民を中心に利用されており、告別室も備えています。館腰駅から車で約10分の立地で、静かな環境の中にあります。",
        "address": "宮城県名取市愛島笠島字東谷地100",
        "prefecture_slug": "miyagi", "city_slug": "natori",
        "latitude": 38.161, "longitude": 140.862,
        "nearest_station": "JR東北本線 館腰駅", "station_walk_minutes": 20,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": True, "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "待合室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}],
        "features": ["火葬場併設", "公営斎場", "バリアフリー"],
        "operator_name": "名取市", "rating_avg": 3.6, "review_count": 13,
    },
    {
        "name": "みおくり邸宅 名取",
        "slug": "miyagi-miokuri-natori",
        "venue_type": "private_hall",
        "description": "名取市に位置する家族葬専用のみおくり邸宅。一軒家風の温かみある空間で、家族だけの静かなお見送りに最適。名取駅から車で約5分のアクセスです。",
        "address": "宮城県名取市増田4-2-20",
        "prefecture_slug": "miyagi", "city_slug": "natori",
        "latitude": 38.173, "longitude": 140.887,
        "nearest_station": "JR東北本線 名取駅", "station_walk_minutes": 10,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬対応", "1日1組貸切", "少人数向け"],
        "operator_name": "みおくり邸宅", "rating_avg": 4.3, "review_count": 14,
    },
    {
        "name": "名取セレモニーホール",
        "slug": "miyagi-natori-ceremony",
        "venue_type": "private_hall",
        "description": "名取市に位置するセレモニーホール。名取駅から車で約7分の立地で、名取市・岩沼市エリアの方に利用されています。家族葬から一般葬まで対応可能です。",
        "address": "宮城県名取市大手町5-8-10",
        "prefecture_slug": "miyagi", "city_slug": "natori",
        "latitude": 38.170, "longitude": 140.891,
        "nearest_station": "JR東北本線 名取駅", "station_walk_minutes": 12,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 35,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "名取セレモニー", "rating_avg": 4.0, "review_count": 16,
    },
    {
        "name": "家族葬の仙和 名取ホール",
        "slug": "miyagi-senwa-natori",
        "venue_type": "private_hall",
        "description": "名取市に位置する家族葬の仙和の式場。1日1組貸切の家族葬専用ホールで、名取駅から近い立地。安置室完備で、少人数のお見送りに最適です。",
        "address": "宮城県名取市飯野坂3-5-12",
        "prefecture_slug": "miyagi", "city_slug": "natori",
        "latitude": 38.176, "longitude": 140.882,
        "nearest_station": "JR東北本線 名取駅", "station_walk_minutes": 8,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["家族葬対応", "1日1組貸切", "駅近"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.1, "review_count": 12,
    },
    # =============================================
    # 多賀城市 (3件)
    # =============================================
    {
        "name": "多賀城セレモニーホール",
        "slug": "miyagi-tagajo-ceremony",
        "venue_type": "private_hall",
        "description": "多賀城市に位置するセレモニーホール。多賀城駅から車で約5分の立地で、多賀城市・塩竈市エリアの方に利用されています。家族葬から一般葬まで対応可能です。",
        "address": "宮城県多賀城市中央2-8-1",
        "prefecture_slug": "miyagi", "city_slug": "tagajo",
        "latitude": 38.295, "longitude": 140.981,
        "nearest_station": "JR仙石線 多賀城駅", "station_walk_minutes": 8,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "駅近", "バリアフリー"],
        "operator_name": "多賀城セレモニー", "rating_avg": 4.0, "review_count": 15,
    },
    {
        "name": "家族葬の仙和 多賀城ホール",
        "slug": "miyagi-senwa-tagajo",
        "venue_type": "private_hall",
        "description": "多賀城市に位置する家族葬の仙和の式場。1日1組貸切の家族葬専用ホールで、多賀城駅から近い立地。安置室完備で、少人数の家族葬に対応しています。",
        "address": "宮城県多賀城市町前3-1-15",
        "prefecture_slug": "miyagi", "city_slug": "tagajo",
        "latitude": 38.296, "longitude": 140.979,
        "nearest_station": "JR仙石線 多賀城駅", "station_walk_minutes": 5,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["家族葬対応", "1日1組貸切", "駅近"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.1, "review_count": 11,
    },
    {
        "name": "ほこだて仏光堂 多賀城ホール",
        "slug": "miyagi-hokodate-tagajo",
        "venue_type": "private_hall",
        "description": "多賀城市に位置するほこだて仏光堂の葬儀ホール。仏壇・仏具の老舗が運営する葬儀場で、伝統を大切にした葬儀を提供。多賀城市の方に利用されています。",
        "address": "宮城県多賀城市八幡2-5-20",
        "prefecture_slug": "miyagi", "city_slug": "tagajo",
        "latitude": 38.301, "longitude": 140.974,
        "nearest_station": "JR仙石線 多賀城駅", "station_walk_minutes": 10,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "ほこだて仏光堂", "rating_avg": 3.9, "review_count": 12,
    },
    # =============================================
    # 塩竈市 (3件)
    # =============================================
    {
        "name": "塩竈市斎場",
        "slug": "miyagi-shiogama-shisaijo",
        "venue_type": "public_crematorium",
        "description": "塩竈市が運営する公営火葬場。塩竈市・多賀城市・松島町・七ヶ浜町・利府町の住民が利用可能。告別室や待合室も備えた充実した施設です。",
        "address": "宮城県塩竈市袖野田町25-1",
        "prefecture_slug": "miyagi", "city_slug": "shiogama",
        "latitude": 38.318, "longitude": 141.019,
        "nearest_station": "JR仙石線 本塩釜駅", "station_walk_minutes": 15,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": True, "parking_count": 40,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "待合室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}],
        "features": ["火葬場併設", "公営斎場", "バリアフリー"],
        "operator_name": "塩竈市", "rating_avg": 3.7, "review_count": 14,
    },
    {
        "name": "塩竈セレモニーホール",
        "slug": "miyagi-shiogama-ceremony",
        "venue_type": "private_hall",
        "description": "塩竈市に位置するセレモニーホール。本塩釜駅から近い立地で、塩竈市・松島町エリアの方に利用されています。家族葬から一般葬まで対応可能な設備を備えています。",
        "address": "宮城県塩竈市海岸通4-15",
        "prefecture_slug": "miyagi", "city_slug": "shiogama",
        "latitude": 38.315, "longitude": 141.022,
        "nearest_station": "JR仙石線 本塩釜駅", "station_walk_minutes": 7,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "駅近", "バリアフリー"],
        "operator_name": "塩竈セレモニー", "rating_avg": 4.0, "review_count": 15,
    },
    {
        "name": "家族葬の仙和 塩竈ホール",
        "slug": "miyagi-senwa-shiogama",
        "venue_type": "private_hall",
        "description": "塩竈市に位置する家族葬の仙和の式場。1日1組貸切の家族葬専用ホール。塩竈市・多賀城市の方に利用されており、安置室完備の温かみある空間です。",
        "address": "宮城県塩竈市新浜町2-25-10",
        "prefecture_slug": "miyagi", "city_slug": "shiogama",
        "latitude": 38.314, "longitude": 141.016,
        "nearest_station": "JR仙石線 本塩釜駅", "station_walk_minutes": 10,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["家族葬対応", "1日1組貸切"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.0, "review_count": 10,
    },
    # =============================================
    # 登米市 (3件)
    # =============================================
    {
        "name": "登米市斎場",
        "slug": "miyagi-tome-shisaijo",
        "venue_type": "public_crematorium",
        "description": "登米市が運営する公営火葬場。登米市全域の住民に利用されています。告別室も備えており、火葬式にも対応。静かな環境の中にある落ち着いた施設です。",
        "address": "宮城県登米市迫町佐沼字江合1-6-1",
        "prefecture_slug": "miyagi", "city_slug": "tome",
        "latitude": 38.683, "longitude": 141.195,
        "nearest_station": "JR東北本線 新田駅", "station_walk_minutes": 30,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 70000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "登米市", "rating_avg": 3.5, "review_count": 10,
    },
    {
        "name": "登米セレモニーホール",
        "slug": "miyagi-tome-ceremony",
        "venue_type": "private_hall",
        "description": "登米市迫町に位置するセレモニーホール。登米市の中心部にあり、家族葬から一般葬まで対応。地域に密着したきめ細かいサービスを提供しています。",
        "address": "宮城県登米市迫町佐沼字中江4-8-15",
        "prefecture_slug": "miyagi", "city_slug": "tome",
        "latitude": 38.685, "longitude": 141.198,
        "nearest_station": "JR東北本線 新田駅", "station_walk_minutes": 25,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 290000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 500000}],
        "features": ["家族葬対応"],
        "operator_name": "登米セレモニー", "rating_avg": 3.8, "review_count": 12,
    },
    {
        "name": "家族葬の仙和 登米ホール",
        "slug": "miyagi-senwa-tome",
        "venue_type": "private_hall",
        "description": "登米市に位置する家族葬の仙和の式場。1日1組貸切の家族葬専用ホールで、登米市の方に利用されています。安置室完備の温かみあるホールです。",
        "address": "宮城県登米市迫町佐沼字内町40-5",
        "prefecture_slug": "miyagi", "city_slug": "tome",
        "latitude": 38.687, "longitude": 141.194,
        "nearest_station": "JR東北本線 新田駅", "station_walk_minutes": 25,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["家族葬対応", "1日1組貸切"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.0, "review_count": 9,
    },
    # =============================================
    # 栗原市 (2件)
    # =============================================
    {
        "name": "栗原市三の迫斎苑",
        "slug": "miyagi-kurihara-sanoen",
        "venue_type": "public_crematorium",
        "description": "栗原市が運営する公営火葬場。栗原市全域の住民に利用されています。自然豊かな環境の中に位置し、静かな雰囲気で故人をお見送りできます。",
        "address": "宮城県栗原市築館字萩沢二ノ丁3-1",
        "prefecture_slug": "miyagi", "city_slug": "kurihara",
        "latitude": 38.730, "longitude": 141.020,
        "nearest_station": "JR東北新幹線 くりこま高原駅", "station_walk_minutes": 30,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 70000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "栗原市", "rating_avg": 3.5, "review_count": 8,
    },
    {
        "name": "栗原メモリアルホール",
        "slug": "miyagi-kurihara-memorial",
        "venue_type": "private_hall",
        "description": "栗原市築館に位置するメモリアルホール。くりこま高原駅から車で約10分の立地。家族葬から一般葬まで対応し、栗原市の方に広く利用されています。",
        "address": "宮城県栗原市築館字伊豆2-6-15",
        "prefecture_slug": "miyagi", "city_slug": "kurihara",
        "latitude": 38.733, "longitude": 141.017,
        "nearest_station": "JR東北新幹線 くりこま高原駅", "station_walk_minutes": 20,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 480000}],
        "features": ["家族葬対応"],
        "operator_name": "栗原メモリアル", "rating_avg": 3.8, "review_count": 11,
    },
    # =============================================
    # 気仙沼市 (2件)
    # =============================================
    {
        "name": "気仙沼市斎場",
        "slug": "miyagi-kesennuma-shisaijo",
        "venue_type": "public_crematorium",
        "description": "気仙沼市が運営する公営火葬場。気仙沼市全域の住民に利用されており、三陸海岸エリアの主要な火葬場。告別室も備えた施設です。",
        "address": "宮城県気仙沼市赤岩杉ノ沢47-6",
        "prefecture_slug": "miyagi", "city_slug": "kesennuma",
        "latitude": 38.907, "longitude": 141.569,
        "nearest_station": "JR大船渡BRT 気仙沼駅", "station_walk_minutes": 20,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 70000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "気仙沼市", "rating_avg": 3.5, "review_count": 9,
    },
    {
        "name": "気仙沼セレモニーホール",
        "slug": "miyagi-kesennuma-ceremony",
        "venue_type": "private_hall",
        "description": "気仙沼市に位置するセレモニーホール。気仙沼駅から車で約10分の立地で、気仙沼市の方に広く利用されています。家族葬から一般葬まで対応し、地域に密着したサービスを提供。",
        "address": "宮城県気仙沼市古町3-4-25",
        "prefecture_slug": "miyagi", "city_slug": "kesennuma",
        "latitude": 38.908, "longitude": 141.572,
        "nearest_station": "JR大船渡BRT 気仙沼駅", "station_walk_minutes": 15,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 290000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 500000}],
        "features": ["家族葬対応"],
        "operator_name": "気仙沼セレモニー", "rating_avg": 3.9, "review_count": 12,
    },
    # =============================================
    # 岩沼市 (2件)
    # =============================================
    {
        "name": "岩沼市斎場",
        "slug": "miyagi-iwanuma-shisaijo",
        "venue_type": "public_crematorium",
        "description": "岩沼市が運営する公営火葬場。岩沼市・亘理町の住民に利用されており、仙南地域の主要な火葬場の一つ。告別室も備えた施設です。",
        "address": "宮城県岩沼市三色吉字雷神山7-1",
        "prefecture_slug": "miyagi", "city_slug": "iwanuma",
        "latitude": 38.113, "longitude": 140.868,
        "nearest_station": "JR東北本線 岩沼駅", "station_walk_minutes": 20,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 25,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "岩沼市", "rating_avg": 3.5, "review_count": 9,
    },
    {
        "name": "岩沼セレモニーホール",
        "slug": "miyagi-iwanuma-ceremony",
        "venue_type": "private_hall",
        "description": "岩沼市に位置するセレモニーホール。岩沼駅から車で約5分の立地で、岩沼市・亘理町エリアの方に利用されています。家族葬から一般葬まで対応。",
        "address": "宮城県岩沼市桜3-5-12",
        "prefecture_slug": "miyagi", "city_slug": "iwanuma",
        "latitude": 38.107, "longitude": 140.873,
        "nearest_station": "JR東北本線 岩沼駅", "station_walk_minutes": 10,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 520000}],
        "features": ["家族葬対応"],
        "operator_name": "岩沼セレモニー", "rating_avg": 3.9, "review_count": 11,
    },
    # =============================================
    # 白石市 (2件)
    # =============================================
    {
        "name": "白石斎苑",
        "slug": "miyagi-shiroishi-saien",
        "venue_type": "public_crematorium",
        "description": "白石市が運営する公営火葬場。白石市・蔵王町・七ヶ宿町の住民に利用されています。白石蔵王駅から車で約15分の立地。告別室も備えています。",
        "address": "宮城県白石市鷹巣字石倉9-3",
        "prefecture_slug": "miyagi", "city_slug": "shiroishi",
        "latitude": 38.004, "longitude": 140.624,
        "nearest_station": "JR東北本線 白石駅", "station_walk_minutes": 25,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 25,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 70000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "白石市", "rating_avg": 3.5, "review_count": 8,
    },
    {
        "name": "白石メモリアルホール",
        "slug": "miyagi-shiroishi-memorial",
        "venue_type": "private_hall",
        "description": "白石市に位置するメモリアルホール。白石駅から車で約10分の立地で、白石市・蔵王町エリアの方に利用されています。家族葬から一般葬まで対応。",
        "address": "宮城県白石市沢端町3-25",
        "prefecture_slug": "miyagi", "city_slug": "shiroishi",
        "latitude": 38.002, "longitude": 140.620,
        "nearest_station": "JR東北本線 白石駅", "station_walk_minutes": 10,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 480000}],
        "features": ["家族葬対応"],
        "operator_name": "白石メモリアル", "rating_avg": 3.8, "review_count": 10,
    },
    # =============================================
    # 角田市 (1件)
    # =============================================
    {
        "name": "角田セレモニーホール",
        "slug": "miyagi-kakuda-ceremony",
        "venue_type": "private_hall",
        "description": "角田市に位置するセレモニーホール。角田駅から車で約5分の立地で、角田市・丸森町エリアの方に利用されています。家族葬から一般葬まで対応可能です。",
        "address": "宮城県角田市角田字牛舘10-5",
        "prefecture_slug": "miyagi", "city_slug": "kakuda",
        "latitude": 37.975, "longitude": 140.781,
        "nearest_station": "阿武隈急行 角田駅", "station_walk_minutes": 10,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 480000}],
        "features": ["家族葬対応"],
        "operator_name": "角田セレモニー", "rating_avg": 3.8, "review_count": 10,
    },
    # =============================================
    # 東松島市 (2件)
    # =============================================
    {
        "name": "メモリアルホール菩提樹 矢本館",
        "slug": "miyagi-bodaiju-yamoto",
        "venue_type": "private_hall",
        "description": "東松島市矢本に位置するメモリアルホール菩提樹。矢本駅から車で約5分の立地で、東松島市の方に広く利用されています。家族葬から一般葬まで対応可能。",
        "address": "宮城県東松島市矢本字上河戸36-1",
        "prefecture_slug": "miyagi", "city_slug": "higashimatsushima",
        "latitude": 38.428, "longitude": 141.213,
        "nearest_station": "JR仙石線 矢本駅", "station_walk_minutes": 10,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 530000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "メモリアルホール菩提樹", "rating_avg": 4.0, "review_count": 14,
    },
    {
        "name": "河南地区葬祭場",
        "slug": "miyagi-kanan-sousaijo",
        "venue_type": "public_facility",
        "description": "東松島市河南地区に位置する公共の葬祭場。地域の方に利用されている施設で、リーズナブルな価格で葬儀が行えます。家族葬に適した施設です。",
        "address": "宮城県東松島市小野字新宮前5-1",
        "prefecture_slug": "miyagi", "city_slug": "higashimatsushima",
        "latitude": 38.441, "longitude": 141.189,
        "nearest_station": "JR仙石線 鹿妻駅", "station_walk_minutes": 15,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 200000}],
        "features": ["家族葬対応", "公共施設", "低価格"],
        "operator_name": "東松島市", "rating_avg": 3.6, "review_count": 8,
    },
    # =============================================
    # 富谷市 (2件)
    # =============================================
    {
        "name": "富谷斎場 清月記",
        "slug": "miyagi-seigetsuki-tomiya",
        "venue_type": "private_hall",
        "description": "富谷市鷹乃杜に位置する清月記の斎場。仙台市泉区に隣接し、富谷市・大和町エリアの方に利用されています。家族葬から一般葬まで対応可能です。",
        "address": "宮城県富谷市鷹乃杜2-1-10",
        "prefecture_slug": "miyagi", "city_slug": "tomiya",
        "latitude": 38.352, "longitude": 140.896,
        "nearest_station": "地下鉄南北線 泉中央駅", "station_walk_minutes": 30,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 40,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "株式会社清月記", "rating_avg": 4.0, "review_count": 15,
    },
    {
        "name": "家族葬の仙和 富谷ホール",
        "slug": "miyagi-senwa-tomiya",
        "venue_type": "private_hall",
        "description": "富谷市に位置する家族葬の仙和の式場。1日1組貸切の家族葬専用ホールで、富谷市の方に利用されています。安置室完備で、少人数のお見送りに最適です。",
        "address": "宮城県富谷市成田3-32-15",
        "prefecture_slug": "miyagi", "city_slug": "tomiya",
        "latitude": 38.347, "longitude": 140.893,
        "nearest_station": "地下鉄南北線 泉中央駅", "station_walk_minutes": 25,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["家族葬対応", "1日1組貸切"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.1, "review_count": 10,
    },
]

def insert_batch(batch):
    data_json = json.dumps(batch, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(SUPABASE_URL, data=data_json, headers=HEADERS, method="POST")
    try:
        with urllib.request.urlopen(req) as resp:
            return resp.status
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"  HTTPError {e.code}: {body[:300]}")
        return e.code

total = 0
batch_size = 10
for i in range(0, len(venues), batch_size):
    batch = venues[i:i+batch_size]
    code = insert_batch(batch)
    total += len(batch)
    print(f"バッチ {i//batch_size+1}: {len(batch)}件 → HTTP {code} (累計 {total}件)")
    time.sleep(0.5)

print(f"\n完了: 合計 {total}件 投入")
