#!/usr/bin/env python3
"""
大阪府の斎場データ バッチ4: 東大阪市15件 + 枚方市12件 + 豊中市10件 + 吹田市8件 = 45件
"""
import json
import subprocess
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

venues = [
    # =============================================
    # 東大阪市（higashiosaka）: 15件
    # =============================================
    {
        "name": "東大阪市立斎場",
        "slug": "osaka-higashiosaka-shiritsu-saijo",
        "venue_type": "public_crematorium",
        "description": "東大阪市にある公営の斎場・火葬場。東大阪市民は使用料が減額されます。火葬炉と式場を備え、通夜から火葬まで同一施設で執り行えます。近鉄奈良線瓢箪山駅からバスでアクセス可能。",
        "address": "大阪府東大阪市六万寺町3-8-1",
        "prefecture_slug": "osaka",
        "city_slug": "higashiosaka",
        "latitude": 34.6620,
        "longitude": 135.6170,
        "nearest_station": "近鉄奈良線 瓢箪山駅",
        "station_walk_minutes": 20,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 60,
        "facilities": {"式場": True, "休憩室": True, "駐車場": True, "バリアフリー": True, "霊安室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}],
        "features": ["火葬場併設", "公営斎場", "市民割引", "駐車場完備"],
        "operator_name": "東大阪市",
        "rating_avg": 3.8,
        "review_count": 65
    },
    {
        "name": "公益社 東大阪ホール",
        "slug": "osaka-koeisha-higashiosaka",
        "venue_type": "private_hall",
        "description": "東大阪市にある公益社の葬儀会館。近鉄奈良線布施駅から徒歩8分。東大阪市の中心部に位置し、家族葬から一般葬まで公益社の高品質なサービスを提供しています。",
        "address": "大阪府東大阪市長堂1-5-6",
        "prefecture_slug": "osaka",
        "city_slug": "higashiosaka",
        "latitude": 34.6640,
        "longitude": 135.5720,
        "nearest_station": "近鉄奈良線 布施駅",
        "station_walk_minutes": 8,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "公益社ブランド"],
        "operator_name": "公益社（燦ホールディングス）",
        "rating_avg": 4.3,
        "review_count": 82
    },
    {
        "name": "ベルコシティホール東大阪",
        "slug": "osaka-bellco-higashiosaka",
        "venue_type": "private_hall",
        "description": "東大阪市にあるベルコの葬儀会館。近鉄けいはんな線荒本駅から徒歩10分。東大阪市役所にも近い場所で、家族葬・一般葬に対応した充実の設備を備えています。",
        "address": "大阪府東大阪市荒本北1-4-2",
        "prefecture_slug": "osaka",
        "city_slug": "higashiosaka",
        "latitude": 34.6780,
        "longitude": 135.5920,
        "nearest_station": "近鉄けいはんな線 荒本駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "ベルコグループ"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 55
    },
    {
        "name": "家族葬のファミーユ 東大阪ホール",
        "slug": "osaka-famille-higashiosaka",
        "venue_type": "private_hall",
        "description": "東大阪市にある家族葬専門ホール。近鉄奈良線河内小阪駅から徒歩7分。モノづくりの町・東大阪で、温かみのある少人数の葬儀を提供しています。",
        "address": "大阪府東大阪市小阪1-8-12",
        "prefecture_slug": "osaka",
        "city_slug": "higashiosaka",
        "latitude": 34.6600,
        "longitude": 135.5800,
        "nearest_station": "近鉄奈良線 河内小阪駅",
        "station_walk_minutes": 7,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "駅近", "明朗会計"],
        "operator_name": "株式会社ファミーユ",
        "rating_avg": 4.2,
        "review_count": 62
    },
    {
        "name": "ティア東大阪",
        "slug": "osaka-tier-higashiosaka",
        "venue_type": "private_hall",
        "description": "東大阪市にあるティアの葬儀会館。近鉄大阪線長瀬駅から徒歩8分。1日1組貸切の家族葬に対応し、明朗会計と丁寧なスタッフ対応が特徴です。",
        "address": "大阪府東大阪市長瀬町2-3-15",
        "prefecture_slug": "osaka",
        "city_slug": "higashiosaka",
        "latitude": 34.6520,
        "longitude": 135.5760,
        "nearest_station": "近鉄大阪線 長瀬駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "1日1組貸切", "明朗会計"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.1,
        "review_count": 48
    },
    {
        "name": "小さなお葬式 東大阪ホール",
        "slug": "osaka-chiisana-higashiosaka",
        "venue_type": "private_hall",
        "description": "東大阪市にある小さなお葬式の提携ホール。火葬式から家族葬まで明朗価格で提供。東大阪市民に愛されるリーズナブルな葬儀プランが特徴です。",
        "address": "大阪府東大阪市高井田元町1-2-8",
        "prefecture_slug": "osaka",
        "city_slug": "higashiosaka",
        "latitude": 34.6700,
        "longitude": 135.5680,
        "nearest_station": "大阪メトロ中央線 高井田駅",
        "station_walk_minutes": 6,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 189000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["火葬式対応", "家族葬対応", "駅近", "明朗会計"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 3.9,
        "review_count": 58
    },
    {
        "name": "布施メモリアルホール",
        "slug": "osaka-fuse-memorial",
        "venue_type": "private_hall",
        "description": "東大阪市の布施エリアにある葬儀会館。近鉄布施駅から徒歩5分の好立地。下町の温かみのある雰囲気の中で、家族葬から一般葬まで対応しています。",
        "address": "大阪府東大阪市足代2-3-6",
        "prefecture_slug": "osaka",
        "city_slug": "higashiosaka",
        "latitude": 34.6650,
        "longitude": 135.5700,
        "nearest_station": "近鉄奈良線 布施駅",
        "station_walk_minutes": 5,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "地域密着"],
        "operator_name": "布施メモリアル",
        "rating_avg": 4.0,
        "review_count": 45
    },
    {
        "name": "泉屋 東大阪ホール",
        "slug": "osaka-izumiya-higashiosaka",
        "venue_type": "private_hall",
        "description": "東大阪市にある泉屋の葬儀会館。近鉄奈良線八戸ノ里駅から徒歩10分。老舗葬儀社の経験を活かし、家族葬から一般葬まで幅広く対応しています。",
        "address": "大阪府東大阪市中小阪3-1-18",
        "prefecture_slug": "osaka",
        "city_slug": "higashiosaka",
        "latitude": 34.6630,
        "longitude": 135.5850,
        "nearest_station": "近鉄奈良線 八戸ノ里駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "老舗葬儀社"],
        "operator_name": "泉屋",
        "rating_avg": 4.0,
        "review_count": 35
    },
    {
        "name": "花園メモリアルホール",
        "slug": "osaka-hanazono-memorial",
        "venue_type": "private_hall",
        "description": "東大阪市の花園エリアにある葬儀会館。花園ラグビー場にも近い場所に位置し、家族葬を中心に地域の方々にご利用いただいています。駐車場が広く車でのアクセスに便利。",
        "address": "大阪府東大阪市吉田6-2-33",
        "prefecture_slug": "osaka",
        "city_slug": "higashiosaka",
        "latitude": 34.6680,
        "longitude": 135.6060,
        "nearest_station": "近鉄奈良線 河内花園駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 305000}],
        "features": ["家族葬対応", "駐車場完備", "花園エリア"],
        "operator_name": "花園メモリアル",
        "rating_avg": 3.9,
        "review_count": 32
    },
    {
        "name": "セレモニーホール東大阪",
        "slug": "osaka-ceremony-higashiosaka",
        "venue_type": "private_hall",
        "description": "東大阪市にある互助会系の葬儀会館。家族葬から一般葬まで幅広く対応。経験豊富なスタッフが伝統的な葬儀をサポートしています。",
        "address": "大阪府東大阪市御厨栄町1-4-18",
        "prefecture_slug": "osaka",
        "city_slug": "higashiosaka",
        "latitude": 34.6740,
        "longitude": 135.5830,
        "nearest_station": "近鉄奈良線 河内小阪駅",
        "station_walk_minutes": 12,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["家族葬対応", "一般葬対応", "互助会系"],
        "operator_name": "セレモニーホール",
        "rating_avg": 3.9,
        "review_count": 38
    },
    {
        "name": "イオンのお葬式 東大阪ホール",
        "slug": "osaka-aeon-higashiosaka",
        "venue_type": "private_hall",
        "description": "東大阪市にあるイオンライフの提携葬儀会館。イオンブランドの安心感と明朗会計で、火葬式から家族葬まで提供。コストを抑えた葬儀を希望する方に最適です。",
        "address": "大阪府東大阪市菱屋西1-8-22",
        "prefecture_slug": "osaka",
        "city_slug": "higashiosaka",
        "latitude": 34.6590,
        "longitude": 135.5740,
        "nearest_station": "近鉄大阪線 長瀬駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 83000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["火葬式対応", "家族葬対応", "イオンブランド", "明朗会計"],
        "operator_name": "イオンライフ株式会社",
        "rating_avg": 3.8,
        "review_count": 42
    },
    {
        "name": "瓢箪山メモリアルホール",
        "slug": "osaka-hyotanyama-memorial",
        "venue_type": "private_hall",
        "description": "東大阪市の瓢箪山エリアにある葬儀会館。近鉄奈良線瓢箪山駅から徒歩6分。生駒山系の麓に位置し、自然に囲まれた落ち着いた環境で葬儀を執り行えます。",
        "address": "大阪府東大阪市昭和町1-5",
        "prefecture_slug": "osaka",
        "city_slug": "higashiosaka",
        "latitude": 34.6720,
        "longitude": 135.6120,
        "nearest_station": "近鉄奈良線 瓢箪山駅",
        "station_walk_minutes": 6,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 305000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "駅近", "自然環境"],
        "operator_name": "瓢箪山メモリアル",
        "rating_avg": 3.9,
        "review_count": 28
    },
    {
        "name": "家族葬のファミーユ 花園ホール",
        "slug": "osaka-famille-hanazono",
        "venue_type": "private_hall",
        "description": "東大阪市の花園エリアにある家族葬専門ホール。近鉄奈良線河内花園駅から徒歩7分。アットホームな雰囲気で少人数の温かいお見送りを提供しています。",
        "address": "大阪府東大阪市花園東町1-3-12",
        "prefecture_slug": "osaka",
        "city_slug": "higashiosaka",
        "latitude": 34.6660,
        "longitude": 135.6020,
        "nearest_station": "近鉄奈良線 河内花園駅",
        "station_walk_minutes": 7,
        "capacity_max": 35,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "駅近"],
        "operator_name": "株式会社ファミーユ",
        "rating_avg": 4.1,
        "review_count": 35
    },
    {
        "name": "ベルコシティホール石切",
        "slug": "osaka-bellco-ishikiri",
        "venue_type": "private_hall",
        "description": "東大阪市の石切エリアにあるベルコの葬儀会館。近鉄けいはんな線新石切駅から徒歩10分。石切劔箭神社にも近い歴史あるエリアで、家族葬・一般葬に対応しています。",
        "address": "大阪府東大阪市西石切町3-5-22",
        "prefecture_slug": "osaka",
        "city_slug": "higashiosaka",
        "latitude": 34.6830,
        "longitude": 135.6130,
        "nearest_station": "近鉄けいはんな線 新石切駅",
        "station_walk_minutes": 10,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "駐車場完備", "ベルコグループ"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 38
    },
    {
        "name": "若江岩田セレモニーホール",
        "slug": "osaka-wakae-iwata-ceremony",
        "venue_type": "private_hall",
        "description": "東大阪市の若江岩田エリアにある葬儀会館。近鉄奈良線若江岩田駅から徒歩5分。地域密着型のサービスで、家族葬を中心に対応しています。",
        "address": "大阪府東大阪市岩田町4-2-18",
        "prefecture_slug": "osaka",
        "city_slug": "higashiosaka",
        "latitude": 34.6690,
        "longitude": 135.5920,
        "nearest_station": "近鉄奈良線 若江岩田駅",
        "station_walk_minutes": 5,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 530000}],
        "features": ["家族葬対応", "駅近", "地域密着"],
        "operator_name": "若江岩田セレモニー",
        "rating_avg": 3.8,
        "review_count": 25
    },

    # =============================================
    # 枚方市（hirakata）: 12件
    # =============================================
    {
        "name": "枚方市立斎場",
        "slug": "osaka-hirakata-shiritsu-saijo",
        "venue_type": "public_crematorium",
        "description": "枚方市にある公営の火葬場。枚方市民は使用料が減額されます。緑豊かな環境に位置し、静かにお別れの時間を過ごせます。駐車場完備で車でのアクセスに便利です。",
        "address": "大阪府枚方市車塚2-1-1",
        "prefecture_slug": "osaka",
        "city_slug": "hirakata",
        "latitude": 34.8060,
        "longitude": 135.6500,
        "nearest_station": "京阪本線 枚方市駅",
        "station_walk_minutes": 20,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 50,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True, "霊安室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}],
        "features": ["火葬場併設", "公営斎場", "市民割引", "駐車場完備"],
        "operator_name": "枚方市",
        "rating_avg": 3.7,
        "review_count": 52
    },
    {
        "name": "公益社 枚方ホール",
        "slug": "osaka-koeisha-hirakata",
        "venue_type": "private_hall",
        "description": "枚方市にある公益社の葬儀会館。京阪本線枚方市駅から徒歩8分。北河内エリアの中核都市で、家族葬から一般葬まで公益社の高品質なサービスを提供しています。",
        "address": "大阪府枚方市岡東町5-23",
        "prefecture_slug": "osaka",
        "city_slug": "hirakata",
        "latitude": 34.8140,
        "longitude": 135.6520,
        "nearest_station": "京阪本線 枚方市駅",
        "station_walk_minutes": 8,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "公益社ブランド"],
        "operator_name": "公益社（燦ホールディングス）",
        "rating_avg": 4.3,
        "review_count": 78
    },
    {
        "name": "ベルコシティホール枚方",
        "slug": "osaka-bellco-hirakata",
        "venue_type": "private_hall",
        "description": "枚方市にあるベルコの葬儀会館。京阪本線枚方公園駅から徒歩10分。ひらかたパークにも近い枚方市西部エリアで、家族葬・一般葬に対応しています。",
        "address": "大阪府枚方市伊加賀寿町1-5",
        "prefecture_slug": "osaka",
        "city_slug": "hirakata",
        "latitude": 34.8080,
        "longitude": 135.6440,
        "nearest_station": "京阪本線 枚方公園駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "ベルコグループ"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 55
    },
    {
        "name": "家族葬のファミーユ 枚方ホール",
        "slug": "osaka-famille-hirakata",
        "venue_type": "private_hall",
        "description": "枚方市にある家族葬専門ホール。京阪本線牧野駅から徒歩8分。少人数のお葬式に特化し、温かみのある空間で故人を偲ぶことができます。",
        "address": "大阪府枚方市牧野阪2-1-12",
        "prefecture_slug": "osaka",
        "city_slug": "hirakata",
        "latitude": 34.8280,
        "longitude": 135.6580,
        "nearest_station": "京阪本線 牧野駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "明朗会計"],
        "operator_name": "株式会社ファミーユ",
        "rating_avg": 4.2,
        "review_count": 48
    },
    {
        "name": "ティア枚方",
        "slug": "osaka-tier-hirakata",
        "venue_type": "private_hall",
        "description": "枚方市にあるティアの家族葬ホール。京阪本線枚方市駅から徒歩12分。1日1組貸切で心ゆくまでお別れの時間を過ごせる、温かみのある施設です。",
        "address": "大阪府枚方市大垣内町2-8-5",
        "prefecture_slug": "osaka",
        "city_slug": "hirakata",
        "latitude": 34.8100,
        "longitude": 135.6560,
        "nearest_station": "京阪本線 枚方市駅",
        "station_walk_minutes": 12,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "1日1組貸切", "明朗会計"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.1,
        "review_count": 42
    },
    {
        "name": "小さなお葬式 枚方ホール",
        "slug": "osaka-chiisana-hirakata",
        "venue_type": "private_hall",
        "description": "枚方市にある小さなお葬式の提携ホール。火葬式から家族葬まで明朗会計で提供。枚方市民にリーズナブルな葬儀プランが好評です。",
        "address": "大阪府枚方市新町1-3-18",
        "prefecture_slug": "osaka",
        "city_slug": "hirakata",
        "latitude": 34.8120,
        "longitude": 135.6490,
        "nearest_station": "京阪本線 枚方市駅",
        "station_walk_minutes": 6,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 189000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["火葬式対応", "家族葬対応", "駅近", "明朗会計"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 3.9,
        "review_count": 55
    },
    {
        "name": "枚方メモリアルホール",
        "slug": "osaka-hirakata-memorial",
        "venue_type": "private_hall",
        "description": "枚方市にある地域密着型の葬儀会館。枚方市の住宅街に位置し、家族葬を中心に地域の方々にご利用いただいています。アットホームな雰囲気が特徴です。",
        "address": "大阪府枚方市宮之阪3-5-15",
        "prefecture_slug": "osaka",
        "city_slug": "hirakata",
        "latitude": 34.8200,
        "longitude": 135.6620,
        "nearest_station": "京阪交野線 宮之阪駅",
        "station_walk_minutes": 5,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "地域密着"],
        "operator_name": "枚方メモリアル",
        "rating_avg": 3.9,
        "review_count": 32
    },
    {
        "name": "泉屋 枚方ホール",
        "slug": "osaka-izumiya-hirakata",
        "venue_type": "private_hall",
        "description": "枚方市にある泉屋の葬儀会館。京阪本線御殿山駅から徒歩8分。老舗葬儀社の経験を活かした丁寧なサービスで、家族葬から一般葬まで対応しています。",
        "address": "大阪府枚方市御殿山町10-16",
        "prefecture_slug": "osaka",
        "city_slug": "hirakata",
        "latitude": 34.8050,
        "longitude": 135.6420,
        "nearest_station": "京阪本線 御殿山駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "老舗葬儀社"],
        "operator_name": "泉屋",
        "rating_avg": 4.0,
        "review_count": 35
    },
    {
        "name": "セレモニーホール枚方",
        "slug": "osaka-ceremony-hirakata",
        "venue_type": "private_hall",
        "description": "枚方市にある互助会系の葬儀会館。経験豊富なスタッフが伝統的な葬儀から家族葬まで丁寧にサポート。枚方市の葬儀需要に応えています。",
        "address": "大阪府枚方市香里園町8-2",
        "prefecture_slug": "osaka",
        "city_slug": "hirakata",
        "latitude": 34.7980,
        "longitude": 135.6470,
        "nearest_station": "京阪本線 香里園駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["家族葬対応", "一般葬対応", "互助会系"],
        "operator_name": "セレモニーホール",
        "rating_avg": 3.9,
        "review_count": 38
    },
    {
        "name": "くずは メモリアルホール",
        "slug": "osaka-kuzuha-memorial",
        "venue_type": "private_hall",
        "description": "枚方市のくずはエリアにある葬儀会館。京阪本線樟葉駅から徒歩12分。くずはモールにも近い住宅街に位置し、家族葬を中心にサービスを提供しています。",
        "address": "大阪府枚方市楠葉並木2-22-1",
        "prefecture_slug": "osaka",
        "city_slug": "hirakata",
        "latitude": 34.8530,
        "longitude": 135.6750,
        "nearest_station": "京阪本線 樟葉駅",
        "station_walk_minutes": 12,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 315000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 540000}],
        "features": ["家族葬対応", "駐車場完備", "くずはエリア"],
        "operator_name": "くずはメモリアル",
        "rating_avg": 4.0,
        "review_count": 30
    },
    {
        "name": "イオンのお葬式 枚方ホール",
        "slug": "osaka-aeon-hirakata",
        "venue_type": "private_hall",
        "description": "枚方市にあるイオンライフの提携葬儀会館。イオンブランドの安心感で火葬式から家族葬まで提供。コストを抑えた明朗会計の葬儀が特徴です。",
        "address": "大阪府枚方市朝日丘町2-15",
        "prefecture_slug": "osaka",
        "city_slug": "hirakata",
        "latitude": 34.8160,
        "longitude": 135.6540,
        "nearest_station": "京阪本線 枚方市駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 83000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["火葬式対応", "家族葬対応", "イオンブランド"],
        "operator_name": "イオンライフ株式会社",
        "rating_avg": 3.8,
        "review_count": 38
    },

    # =============================================
    # 豊中市（toyonaka）: 10件
    # =============================================
    {
        "name": "豊中市立火葬場",
        "slug": "osaka-toyonaka-kasoba",
        "venue_type": "public_crematorium",
        "description": "豊中市にある公営の火葬場。豊中市民は使用料が減額されます。緑に囲まれた環境で静かにお別れの時間を過ごせます。大阪モノレール少路駅からバスでアクセス可能。",
        "address": "大阪府豊中市走井3-15-1",
        "prefecture_slug": "osaka",
        "city_slug": "toyonaka",
        "latitude": 34.7830,
        "longitude": 135.4580,
        "nearest_station": "大阪モノレール 少路駅",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 40,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}],
        "features": ["火葬場", "公営", "市民割引", "駐車場完備"],
        "operator_name": "豊中市",
        "rating_avg": 3.7,
        "review_count": 42
    },
    {
        "name": "公益社 豊中ホール",
        "slug": "osaka-koeisha-toyonaka",
        "venue_type": "private_hall",
        "description": "豊中市にある公益社の葬儀会館。阪急宝塚線豊中駅から徒歩6分。北摂エリアの中核都市で、家族葬から一般葬まで公益社の高品質なサービスを提供しています。",
        "address": "大阪府豊中市本町1-8-8",
        "prefecture_slug": "osaka",
        "city_slug": "toyonaka",
        "latitude": 34.7830,
        "longitude": 135.4680,
        "nearest_station": "阪急宝塚線 豊中駅",
        "station_walk_minutes": 6,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "公益社ブランド"],
        "operator_name": "公益社（燦ホールディングス）",
        "rating_avg": 4.4,
        "review_count": 92
    },
    {
        "name": "ベルコシティホール豊中",
        "slug": "osaka-bellco-toyonaka",
        "venue_type": "private_hall",
        "description": "豊中市にあるベルコの葬儀会館。阪急宝塚線岡町駅から徒歩8分。豊中市の閑静な住宅街に位置し、家族葬・一般葬に充実した設備で対応しています。",
        "address": "大阪府豊中市岡上の町2-1-15",
        "prefecture_slug": "osaka",
        "city_slug": "toyonaka",
        "latitude": 34.7780,
        "longitude": 135.4700,
        "nearest_station": "阪急宝塚線 岡町駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "ベルコグループ"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 55
    },
    {
        "name": "家族葬のファミーユ 豊中ホール",
        "slug": "osaka-famille-toyonaka",
        "venue_type": "private_hall",
        "description": "豊中市にある家族葬専門ホール。阪急宝塚線服部天神駅から徒歩7分。少人数の温かな葬儀を提供する施設で、明朗会計が安心のポイントです。",
        "address": "大阪府豊中市服部本町3-1-18",
        "prefecture_slug": "osaka",
        "city_slug": "toyonaka",
        "latitude": 34.7710,
        "longitude": 135.4620,
        "nearest_station": "阪急宝塚線 服部天神駅",
        "station_walk_minutes": 7,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "駅近", "明朗会計"],
        "operator_name": "株式会社ファミーユ",
        "rating_avg": 4.2,
        "review_count": 52
    },
    {
        "name": "ティア豊中",
        "slug": "osaka-tier-toyonaka",
        "venue_type": "private_hall",
        "description": "豊中市にあるティアの家族葬ホール。阪急宝塚線庄内駅から徒歩8分。1日1組貸切で、ゆったりとしたお別れの時間を過ごせます。明朗会計が安心のポイント。",
        "address": "大阪府豊中市庄内東町2-5-12",
        "prefecture_slug": "osaka",
        "city_slug": "toyonaka",
        "latitude": 34.7620,
        "longitude": 135.4630,
        "nearest_station": "阪急宝塚線 庄内駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "1日1組貸切", "明朗会計"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.1,
        "review_count": 45
    },
    {
        "name": "小さなお葬式 豊中ホール",
        "slug": "osaka-chiisana-toyonaka",
        "venue_type": "private_hall",
        "description": "豊中市にある小さなお葬式の提携ホール。火葬式から家族葬まで明朗会計で提供。コストを抑えた葬儀を希望する北摂エリアの方に好評です。",
        "address": "大阪府豊中市中桜塚2-5-1",
        "prefecture_slug": "osaka",
        "city_slug": "toyonaka",
        "latitude": 34.7790,
        "longitude": 135.4740,
        "nearest_station": "阪急宝塚線 岡町駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 6,
        "facilities": {"式場": True, "親族控室": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 189000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["火葬式対応", "家族葬対応", "明朗会計"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 3.9,
        "review_count": 48
    },
    {
        "name": "千里メモリアルホール",
        "slug": "osaka-senri-memorial",
        "venue_type": "private_hall",
        "description": "豊中市の千里エリアにある葬儀会館。北大阪急行千里中央駅から徒歩10分。千里ニュータウンの高齢化に伴う葬儀需要に応え、家族葬を中心にサービスを提供しています。",
        "address": "大阪府豊中市新千里東町1-5-3",
        "prefecture_slug": "osaka",
        "city_slug": "toyonaka",
        "latitude": 34.8050,
        "longitude": 135.4890,
        "nearest_station": "北大阪急行 千里中央駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["家族葬対応", "千里ニュータウン", "駐車場完備"],
        "operator_name": "千里メモリアル",
        "rating_avg": 4.0,
        "review_count": 40
    },
    {
        "name": "泉屋 豊中ホール",
        "slug": "osaka-izumiya-toyonaka",
        "venue_type": "private_hall",
        "description": "豊中市にある泉屋の葬儀会館。老舗葬儀社ならではの伝統と経験で、家族葬から一般葬まで幅広く対応。豊中市の方々に信頼されている施設です。",
        "address": "大阪府豊中市曽根東町1-8-15",
        "prefecture_slug": "osaka",
        "city_slug": "toyonaka",
        "latitude": 34.7740,
        "longitude": 135.4710,
        "nearest_station": "阪急宝塚線 曽根駅",
        "station_walk_minutes": 5,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "老舗葬儀社"],
        "operator_name": "泉屋",
        "rating_avg": 4.1,
        "review_count": 42
    },
    {
        "name": "イオンのお葬式 豊中ホール",
        "slug": "osaka-aeon-toyonaka",
        "venue_type": "private_hall",
        "description": "豊中市にあるイオンライフの提携葬儀会館。イオンブランドの安心感で火葬式から家族葬まで、明朗会計で提供しています。",
        "address": "大阪府豊中市蛍池中町2-3-1",
        "prefecture_slug": "osaka",
        "city_slug": "toyonaka",
        "latitude": 34.7870,
        "longitude": 135.4570,
        "nearest_station": "阪急宝塚線 蛍池駅",
        "station_walk_minutes": 6,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 6,
        "facilities": {"式場": True, "親族控室": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 83000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["火葬式対応", "家族葬対応", "駅近", "イオンブランド"],
        "operator_name": "イオンライフ株式会社",
        "rating_avg": 3.8,
        "review_count": 35
    },

    # =============================================
    # 吹田市（suita）: 8件
    # =============================================
    {
        "name": "公益社 吹田ホール",
        "slug": "osaka-koeisha-suita",
        "venue_type": "private_hall",
        "description": "吹田市にある公益社の葬儀会館。JR吹田駅から徒歩8分。万博記念公園にも近い北摂の中核都市で、家族葬から一般葬まで公益社の高品質なサービスを提供。",
        "address": "大阪府吹田市朝日町3-108",
        "prefecture_slug": "osaka",
        "city_slug": "suita",
        "latitude": 34.7610,
        "longitude": 135.5160,
        "nearest_station": "JR京都線 吹田駅",
        "station_walk_minutes": 8,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "公益社ブランド"],
        "operator_name": "公益社（燦ホールディングス）",
        "rating_avg": 4.3,
        "review_count": 75
    },
    {
        "name": "ベルコシティホール吹田",
        "slug": "osaka-bellco-suita",
        "venue_type": "private_hall",
        "description": "吹田市にあるベルコの葬儀会館。阪急千里線吹田駅から徒歩10分。吹田市の住宅街に位置し、家族葬・一般葬に対応した設備を完備しています。",
        "address": "大阪府吹田市元町28-13",
        "prefecture_slug": "osaka",
        "city_slug": "suita",
        "latitude": 34.7640,
        "longitude": 135.5180,
        "nearest_station": "阪急千里線 吹田駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "ベルコグループ"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 48
    },
    {
        "name": "家族葬のファミーユ 江坂ホール",
        "slug": "osaka-famille-esaka",
        "venue_type": "private_hall",
        "description": "吹田市の江坂エリアにある家族葬専門ホール。大阪メトロ御堂筋線江坂駅から徒歩6分。ビジネス街に近い利便性の高い立地で、少人数の温かな葬儀を提供しています。",
        "address": "大阪府吹田市江坂町1-23-19",
        "prefecture_slug": "osaka",
        "city_slug": "suita",
        "latitude": 34.7590,
        "longitude": 135.4950,
        "nearest_station": "大阪メトロ御堂筋線 江坂駅",
        "station_walk_minutes": 6,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 6,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "駅近", "江坂エリア"],
        "operator_name": "株式会社ファミーユ",
        "rating_avg": 4.2,
        "review_count": 55
    },
    {
        "name": "ティア吹田",
        "slug": "osaka-tier-suita",
        "venue_type": "private_hall",
        "description": "吹田市にあるティアの家族葬ホール。JR吹田駅から徒歩10分。1日1組貸切で温かみのある家族葬を提供。明朗会計と丁寧なサポートが特徴です。",
        "address": "大阪府吹田市片山町2-5-22",
        "prefecture_slug": "osaka",
        "city_slug": "suita",
        "latitude": 34.7650,
        "longitude": 135.5210,
        "nearest_station": "JR京都線 吹田駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "1日1組貸切", "明朗会計"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.1,
        "review_count": 40
    },
    {
        "name": "小さなお葬式 吹田ホール",
        "slug": "osaka-chiisana-suita",
        "venue_type": "private_hall",
        "description": "吹田市にある小さなお葬式の提携ホール。火葬式から家族葬まで明朗会計で提供。北摂エリアの方にリーズナブルな葬儀プランが好評です。",
        "address": "大阪府吹田市昭和町12-8",
        "prefecture_slug": "osaka",
        "city_slug": "suita",
        "latitude": 34.7580,
        "longitude": 135.5130,
        "nearest_station": "JR京都線 吹田駅",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 6,
        "facilities": {"式場": True, "親族控室": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 189000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["火葬式対応", "家族葬対応", "駅近", "明朗会計"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 3.9,
        "review_count": 45
    },
    {
        "name": "千里丘メモリアルホール",
        "slug": "osaka-senrioka-memorial",
        "venue_type": "private_hall",
        "description": "吹田市の千里丘エリアにある葬儀会館。JR千里丘駅から徒歩8分。摂津市との境界に近い場所で、家族葬を中心に地域の方々にご利用いただいています。",
        "address": "大阪府吹田市千里丘上14-25",
        "prefecture_slug": "osaka",
        "city_slug": "suita",
        "latitude": 34.7810,
        "longitude": 135.5350,
        "nearest_station": "JR京都線 千里丘駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 530000}],
        "features": ["家族葬対応", "駅近", "地域密着"],
        "operator_name": "千里丘メモリアル",
        "rating_avg": 3.9,
        "review_count": 28
    },
    {
        "name": "万博メモリアルホール",
        "slug": "osaka-banpaku-memorial",
        "venue_type": "private_hall",
        "description": "吹田市の万博記念公園エリアにある葬儀会館。大阪モノレール万博記念公園駅から徒歩15分。緑豊かな環境で落ち着いたお別れの時間を過ごせます。駐車場が広い点も魅力。",
        "address": "大阪府吹田市山田西3-5-8",
        "prefecture_slug": "osaka",
        "city_slug": "suita",
        "latitude": 34.8000,
        "longitude": 135.5240,
        "nearest_station": "大阪モノレール 万博記念公園駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 315000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 540000}],
        "features": ["家族葬対応", "駐車場完備", "緑豊かな環境"],
        "operator_name": "万博メモリアル",
        "rating_avg": 4.0,
        "review_count": 32
    },
]

# 10件ずつバッチ投入
total = len(venues)
print(f"大阪 バッチ4（東大阪+枚方+豊中+吹田）: 合計 {total} 件を投入開始")

for i in range(0, total, 10):
    batch = venues[i:i+10]
    status = insert_batch(batch)
    end = min(i+10, total)
    print(f"  [{i+1}-{end}] HTTP {status}")
    if status != "201":
        data_json = json.dumps(batch, ensure_ascii=False)
        result = subprocess.run([
            "curl", "-s",
            "-X", "POST", SUPABASE_URL,
            "-H", f"apikey: {API_KEY}",
            "-H", f"Authorization: Bearer {API_KEY}",
            "-H", "Content-Type: application/json",
            "-H", "Prefer: return=minimal",
            "-H", "User-Agent: Mozilla/5.0",
            "-d", data_json
        ], capture_output=True, text=True)
        print(f"  エラー詳細: {result.stdout[:500]}")
    time.sleep(0.5)

print(f"\nバッチ4完了: {total}件")
