#!/usr/bin/env python3
"""
北海道の斎場データ バッチ4: 釧路12件+帯広10件+北見8件+小樽6件+苫小牧8件 = 44件
"""
import json
import subprocess
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

venues = [
    # =============================================
    # 釧路市 (12件)
    # =============================================
    {"name": "釧路市斎場", "slug": "hokkaido-kushiro-shi-saijo", "venue_type": "public_crematorium", "description": "釧路市が運営する公営の総合斎場。火葬棟と式場を併設し、通夜から火葬まで同一敷地内で行えます。釧路市民は火葬料無料。広い駐車場を完備。", "address": "北海道釧路市星が浦大通3丁目2-1", "prefecture_slug": "hokkaido", "city_slug": "kushiro", "latitude": 42.9550, "longitude": 144.3600, "nearest_station": "JR根室本線 新大楽毛駅", "station_walk_minutes": 15, "capacity_max": 80, "hall_count": 3, "has_crematorium": True, "parking_count": 150, "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}], "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"], "operator_name": "釧路市", "rating_avg": 3.9, "review_count": 48},
    {"name": "やわらぎ斎場 釧路", "slug": "hokkaido-yawaragi-kushiro", "venue_type": "private_hall", "description": "やわらぎの釧路拠点。JR釧路駅から車で10分。道東エリアの中核斎場として、家族葬から大規模葬まで幅広く対応。24時間365日対応。", "address": "北海道釧路市愛国東2丁目8-15", "prefecture_slug": "hokkaido", "city_slug": "kushiro", "latitude": 42.9700, "longitude": 144.3800, "nearest_station": "JR根室本線 釧路駅", "station_walk_minutes": 15, "capacity_max": 100, "hall_count": 3, "has_crematorium": False, "parking_count": 40, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}], "features": ["大規模葬対応", "宿泊可能", "24時間対応", "駐車場完備"], "operator_name": "株式会社やわらぎ", "rating_avg": 4.2, "review_count": 56},
    {"name": "ベルコ釧路シティホール", "slug": "hokkaido-bellco-kushiro", "venue_type": "private_hall", "description": "ベルコの釧路斎場。昭和エリアに位置し、広い駐車場と充実した設備。互助会会員は割引価格で利用可能。家族葬から一般葬まで対応。", "address": "北海道釧路市昭和中央4丁目15-3", "prefecture_slug": "hokkaido", "city_slug": "kushiro", "latitude": 42.9650, "longitude": 144.3500, "nearest_station": "JR根室本線 新富士駅", "station_walk_minutes": 15, "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 40, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}], "features": ["互助会対応", "駐車場完備", "家族葬対応", "バリアフリー"], "operator_name": "株式会社ベルコ", "rating_avg": 4.0, "review_count": 45},
    {"name": "北海斎場 釧路", "slug": "hokkaido-hokkai-kushiro", "venue_type": "private_hall", "description": "北海斎場の釧路支店。釧路中心部に位置し、老舗の安心感と丁寧なサービスが好評。伝統的な葬儀から現代的な家族葬まで対応します。", "address": "北海道釧路市北大通12丁目1-8", "prefecture_slug": "hokkaido", "city_slug": "kushiro", "latitude": 42.9750, "longitude": 144.3720, "nearest_station": "JR根室本線 釧路駅", "station_walk_minutes": 8, "capacity_max": 70, "hall_count": 2, "has_crematorium": False, "parking_count": 25, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "和室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000}], "features": ["駅近", "老舗葬儀社", "和室あり", "家族葬対応"], "operator_name": "北海斎場株式会社", "rating_avg": 4.1, "review_count": 38},
    {"name": "シティホール釧路", "slug": "hokkaido-cityhall-kushiro", "venue_type": "private_hall", "description": "シティホールグループの釧路店。花祭壇が美しいモダンな式場で、1日1組貸切対応。故人らしいお別れをプロデュースします。", "address": "北海道釧路市春採5丁目3-12", "prefecture_slug": "hokkaido", "city_slug": "kushiro", "latitude": 42.9680, "longitude": 144.3900, "nearest_station": "JR根室本線 釧路駅", "station_walk_minutes": 12, "capacity_max": 50, "hall_count": 2, "has_crematorium": False, "parking_count": 20, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 418000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 638000}], "features": ["花祭壇", "1日1組貸切", "家族葬対応", "モダンな内装"], "operator_name": "株式会社シティホール", "rating_avg": 4.3, "review_count": 31},
    {"name": "家族葬のウィズハウス 釧路", "slug": "hokkaido-withhouse-kushiro", "venue_type": "private_hall", "description": "ウィズハウスの釧路店。鳥取エリアの閑静な住宅地に位置。居間スタイルの温かみのある式場で少人数の家族葬に最適。", "address": "北海道釧路市鳥取大通8丁目2-5", "prefecture_slug": "hokkaido", "city_slug": "kushiro", "latitude": 42.9600, "longitude": 144.3650, "nearest_station": "JR根室本線 新大楽毛駅", "station_walk_minutes": 12, "capacity_max": 25, "hall_count": 1, "has_crematorium": False, "parking_count": 10, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "キッチン": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}], "features": ["家族葬専用", "1日1組貸切", "居間スタイル"], "operator_name": "株式会社ウィズハウス", "rating_avg": 4.5, "review_count": 22},
    {"name": "はまそう釧路ホール", "slug": "hokkaido-hamaso-kushiro", "venue_type": "private_hall", "description": "はまそうの釧路拠点。広い敷地に大型式場を備え、社葬にも対応可能。釧路エリア最大級の葬儀施設です。", "address": "北海道釧路市芦野2丁目18-5", "prefecture_slug": "hokkaido", "city_slug": "kushiro", "latitude": 42.9800, "longitude": 144.3550, "nearest_station": "JR根室本線 釧路駅", "station_walk_minutes": 20, "capacity_max": 150, "hall_count": 3, "has_crematorium": False, "parking_count": 60, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True, "宿泊施設": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 698000}], "features": ["釧路最大級", "社葬対応", "駐車場完備", "宿泊可能"], "operator_name": "株式会社はまそう", "rating_avg": 4.1, "review_count": 42},
    {"name": "コープ葬祭 釧路ホール", "slug": "hokkaido-coop-kushiro", "venue_type": "private_hall", "description": "コープさっぽろの釧路葬祭ホール。組合員割引で利用可能。リーズナブルな価格と丁寧なサービスが好評です。", "address": "北海道釧路市文苑2丁目58-12", "prefecture_slug": "hokkaido", "city_slug": "kushiro", "latitude": 42.9850, "longitude": 144.3700, "nearest_station": "JR根室本線 釧路駅", "station_walk_minutes": 20, "capacity_max": 50, "hall_count": 2, "has_crematorium": False, "parking_count": 25, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 188000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}], "features": ["組合員割引", "明瞭価格", "家族葬対応"], "operator_name": "コープさっぽろ", "rating_avg": 4.0, "review_count": 30},
    {"name": "メモリアルホール釧路", "slug": "hokkaido-memorial-kushiro", "venue_type": "private_hall", "description": "釧路市中心部のメモリアルホール。幣舞橋近くの立地で、地域密着の丁寧なサービスが好評。家族葬から一般葬まで対応。", "address": "北海道釧路市南大通5丁目2-8", "prefecture_slug": "hokkaido", "city_slug": "kushiro", "latitude": 42.9720, "longitude": 144.3750, "nearest_station": "JR根室本線 釧路駅", "station_walk_minutes": 10, "capacity_max": 60, "hall_count": 2, "has_crematorium": False, "parking_count": 20, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}], "features": ["駅近", "地域密着", "家族葬対応", "バリアフリー"], "operator_name": "メモリアルサービス北海道", "rating_avg": 4.0, "review_count": 28},
    {"name": "釧路厳島神社会館", "slug": "hokkaido-kushiro-itsukushima", "venue_type": "temple_hall", "description": "釧路市の厳島神社が運営する会館。神式の葬儀に対応し、荘厳な雰囲気の中でお別れができます。宗派を問わず利用可能。", "address": "北海道釧路市米町1丁目3-18", "prefecture_slug": "hokkaido", "city_slug": "kushiro", "latitude": 42.9780, "longitude": 144.3850, "nearest_station": "JR根室本線 釧路駅", "station_walk_minutes": 12, "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "駐車場": True, "控室": True, "和室": True}, "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 478000}], "features": ["神社式場", "宗派不問", "伝統的な雰囲気"], "operator_name": "厳島神社", "rating_avg": 4.0, "review_count": 15},
    {"name": "釧路鳥取セレモニー", "slug": "hokkaido-kushiro-tottori-ceremony", "venue_type": "private_hall", "description": "釧路市鳥取エリアの地域密着型セレモニーホール。リーズナブルな価格設定で家族葬に人気。温かみのある対応が好評です。", "address": "北海道釧路市鳥取北8丁目5-12", "prefecture_slug": "hokkaido", "city_slug": "kushiro", "latitude": 42.9550, "longitude": 144.3550, "nearest_station": "JR根室本線 新大楽毛駅", "station_walk_minutes": 10, "capacity_max": 35, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}], "features": ["地域密着", "リーズナブル", "家族葬対応"], "operator_name": "鳥取セレモニー", "rating_avg": 4.1, "review_count": 19},
    {"name": "釧路市民葬祭会館", "slug": "hokkaido-kushiro-shimin-sousai", "venue_type": "public_facility", "description": "釧路市の公共施設を利用した葬儀会場。低価格で市民に広く開放されています。シンプルなお別れに最適。", "address": "北海道釧路市黒金町8丁目3-1", "prefecture_slug": "hokkaido", "city_slug": "kushiro", "latitude": 42.9740, "longitude": 144.3680, "nearest_station": "JR根室本線 釧路駅", "station_walk_minutes": 8, "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 25, "facilities": {"バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 68000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 228000}], "features": ["公共施設", "低価格", "駅近"], "operator_name": "釧路市", "rating_avg": 3.7, "review_count": 14},
    # =============================================
    # 帯広市 (10件)
    # =============================================
    {"name": "帯広市斎場", "slug": "hokkaido-obihiro-shi-saijo", "venue_type": "public_crematorium", "description": "帯広市が運営する公営斎場。火葬棟と式場を併設。帯広市民は火葬料無料。十勝平野の静かな環境にあり、広い駐車場を完備しています。", "address": "北海道帯広市東8条南28丁目1", "prefecture_slug": "hokkaido", "city_slug": "obihiro", "latitude": 42.8900, "longitude": 143.2200, "nearest_station": "JR根室本線 帯広駅", "station_walk_minutes": 25, "capacity_max": 80, "hall_count": 2, "has_crematorium": True, "parking_count": 120, "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}], "features": ["火葬場併設", "公営斎場", "駐車場完備"], "operator_name": "帯広市", "rating_avg": 3.9, "review_count": 42},
    {"name": "やわらぎ斎場 帯広", "slug": "hokkaido-yawaragi-obihiro", "venue_type": "private_hall", "description": "やわらぎの帯広拠点。JR帯広駅から車で10分。十勝エリアの中核斎場として充実した設備とサービスを提供。24時間365日対応。", "address": "北海道帯広市西5条南15丁目1-8", "prefecture_slug": "hokkaido", "city_slug": "obihiro", "latitude": 42.9150, "longitude": 143.1950, "nearest_station": "JR根室本線 帯広駅", "station_walk_minutes": 10, "capacity_max": 100, "hall_count": 3, "has_crematorium": False, "parking_count": 40, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}], "features": ["駅近", "大規模葬対応", "宿泊可能", "24時間対応"], "operator_name": "株式会社やわらぎ", "rating_avg": 4.2, "review_count": 55},
    {"name": "ベルコ帯広シティホール", "slug": "hokkaido-bellco-obihiro", "venue_type": "private_hall", "description": "ベルコの帯広斎場。西帯広エリアに位置し、広い駐車場と大ホールを備えています。互助会会員は割引利用可能。", "address": "北海道帯広市西18条南3丁目28-5", "prefecture_slug": "hokkaido", "city_slug": "obihiro", "latitude": 42.9200, "longitude": 143.1700, "nearest_station": "JR根室本線 西帯広駅", "station_walk_minutes": 12, "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 40, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}], "features": ["互助会対応", "駐車場完備", "家族葬対応"], "operator_name": "株式会社ベルコ", "rating_avg": 4.0, "review_count": 40},
    {"name": "シティホール帯広", "slug": "hokkaido-cityhall-obihiro", "venue_type": "private_hall", "description": "シティホールグループの帯広店。モダンなデザインの式場で花祭壇が人気。1日1組貸切で丁寧なサービスを提供。", "address": "北海道帯広市東3条南12丁目2-15", "prefecture_slug": "hokkaido", "city_slug": "obihiro", "latitude": 42.9100, "longitude": 143.2100, "nearest_station": "JR根室本線 帯広駅", "station_walk_minutes": 8, "capacity_max": 50, "hall_count": 2, "has_crematorium": False, "parking_count": 20, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 418000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 638000}], "features": ["駅近", "花祭壇", "1日1組貸切", "家族葬対応"], "operator_name": "株式会社シティホール", "rating_avg": 4.3, "review_count": 33},
    {"name": "家族葬のウィズハウス 帯広", "slug": "hokkaido-withhouse-obihiro", "venue_type": "private_hall", "description": "ウィズハウスの帯広店。居間スタイルの温かみのある式場で少人数の家族葬に最適。1日1組完全貸切。", "address": "北海道帯広市西12条南8丁目5-10", "prefecture_slug": "hokkaido", "city_slug": "obihiro", "latitude": 42.9130, "longitude": 143.1850, "nearest_station": "JR根室本線 帯広駅", "station_walk_minutes": 15, "capacity_max": 25, "hall_count": 1, "has_crematorium": False, "parking_count": 10, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "キッチン": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}], "features": ["家族葬専用", "1日1組貸切", "居間スタイル"], "operator_name": "株式会社ウィズハウス", "rating_avg": 4.5, "review_count": 24},
    {"name": "はまそう帯広ホール", "slug": "hokkaido-hamaso-obihiro", "venue_type": "private_hall", "description": "はまそうの帯広拠点。広い敷地に大型式場を備え、社葬にも対応可能。十勝エリア最大級の葬儀施設。", "address": "北海道帯広市稲田町基線8-1", "prefecture_slug": "hokkaido", "city_slug": "obihiro", "latitude": 42.8800, "longitude": 143.2100, "nearest_station": "JR根室本線 帯広駅", "station_walk_minutes": 25, "capacity_max": 120, "hall_count": 3, "has_crematorium": False, "parking_count": 50, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 698000}], "features": ["十勝最大級", "社葬対応", "駐車場完備", "宿泊可能"], "operator_name": "株式会社はまそう", "rating_avg": 4.1, "review_count": 38},
    {"name": "コープ葬祭 帯広ホール", "slug": "hokkaido-coop-obihiro", "venue_type": "private_hall", "description": "コープさっぽろの帯広葬祭ホール。組合員割引でリーズナブルに利用可能。明瞭な料金体系が好評。", "address": "北海道帯広市東5条南13丁目1-5", "prefecture_slug": "hokkaido", "city_slug": "obihiro", "latitude": 42.9080, "longitude": 143.2150, "nearest_station": "JR根室本線 帯広駅", "station_walk_minutes": 10, "capacity_max": 50, "hall_count": 2, "has_crematorium": False, "parking_count": 25, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 188000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}], "features": ["組合員割引", "明瞭価格", "駅近", "家族葬対応"], "operator_name": "コープさっぽろ", "rating_avg": 4.0, "review_count": 28},
    {"name": "メモリアルホール帯広", "slug": "hokkaido-memorial-obihiro", "venue_type": "private_hall", "description": "帯広中心部のメモリアルホール。十勝の大自然を感じる温かみのある空間で、家族葬に人気の斎場です。", "address": "北海道帯広市大通南12丁目5-8", "prefecture_slug": "hokkaido", "city_slug": "obihiro", "latitude": 42.9120, "longitude": 143.2050, "nearest_station": "JR根室本線 帯広駅", "station_walk_minutes": 8, "capacity_max": 60, "hall_count": 2, "has_crematorium": False, "parking_count": 25, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}], "features": ["駅近", "家族葬対応", "バリアフリー"], "operator_name": "メモリアルサービス北海道", "rating_avg": 4.0, "review_count": 25},
    {"name": "帯広西願寺会館", "slug": "hokkaido-obihiro-saiganji", "venue_type": "temple_hall", "description": "帯広市にある浄土真宗の寺院式場。歴史ある本堂で仏式葬儀を執り行えます。宗派不問。", "address": "北海道帯広市東2条南5丁目3-1", "prefecture_slug": "hokkaido", "city_slug": "obihiro", "latitude": 42.9180, "longitude": 143.2080, "nearest_station": "JR根室本線 帯広駅", "station_walk_minutes": 5, "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "駐車場": True, "控室": True, "和室": True}, "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 268000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 458000}], "features": ["寺院式場", "宗派不問", "駅近"], "operator_name": "西願寺", "rating_avg": 3.9, "review_count": 14},
    {"name": "帯広セレモニーホール稲田", "slug": "hokkaido-obihiro-ceremony-inada", "venue_type": "private_hall", "description": "帯広市稲田エリアの地域密着型セレモニーホール。リーズナブルな価格設定で家族葬に人気。温かみのある対応が好評。", "address": "北海道帯広市稲田町南8線13-1", "prefecture_slug": "hokkaido", "city_slug": "obihiro", "latitude": 42.8850, "longitude": 143.2000, "nearest_station": "JR根室本線 帯広駅", "station_walk_minutes": 25, "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 20, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}], "features": ["地域密着", "リーズナブル", "家族葬対応", "駐車場完備"], "operator_name": "帯広稲田セレモニー", "rating_avg": 4.1, "review_count": 18},
    # =============================================
    # 北見市 (8件)
    # =============================================
    {"name": "北見市斎場", "slug": "hokkaido-kitami-shi-saijo", "venue_type": "public_crematorium", "description": "北見市が運営する公営斎場。火葬棟を併設。北見市民は火葬料無料。オホーツク海側の穏やかな環境に位置しています。", "address": "北海道北見市常呂町日吉15", "prefecture_slug": "hokkaido", "city_slug": "kitami", "latitude": 44.0800, "longitude": 144.1000, "nearest_station": "JR石北本線 北見駅", "station_walk_minutes": 30, "capacity_max": 60, "hall_count": 2, "has_crematorium": True, "parking_count": 80, "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 478000}], "features": ["火葬場併設", "公営斎場", "駐車場完備"], "operator_name": "北見市", "rating_avg": 3.8, "review_count": 32},
    {"name": "やわらぎ斎場 北見", "slug": "hokkaido-yawaragi-kitami", "venue_type": "private_hall", "description": "やわらぎの北見拠点。北見市中心部に位置し、家族葬から一般葬まで対応。オホーツク地域の方々に信頼されている斎場です。", "address": "北海道北見市北4条東3丁目1-8", "prefecture_slug": "hokkaido", "city_slug": "kitami", "latitude": 43.8040, "longitude": 143.8960, "nearest_station": "JR石北本線 北見駅", "station_walk_minutes": 8, "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 578000}], "features": ["駅近", "家族葬対応", "宿泊可能", "24時間対応"], "operator_name": "株式会社やわらぎ", "rating_avg": 4.2, "review_count": 42},
    {"name": "ベルコ北見シティホール", "slug": "hokkaido-bellco-kitami", "venue_type": "private_hall", "description": "ベルコの北見斎場。三輪エリアに位置し、広い駐車場を備えた斎場。互助会会員は割引利用可能。", "address": "北海道北見市三輪4丁目2-15", "prefecture_slug": "hokkaido", "city_slug": "kitami", "latitude": 43.8100, "longitude": 143.8800, "nearest_station": "JR石北本線 北見駅", "station_walk_minutes": 15, "capacity_max": 70, "hall_count": 2, "has_crematorium": False, "parking_count": 35, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}], "features": ["互助会対応", "駐車場完備", "家族葬対応"], "operator_name": "株式会社ベルコ", "rating_avg": 4.0, "review_count": 35},
    {"name": "北海斎場 北見", "slug": "hokkaido-hokkai-kitami", "venue_type": "private_hall", "description": "北海斎場の北見支店。北見駅近くに位置し、老舗の信頼と丁寧なサービスが好評。", "address": "北海道北見市大通西2丁目5-8", "prefecture_slug": "hokkaido", "city_slug": "kitami", "latitude": 43.8020, "longitude": 143.8920, "nearest_station": "JR石北本線 北見駅", "station_walk_minutes": 5, "capacity_max": 60, "hall_count": 2, "has_crematorium": False, "parking_count": 20, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "和室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000}], "features": ["駅近", "老舗葬儀社", "家族葬対応"], "operator_name": "北海斎場株式会社", "rating_avg": 4.1, "review_count": 28},
    {"name": "家族葬のウィズハウス 北見", "slug": "hokkaido-withhouse-kitami", "venue_type": "private_hall", "description": "ウィズハウスの北見店。居間スタイルの温かみある式場で少人数家族葬に最適。", "address": "北海道北見市高栄東町5丁目3-8", "prefecture_slug": "hokkaido", "city_slug": "kitami", "latitude": 43.7950, "longitude": 143.9000, "nearest_station": "JR石北本線 北見駅", "station_walk_minutes": 12, "capacity_max": 25, "hall_count": 1, "has_crematorium": False, "parking_count": 10, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "キッチン": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}], "features": ["家族葬専用", "1日1組貸切", "居間スタイル"], "operator_name": "株式会社ウィズハウス", "rating_avg": 4.4, "review_count": 18},
    {"name": "コープ葬祭 北見ホール", "slug": "hokkaido-coop-kitami", "venue_type": "private_hall", "description": "コープさっぽろの北見葬祭ホール。組合員割引でリーズナブルに利用可能。", "address": "北海道北見市北進町4丁目1-18", "prefecture_slug": "hokkaido", "city_slug": "kitami", "latitude": 43.8060, "longitude": 143.9050, "nearest_station": "JR石北本線 北見駅", "station_walk_minutes": 10, "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 20, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 188000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}], "features": ["組合員割引", "明瞭価格", "家族葬対応"], "operator_name": "コープさっぽろ", "rating_avg": 4.0, "review_count": 22},
    {"name": "メモリアルホール北見", "slug": "hokkaido-memorial-kitami", "venue_type": "private_hall", "description": "北見市端野エリアのメモリアルホール。地域密着の丁寧なサービスで家族葬に人気。", "address": "北海道北見市端野町二区471", "prefecture_slug": "hokkaido", "city_slug": "kitami", "latitude": 43.7900, "longitude": 143.9200, "nearest_station": "JR石北本線 端野駅", "station_walk_minutes": 8, "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 20, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}], "features": ["地域密着", "駅近", "家族葬対応"], "operator_name": "メモリアルサービス北海道", "rating_avg": 4.0, "review_count": 16},
    {"name": "北見三輪寺会館", "slug": "hokkaido-kitami-miwaji", "venue_type": "temple_hall", "description": "北見市の真宗大谷派寺院が運営する式場。荘厳な本堂での仏式葬儀に対応。宗派不問。", "address": "北海道北見市三輪1丁目5-3", "prefecture_slug": "hokkaido", "city_slug": "kitami", "latitude": 43.8080, "longitude": 143.8850, "nearest_station": "JR石北本線 北見駅", "station_walk_minutes": 10, "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "駐車場": True, "控室": True, "和室": True}, "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 268000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 458000}], "features": ["寺院式場", "宗派不問", "伝統的な雰囲気"], "operator_name": "三輪寺", "rating_avg": 3.9, "review_count": 11},
    # =============================================
    # 小樽市 (6件)
    # =============================================
    {"name": "小樽市斎場", "slug": "hokkaido-otaru-shi-saijo", "venue_type": "public_crematorium", "description": "小樽市が運営する公営斎場。火葬棟を併設。小樽市民は火葬料無料。小樽の港を見下ろす丘の上に位置しています。", "address": "北海道小樽市天神2丁目23-1", "prefecture_slug": "hokkaido", "city_slug": "otaru", "latitude": 43.1900, "longitude": 140.9700, "nearest_station": "JR函館本線 小樽駅", "station_walk_minutes": 20, "capacity_max": 60, "hall_count": 2, "has_crematorium": True, "parking_count": 80, "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 478000}], "features": ["火葬場併設", "公営斎場", "駐車場完備"], "operator_name": "小樽市", "rating_avg": 3.8, "review_count": 35},
    {"name": "やわらぎ斎場 小樽", "slug": "hokkaido-yawaragi-otaru", "venue_type": "private_hall", "description": "やわらぎの小樽拠点。JR小樽駅から車で10分。港町小樽の歴史を感じる落ち着いた空間で、家族葬に人気。", "address": "北海道小樽市稲穂3丁目10-5", "prefecture_slug": "hokkaido", "city_slug": "otaru", "latitude": 43.1920, "longitude": 140.9950, "nearest_station": "JR函館本線 小樽駅", "station_walk_minutes": 8, "capacity_max": 60, "hall_count": 2, "has_crematorium": False, "parking_count": 25, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 568000}], "features": ["駅近", "家族葬対応", "宿泊可能"], "operator_name": "株式会社やわらぎ", "rating_avg": 4.2, "review_count": 38},
    {"name": "ベルコ小樽シティホール", "slug": "hokkaido-bellco-otaru", "venue_type": "private_hall", "description": "ベルコの小樽斎場。築港エリアに位置し、広い駐車場を完備。互助会会員は割引利用可能。", "address": "北海道小樽市築港8-8", "prefecture_slug": "hokkaido", "city_slug": "otaru", "latitude": 43.1850, "longitude": 141.0100, "nearest_station": "JR函館本線 南小樽駅", "station_walk_minutes": 10, "capacity_max": 70, "hall_count": 2, "has_crematorium": False, "parking_count": 35, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}], "features": ["互助会対応", "駐車場完備", "家族葬対応"], "operator_name": "株式会社ベルコ", "rating_avg": 4.0, "review_count": 30},
    {"name": "家族葬のウィズハウス 小樽", "slug": "hokkaido-withhouse-otaru", "venue_type": "private_hall", "description": "ウィズハウスの小樽店。花園エリアの静かな住宅地に位置。居間スタイルの温かみある空間。", "address": "北海道小樽市花園3丁目12-5", "prefecture_slug": "hokkaido", "city_slug": "otaru", "latitude": 43.1880, "longitude": 140.9900, "nearest_station": "JR函館本線 小樽駅", "station_walk_minutes": 10, "capacity_max": 25, "hall_count": 1, "has_crematorium": False, "parking_count": 10, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "キッチン": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}], "features": ["家族葬専用", "1日1組貸切", "居間スタイル"], "operator_name": "株式会社ウィズハウス", "rating_avg": 4.4, "review_count": 18},
    {"name": "小樽龍徳寺会館", "slug": "hokkaido-otaru-ryutokuji", "venue_type": "temple_hall", "description": "小樽市にある曹洞宗の寺院式場。歴史ある本堂で伝統的な仏式葬儀が可能。宗派不問。", "address": "北海道小樽市入船1丁目25-1", "prefecture_slug": "hokkaido", "city_slug": "otaru", "latitude": 43.1860, "longitude": 140.9850, "nearest_station": "JR函館本線 南小樽駅", "station_walk_minutes": 8, "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 12, "facilities": {"安置室": True, "駐車場": True, "控室": True, "和室": True}, "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 268000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 458000}], "features": ["寺院式場", "宗派不問", "歴史ある環境"], "operator_name": "龍徳寺", "rating_avg": 3.9, "review_count": 12},
    {"name": "メモリアルホール小樽", "slug": "hokkaido-memorial-otaru", "venue_type": "private_hall", "description": "小樽市長橋エリアのメモリアルホール。地域密着の丁寧なサービスで家族葬に人気。", "address": "北海道小樽市長橋3丁目8-15", "prefecture_slug": "hokkaido", "city_slug": "otaru", "latitude": 43.2000, "longitude": 140.9800, "nearest_station": "JR函館本線 小樽駅", "station_walk_minutes": 15, "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 20, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}], "features": ["地域密着", "家族葬対応", "駐車場完備"], "operator_name": "メモリアルサービス北海道", "rating_avg": 4.0, "review_count": 20},
    # =============================================
    # 苫小牧市 (8件)
    # =============================================
    {"name": "苫小牧市斎場", "slug": "hokkaido-tomakomai-shi-saijo", "venue_type": "public_crematorium", "description": "苫小牧市が運営する公営斎場。火葬棟を併設。苫小牧市民は火葬料無料。", "address": "北海道苫小牧市高丘42-7", "prefecture_slug": "hokkaido", "city_slug": "tomakomai", "latitude": 42.6450, "longitude": 141.6000, "nearest_station": "JR室蘭本線 苫小牧駅", "station_walk_minutes": 20, "capacity_max": 60, "hall_count": 2, "has_crematorium": True, "parking_count": 100, "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 478000}], "features": ["火葬場併設", "公営斎場", "駐車場完備"], "operator_name": "苫小牧市", "rating_avg": 3.8, "review_count": 35},
    {"name": "やわらぎ斎場 苫小牧", "slug": "hokkaido-yawaragi-tomakomai", "venue_type": "private_hall", "description": "やわらぎの苫小牧拠点。JR苫小牧駅から車で10分。家族葬から一般葬まで対応。24時間365日対応。", "address": "北海道苫小牧市表町5丁目11-5", "prefecture_slug": "hokkaido", "city_slug": "tomakomai", "latitude": 42.6350, "longitude": 141.6100, "nearest_station": "JR室蘭本線 苫小牧駅", "station_walk_minutes": 8, "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 578000}], "features": ["駅近", "家族葬対応", "宿泊可能", "24時間対応"], "operator_name": "株式会社やわらぎ", "rating_avg": 4.2, "review_count": 45},
    {"name": "ベルコ苫小牧シティホール", "slug": "hokkaido-bellco-tomakomai", "venue_type": "private_hall", "description": "ベルコの苫小牧斎場。広い駐車場と充実した設備。互助会会員割引あり。", "address": "北海道苫小牧市日新町2丁目5-18", "prefecture_slug": "hokkaido", "city_slug": "tomakomai", "latitude": 42.6400, "longitude": 141.6200, "nearest_station": "JR室蘭本線 苫小牧駅", "station_walk_minutes": 12, "capacity_max": 70, "hall_count": 2, "has_crematorium": False, "parking_count": 35, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}], "features": ["互助会対応", "駐車場完備", "家族葬対応"], "operator_name": "株式会社ベルコ", "rating_avg": 4.0, "review_count": 38},
    {"name": "家族葬のウィズハウス 苫小牧", "slug": "hokkaido-withhouse-tomakomai", "venue_type": "private_hall", "description": "ウィズハウスの苫小牧店。居間スタイルの温かみある式場。", "address": "北海道苫小牧市光洋町3丁目8-12", "prefecture_slug": "hokkaido", "city_slug": "tomakomai", "latitude": 42.6300, "longitude": 141.6050, "nearest_station": "JR室蘭本線 苫小牧駅", "station_walk_minutes": 10, "capacity_max": 25, "hall_count": 1, "has_crematorium": False, "parking_count": 10, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "キッチン": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}], "features": ["家族葬専用", "1日1組貸切", "居間スタイル"], "operator_name": "株式会社ウィズハウス", "rating_avg": 4.4, "review_count": 20},
    {"name": "北海斎場 苫小牧", "slug": "hokkaido-hokkai-tomakomai", "venue_type": "private_hall", "description": "北海斎場の苫小牧支店。老舗の安心感と丁寧なサービス。", "address": "北海道苫小牧市旭町3丁目5-15", "prefecture_slug": "hokkaido", "city_slug": "tomakomai", "latitude": 42.6380, "longitude": 141.6150, "nearest_station": "JR室蘭本線 苫小牧駅", "station_walk_minutes": 8, "capacity_max": 60, "hall_count": 2, "has_crematorium": False, "parking_count": 20, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "和室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}], "features": ["駅近", "老舗葬儀社", "家族葬対応"], "operator_name": "北海斎場株式会社", "rating_avg": 4.1, "review_count": 30},
    {"name": "コープ葬祭 苫小牧ホール", "slug": "hokkaido-coop-tomakomai", "venue_type": "private_hall", "description": "コープさっぽろの苫小牧葬祭ホール。組合員割引でリーズナブル。", "address": "北海道苫小牧市双葉町2丁目18-5", "prefecture_slug": "hokkaido", "city_slug": "tomakomai", "latitude": 42.6320, "longitude": 141.6080, "nearest_station": "JR室蘭本線 苫小牧駅", "station_walk_minutes": 10, "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 20, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 188000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}], "features": ["組合員割引", "明瞭価格", "家族葬対応"], "operator_name": "コープさっぽろ", "rating_avg": 4.0, "review_count": 22},
    {"name": "メモリアルホール苫小牧", "slug": "hokkaido-memorial-tomakomai", "venue_type": "private_hall", "description": "苫小牧市沼ノ端エリアのメモリアルホール。広い駐車場と落ち着いた空間。", "address": "北海道苫小牧市沼ノ端中央4丁目18-8", "prefecture_slug": "hokkaido", "city_slug": "tomakomai", "latitude": 42.6500, "longitude": 141.6350, "nearest_station": "JR千歳線 沼ノ端駅", "station_walk_minutes": 8, "capacity_max": 50, "hall_count": 2, "has_crematorium": False, "parking_count": 25, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}], "features": ["駅近", "駐車場完備", "家族葬対応"], "operator_name": "メモリアルサービス北海道", "rating_avg": 4.0, "review_count": 22},
    {"name": "苫小牧樽前寺会館", "slug": "hokkaido-tomakomai-tarumaiji", "venue_type": "temple_hall", "description": "苫小牧市の日蓮宗寺院が運営する式場。伝統的な仏式葬儀に対応。宗派不問。", "address": "北海道苫小牧市矢代町2丁目8-3", "prefecture_slug": "hokkaido", "city_slug": "tomakomai", "latitude": 42.6370, "longitude": 141.6020, "nearest_station": "JR室蘭本線 苫小牧駅", "station_walk_minutes": 10, "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 12, "facilities": {"安置室": True, "駐車場": True, "控室": True, "和室": True}, "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 268000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 458000}], "features": ["寺院式場", "宗派不問", "伝統的な雰囲気"], "operator_name": "樽前寺", "rating_avg": 3.9, "review_count": 10},
]

# 10件ずつバッチ投入
total = len(venues)
print(f"北海道バッチ4: 釧路+帯広+北見+小樽+苫小牧 {total}件を投入開始")

for i in range(0, total, 10):
    batch = venues[i:i+10]
    code = insert_batch(batch)
    print(f"  バッチ {i//10+1}: {len(batch)}件 → HTTP {code}")
    if code != "201":
        data_json = json.dumps(batch, ensure_ascii=False)
        result = subprocess.run([
            "curl", "-s",
            "-X", "POST", SUPABASE_URL,
            "-H", f"apikey: {API_KEY}",
            "-H", f"Authorization: Bearer {API_KEY}",
            "-H", "Content-Type: application/json",
            "-H", "Prefer: return=minimal",
            "-H", "User-Agent: Mozilla/5.0",
            "-d", data_json
        ], capture_output=True, text=True)
        print(f"    エラー詳細: {result.stdout[:500]}")
    time.sleep(1)

print(f"バッチ4完了: {total}件")
