#!/usr/bin/env python3
"""
北海道・札幌市（後半40件）: 南区・西区・手稲区・厚別区・清田区 + 公営火葬場
"""

import json
import urllib.request
import urllib.error
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

HEADERS = {
    "apikey": API_KEY,
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal",
}

venues = [
    # =============================================
    # 札幌市南区 — 6件
    # =============================================
    {
        "name": "やわらぎ斎場 川沿",
        "slug": "yawaragi-kawazoi-sapporo",
        "venue_type": "private_hall",
        "description": "札幌市南区川沿のやわらぎ斎場。豊平川沿いの静かなエリアに位置し、自然に囲まれた落ち着いた雰囲気。家族葬を中心に、心安らぐお別れの時間を提供しています。広い駐車場完備。",
        "address": "北海道札幌市南区川沿8条1丁目1-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0100,
        "longitude": 141.3350,
        "nearest_station": "地下鉄南北線 真駒内駅",
        "station_walk_minutes": 15,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}],
        "features": ["駐車場完備", "家族葬対応", "自然に囲まれた環境"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.0,
        "review_count": 14,
    },
    {
        "name": "やわらぎ斎場 藤野",
        "slug": "yawaragi-fujino-sapporo",
        "venue_type": "private_hall",
        "description": "札幌市南区藤野のやわらぎ斎場。藤野エリアの住民に親しまれている地域密着型の葬儀場。落ち着いた空間で故人とのお別れができます。冬季も除雪対応で安心のアクセス。",
        "address": "北海道札幌市南区藤野3条4丁目2-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 42.9950,
        "longitude": 141.3100,
        "nearest_station": "地下鉄南北線 真駒内駅",
        "station_walk_minutes": 25,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}],
        "features": ["地域密着", "駐車場完備", "家族葬対応"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 3.9,
        "review_count": 10,
    },
    {
        "name": "やわらぎ斎場 澄川",
        "slug": "yawaragi-sumikawa-sapporo",
        "venue_type": "private_hall",
        "description": "札幌市南区澄川のやわらぎ斎場。地下鉄南北線澄川駅から徒歩圏内と公共交通機関でのアクセスが便利。澄川・平岸エリアの方に多く利用されている葬儀場です。",
        "address": "北海道札幌市南区澄川3条6丁目1-15",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0230,
        "longitude": 141.3530,
        "nearest_station": "地下鉄南北線 澄川駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["駅近", "家族葬対応", "一般葬対応", "バリアフリー"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.0,
        "review_count": 16,
    },
    {
        "name": "ウィズハウス 川沿",
        "slug": "withhouse-kawazoi-sapporo",
        "venue_type": "private_hall",
        "description": "コープの家族葬ウィズハウスの川沿店。札幌市南区川沿12条に位置し、1日1組貸切の家族葬ホール。コープ会員割引あり。自然豊かな環境の中で心温まるお別れを。",
        "address": "北海道札幌市南区川沿12条2丁目2-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0050,
        "longitude": 141.3350,
        "nearest_station": "地下鉄南北線 真駒内駅",
        "station_walk_minutes": 20,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["コープ会員割引", "1日1組貸切", "家族葬専用", "自然豊か"],
        "operator_name": "めもるホールディングス",
        "rating_avg": 4.1,
        "review_count": 12,
    },
    {
        "name": "メモリアホール澄川",
        "slug": "memoria-sumikawa-sapporo",
        "venue_type": "private_hall",
        "description": "メモリアホール（現ティア）が運営する澄川エリアの葬儀場。地下鉄南北線澄川駅から近く、こぢんまりとした家族葬に最適。温かみのある内装と丁寧な対応が評判です。",
        "address": "北海道札幌市南区澄川4条2丁目5-10",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0220,
        "longitude": 141.3500,
        "nearest_station": "地下鉄南北線 澄川駅",
        "station_walk_minutes": 6,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["駅近", "家族葬対応", "少人数対応"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.0,
        "review_count": 11,
    },
    {
        "name": "家族葬のディアネス 南あいの里",
        "slug": "dearness-minami-ainosato",
        "venue_type": "private_hall",
        "description": "家族葬のディアネスが運営する南あいの里エリアの家族葬専用ホール。静かな住宅街にあり、少人数で故人をゆっくり偲べる空間。温かみのある照明と木の質感が心を癒します。",
        "address": "北海道札幌市北区南あいの里6丁目7-10",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1430,
        "longitude": 141.3680,
        "nearest_station": "JR学園都市線 拓北駅",
        "station_walk_minutes": 10,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}],
        "features": ["家族葬専用", "少人数対応", "閑静な立地"],
        "operator_name": "ディアネス",
        "rating_avg": 4.2,
        "review_count": 8,
    },
    # =============================================
    # 札幌市西区 — 8件
    # =============================================
    {
        "name": "やわらぎ斎場 西町",
        "slug": "yawaragi-nishimachi-sapporo",
        "venue_type": "private_hall",
        "description": "札幌市西区西町のやわらぎ斎場。地下鉄東西線発寒南駅から近く、西区の中心的な葬儀場。複数の式場を持ち、家族葬から大規模な一般葬まで対応可能。別館と合わせて幅広いニーズに対応。",
        "address": "北海道札幌市西区西町南18丁目1-38",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0550,
        "longitude": 141.3000,
        "nearest_station": "地下鉄東西線 発寒南駅",
        "station_walk_minutes": 5,
        "capacity_max": 80,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["駅近", "大型式場", "家族葬対応", "一般葬対応"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.1,
        "review_count": 22,
    },
    {
        "name": "やわらぎ斎場 西野",
        "slug": "yawaragi-nishino-sapporo",
        "venue_type": "private_hall",
        "description": "札幌市西区西野のやわらぎ斎場。西野エリアの住宅街に位置し、地域に根差した葬儀場。落ち着いた雰囲気で、家族葬を中心にご利用いただいています。広い駐車場あり。",
        "address": "北海道札幌市西区西野5条4丁目6-17",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0570,
        "longitude": 141.2900,
        "nearest_station": "地下鉄東西線 発寒南駅",
        "station_walk_minutes": 15,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}],
        "features": ["駐車場完備", "家族葬対応", "地域密着"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 3.9,
        "review_count": 13,
    },
    {
        "name": "やわらぎファミリア 八軒",
        "slug": "yawaragi-familia-hachiken",
        "venue_type": "private_hall",
        "description": "やわらぎグループのファミリアブランド八軒店。JR琴似駅から徒歩圏内で交通至便。少人数の家族葬に特化した温かみのあるホール。1日1組貸切で、ゆったりとしたお別れの時間を。",
        "address": "北海道札幌市西区八軒5条西1丁目2-26",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0750,
        "longitude": 141.3200,
        "nearest_station": "JR函館本線 琴似駅",
        "station_walk_minutes": 8,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}],
        "features": ["駅近", "家族葬専用", "1日1組貸切", "少人数対応"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.2,
        "review_count": 10,
    },
    {
        "name": "やわらぎファミリア 発寒",
        "slug": "yawaragi-familia-hassamu",
        "venue_type": "private_hall",
        "description": "やわらぎグループのファミリアブランド発寒店。札幌市西区発寒に位置し、JR発寒駅からもアクセス可能。少人数での家族葬に最適なコンパクトな空間を提供します。",
        "address": "北海道札幌市西区発寒13条3丁目7-42",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0900,
        "longitude": 141.2850,
        "nearest_station": "JR函館本線 発寒駅",
        "station_walk_minutes": 10,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}],
        "features": ["家族葬専用", "少人数対応", "駐車場完備"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.0,
        "review_count": 9,
    },
    {
        "name": "ウィズハウス 発寒",
        "slug": "withhouse-hassamu-sapporo",
        "venue_type": "private_hall",
        "description": "コープの家族葬ウィズハウスの発寒店。札幌市西区発寒に位置し、コープ会員割引が利用可能。木のぬくもりを感じるナチュラルな内装で、家族葬に最適な空間です。",
        "address": "北海道札幌市西区発寒13条4丁目13-3",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0910,
        "longitude": 141.2830,
        "nearest_station": "JR函館本線 発寒駅",
        "station_walk_minutes": 8,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["コープ会員割引", "家族葬専用", "24時間対応"],
        "operator_name": "めもるホールディングス",
        "rating_avg": 4.1,
        "review_count": 15,
    },
    {
        "name": "メモリアホール西野山の手",
        "slug": "memoria-nishino-yamanote",
        "venue_type": "private_hall",
        "description": "メモリアホール（現ティア）が運営する西野・山の手エリアの葬儀場。閑静な住宅街に位置し、落ち着いた雰囲気。小規模から中規模の葬儀に対応し、きめ細かなサービスが好評です。",
        "address": "北海道札幌市西区山の手3条6丁目4-15",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0620,
        "longitude": 141.3100,
        "nearest_station": "地下鉄東西線 琴似駅",
        "station_walk_minutes": 12,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["家族葬対応", "閑静な立地", "駐車場完備"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.0,
        "review_count": 14,
    },
    {
        "name": "フリエホール しんことに",
        "slug": "furie-hall-shinkotoni",
        "venue_type": "private_hall",
        "description": "コープの家族葬フリエホールの新琴似店。札幌市北区新琴似に位置し、カジュアルで温かみのある家族葬を低価格で提供。コープ会員は追加割引あり。少人数に特化した空間です。",
        "address": "北海道札幌市北区新琴似7条13丁目3-10",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1100,
        "longitude": 141.3480,
        "nearest_station": "JR学園都市線 新琴似駅",
        "station_walk_minutes": 12,
        "capacity_max": 20,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["コープ会員割引", "家族葬専用", "少人数対応", "低価格"],
        "operator_name": "めもるホールディングス",
        "rating_avg": 3.9,
        "review_count": 8,
    },
    {
        "name": "香華殿 琴似斎場",
        "slug": "kokaden-kotoni-saijo",
        "venue_type": "private_hall",
        "description": "香華殿グループが運営する西区琴似エリアの葬儀場。JR琴似駅・地下鉄琴似駅の両方からアクセス可能で交通至便。格式のある落ち着いた式場で、家族葬から一般葬まで対応します。",
        "address": "北海道札幌市西区琴似2条3丁目1-20",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0680,
        "longitude": 141.3130,
        "nearest_station": "JR函館本線 琴似駅",
        "station_walk_minutes": 5,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 18,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 520000}],
        "features": ["駅近", "家族葬対応", "一般葬対応", "格式高い"],
        "operator_name": "香華殿",
        "rating_avg": 4.1,
        "review_count": 16,
    },
    # =============================================
    # 札幌市手稲区 — 8件
    # =============================================
    {
        "name": "やわらぎ斎場 手稲",
        "slug": "yawaragi-teine-sapporo",
        "venue_type": "private_hall",
        "description": "札幌市手稲区曙のやわらぎ斎場。JR手稲駅から車で5分の好立地。手稲区を代表する葬儀場で、家族葬から一般葬まで幅広く対応。広々とした駐車場と充実した設備が特徴です。",
        "address": "北海道札幌市手稲区曙4条1丁目6-10",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1100,
        "longitude": 141.2400,
        "nearest_station": "JR函館本線 手稲駅",
        "station_walk_minutes": 12,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["駐車場完備", "家族葬対応", "一般葬対応", "バリアフリー"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.1,
        "review_count": 18,
    },
    {
        "name": "やわらぎファミリア 手稲",
        "slug": "yawaragi-familia-teine",
        "venue_type": "private_hall",
        "description": "やわらぎグループのファミリアブランド手稲店。手稲区曙に位置し、やわらぎ斎場手稲の近くにある少人数向けホール。家族葬に特化したコンパクトな空間を提供します。",
        "address": "北海道札幌市手稲区曙2条3丁目4-37",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1080,
        "longitude": 141.2430,
        "nearest_station": "JR函館本線 手稲駅",
        "station_walk_minutes": 10,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}],
        "features": ["家族葬専用", "少人数対応", "駐車場完備"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.0,
        "review_count": 9,
    },
    {
        "name": "やわらぎ斎場 稲穂",
        "slug": "yawaragi-inaho-sapporo",
        "venue_type": "private_hall",
        "description": "札幌市手稲区稲穂のやわらぎ斎場。JR星置駅から近く、手稲区西部エリアのお客様に便利な立地。温かみのある式場で、家族葬を中心にご利用いただいています。",
        "address": "北海道札幌市手稲区稲穂2条3丁目7-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1150,
        "longitude": 141.2200,
        "nearest_station": "JR函館本線 星置駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}],
        "features": ["駅近", "家族葬対応", "駐車場完備"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.0,
        "review_count": 11,
    },
    {
        "name": "ウィズハウス 手稲",
        "slug": "withhouse-teine-sapporo",
        "venue_type": "private_hall",
        "description": "コープの家族葬ウィズハウスの手稲店。明日風エリアに位置し、別邸タイプも併設。コープ会員割引あり。モダンな内装と充実した設備で、心温まる家族葬を提供します。",
        "address": "北海道札幌市手稲区明日風5丁目19-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1200,
        "longitude": 141.2300,
        "nearest_station": "JR函館本線 稲穂駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["コープ会員割引", "別邸タイプあり", "家族葬専用"],
        "operator_name": "めもるホールディングス",
        "rating_avg": 4.2,
        "review_count": 16,
    },
    {
        "name": "ウィズハウス 手稲前田",
        "slug": "withhouse-teine-maeda",
        "venue_type": "private_hall",
        "description": "コープの家族葬ウィズハウスの手稲前田店。前田エリアに位置し、スーパーや公共施設が近い便利な立地。少人数の家族葬に特化し、温かみのある空間でお別れの時間を過ごせます。",
        "address": "北海道札幌市手稲区前田5条7丁目4-16",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1050,
        "longitude": 141.2500,
        "nearest_station": "JR函館本線 手稲駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["コープ会員割引", "家族葬専用", "便利な立地"],
        "operator_name": "めもるホールディングス",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "ていね北海斎場",
        "slug": "teine-hokkai-saijo",
        "venue_type": "private_hall",
        "description": "手稲区富丘に位置する北海斎場の手稲支店。札幌市山口斎場（火葬場）に近く、火葬場への移動が便利。広い式場と駐車場を備え、一般葬にも対応可能な総合葬儀場です。",
        "address": "北海道札幌市手稲区富丘2条5丁目1-30",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1000,
        "longitude": 141.2600,
        "nearest_station": "JR函館本線 稲積公園駅",
        "station_walk_minutes": 12,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True, "送迎バス": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 285000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 480000}],
        "features": ["火葬場近い", "送迎バスあり", "一般葬対応", "駐車場完備"],
        "operator_name": "北海斎場",
        "rating_avg": 4.0,
        "review_count": 20,
    },
    {
        "name": "家族葬ホール ラベンダー",
        "slug": "lavender-hall-teine",
        "venue_type": "private_hall",
        "description": "札幌市手稲区前田の家族葬専用ホール。ラベンダーの名にふさわしい温かみのある上品な空間。少人数での家族葬に特化しており、故人とのゆったりとしたお別れの時間を大切にしています。",
        "address": "北海道札幌市手稲区前田8条11丁目1-15",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1100,
        "longitude": 141.2350,
        "nearest_station": "JR函館本線 手稲駅",
        "station_walk_minutes": 15,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 290000}],
        "features": ["家族葬専用", "少人数対応", "上品な空間"],
        "operator_name": "ラベンダーホール",
        "rating_avg": 4.2,
        "review_count": 8,
    },
    {
        "name": "札幌市山口斎場",
        "slug": "sapporo-yamaguchi-saijo",
        "venue_type": "public_crematorium",
        "description": "札幌市が運営する公営火葬場。手稲区山口に位置し、中央区・北区・東区・西区・手稲区の火葬を担当。火葬炉を多数備え、通夜室も利用可能。札幌市民は火葬料無料（12歳以上）。",
        "address": "北海道札幌市手稲区手稲山口308番地",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1230,
        "longitude": 141.2100,
        "nearest_station": "JR函館本線 手稲駅",
        "station_walk_minutes": 30,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 150,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "通夜室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 0}],
        "features": ["火葬場", "公営斎場", "駐車場完備", "札幌市民火葬料無料"],
        "operator_name": "札幌市",
        "rating_avg": 3.8,
        "review_count": 30,
    },
    # =============================================
    # 札幌市厚別区 — 4件
    # =============================================
    {
        "name": "やわらぎ斎場 厚別",
        "slug": "yawaragi-atsubetsu-sapporo",
        "venue_type": "private_hall",
        "description": "札幌市厚別区のやわらぎ斎場。JR森林公園駅から近く、厚別区の中心的な葬儀場。家族葬から一般葬まで対応可能で、広い式場と充実した設備を備えています。",
        "address": "北海道札幌市厚別区厚別南3丁目2-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0450,
        "longitude": 141.4350,
        "nearest_station": "JR函館本線 森林公園駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["駅近", "家族葬対応", "一般葬対応", "駐車場完備"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.0,
        "review_count": 17,
    },
    {
        "name": "やわらぎ斎場 厚別西",
        "slug": "yawaragi-atsubetsunishi",
        "venue_type": "private_hall",
        "description": "札幌市厚別区厚別西のやわらぎ斎場。地下鉄東西線ひばりが丘駅からアクセス可能。閑静な住宅街にある落ち着いた葬儀場で、家族葬を中心に地域の方にご利用いただいています。",
        "address": "北海道札幌市厚別区厚別西5条4丁目1-40",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0480,
        "longitude": 141.4200,
        "nearest_station": "地下鉄東西線 ひばりが丘駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}],
        "features": ["家族葬対応", "閑静な立地", "駐車場完備"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "ウィズハウス 大谷地",
        "slug": "withhouse-oyachi-sapporo",
        "venue_type": "private_hall",
        "description": "コープの家族葬ウィズハウスの大谷地店。地下鉄東西線大谷地駅からアクセス可能。厚別区の家族葬ニーズに応え、コープ会員割引で経済的な葬儀を提供します。",
        "address": "北海道札幌市厚別区大谷地東5丁目4-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0400,
        "longitude": 141.4300,
        "nearest_station": "地下鉄東西線 大谷地駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["コープ会員割引", "家族葬専用", "24時間対応"],
        "operator_name": "めもるホールディングス",
        "rating_avg": 4.1,
        "review_count": 13,
    },
    {
        "name": "メモリアホール厚別",
        "slug": "memoria-atsubetsu-sapporo",
        "venue_type": "private_hall",
        "description": "メモリアホール（現ティア）が運営する厚別区の葬儀場。新札幌エリアに位置し、JR新札幌駅・地下鉄新さっぽろ駅の両方からアクセス可能。家族葬から一般葬まで幅広く対応します。",
        "address": "北海道札幌市厚別区厚別中央2条5丁目3-20",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0350,
        "longitude": 141.4150,
        "nearest_station": "JR千歳線 新札幌駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["駅近", "家族葬対応", "一般葬対応"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.0,
        "review_count": 15,
    },
    # =============================================
    # 札幌市清田区 — 4件
    # =============================================
    {
        "name": "やわらぎ斎場 清田",
        "slug": "yawaragi-kiyota-sapporo",
        "venue_type": "private_hall",
        "description": "札幌市清田区のやわらぎ斎場。清田区の中心に位置し、里塚斎場（火葬場）へのアクセスも便利。家族葬から一般葬まで対応し、清田区・豊平区エリアの方に広く利用されています。",
        "address": "北海道札幌市清田区清田1条1丁目3-83",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0200,
        "longitude": 141.4100,
        "nearest_station": "地下鉄東豊線 福住駅",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["火葬場近い", "家族葬対応", "一般葬対応", "駐車場完備"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.0,
        "review_count": 16,
    },
    {
        "name": "やわらぎファミリア 清田",
        "slug": "yawaragi-familia-kiyota",
        "venue_type": "private_hall",
        "description": "やわらぎグループのファミリアブランド清田店。清田区清田に位置し、少人数の家族葬に特化。やわらぎ斎場清田に近い立地で、家族葬専用の温かな空間を提供しています。",
        "address": "北海道札幌市清田区清田7条2丁目1-22",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0150,
        "longitude": 141.4150,
        "nearest_station": "地下鉄東豊線 福住駅",
        "station_walk_minutes": 25,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}],
        "features": ["家族葬専用", "少人数対応", "駐車場完備"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.0,
        "review_count": 9,
    },
    {
        "name": "ウィズハウス 清田",
        "slug": "withhouse-kiyota-sapporo",
        "venue_type": "private_hall",
        "description": "コープの家族葬ウィズハウスの清田店。北広島市大曲並木に位置し、清田区・北広島市のお客様に便利。2F・3F・別邸の3タイプがあり、人数や好みに合わせて選択可能。",
        "address": "北海道北広島市大曲並木3丁目1-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0050,
        "longitude": 141.4200,
        "nearest_station": "JR千歳線 上野幌駅",
        "station_walk_minutes": 20,
        "capacity_max": 40,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["コープ会員割引", "3タイプから選択", "家族葬専用"],
        "operator_name": "めもるホールディングス",
        "rating_avg": 4.1,
        "review_count": 14,
    },
    {
        "name": "札幌市里塚斎場",
        "slug": "sapporo-satozuka-saijo",
        "venue_type": "public_crematorium",
        "description": "札幌市が運営する公営火葬場。清田区里塚に位置し、白石区・豊平区・厚別区・清田区・南区の火葬を担当。火葬炉30基を備える大規模施設。札幌市民は火葬料無料（12歳以上）。",
        "address": "北海道札幌市清田区里塚506番地",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0050,
        "longitude": 141.4350,
        "nearest_station": "JR千歳線 上野幌駅",
        "station_walk_minutes": 30,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 200,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "通夜室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 0}],
        "features": ["火葬場", "公営斎場", "大型施設", "札幌市民火葬料無料"],
        "operator_name": "札幌市",
        "rating_avg": 3.8,
        "review_count": 28,
    },
]

def insert_batch(batch):
    data_json = json.dumps(batch, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(SUPABASE_URL, data=data_json, headers=HEADERS, method="POST")
    try:
        with urllib.request.urlopen(req) as res:
            return res.status
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"  HTTPError {e.code}: {body[:300]}")
        return e.code

total = len(venues)
print(f"北海道・札幌市（後半）: {total}件を投入開始")

ok = 0
for i in range(0, total, 10):
    batch = venues[i:i+10]
    code = insert_batch(batch)
    names = ", ".join(v["name"] for v in batch)
    print(f"  バッチ {i//10+1}: {code} ({len(batch)}件) — {names}")
    if code in (200, 201):
        ok += len(batch)
    time.sleep(0.5)

print(f"\n完了: {ok}/{total}件 投入成功")
