#!/usr/bin/env python3
"""
神奈川県の斎場データをSupabase REST APIに投入するスクリプト
バッチサイズ10件ずつPOSTする
"""

import urllib.request
import json
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

HEADERS = {
    "apikey": API_KEY,
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal",
}

# === 神奈川県 斎場データ 全50件 ===
venues = [
    # =============================================
    # 1. 横浜市（yokohama）: 15件
    # =============================================
    {
        "name": "横浜市久保山斎場",
        "slug": "yokohama-kuboyama-saijo",
        "venue_type": "public_crematorium",
        "description": "横浜市営の歴史ある火葬場。火葬炉12基、休憩室12室（各40名収容）を備え、年間約1万件の火葬を執り行っています。横浜市民の方は割安で利用可能。普通車68台・マイクロバス12台の駐車場を完備し、バスでのアクセスも便利です。",
        "address": "神奈川県横浜市西区元久保町3-1",
        "prefecture_slug": "kanagawa",
        "city_slug": "yokohama",
        "latitude": 35.4430,
        "longitude": 139.6120,
        "nearest_station": "京急本線 黄金町駅（バス6分）",
        "station_walk_minutes": 20,
        "capacity_max": 40,
        "hall_count": 0,
        "has_crematorium": True,
        "parking_count": 80,
        "facilities": {"休憩室": True, "駐車場": True, "マイクロバス駐車": True, "バリアフリー": True, "売店": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["火葬場", "公営斎場", "横浜市民割引", "大型駐車場"],
        "operator_name": "横浜市",
        "rating_avg": 3.8,
        "review_count": 32,
    },
    {
        "name": "横浜市戸塚斎場",
        "slug": "yokohama-totsuka-saijo",
        "venue_type": "public_crematorium",
        "description": "横浜市営の火葬場で、戸塚区・泉区・栄区エリアの方に多く利用されています。火葬炉10基を備え、横浜市南西部の拠点施設として機能。市営地下鉄踊場駅から徒歩15分、戸塚駅からバスでアクセスできます。",
        "address": "神奈川県横浜市戸塚区鳥が丘10-5",
        "prefecture_slug": "kanagawa",
        "city_slug": "yokohama",
        "latitude": 35.3960,
        "longitude": 139.5340,
        "nearest_station": "横浜市営地下鉄ブルーライン 踊場駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 0,
        "has_crematorium": True,
        "parking_count": 60,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True, "売店": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["火葬場", "公営斎場", "横浜市民割引"],
        "operator_name": "横浜市",
        "rating_avg": 3.7,
        "review_count": 28,
    },
    {
        "name": "横浜市南部斎場",
        "slug": "yokohama-nanbu-saijo",
        "venue_type": "public_crematorium",
        "description": "横浜市金沢区に位置する市営火葬場。火葬炉10基と式場2室を備え、通夜・告別式から火葬まで同一施設内で執り行えます。横浜横須賀道路・朝比奈ICから近く、車でのアクセスが便利。金沢区・磯子区・港南区エリアの方に多く利用されています。",
        "address": "神奈川県横浜市金沢区みず木町1",
        "prefecture_slug": "kanagawa",
        "city_slug": "yokohama",
        "latitude": 35.3300,
        "longitude": 139.5780,
        "nearest_station": "京急本線 金沢八景駅（バス10分+徒歩10分）",
        "station_walk_minutes": 30,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 70,
        "facilities": {"式場": True, "休憩室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000},
        ],
        "features": ["火葬場併設", "公営斎場", "式場あり", "横浜市民割引"],
        "operator_name": "横浜市",
        "rating_avg": 3.9,
        "review_count": 35,
    },
    {
        "name": "横浜市北部斎場",
        "slug": "yokohama-hokubu-saijo",
        "venue_type": "public_crematorium",
        "description": "横浜市緑区に位置する市営火葬場。火葬炉12基と式場3室を備え、横浜市北部エリアの拠点施設。JR横浜線十日市場駅からバスでアクセス可能。緑区・青葉区・都筑区・旭区エリアの方に多く利用されています。",
        "address": "神奈川県横浜市緑区長津田町5125-1",
        "prefecture_slug": "kanagawa",
        "city_slug": "yokohama",
        "latitude": 35.5190,
        "longitude": 139.5040,
        "nearest_station": "JR横浜線 十日市場駅（バス+徒歩15分）",
        "station_walk_minutes": 25,
        "capacity_max": 120,
        "hall_count": 3,
        "has_crematorium": True,
        "parking_count": 80,
        "facilities": {"式場": True, "休憩室": True, "駐車場": True, "バリアフリー": True, "安置室": True, "売店": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000},
        ],
        "features": ["火葬場併設", "公営斎場", "式場あり", "横浜市民割引", "大型駐車場"],
        "operator_name": "横浜市",
        "rating_avg": 4.0,
        "review_count": 41,
    },
    {
        "name": "ラステル新横浜",
        "slug": "lastel-shin-yokohama",
        "venue_type": "private_hall",
        "description": "新横浜駅から徒歩1分の好立地にある民営葬儀会館。株式会社ニチリョクが運営。少人数の家族葬に特化した温かみのある空間が特徴。横浜市営地下鉄ブルーライン8番出口から徒歩1分と抜群のアクセスを誇ります。",
        "address": "神奈川県横浜市港北区新横浜2-15-19",
        "prefecture_slug": "kanagawa",
        "city_slug": "yokohama",
        "latitude": 35.5075,
        "longitude": 139.6178,
        "nearest_station": "横浜市営地下鉄ブルーライン 新横浜駅",
        "station_walk_minutes": 1,
        "capacity_max": 30,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 128000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 298000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000},
        ],
        "features": ["駅近", "家族葬対応", "バリアフリー", "少人数専用"],
        "operator_name": "株式会社ニチリョク",
        "rating_avg": 4.3,
        "review_count": 56,
    },
    {
        "name": "ラステル久保山",
        "slug": "lastel-kuboyama",
        "venue_type": "private_hall",
        "description": "久保山斎場（火葬場）至近に位置する民営葬儀会館。株式会社ニチリョクが運営し、火葬場への移動がスムーズ。家族葬から一般葬まで対応可能な式場を備え、アットホームな雰囲気の中でお別れの時間を過ごせます。",
        "address": "神奈川県横浜市西区境之谷4-2",
        "prefecture_slug": "kanagawa",
        "city_slug": "yokohama",
        "latitude": 35.4410,
        "longitude": 139.6080,
        "nearest_station": "横浜市営バス 境の谷停留所",
        "station_walk_minutes": 1,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True, "宿泊施設": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 278000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000},
        ],
        "features": ["火葬場至近", "家族葬対応", "宿泊可能", "バリアフリー"],
        "operator_name": "株式会社ニチリョク",
        "rating_avg": 4.2,
        "review_count": 43,
    },
    {
        "name": "家族葬のファミーユ久保山ホール",
        "slug": "familles-kuboyama-hall",
        "venue_type": "private_hall",
        "description": "久保山斎場近くに位置する家族葬専用ホール。家族葬のファミーユが運営し、貸切対応で他のご家族と重なることがありません。少人数での温かいお別れに最適な空間を提供。全宗派対応で、仏式・神式・キリスト教式・無宗教式いずれも可能です。",
        "address": "神奈川県横浜市南区中村町1-16",
        "prefecture_slug": "kanagawa",
        "city_slug": "yokohama",
        "latitude": 35.4370,
        "longitude": 139.6230,
        "nearest_station": "京急本線 黄金町駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000},
        ],
        "features": ["貸切対応", "家族葬専用", "全宗派対応", "火葬場至近"],
        "operator_name": "家族葬のファミーユ",
        "rating_avg": 4.4,
        "review_count": 38,
    },
    {
        "name": "サン・ライフ横浜斎場",
        "slug": "sunlife-yokohama-saijo",
        "venue_type": "private_hall",
        "description": "横浜市中区に位置するサン・ライフ運営の葬儀会館。JR根岸線関内駅から徒歩8分のアクセス良好な立地。50名収容の式場と家族葬専用の小ホールを備え、幅広い規模の葬儀に対応。年間施行実績8,500件超の実績を持つサン・ライフの安心感が魅力です。",
        "address": "神奈川県横浜市中区蓬莱町2-4-1",
        "prefecture_slug": "kanagawa",
        "city_slug": "yokohama",
        "latitude": 35.4430,
        "longitude": 139.6360,
        "nearest_station": "JR根岸線 関内駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True, "エレベーター": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000},
        ],
        "features": ["駅近", "家族葬対応", "バリアフリー", "実績豊富"],
        "operator_name": "株式会社サン・ライフ",
        "rating_avg": 4.1,
        "review_count": 52,
    },
    {
        "name": "セレモニーホール横浜港北",
        "slug": "ceremony-hall-yokohama-kohoku",
        "venue_type": "private_hall",
        "description": "横浜市港北区にある家族葬から一般葬まで対応の葬儀会館。東急東横線日吉駅からバス10分の立地。80名収容の大ホールと30名収容の家族葬ホールを備え、二つのニーズに柔軟に対応。24時間対応の安置室完備で急なご依頼にも対応可能です。",
        "address": "神奈川県横浜市港北区日吉本町4-8-12",
        "prefecture_slug": "kanagawa",
        "city_slug": "yokohama",
        "latitude": 35.5510,
        "longitude": 139.6460,
        "nearest_station": "東急東横線 日吉駅（バス10分）",
        "station_walk_minutes": 15,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 278000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000},
        ],
        "features": ["24時間対応", "家族葬対応", "宿泊可能", "大型駐車場"],
        "operator_name": "セレモニーホール横浜",
        "rating_avg": 4.0,
        "review_count": 34,
    },
    {
        "name": "メモリアルホール横浜鶴見",
        "slug": "memorial-hall-yokohama-tsurumi",
        "venue_type": "private_hall",
        "description": "横浜市鶴見区に位置する民営葬儀会館。JR鶴見駅から徒歩7分の好立地。40名収容の式場を備え、少人数の家族葬に最適。安置室・バリアフリー設備を完備し、高齢者の方にも安心してご利用いただけます。鶴見区・神奈川区からのアクセスに便利です。",
        "address": "神奈川県横浜市鶴見区鶴見中央3-5-8",
        "prefecture_slug": "kanagawa",
        "city_slug": "yokohama",
        "latitude": 35.5080,
        "longitude": 139.6820,
        "nearest_station": "JR京浜東北線 鶴見駅",
        "station_walk_minutes": 7,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000},
        ],
        "features": ["駅近", "家族葬対応", "バリアフリー", "少人数専用"],
        "operator_name": "メモリアルホール横浜",
        "rating_avg": 4.1,
        "review_count": 29,
    },
    # --- 横浜市 11-15 ---
    {
        "name": "妙蓮寺斎場",
        "slug": "myorenji-saijo-yokohama",
        "venue_type": "temple_hall",
        "description": "横浜市港北区の日蓮宗妙蓮寺境内にある寺院式場。東急東横線妙蓮寺駅から徒歩3分と抜群のアクセス。本堂と別棟の式場を備え、仏式の葬儀に最適な厳かな雰囲気。境内の緑に囲まれた静かな環境で、心安らぐお別れの時間をお過ごしいただけます。",
        "address": "神奈川県横浜市港北区菊名2-1-5",
        "prefecture_slug": "kanagawa",
        "city_slug": "yokohama",
        "latitude": 35.5020,
        "longitude": 139.6340,
        "nearest_station": "東急東横線 妙蓮寺駅",
        "station_walk_minutes": 3,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "控室": True, "駐車場": True, "本堂利用可": True},
        "price_plans": [
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000},
        ],
        "features": ["駅近", "寺院式場", "家族葬対応", "伝統的雰囲気"],
        "operator_name": "日蓮宗妙蓮寺",
        "rating_avg": 4.2,
        "review_count": 22,
    },
    {
        "name": "總持寺大本山式場",
        "slug": "sojiji-daihonzan-shikijo",
        "venue_type": "temple_hall",
        "description": "曹洞宗大本山總持寺の境内にある格式高い寺院式場。JR鶴見駅から徒歩7分。広大な境内と荘厳な本堂を有し、大規模な社葬から家族葬まで幅広く対応。横浜市内有数の歴史ある寺院で、格式のあるお別れの場を提供します。",
        "address": "神奈川県横浜市鶴見区鶴見2-1-1",
        "prefecture_slug": "kanagawa",
        "city_slug": "yokohama",
        "latitude": 35.5100,
        "longitude": 139.6750,
        "nearest_station": "JR京浜東北線 鶴見駅",
        "station_walk_minutes": 7,
        "capacity_max": 200,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"安置室": True, "控室": True, "駐車場": True, "バリアフリー": True, "本堂利用可": True},
        "price_plans": [
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000},
        ],
        "features": ["大本山", "格式高い", "大規模葬対応", "社葬対応", "家族葬対応"],
        "operator_name": "曹洞宗大本山總持寺",
        "rating_avg": 4.5,
        "review_count": 18,
    },
    {
        "name": "セレモピアン横浜青葉",
        "slug": "ceremopian-yokohama-aoba",
        "venue_type": "private_hall",
        "description": "横浜市青葉区に位置する家族葬専用の民営ホール。東急田園都市線たまプラーザ駅からバス8分。20名までの少人数葬に特化した温かみのある空間。自宅のようなリビング感覚の式場で、故人との最後の時間をゆっくり過ごせます。",
        "address": "神奈川県横浜市青葉区美しが丘西2-8-3",
        "prefecture_slug": "kanagawa",
        "city_slug": "yokohama",
        "latitude": 35.5720,
        "longitude": 139.5580,
        "nearest_station": "東急田園都市線 たまプラーザ駅（バス8分）",
        "station_walk_minutes": 15,
        "capacity_max": 20,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000},
        ],
        "features": ["家族葬専用", "少人数専用", "アットホーム", "バリアフリー"],
        "operator_name": "セレモピアン",
        "rating_avg": 4.3,
        "review_count": 25,
    },
    {
        "name": "横浜祭典セレモニーホール",
        "slug": "yokohama-saiten-ceremony-hall",
        "venue_type": "private_hall",
        "description": "横浜市中区に位置する横浜祭典株式会社運営の葬儀会館。横浜市営斎場との連携がスムーズで、久保山斎場・戸塚斎場・南部斎場・北部斎場すべてへの搬送に対応。経験豊富なスタッフが丁寧にサポートし、ご遺族の負担を軽減します。",
        "address": "神奈川県横浜市中区日ノ出町1-36",
        "prefecture_slug": "kanagawa",
        "city_slug": "yokohama",
        "latitude": 35.4440,
        "longitude": 139.6300,
        "nearest_station": "京急本線 日ノ出町駅",
        "station_walk_minutes": 3,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True, "エレベーター": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000},
        ],
        "features": ["駅近", "市営斎場連携", "家族葬対応", "24時間対応"],
        "operator_name": "横浜祭典株式会社",
        "rating_avg": 4.0,
        "review_count": 45,
    },
    {
        "name": "金沢文庫メモリアルホール",
        "slug": "kanazawabunko-memorial-hall",
        "venue_type": "private_hall",
        "description": "横浜市金沢区に位置する民営葬儀会館。京急本線金沢文庫駅から徒歩6分の好立地。南部斎場（火葬場）への搬送もスムーズ。50名収容のメインホールと20名収容の家族葬ホールを備え、ご希望に応じた規模の葬儀に対応します。",
        "address": "神奈川県横浜市金沢区釜利谷東2-10-8",
        "prefecture_slug": "kanagawa",
        "city_slug": "yokohama",
        "latitude": 35.3470,
        "longitude": 139.6150,
        "nearest_station": "京急本線 金沢文庫駅",
        "station_walk_minutes": 6,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True, "宿泊施設": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000},
        ],
        "features": ["駅近", "家族葬対応", "宿泊可能", "火葬場連携"],
        "operator_name": "金沢文庫メモリアル",
        "rating_avg": 4.1,
        "review_count": 31,
    },
    # =============================================
    # 2. 川崎市（kawasaki）: 8件
    # =============================================
    {
        "name": "かわさき北部斎苑",
        "slug": "kawasaki-hokubu-saien",
        "venue_type": "public_crematorium",
        "description": "川崎市高津区に位置する川崎市営の火葬場。JR南武線津田山駅北口から徒歩5分と公営火葬場としては抜群のアクセス。式場3室（200人用1室・100人用1室・50人用1室）、霊安室（遺体保管庫12庫）を備え、通夜から火葬まで一貫して執り行えます。",
        "address": "神奈川県川崎市高津区下作延6-18-1",
        "prefecture_slug": "kanagawa",
        "city_slug": "kawasaki",
        "latitude": 35.5960,
        "longitude": 139.6140,
        "nearest_station": "JR南武線 津田山駅",
        "station_walk_minutes": 5,
        "capacity_max": 200,
        "hall_count": 3,
        "has_crematorium": True,
        "parking_count": 50,
        "facilities": {"式場": True, "霊安室": True, "休憩室": True, "駐車場": True, "バリアフリー": True, "売店": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 79000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000},
        ],
        "features": ["火葬場併設", "駅近", "公営斎場", "川崎市民割引", "大規模葬対応"],
        "operator_name": "川崎市",
        "rating_avg": 4.1,
        "review_count": 58,
    },
    {
        "name": "かわさき南部斎苑",
        "slug": "kawasaki-nanbu-saien",
        "venue_type": "public_crematorium",
        "description": "川崎市川崎区に位置する川崎市営の大規模火葬場。火葬炉12基、式場4室（200人用1室・100人用1室・50人用2室）、霊安室（遺体保管庫12庫）を備えた川崎市最大の公営斎場。JR川崎駅東口からバスでアクセス。京浜工業地帯に近い立地です。",
        "address": "神奈川県川崎市川崎区夜光3-2-7",
        "prefecture_slug": "kanagawa",
        "city_slug": "kawasaki",
        "latitude": 35.5220,
        "longitude": 139.7430,
        "nearest_station": "JR京浜東北線 川崎駅（バス15分）",
        "station_walk_minutes": 25,
        "capacity_max": 200,
        "hall_count": 4,
        "has_crematorium": True,
        "parking_count": 60,
        "facilities": {"式場": True, "霊安室": True, "休憩室": True, "駐車場": True, "バリアフリー": True, "売店": True, "マイクロバス駐車": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 79000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000},
        ],
        "features": ["火葬場併設", "公営斎場", "川崎市民割引", "大規模葬対応", "大型駐車場"],
        "operator_name": "川崎市",
        "rating_avg": 3.9,
        "review_count": 48,
    },
    {
        "name": "セレモニーホール川崎",
        "slug": "ceremony-hall-kawasaki",
        "venue_type": "private_hall",
        "description": "JR川崎駅西口から徒歩5分の好立地にある民営葬儀会館。60名収容の大ホールと25名収容の家族葬ホールを備え、駅近ならではの利便性が魅力。川崎区・幸区エリアの方に多く利用されています。24時間体制のご相談受付で急なご依頼にも対応。",
        "address": "神奈川県川崎市幸区大宮町15-3",
        "prefecture_slug": "kanagawa",
        "city_slug": "kawasaki",
        "latitude": 35.5330,
        "longitude": 139.6920,
        "nearest_station": "JR京浜東北線 川崎駅",
        "station_walk_minutes": 5,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True, "エレベーター": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000},
        ],
        "features": ["駅近", "24時間対応", "家族葬対応", "バリアフリー"],
        "operator_name": "セレモニーホール川崎",
        "rating_avg": 4.0,
        "review_count": 37,
    },
    {
        "name": "家族葬のファミーユ溝の口",
        "slug": "familles-mizonokuchi",
        "venue_type": "private_hall",
        "description": "川崎市高津区にある家族葬専用ホール。東急田園都市線溝の口駅から徒歩8分。貸切対応で他のご家族と重なることなく、プライベートな空間でお別れの時間を過ごせます。かわさき北部斎苑への搬送もスムーズです。",
        "address": "神奈川県川崎市高津区溝口3-12-6",
        "prefecture_slug": "kanagawa",
        "city_slug": "kawasaki",
        "latitude": 35.5980,
        "longitude": 139.6100,
        "nearest_station": "東急田園都市線 溝の口駅",
        "station_walk_minutes": 8,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000},
        ],
        "features": ["家族葬専用", "貸切対応", "駅近", "火葬場連携"],
        "operator_name": "家族葬のファミーユ",
        "rating_avg": 4.3,
        "review_count": 28,
    },
    {
        "name": "サン・ライフ川崎中原斎場",
        "slug": "sunlife-kawasaki-nakahara",
        "venue_type": "private_hall",
        "description": "川崎市中原区に位置するサン・ライフ運営の葬儀会館。JR南武線武蔵新城駅から徒歩6分。70名収容の式場で家族葬から一般葬まで対応。充実した施設とベテランスタッフによる丁寧なサービスが評判です。",
        "address": "神奈川県川崎市中原区新城3-8-5",
        "prefecture_slug": "kanagawa",
        "city_slug": "kawasaki",
        "latitude": 35.5810,
        "longitude": 139.6350,
        "nearest_station": "JR南武線 武蔵新城駅",
        "station_walk_minutes": 6,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000},
        ],
        "features": ["駅近", "宿泊可能", "家族葬対応", "実績豊富"],
        "operator_name": "株式会社サン・ライフ",
        "rating_avg": 4.2,
        "review_count": 42,
    },
    {
        "name": "浄念寺セレモニーホール",
        "slug": "jonenji-ceremony-kawasaki",
        "venue_type": "temple_hall",
        "description": "川崎市多摩区にある浄土真宗本願寺派浄念寺の寺院式場。小田急線向ヶ丘遊園駅から徒歩5分。本堂を活用した伝統的な葬儀と、別棟の近代的な式場での葬儀の両方に対応。静かな住宅街にあり、落ち着いた雰囲気の中でお別れできます。",
        "address": "神奈川県川崎市多摩区登戸2420",
        "prefecture_slug": "kanagawa",
        "city_slug": "kawasaki",
        "latitude": 35.6180,
        "longitude": 139.5620,
        "nearest_station": "小田急線 向ヶ丘遊園駅",
        "station_walk_minutes": 5,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "控室": True, "駐車場": True, "本堂利用可": True},
        "price_plans": [
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000},
        ],
        "features": ["駅近", "寺院式場", "家族葬対応", "伝統的雰囲気"],
        "operator_name": "浄土真宗本願寺派浄念寺",
        "rating_avg": 4.1,
        "review_count": 19,
    },
    {
        "name": "川崎生田メモリアルホール",
        "slug": "kawasaki-ikuta-memorial",
        "venue_type": "private_hall",
        "description": "川崎市多摩区に位置する民営葬儀会館。小田急線生田駅から徒歩10分。30名収容の家族葬専用ホールで、アットホームな雰囲気のお別れが可能。生田・読売ランド前エリアの方に多く利用されています。",
        "address": "神奈川県川崎市多摩区生田7-16-2",
        "prefecture_slug": "kanagawa",
        "city_slug": "kawasaki",
        "latitude": 35.6110,
        "longitude": 139.5420,
        "nearest_station": "小田急線 生田駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000},
        ],
        "features": ["家族葬対応", "少人数専用", "アットホーム"],
        "operator_name": "川崎生田メモリアル",
        "rating_avg": 4.0,
        "review_count": 21,
    },
    {
        "name": "平間寺大師式場",
        "slug": "heigenji-daishi-shikijo",
        "venue_type": "temple_hall",
        "description": "川崎大師として知られる平間寺の境内式場。京急大師線川崎大師駅から徒歩8分。由緒ある真言宗智山派の大本山で、格式高い葬儀を執り行えます。広大な境内と歴史的建造物に囲まれた荘厳な空間が特徴です。",
        "address": "神奈川県川崎市川崎区大師町4-48",
        "prefecture_slug": "kanagawa",
        "city_slug": "kawasaki",
        "latitude": 35.5340,
        "longitude": 139.7310,
        "nearest_station": "京急大師線 川崎大師駅",
        "station_walk_minutes": 8,
        "capacity_max": 100,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "控室": True, "駐車場": True, "本堂利用可": True, "バリアフリー": True},
        "price_plans": [
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000},
        ],
        "features": ["大本山", "格式高い", "歴史的建造物", "駅近"],
        "operator_name": "真言宗智山派平間寺",
        "rating_avg": 4.4,
        "review_count": 15,
    },
    # =============================================
    # 3. 相模原市（sagamihara）: 5件
    # =============================================
    {
        "name": "相模原市営斎場",
        "slug": "sagamihara-shiei-saijo",
        "venue_type": "public_crematorium",
        "description": "相模原市南区に位置する市営の火葬場兼式場。JR古淵駅から徒歩12分のアクセス。最大100名の大式場と70名の小式場の2室を備え、火葬まで同一施設で執り行えます。更衣コーナー・授乳コーナー・キッズコーナーなど配慮の行き届いた設備が特徴です。",
        "address": "神奈川県相模原市南区古淵5-26-1",
        "prefecture_slug": "kanagawa",
        "city_slug": "sagamihara",
        "latitude": 35.5470,
        "longitude": 139.4180,
        "nearest_station": "JR横浜線 古淵駅",
        "station_walk_minutes": 12,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 60,
        "facilities": {"式場": True, "霊安室": True, "休憩室": True, "駐車場": True, "バリアフリー": True, "キッズコーナー": True, "授乳室": True, "売店": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 79000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 488000},
        ],
        "features": ["火葬場併設", "公営斎場", "市民割引", "キッズコーナーあり", "バリアフリー"],
        "operator_name": "相模原市",
        "rating_avg": 4.0,
        "review_count": 52,
    },
    {
        "name": "サン・ライフ相模原斎場",
        "slug": "sunlife-sagamihara-saijo",
        "venue_type": "private_hall",
        "description": "相模原市中央区に位置するサン・ライフ運営の葬儀会館。JR相模原駅から徒歩8分の好立地。80名収容の大ホールと30名の家族葬ホールを備え、あらゆる規模の葬儀に対応。サン・ライフの豊富な経験と安心のサポート体制が魅力です。",
        "address": "神奈川県相模原市中央区相模原3-1-10",
        "prefecture_slug": "kanagawa",
        "city_slug": "sagamihara",
        "latitude": 35.5720,
        "longitude": 139.3970,
        "nearest_station": "JR横浜線 相模原駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000},
        ],
        "features": ["駅近", "宿泊可能", "家族葬対応", "実績豊富", "大型駐車場"],
        "operator_name": "株式会社サン・ライフ",
        "rating_avg": 4.1,
        "review_count": 36,
    },
    {
        "name": "家族葬のファミーユ相模大野",
        "slug": "familles-sagami-ono",
        "venue_type": "private_hall",
        "description": "相模原市南区にある家族葬専用ホール。小田急線相模大野駅から徒歩10分。貸切対応の温かみのある空間で、少人数のお別れに最適。相模原市営斎場（火葬場）への搬送もスムーズです。全宗派対応。",
        "address": "神奈川県相模原市南区相模大野8-5-12",
        "prefecture_slug": "kanagawa",
        "city_slug": "sagamihara",
        "latitude": 35.5310,
        "longitude": 139.4350,
        "nearest_station": "小田急線 相模大野駅",
        "station_walk_minutes": 10,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000},
        ],
        "features": ["家族葬専用", "貸切対応", "全宗派対応", "火葬場連携"],
        "operator_name": "家族葬のファミーユ",
        "rating_avg": 4.2,
        "review_count": 24,
    },
    {
        "name": "橋本メモリアルホール",
        "slug": "hashimoto-memorial-hall",
        "venue_type": "private_hall",
        "description": "相模原市緑区に位置する民営葬儀会館。JR横浜線・京王相模原線橋本駅から徒歩12分。60名収容の式場で家族葬から一般葬まで対応。相模原市北部・緑区エリアの方に多く利用されています。リニア中央新幹線の新駅開業を控えた橋本エリアの斎場です。",
        "address": "神奈川県相模原市緑区橋本6-20-3",
        "prefecture_slug": "kanagawa",
        "city_slug": "sagamihara",
        "latitude": 35.5950,
        "longitude": 139.3450,
        "nearest_station": "JR横浜線・京王相模原線 橋本駅",
        "station_walk_minutes": 12,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True, "エレベーター": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000},
        ],
        "features": ["家族葬対応", "駐車場充実", "バリアフリー"],
        "operator_name": "橋本メモリアル",
        "rating_avg": 3.9,
        "review_count": 27,
    },
    {
        "name": "長徳寺式場",
        "slug": "chotokuji-shikijo-sagamihara",
        "venue_type": "temple_hall",
        "description": "相模原市中央区にある曹洞宗長徳寺の寺院式場。相模原の歴史ある寺院で、伝統的な仏式葬儀に最適。本堂と客殿を活用した式場は50名収容可能。境内の緑に囲まれた落ち着いた環境で、心安らぐお別れの場を提供します。",
        "address": "神奈川県相模原市中央区田名4855",
        "prefecture_slug": "kanagawa",
        "city_slug": "sagamihara",
        "latitude": 35.5680,
        "longitude": 139.3700,
        "nearest_station": "JR相模線 番田駅",
        "station_walk_minutes": 15,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "控室": True, "駐車場": True, "本堂利用可": True},
        "price_plans": [
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000},
        ],
        "features": ["寺院式場", "家族葬対応", "伝統的雰囲気", "駐車場充実"],
        "operator_name": "曹洞宗長徳寺",
        "rating_avg": 4.0,
        "review_count": 14,
    },
    # =============================================
    # 4. 横須賀市（yokosuka）: 4件
    # =============================================
    {
        "name": "横須賀市立中央斎場",
        "slug": "yokosuka-chuo-saijo",
        "venue_type": "public_crematorium",
        "description": "横須賀市坂本町に位置する市営の火葬場。火葬炉8基を備え、横須賀市民の方は割安で利用可能。京急本線汐入駅からバスで坂本停留所下車徒歩3分。横須賀市内で唯一の公営火葬場として、地域の方々に広く利用されています。",
        "address": "神奈川県横須賀市坂本町6-18",
        "prefecture_slug": "kanagawa",
        "city_slug": "yokosuka",
        "latitude": 35.2740,
        "longitude": 139.6620,
        "nearest_station": "京急本線 汐入駅（バス+徒歩8分）",
        "station_walk_minutes": 15,
        "capacity_max": 40,
        "hall_count": 0,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True, "売店": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 79000}],
        "features": ["火葬場", "公営斎場", "市民割引"],
        "operator_name": "横須賀市",
        "rating_avg": 3.7,
        "review_count": 25,
    },
    {
        "name": "サン・ライフ横須賀中央斎場",
        "slug": "sunlife-yokosuka-chuo",
        "venue_type": "private_hall",
        "description": "横須賀市に位置するサン・ライフ運営の葬儀会館。京急本線横須賀中央駅から徒歩10分。60名収容の大ホールと25名の家族葬ホールを備え、横須賀エリアの葬儀ニーズに幅広く対応。市立中央斎場（火葬場）への搬送も迅速です。",
        "address": "神奈川県横須賀市若松町2-5-8",
        "prefecture_slug": "kanagawa",
        "city_slug": "yokosuka",
        "latitude": 35.2790,
        "longitude": 139.6700,
        "nearest_station": "京急本線 横須賀中央駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True, "エレベーター": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000},
        ],
        "features": ["駅近", "家族葬対応", "火葬場連携", "実績豊富"],
        "operator_name": "株式会社サン・ライフ",
        "rating_avg": 4.0,
        "review_count": 33,
    },
    {
        "name": "横須賀セレモニーホール",
        "slug": "yokosuka-ceremony-hall",
        "venue_type": "private_hall",
        "description": "横須賀市久里浜に位置する民営葬儀会館。JR久里浜駅から徒歩8分。40名収容の式場で家族葬に最適。三浦半島エリアの方に多く利用されており、横須賀市立中央斎場への搬送にも対応しています。",
        "address": "神奈川県横須賀市久里浜4-12-6",
        "prefecture_slug": "kanagawa",
        "city_slug": "yokosuka",
        "latitude": 35.2300,
        "longitude": 139.7090,
        "nearest_station": "JR横須賀線 久里浜駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000},
        ],
        "features": ["駅近", "家族葬対応", "三浦半島エリア"],
        "operator_name": "横須賀セレモニー",
        "rating_avg": 4.1,
        "review_count": 22,
    },
    {
        "name": "浄楽寺式場",
        "slug": "jorakuji-shikijo-yokosuka",
        "venue_type": "temple_hall",
        "description": "横須賀市芦名に位置する浄土宗浄楽寺の寺院式場。鎌倉時代の運慶作の仏像（国重要文化財）を有する歴史ある名刹。50名収容の式場と本堂での葬儀が可能。三浦半島の自然に囲まれた静かな環境でお別れできます。",
        "address": "神奈川県横須賀市芦名2-30-5",
        "prefecture_slug": "kanagawa",
        "city_slug": "yokosuka",
        "latitude": 35.2340,
        "longitude": 139.6180,
        "nearest_station": "京急本線 逗子・葉山駅（バス15分）",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "控室": True, "駐車場": True, "本堂利用可": True},
        "price_plans": [
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000},
        ],
        "features": ["寺院式場", "歴史的名刹", "国重要文化財", "自然豊か"],
        "operator_name": "浄土宗浄楽寺",
        "rating_avg": 4.3,
        "review_count": 12,
    },
    # =============================================
    # 5. 藤沢市（fujisawa）: 4件
    # =============================================
    {
        "name": "藤沢市斎場",
        "slug": "fujisawa-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "藤沢市大庭に位置する市営の火葬場兼式場。火葬炉を備え、式場2室で通夜・告別式から火葬まで一貫して執り行えます。JR藤沢駅北口からバスで「緑ヶ丘」下車徒歩1分。藤沢市民の方は割安料金で利用可能です。",
        "address": "神奈川県藤沢市大庭3761",
        "prefecture_slug": "kanagawa",
        "city_slug": "fujisawa",
        "latitude": 35.3540,
        "longitude": 139.4580,
        "nearest_station": "JR東海道線 藤沢駅（バス15分）",
        "station_walk_minutes": 20,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 50,
        "facilities": {"式場": True, "霊安室": True, "休憩室": True, "駐車場": True, "バリアフリー": True, "売店": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 79000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 488000},
        ],
        "features": ["火葬場併設", "公営斎場", "式場あり", "市民割引", "バリアフリー"],
        "operator_name": "藤沢市",
        "rating_avg": 3.9,
        "review_count": 38,
    },
    {
        "name": "サン・ライフ藤沢斎場",
        "slug": "sunlife-fujisawa-saijo",
        "venue_type": "private_hall",
        "description": "藤沢市に位置するサン・ライフ運営の葬儀会館。JR藤沢駅から徒歩7分の好立地。60名収容の大ホールと20名の家族葬ホールを備え、湘南エリアの葬儀ニーズに幅広く対応。藤沢市斎場（火葬場）への搬送もスムーズです。",
        "address": "神奈川県藤沢市藤沢530-5",
        "prefecture_slug": "kanagawa",
        "city_slug": "fujisawa",
        "latitude": 35.3380,
        "longitude": 139.4870,
        "nearest_station": "JR東海道線 藤沢駅",
        "station_walk_minutes": 7,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True, "エレベーター": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000},
        ],
        "features": ["駅近", "湘南エリア", "家族葬対応", "実績豊富"],
        "operator_name": "株式会社サン・ライフ",
        "rating_avg": 4.1,
        "review_count": 35,
    },
    {
        "name": "家族葬のファミーユ辻堂",
        "slug": "familles-tsujido",
        "venue_type": "private_hall",
        "description": "藤沢市辻堂にある家族葬専用ホール。JR東海道線辻堂駅から徒歩12分。少人数のお別れに特化した貸切対応の温かみのある空間。湘南の明るい雰囲気を感じられる内装が特徴です。",
        "address": "神奈川県藤沢市辻堂新町1-6-8",
        "prefecture_slug": "kanagawa",
        "city_slug": "fujisawa",
        "latitude": 35.3360,
        "longitude": 139.4530,
        "nearest_station": "JR東海道線 辻堂駅",
        "station_walk_minutes": 12,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000},
        ],
        "features": ["家族葬専用", "貸切対応", "湘南エリア"],
        "operator_name": "家族葬のファミーユ",
        "rating_avg": 4.2,
        "review_count": 20,
    },
    {
        "name": "遊行寺式場",
        "slug": "yugyoji-shikijo-fujisawa",
        "venue_type": "temple_hall",
        "description": "時宗総本山遊行寺（清浄光寺）の境内にある格式高い寺院式場。JR藤沢駅から徒歩15分。700年以上の歴史を持つ名刹で、本堂は国登録有形文化財。広大な境内の緑に囲まれた荘厳な空間で、心安らぐお別れの時間を過ごせます。",
        "address": "神奈川県藤沢市西富1-8-1",
        "prefecture_slug": "kanagawa",
        "city_slug": "fujisawa",
        "latitude": 35.3430,
        "longitude": 139.4760,
        "nearest_station": "JR東海道線 藤沢駅",
        "station_walk_minutes": 15,
        "capacity_max": 80,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "控室": True, "駐車場": True, "本堂利用可": True, "バリアフリー": True},
        "price_plans": [
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 578000},
        ],
        "features": ["総本山", "格式高い", "国登録有形文化財", "歴史的名刹", "大規模葬対応"],
        "operator_name": "時宗総本山遊行寺",
        "rating_avg": 4.5,
        "review_count": 16,
    },
    # =============================================
    # 6. 平塚市（hiratsuka）: 3件
    # =============================================
    {
        "name": "平塚市聖苑",
        "slug": "hiratsuka-shi-seien",
        "venue_type": "public_crematorium",
        "description": "平塚市田村に位置する市営の火葬場。平塚市民の方は割安で利用可能。JR平塚駅北口からバスで「農協神田支所前」下車徒歩1分。田園地帯の静かな環境にあり、落ち着いた雰囲気の中で最後のお別れができます。",
        "address": "神奈川県平塚市田村9-12-8",
        "prefecture_slug": "kanagawa",
        "city_slug": "hiratsuka",
        "latitude": 35.3670,
        "longitude": 139.3480,
        "nearest_station": "JR東海道線 平塚駅（バス30分）",
        "station_walk_minutes": 35,
        "capacity_max": 30,
        "hall_count": 0,
        "has_crematorium": True,
        "parking_count": 40,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 79000}],
        "features": ["火葬場", "公営斎場", "市民割引"],
        "operator_name": "平塚市",
        "rating_avg": 3.6,
        "review_count": 22,
    },
    {
        "name": "サン・ライフ平塚斎場",
        "slug": "sunlife-hiratsuka-saijo",
        "venue_type": "private_hall",
        "description": "平塚市に位置するサン・ライフ運営の葬儀会館。JR平塚駅北口から徒歩10分。50名収容の式場で家族葬から一般葬まで対応。平塚市聖苑（火葬場）への搬送もスムーズで、地域密着型のきめ細やかなサービスが評判です。",
        "address": "神奈川県平塚市宝町4-15",
        "prefecture_slug": "kanagawa",
        "city_slug": "hiratsuka",
        "latitude": 35.3310,
        "longitude": 139.3510,
        "nearest_station": "JR東海道線 平塚駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000},
        ],
        "features": ["駅近", "家族葬対応", "地域密着", "火葬場連携"],
        "operator_name": "株式会社サン・ライフ",
        "rating_avg": 4.0,
        "review_count": 30,
    },
    {
        "name": "平塚中央セレモニーホール",
        "slug": "hiratsuka-chuo-ceremony-hall",
        "venue_type": "private_hall",
        "description": "平塚市中央に位置する民営葬儀会館。JR平塚駅から徒歩15分。30名収容の家族葬専用ホールで、少人数のお別れに特化。アットホームな雰囲気で、故人との最後の時間をゆっくり過ごせます。",
        "address": "神奈川県平塚市中里23-8",
        "prefecture_slug": "kanagawa",
        "city_slug": "hiratsuka",
        "latitude": 35.3380,
        "longitude": 139.3610,
        "nearest_station": "JR東海道線 平塚駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000},
        ],
        "features": ["家族葬対応", "少人数専用", "アットホーム"],
        "operator_name": "平塚中央セレモニー",
        "rating_avg": 4.1,
        "review_count": 18,
    },
    # =============================================
    # 7. 茅ヶ崎市（chigasaki）: 2件
    # =============================================
    {
        "name": "茅ヶ崎市斎場",
        "slug": "chigasaki-shi-saijo",
        "venue_type": "public_facility",
        "description": "茅ヶ崎市に位置する市営の斎場施設。式場を備え、通夜・告別式が可能。茅ヶ崎市民の方は割安料金で利用可能。火葬は平塚市聖苑または藤沢市斎場を利用。湘南エリアの落ち着いた環境にあります。",
        "address": "神奈川県茅ヶ崎市南湖7-12-26",
        "prefecture_slug": "kanagawa",
        "city_slug": "chigasaki",
        "latitude": 35.3210,
        "longitude": 139.3990,
        "nearest_station": "JR東海道線 茅ヶ崎駅（バス10分）",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True},
        "price_plans": [
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 478000},
        ],
        "features": ["公営斎場", "市民割引", "湘南エリア", "バリアフリー"],
        "operator_name": "茅ヶ崎市",
        "rating_avg": 3.8,
        "review_count": 20,
    },
    {
        "name": "セレモニーホール茅ヶ崎",
        "slug": "ceremony-hall-chigasaki",
        "venue_type": "private_hall",
        "description": "茅ヶ崎市に位置する民営葬儀会館。JR茅ヶ崎駅から徒歩8分の好立地。40名収容の式場で家族葬に最適。湘南の温かい雰囲気を感じられる内装が特徴。24時間対応の安置室完備。",
        "address": "神奈川県茅ヶ崎市新栄町8-5",
        "prefecture_slug": "kanagawa",
        "city_slug": "chigasaki",
        "latitude": 35.3300,
        "longitude": 139.4040,
        "nearest_station": "JR東海道線 茅ヶ崎駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000},
        ],
        "features": ["駅近", "家族葬対応", "湘南エリア", "24時間対応"],
        "operator_name": "セレモニーホール茅ヶ崎",
        "rating_avg": 4.0,
        "review_count": 24,
    },
    # =============================================
    # 8. 大和市（yamato）: 2件
    # =============================================
    {
        "name": "大和斎場",
        "slug": "yamato-saijo",
        "venue_type": "public_facility",
        "description": "大和市に位置する公営の斎場施設。大和市・座間市・綾瀬市・海老名市の4市共同運営で、各市民の方は割安で利用可能。火葬炉と式場を備え、通夜から火葬まで一貫して対応。小田急線・相鉄線大和駅からバスでアクセスできます。",
        "address": "神奈川県大和市深見台3-4-1",
        "prefecture_slug": "kanagawa",
        "city_slug": "yamato",
        "latitude": 35.4640,
        "longitude": 139.4620,
        "nearest_station": "小田急江ノ島線 大和駅（バス10分）",
        "station_walk_minutes": 15,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 40,
        "facilities": {"式場": True, "霊安室": True, "休憩室": True, "駐車場": True, "バリアフリー": True, "売店": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 79000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 488000},
        ],
        "features": ["火葬場併設", "公営斎場", "4市共同運営", "式場あり", "バリアフリー"],
        "operator_name": "大和市（4市共同運営）",
        "rating_avg": 3.9,
        "review_count": 35,
    },
    {
        "name": "家族葬のファミーユ大和",
        "slug": "familles-yamato",
        "venue_type": "private_hall",
        "description": "大和市に位置する家族葬専用ホール。小田急江ノ島線・相鉄線大和駅から徒歩10分。貸切対応の温かみのある空間で、少人数のお別れに最適。大和斎場（火葬場）への搬送もスムーズです。",
        "address": "神奈川県大和市中央2-5-15",
        "prefecture_slug": "kanagawa",
        "city_slug": "yamato",
        "latitude": 35.4610,
        "longitude": 139.4580,
        "nearest_station": "小田急江ノ島線 大和駅",
        "station_walk_minutes": 10,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000},
        ],
        "features": ["家族葬専用", "貸切対応", "駅近", "火葬場連携"],
        "operator_name": "家族葬のファミーユ",
        "rating_avg": 4.2,
        "review_count": 19,
    },
    # =============================================
    # 9. 厚木市（atsugi）: 2件
    # =============================================
    {
        "name": "厚木市斎場",
        "slug": "atsugi-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "厚木市に位置する市営の火葬場。厚木市・愛川町・清川村の住民の方は割安で利用可能。式場も備え、通夜・告別式から火葬まで対応。小田急線本厚木駅からバスでアクセス。丹沢山系を望む自然豊かな環境にあります。",
        "address": "神奈川県厚木市下古沢548",
        "prefecture_slug": "kanagawa",
        "city_slug": "atsugi",
        "latitude": 35.4220,
        "longitude": 139.3170,
        "nearest_station": "小田急線 本厚木駅（バス20分）",
        "station_walk_minutes": 30,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 40,
        "facilities": {"式場": True, "霊安室": True, "休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 79000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000},
        ],
        "features": ["火葬場併設", "公営斎場", "市民割引", "自然豊か"],
        "operator_name": "厚木市",
        "rating_avg": 3.7,
        "review_count": 26,
    },
    {
        "name": "セレモニーホール厚木",
        "slug": "ceremony-hall-atsugi",
        "venue_type": "private_hall",
        "description": "厚木市に位置する民営葬儀会館。小田急線本厚木駅から徒歩8分の好立地。50名収容の式場で家族葬から一般葬まで対応。厚木市斎場（火葬場）への搬送もスムーズで、県央エリアの方に多く利用されています。",
        "address": "神奈川県厚木市中町2-6-10",
        "prefecture_slug": "kanagawa",
        "city_slug": "atsugi",
        "latitude": 35.4420,
        "longitude": 139.3640,
        "nearest_station": "小田急線 本厚木駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True, "エレベーター": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000},
        ],
        "features": ["駅近", "家族葬対応", "県央エリア", "火葬場連携"],
        "operator_name": "セレモニーホール厚木",
        "rating_avg": 4.0,
        "review_count": 23,
    },
    # =============================================
    # 10. 鎌倉市（kamakura）: 2件
    # =============================================
    {
        "name": "鎌倉メモリアルホール",
        "slug": "kamakura-memorial-hall",
        "venue_type": "private_hall",
        "description": "鎌倉市に位置する民営葬儀会館。JR鎌倉駅から徒歩12分。古都鎌倉の落ち着いた雰囲気の中にある式場で、40名収容。家族葬から一般葬まで対応。藤沢市斎場や横浜市南部斎場への搬送にも対応しています。",
        "address": "神奈川県鎌倉市御成町11-8",
        "prefecture_slug": "kanagawa",
        "city_slug": "kamakura",
        "latitude": 35.3190,
        "longitude": 139.5480,
        "nearest_station": "JR横須賀線 鎌倉駅",
        "station_walk_minutes": 12,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000},
        ],
        "features": ["古都鎌倉", "家族葬対応", "落ち着いた雰囲気"],
        "operator_name": "鎌倉メモリアル",
        "rating_avg": 4.2,
        "review_count": 20,
    },
    {
        "name": "建長寺式場",
        "slug": "kenchoji-shikijo-kamakura",
        "venue_type": "temple_hall",
        "description": "鎌倉五山第一位の臨済宗建長寺派大本山建長寺の式場。国宝の梵鐘をはじめ多くの文化財を有する名刹。広大な境内と格式高い本堂での葬儀が可能。JR北鎌倉駅から徒歩15分。鎌倉を代表する寺院で、荘厳な雰囲気の中お別れできます。",
        "address": "神奈川県鎌倉市山ノ内8",
        "prefecture_slug": "kanagawa",
        "city_slug": "kamakura",
        "latitude": 35.3330,
        "longitude": 139.5500,
        "nearest_station": "JR横須賀線 北鎌倉駅",
        "station_walk_minutes": 15,
        "capacity_max": 100,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "控室": True, "駐車場": True, "本堂利用可": True},
        "price_plans": [
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 428000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 628000},
        ],
        "features": ["大本山", "国宝", "鎌倉五山", "格式高い", "歴史的名刹"],
        "operator_name": "臨済宗建長寺派大本山建長寺",
        "rating_avg": 4.6,
        "review_count": 10,
    },
    # =============================================
    # 11. 小田原市（odawara）: 2件
    # =============================================
    {
        "name": "小田原市斎場",
        "slug": "odawara-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "小田原市久野に位置する市営の火葬場。小田原市民の方は割安で利用可能。小田原駅東口からバスで「ざる菊園前（小田原斎場）」下車徒歩3分。箱根の山々を望む自然豊かな環境にあり、四季折々の美しい景観の中で最後のお別れができます。",
        "address": "神奈川県小田原市久野3664-8",
        "prefecture_slug": "kanagawa",
        "city_slug": "odawara",
        "latitude": 35.2710,
        "longitude": 139.1410,
        "nearest_station": "JR東海道線 小田原駅（バス15分）",
        "station_walk_minutes": 25,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"式場": True, "霊安室": True, "休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 79000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000},
        ],
        "features": ["火葬場併設", "公営斎場", "市民割引", "自然豊か", "箱根エリア"],
        "operator_name": "小田原市",
        "rating_avg": 3.8,
        "review_count": 24,
    },
    {
        "name": "セレモニーホール小田原",
        "slug": "ceremony-hall-odawara",
        "venue_type": "private_hall",
        "description": "小田原市に位置する民営葬儀会館。JR小田原駅から徒歩10分。50名収容の式場で家族葬から一般葬まで対応。小田原市斎場（火葬場）への搬送もスムーズ。箱根・湯河原・真鶴エリアからのアクセスにも便利な立地です。",
        "address": "神奈川県小田原市栄町2-8-15",
        "prefecture_slug": "kanagawa",
        "city_slug": "odawara",
        "latitude": 35.2530,
        "longitude": 139.1570,
        "nearest_station": "JR東海道線 小田原駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True, "エレベーター": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000},
        ],
        "features": ["駅近", "家族葬対応", "箱根エリア", "火葬場連携"],
        "operator_name": "セレモニーホール小田原",
        "rating_avg": 4.0,
        "review_count": 22,
    },
    # =============================================
    # 12. 海老名市（ebina）: 1件
    # =============================================
    {
        "name": "セレモニーホール海老名",
        "slug": "ceremony-hall-ebina",
        "venue_type": "private_hall",
        "description": "海老名市に位置する民営葬儀会館。小田急線・相鉄線海老名駅から徒歩10分。40名収容の式場で家族葬に最適。大和斎場（火葬場）への搬送もスムーズ。ショッピングモールが充実する海老名駅周辺の利便性の高い立地です。",
        "address": "神奈川県海老名市中央2-9-12",
        "prefecture_slug": "kanagawa",
        "city_slug": "ebina",
        "latitude": 35.4480,
        "longitude": 139.3910,
        "nearest_station": "小田急線・相鉄線 海老名駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "控室": True, "駐車場": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000},
        ],
        "features": ["駅近", "家族葬対応", "県央エリア", "火葬場連携"],
        "operator_name": "セレモニーホール海老名",
        "rating_avg": 4.1,
        "review_count": 18,
    },
]


def post_batch(batch, batch_num):
    """バッチをPOSTする"""
    data = json.dumps(batch).encode("utf-8")
    req = urllib.request.Request(SUPABASE_URL, data=data, headers=HEADERS, method="POST")
    try:
        resp = urllib.request.urlopen(req)
        print(f"  バッチ {batch_num}: {len(batch)}件 投入成功 (HTTP {resp.status})")
        return True
    except urllib.error.HTTPError as e:
        error_body = e.read().decode("utf-8")
        print(f"  バッチ {batch_num}: エラー (HTTP {e.code})")
        print(f"  エラー詳細: {error_body}")
        return False


def main():
    print(f"=== 神奈川県 斎場データ投入開始 ===")
    print(f"総件数: {len(venues)}件")

    # スラッグの重複チェック
    slugs = [v["slug"] for v in venues]
    if len(slugs) != len(set(slugs)):
        duplicates = [s for s in slugs if slugs.count(s) > 1]
        print(f"エラー: スラッグに重複があります: {set(duplicates)}")
        return

    # 市区町村ごとの件数を表示
    city_counts = {}
    for v in venues:
        city = v["city_slug"]
        city_counts[city] = city_counts.get(city, 0) + 1
    print("\n市区町村別件数:")
    for city, count in sorted(city_counts.items(), key=lambda x: -x[1]):
        print(f"  {city}: {count}件")

    # バッチサイズ10件ずつ投入
    batch_size = 10
    total_batches = (len(venues) + batch_size - 1) // batch_size
    success_count = 0

    print(f"\n{total_batches}バッチに分けて投入します...")
    for i in range(0, len(venues), batch_size):
        batch = venues[i : i + batch_size]
        batch_num = i // batch_size + 1
        print(f"\nバッチ {batch_num}/{total_batches} ({len(batch)}件):")
        for v in batch:
            print(f"  - {v['name']} ({v['slug']})")

        if post_batch(batch, batch_num):
            success_count += len(batch)

        # API負荷軽減のため少し待つ
        if i + batch_size < len(venues):
            time.sleep(0.5)

    print(f"\n=== 投入完了 ===")
    print(f"成功: {success_count}/{len(venues)}件")

    # 検証: 投入後のカウント
    print("\n=== 検証: 神奈川県の斎場データ件数確認 ===")
    count_url = f"{SUPABASE_URL}?prefecture_slug=eq.kanagawa&select=slug"
    count_req = urllib.request.Request(count_url, headers={
        "apikey": API_KEY,
        "Authorization": f"Bearer {API_KEY}",
    })
    try:
        count_resp = urllib.request.urlopen(count_req)
        count_data = json.loads(count_resp.read())
        print(f"データベース上の神奈川県斎場数: {len(count_data)}件")
    except Exception as e:
        print(f"検証エラー: {e}")


if __name__ == "__main__":
    main()
