# -*- coding: utf-8 -*-
import json, subprocess, time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

venues = [
    # === 宇治市 残り3件 ===
    {"name":"五条会館 宇治","slug":"kyoto-gojo-uji","venue_type":"private_hall","description":"宇治市槇島エリアの五条会館。国道24号線沿いでお車でのアクセスが便利です。","address":"京都府宇治市槇島町十八47","prefecture_slug":"kyoto","city_slug":"uji","latitude":34.892,"longitude":135.780,"nearest_station":"近鉄京都線 向島駅","station_walk_minutes":10,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":375000},{"type":"ippanso","label":"一般葬プラン","priceFrom":680000}],"features":["家族葬対応","大駐車場"],"operator_name":"五条会館","rating_avg":4.0,"review_count":25},
    {"name":"JA葬祭宇治","slug":"kyoto-ja-uji","venue_type":"private_hall","description":"JA京都やましろが運営する宇治市の葬祭ホール。地域に根差した適正価格のサービスが特徴です。","address":"京都府宇治市宇治弐番65-9","prefecture_slug":"kyoto","city_slug":"uji","latitude":34.888,"longitude":135.805,"nearest_station":"JR奈良線 宇治駅","station_walk_minutes":10,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":298000},{"type":"ippanso","label":"一般葬プラン","priceFrom":550000}],"features":["家族葬対応","低価格"],"operator_name":"JA京都やましろ","rating_avg":3.9,"review_count":20},
    {"name":"メモリアルホール宇治","slug":"kyoto-memorial-uji","venue_type":"private_hall","description":"宇治市伊勢田エリアのメモリアルホール。近鉄伊勢田駅近くの便利な立地です。","address":"京都府宇治市伊勢田町遊田68","prefecture_slug":"kyoto","city_slug":"uji","latitude":34.878,"longitude":135.786,"nearest_station":"近鉄京都線 伊勢田駅","station_walk_minutes":5,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":12,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":348000}],"features":["家族葬対応","駅近"],"operator_name":"メモリアルホール","rating_avg":4.1,"review_count":18},
    # === 亀岡市 5件 ===
    {"name":"公益社 亀岡ホール","slug":"kyoto-koekisha-kameoka","venue_type":"private_hall","description":"亀岡市の中心部に位置する公益社のホール。JR亀岡駅から徒歩圏内で、丹波地域の中核斎場です。","address":"京都府亀岡市追分町谷筋25-30","prefecture_slug":"kyoto","city_slug":"kameoka","latitude":35.011,"longitude":135.577,"nearest_station":"JR山陰本線 亀岡駅","station_walk_minutes":10,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":100000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":370000},{"type":"ippanso","label":"一般葬プラン","priceFrom":680000}],"features":["家族葬対応","駅近"],"operator_name":"公益社","rating_avg":4.1,"review_count":30},
    {"name":"ベルコ亀岡シティホール","slug":"kyoto-bellco-kameoka","venue_type":"private_hall","description":"亀岡市篠町エリアのベルコ葬儀会館。京都縦貫道亀岡ICに近い便利な立地です。","address":"京都府亀岡市篠町馬堀六ノ坪1-5","prefecture_slug":"kyoto","city_slug":"kameoka","latitude":35.009,"longitude":135.600,"nearest_station":"JR山陰本線 馬堀駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":350000}],"features":["家族葬対応","駅近","インター近く"],"operator_name":"ベルコ","rating_avg":4.2,"review_count":22},
    {"name":"家族葬のファミーユ亀岡","slug":"kyoto-famillu-kameoka","venue_type":"private_hall","description":"亀岡市の家族葬専門ホール。少人数でのお見送りに特化した温かい空間です。","address":"京都府亀岡市三宅町18-3","prefecture_slug":"kyoto","city_slug":"kameoka","latitude":35.015,"longitude":135.585,"nearest_station":"JR山陰本線 亀岡駅","station_walk_minutes":12,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":85000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":290000}],"features":["家族葬対応","少人数対応","低価格"],"operator_name":"家族葬のファミーユ","rating_avg":4.3,"review_count":14},
    {"name":"亀岡市斎場","slug":"kyoto-kameoka-saijo","venue_type":"public_crematorium","description":"亀岡市が運営する公営火葬場・斎場。市民料金で利用でき、亀岡市民に広く利用されています。","address":"京都府亀岡市余部町法華寺8","prefecture_slug":"kyoto","city_slug":"kameoka","latitude":35.020,"longitude":135.570,"nearest_station":"JR山陰本線 亀岡駅","station_walk_minutes":15,"capacity_max":60,"hall_count":1,"has_crematorium":True,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":55000}],"features":["公営施設","火葬場併設"],"operator_name":"亀岡市","rating_avg":3.6,"review_count":25},
    {"name":"洛王セレモニー亀岡","slug":"kyoto-rakuo-kameoka","venue_type":"private_hall","description":"亀岡市千代川エリアの洛王セレモニー。国道9号線沿いでお車でのアクセスが便利な式場です。","address":"京都府亀岡市千代川町拝田21","prefecture_slug":"kyoto","city_slug":"kameoka","latitude":35.024,"longitude":135.558,"nearest_station":"JR山陰本線 千代川駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":18,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":358000},{"type":"ippanso","label":"一般葬プラン","priceFrom":650000}],"features":["家族葬対応","駅近"],"operator_name":"洛王セレモニー","rating_avg":4.0,"review_count":18},
    # === 舞鶴市 5件 ===
    {"name":"公益社 西舞鶴ホール","slug":"kyoto-koekisha-nishimaizuru","venue_type":"private_hall","description":"西舞鶴の中心部に位置する公益社のホール。舞鶴市西部エリアの中核斎場です。","address":"京都府舞鶴市引土新111","prefecture_slug":"kyoto","city_slug":"maizuru","latitude":35.479,"longitude":135.380,"nearest_station":"JR舞鶴線 西舞鶴駅","station_walk_minutes":8,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":98000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":365000},{"type":"ippanso","label":"一般葬プラン","priceFrom":660000}],"features":["家族葬対応","駅近"],"operator_name":"公益社","rating_avg":4.1,"review_count":28},
    {"name":"ベルコ舞鶴シティホール","slug":"kyoto-bellco-maizuru","venue_type":"private_hall","description":"東舞鶴エリアのベルコ葬儀会館。海上自衛隊舞鶴基地にも近い立地です。","address":"京都府舞鶴市浜339-1","prefecture_slug":"kyoto","city_slug":"maizuru","latitude":35.473,"longitude":135.396,"nearest_station":"JR舞鶴線 東舞鶴駅","station_walk_minutes":10,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":348000}],"features":["家族葬対応","駅近"],"operator_name":"ベルコ","rating_avg":4.0,"review_count":20},
    {"name":"舞鶴市斎場","slug":"kyoto-maizuru-saijo","venue_type":"public_crematorium","description":"舞鶴市が運営する公営火葬場・斎場。舞鶴湾を見渡す高台に位置し、市民料金で利用できます。","address":"京都府舞鶴市字長浜小字谷2","prefecture_slug":"kyoto","city_slug":"maizuru","latitude":35.461,"longitude":135.385,"nearest_station":"JR舞鶴線 東舞鶴駅","station_walk_minutes":20,"capacity_max":60,"hall_count":1,"has_crematorium":True,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":55000}],"features":["公営施設","火葬場併設"],"operator_name":"舞鶴市","rating_avg":3.6,"review_count":22},
    {"name":"家族葬のファミーユ舞鶴","slug":"kyoto-famillu-maizuru","venue_type":"private_hall","description":"舞鶴市の家族葬専門ホール。少人数でのお見送りに最適な温かい空間です。","address":"京都府舞鶴市円満寺134-2","prefecture_slug":"kyoto","city_slug":"maizuru","latitude":35.482,"longitude":135.389,"nearest_station":"JR舞鶴線 西舞鶴駅","station_walk_minutes":12,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":85000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":290000}],"features":["家族葬対応","少人数対応","低価格"],"operator_name":"家族葬のファミーユ","rating_avg":4.3,"review_count":12},
    {"name":"洛王セレモニー舞鶴","slug":"kyoto-rakuo-maizuru","venue_type":"private_hall","description":"舞鶴市倉谷エリアの洛王セレモニー。国道27号線沿いの便利な立地です。","address":"京都府舞鶴市字倉谷小字奥山1827-3","prefecture_slug":"kyoto","city_slug":"maizuru","latitude":35.476,"longitude":135.374,"nearest_station":"JR舞鶴線 西舞鶴駅","station_walk_minutes":15,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":18,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":355000},{"type":"ippanso","label":"一般葬プラン","priceFrom":640000}],"features":["家族葬対応"],"operator_name":"洛王セレモニー","rating_avg":4.0,"review_count":16},
]

for i in range(0, len(venues), 10):
    batch = venues[i:i+10]
    code = insert_batch(batch)
    print(f"バッチ {i//10+1}: {code} ({len(batch)}件)")
    time.sleep(1)

print(f"\n完了: 合計 {len(venues)} 件")
