#!/usr/bin/env python3
"""
宮城県の斎場データ Part2: 仙台市泉区16件 + 仙台市追加施設20件 = 36件
"""

import urllib.request
import json
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

HEADERS = {
    "apikey": API_KEY,
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal",
    "User-Agent": "Mozilla/5.0",
}

venues = [
    # =============================================
    # 仙台市泉区（16件）
    # =============================================
    {
        "name": "清月記 泉ホール",
        "slug": "miyagi-seigetuki-izumi",
        "venue_type": "private_hall",
        "description": "仙台市泉区泉中央に位置する清月記の拠点斎場。地下鉄南北線泉中央駅から徒歩圏内で、仙台北部エリアの中心施設です。3つの式場を備え、家族葬から大規模な一般葬まで対応。24時間対応の相談窓口があります。",
        "address": "宮城県仙台市泉区泉中央1-15-8",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.3200,
        "longitude": 140.8810,
        "nearest_station": "仙台市営地下鉄南北線 泉中央駅",
        "station_walk_minutes": 7,
        "capacity_max": 150,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True, "24時間対応": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000},
        ],
        "features": ["駅近", "24時間対応", "家族葬対応", "泉中央エリア", "大規模対応"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.3,
        "review_count": 88,
    },
    {
        "name": "葬祭会館ティア泉",
        "slug": "miyagi-tier-izumi",
        "venue_type": "private_hall",
        "description": "仙台市泉区将監に位置するティアの斎場。泉パークタウン入口に近く、車でのアクセスが良好。明朗会計と丁寧なスタッフ対応で安心して葬儀を任せられます。",
        "address": "宮城県仙台市泉区将監4-10-15",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.3280,
        "longitude": 140.8750,
        "nearest_station": "仙台市営地下鉄南北線 泉中央駅（バス10分）",
        "station_walk_minutes": 20,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000},
        ],
        "features": ["明朗会計", "車アクセス良好", "家族葬対応", "全国チェーン"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.0,
        "review_count": 42,
    },
    {
        "name": "セレモニーホール紫雲閣 泉",
        "slug": "miyagi-shiunkan-izumi",
        "venue_type": "private_hall",
        "description": "仙台市泉区南光台に位置する紫雲閣の斎場。旭ケ丘エリアに隣接し、泉区と青葉区の境界付近で両エリアからアクセスしやすい立地です。和モダンの落ち着いた空間で心のこもった葬儀を執り行えます。",
        "address": "宮城県仙台市泉区南光台3-8-20",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.3050,
        "longitude": 140.8880,
        "nearest_station": "仙台市営地下鉄南北線 旭ケ丘駅",
        "station_walk_minutes": 12,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000},
        ],
        "features": ["和モダン", "アクセス良好", "家族葬対応"],
        "operator_name": "紫雲閣グループ",
        "rating_avg": 4.0,
        "review_count": 39,
    },
    {
        "name": "花についた 泉",
        "slug": "miyagi-hana-ni-tsuta-izumi",
        "venue_type": "private_hall",
        "description": "仙台市泉区高森エリアに位置する「花についた」の斎場。泉パークタウン内の閑静な住宅街にあり、自然に囲まれた穏やかな環境です。花祭壇の美しさが際立つ温かい式場で、家族葬を中心に丁寧なサービスを提供しています。",
        "address": "宮城県仙台市泉区高森2-1-10",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.3350,
        "longitude": 140.8600,
        "nearest_station": "仙台市営地下鉄南北線 泉中央駅（バス15分）",
        "station_walk_minutes": 30,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000},
        ],
        "features": ["花祭壇", "閑静な環境", "家族葬専門", "自然豊か"],
        "operator_name": "花についた",
        "rating_avg": 4.2,
        "review_count": 30,
    },
    {
        "name": "やすらぎホール泉",
        "slug": "miyagi-yasuragi-izumi",
        "venue_type": "private_hall",
        "description": "仙台市泉区八乙女エリアに位置する家族葬対応の斎場。地下鉄南北線八乙女駅から近く、コンパクトながらも温かみのある空間。1日1組限定の貸切対応で、プライベートなお別れの時間を大切にしています。",
        "address": "宮城県仙台市泉区八乙女中央3-5-12",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.3110,
        "longitude": 140.8790,
        "nearest_station": "仙台市営地下鉄南北線 八乙女駅",
        "station_walk_minutes": 5,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000},
        ],
        "features": ["家族葬専門", "1日1組貸切", "駅近", "低価格"],
        "operator_name": "やすらぎホール",
        "rating_avg": 4.1,
        "review_count": 26,
    },
    {
        "name": "清月記 向陽台ホール",
        "slug": "miyagi-seigetuki-koyodai",
        "venue_type": "private_hall",
        "description": "仙台市泉区向陽台に位置する清月記の郊外型斎場。泉ヶ岳の麓に広がる住宅街にあり、自然豊かな環境です。広い駐車場を備え、車でのアクセスに便利。家族葬からの一般葬まで対応しています。",
        "address": "宮城県仙台市泉区向陽台4-20-8",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.3400,
        "longitude": 140.8500,
        "nearest_station": "仙台市営地下鉄南北線 泉中央駅（バス20分）",
        "station_walk_minutes": 35,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 60,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 578000},
        ],
        "features": ["大型駐車場", "郊外型", "自然豊か", "家族葬対応"],
        "operator_name": "株式会社清月記",
        "rating_avg": 3.9,
        "review_count": 24,
    },
    {
        "name": "メモリアルホール泉中央",
        "slug": "miyagi-memorial-izumi-chuo",
        "venue_type": "private_hall",
        "description": "仙台市泉区泉中央エリアに位置する斎場。泉中央副都心の商業エリアに近く、利便性の高い立地です。モダンな内装と充実した設備で、格式ある葬儀を執り行えます。",
        "address": "宮城県仙台市泉区泉中央3-20-1",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.3180,
        "longitude": 140.8830,
        "nearest_station": "仙台市営地下鉄南北線 泉中央駅",
        "station_walk_minutes": 8,
        "capacity_max": 120,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 628000},
        ],
        "features": ["駅近", "モダン設備", "家族葬対応", "好立地"],
        "operator_name": "メモリアルホール",
        "rating_avg": 4.1,
        "review_count": 45,
    },
    {
        "name": "仙台典礼 泉会館",
        "slug": "miyagi-tenrei-izumi",
        "venue_type": "private_hall",
        "description": "仙台市泉区松森に位置する斎場。地域密着型の丁寧なサービスが特徴で、リーズナブルな価格設定が好評。泉区北部の住宅街にあり、近隣住民に親しまれています。",
        "address": "宮城県仙台市泉区松森字鹿島3-5",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.3150,
        "longitude": 140.9000,
        "nearest_station": "仙台市営地下鉄南北線 八乙女駅（バス10分）",
        "station_walk_minutes": 20,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 508000},
        ],
        "features": ["地域密着", "低価格", "リーズナブル"],
        "operator_name": "仙台典礼",
        "rating_avg": 3.8,
        "review_count": 22,
    },
    {
        "name": "セレモニーホール紫雲閣 泉中央",
        "slug": "miyagi-shiunkan-izumi-chuo",
        "venue_type": "private_hall",
        "description": "仙台市泉区市名坂に位置する紫雲閣の斎場。泉中央と黒松エリアの間にあり、両地域からのアクセスが便利。中規模の式場で、家族葬から一般葬まで対応しています。",
        "address": "宮城県仙台市泉区市名坂字石止5-1",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.3100,
        "longitude": 140.8850,
        "nearest_station": "仙台市営地下鉄南北線 黒松駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000},
        ],
        "features": ["アクセス良好", "家族葬対応", "中規模対応"],
        "operator_name": "紫雲閣グループ",
        "rating_avg": 3.9,
        "review_count": 35,
    },
    {
        "name": "清月記 根白石ホール",
        "slug": "miyagi-seigetuki-neshiroishi",
        "venue_type": "private_hall",
        "description": "仙台市泉区根白石エリアの清月記斎場。泉ヶ岳に向かう道沿いに位置し、自然に囲まれた静かな環境。泉区北西部の地域住民に利用されています。広い敷地に大型駐車場を完備。",
        "address": "宮城県仙台市泉区根白石字杉下前18",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.3550,
        "longitude": 140.8350,
        "nearest_station": "仙台市営地下鉄南北線 泉中央駅（バス30分）",
        "station_walk_minutes": 60,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000},
        ],
        "features": ["郊外型", "大型駐車場", "自然豊か", "地域密着"],
        "operator_name": "株式会社清月記",
        "rating_avg": 3.8,
        "review_count": 16,
    },
    {
        "name": "アークベル泉パークタウン",
        "slug": "miyagi-arcbell-izumi-park",
        "venue_type": "private_hall",
        "description": "仙台市泉区のパークタウンエリアに位置するアークベルの斎場。洗練されたインテリアとホスピタリティの高いサービスが特徴。泉パークタウンの高級住宅街に佇む格式ある施設です。",
        "address": "宮城県仙台市泉区寺岡6-8-1",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.3380,
        "longitude": 140.8450,
        "nearest_station": "仙台市営地下鉄南北線 泉中央駅（バス20分）",
        "station_walk_minutes": 35,
        "capacity_max": 150,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 60,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True, "会食スペース": True},
        "price_plans": [
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 698000},
        ],
        "features": ["格式高い", "ホスピタリティ", "大型駐車場", "会食充実"],
        "operator_name": "アークベル株式会社",
        "rating_avg": 4.2,
        "review_count": 32,
    },
    {
        "name": "泉メモリアルガーデン",
        "slug": "miyagi-izumi-memorial-garden",
        "venue_type": "private_hall",
        "description": "仙台市泉区長命ケ丘に位置するガーデンスタイルの斎場。緑に囲まれた開放的な空間で、従来の斎場とは異なるナチュラルな雰囲気が特徴。ガーデン葬やお別れ会にも対応しています。",
        "address": "宮城県仙台市泉区長命ケ丘3-28-1",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.3250,
        "longitude": 140.8650,
        "nearest_station": "仙台市営地下鉄南北線 泉中央駅（バス10分）",
        "station_walk_minutes": 20,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "ガーデン": True},
        "price_plans": [
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000},
        ],
        "features": ["ガーデンスタイル", "ナチュラル", "お別れ会対応", "自然豊か"],
        "operator_name": "泉メモリアルガーデン",
        "rating_avg": 4.3,
        "review_count": 28,
    },
    # =============================================
    # 仙台市 追加施設（20件）: 各区の補完分
    # =============================================
    # 青葉区追加
    {
        "name": "仙台葬祭センター 青葉",
        "slug": "miyagi-sousai-center-aoba",
        "venue_type": "private_hall",
        "description": "仙台市青葉区小松島に位置する葬祭センター。仙台バイパス沿いでアクセスが良く、広い駐車場を完備。リーズナブルな価格で家族葬から一般葬まで幅広く対応しています。",
        "address": "宮城県仙台市青葉区小松島3-20-5",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2720,
        "longitude": 140.8520,
        "nearest_station": "JR仙山線 北仙台駅",
        "station_walk_minutes": 15,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000},
        ],
        "features": ["低価格", "バイパス沿い", "広い駐車場", "家族葬対応"],
        "operator_name": "仙台葬祭センター",
        "rating_avg": 3.8,
        "review_count": 35,
    },
    {
        "name": "清月記 吉成ホール",
        "slug": "miyagi-seigetuki-yoshinari",
        "venue_type": "private_hall",
        "description": "仙台市青葉区吉成に位置する清月記の斎場。南吉成・吉成エリアの住宅街にあり、地域に密着したサービスを提供。コンパクトながら温かみのある式場で家族葬に最適です。",
        "address": "宮城県仙台市青葉区吉成1-20-15",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2900,
        "longitude": 140.8350,
        "nearest_station": "JR仙山線 国見駅（バス10分）",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000},
        ],
        "features": ["地域密着", "家族葬専門", "コンパクト"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.0,
        "review_count": 25,
    },
    # 宮城野区追加
    {
        "name": "仙台葬祭センター 宮城野",
        "slug": "miyagi-sousai-center-miyagino",
        "venue_type": "private_hall",
        "description": "仙台市宮城野区田子に位置する葬祭センター。産業道路沿いで車でのアクセスが便利。リーズナブルな価格で質の高いサービスを提供し、コストパフォーマンスの良さが評判です。",
        "address": "宮城県仙台市宮城野区田子2-5-18",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2700,
        "longitude": 140.9350,
        "nearest_station": "JR仙石線 福田町駅",
        "station_walk_minutes": 15,
        "capacity_max": 80,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 488000},
        ],
        "features": ["低価格", "コスパ良好", "車アクセス便利"],
        "operator_name": "仙台葬祭センター",
        "rating_avg": 3.7,
        "review_count": 22,
    },
    {
        "name": "清月記 鶴ケ谷ホール",
        "slug": "miyagi-seigetuki-tsurugaya",
        "venue_type": "private_hall",
        "description": "仙台市宮城野区鶴ケ谷に位置する清月記の斎場。団地に囲まれた住宅エリアにあり、地域住民に長年親しまれています。温かいスタッフ対応と丁寧なサービスが特徴です。",
        "address": "宮城県仙台市宮城野区鶴ケ谷5-22-1",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2830,
        "longitude": 140.9150,
        "nearest_station": "JR仙石線 小鶴新田駅（バス10分）",
        "station_walk_minutes": 20,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000},
        ],
        "features": ["地域密着", "住宅エリア", "家族葬対応"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.0,
        "review_count": 30,
    },
    # 若林区追加
    {
        "name": "仙台葬祭センター 若林",
        "slug": "miyagi-sousai-center-wakabayashi",
        "venue_type": "private_hall",
        "description": "仙台市若林区卸町に位置する葬祭センター。仙台東部の卸町流通エリアにあり、幹線道路からのアクセスが便利。広い敷地に駐車場を完備し、大型車両での来場にも対応しています。",
        "address": "宮城県仙台市若林区卸町東5-3-1",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2530,
        "longitude": 140.9150,
        "nearest_station": "仙台市営地下鉄東西線 卸町駅",
        "station_walk_minutes": 8,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 508000},
        ],
        "features": ["広い駐車場", "駅近", "幹線道路沿い", "家族葬対応"],
        "operator_name": "仙台葬祭センター",
        "rating_avg": 3.8,
        "review_count": 28,
    },
    {
        "name": "清月記 南染師町ホール",
        "slug": "miyagi-seigetuki-minamisomeshimachi",
        "venue_type": "private_hall",
        "description": "仙台市若林区南染師町に位置する清月記の斎場。仙台城下町の歴史ある地域にあり、風情漂う街並みの中に佇む施設。コンパクトながらも清潔感のある式場で、少人数の家族葬に対応しています。",
        "address": "宮城県仙台市若林区南染師町15-3",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2500,
        "longitude": 140.8800,
        "nearest_station": "仙台市営地下鉄東西線 連坊駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000},
        ],
        "features": ["コンパクト", "歴史ある街", "家族葬専門"],
        "operator_name": "株式会社清月記",
        "rating_avg": 3.9,
        "review_count": 20,
    },
    # 太白区追加
    {
        "name": "仙台葬祭センター 太白",
        "slug": "miyagi-sousai-center-taihaku",
        "venue_type": "private_hall",
        "description": "仙台市太白区郡山に位置する葬祭センター。仙台南部の郡山エリアにあり、名取市との境界に近い立地。リーズナブルな価格と丁寧なサービスで、南仙台エリアの住民に支持されています。",
        "address": "宮城県仙台市太白区郡山6-15-1",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2120,
        "longitude": 140.8780,
        "nearest_station": "JR東北本線 太子堂駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 488000},
        ],
        "features": ["低価格", "南仙台エリア", "地域密着"],
        "operator_name": "仙台葬祭センター",
        "rating_avg": 3.7,
        "review_count": 23,
    },
    {
        "name": "清月記 山田ホール",
        "slug": "miyagi-seigetuki-yamada",
        "venue_type": "private_hall",
        "description": "仙台市太白区山田エリアに位置する清月記の斎場。東北自動車道仙台南ICから近く、車でのアクセスに優れています。広い敷地に大型駐車場を備え、遠方からの参列者にも便利です。",
        "address": "宮城県仙台市太白区山田北前町10-1",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2050,
        "longitude": 140.8500,
        "nearest_station": "JR東北本線 南仙台駅（バス15分）",
        "station_walk_minutes": 30,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 70,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000},
            {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000},
        ],
        "features": ["IC近接", "大型駐車場", "車アクセス良好", "家族葬対応"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.0,
        "review_count": 32,
    },
    # 泉区追加
    {
        "name": "仙台葬祭センター 泉",
        "slug": "miyagi-sousai-center-izumi",
        "venue_type": "private_hall",
        "description": "仙台市泉区加茂に位置する葬祭センター。泉区東部の住宅街にあり、コストパフォーマンスの良さが評判。経済的な負担を抑えたい方に選ばれているリーズナブルな斎場です。",
        "address": "宮城県仙台市泉区加茂4-18-5",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.3200,
        "longitude": 140.9050,
        "nearest_station": "仙台市営地下鉄南北線 八乙女駅（バス15分）",
        "station_walk_minutes": 25,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 268000},
        ],
        "features": ["低価格", "コスパ良好", "家族葬対応"],
        "operator_name": "仙台葬祭センター",
        "rating_avg": 3.6,
        "review_count": 18,
    },
    {
        "name": "清月記 松陵ホール",
        "slug": "miyagi-seigetuki-shoryo",
        "venue_type": "private_hall",
        "description": "仙台市泉区松陵に位置する清月記の斎場。泉パークタウン松陵エリアの住宅街に溶け込む落ち着いた佇まいの施設。地域のベッドタウンとして発展したエリアの葬儀需要に応えています。",
        "address": "宮城県仙台市泉区松陵5-15-1",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.3300,
        "longitude": 140.8550,
        "nearest_station": "仙台市営地下鉄南北線 泉中央駅（バス15分）",
        "station_walk_minutes": 25,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000},
        ],
        "features": ["住宅街", "地域密着", "落ち着いた環境", "家族葬対応"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.0,
        "review_count": 21,
    },
    # 太白区 公共施設
    {
        "name": "仙台市太白区文化センター",
        "slug": "miyagi-taihaku-bunka-center",
        "venue_type": "public_facility",
        "description": "仙台市太白区長町に位置する公共文化施設。通常は文化イベントや集会に使用されますが、葬儀・お別れ会にも貸出可能。JR長町駅・地下鉄長町駅から徒歩圏内の好立地で、公共施設ならではのリーズナブルな使用料が魅力です。",
        "address": "宮城県仙台市太白区長町5-3-2",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2270,
        "longitude": 140.8770,
        "nearest_station": "仙台市営地下鉄南北線 長町駅",
        "station_walk_minutes": 5,
        "capacity_max": 300,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"ホール": True, "会議室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [
            {"type": "ippanso", "label": "お別れ会プラン", "priceFrom": 200000},
        ],
        "features": ["公共施設", "大規模対応", "駅近", "低使用料"],
        "operator_name": "仙台市",
        "rating_avg": 3.5,
        "review_count": 12,
    },
    # 青葉区 公共施設
    {
        "name": "仙台市戦災復興記念館",
        "slug": "miyagi-sensai-fukko-kinenkan",
        "venue_type": "public_facility",
        "description": "仙台市青葉区大町に位置する公共施設。ホールや会議室を備え、偲ぶ会やお別れ会の会場としても利用可能。仙台市中心部にあり交通アクセスに優れています。",
        "address": "宮城県仙台市青葉区大町2-12-1",
        "prefecture_slug": "miyagi",
        "city_slug": "sendai",
        "latitude": 38.2570,
        "longitude": 140.8640,
        "nearest_station": "仙台市営地下鉄東西線 大町西公園駅",
        "station_walk_minutes": 3,
        "capacity_max": 200,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"ホール": True, "会議室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [
            {"type": "ippanso", "label": "お別れ会プラン", "priceFrom": 180000},
        ],
        "features": ["公共施設", "駅近", "中心部", "お別れ会向け"],
        "operator_name": "仙台市",
        "rating_avg": 3.6,
        "review_count": 10,
    },
]


def post_batch(batch, batch_num):
    """バッチをPOSTする"""
    data = json.dumps(batch).encode("utf-8")
    req = urllib.request.Request(SUPABASE_URL, data=data, headers=HEADERS, method="POST")
    try:
        resp = urllib.request.urlopen(req)
        print(f"  バッチ {batch_num}: {len(batch)}件 投入成功 (HTTP {resp.status})")
        return True
    except urllib.error.HTTPError as e:
        error_body = e.read().decode("utf-8")
        print(f"  バッチ {batch_num}: エラー (HTTP {e.code})")
        print(f"  エラー詳細: {error_body}")
        return False


def main():
    print(f"=== 宮城県 斎場データ Part2 投入開始 ===")
    print(f"総件数: {len(venues)}件")

    slugs = [v["slug"] for v in venues]
    if len(slugs) != len(set(slugs)):
        duplicates = [s for s in slugs if slugs.count(s) > 1]
        print(f"エラー: スラッグに重複があります: {set(duplicates)}")
        return

    batch_size = 10
    total_batches = (len(venues) + batch_size - 1) // batch_size
    success_count = 0

    print(f"\n{total_batches}バッチに分けて投入します...")
    for i in range(0, len(venues), batch_size):
        batch = venues[i : i + batch_size]
        batch_num = i // batch_size + 1
        print(f"\nバッチ {batch_num}/{total_batches} ({len(batch)}件):")
        for v in batch:
            print(f"  - {v['name']} ({v['slug']})")

        if post_batch(batch, batch_num):
            success_count += len(batch)

        if i + batch_size < len(venues):
            time.sleep(0.5)

    print(f"\n=== 投入完了 ===")
    print(f"成功: {success_count}/{len(venues)}件")


if __name__ == "__main__":
    main()
