#!/usr/bin/env python3
"""
宮城県の斎場データ Part3: 仙台市以外の市町村 + 仙台追加 = 52件
石巻8件, 大崎6件, 名取5件, 登米4件, 栗原3件, 気仙沼3件,
多賀城3件, 塩竈2件, 仙台追加12件, 他各2件
"""

import urllib.request
import json
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

HEADERS = {
    "apikey": API_KEY,
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal",
    "User-Agent": "Mozilla/5.0",
}

venues = [
    # =============================================
    # 石巻市（ishinomaki）: 8件
    # =============================================
    {
        "name": "石巻市斎場",
        "slug": "miyagi-ishinomaki-saijo",
        "venue_type": "public_crematorium",
        "description": "石巻市が運営する公営火葬場。火葬炉6基と式場を備え、石巻市民は割安料金で利用可能です。三陸自動車道石巻河南ICから近く、車でのアクセスが便利。2011年の震災後に設備が一新されています。",
        "address": "宮城県石巻市大瓜字鷹の巣45-2",
        "prefecture_slug": "miyagi",
        "city_slug": "ishinomaki",
        "latitude": 38.4350,
        "longitude": 141.2730,
        "nearest_station": "JR仙石線 石巻駅（バス15分）",
        "station_walk_minutes": 40,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 80,
        "facilities": {"式場": True, "休憩室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}],
        "features": ["火葬場", "公営斎場", "石巻市民割引", "震災後リニューアル"],
        "operator_name": "石巻市",
        "rating_avg": 3.7,
        "review_count": 28,
    },
    {
        "name": "清月記 石巻ホール",
        "slug": "miyagi-seigetuki-ishinomaki",
        "venue_type": "private_hall",
        "description": "石巻市中心部に位置する清月記の斎場。石巻駅から徒歩圏内で、石巻圏域の拠点施設として家族葬から一般葬まで幅広く対応。地域に根差した丁寧なサービスを提供しています。",
        "address": "宮城県石巻市中里3-1-15",
        "prefecture_slug": "miyagi",
        "city_slug": "ishinomaki",
        "latitude": 38.4340,
        "longitude": 141.3060,
        "nearest_station": "JR仙石線 石巻駅",
        "station_walk_minutes": 10,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000},
        ],
        "features": ["駅近", "家族葬対応", "石巻拠点", "地域密着"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.1,
        "review_count": 48,
    },
    {
        "name": "セレモニーホール紫雲閣 石巻",
        "slug": "miyagi-shiunkan-ishinomaki",
        "venue_type": "private_hall",
        "description": "石巻市蛇田エリアに位置する紫雲閣の斎場。三陸自動車道石巻蛇田ICから近い便利な立地。広い駐車場と充実した設備で、安心の葬儀サービスを提供しています。",
        "address": "宮城県石巻市蛇田字新金沼388-1",
        "prefecture_slug": "miyagi",
        "city_slug": "ishinomaki",
        "latitude": 38.4280,
        "longitude": 141.2880,
        "nearest_station": "JR仙石線 蛇田駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 568000},
        ],
        "features": ["IC近接", "駅近", "広い駐車場", "家族葬対応"],
        "operator_name": "紫雲閣グループ",
        "rating_avg": 3.9,
        "review_count": 32,
    },
    {
        "name": "メモリアルホール石巻",
        "slug": "miyagi-memorial-ishinomaki",
        "venue_type": "private_hall",
        "description": "石巻市大街道エリアに位置する斎場。石巻バイパス沿いでアクセスが良く、中規模の式場で家族葬から一般葬まで対応しています。地域に根差した温かいサービスが特徴です。",
        "address": "宮城県石巻市大街道西2-5-1",
        "prefecture_slug": "miyagi",
        "city_slug": "ishinomaki",
        "latitude": 38.4200,
        "longitude": 141.2800,
        "nearest_station": "JR仙石線 蛇田駅",
        "station_walk_minutes": 12,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000},
        ],
        "features": ["バイパス沿い", "家族葬対応", "地域密着"],
        "operator_name": "メモリアルホール",
        "rating_avg": 4.0,
        "review_count": 26,
    },
    {
        "name": "葬祭会館ティア石巻",
        "slug": "miyagi-tier-ishinomaki",
        "venue_type": "private_hall",
        "description": "石巻市あけぼのエリアに位置するティアの斎場。明朗会計のわかりやすい料金体系と、丁寧なサービスが特徴。家族葬プランが充実しています。",
        "address": "宮城県石巻市あけぼの3-1-10",
        "prefecture_slug": "miyagi",
        "city_slug": "ishinomaki",
        "latitude": 38.4300,
        "longitude": 141.3000,
        "nearest_station": "JR仙石線 石巻駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000},
        ],
        "features": ["明朗会計", "家族葬対応", "全国チェーン"],
        "operator_name": "株式会社ティア",
        "rating_avg": 3.9,
        "review_count": 22,
    },
    {
        "name": "やすらぎホール石巻",
        "slug": "miyagi-yasuragi-ishinomaki",
        "venue_type": "private_hall",
        "description": "石巻市渡波エリアに位置する家族葬対応の斎場。漁港に近い下町エリアにあり、地域に密着したアットホームなサービスを提供。リーズナブルな価格設定が特徴です。",
        "address": "宮城県石巻市渡波字山崎35-2",
        "prefecture_slug": "miyagi",
        "city_slug": "ishinomaki",
        "latitude": 38.4060,
        "longitude": 141.3400,
        "nearest_station": "JR仙石線 渡波駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000},
        ],
        "features": ["低価格", "家族葬専門", "地域密着", "アットホーム"],
        "operator_name": "やすらぎホール",
        "rating_avg": 3.8,
        "review_count": 18,
    },
    {
        "name": "石巻典礼会館",
        "slug": "miyagi-ishinomaki-tenrei",
        "venue_type": "private_hall",
        "description": "石巻市日和が丘エリアに位置する地元密着型の斎場。日和山の麓にあり、高台の安全な立地です。家族葬を中心に、地域の葬儀を長年支えてきた実績のある施設です。",
        "address": "宮城県石巻市日和が丘2-10-5",
        "prefecture_slug": "miyagi",
        "city_slug": "ishinomaki",
        "latitude": 38.4320,
        "longitude": 141.3150,
        "nearest_station": "JR仙石線 石巻駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000},
        ],
        "features": ["地元密着", "高台立地", "家族葬対応", "老舗"],
        "operator_name": "石巻典礼",
        "rating_avg": 3.9,
        "review_count": 24,
    },
    {
        "name": "洞源院 式場",
        "slug": "miyagi-togenin-ishinomaki",
        "venue_type": "temple_hall",
        "description": "石巻市湊エリアにある曹洞宗の寺院式場。歴史ある寺院で、仏式葬儀を丁寧に執り行えます。本堂での荘厳な雰囲気の中、故人を偲ぶことができます。",
        "address": "宮城県石巻市湊字大門崎山1-21",
        "prefecture_slug": "miyagi",
        "city_slug": "ishinomaki",
        "latitude": 38.4250,
        "longitude": 141.3250,
        "nearest_station": "JR仙石線 石巻駅（バス10分）",
        "station_walk_minutes": 25,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "控室": True, "駐車場": True},
        "price_plans": [
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000},
        ],
        "features": ["寺院式場", "仏式専門", "荘厳な雰囲気"],
        "operator_name": "洞源院",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    # =============================================
    # 大崎市（osaki）: 6件
    # =============================================
    {
        "name": "大崎市鳴子斎場",
        "slug": "miyagi-osaki-naruko-saijo",
        "venue_type": "public_crematorium",
        "description": "大崎市鳴子温泉エリアに位置する公営火葬場。火葬炉3基を備え、大崎市北部の火葬需要に対応しています。鳴子温泉郷の自然に囲まれた静かな環境です。",
        "address": "宮城県大崎市鳴子温泉字要害22-1",
        "prefecture_slug": "miyagi",
        "city_slug": "osaki",
        "latitude": 38.7350,
        "longitude": 140.7200,
        "nearest_station": "JR陸羽東線 鳴子温泉駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}],
        "features": ["火葬場", "公営斎場", "大崎市民割引"],
        "operator_name": "大崎市",
        "rating_avg": 3.6,
        "review_count": 15,
    },
    {
        "name": "清月記 古川ホール",
        "slug": "miyagi-seigetuki-furukawa",
        "venue_type": "private_hall",
        "description": "大崎市古川に位置する清月記の拠点斎場。JR古川駅から近く、大崎圏域の中心施設として多くの葬儀を執り行っています。家族葬から一般葬まで対応可能な2つの式場を備えています。",
        "address": "宮城県大崎市古川駅前大通1-5-15",
        "prefecture_slug": "miyagi",
        "city_slug": "osaki",
        "latitude": 38.5780,
        "longitude": 140.9570,
        "nearest_station": "JR東北新幹線・陸羽東線 古川駅",
        "station_walk_minutes": 8,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000},
        ],
        "features": ["新幹線駅近", "家族葬対応", "大崎圏域拠点"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.2,
        "review_count": 55,
    },
    {
        "name": "セレモニーホール紫雲閣 古川",
        "slug": "miyagi-shiunkan-furukawa",
        "venue_type": "private_hall",
        "description": "大崎市古川に位置する紫雲閣の斎場。国道4号線沿いでアクセスが良く、広い駐車場を完備。落ち着いた和モダンの式場で、丁寧な葬儀サービスを提供しています。",
        "address": "宮城県大崎市古川穂波3-8-20",
        "prefecture_slug": "miyagi",
        "city_slug": "osaki",
        "latitude": 38.5730,
        "longitude": 140.9650,
        "nearest_station": "JR陸羽東線 古川駅",
        "station_walk_minutes": 12,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000},
        ],
        "features": ["国道4号沿い", "広い駐車場", "家族葬対応"],
        "operator_name": "紫雲閣グループ",
        "rating_avg": 3.9,
        "review_count": 30,
    },
    {
        "name": "メモリアルホール大崎",
        "slug": "miyagi-memorial-osaki",
        "venue_type": "private_hall",
        "description": "大崎市古川の三本木エリアに位置する斎場。東北自動車道三本木ICから近く、車でのアクセスが便利。家族葬に最適なコンパクトな式場で温かいお別れの場を提供しています。",
        "address": "宮城県大崎市三本木字大豆坂24-5",
        "prefecture_slug": "miyagi",
        "city_slug": "osaki",
        "latitude": 38.5400,
        "longitude": 140.9500,
        "nearest_station": "JR東北本線 田尻駅",
        "station_walk_minutes": 20,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000},
        ],
        "features": ["IC近接", "家族葬対応", "コンパクト"],
        "operator_name": "メモリアルホール",
        "rating_avg": 3.9,
        "review_count": 22,
    },
    {
        "name": "やすらぎホール古川",
        "slug": "miyagi-yasuragi-furukawa",
        "venue_type": "private_hall",
        "description": "大崎市古川に位置する家族葬専門のホール。リーズナブルな価格で質の高いサービスを提供。1日1組限定の貸切対応で、ゆっくりとしたお別れの時間を大切にしています。",
        "address": "宮城県大崎市古川旭5-3-8",
        "prefecture_slug": "miyagi",
        "city_slug": "osaki",
        "latitude": 38.5750,
        "longitude": 140.9520,
        "nearest_station": "JR陸羽東線 古川駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000},
        ],
        "features": ["家族葬専門", "1日1組貸切", "低価格"],
        "operator_name": "やすらぎホール",
        "rating_avg": 4.0,
        "review_count": 19,
    },
    {
        "name": "大崎典礼会館",
        "slug": "miyagi-osaki-tenrei",
        "venue_type": "private_hall",
        "description": "大崎市古川に位置する地元密着型の斎場。長年にわたり大崎地域の葬儀を支えてきた実績があり、丁寧なサービスと親切なスタッフ対応で信頼を得ています。",
        "address": "宮城県大崎市古川七日町8-15",
        "prefecture_slug": "miyagi",
        "city_slug": "osaki",
        "latitude": 38.5770,
        "longitude": 140.9600,
        "nearest_station": "JR陸羽東線 古川駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 508000},
        ],
        "features": ["地元密着", "老舗", "丁寧なサービス"],
        "operator_name": "大崎典礼",
        "rating_avg": 3.8,
        "review_count": 25,
    },
    # =============================================
    # 名取市（natori）: 5件
    # =============================================
    {
        "name": "名取市斎場",
        "slug": "miyagi-natori-saijo",
        "venue_type": "public_crematorium",
        "description": "名取市が運営する公営火葬場。火葬炉4基を備え、名取市民は割安料金で利用可能。仙台空港アクセス線沿線で、仙台市太白区との境界にも近い立地です。",
        "address": "宮城県名取市愛島笠島字東蔵神34-1",
        "prefecture_slug": "miyagi",
        "city_slug": "natori",
        "latitude": 38.1800,
        "longitude": 140.8450,
        "nearest_station": "JR東北本線 名取駅（バス10分）",
        "station_walk_minutes": 25,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 40,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}],
        "features": ["火葬場", "公営斎場", "名取市民割引"],
        "operator_name": "名取市",
        "rating_avg": 3.6,
        "review_count": 18,
    },
    {
        "name": "清月記 名取ホール",
        "slug": "miyagi-seigetuki-natori",
        "venue_type": "private_hall",
        "description": "名取市増田に位置する清月記の斎場。JR名取駅から近く、名取市の中心部にあります。家族葬から一般葬まで対応可能で、仙台南部・名取エリアの葬儀需要に応えています。",
        "address": "宮城県名取市増田4-8-20",
        "prefecture_slug": "miyagi",
        "city_slug": "natori",
        "latitude": 38.1740,
        "longitude": 140.8900,
        "nearest_station": "JR東北本線 名取駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000},
        ],
        "features": ["駅近", "家族葬対応", "名取拠点"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.1,
        "review_count": 38,
    },
    {
        "name": "セレモニーホール紫雲閣 名取",
        "slug": "miyagi-shiunkan-natori",
        "venue_type": "private_hall",
        "description": "名取市美田園エリアに位置する紫雲閣の斎場。仙台空港アクセス線美田園駅から近く、仙台空港にも近い好立地。広い駐車場を完備しています。",
        "address": "宮城県名取市美田園7-1-5",
        "prefecture_slug": "miyagi",
        "city_slug": "natori",
        "latitude": 38.1650,
        "longitude": 140.9050,
        "nearest_station": "仙台空港アクセス線 美田園駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 568000},
        ],
        "features": ["駅近", "空港近接", "広い駐車場", "家族葬対応"],
        "operator_name": "紫雲閣グループ",
        "rating_avg": 4.0,
        "review_count": 28,
    },
    {
        "name": "やすらぎホール名取",
        "slug": "miyagi-yasuragi-natori",
        "venue_type": "private_hall",
        "description": "名取市杜せきのしたエリアに位置する家族葬対応の斎場。イオンモール名取近くの便利な立地で、リーズナブルな価格のお別れプランが好評です。",
        "address": "宮城県名取市杜せきのした5-3-1",
        "prefecture_slug": "miyagi",
        "city_slug": "natori",
        "latitude": 38.1700,
        "longitude": 140.8950,
        "nearest_station": "仙台空港アクセス線 杜せきのした駅",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000},
        ],
        "features": ["駅近", "家族葬専門", "低価格", "便利な立地"],
        "operator_name": "やすらぎホール",
        "rating_avg": 4.0,
        "review_count": 22,
    },
    {
        "name": "名取典礼会館",
        "slug": "miyagi-natori-tenrei",
        "venue_type": "private_hall",
        "description": "名取市飯野坂に位置する地元密着の斎場。名取市南部の住宅街にあり、アットホームな雰囲気でお別れの場を提供。地域の葬儀を長年支えてきた信頼の施設です。",
        "address": "宮城県名取市飯野坂3-5-18",
        "prefecture_slug": "miyagi",
        "city_slug": "natori",
        "latitude": 38.1680,
        "longitude": 140.8800,
        "nearest_station": "JR東北本線 館腰駅",
        "station_walk_minutes": 12,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000},
        ],
        "features": ["地元密着", "アットホーム", "家族葬対応"],
        "operator_name": "名取典礼",
        "rating_avg": 3.8,
        "review_count": 16,
    },
    # =============================================
    # 登米市（tome）: 4件
    # =============================================
    {
        "name": "登米市迫斎場",
        "slug": "miyagi-tome-hasama-saijo",
        "venue_type": "public_crematorium",
        "description": "登米市迫町に位置する公営火葬場。登米市民は割安料金で利用可能。三陸自動車道登米ICから近くアクセスが便利です。",
        "address": "宮城県登米市迫町佐沼字南佐沼120",
        "prefecture_slug": "miyagi",
        "city_slug": "tome",
        "latitude": 38.6870,
        "longitude": 141.2020,
        "nearest_station": "JR東北本線 瀬峰駅（バス20分）",
        "station_walk_minutes": 50,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}],
        "features": ["火葬場", "公営斎場", "登米市民割引"],
        "operator_name": "登米市",
        "rating_avg": 3.5,
        "review_count": 12,
    },
    {
        "name": "清月記 佐沼ホール",
        "slug": "miyagi-seigetuki-sanuma",
        "venue_type": "private_hall",
        "description": "登米市迫町佐沼に位置する清月記の斎場。登米地域の中心市街地にあり、家族葬から一般葬まで対応可能。地域に根差した丁寧なサービスを提供しています。",
        "address": "宮城県登米市迫町佐沼字中江3-5-1",
        "prefecture_slug": "miyagi",
        "city_slug": "tome",
        "latitude": 38.6830,
        "longitude": 141.1950,
        "nearest_station": "JR東北本線 瀬峰駅（バス15分）",
        "station_walk_minutes": 40,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000},
        ],
        "features": ["地域密着", "家族葬対応", "登米拠点"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.0,
        "review_count": 28,
    },
    {
        "name": "セレモニーホール紫雲閣 登米",
        "slug": "miyagi-shiunkan-tome",
        "venue_type": "private_hall",
        "description": "登米市中田町に位置する紫雲閣の斎場。国道346号線沿いでアクセスが良く、登米市南部の葬儀需要に対応しています。落ち着いた式場で家族葬を中心にサービスを提供。",
        "address": "宮城県登米市中田町石森字加賀野1-5",
        "prefecture_slug": "miyagi",
        "city_slug": "tome",
        "latitude": 38.6500,
        "longitude": 141.1700,
        "nearest_station": "JR東北本線 瀬峰駅（バス25分）",
        "station_walk_minutes": 60,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000},
        ],
        "features": ["国道沿い", "家族葬対応", "地域密着"],
        "operator_name": "紫雲閣グループ",
        "rating_avg": 3.8,
        "review_count": 18,
    },
    {
        "name": "やすらぎホール登米",
        "slug": "miyagi-yasuragi-tome",
        "venue_type": "private_hall",
        "description": "登米市迫町に位置する家族葬専門ホール。リーズナブルな価格で温かいお別れの場を提供。地域の方に親しまれているアットホームな施設です。",
        "address": "宮城県登米市迫町佐沼字大網218",
        "prefecture_slug": "miyagi",
        "city_slug": "tome",
        "latitude": 38.6850,
        "longitude": 141.2000,
        "nearest_station": "JR東北本線 瀬峰駅（バス20分）",
        "station_walk_minutes": 45,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 268000},
        ],
        "features": ["家族葬専門", "低価格", "アットホーム"],
        "operator_name": "やすらぎホール",
        "rating_avg": 3.9,
        "review_count": 14,
    },
    # =============================================
    # 栗原市（kurihara）: 3件
    # =============================================
    {
        "name": "栗原市築館斎場",
        "slug": "miyagi-kurihara-tsukidate-saijo",
        "venue_type": "public_crematorium",
        "description": "栗原市築館に位置する公営火葬場。栗原市の中心部にあり、火葬炉3基を備えています。栗原市民は割安料金で利用可能です。",
        "address": "宮城県栗原市築館字留場大久保1-1",
        "prefecture_slug": "miyagi",
        "city_slug": "kurihara",
        "latitude": 38.7310,
        "longitude": 141.0180,
        "nearest_station": "JR東北新幹線 くりこま高原駅（バス15分）",
        "station_walk_minutes": 40,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}],
        "features": ["火葬場", "公営斎場", "栗原市民割引"],
        "operator_name": "栗原市",
        "rating_avg": 3.5,
        "review_count": 10,
    },
    {
        "name": "清月記 築館ホール",
        "slug": "miyagi-seigetuki-tsukidate",
        "venue_type": "private_hall",
        "description": "栗原市築館に位置する清月記の斎場。栗原地域の葬儀需要に対応し、家族葬から一般葬まで幅広くサービスを提供。地域に根差した丁寧な対応が特徴です。",
        "address": "宮城県栗原市築館伊豆2-6-1",
        "prefecture_slug": "miyagi",
        "city_slug": "kurihara",
        "latitude": 38.7280,
        "longitude": 141.0200,
        "nearest_station": "JR東北新幹線 くりこま高原駅（バス15分）",
        "station_walk_minutes": 35,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 508000},
        ],
        "features": ["地域密着", "家族葬対応", "栗原拠点"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.0,
        "review_count": 22,
    },
    {
        "name": "やすらぎホール栗原",
        "slug": "miyagi-yasuragi-kurihara",
        "venue_type": "private_hall",
        "description": "栗原市築館に位置する家族葬専門のホール。リーズナブルな料金と温かいサービスで地域に愛されています。",
        "address": "宮城県栗原市築館薬師3-8-1",
        "prefecture_slug": "miyagi",
        "city_slug": "kurihara",
        "latitude": 38.7300,
        "longitude": 141.0150,
        "nearest_station": "JR東北新幹線 くりこま高原駅（バス10分）",
        "station_walk_minutes": 30,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 258000},
        ],
        "features": ["家族葬専門", "低価格", "地域密着"],
        "operator_name": "やすらぎホール",
        "rating_avg": 3.8,
        "review_count": 12,
    },
    # =============================================
    # 気仙沼市（kesennuma）: 3件
    # =============================================
    {
        "name": "気仙沼市斎場",
        "slug": "miyagi-kesennuma-saijo",
        "venue_type": "public_crematorium",
        "description": "気仙沼市が運営する公営火葬場。三陸海岸に面した気仙沼市の火葬需要を担う基幹施設。東日本大震災後に設備を一新し、近代的な施設に生まれ変わりました。",
        "address": "宮城県気仙沼市赤岩杉ノ沢47-6",
        "prefecture_slug": "miyagi",
        "city_slug": "kesennuma",
        "latitude": 38.9070,
        "longitude": 141.5650,
        "nearest_station": "JR大船渡線BRT 気仙沼駅（バス15分）",
        "station_walk_minutes": 40,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}],
        "features": ["火葬場", "公営斎場", "気仙沼市民割引", "震災後リニューアル"],
        "operator_name": "気仙沼市",
        "rating_avg": 3.6,
        "review_count": 14,
    },
    {
        "name": "清月記 気仙沼ホール",
        "slug": "miyagi-seigetuki-kesennuma",
        "venue_type": "private_hall",
        "description": "気仙沼市南町に位置する清月記の斎場。気仙沼湾を臨む市街地にあり、気仙沼地域の葬儀拠点として機能。家族葬から一般葬まで対応可能です。",
        "address": "宮城県気仙沼市南町1-3-20",
        "prefecture_slug": "miyagi",
        "city_slug": "kesennuma",
        "latitude": 38.9050,
        "longitude": 141.5700,
        "nearest_station": "JR大船渡線BRT 気仙沼駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000},
        ],
        "features": ["気仙沼拠点", "家族葬対応", "地域密着"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.1,
        "review_count": 25,
    },
    {
        "name": "やすらぎホール気仙沼",
        "slug": "miyagi-yasuragi-kesennuma",
        "venue_type": "private_hall",
        "description": "気仙沼市田中前に位置する家族葬対応の斎場。漁港町らしい温かい人情味のある対応が特徴で、地域住民に愛されている施設です。",
        "address": "宮城県気仙沼市田中前3-5-1",
        "prefecture_slug": "miyagi",
        "city_slug": "kesennuma",
        "latitude": 38.9020,
        "longitude": 141.5680,
        "nearest_station": "JR大船渡線BRT 気仙沼駅",
        "station_walk_minutes": 12,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000},
        ],
        "features": ["家族葬専門", "地域密着", "アットホーム"],
        "operator_name": "やすらぎホール",
        "rating_avg": 3.9,
        "review_count": 16,
    },
    # =============================================
    # 多賀城市（tagajo）: 3件
    # =============================================
    {
        "name": "清月記 多賀城ホール",
        "slug": "miyagi-seigetuki-tagajo",
        "venue_type": "private_hall",
        "description": "多賀城市中央に位置する清月記の斎場。JR仙石線多賀城駅から近く、仙台と松島の中間に位置する好立地。史跡多賀城にちなんだ和の趣きある式場が特徴です。",
        "address": "宮城県多賀城市中央2-8-1",
        "prefecture_slug": "miyagi",
        "city_slug": "tagajo",
        "latitude": 38.2950,
        "longitude": 140.9700,
        "nearest_station": "JR仙石線 多賀城駅",
        "station_walk_minutes": 7,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000},
        ],
        "features": ["駅近", "家族葬対応", "和の趣き"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.1,
        "review_count": 32,
    },
    {
        "name": "セレモニーホール紫雲閣 多賀城",
        "slug": "miyagi-shiunkan-tagajo",
        "venue_type": "private_hall",
        "description": "多賀城市八幡エリアに位置する紫雲閣の斎場。国道45号線沿いで車でのアクセスが便利。仙台・塩竈からも近い立地で、広域からの利用があります。",
        "address": "宮城県多賀城市八幡4-3-15",
        "prefecture_slug": "miyagi",
        "city_slug": "tagajo",
        "latitude": 38.2980,
        "longitude": 140.9750,
        "nearest_station": "JR仙石線 多賀城駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000},
        ],
        "features": ["国道沿い", "アクセス良好", "家族葬対応"],
        "operator_name": "紫雲閣グループ",
        "rating_avg": 3.9,
        "review_count": 24,
    },
    {
        "name": "多賀城典礼会館",
        "slug": "miyagi-tagajo-tenrei",
        "venue_type": "private_hall",
        "description": "多賀城市桜木に位置する地元密着の斎場。アットホームな雰囲気で、少人数の家族葬に対応。リーズナブルな価格設定が地域住民に支持されています。",
        "address": "宮城県多賀城市桜木3-5-10",
        "prefecture_slug": "miyagi",
        "city_slug": "tagajo",
        "latitude": 38.2920,
        "longitude": 140.9680,
        "nearest_station": "JR仙石線 多賀城駅",
        "station_walk_minutes": 12,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000},
        ],
        "features": ["地元密着", "低価格", "家族葬対応", "アットホーム"],
        "operator_name": "多賀城典礼",
        "rating_avg": 3.8,
        "review_count": 18,
    },
    # =============================================
    # 塩竈市（shiogama）: 2件
    # =============================================
    {
        "name": "清月記 塩釜ホール",
        "slug": "miyagi-seigetuki-shiogama",
        "venue_type": "private_hall",
        "description": "塩竈市本町に位置する清月記の斎場。鹽竈神社の門前町にあり、港町塩竈の風情を感じられる立地。JR仙石線本塩釜駅から近く、家族葬から一般葬まで対応しています。",
        "address": "宮城県塩竈市本町3-1-15",
        "prefecture_slug": "miyagi",
        "city_slug": "shiogama",
        "latitude": 38.3160,
        "longitude": 141.0200,
        "nearest_station": "JR仙石線 本塩釜駅",
        "station_walk_minutes": 5,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000},
        ],
        "features": ["駅近", "港町", "家族葬対応", "鹽竈神社近接"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.1,
        "review_count": 30,
    },
    {
        "name": "やすらぎホール塩竈",
        "slug": "miyagi-yasuragi-shiogama",
        "venue_type": "private_hall",
        "description": "塩竈市杉の入に位置する家族葬対応の斎場。塩竈市の住宅エリアにあり、地域に密着したサービスを提供。リーズナブルな価格が好評です。",
        "address": "宮城県塩竈市杉の入2-15-1",
        "prefecture_slug": "miyagi",
        "city_slug": "shiogama",
        "latitude": 38.3130,
        "longitude": 141.0150,
        "nearest_station": "JR仙石線 本塩釜駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000},
        ],
        "features": ["家族葬対応", "低価格", "地域密着"],
        "operator_name": "やすらぎホール",
        "rating_avg": 3.9,
        "review_count": 20,
    },
    # =============================================
    # その他の市: 各2件ずつ
    # =============================================
    # 白石市（shiroishi）
    {
        "name": "白石市斎場",
        "slug": "miyagi-shiroishi-saijo",
        "venue_type": "public_crematorium",
        "description": "白石市が運営する公営火葬場。蔵王連峰の麓に位置し、白石市民は割安料金で利用可能。東北自動車道白石ICから近いアクセスの良い施設です。",
        "address": "宮城県白石市福岡蔵本字陣場1",
        "prefecture_slug": "miyagi",
        "city_slug": "shiroishi",
        "latitude": 38.0010,
        "longitude": 140.6200,
        "nearest_station": "JR東北本線 白石駅（バス10分）",
        "station_walk_minutes": 25,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}],
        "features": ["火葬場", "公営斎場", "白石市民割引"],
        "operator_name": "白石市",
        "rating_avg": 3.5,
        "review_count": 10,
    },
    {
        "name": "清月記 白石ホール",
        "slug": "miyagi-seigetuki-shiroishi",
        "venue_type": "private_hall",
        "description": "白石市中町に位置する清月記の斎場。白石城下町の中心部にあり、地域に根差した葬儀サービスを提供しています。",
        "address": "宮城県白石市中町30-1",
        "prefecture_slug": "miyagi",
        "city_slug": "shiroishi",
        "latitude": 38.0020,
        "longitude": 140.6180,
        "nearest_station": "JR東北本線 白石駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000},
        ],
        "features": ["駅近", "城下町", "家族葬対応"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.0,
        "review_count": 18,
    },
    # 角田市（kakuda）
    {
        "name": "清月記 角田ホール",
        "slug": "miyagi-seigetuki-kakuda",
        "venue_type": "private_hall",
        "description": "角田市角田に位置する清月記の斎場。角田市の中心部にあり、地域の葬儀需要に応えています。阿武隈急行角田駅から近い便利な立地です。",
        "address": "宮城県角田市角田字町200-1",
        "prefecture_slug": "miyagi",
        "city_slug": "kakuda",
        "latitude": 37.9740,
        "longitude": 140.7830,
        "nearest_station": "阿武隈急行 角田駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000},
        ],
        "features": ["駅近", "地域密着", "家族葬対応"],
        "operator_name": "株式会社清月記",
        "rating_avg": 3.9,
        "review_count": 15,
    },
    {
        "name": "やすらぎホール角田",
        "slug": "miyagi-yasuragi-kakuda",
        "venue_type": "private_hall",
        "description": "角田市に位置する家族葬専門のホール。田園風景に囲まれた穏やかな環境で、故人をゆっくり偲ぶことができます。",
        "address": "宮城県角田市梶賀字高畑50",
        "prefecture_slug": "miyagi",
        "city_slug": "kakuda",
        "latitude": 37.9780,
        "longitude": 140.7800,
        "nearest_station": "阿武隈急行 角田駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 258000},
        ],
        "features": ["家族葬専門", "低価格", "田園風景"],
        "operator_name": "やすらぎホール",
        "rating_avg": 3.8,
        "review_count": 10,
    },
    # 東松島市（higashimatsushima）
    {
        "name": "清月記 矢本ホール",
        "slug": "miyagi-seigetuki-yamoto",
        "venue_type": "private_hall",
        "description": "東松島市矢本に位置する清月記の斎場。JR仙石線矢本駅から近く、松島湾を臨む地域の拠点施設。震災復興の象徴でもあるエリアに建つ近代的な施設です。",
        "address": "宮城県東松島市矢本字大溜1-1",
        "prefecture_slug": "miyagi",
        "city_slug": "higashimatsushima",
        "latitude": 38.4250,
        "longitude": 141.2100,
        "nearest_station": "JR仙石線 矢本駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000},
        ],
        "features": ["駅近", "家族葬対応", "近代的施設"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.0,
        "review_count": 20,
    },
    {
        "name": "やすらぎホール東松島",
        "slug": "miyagi-yasuragi-higashimatsushima",
        "venue_type": "private_hall",
        "description": "東松島市赤井に位置する家族葬対応のホール。地域に根差したアットホームなサービスで、少人数のお別れに最適な空間を提供しています。",
        "address": "宮城県東松島市赤井字鷲塚80",
        "prefecture_slug": "miyagi",
        "city_slug": "higashimatsushima",
        "latitude": 38.4280,
        "longitude": 141.2200,
        "nearest_station": "JR仙石線 矢本駅",
        "station_walk_minutes": 12,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 268000},
        ],
        "features": ["家族葬専門", "低価格", "地域密着"],
        "operator_name": "やすらぎホール",
        "rating_avg": 3.8,
        "review_count": 12,
    },
    # 富谷市（tomiya）
    {
        "name": "清月記 富谷ホール",
        "slug": "miyagi-seigetuki-tomiya",
        "venue_type": "private_hall",
        "description": "富谷市成田に位置する清月記の斎場。仙台市泉区との境界に近く、仙台北部のベッドタウンとして発展する富谷市の葬儀需要に対応。国道4号線沿いでアクセスが便利です。",
        "address": "宮城県富谷市成田9-2-1",
        "prefecture_slug": "miyagi",
        "city_slug": "tomiya",
        "latitude": 38.3450,
        "longitude": 140.8930,
        "nearest_station": "仙台市営地下鉄南北線 泉中央駅（バス15分）",
        "station_walk_minutes": 30,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000},
        ],
        "features": ["国道沿い", "ベッドタウン", "家族葬対応"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.1,
        "review_count": 28,
    },
    {
        "name": "やすらぎホール富谷",
        "slug": "miyagi-yasuragi-tomiya",
        "venue_type": "private_hall",
        "description": "富谷市大清水に位置する家族葬対応のホール。富谷市の住宅街にあり、新興住宅地の住民に利用されています。1日1組限定の貸切対応です。",
        "address": "宮城県富谷市大清水1-30-5",
        "prefecture_slug": "miyagi",
        "city_slug": "tomiya",
        "latitude": 38.3500,
        "longitude": 140.8850,
        "nearest_station": "仙台市営地下鉄南北線 泉中央駅（バス20分）",
        "station_walk_minutes": 35,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000},
        ],
        "features": ["家族葬専門", "1日1組貸切", "新興住宅地"],
        "operator_name": "やすらぎホール",
        "rating_avg": 4.0,
        "review_count": 16,
    },
    # 岩沼市（iwanuma）
    {
        "name": "清月記 岩沼ホール",
        "slug": "miyagi-seigetuki-iwanuma",
        "venue_type": "private_hall",
        "description": "岩沼市に位置する清月記の斎場。JR岩沼駅から近く、竹駒神社にも近い歴史ある街に位置。名取市・亘理町からのアクセスも良好で、広域の葬儀需要に対応しています。",
        "address": "宮城県岩沼市中央1-5-20",
        "prefecture_slug": "miyagi",
        "city_slug": "iwanuma",
        "latitude": 38.1040,
        "longitude": 140.8680,
        "nearest_station": "JR東北本線 岩沼駅",
        "station_walk_minutes": 7,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000},
            {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000},
        ],
        "features": ["駅近", "竹駒神社近接", "家族葬対応"],
        "operator_name": "株式会社清月記",
        "rating_avg": 4.0,
        "review_count": 24,
    },
    {
        "name": "やすらぎホール岩沼",
        "slug": "miyagi-yasuragi-iwanuma",
        "venue_type": "private_hall",
        "description": "岩沼市たけくまに位置する家族葬対応のホール。岩沼駅東口エリアの住宅街にあり、リーズナブルな価格で温かいサービスを提供しています。",
        "address": "宮城県岩沼市たけくま3-8-1",
        "prefecture_slug": "miyagi",
        "city_slug": "iwanuma",
        "latitude": 38.1060,
        "longitude": 140.8750,
        "nearest_station": "JR東北本線 岩沼駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [
            {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000},
            {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 268000},
        ],
        "features": ["家族葬専門", "低価格", "駅近"],
        "operator_name": "やすらぎホール",
        "rating_avg": 3.8,
        "review_count": 14,
    },
]


def post_batch(batch, batch_num):
    """バッチをPOSTする"""
    data = json.dumps(batch).encode("utf-8")
    req = urllib.request.Request(SUPABASE_URL, data=data, headers=HEADERS, method="POST")
    try:
        resp = urllib.request.urlopen(req)
        print(f"  バッチ {batch_num}: {len(batch)}件 投入成功 (HTTP {resp.status})")
        return True
    except urllib.error.HTTPError as e:
        error_body = e.read().decode("utf-8")
        print(f"  バッチ {batch_num}: エラー (HTTP {e.code})")
        print(f"  エラー詳細: {error_body}")
        return False


def main():
    print(f"=== 宮城県 斎場データ Part3 投入開始 ===")
    print(f"総件数: {len(venues)}件")

    slugs = [v["slug"] for v in venues]
    if len(slugs) != len(set(slugs)):
        duplicates = [s for s in slugs if slugs.count(s) > 1]
        print(f"エラー: スラッグに重複があります: {set(duplicates)}")
        return

    city_counts = {}
    for v in venues:
        city = v["city_slug"]
        city_counts[city] = city_counts.get(city, 0) + 1
    print("\n市区町村別件数:")
    for city, count in sorted(city_counts.items(), key=lambda x: -x[1]):
        print(f"  {city}: {count}件")

    batch_size = 10
    total_batches = (len(venues) + batch_size - 1) // batch_size
    success_count = 0

    print(f"\n{total_batches}バッチに分けて投入します...")
    for i in range(0, len(venues), batch_size):
        batch = venues[i : i + batch_size]
        batch_num = i // batch_size + 1
        print(f"\nバッチ {batch_num}/{total_batches} ({len(batch)}件):")
        for v in batch:
            print(f"  - {v['name']} ({v['slug']})")

        if post_batch(batch, batch_num):
            success_count += len(batch)

        if i + batch_size < len(venues):
            time.sleep(0.5)

    print(f"\n=== 投入完了 ===")
    print(f"成功: {success_count}/{len(venues)}件")


if __name__ == "__main__":
    main()
