#!/usr/bin/env python3
"""
岐阜県 斎場データ追加（batch2） — 42件
Supabase REST APIに10件ずつバッチでPOSTする
"""

import json
import urllib.request
import urllib.error
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

HEADERS = {
    "apikey": API_KEY,
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal",
}

venues = [
    # =============================================
    # 岐阜市 (gifu-city) — 10件追加
    # =============================================
    {
        "name": "メモワール長森斎場",
        "slug": "memoir-nagamori-gifu",
        "venue_type": "private_hall",
        "description": "メモワールが運営する岐阜市長森の葬儀斎場。創業50年以上の実績と信用を持つ岐阜県下最大の斎場数を擁する葬儀社。家族葬から一般葬まで幅広く対応。温かみのあるアットホームな式場が特長です。",
        "address": "岐阜県岐阜市野一色6-12-17",
        "prefecture_slug": "gifu",
        "city_slug": "gifu-city",
        "latitude": 35.408,
        "longitude": 136.799,
        "nearest_station": "JR東海道本線 長森駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["老舗葬儀社", "家族葬対応", "宿泊可能", "駅近", "駐車場完備"],
        "operator_name": "葬儀斎場メモワール",
        "rating_avg": 4.2,
        "review_count": 28,
    },
    {
        "name": "メモワール鷺山斎場",
        "slug": "memoir-sagiyama-gifu",
        "venue_type": "private_hall",
        "description": "メモワールが運営する岐阜市鷺山の葬儀斎場。アットホームな雰囲気が特徴の式場で、一日一式の通夜・葬儀に対応。少人数の家族葬に最適な落ち着いた空間。経験豊富なスタッフが丁寧にサポートします。",
        "address": "岐阜県岐阜市鷺山東2-5-18",
        "prefecture_slug": "gifu",
        "city_slug": "gifu-city",
        "latitude": 35.438,
        "longitude": 136.758,
        "nearest_station": "名鉄名古屋本線 名鉄岐阜駅",
        "station_walk_minutes": 20,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}],
        "features": ["家族葬対応", "1日1組貸切", "アットホーム", "24時間対応"],
        "operator_name": "葬儀斎場メモワール",
        "rating_avg": 4.3,
        "review_count": 22,
    },
    {
        "name": "メモワール三輪斎場",
        "slug": "memoir-miwa-gifu",
        "venue_type": "private_hall",
        "description": "メモワールが運営する岐阜市三輪の葬儀斎場。岐阜市北部エリアの方々に利用されている式場。家族葬に特化した温かみのある空間で、落ち着いた雰囲気の中でお別れができます。24時間対応の相談窓口あり。",
        "address": "岐阜県岐阜市三輪宮西985-1",
        "prefecture_slug": "gifu",
        "city_slug": "gifu-city",
        "latitude": 35.455,
        "longitude": 136.795,
        "nearest_station": "名鉄各務原線 高田橋駅",
        "station_walk_minutes": 15,
        "capacity_max": 35,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 18,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["家族葬専用", "24時間対応", "駐車場完備"],
        "operator_name": "葬儀斎場メモワール",
        "rating_avg": 4.1,
        "review_count": 16,
    },
    {
        "name": "メモワール加納斎場",
        "slug": "memoir-kanou-gifu",
        "venue_type": "private_hall",
        "description": "メモワールが運営する岐阜市加納の葬儀斎場。JR岐阜駅南口から車で約5分の好立地。岐阜市斎苑にも近く、火葬場へのアクセスが便利。大小の式場を備え、家族葬から一般葬まで対応可能です。",
        "address": "岐阜県岐阜市加納本町3-15-8",
        "prefecture_slug": "gifu",
        "city_slug": "gifu-city",
        "latitude": 35.405,
        "longitude": 136.753,
        "nearest_station": "JR東海道本線 岐阜駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["駅近", "火葬場近く", "家族葬対応", "大規模葬対応", "宿泊可能"],
        "operator_name": "葬儀斎場メモワール",
        "rating_avg": 4.2,
        "review_count": 25,
    },
    {
        "name": "セレモニーホール野々村",
        "slug": "nonomura-ceremony-gifu",
        "venue_type": "private_hall",
        "description": "野々村葬儀社が運営する岐阜市の大型葬儀会館。大中小3つのホールに加え別棟の家族葬専用ホールを1つ備え、少人数から大規模葬儀まで対応。岐阜市内で人気の高い葬儀場で、1日1組貸切の家族葬にも対応しています。",
        "address": "岐阜県岐阜市六条東3-3-20",
        "prefecture_slug": "gifu",
        "city_slug": "gifu-city",
        "latitude": 35.395,
        "longitude": 136.768,
        "nearest_station": "JR東海道本線 岐阜駅",
        "station_walk_minutes": 15,
        "capacity_max": 150,
        "hall_count": 4,
        "has_crematorium": False,
        "parking_count": 60,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["大規模葬対応", "家族葬専用ホールあり", "1日1組貸切", "宿泊可能", "駐車場完備"],
        "operator_name": "野々村葬儀社",
        "rating_avg": 4.4,
        "review_count": 35,
    },
    {
        "name": "岐阜葬祭 島斎場",
        "slug": "gifu-sousai-shima-saijo",
        "venue_type": "private_hall",
        "description": "岐阜葬祭が運営する岐阜市島の葬儀斎場。旧島岐阜斎場としても知られ、岐阜市中部エリアで利用されている施設。安置施設を完備し、家族葬から一般葬まで幅広いプランに対応。24時間対応の相談窓口があります。",
        "address": "岐阜県岐阜市東島1-15-30",
        "prefecture_slug": "gifu",
        "city_slug": "gifu-city",
        "latitude": 35.398,
        "longitude": 136.790,
        "nearest_station": "名鉄名古屋本線 笠松駅",
        "station_walk_minutes": 18,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["安置室完備", "家族葬対応", "大規模葬対応", "24時間対応", "駐車場完備"],
        "operator_name": "岐阜葬祭",
        "rating_avg": 4.1,
        "review_count": 22,
    },
    {
        "name": "アスピカ岐阜斎場",
        "slug": "aspica-gifu-saijo",
        "venue_type": "private_hall",
        "description": "株式会社アスピカが運営する岐阜市の葬儀会館。家族葬に特化したホールで、少人数のお別れに最適。清潔感のある近代的な設備と、経験豊富なスタッフによる丁寧なサポートが特長。明朗会計で安心して利用できます。",
        "address": "岐阜県岐阜市茜部中島3-68",
        "prefecture_slug": "gifu",
        "city_slug": "gifu-city",
        "latitude": 35.388,
        "longitude": 136.755,
        "nearest_station": "JR東海道本線 西岐阜駅",
        "station_walk_minutes": 12,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬専用", "明朗会計", "24時間対応", "バリアフリー"],
        "operator_name": "株式会社アスピカ",
        "rating_avg": 4.2,
        "review_count": 18,
    },
    {
        "name": "小さなお葬式 岐阜ホール",
        "slug": "chiisana-ososhiki-gifu",
        "venue_type": "private_hall",
        "description": "全国展開の「小さなお葬式」ブランドの岐阜ホール。火葬式から家族葬まで、明確な料金体系でリーズナブルなプランを提供。追加費用が少なく、シンプルで温かみのある葬儀を実現。岐阜市内のアクセスしやすい立地です。",
        "address": "岐阜県岐阜市長住町2-5",
        "prefecture_slug": "gifu",
        "city_slug": "gifu-city",
        "latitude": 35.420,
        "longitude": 136.760,
        "nearest_station": "名鉄名古屋本線 名鉄岐阜駅",
        "station_walk_minutes": 8,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["低価格", "明朗会計", "駅近", "家族葬対応"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 4.0,
        "review_count": 14,
    },
    {
        "name": "メモワール芥見斎場",
        "slug": "memoir-akutami-gifu",
        "venue_type": "private_hall",
        "description": "メモワールが運営する岐阜市芥見の葬儀斎場。岐阜市東部エリアの方々に利用されている落ち着いた式場。家族葬に適したアットホームな空間で、ゆっくりとお別れの時間を過ごせます。",
        "address": "岐阜県岐阜市芥見大般若1-68",
        "prefecture_slug": "gifu",
        "city_slug": "gifu-city",
        "latitude": 35.430,
        "longitude": 136.835,
        "nearest_station": "名鉄各務原線 各務原市役所前駅",
        "station_walk_minutes": 25,
        "capacity_max": 35,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 18,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["家族葬対応", "アットホーム", "駐車場完備"],
        "operator_name": "葬儀斎場メモワール",
        "rating_avg": 4.0,
        "review_count": 13,
    },
    {
        "name": "家族葬のかぞくホール岐阜",
        "slug": "kazoku-hall-gifu",
        "venue_type": "private_hall",
        "description": "岐阜市の家族葬専用ホール。少人数のお別れに特化した完全貸切型の式場。リビングルームのような温かい雰囲気の中で、ご家族だけのプライベートな時間を過ごせます。火葬式から家族葬まで明朗会計で対応。",
        "address": "岐阜県岐阜市則武西2-18-5",
        "prefecture_slug": "gifu",
        "city_slug": "gifu-city",
        "latitude": 35.430,
        "longitude": 136.738,
        "nearest_station": "JR東海道本線 西岐阜駅",
        "station_walk_minutes": 10,
        "capacity_max": 20,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬専用", "1日1組貸切", "明朗会計", "低価格"],
        "operator_name": "かぞくホール",
        "rating_avg": 4.3,
        "review_count": 12,
    },

    # =============================================
    # 大垣市 (ogaki) — 5件追加
    # =============================================
    {
        "name": "岐阜葬祭 大垣斎場",
        "slug": "gifu-sousai-ogaki-saijo",
        "venue_type": "private_hall",
        "description": "岐阜葬祭が運営する大垣市の葬儀斎場。旧セレモニーホール子安斎場。JR大垣駅から車で約8分。家族葬から一般葬まで幅広く対応し、安置施設も完備。西濃エリアで実績のある葬儀社の安心のサービスです。",
        "address": "岐阜県大垣市安井町2-58",
        "prefecture_slug": "gifu",
        "city_slug": "ogaki",
        "latitude": 35.362,
        "longitude": 136.614,
        "nearest_station": "JR東海道本線 大垣駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000}],
        "features": ["安置室完備", "家族葬対応", "大規模葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "岐阜葬祭",
        "rating_avg": 4.1,
        "review_count": 20,
    },
    {
        "name": "セレモニーホール大垣南",
        "slug": "ceremony-ogaki-minami",
        "venue_type": "private_hall",
        "description": "大垣市南部の民間葬儀会館。家族葬に特化した落ち着いた空間で、1日1組完全貸切対応。大垣IC近くでアクセスも便利。経験豊富なスタッフが西濃地域の葬儀文化に配慮したサービスを提供しています。",
        "address": "岐阜県大垣市浅中1-1-28",
        "prefecture_slug": "gifu",
        "city_slug": "ogaki",
        "latitude": 35.340,
        "longitude": 136.606,
        "nearest_station": "養老鉄道 西大垣駅",
        "station_walk_minutes": 12,
        "capacity_max": 35,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 18,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬専用", "1日1組貸切", "IC近く", "24時間対応"],
        "operator_name": "大垣南セレモニー",
        "rating_avg": 4.2,
        "review_count": 14,
    },
    {
        "name": "家族葬の花みずき大垣",
        "slug": "hanamizuki-ogaki",
        "venue_type": "private_hall",
        "description": "大垣市の家族葬専用ホール。少人数のお別れに特化した完全貸切型式場。花と緑に囲まれた温かみのある空間で、ご家族だけの静かなお別れの時間を提供。明朗会計でリーズナブルなプランが特長です。",
        "address": "岐阜県大垣市中川町3-22-1",
        "prefecture_slug": "gifu",
        "city_slug": "ogaki",
        "latitude": 35.358,
        "longitude": 136.620,
        "nearest_station": "JR東海道本線 大垣駅",
        "station_walk_minutes": 10,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬専用", "1日1組貸切", "明朗会計", "駅近"],
        "operator_name": "花みずき",
        "rating_avg": 4.4,
        "review_count": 16,
    },
    {
        "name": "小さなお葬式 大垣ホール",
        "slug": "chiisana-ososhiki-ogaki",
        "venue_type": "private_hall",
        "description": "全国展開の「小さなお葬式」ブランドの大垣ホール。火葬式から家族葬まで明確な料金体系で提供。追加費用が少なく、シンプルで温かみのある葬儀を実現。大垣市内のアクセスしやすい立地です。",
        "address": "岐阜県大垣市本今町3-118",
        "prefecture_slug": "gifu",
        "city_slug": "ogaki",
        "latitude": 35.355,
        "longitude": 136.625,
        "nearest_station": "JR東海道本線 大垣駅",
        "station_walk_minutes": 12,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["低価格", "明朗会計", "家族葬対応", "24時間対応"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "メモリアルホール大垣北",
        "slug": "memorial-ogaki-kita",
        "venue_type": "private_hall",
        "description": "大垣市北部の葬儀会館。家族葬から一般葬まで対応可能な中規模施設。バリアフリー対応で高齢の参列者にも安心。広い駐車場を完備し、近隣の方はもちろん遠方からの参列者にも配慮した設備です。",
        "address": "岐阜県大垣市長松町848",
        "prefecture_slug": "gifu",
        "city_slug": "ogaki",
        "latitude": 35.375,
        "longitude": 136.598,
        "nearest_station": "JR東海道本線 大垣駅",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["家族葬対応", "大規模葬対応", "宿泊可能", "バリアフリー", "駐車場完備"],
        "operator_name": "メモリアルホール大垣",
        "rating_avg": 4.0,
        "review_count": 15,
    },

    # =============================================
    # 各務原市 (kakamigahara) — 4件追加
    # =============================================
    {
        "name": "メモワール各務原斎場",
        "slug": "memoir-kakamigahara-saijo",
        "venue_type": "private_hall",
        "description": "メモワールが運営する各務原市の葬儀斎場。名鉄各務原線沿いの好立地。家族葬から一般葬まで幅広く対応し、経験豊富なスタッフが丁寧にサポート。メモワールの県下最大のネットワークによる安心のサービスです。",
        "address": "岐阜県各務原市鵜沼各務原町7-55",
        "prefecture_slug": "gifu",
        "city_slug": "kakamigahara",
        "latitude": 35.398,
        "longitude": 136.880,
        "nearest_station": "名鉄各務原線 各務原市役所前駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["老舗葬儀社", "家族葬対応", "大規模葬対応", "宿泊可能", "駅近"],
        "operator_name": "葬儀斎場メモワール",
        "rating_avg": 4.2,
        "review_count": 20,
    },
    {
        "name": "岐阜葬祭 そはら斎場",
        "slug": "gifu-sousai-sohara",
        "venue_type": "private_hall",
        "description": "岐阜葬祭が運営する各務原市蘇原の葬儀斎場。JR蘇原駅から車で約5分の好立地。安置施設を完備し、家族葬から一般葬まで幅広いプランに対応。各務原市南部エリアの方々に利用されています。",
        "address": "岐阜県各務原市蘇原希望町2-28",
        "prefecture_slug": "gifu",
        "city_slug": "kakamigahara",
        "latitude": 35.378,
        "longitude": 136.860,
        "nearest_station": "JR高山本線 蘇原駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000}],
        "features": ["安置室完備", "家族葬対応", "駅近", "駐車場完備"],
        "operator_name": "岐阜葬祭",
        "rating_avg": 4.1,
        "review_count": 16,
    },
    {
        "name": "家族葬ホール各務原",
        "slug": "kazokuso-hall-kakamigahara",
        "venue_type": "private_hall",
        "description": "各務原市の家族葬専用ホール。少人数のお別れに特化した完全貸切型式場。温かみのある内装で、ご家族だけのプライベートな時間を提供。明朗会計のリーズナブルなプランが特長です。",
        "address": "岐阜県各務原市那加前洞新町3-62",
        "prefecture_slug": "gifu",
        "city_slug": "kakamigahara",
        "latitude": 35.400,
        "longitude": 136.845,
        "nearest_station": "名鉄各務原線 新那加駅",
        "station_walk_minutes": 8,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬専用", "1日1組貸切", "明朗会計", "駅近"],
        "operator_name": "各務原葬祭",
        "rating_avg": 4.3,
        "review_count": 11,
    },
    {
        "name": "セレモニーホール那加",
        "slug": "ceremony-naka-kakamigahara",
        "venue_type": "private_hall",
        "description": "各務原市那加エリアの葬儀会館。名鉄新那加駅から車で約5分。中規模の式場を備え、一般葬から家族葬まで対応。バリアフリー設備と広い駐車場を完備した近代的な施設です。",
        "address": "岐阜県各務原市那加桜町3-15",
        "prefecture_slug": "gifu",
        "city_slug": "kakamigahara",
        "latitude": 35.395,
        "longitude": 136.847,
        "nearest_station": "名鉄各務原線 新那加駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000}],
        "features": ["駅近", "家族葬対応", "大規模葬対応", "宿泊可能", "バリアフリー"],
        "operator_name": "那加セレモニー",
        "rating_avg": 4.0,
        "review_count": 15,
    },

    # =============================================
    # 多治見市 (tajimi) — 3件追加
    # =============================================
    {
        "name": "セレモニーホール多治見",
        "slug": "ceremony-hall-tajimi",
        "venue_type": "private_hall",
        "description": "多治見市の民間葬儀会館。JR多治見駅から車で約10分。家族葬から一般葬まで幅広く対応。美濃焼の街・多治見らしい落ち着いた佇まいの式場で、温かみのあるサービスが特長です。",
        "address": "岐阜県多治見市住吉町7-15",
        "prefecture_slug": "gifu",
        "city_slug": "tajimi",
        "latitude": 35.332,
        "longitude": 137.130,
        "nearest_station": "JR中央本線 多治見駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["家族葬対応", "大規模葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "多治見セレモニー",
        "rating_avg": 4.1,
        "review_count": 18,
    },
    {
        "name": "家族葬ホール多治見",
        "slug": "kazokuso-hall-tajimi",
        "venue_type": "private_hall",
        "description": "多治見市の家族葬専用ホール。少人数のお別れに特化した落ち着いた空間。1日1組完全貸切で、ご家族だけの時間をゆっくりと過ごせます。JR多治見駅から車で約8分。24時間対応の相談窓口があります。",
        "address": "岐阜県多治見市太平町5-62",
        "prefecture_slug": "gifu",
        "city_slug": "tajimi",
        "latitude": 35.335,
        "longitude": 137.125,
        "nearest_station": "JR中央本線 多治見駅",
        "station_walk_minutes": 12,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["家族葬専用", "1日1組貸切", "24時間対応", "明朗会計"],
        "operator_name": "多治見葬祭",
        "rating_avg": 4.3,
        "review_count": 13,
    },
    {
        "name": "東濃メモリアルホール",
        "slug": "tono-memorial-tajimi",
        "venue_type": "private_hall",
        "description": "多治見市の中規模葬儀会館。東濃エリアで実績のある葬儀社が運営。通夜から告別式まで対応可能で、家族葬にも最適。清潔感のある近代的な設備と、地域に根ざした丁寧なサービスが特長です。",
        "address": "岐阜県多治見市小名田町小滝5-231",
        "prefecture_slug": "gifu",
        "city_slug": "tajimi",
        "latitude": 35.325,
        "longitude": 137.115,
        "nearest_station": "JR太多線 小泉駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["家族葬対応", "大規模葬対応", "駅近", "駐車場完備"],
        "operator_name": "東濃メモリアル",
        "rating_avg": 4.0,
        "review_count": 16,
    },

    # =============================================
    # 高山市 (takayama) — 3件追加
    # =============================================
    {
        "name": "高山市営斎場",
        "slug": "takayama-shiee-saijo",
        "venue_type": "public_crematorium",
        "description": "高山市が運営する公営火葬場。飛騨高山の山間部に位置し、静かな環境で故人を見送れます。市民は火葬料が優遇されます。火葬施設と待合室を備え、バリアフリー対応の近代的な施設です。",
        "address": "岐阜県高山市西之一色町3-1130",
        "prefecture_slug": "gifu",
        "city_slug": "takayama",
        "latitude": 36.148,
        "longitude": 137.238,
        "nearest_station": "JR高山本線 高山駅",
        "station_walk_minutes": 20,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 72000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "高山市",
        "rating_avg": 3.7,
        "review_count": 18,
    },
    {
        "name": "飛騨メモリアルホール",
        "slug": "hida-memorial-takayama",
        "venue_type": "private_hall",
        "description": "高山市の民間葬儀会館。飛騨高山の伝統と文化に配慮した落ち着いた佇まいの式場。家族葬から一般葬まで幅広く対応し、地元の風習に精通したスタッフが丁寧にサポートします。宿泊施設も完備。",
        "address": "岐阜県高山市花岡町3-88",
        "prefecture_slug": "gifu",
        "city_slug": "takayama",
        "latitude": 36.142,
        "longitude": 137.252,
        "nearest_station": "JR高山本線 高山駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["老舗葬儀社", "家族葬対応", "大規模葬対応", "宿泊可能", "駅近"],
        "operator_name": "飛騨メモリアル",
        "rating_avg": 4.2,
        "review_count": 22,
    },
    {
        "name": "家族葬ホール高山",
        "slug": "kazokuso-hall-takayama",
        "venue_type": "private_hall",
        "description": "高山市の家族葬専用ホール。飛騨の木を活かした温かみのあるインテリアが特長。少人数のお別れに特化し、1日1組貸切でご家族だけの時間を大切にできます。高山の街中からもアクセスしやすい立地。",
        "address": "岐阜県高山市総和町1-5-12",
        "prefecture_slug": "gifu",
        "city_slug": "takayama",
        "latitude": 36.140,
        "longitude": 137.255,
        "nearest_station": "JR高山本線 高山駅",
        "station_walk_minutes": 8,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬専用", "1日1組貸切", "駅近", "24時間対応"],
        "operator_name": "高山葬祭",
        "rating_avg": 4.3,
        "review_count": 12,
    },

    # =============================================
    # その他の市 — 各1〜2件（合計約17件）
    # =============================================

    # 関市 (seki-gifu) — 2件
    {
        "name": "メモワール関斎場",
        "slug": "memoir-seki-gifu",
        "venue_type": "private_hall",
        "description": "メモワールが運営する関市の葬儀斎場。刃物の街・関に位置し、家族葬から一般葬まで対応可能。メモワールの充実したネットワークによる安心のサービス。24時間対応の相談窓口があります。",
        "address": "岐阜県関市山田916-1",
        "prefecture_slug": "gifu",
        "city_slug": "seki-gifu",
        "latitude": 35.488,
        "longitude": 136.918,
        "nearest_station": "長良川鉄道 関駅",
        "station_walk_minutes": 12,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["家族葬対応", "大規模葬対応", "24時間対応", "駐車場完備"],
        "operator_name": "葬儀斎場メモワール",
        "rating_avg": 4.1,
        "review_count": 16,
    },
    {
        "name": "関市斎苑",
        "slug": "seki-shi-saien",
        "venue_type": "public_crematorium",
        "description": "関市が運営する公営火葬場。市民は火葬料が優遇されます。火葬施設と待合室を備え、バリアフリー対応。関市内の静かな環境に位置し、駐車場も完備しています。",
        "address": "岐阜県関市下有知6862-1",
        "prefecture_slug": "gifu",
        "city_slug": "seki-gifu",
        "latitude": 35.482,
        "longitude": 136.900,
        "nearest_station": "長良川鉄道 関駅",
        "station_walk_minutes": 20,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 25,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 72000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "関市",
        "rating_avg": 3.7,
        "review_count": 12,
    },

    # 可児市 (kani) — 2件
    {
        "name": "のうひグリーンホール東可児",
        "slug": "nouhi-green-higashi-kani",
        "venue_type": "private_hall",
        "description": "のうひ葬祭が運営する可児市の葬儀ホール。JR新可児駅から車で約5分。小規模から大規模まで対応可能な式場。地域に根ざした温かみのあるサービスが特長で、経験豊富なスタッフが丁寧にサポートします。",
        "address": "岐阜県可児市広見5-50",
        "prefecture_slug": "gifu",
        "city_slug": "kani",
        "latitude": 35.426,
        "longitude": 137.062,
        "nearest_station": "JR太多線 新可児駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["地域密着", "家族葬対応", "大規模葬対応", "宿泊可能", "駅近"],
        "operator_name": "株式会社濃飛葬祭",
        "rating_avg": 4.2,
        "review_count": 20,
    },
    {
        "name": "家族葬のファミリア可児",
        "slug": "familia-kani",
        "venue_type": "private_hall",
        "description": "のうひ葬祭が展開する可児市の家族葬専用ホール。名鉄日本ライン今渡駅から車で約5分。少人数のお別れに特化した完全貸切型式場で、アットホームな雰囲気が特長。お葬式が52.8万円（税込）からと明朗会計です。",
        "address": "岐阜県可児市今渡2200-3",
        "prefecture_slug": "gifu",
        "city_slug": "kani",
        "latitude": 35.420,
        "longitude": 137.055,
        "nearest_station": "名鉄広見線 日本ライン今渡駅",
        "station_walk_minutes": 8,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬専用", "1日1組貸切", "明朗会計", "駅近"],
        "operator_name": "株式会社濃飛葬祭",
        "rating_avg": 4.4,
        "review_count": 15,
    },

    # 中津川市 (nakatsugawa) — 2件
    {
        "name": "中津川市斎場",
        "slug": "nakatsugawa-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "中津川市が運営する公営火葬場。木曽路の入口・中津川に位置し、自然に囲まれた静かな環境。市民は火葬料が優遇されます。火葬施設と待合室を備え、駐車場を完備しています。",
        "address": "岐阜県中津川市千旦林1468-298",
        "prefecture_slug": "gifu",
        "city_slug": "nakatsugawa",
        "latitude": 35.487,
        "longitude": 137.492,
        "nearest_station": "JR中央本線 中津川駅",
        "station_walk_minutes": 20,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 25,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 70000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "中津川市",
        "rating_avg": 3.7,
        "review_count": 14,
    },
    {
        "name": "セレモニーホール中津川",
        "slug": "ceremony-nakatsugawa",
        "venue_type": "private_hall",
        "description": "中津川市の民間葬儀会館。JR中津川駅から車で約8分。東濃エリアの方々に利用されている中規模施設。家族葬から一般葬まで対応可能で、地域の風習に配慮したサービスを提供しています。",
        "address": "岐阜県中津川市太田町2-6-15",
        "prefecture_slug": "gifu",
        "city_slug": "nakatsugawa",
        "latitude": 35.490,
        "longitude": 137.500,
        "nearest_station": "JR中央本線 中津川駅",
        "station_walk_minutes": 12,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["家族葬対応", "大規模葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "中津川セレモニー",
        "rating_avg": 4.0,
        "review_count": 16,
    },

    # 美濃加茂市 (minokamo) — 2件
    {
        "name": "メモワール美濃加茂斎場",
        "slug": "memoir-minokamo-saijo",
        "venue_type": "private_hall",
        "description": "メモワールが運営する美濃加茂市の葬儀斎場。家族葬から一般葬まで対応可能。メモワールの県下最大のネットワークによる安心のサービス。美濃加茂市・可児市エリアの方々に利用されています。",
        "address": "岐阜県美濃加茂市川合町4-1-37",
        "prefecture_slug": "gifu",
        "city_slug": "minokamo",
        "latitude": 35.440,
        "longitude": 137.015,
        "nearest_station": "JR高山本線 美濃太田駅",
        "station_walk_minutes": 12,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["老舗葬儀社", "家族葬対応", "大規模葬対応", "駐車場完備"],
        "operator_name": "葬儀斎場メモワール",
        "rating_avg": 4.1,
        "review_count": 15,
    },
    {
        "name": "家族葬のファミリア美濃加茂",
        "slug": "familia-minokamo",
        "venue_type": "private_hall",
        "description": "のうひ葬祭が展開する美濃加茂市の家族葬専用ホール。JR美濃太田駅から車で約5分。少人数のお別れに特化した完全貸切型。アットホームな雰囲気の中でご家族だけの時間を過ごせます。明朗会計で安心。",
        "address": "岐阜県美濃加茂市古井町下古井485-1",
        "prefecture_slug": "gifu",
        "city_slug": "minokamo",
        "latitude": 35.435,
        "longitude": 137.028,
        "nearest_station": "JR高山本線 古井駅",
        "station_walk_minutes": 8,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬専用", "1日1組貸切", "明朗会計", "駅近"],
        "operator_name": "株式会社濃飛葬祭",
        "rating_avg": 4.3,
        "review_count": 13,
    },

    # 恵那市 (ena) — 1件
    {
        "name": "恵那市斎場",
        "slug": "ena-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "恵那市が運営する公営火葬場。恵那峡に近い自然豊かな環境。市民は火葬料が優遇されます。火葬施設と待合室を備え、駐車場を完備したバリアフリー対応の施設です。",
        "address": "岐阜県恵那市大井町2726-210",
        "prefecture_slug": "gifu",
        "city_slug": "ena",
        "latitude": 35.449,
        "longitude": 137.412,
        "nearest_station": "JR中央本線 恵那駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 20,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 70000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "恵那市",
        "rating_avg": 3.6,
        "review_count": 10,
    },

    # 羽島市 (hashima) — 1件
    {
        "name": "メモワール羽島斎場",
        "slug": "memoir-hashima",
        "venue_type": "private_hall",
        "description": "メモワールが運営する羽島市の葬儀斎場。新幹線岐阜羽島駅にも近く、遠方からの参列者にも便利な立地。家族葬から一般葬まで対応可能で、メモワールならではの安心のサービスを提供しています。",
        "address": "岐阜県羽島市竹鼻町丸の内6-35",
        "prefecture_slug": "gifu",
        "city_slug": "hashima",
        "latitude": 35.318,
        "longitude": 136.698,
        "nearest_station": "名鉄竹鼻線 竹鼻駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["駅近", "家族葬対応", "新幹線駅近く", "駐車場完備"],
        "operator_name": "葬儀斎場メモワール",
        "rating_avg": 4.1,
        "review_count": 14,
    },

    # 瑞浪市 (mizunami) — 1件
    {
        "name": "瑞浪市斎場",
        "slug": "mizunami-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "瑞浪市が運営する公営火葬場。化石の町・瑞浪に位置する静かな環境の施設。市民は火葬料が優遇されます。火葬施設と待合室を備え、駐車場を完備しています。",
        "address": "岐阜県瑞浪市土岐町7525-1",
        "prefecture_slug": "gifu",
        "city_slug": "mizunami",
        "latitude": 35.362,
        "longitude": 137.253,
        "nearest_station": "JR中央本線 瑞浪駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 20,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 68000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "瑞浪市",
        "rating_avg": 3.6,
        "review_count": 9,
    },

    # 土岐市 (toki) — 1件
    {
        "name": "土岐市斎場",
        "slug": "toki-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "土岐市が運営する公営火葬場。美濃焼の産地・土岐に位置する静かな環境。市民は火葬料が優遇されます。火葬施設と待合室を備え、バリアフリー対応の近代的な施設です。",
        "address": "岐阜県土岐市泉町定林寺473",
        "prefecture_slug": "gifu",
        "city_slug": "toki",
        "latitude": 35.355,
        "longitude": 137.178,
        "nearest_station": "JR中央本線 土岐市駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 20,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 68000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "土岐市",
        "rating_avg": 3.7,
        "review_count": 10,
    },

    # 瑞穂市 (mizuho) — 1件
    {
        "name": "セレモニーホール瑞穂",
        "slug": "ceremony-mizuho",
        "venue_type": "private_hall",
        "description": "瑞穂市の民間葬儀会館。岐阜市と大垣市の間に位置するベッドタウン・瑞穂市で、家族葬に最適なホール。1日1組貸切で落ち着いた雰囲気。JR穂積駅から車で約5分の好立地です。",
        "address": "岐阜県瑞穂市穂積1012-2",
        "prefecture_slug": "gifu",
        "city_slug": "mizuho",
        "latitude": 35.390,
        "longitude": 136.680,
        "nearest_station": "JR東海道本線 穂積駅",
        "station_walk_minutes": 8,
        "capacity_max": 35,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 18,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬対応", "1日1組貸切", "駅近", "24時間対応"],
        "operator_name": "瑞穂セレモニー",
        "rating_avg": 4.1,
        "review_count": 11,
    },

    # 山県市 (yamagata-gifu) — 1件
    {
        "name": "メモワール山県斎場",
        "slug": "memoir-yamagata-gifu",
        "venue_type": "private_hall",
        "description": "メモワールが運営する山県市の葬儀斎場。岐阜市北部に隣接する山県市で、家族葬を中心にサービスを提供。メモワールの充実したネットワークによる安心のサポート。静かな環境で故人を偲べます。",
        "address": "岐阜県山県市高木1000-1",
        "prefecture_slug": "gifu",
        "city_slug": "yamagata-gifu",
        "latitude": 35.490,
        "longitude": 136.780,
        "nearest_station": "JR高山本線 岐阜駅",
        "station_walk_minutes": 30,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["家族葬対応", "駐車場完備", "24時間対応"],
        "operator_name": "葬儀斎場メモワール",
        "rating_avg": 4.0,
        "review_count": 10,
    },

    # 本巣市 (motosu) — 1件
    {
        "name": "家族葬ホール華園本巣",
        "slug": "kazoku-hall-hanaen-motosu",
        "venue_type": "private_hall",
        "description": "本巣市の家族葬専用ホール。少人数のお別れに特化した落ち着いた空間。岐阜市北西部に隣接する本巣市で、温かみのあるサービスを提供。1日1組貸切でご家族だけの時間を大切にできます。",
        "address": "岐阜県本巣市三橋2-25",
        "prefecture_slug": "gifu",
        "city_slug": "motosu",
        "latitude": 35.455,
        "longitude": 136.682,
        "nearest_station": "樽見鉄道 本巣駅",
        "station_walk_minutes": 10,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬専用", "1日1組貸切", "駅近", "24時間対応"],
        "operator_name": "華園",
        "rating_avg": 4.2,
        "review_count": 9,
    },

    # 郡上市 (gujo) — 1件
    {
        "name": "郡上市営斎場",
        "slug": "gujo-shiee-saijo",
        "venue_type": "public_crematorium",
        "description": "郡上市が運営する公営火葬場。郡上おどりで有名な郡上八幡に近い自然豊かな環境。市民は火葬料が優遇されます。火葬施設と待合室を備え、山間部ならではの静かな環境で故人を見送れます。",
        "address": "岐阜県郡上市八幡町小野5-6-1",
        "prefecture_slug": "gifu",
        "city_slug": "gujo",
        "latitude": 35.748,
        "longitude": 136.960,
        "nearest_station": "長良川鉄道 郡上八幡駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 20,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 68000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "郡上市",
        "rating_avg": 3.6,
        "review_count": 8,
    },

    # 海津市 (kaizu) — 1件
    {
        "name": "海津市斎場",
        "slug": "kaizu-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "海津市が運営する公営火葬場。木曽三川の合流点に近い南濃地域に位置。市民は火葬料が優遇されます。火葬施設と待合室を備え、穏やかな環境で故人を見送れる施設です。",
        "address": "岐阜県海津市平田町三郷2330",
        "prefecture_slug": "gifu",
        "city_slug": "kaizu",
        "latitude": 35.225,
        "longitude": 136.635,
        "nearest_station": "養老鉄道 石津駅",
        "station_walk_minutes": 20,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 20,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 68000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "海津市",
        "rating_avg": 3.5,
        "review_count": 7,
    },
]

def insert_batch(batch, batch_num, total_batches):
    data = json.dumps(batch, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(SUPABASE_URL, data=data, headers=HEADERS, method="POST")
    try:
        with urllib.request.urlopen(req) as resp:
            print(f"  バッチ {batch_num}/{total_batches}: HTTP {resp.status} OK ({len(batch)}件)")
            return True
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")
        print(f"  バッチ {batch_num}/{total_batches}: HTTP {e.code} ERROR")
        print(f"  レスポンス: {body[:500]}")
        return False

def main():
    print(f"=== 岐阜県 斎場データ追加 (batch2) ===")
    print(f"合計: {len(venues)}件")
    print()

    batch_size = 10
    total_batches = (len(venues) + batch_size - 1) // batch_size
    success_count = 0
    fail_count = 0

    for i in range(0, len(venues), batch_size):
        batch = venues[i:i + batch_size]
        batch_num = i // batch_size + 1
        ok = insert_batch(batch, batch_num, total_batches)
        if ok:
            success_count += len(batch)
        else:
            fail_count += len(batch)
        time.sleep(0.5)

    print()
    print(f"=== 完了 ===")
    print(f"成功: {success_count}件 / 失敗: {fail_count}件")

if __name__ == "__main__":
    main()
