#!/usr/bin/env python3
"""
北海道の斎場データ バッチ1: 札幌市 前半40件
"""
import json
import subprocess
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

venues = [
    # =============================================
    # 札幌市中央区 (10件)
    # =============================================
    {
        "name": "札幌市里塚斎場",
        "slug": "hokkaido-sapporo-satozuka-saijo",
        "venue_type": "public_crematorium",
        "description": "札幌市が運営する公営の総合斎場。火葬棟と式場を備え、通夜から火葬まで同一敷地内で執り行えます。札幌市民は火葬料無料。広い駐車場を完備し、大規模な葬儀にも対応可能です。清田区里塚に位置し、緑に囲まれた静かな環境です。",
        "address": "北海道札幌市清田区里塚507",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0047,
        "longitude": 141.4222,
        "nearest_station": "地下鉄東西線 大谷地駅",
        "station_walk_minutes": 30,
        "capacity_max": 120,
        "hall_count": 4,
        "has_crematorium": True,
        "parking_count": 250,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True, "売店": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応", "バリアフリー"],
        "operator_name": "札幌市",
        "rating_avg": 4.0,
        "review_count": 87,
    },
    {
        "name": "札幌市山口斎場",
        "slug": "hokkaido-sapporo-yamaguchi-saijo",
        "venue_type": "public_crematorium",
        "description": "札幌市西部に位置する公営火葬場。手稲山の麓にあり、自然に囲まれた静かな環境。火葬施設のみの運営で、式場は併設されていません。札幌市民は火葬料無料で利用できます。",
        "address": "北海道札幌市手稲区手稲山口553",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1167,
        "longitude": 141.2167,
        "nearest_station": "JR函館本線 手稲駅",
        "station_walk_minutes": 30,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 100,
        "facilities": {"霊安室": True, "駐車場": True, "控室": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "札幌市",
        "rating_avg": 3.8,
        "review_count": 42,
    },
    {
        "name": "やわらぎ斎場 中央",
        "slug": "hokkaido-yawaragi-chuo",
        "venue_type": "private_hall",
        "description": "北海道最大手の葬儀社やわらぎが運営する札幌中央区のフラッグシップ斎場。地下鉄南北線「すすきの駅」から徒歩5分と抜群のアクセス。少人数の家族葬から200名規模の一般葬まで幅広く対応。24時間365日相談受付。",
        "address": "北海道札幌市中央区南4条西8丁目2-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0550,
        "longitude": 141.3450,
        "nearest_station": "地下鉄南北線 すすきの駅",
        "station_walk_minutes": 5,
        "capacity_max": 200,
        "hall_count": 5,
        "has_crematorium": False,
        "parking_count": 60,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True, "シャワー室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 698000}],
        "features": ["駅近", "大規模葬対応", "家族葬対応", "宿泊可能", "24時間対応"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.3,
        "review_count": 124,
    },
    {
        "name": "北海斎場 大通",
        "slug": "hokkaido-hokkai-odori",
        "venue_type": "private_hall",
        "description": "創業50年の実績を持つ北海斎場の本店。大通公園に近い好立地で、交通アクセスも抜群です。格式ある式場でありながら、家族葬にも柔軟に対応。熟練のスタッフが心のこもったお見送りをサポートします。",
        "address": "北海道札幌市中央区大通西18丁目1-28",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0580,
        "longitude": 141.3310,
        "nearest_station": "地下鉄東西線 西18丁目駅",
        "station_walk_minutes": 3,
        "capacity_max": 150,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 418000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 728000}],
        "features": ["駅近", "老舗葬儀社", "大規模葬対応", "家族葬対応", "宿泊可能"],
        "operator_name": "北海斎場株式会社",
        "rating_avg": 4.2,
        "review_count": 98,
    },
    {
        "name": "シティホール札幌中央",
        "slug": "hokkaido-cityhall-sapporo-chuo",
        "venue_type": "private_hall",
        "description": "全国展開するシティホールグループの札幌中央店。地下鉄「中島公園駅」から徒歩3分の立地。モダンで洗練された空間設計が特長。1日1組貸切で、プライベートなお別れの場を提供します。",
        "address": "北海道札幌市中央区南9条西4丁目1-12",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0490,
        "longitude": 141.3540,
        "nearest_station": "地下鉄南北線 中島公園駅",
        "station_walk_minutes": 3,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 128000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 278000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 438000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 658000}],
        "features": ["駅近", "1日1組貸切", "家族葬対応", "モダンな内装"],
        "operator_name": "株式会社シティホール",
        "rating_avg": 4.4,
        "review_count": 67,
    },
    {
        "name": "むすびす札幌円山",
        "slug": "hokkaido-musubisu-maruyama",
        "venue_type": "private_hall",
        "description": "むすびす（旧アーバンフューネス）が運営する家族葬専用ホール。札幌の高級住宅街・円山エリアに位置し、上質で温かみのある空間が特長。故人の人柄を表現するオーダーメイドの葬儀を提案します。",
        "address": "北海道札幌市中央区北3条西25丁目2-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0630,
        "longitude": 141.3240,
        "nearest_station": "地下鉄東西線 円山公園駅",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "シャワー室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 148000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 468000}],
        "features": ["家族葬専用", "オーダーメイド葬", "駅近", "上質な空間"],
        "operator_name": "むすびす株式会社",
        "rating_avg": 4.5,
        "review_count": 45,
    },
    {
        "name": "メモリアルホール中央",
        "slug": "hokkaido-memorial-chuo",
        "venue_type": "private_hall",
        "description": "札幌中央区の歴史ある葬儀場。豊水すすきのエリアに位置し、地下鉄3路線が利用可能な好アクセス。伝統的な和室式場と現代的な洋室式場の両方を備え、幅広いニーズに対応します。",
        "address": "北海道札幌市中央区南7条西1丁目15",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0520,
        "longitude": 141.3560,
        "nearest_station": "地下鉄東豊線 豊水すすきの駅",
        "station_walk_minutes": 4,
        "capacity_max": 100,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "和室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["駅近", "和室あり", "家族葬対応", "大規模葬対応"],
        "operator_name": "メモリアルサービス北海道",
        "rating_avg": 4.1,
        "review_count": 76,
    },
    {
        "name": "中央寺会館",
        "slug": "hokkaido-chuoji-kaikan",
        "venue_type": "temple_hall",
        "description": "札幌中央区にある浄土真宗の寺院式場。古くから地域に根ざし、伝統的な仏式葬儀を執り行えます。宗派を問わず利用可能。落ち着いた本堂で厳粛なお別れの時間を提供します。",
        "address": "北海道札幌市中央区南6条西2丁目4-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0530,
        "longitude": 141.3530,
        "nearest_station": "地下鉄南北線 すすきの駅",
        "station_walk_minutes": 6,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "駐車場": True, "控室": True, "和室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["寺院式場", "宗派不問", "伝統的な雰囲気", "駅近"],
        "operator_name": "中央寺",
        "rating_avg": 4.0,
        "review_count": 23,
    },
    {
        "name": "コープ葬祭 大通ホール",
        "slug": "hokkaido-coop-odori",
        "venue_type": "private_hall",
        "description": "コープさっぽろが運営する葬祭ホール。組合員価格でリーズナブルに利用可能。大通エリアに位置し交通アクセス良好。事前相談や見積もりが無料で、明瞭な価格設定が好評です。",
        "address": "北海道札幌市中央区大通西12丁目4-78",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0590,
        "longitude": 141.3370,
        "nearest_station": "地下鉄東西線 西11丁目駅",
        "station_walk_minutes": 4,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["組合員割引", "明瞭価格", "駅近", "家族葬対応"],
        "operator_name": "コープさっぽろ",
        "rating_avg": 4.1,
        "review_count": 54,
    },
    {
        "name": "ベルコ札幌中央シティホール",
        "slug": "hokkaido-bellco-chuo-city",
        "venue_type": "private_hall",
        "description": "全国チェーンのベルコが運営する札幌中央区のシティホール。互助会会員制度で計画的な葬儀費用の積立が可能。充実した設備と経験豊富なスタッフが丁寧にサポートします。",
        "address": "北海道札幌市中央区南2条西10丁目5-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0570,
        "longitude": 141.3400,
        "nearest_station": "地下鉄東西線 西11丁目駅",
        "station_walk_minutes": 5,
        "capacity_max": 100,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 408000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 648000}],
        "features": ["互助会対応", "宿泊可能", "家族葬対応", "大規模葬対応"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 89,
    },
    # =============================================
    # 札幌市北区 (8件)
    # =============================================
    {
        "name": "やわらぎ斎場 北",
        "slug": "hokkaido-yawaragi-kita",
        "venue_type": "private_hall",
        "description": "やわらぎが運営する札幌北区の斎場。地下鉄南北線「北24条駅」から徒歩8分。家族葬に特化したアットホームな空間で、1日1組貸切対応。24時間365日、電話1本で搬送から葬儀まで対応します。",
        "address": "北海道札幌市北区北24条西6丁目2-15",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0860,
        "longitude": 141.3420,
        "nearest_station": "地下鉄南北線 北24条駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["家族葬対応", "1日1組貸切", "宿泊可能", "24時間対応"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.3,
        "review_count": 78,
    },
    {
        "name": "ベルコ札幌北シティホール",
        "slug": "hokkaido-bellco-kita-city",
        "venue_type": "private_hall",
        "description": "ベルコが運営する札幌北区の大型斎場。新琴似エリアに位置し、広い駐車場を完備。100名規模の一般葬にも対応可能な大ホールと、家族葬向けの小ホールを備えています。",
        "address": "北海道札幌市北区新琴似7条3丁目1-22",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1110,
        "longitude": 141.3360,
        "nearest_station": "JR学園都市線 新琴似駅",
        "station_walk_minutes": 10,
        "capacity_max": 100,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000}],
        "features": ["大規模葬対応", "家族葬対応", "駐車場完備", "互助会対応"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 56,
    },
    {
        "name": "メモリアルホール麻生",
        "slug": "hokkaido-memorial-asabu",
        "venue_type": "private_hall",
        "description": "札幌北区麻生エリアの葬儀ホール。地下鉄南北線「麻生駅」から徒歩6分の好立地。モダンな内装で明るく温かみのある空間。家族葬を中心に丁寧なサービスを提供しています。",
        "address": "北海道札幌市北区北40条西5丁目1-10",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0970,
        "longitude": 141.3430,
        "nearest_station": "地下鉄南北線 麻生駅",
        "station_walk_minutes": 6,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["駅近", "家族葬対応", "モダンな内装", "バリアフリー"],
        "operator_name": "メモリアルサービス北海道",
        "rating_avg": 4.2,
        "review_count": 43,
    },
    {
        "name": "北海斎場 北",
        "slug": "hokkaido-hokkai-kita",
        "venue_type": "private_hall",
        "description": "北海斎場の北区支店。JR学園都市線沿線に位置し、北区・石狩方面からのアクセスが便利。落ち着いた和モダンの内装で、伝統的な葬儀から現代的な家族葬まで対応します。",
        "address": "北海道札幌市北区北32条西2丁目3-8",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0930,
        "longitude": 141.3500,
        "nearest_station": "地下鉄南北線 北34条駅",
        "station_walk_minutes": 7,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "和室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 628000}],
        "features": ["和モダン", "家族葬対応", "駐車場完備", "老舗葬儀社"],
        "operator_name": "北海斎場株式会社",
        "rating_avg": 4.1,
        "review_count": 52,
    },
    {
        "name": "家族葬のウィズハウス 北",
        "slug": "hokkaido-withhouse-kita",
        "venue_type": "private_hall",
        "description": "ウィズハウスが運営する家族葬専用ホール。北区篠路エリアの閑静な住宅地に位置し、1日1組貸切のプライベート空間。自宅のようにくつろげる居間スタイルの式場が特長です。",
        "address": "北海道札幌市北区篠路3条7丁目5-15",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1290,
        "longitude": 141.3580,
        "nearest_station": "JR学園都市線 篠路駅",
        "station_walk_minutes": 8,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "キッチン": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}],
        "features": ["家族葬専用", "1日1組貸切", "居間スタイル", "バリアフリー"],
        "operator_name": "株式会社ウィズハウス",
        "rating_avg": 4.4,
        "review_count": 38,
    },
    {
        "name": "コープ葬祭 北ホール",
        "slug": "hokkaido-coop-kita",
        "venue_type": "private_hall",
        "description": "コープさっぽろが運営する北区の葬祭ホール。組合員は割引価格で利用可能。明瞭な料金体系と手厚いサポートが好評。屯田地区に位置し、広い駐車場を完備しています。",
        "address": "北海道札幌市北区屯田6条3丁目2-18",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1200,
        "longitude": 141.3280,
        "nearest_station": "地下鉄南北線 麻生駅",
        "station_walk_minutes": 20,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["組合員割引", "明瞭価格", "駐車場完備", "家族葬対応"],
        "operator_name": "コープさっぽろ",
        "rating_avg": 4.0,
        "review_count": 41,
    },
    {
        "name": "正福寺会館",
        "slug": "hokkaido-shofukuji-kaikan",
        "venue_type": "temple_hall",
        "description": "札幌北区にある曹洞宗の寺院式場。歴史ある本堂で厳粛な仏式葬儀を執り行えます。宗派を問わず利用可能で、僧侶の手配もサポート。地域密着の温かいサービスが特長です。",
        "address": "北海道札幌市北区北28条西12丁目3-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0900,
        "longitude": 141.3280,
        "nearest_station": "地下鉄南北線 北24条駅",
        "station_walk_minutes": 15,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "駐車場": True, "控室": True, "和室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 478000}],
        "features": ["寺院式場", "宗派不問", "伝統的な雰囲気", "地域密着"],
        "operator_name": "正福寺",
        "rating_avg": 3.9,
        "review_count": 18,
    },
    {
        "name": "セレモニーホール太平",
        "slug": "hokkaido-ceremony-taihei",
        "venue_type": "private_hall",
        "description": "札幌北区太平エリアの地域密着型葬儀ホール。JR学園都市線「太平駅」から徒歩10分。少人数の家族葬に特化し、温かみのある木のぬくもりを感じる内装が特長です。",
        "address": "北海道札幌市北区太平6条5丁目1-7",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1180,
        "longitude": 141.3700,
        "nearest_station": "JR学園都市線 太平駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専用", "木の温もり", "駅近", "地域密着"],
        "operator_name": "太平セレモニー",
        "rating_avg": 4.2,
        "review_count": 27,
    },
    # =============================================
    # 札幌市東区 (8件)
    # =============================================
    {
        "name": "やわらぎ斎場 東",
        "slug": "hokkaido-yawaragi-higashi",
        "venue_type": "private_hall",
        "description": "やわらぎが運営する東区の斎場。地下鉄東豊線「元町駅」から徒歩7分。明るく清潔感のある空間で、家族葬から一般葬まで幅広く対応。スタッフの対応が丁寧と評判です。",
        "address": "北海道札幌市東区北23条東16丁目1-8",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0860,
        "longitude": 141.3750,
        "nearest_station": "地下鉄東豊線 元町駅",
        "station_walk_minutes": 7,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["家族葬対応", "宿泊可能", "24時間対応", "バリアフリー"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.2,
        "review_count": 63,
    },
    {
        "name": "ベルコ札幌東シティホール",
        "slug": "hokkaido-bellco-higashi-city",
        "venue_type": "private_hall",
        "description": "ベルコが運営する東区の大型葬儀ホール。東苗穂エリアに位置し、広い敷地に充実した設備を備えています。150名規模の式場があり、社葬や団体葬にも対応可能です。",
        "address": "北海道札幌市東区東苗穂8条2丁目3-15",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0950,
        "longitude": 141.4020,
        "nearest_station": "地下鉄東豊線 環状通東駅",
        "station_walk_minutes": 20,
        "capacity_max": 150,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 80,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 648000}],
        "features": ["大規模葬対応", "駐車場完備", "互助会対応", "宿泊可能"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 71,
    },
    {
        "name": "シティホール札幌東",
        "slug": "hokkaido-cityhall-sapporo-higashi",
        "venue_type": "private_hall",
        "description": "シティホールグループの札幌東区店。北光線沿いに位置し、わかりやすいアクセス。花に囲まれた温かみのある式場で、故人らしいお別れをプロデュースします。",
        "address": "北海道札幌市東区北15条東7丁目1-25",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0790,
        "longitude": 141.3650,
        "nearest_station": "地下鉄東豊線 東区役所前駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 418000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 638000}],
        "features": ["花祭壇", "家族葬対応", "1日1組貸切", "バリアフリー"],
        "operator_name": "株式会社シティホール",
        "rating_avg": 4.3,
        "review_count": 48,
    },
    {
        "name": "札幌東セレモニーホール",
        "slug": "hokkaido-sapporo-higashi-ceremony",
        "venue_type": "private_hall",
        "description": "東区伏古エリアの地域密着型セレモニーホール。静かな住宅街に位置し、落ち着いた雰囲気のなかでお別れの時間を過ごせます。リーズナブルな価格設定が好評。",
        "address": "北海道札幌市東区伏古10条3丁目2-12",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0880,
        "longitude": 141.3850,
        "nearest_station": "地下鉄東豊線 環状通東駅",
        "station_walk_minutes": 15,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["リーズナブル", "家族葬対応", "地域密着", "バリアフリー"],
        "operator_name": "札幌東セレモニー",
        "rating_avg": 4.1,
        "review_count": 34,
    },
    {
        "name": "家族葬のウィズハウス 東",
        "slug": "hokkaido-withhouse-higashi",
        "venue_type": "private_hall",
        "description": "ウィズハウスの東区店。自宅のような温かみのある空間で、ゆっくりとお別れの時間を過ごせます。1日1組完全貸切で、故人との最後の時間を大切にできます。",
        "address": "北海道札幌市東区北20条東1丁目3-8",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0840,
        "longitude": 141.3560,
        "nearest_station": "地下鉄南北線 北18条駅",
        "station_walk_minutes": 12,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "キッチン": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["家族葬専用", "1日1組貸切", "居間スタイル", "24時間対応"],
        "operator_name": "株式会社ウィズハウス",
        "rating_avg": 4.5,
        "review_count": 29,
    },
    {
        "name": "コープ葬祭 東ホール",
        "slug": "hokkaido-coop-higashi",
        "venue_type": "private_hall",
        "description": "コープさっぽろの東区葬祭ホール。北13条東エリアに位置し、地下鉄東豊線からのアクセスが便利。組合員割引でリーズナブルに利用でき、事前相談も随時受付しています。",
        "address": "北海道札幌市東区北13条東8丁目1-20",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0770,
        "longitude": 141.3680,
        "nearest_station": "地下鉄東豊線 東区役所前駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["組合員割引", "明瞭価格", "駅近", "家族葬対応"],
        "operator_name": "コープさっぽろ",
        "rating_avg": 4.0,
        "review_count": 37,
    },
    {
        "name": "東栄寺ホール",
        "slug": "hokkaido-toeiji-hall",
        "venue_type": "temple_hall",
        "description": "東区にある真言宗の寺院式場。伝統ある本堂と現代的な設備を兼ね備えた式場です。宗派を問わず利用でき、僧侶の手配もサポート。歴史ある環境で厳粛なお別れを。",
        "address": "北海道札幌市東区北16条東10丁目2-5",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0800,
        "longitude": 141.3720,
        "nearest_station": "地下鉄東豊線 環状通東駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "駐車場": True, "控室": True, "和室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 488000}],
        "features": ["寺院式場", "宗派不問", "伝統的な雰囲気"],
        "operator_name": "東栄寺",
        "rating_avg": 3.9,
        "review_count": 15,
    },
    {
        "name": "メモリアルホール丘珠",
        "slug": "hokkaido-memorial-okadama",
        "venue_type": "private_hall",
        "description": "札幌東区丘珠エリアの葬儀ホール。丘珠空港に近い静かな立地。広い駐車場を備え、車でのアクセスが便利です。アットホームな雰囲気で、少人数の家族葬に最適。",
        "address": "北海道札幌市東区丘珠町183-5",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1050,
        "longitude": 141.3900,
        "nearest_station": "地下鉄東豊線 栄町駅",
        "station_walk_minutes": 20,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬対応", "駐車場完備", "アットホーム"],
        "operator_name": "メモリアルサービス北海道",
        "rating_avg": 4.0,
        "review_count": 22,
    },
    # =============================================
    # 札幌市白石区 (8件)
    # =============================================
    {
        "name": "やわらぎ斎場 白石",
        "slug": "hokkaido-yawaragi-shiroishi",
        "venue_type": "private_hall",
        "description": "やわらぎが運営する白石区の斎場。地下鉄東西線「白石駅」から徒歩6分の好立地。清潔感のあるモダンな空間で、家族葬に最適。経験豊富なスタッフが細やかなサポートを提供します。",
        "address": "北海道札幌市白石区本郷通6丁目南1-15",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0530,
        "longitude": 141.3930,
        "nearest_station": "地下鉄東西線 白石駅",
        "station_walk_minutes": 6,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["駅近", "家族葬対応", "宿泊可能", "24時間対応"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.2,
        "review_count": 58,
    },
    {
        "name": "ベルコ白石シティホール",
        "slug": "hokkaido-bellco-shiroishi",
        "venue_type": "private_hall",
        "description": "ベルコの白石区斎場。南郷通沿いに位置し、地下鉄東西線「南郷7丁目駅」からのアクセスが便利。大小2つのホールを備え、家族葬から一般葬まで対応可能です。",
        "address": "北海道札幌市白石区南郷通8丁目南5-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0440,
        "longitude": 141.3980,
        "nearest_station": "地下鉄東西線 南郷7丁目駅",
        "station_walk_minutes": 5,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 628000}],
        "features": ["駅近", "互助会対応", "家族葬対応", "駐車場完備"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.1,
        "review_count": 64,
    },
    {
        "name": "北海斎場 白石",
        "slug": "hokkaido-hokkai-shiroishi",
        "venue_type": "private_hall",
        "description": "北海斎場の白石支店。菊水エリアに位置し、地下鉄「菊水駅」から徒歩8分。伝統と格式を重視しながらも、現代的なニーズに応える柔軟なサービスを提供しています。",
        "address": "北海道札幌市白石区菊水5条3丁目1-12",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0510,
        "longitude": 141.3780,
        "nearest_station": "地下鉄東西線 菊水駅",
        "station_walk_minutes": 8,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "和室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000}],
        "features": ["駅近", "老舗葬儀社", "和室あり", "家族葬対応"],
        "operator_name": "北海斎場株式会社",
        "rating_avg": 4.1,
        "review_count": 47,
    },
    {
        "name": "家族葬のウィズハウス 白石",
        "slug": "hokkaido-withhouse-shiroishi",
        "venue_type": "private_hall",
        "description": "ウィズハウスの白石区店。東札幌エリアに位置し、自宅のようにくつろげる居間スタイルの式場。少人数で故人との最後の時間を大切にしたい方に最適な空間です。",
        "address": "北海道札幌市白石区東札幌4条2丁目5-10",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0470,
        "longitude": 141.3860,
        "nearest_station": "地下鉄東西線 東札幌駅",
        "station_walk_minutes": 5,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "キッチン": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["家族葬専用", "1日1組貸切", "駅近", "居間スタイル"],
        "operator_name": "株式会社ウィズハウス",
        "rating_avg": 4.4,
        "review_count": 33,
    },
    {
        "name": "白石セレモニーホール南郷",
        "slug": "hokkaido-shiroishi-nango-ceremony",
        "venue_type": "private_hall",
        "description": "白石区南郷エリアのセレモニーホール。地下鉄「南郷13丁目駅」から徒歩5分。リーズナブルな価格設定で地域に愛される斎場です。家族葬から一般葬まで対応。",
        "address": "北海道札幌市白石区南郷通13丁目北3-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0450,
        "longitude": 141.4080,
        "nearest_station": "地下鉄東西線 南郷13丁目駅",
        "station_walk_minutes": 5,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000}],
        "features": ["駅近", "リーズナブル", "家族葬対応", "地域密着"],
        "operator_name": "南郷セレモニー",
        "rating_avg": 4.0,
        "review_count": 31,
    },
    {
        "name": "メモリアルホール白石",
        "slug": "hokkaido-memorial-shiroishi",
        "venue_type": "private_hall",
        "description": "白石区本通エリアのメモリアルホール。広い駐車場と充実した設備を備え、100名規模の葬儀にも対応可能。バリアフリー設計で、ご高齢の参列者にも安心です。",
        "address": "北海道札幌市白石区本通14丁目南2-8",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0420,
        "longitude": 141.4130,
        "nearest_station": "地下鉄東西線 南郷13丁目駅",
        "station_walk_minutes": 10,
        "capacity_max": 100,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 45,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 578000}],
        "features": ["大規模葬対応", "駐車場完備", "バリアフリー", "家族葬対応"],
        "operator_name": "メモリアルサービス北海道",
        "rating_avg": 4.0,
        "review_count": 42,
    },
    {
        "name": "白石公民館ホール",
        "slug": "hokkaido-shiroishi-kouminkan",
        "venue_type": "public_facility",
        "description": "白石区の公共施設を利用した葬儀会場。公民館の大ホールを葬儀用に開放しており、リーズナブルに利用可能。設備はシンプルですが、低予算での葬儀を希望する方に好評です。",
        "address": "北海道札幌市白石区南郷通1丁目南8-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0500,
        "longitude": 141.3900,
        "nearest_station": "地下鉄東西線 白石駅",
        "station_walk_minutes": 7,
        "capacity_max": 80,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 248000}],
        "features": ["公共施設", "低価格", "駅近"],
        "operator_name": "札幌市白石区",
        "rating_avg": 3.6,
        "review_count": 14,
    },
    {
        "name": "光明寺会館",
        "slug": "hokkaido-komyoji-shiroishi",
        "venue_type": "temple_hall",
        "description": "白石区にある浄土宗の寺院式場。歴史ある本堂で静かにお別れの時間を過ごせます。宗派を問わず利用可能。住職による読経と丁寧なおもてなしが特長です。",
        "address": "北海道札幌市白石区栄通18丁目5-3",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0380,
        "longitude": 141.4150,
        "nearest_station": "地下鉄東西線 南郷18丁目駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "駐車場": True, "控室": True, "和室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 468000}],
        "features": ["寺院式場", "宗派不問", "伝統的な雰囲気"],
        "operator_name": "光明寺",
        "rating_avg": 3.8,
        "review_count": 11,
    },
    # =============================================
    # 札幌市豊平区 (8件)
    # =============================================
    {
        "name": "やわらぎ斎場 豊平",
        "slug": "hokkaido-yawaragi-toyohira",
        "venue_type": "private_hall",
        "description": "やわらぎが運営する豊平区の斎場。地下鉄東豊線「豊平公園駅」から徒歩5分。開放的なデザインの式場で、花に囲まれたお別れの空間を提供。家族葬に人気の斎場です。",
        "address": "北海道札幌市豊平区豊平6条6丁目5-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0420,
        "longitude": 141.3750,
        "nearest_station": "地下鉄東豊線 豊平公園駅",
        "station_walk_minutes": 5,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["駅近", "花祭壇", "家族葬対応", "宿泊可能"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.3,
        "review_count": 72,
    },
    {
        "name": "ベルコ豊平シティホール",
        "slug": "hokkaido-bellco-toyohira",
        "venue_type": "private_hall",
        "description": "ベルコの豊平区斎場。月寒エリアに位置し、広い敷地と充実した設備を備えています。大小2つのホールで家族葬から一般葬まで対応。36号線沿いでアクセスも便利です。",
        "address": "北海道札幌市豊平区月寒中央通7丁目3-12",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0300,
        "longitude": 141.3980,
        "nearest_station": "地下鉄東豊線 月寒中央駅",
        "station_walk_minutes": 7,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 628000}],
        "features": ["互助会対応", "駐車場完備", "家族葬対応", "バリアフリー"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 55,
    },
    {
        "name": "シティホール平岸",
        "slug": "hokkaido-cityhall-hiragishi",
        "venue_type": "private_hall",
        "description": "シティホールグループの平岸店。地下鉄南北線「平岸駅」から徒歩5分の好立地。コンパクトながら設備が充実した式場で、家族葬に特化したサービスを提供しています。",
        "address": "北海道札幌市豊平区平岸3条7丁目1-25",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0330,
        "longitude": 141.3680,
        "nearest_station": "地下鉄南北線 平岸駅",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 418000}],
        "features": ["駅近", "家族葬専用", "1日1組貸切"],
        "operator_name": "株式会社シティホール",
        "rating_avg": 4.3,
        "review_count": 39,
    },
    {
        "name": "家族葬のウィズハウス 豊平",
        "slug": "hokkaido-withhouse-toyohira",
        "venue_type": "private_hall",
        "description": "ウィズハウスの豊平区店。美園エリアの静かな住宅街に位置。自宅のようなリビングスタイルの式場で、故人との最後の時間を大切に過ごせます。",
        "address": "北海道札幌市豊平区美園8条5丁目3-8",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0380,
        "longitude": 141.3880,
        "nearest_station": "地下鉄東豊線 美園駅",
        "station_walk_minutes": 6,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "キッチン": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["家族葬専用", "1日1組貸切", "居間スタイル", "駅近"],
        "operator_name": "株式会社ウィズハウス",
        "rating_avg": 4.5,
        "review_count": 31,
    },
    {
        "name": "メモリアルホール月寒",
        "slug": "hokkaido-memorial-tsukisamu",
        "venue_type": "private_hall",
        "description": "月寒エリアの大型メモリアルホール。36号線沿いの立地で車でのアクセスが便利。3つのホールを備え、家族葬から大規模葬まで対応。充実した設備とスタッフの対応が好評です。",
        "address": "北海道札幌市豊平区月寒東3条11丁目2-5",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0260,
        "longitude": 141.4100,
        "nearest_station": "地下鉄東豊線 福住駅",
        "station_walk_minutes": 12,
        "capacity_max": 120,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 60,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["大規模葬対応", "駐車場完備", "宿泊可能", "バリアフリー"],
        "operator_name": "メモリアルサービス北海道",
        "rating_avg": 4.1,
        "review_count": 61,
    },
    {
        "name": "コープ葬祭 豊平ホール",
        "slug": "hokkaido-coop-toyohira",
        "venue_type": "private_hall",
        "description": "コープさっぽろの豊平区葬祭ホール。西岡エリアに位置し、広い駐車場完備。組合員割引でお得に利用できます。明瞭な料金体系と丁寧な事前相談が好評です。",
        "address": "北海道札幌市豊平区西岡3条6丁目8-15",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0180,
        "longitude": 141.3780,
        "nearest_station": "地下鉄南北線 澄川駅",
        "station_walk_minutes": 15,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["組合員割引", "明瞭価格", "駐車場完備", "家族葬対応"],
        "operator_name": "コープさっぽろ",
        "rating_avg": 4.0,
        "review_count": 38,
    },
    {
        "name": "豊平寺ホール",
        "slug": "hokkaido-toyohiradera-hall",
        "venue_type": "temple_hall",
        "description": "豊平区の日蓮宗寺院が運営する式場。伝統的な本堂での仏式葬儀のほか、ホールでの一般的な葬儀にも対応。宗派を問わず利用できます。",
        "address": "北海道札幌市豊平区豊平4条8丁目2-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0440,
        "longitude": 141.3680,
        "nearest_station": "地下鉄東豊線 学園前駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "駐車場": True, "控室": True, "和室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 478000}],
        "features": ["寺院式場", "宗派不問", "伝統的な雰囲気"],
        "operator_name": "豊平寺",
        "rating_avg": 3.9,
        "review_count": 16,
    },
    {
        "name": "セレモニーホール福住",
        "slug": "hokkaido-ceremony-fukuzumi",
        "venue_type": "private_hall",
        "description": "豊平区福住エリアのセレモニーホール。地下鉄東豊線「福住駅」から徒歩8分。札幌ドーム近くの立地で、わかりやすいアクセス。温かみのある空間で家族葬に最適です。",
        "address": "北海道札幌市豊平区福住2条4丁目2-18",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0210,
        "longitude": 141.4020,
        "nearest_station": "地下鉄東豊線 福住駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["駅近", "家族葬対応", "バリアフリー", "アットホーム"],
        "operator_name": "福住セレモニー",
        "rating_avg": 4.1,
        "review_count": 25,
    },
]

# 10件ずつバッチ投入
total = len(venues)
print(f"北海道バッチ1: 札幌前半 {total}件を投入開始")

for i in range(0, total, 10):
    batch = venues[i:i+10]
    code = insert_batch(batch)
    print(f"  バッチ {i//10+1}: {len(batch)}件 → HTTP {code}")
    if code != "201":
        # エラー詳細を取得
        data_json = json.dumps(batch, ensure_ascii=False)
        result = subprocess.run([
            "curl", "-s",
            "-X", "POST", SUPABASE_URL,
            "-H", f"apikey: {API_KEY}",
            "-H", f"Authorization: Bearer {API_KEY}",
            "-H", "Content-Type: application/json",
            "-H", "Prefer: return=minimal",
            "-H", "User-Agent: Mozilla/5.0",
            "-d", data_json
        ], capture_output=True, text=True)
        print(f"    エラー詳細: {result.stdout[:500]}")
    time.sleep(1)

print(f"バッチ1完了: {total}件")
