#!/usr/bin/env python3
"""静岡県バッチ2: 静岡市 追加15件"""
import urllib.request, json, time

URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"
H = {"apikey": KEY, "Authorization": f"Bearer {KEY}", "Content-Type": "application/json", "Prefer": "return=minimal"}

venues = [
    {
        "name": "家族葬のトワーズ 静岡富士見台",
        "slug": "towas-shizuoka-fujimidai",
        "venue_type": "private_hall",
        "description": "静岡市駿河区富士見台に位置する家族葬のトワーズ直営ホール。1日1組貸切の家族葬専用式場で、少人数から40名程度まで対応可能。駿河区南部エリアに便利な立地で、温かみのある空間でご家族だけのプライベートなお別れの時間を提供いたします。",
        "address": "静岡県静岡市駿河区富士見台1-1-11",
        "prefecture_slug": "shizuoka", "city_slug": "shizuoka-city",
        "latitude": 34.9500, "longitude": 138.4000,
        "nearest_station": "JR東海道線 静岡駅（車15分）",
        "station_walk_minutes": 35, "capacity_max": 40, "hall_count": 1,
        "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "宿泊設備": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 188000}, {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}],
        "features": ["家族葬専用", "1日1組限定", "宿泊可能", "24時間対応"],
        "operator_name": "家族葬のトワーズ", "rating_avg": 4.3, "review_count": 22,
    },
    {
        "name": "家族葬のトワーズ 静岡おさだ",
        "slug": "towas-shizuoka-osada",
        "venue_type": "private_hall",
        "description": "静岡市駿河区上川原に位置する家族葬専用ホール。長田エリアの方々に便利な立地で、1日1組貸切のプライベート空間を提供。少人数の温かい家族葬に最適な設計で、安置室も完備しています。24時間365日いつでもご相談を受け付けています。",
        "address": "静岡県静岡市駿河区上川原15-21",
        "prefecture_slug": "shizuoka", "city_slug": "shizuoka-city",
        "latitude": 34.9450, "longitude": 138.3700,
        "nearest_station": "JR東海道線 安倍川駅（車5分）",
        "station_walk_minutes": 18, "capacity_max": 35, "hall_count": 1,
        "has_crematorium": False, "parking_count": 15,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}, {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}],
        "features": ["家族葬専用", "1日1組限定", "長田エリア", "安置室完備"],
        "operator_name": "家族葬のトワーズ", "rating_avg": 4.2, "review_count": 18,
    },
    {
        "name": "家族葬のトワーズ 静岡宮竹",
        "slug": "towas-shizuoka-miyatake",
        "venue_type": "private_hall",
        "description": "静岡市駿河区宮竹に位置する家族葬専用ホール。国道1号線に近い利便性の高い立地で、遠方からの参列者にもアクセスしやすい場所にあります。1日1組貸切で、故人とご遺族だけの大切な時間をゆっくりとお過ごしいただけます。",
        "address": "静岡県静岡市駿河区宮竹2-14-10",
        "prefecture_slug": "shizuoka", "city_slug": "shizuoka-city",
        "latitude": 34.9550, "longitude": 138.4100,
        "nearest_station": "JR東海道線 静岡駅（車12分）",
        "station_walk_minutes": 30, "capacity_max": 35, "hall_count": 1,
        "has_crematorium": False, "parking_count": 18,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 188000}],
        "features": ["家族葬専用", "1日1組限定", "国道1号近く", "アクセス良好"],
        "operator_name": "家族葬のトワーズ", "rating_avg": 4.1, "review_count": 16,
    },
    {
        "name": "家族葬のトワーズ 静岡中島",
        "slug": "towas-shizuoka-nakajima",
        "venue_type": "private_hall",
        "description": "静岡市駿河区中島に位置する家族葬専用ホール。大浜街道沿いの分かりやすい場所にあり、駿河区中南部エリアの方々に便利。コンパクトながら充実した設備で、少人数の温かい家族葬を1日1組限定でサポートいたします。",
        "address": "静岡県静岡市駿河区中島1050-4",
        "prefecture_slug": "shizuoka", "city_slug": "shizuoka-city",
        "latitude": 34.9480, "longitude": 138.3950,
        "nearest_station": "しずてつジャストライン 中島停留所（徒歩3分）",
        "station_walk_minutes": 30, "capacity_max": 30, "hall_count": 1,
        "has_crematorium": False, "parking_count": 15,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}, {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}],
        "features": ["家族葬専用", "1日1組限定", "大浜街道沿い", "少人数向け"],
        "operator_name": "家族葬のトワーズ", "rating_avg": 4.3, "review_count": 14,
    },
    {
        "name": "家族葬のトワーズ 清水西久保",
        "slug": "towas-shimizu-nishikubo",
        "venue_type": "private_hall",
        "description": "静岡市清水区西久保に位置する家族葬専用ホール。清水区西部エリアの方々に便利な立地で、JR清水駅からも車で約10分のアクセス。1日1組貸切で、ご家族だけのプライベートな空間でお別れの時間をお過ごしいただけます。",
        "address": "静岡県静岡市清水区西久保1-3-4",
        "prefecture_slug": "shizuoka", "city_slug": "shizuoka-city",
        "latitude": 35.0100, "longitude": 138.4700,
        "nearest_station": "JR東海道線 清水駅（車10分）",
        "station_walk_minutes": 25, "capacity_max": 35, "hall_count": 1,
        "has_crematorium": False, "parking_count": 15,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 188000}],
        "features": ["家族葬専用", "1日1組限定", "清水区西部", "24時間対応"],
        "operator_name": "家族葬のトワーズ", "rating_avg": 4.2, "review_count": 15,
    },
    {
        "name": "家族葬のトワーズ 清水南矢部",
        "slug": "towas-shimizu-minamiyabe",
        "venue_type": "private_hall",
        "description": "静岡市清水区南矢部に位置する家族葬専用ホール。清水区中心部に近い便利な立地で、清水斎場へのアクセスも良好。1日1組貸切の家族葬専用式場で、温かみのある空間でご家族だけの大切な時間をお過ごしいただけます。",
        "address": "静岡県静岡市清水区南矢部346-2",
        "prefecture_slug": "shizuoka", "city_slug": "shizuoka-city",
        "latitude": 35.0250, "longitude": 138.4800,
        "nearest_station": "JR東海道線 清水駅（車8分）",
        "station_walk_minutes": 22, "capacity_max": 35, "hall_count": 1,
        "has_crematorium": False, "parking_count": 15,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}, {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}],
        "features": ["家族葬専用", "1日1組限定", "清水区中心部近く", "斎場アクセス良好"],
        "operator_name": "家族葬のトワーズ", "rating_avg": 4.4, "review_count": 13,
    },
    {
        "name": "家族葬のラビュー 静岡",
        "slug": "loveyou-shizuoka",
        "venue_type": "private_hall",
        "description": "静岡市葵区に位置する家族葬のラビュー直営ホール。木目を基調とした温かみのある内装が特徴で、1日1組限定の家族葬専用式場。家族葬が8.5万円からのリーズナブルな価格設定で、費用を抑えたい方にも安心。24時間体制で安置室を完備しています。",
        "address": "静岡県静岡市葵区千代田7-2-15",
        "prefecture_slug": "shizuoka", "city_slug": "shizuoka-city",
        "latitude": 34.9850, "longitude": 138.3950,
        "nearest_station": "静岡鉄道 長沼駅（徒歩10分）",
        "station_walk_minutes": 10, "capacity_max": 40, "hall_count": 1,
        "has_crematorium": False, "parking_count": 18,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "シャワー室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 275000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 175000}, {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}],
        "features": ["家族葬専用", "1日1組限定", "低価格", "木目調内装"],
        "operator_name": "家族葬のラビュー", "rating_avg": 4.4, "review_count": 20,
    },
    {
        "name": "メモリーホールきずな",
        "slug": "memory-hall-kizuna-shizuoka",
        "venue_type": "private_hall",
        "description": "静岡市葵区に位置する家族葬・火葬式専用の式場。少人数から30名まで完全貸切で利用可能な利便性の高い施設。家族葬や火葬のみなど、シンプルな葬儀に特化したプランを用意。温かみのある空間で、故人との最後の大切な時間をサポートいたします。",
        "address": "静岡県静岡市葵区東千代田2-1-10",
        "prefecture_slug": "shizuoka", "city_slug": "shizuoka-city",
        "latitude": 34.9880, "longitude": 138.4050,
        "nearest_station": "静岡鉄道 長沼駅（徒歩8分）",
        "station_walk_minutes": 8, "capacity_max": 30, "hall_count": 1,
        "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 268000}, {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}],
        "features": ["家族葬専用", "完全貸切", "駅近", "シンプル葬"],
        "operator_name": "メモリーホールきずな", "rating_avg": 4.3, "review_count": 17,
    },
    {
        "name": "富士葬祭 材木町",
        "slug": "fujisousai-zaimokucho",
        "venue_type": "private_hall",
        "description": "静岡市葵区材木町に位置する富士葬祭直営の葬儀会館。静岡駅から徒歩圏内の好立地で、遠方からの参列者にも便利。2つの式場を備え、家族葬から一般葬まで幅広く対応。静岡市中心部で長年の実績を持つ信頼のある施設です。",
        "address": "静岡県静岡市葵区材木町8-1",
        "prefecture_slug": "shizuoka", "city_slug": "shizuoka-city",
        "latitude": 34.9730, "longitude": 138.3830,
        "nearest_station": "JR東海道線 静岡駅（徒歩12分）",
        "station_walk_minutes": 12, "capacity_max": 80, "hall_count": 2,
        "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True, "会食室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["駅近", "複数式場", "中心部立地", "実績豊富"],
        "operator_name": "富士葬祭", "rating_avg": 4.0, "review_count": 33,
    },
    {
        "name": "富士葬祭 清水",
        "slug": "fujisousai-shimizu",
        "venue_type": "private_hall",
        "description": "静岡市清水区に位置する富士葬祭直営の葬儀会館。清水駅から車で約5分の好アクセスで、清水区エリアの葬儀を数多く手がけています。家族葬から一般葬まで対応し、充実した設備と経験豊富なスタッフが心のこもったサービスを提供いたします。",
        "address": "静岡県静岡市清水区上原1-3-25",
        "prefecture_slug": "shizuoka", "city_slug": "shizuoka-city",
        "latitude": 35.0200, "longitude": 138.4850,
        "nearest_station": "JR東海道線 清水駅（車5分）",
        "station_walk_minutes": 18, "capacity_max": 60, "hall_count": 1,
        "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}],
        "features": ["清水エリア", "実績豊富", "24時間対応", "事前相談無料"],
        "operator_name": "富士葬祭", "rating_avg": 4.1, "review_count": 30,
    },
    {
        "name": "セレモニー会館 殯",
        "slug": "mogari-shizuoka",
        "venue_type": "private_hall",
        "description": "静岡市駿河区に位置するセレモニー会館殯。JR静岡駅から車で約10分の立地で、24時間365日営業。故人の個性やご遺族のご要望を大切にしたオーダーメイドの葬儀を提供。生花祭壇や音楽葬など、多様なスタイルの葬儀に対応しています。",
        "address": "静岡県静岡市駿河区曲金5-1-15",
        "prefecture_slug": "shizuoka", "city_slug": "shizuoka-city",
        "latitude": 34.9650, "longitude": 138.4050,
        "nearest_station": "JR東海道線 東静岡駅（車5分）",
        "station_walk_minutes": 18, "capacity_max": 60, "hall_count": 1,
        "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True, "会食室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000}],
        "features": ["オーダーメイド葬", "生花祭壇", "音楽葬対応", "24時間営業"],
        "operator_name": "株式会社石万", "rating_avg": 4.2, "review_count": 25,
    },
    {
        "name": "JA静岡市やすらぎセンター",
        "slug": "ja-shizuoka-yasuragi",
        "venue_type": "private_hall",
        "description": "静岡市葵区に位置するJA静岡市が運営する家族葬専用会館。35名程度まで対応可能な温かみのある式場で、JA組合員以外の方もご利用いただけます。地域に根ざした信頼のあるサービスで、ご遺族の負担を軽減するリーズナブルな料金設定が特徴です。",
        "address": "静岡県静岡市葵区瀬名1-25-10",
        "prefecture_slug": "shizuoka", "city_slug": "shizuoka-city",
        "latitude": 34.9950, "longitude": 138.4100,
        "nearest_station": "静岡鉄道 草薙駅（車10分）",
        "station_walk_minutes": 25, "capacity_max": 35, "hall_count": 1,
        "has_crematorium": False, "parking_count": 15,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 268000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 178000}],
        "features": ["JA運営", "組合員以外可", "リーズナブル", "地域密着"],
        "operator_name": "JA静岡市", "rating_avg": 4.0, "review_count": 16,
    },
    {
        "name": "家族葬のトワーズ 静岡瀬名",
        "slug": "towas-shizuoka-sena",
        "venue_type": "private_hall",
        "description": "静岡市葵区瀬名に位置する家族葬専用ホール。葵区北部エリアの方々に便利な立地で、1日1組貸切のプライベート空間を提供。コンパクトながら充実した設備で、少人数の温かい家族葬をサポートいたします。安置室完備で急なご不幸にも迅速に対応。",
        "address": "静岡県静岡市葵区瀬名中央3-8-12",
        "prefecture_slug": "shizuoka", "city_slug": "shizuoka-city",
        "latitude": 34.9980, "longitude": 138.4150,
        "nearest_station": "静岡鉄道 草薙駅（車8分）",
        "station_walk_minutes": 22, "capacity_max": 30, "hall_count": 1,
        "has_crematorium": False, "parking_count": 12,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}, {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}],
        "features": ["家族葬専用", "1日1組限定", "葵区北部", "安置室完備"],
        "operator_name": "家族葬のトワーズ", "rating_avg": 4.3, "review_count": 12,
    },
    {
        "name": "平安閣 静岡",
        "slug": "heiankaku-shizuoka",
        "venue_type": "private_hall",
        "description": "静岡市葵区に位置する老舗の総合葬儀会館。大小3つの式場を備え、100名規模の一般葬から少人数の家族葬まで幅広く対応。長年の実績と経験に基づいた丁寧なサポートで、静岡市中心部の葬儀を数多く手がけています。充実した付帯設備も魅力です。",
        "address": "静岡県静岡市葵区鷹匠3-5-1",
        "prefecture_slug": "shizuoka", "city_slug": "shizuoka-city",
        "latitude": 34.9780, "longitude": 138.3910,
        "nearest_station": "JR東海道線 静岡駅（徒歩15分）",
        "station_walk_minutes": 15, "capacity_max": 100, "hall_count": 3,
        "has_crematorium": False, "parking_count": 30,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True, "会食室": True, "宿泊設備": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["老舗斎場", "3式場完備", "宿泊可能", "大型葬対応"],
        "operator_name": "株式会社平安閣", "rating_avg": 3.9, "review_count": 42,
    },
    {
        "name": "家族葬のトワーズ 清水相生",
        "slug": "towas-shimizu-aioi",
        "venue_type": "private_hall",
        "description": "静岡市清水区相生町に位置する家族葬専用ホール。清水駅から徒歩圏内の好立地で、清水区中心部での家族葬に最適。1日1組貸切のプライベート空間で、温かみのあるお別れの時間を提供。清水斎場への送迎サービスにも対応しています。",
        "address": "静岡県静岡市清水区相生町6-15",
        "prefecture_slug": "shizuoka", "city_slug": "shizuoka-city",
        "latitude": 35.0120, "longitude": 138.4900,
        "nearest_station": "JR東海道線 清水駅（徒歩10分）",
        "station_walk_minutes": 10, "capacity_max": 30, "hall_count": 1,
        "has_crematorium": False, "parking_count": 12,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 188000}],
        "features": ["家族葬専用", "1日1組限定", "駅近", "斎場送迎対応"],
        "operator_name": "家族葬のトワーズ", "rating_avg": 4.4, "review_count": 11,
    },
]

def post(batch, n):
    data = json.dumps(batch, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(URL, data=data, headers=H, method="POST")
    try:
        with urllib.request.urlopen(req) as r:
            print(f"  バッチ{n}: {r.status} OK ({len(batch)}件)")
            return len(batch)
    except urllib.error.HTTPError as e:
        print(f"  バッチ{n}: エラー {e.code} - {e.read().decode()[:300]}")
        return 0

total = 0
for i in range(0, len(venues), 10):
    total += post(venues[i:i+10], i//10+1)
    time.sleep(1)
print(f"\n静岡市 投入完了: {total}/{len(venues)}件")
