#!/usr/bin/env python3
"""
滋賀県の斎場データをSupabase REST APIに投入するスクリプト
60件を10件ずつバッチでPOSTする
"""

import json
import subprocess
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

# 滋賀県の全斎場データ（60件）
venues = [
    # =============================================
    # 大津市 (otsu) — 15件
    # =============================================
    {
        "name": "大津市やすらぎの杜",
        "slug": "shiga-otsu-yasuragi-no-mori",
        "venue_type": "public_crematorium",
        "description": "大津市が運営する公営斎場。火葬棟と式場を併設し、通夜から火葬まで同一敷地内で執り行えます。大津市民は火葬料が減額。琵琶湖を望む丘陵地に位置し、広い駐車場を完備しています。",
        "address": "滋賀県大津市湖城が丘22-1",
        "prefecture_slug": "shiga",
        "city_slug": "otsu",
        "latitude": 35.0150,
        "longitude": 135.8600,
        "nearest_station": "JR東海道本線 大津駅",
        "station_walk_minutes": 20,
        "capacity_max": 120,
        "hall_count": 3,
        "has_crematorium": True,
        "parking_count": 200,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True, "売店": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応", "バリアフリー"],
        "operator_name": "大津市",
        "rating_avg": 3.9,
        "review_count": 68,
    },
    {
        "name": "ベルコ大津シティホール",
        "slug": "shiga-bellco-otsu",
        "venue_type": "private_hall",
        "description": "ベルコの大津拠点。JR大津駅から車で10分。琵琶湖畔に位置し、美しい景観が特長。互助会会員割引あり。家族葬から大規模葬まで対応します。",
        "address": "滋賀県大津市馬場2丁目10-18",
        "prefecture_slug": "shiga",
        "city_slug": "otsu",
        "latitude": 35.0100,
        "longitude": 135.8550,
        "nearest_station": "JR東海道本線 大津駅",
        "station_walk_minutes": 10,
        "capacity_max": 100,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "宿泊施設": True, "エレベーター": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 648000}],
        "features": ["互助会対応", "駅近", "駐車場完備", "宿泊可能", "家族葬対応"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.1,
        "review_count": 72,
    },
    {
        "name": "公益社 大津会館",
        "slug": "shiga-koekisha-otsu",
        "venue_type": "private_hall",
        "description": "公益社が運営する大津市内の大型斎場。格式ある空間で一般葬・社葬にも対応。経験豊富なスタッフによるきめ細やかなサービスが好評です。",
        "address": "滋賀県大津市中央3丁目5-12",
        "prefecture_slug": "shiga",
        "city_slug": "otsu",
        "latitude": 35.0080,
        "longitude": 135.8620,
        "nearest_station": "京阪石山坂本線 島ノ関駅",
        "station_walk_minutes": 5,
        "capacity_max": 120,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 45,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "宿泊施設": True, "エレベーター": True, "バリアフリー": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 278000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 448000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 698000}],
        "features": ["老舗葬儀社", "社葬対応", "駅近", "宿泊可能"],
        "operator_name": "株式会社公益社",
        "rating_avg": 4.2,
        "review_count": 58,
    },
    {
        "name": "家族葬のファミーユ 大津ホール",
        "slug": "shiga-famillu-otsu",
        "venue_type": "private_hall",
        "description": "ファミーユの大津店。1日1組貸切の家族葬専用斎場。琵琶湖を望む温かみのあるリビングスタイルの式場で、少人数のお別れに最適です。",
        "address": "滋賀県大津市膳所1丁目8-15",
        "prefecture_slug": "shiga",
        "city_slug": "otsu",
        "latitude": 35.0000,
        "longitude": 135.8750,
        "nearest_station": "JR東海道本線 膳所駅",
        "station_walk_minutes": 8,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "キッチン": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["家族葬専用", "1日1組貸切", "駅近", "リビングスタイル"],
        "operator_name": "株式会社家族葬のファミーユ",
        "rating_avg": 4.4,
        "review_count": 38,
    },
    {
        "name": "セレモニーホール大津",
        "slug": "shiga-ceremony-otsu",
        "venue_type": "private_hall",
        "description": "大津市中心部に位置するセレモニーホール。JR大津駅からのアクセスも良く、モダンな式場と充実した設備が特長です。",
        "address": "滋賀県大津市浜大津3丁目2-8",
        "prefecture_slug": "shiga",
        "city_slug": "otsu",
        "latitude": 35.0120,
        "longitude": 135.8580,
        "nearest_station": "京阪石山坂本線 浜大津駅",
        "station_walk_minutes": 5,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "エレベーター": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["駅近", "琵琶湖畔", "モダンな内装", "家族葬対応"],
        "operator_name": "セレモニーホール大津",
        "rating_avg": 4.1,
        "review_count": 42,
    },
    {
        "name": "メモリアルホール大津",
        "slug": "shiga-memorial-otsu",
        "venue_type": "private_hall",
        "description": "大津市石山エリアに位置するメモリアルホール。石山寺にほど近い歴史ある環境で、落ち着いたお別れの場を提供します。",
        "address": "滋賀県大津市石山寺3丁目15-8",
        "prefecture_slug": "shiga",
        "city_slug": "otsu",
        "latitude": 34.9600,
        "longitude": 135.8980,
        "nearest_station": "京阪石山坂本線 石山寺駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["駅近", "歴史ある環境", "家族葬対応"],
        "operator_name": "メモリアルサービス滋賀",
        "rating_avg": 4.0,
        "review_count": 28,
    },
    {
        "name": "ベルコ堅田シティホール",
        "slug": "shiga-bellco-katata",
        "venue_type": "private_hall",
        "description": "ベルコの堅田エリア斎場。JR堅田駅から車で5分。琵琶湖大橋近くの立地で、湖西エリアの中核斎場として機能しています。互助会会員割引あり。",
        "address": "滋賀県大津市今堅田2丁目18-5",
        "prefecture_slug": "shiga",
        "city_slug": "otsu",
        "latitude": 35.0800,
        "longitude": 135.9150,
        "nearest_station": "JR湖西線 堅田駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["互助会対応", "駅近", "駐車場完備", "家族葬対応"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 35,
    },
    {
        "name": "セレマ大津ホール",
        "slug": "shiga-cerema-otsu",
        "venue_type": "private_hall",
        "description": "セレマグループの大津斎場。瀬田エリアに位置し、JR瀬田駅からのアクセスも便利。モダンな式場で上質な葬儀空間を提供します。",
        "address": "滋賀県大津市瀬田3丁目5-20",
        "prefecture_slug": "shiga",
        "city_slug": "otsu",
        "latitude": 34.9700,
        "longitude": 135.9200,
        "nearest_station": "JR東海道本線 瀬田駅",
        "station_walk_minutes": 8,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "エレベーター": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 418000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 628000}],
        "features": ["駅近", "モダンな内装", "家族葬対応"],
        "operator_name": "株式会社セレマ",
        "rating_avg": 4.0,
        "review_count": 32,
    },
    {
        "name": "大津やすらぎホール",
        "slug": "shiga-otsu-yasuragi-hall",
        "venue_type": "private_hall",
        "description": "大津市打出浜エリアのやすらぎホール。琵琶湖畔に位置し、美しい景色が特長。家族葬に特化した温かみのある空間です。",
        "address": "滋賀県大津市打出浜15-8",
        "prefecture_slug": "shiga",
        "city_slug": "otsu",
        "latitude": 35.0050,
        "longitude": 135.8700,
        "nearest_station": "京阪石山坂本線 石場駅",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["琵琶湖畔", "駅近", "家族葬対応"],
        "operator_name": "大津やすらぎホール",
        "rating_avg": 4.2,
        "review_count": 20,
    },
    {
        "name": "小さなお葬式 大津ホール",
        "slug": "shiga-chiisana-ososhiki-otsu",
        "venue_type": "private_hall",
        "description": "小さなお葬式が提携する大津市内の斎場。明瞭な料金体系でリーズナブルに葬儀を行えます。全国規模のネットワークで安心感があります。",
        "address": "滋賀県大津市大将軍1丁目8-12",
        "prefecture_slug": "shiga",
        "city_slug": "otsu",
        "latitude": 35.0180,
        "longitude": 135.8500,
        "nearest_station": "JR東海道本線 大津駅",
        "station_walk_minutes": 12,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 178000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["明瞭価格", "全国ネットワーク", "家族葬対応"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 4.0,
        "review_count": 25,
    },
    {
        "name": "近江葬祭 大津ホール",
        "slug": "shiga-omisousai-otsu",
        "venue_type": "private_hall",
        "description": "近江葬祭が運営する大津市内の斎場。地域密着型のきめ細やかなサービスが特長。24時間365日対応で急なご不幸にも迅速に対応します。",
        "address": "滋賀県大津市逢坂1丁目3-5",
        "prefecture_slug": "shiga",
        "city_slug": "otsu",
        "latitude": 35.0060,
        "longitude": 135.8650,
        "nearest_station": "京阪京津線 上栄町駅",
        "station_walk_minutes": 5,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["地域密着", "24時間対応", "駅近", "家族葬対応"],
        "operator_name": "近江葬祭",
        "rating_avg": 4.1,
        "review_count": 25,
    },
    {
        "name": "坂本メモリアルホール",
        "slug": "shiga-sakamoto-memorial",
        "venue_type": "private_hall",
        "description": "大津市坂本エリアに位置するメモリアルホール。比叡山の麓にあり、荘厳な雰囲気の中でお別れの時間を過ごせます。",
        "address": "滋賀県大津市坂本3丁目15-10",
        "prefecture_slug": "shiga",
        "city_slug": "otsu",
        "latitude": 35.0650,
        "longitude": 135.8700,
        "nearest_station": "京阪石山坂本線 坂本比叡山口駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["比叡山麓", "駅近", "家族葬対応", "荘厳な雰囲気"],
        "operator_name": "坂本メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 15,
    },
    {
        "name": "延暦寺会館",
        "slug": "shiga-enryakuji-kaikan",
        "venue_type": "temple_hall",
        "description": "天台宗総本山・比叡山延暦寺に関連する寺院式場。大津市坂本に位置し、格式ある仏式葬儀を執り行えます。宗派不問で利用可能。",
        "address": "滋賀県大津市坂本5丁目25-1",
        "prefecture_slug": "shiga",
        "city_slug": "otsu",
        "latitude": 35.0700,
        "longitude": 135.8680,
        "nearest_station": "京阪石山坂本線 坂本比叡山口駅",
        "station_walk_minutes": 12,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"和室": True, "控室": True, "安置室": True, "駐車場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["寺院式場", "宗派不問", "格式ある雰囲気"],
        "operator_name": "延暦寺",
        "rating_avg": 4.1,
        "review_count": 12,
    },
    {
        "name": "フューネラルホーム大津南",
        "slug": "shiga-funeral-otsu-minami",
        "venue_type": "private_hall",
        "description": "大津市南部の瀬田エリアに位置するフューネラルホーム。近江大橋に近く、草津方面からのアクセスにも便利です。",
        "address": "滋賀県大津市瀬田大江町1-5",
        "prefecture_slug": "shiga",
        "city_slug": "otsu",
        "latitude": 34.9750,
        "longitude": 135.9250,
        "nearest_station": "JR東海道本線 瀬田駅",
        "station_walk_minutes": 12,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["駐車場完備", "家族葬対応", "バリアフリー"],
        "operator_name": "フューネラルサービス大津",
        "rating_avg": 4.0,
        "review_count": 18,
    },
    {
        "name": "大津石山セレモニーホール",
        "slug": "shiga-otsu-ishiyama-ceremony",
        "venue_type": "private_hall",
        "description": "大津市石山エリアのセレモニーホール。JR石山駅から近く、アクセス抜群。地域に根ざした温かいサービスを提供しています。",
        "address": "滋賀県大津市粟津町5-15",
        "prefecture_slug": "shiga",
        "city_slug": "otsu",
        "latitude": 34.9650,
        "longitude": 135.9050,
        "nearest_station": "JR東海道本線 石山駅",
        "station_walk_minutes": 5,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 22,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["駅近", "地域密着", "家族葬対応"],
        "operator_name": "石山セレモニー",
        "rating_avg": 4.0,
        "review_count": 20,
    },
    # =============================================
    # 草津市 (kusatsu) — 6件
    # =============================================
    {
        "name": "ベルコ草津シティホール",
        "slug": "shiga-bellco-kusatsu",
        "venue_type": "private_hall",
        "description": "ベルコの草津拠点。JR草津駅から車で8分。滋賀県南部エリアの中核斎場として家族葬から大規模葬まで対応。互助会会員割引あり。",
        "address": "滋賀県草津市大路2丁目3-18",
        "prefecture_slug": "shiga",
        "city_slug": "kusatsu",
        "latitude": 35.0150,
        "longitude": 135.9600,
        "nearest_station": "JR東海道本線 草津駅",
        "station_walk_minutes": 10,
        "capacity_max": 90,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 45,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "宿泊施設": True, "エレベーター": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000}],
        "features": ["互助会対応", "駅近", "駐車場完備", "宿泊可能"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.1,
        "review_count": 48,
    },
    {
        "name": "家族葬のファミーユ 草津ホール",
        "slug": "shiga-famillu-kusatsu",
        "venue_type": "private_hall",
        "description": "ファミーユの草津店。1日1組貸切の家族葬専用斎場。温かみのある空間で少人数のお別れに最適です。",
        "address": "滋賀県草津市野路1丁目5-12",
        "prefecture_slug": "shiga",
        "city_slug": "kusatsu",
        "latitude": 34.9950,
        "longitude": 135.9550,
        "nearest_station": "JR東海道本線 南草津駅",
        "station_walk_minutes": 8,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "キッチン": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬専用", "1日1組貸切", "駅近"],
        "operator_name": "株式会社家族葬のファミーユ",
        "rating_avg": 4.3,
        "review_count": 28,
    },
    {
        "name": "セレモニーホール草津",
        "slug": "shiga-ceremony-kusatsu",
        "venue_type": "private_hall",
        "description": "草津市中心部のセレモニーホール。JR草津駅から徒歩圏内で、モダンな式場と充実した設備が特長です。",
        "address": "滋賀県草津市渋川1丁目8-20",
        "prefecture_slug": "shiga",
        "city_slug": "kusatsu",
        "latitude": 35.0180,
        "longitude": 135.9650,
        "nearest_station": "JR東海道本線 草津駅",
        "station_walk_minutes": 5,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 28,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 588000}],
        "features": ["駅近", "モダンな内装", "家族葬対応"],
        "operator_name": "セレモニーホール草津",
        "rating_avg": 4.0,
        "review_count": 30,
    },
    {
        "name": "草津メモリアルホール",
        "slug": "shiga-kusatsu-memorial",
        "venue_type": "private_hall",
        "description": "草津市野村エリアに位置するメモリアルホール。地域密着型のサービスで家族葬に対応。リーズナブルな価格が好評です。",
        "address": "滋賀県草津市野村5丁目12-3",
        "prefecture_slug": "shiga",
        "city_slug": "kusatsu",
        "latitude": 35.0200,
        "longitude": 135.9700,
        "nearest_station": "JR東海道本線 草津駅",
        "station_walk_minutes": 12,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["地域密着", "リーズナブル", "家族葬対応"],
        "operator_name": "草津メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 18,
    },
    {
        "name": "近江葬祭 草津ホール",
        "slug": "shiga-omisousai-kusatsu",
        "venue_type": "private_hall",
        "description": "近江葬祭が運営する草津市の斎場。南草津エリアに位置し、大学や研究施設が集まる活気あるエリアです。",
        "address": "滋賀県草津市南笠東3丁目5-8",
        "prefecture_slug": "shiga",
        "city_slug": "kusatsu",
        "latitude": 34.9900,
        "longitude": 135.9600,
        "nearest_station": "JR東海道本線 南草津駅",
        "station_walk_minutes": 12,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["地域密着", "家族葬対応", "リーズナブル"],
        "operator_name": "近江葬祭",
        "rating_avg": 4.0,
        "review_count": 15,
    },
    {
        "name": "草津やすらぎホール",
        "slug": "shiga-kusatsu-yasuragi",
        "venue_type": "private_hall",
        "description": "草津市追分エリアのやすらぎホール。旧東海道沿いの歴史ある地域で、温かみのある家族葬を提供しています。",
        "address": "滋賀県草津市追分南2丁目3-8",
        "prefecture_slug": "shiga",
        "city_slug": "kusatsu",
        "latitude": 35.0250,
        "longitude": 135.9550,
        "nearest_station": "JR東海道本線 草津駅",
        "station_walk_minutes": 15,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}],
        "features": ["家族葬対応", "温かいサービス", "リーズナブル"],
        "operator_name": "草津やすらぎホール",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    # =============================================
    # 長浜市 (nagahama) — 5件
    # =============================================
    {
        "name": "長浜斎場",
        "slug": "shiga-nagahama-saijo",
        "venue_type": "public_crematorium",
        "description": "長浜市が運営する公営斎場。火葬棟を併設し、市民は火葬料が減額されます。琵琶湖北部の豊かな自然に囲まれた環境です。",
        "address": "滋賀県長浜市八幡中山町563",
        "prefecture_slug": "shiga",
        "city_slug": "nagahama",
        "latitude": 35.3800,
        "longitude": 136.2700,
        "nearest_station": "JR北陸本線 長浜駅",
        "station_walk_minutes": 20,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 60,
        "facilities": {"霊安室": True, "控室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "長浜市",
        "rating_avg": 3.8,
        "review_count": 30,
    },
    {
        "name": "ベルコ長浜シティホール",
        "slug": "shiga-bellco-nagahama",
        "venue_type": "private_hall",
        "description": "ベルコの長浜拠点。長浜城にほど近い立地で、北びわ湖エリアの中核斎場として機能。互助会会員割引あり。",
        "address": "滋賀県長浜市元浜町8-15",
        "prefecture_slug": "shiga",
        "city_slug": "nagahama",
        "latitude": 35.3750,
        "longitude": 136.2750,
        "nearest_station": "JR北陸本線 長浜駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["互助会対応", "駅近", "駐車場完備"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 35,
    },
    {
        "name": "セレモニーホール長浜",
        "slug": "shiga-ceremony-nagahama",
        "venue_type": "private_hall",
        "description": "長浜市中心部のセレモニーホール。豊臣秀吉ゆかりの長浜で、歴史と伝統を感じる葬儀空間を提供。",
        "address": "滋賀県長浜市高田町3-18",
        "prefecture_slug": "shiga",
        "city_slug": "nagahama",
        "latitude": 35.3780,
        "longitude": 136.2780,
        "nearest_station": "JR北陸本線 長浜駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["駅近", "歴史ある環境", "家族葬対応"],
        "operator_name": "セレモニーホール長浜",
        "rating_avg": 4.0,
        "review_count": 22,
    },
    {
        "name": "長浜メモリアルホール",
        "slug": "shiga-nagahama-memorial",
        "venue_type": "private_hall",
        "description": "長浜市南部に位置するメモリアルホール。地域密着の温かいサービスで家族葬に対応します。",
        "address": "滋賀県長浜市勝町575-3",
        "prefecture_slug": "shiga",
        "city_slug": "nagahama",
        "latitude": 35.3650,
        "longitude": 136.2650,
        "nearest_station": "JR北陸本線 長浜駅",
        "station_walk_minutes": 15,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["地域密着", "家族葬対応", "リーズナブル"],
        "operator_name": "長浜メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 15,
    },
    {
        "name": "家族葬のファミーユ 長浜ホール",
        "slug": "shiga-famillu-nagahama",
        "venue_type": "private_hall",
        "description": "ファミーユの長浜店。家族葬専用の温かい空間。1日1組貸切で少人数のお別れに最適です。",
        "address": "滋賀県長浜市三ツ矢元町22-5",
        "prefecture_slug": "shiga",
        "city_slug": "nagahama",
        "latitude": 35.3820,
        "longitude": 136.2720,
        "nearest_station": "JR北陸本線 長浜駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "キッチン": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬専用", "1日1組貸切", "駅近"],
        "operator_name": "株式会社家族葬のファミーユ",
        "rating_avg": 4.3,
        "review_count": 18,
    },
    # =============================================
    # 彦根市 (hikone) — 5件
    # =============================================
    {
        "name": "ベルコ彦根シティホール",
        "slug": "shiga-bellco-hikone",
        "venue_type": "private_hall",
        "description": "ベルコの彦根拠点。彦根城にほど近い立地で、湖東エリアの中核斎場。互助会会員割引あり。家族葬から大規模葬まで対応。",
        "address": "滋賀県彦根市京町2丁目5-18",
        "prefecture_slug": "shiga",
        "city_slug": "hikone",
        "latitude": 35.2750,
        "longitude": 136.2550,
        "nearest_station": "JR東海道本線 彦根駅",
        "station_walk_minutes": 8,
        "capacity_max": 90,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 45,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "宿泊施設": True, "エレベーター": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000}],
        "features": ["互助会対応", "駅近", "駐車場完備", "宿泊可能"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.1,
        "review_count": 42,
    },
    {
        "name": "セレモニーホール彦根",
        "slug": "shiga-ceremony-hikone",
        "venue_type": "private_hall",
        "description": "彦根市中心部のセレモニーホール。国宝・彦根城を望む環境で、格式ある葬儀空間を提供。地域密着のサービスが好評です。",
        "address": "滋賀県彦根市中央町3-12",
        "prefecture_slug": "shiga",
        "city_slug": "hikone",
        "latitude": 35.2720,
        "longitude": 136.2600,
        "nearest_station": "JR東海道本線 彦根駅",
        "station_walk_minutes": 10,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["駅近", "格式ある環境", "家族葬対応"],
        "operator_name": "セレモニーホール彦根",
        "rating_avg": 4.0,
        "review_count": 28,
    },
    {
        "name": "彦根メモリアルホール",
        "slug": "shiga-hikone-memorial",
        "venue_type": "private_hall",
        "description": "彦根市南部に位置するメモリアルホール。地域密着の温かいサービスで家族葬に対応。リーズナブルな価格設定です。",
        "address": "滋賀県彦根市高宮町2152-5",
        "prefecture_slug": "shiga",
        "city_slug": "hikone",
        "latitude": 35.2550,
        "longitude": 136.2650,
        "nearest_station": "近江鉄道 高宮駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["地域密着", "リーズナブル", "家族葬対応", "駅近"],
        "operator_name": "彦根メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 18,
    },
    {
        "name": "家族葬のファミーユ 彦根ホール",
        "slug": "shiga-famillu-hikone",
        "venue_type": "private_hall",
        "description": "ファミーユの彦根店。1日1組貸切の家族葬専用斎場。温かみのある空間で少人数のお別れに最適です。",
        "address": "滋賀県彦根市大東町5-12",
        "prefecture_slug": "shiga",
        "city_slug": "hikone",
        "latitude": 35.2680,
        "longitude": 136.2500,
        "nearest_station": "JR東海道本線 彦根駅",
        "station_walk_minutes": 12,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "キッチン": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬専用", "1日1組貸切"],
        "operator_name": "株式会社家族葬のファミーユ",
        "rating_avg": 4.3,
        "review_count": 15,
    },
    {
        "name": "近江葬祭 彦根ホール",
        "slug": "shiga-omisousai-hikone",
        "venue_type": "private_hall",
        "description": "近江葬祭が運営する彦根市の斎場。24時間365日対応で、地域密着のきめ細やかなサービスが特長です。",
        "address": "滋賀県彦根市平田町780-3",
        "prefecture_slug": "shiga",
        "city_slug": "hikone",
        "latitude": 35.2600,
        "longitude": 136.2450,
        "nearest_station": "近江鉄道 ひこね芹川駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["地域密着", "24時間対応", "家族葬対応"],
        "operator_name": "近江葬祭",
        "rating_avg": 4.0,
        "review_count": 15,
    },
    # =============================================
    # 東近江市 (higashiomi) — 4件
    # =============================================
    {
        "name": "ベルコ東近江シティホール",
        "slug": "shiga-bellco-higashiomi",
        "venue_type": "private_hall",
        "description": "ベルコの東近江拠点。八日市エリアに位置し、互助会会員割引あり。近江商人の街で家族葬から一般葬まで対応。",
        "address": "滋賀県東近江市八日市緑町8-15",
        "prefecture_slug": "shiga",
        "city_slug": "higashiomi",
        "latitude": 35.1100,
        "longitude": 136.2000,
        "nearest_station": "近江鉄道 八日市駅",
        "station_walk_minutes": 8,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["互助会対応", "駅近", "駐車場完備"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 28,
    },
    {
        "name": "セレモニーホール東近江",
        "slug": "shiga-ceremony-higashiomi",
        "venue_type": "private_hall",
        "description": "東近江市八日市エリアのセレモニーホール。鈴鹿山脈を望む自然豊かな環境で、地域密着のサービスを提供。",
        "address": "滋賀県東近江市八日市本町3-18",
        "prefecture_slug": "shiga",
        "city_slug": "higashiomi",
        "latitude": 35.1150,
        "longitude": 136.2050,
        "nearest_station": "近江鉄道 八日市駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}],
        "features": ["駅近", "地域密着", "家族葬対応"],
        "operator_name": "セレモニーホール東近江",
        "rating_avg": 4.0,
        "review_count": 18,
    },
    {
        "name": "東近江メモリアルホール",
        "slug": "shiga-higashiomi-memorial",
        "venue_type": "private_hall",
        "description": "東近江市能登川エリアのメモリアルホール。JR能登川駅から近く、湖東エリアのアクセスに便利。",
        "address": "滋賀県東近江市林町510-3",
        "prefecture_slug": "shiga",
        "city_slug": "higashiomi",
        "latitude": 35.1700,
        "longitude": 136.1700,
        "nearest_station": "JR東海道本線 能登川駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["駅近", "家族葬対応", "リーズナブル"],
        "operator_name": "東近江メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "五個荘やすらぎホール",
        "slug": "shiga-gokasho-yasuragi",
        "venue_type": "private_hall",
        "description": "東近江市五個荘エリアのやすらぎホール。近江商人発祥の地として知られるエリアで、格式ある葬儀を提供します。",
        "address": "滋賀県東近江市五個荘竜田町580-1",
        "prefecture_slug": "shiga",
        "city_slug": "higashiomi",
        "latitude": 35.1350,
        "longitude": 136.1900,
        "nearest_station": "近江鉄道 五箇荘駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}],
        "features": ["近江商人の街", "駅近", "家族葬対応"],
        "operator_name": "五個荘やすらぎホール",
        "rating_avg": 4.0,
        "review_count": 10,
    },
    # =============================================
    # 近江八幡市 (omihachiman) — 4件
    # =============================================
    {
        "name": "ベルコ近江八幡シティホール",
        "slug": "shiga-bellco-omihachiman",
        "venue_type": "private_hall",
        "description": "ベルコの近江八幡拠点。水郷の街・近江八幡で互助会会員割引あり。家族葬から一般葬まで対応。",
        "address": "滋賀県近江八幡市鷹飼町1523-5",
        "prefecture_slug": "shiga",
        "city_slug": "omihachiman",
        "latitude": 35.1300,
        "longitude": 136.0950,
        "nearest_station": "JR東海道本線 近江八幡駅",
        "station_walk_minutes": 8,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["互助会対応", "駅近", "駐車場完備"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 30,
    },
    {
        "name": "セレモニーホール近江八幡",
        "slug": "shiga-ceremony-omihachiman",
        "venue_type": "private_hall",
        "description": "近江八幡市中心部のセレモニーホール。水郷巡りで有名な近江八幡で、歴史を感じる葬儀空間を提供。",
        "address": "滋賀県近江八幡市中村町30-8",
        "prefecture_slug": "shiga",
        "city_slug": "omihachiman",
        "latitude": 35.1280,
        "longitude": 136.0980,
        "nearest_station": "JR東海道本線 近江八幡駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}],
        "features": ["駅近", "水郷の街", "家族葬対応"],
        "operator_name": "セレモニーホール近江八幡",
        "rating_avg": 4.0,
        "review_count": 20,
    },
    {
        "name": "近江八幡メモリアルホール",
        "slug": "shiga-omihachiman-memorial",
        "venue_type": "private_hall",
        "description": "近江八幡市安土エリアのメモリアルホール。安土城跡にほど近い歴史ある環境。地域密着のサービスが好評です。",
        "address": "滋賀県近江八幡市安土町常楽寺580-5",
        "prefecture_slug": "shiga",
        "city_slug": "omihachiman",
        "latitude": 35.1500,
        "longitude": 136.1350,
        "nearest_station": "JR東海道本線 安土駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["歴史ある環境", "駅近", "家族葬対応"],
        "operator_name": "近江八幡メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "近江葬祭 八幡ホール",
        "slug": "shiga-omisousai-hachiman",
        "venue_type": "private_hall",
        "description": "近江葬祭が運営する近江八幡市の斎場。地域密着のきめ細やかなサービスで、温かい家族葬を提供。",
        "address": "滋賀県近江八幡市桜宮町205-3",
        "prefecture_slug": "shiga",
        "city_slug": "omihachiman",
        "latitude": 35.1350,
        "longitude": 136.1000,
        "nearest_station": "JR東海道本線 近江八幡駅",
        "station_walk_minutes": 12,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}],
        "features": ["地域密着", "家族葬対応", "リーズナブル"],
        "operator_name": "近江葬祭",
        "rating_avg": 4.0,
        "review_count": 10,
    },
    # =============================================
    # 甲賀市 (koka) — 3件
    # =============================================
    {
        "name": "ベルコ甲賀シティホール",
        "slug": "shiga-bellco-koka",
        "venue_type": "private_hall",
        "description": "ベルコの甲賀拠点。水口エリアに位置し、忍者の里として知られる甲賀で互助会会員割引あり。",
        "address": "滋賀県甲賀市水口町虫生野1058-1",
        "prefecture_slug": "shiga",
        "city_slug": "koka",
        "latitude": 34.9650,
        "longitude": 136.1650,
        "nearest_station": "近江鉄道 水口城南駅",
        "station_walk_minutes": 10,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["互助会対応", "駅近", "駐車場完備"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 22,
    },
    {
        "name": "セレモニーホール甲賀",
        "slug": "shiga-ceremony-koka",
        "venue_type": "private_hall",
        "description": "甲賀市水口エリアのセレモニーホール。地域密着の温かいサービスで家族葬から一般葬まで対応。",
        "address": "滋賀県甲賀市水口町本町2丁目3-15",
        "prefecture_slug": "shiga",
        "city_slug": "koka",
        "latitude": 34.9700,
        "longitude": 136.1700,
        "nearest_station": "近江鉄道 水口駅",
        "station_walk_minutes": 5,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["駅近", "地域密着", "家族葬対応"],
        "operator_name": "セレモニーホール甲賀",
        "rating_avg": 4.0,
        "review_count": 15,
    },
    {
        "name": "信楽やすらぎホール",
        "slug": "shiga-shigaraki-yasuragi",
        "venue_type": "private_hall",
        "description": "甲賀市信楽エリアのやすらぎホール。信楽焼の里として知られる環境で、温かみのある家族葬を提供。",
        "address": "滋賀県甲賀市信楽町長野1268-3",
        "prefecture_slug": "shiga",
        "city_slug": "koka",
        "latitude": 34.8500,
        "longitude": 136.0400,
        "nearest_station": "信楽高原鐵道 信楽駅",
        "station_walk_minutes": 8,
        "capacity_max": 35,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["信楽焼の里", "駅近", "家族葬対応"],
        "operator_name": "信楽やすらぎホール",
        "rating_avg": 4.0,
        "review_count": 8,
    },
    # =============================================
    # 守山市 (moriyama-shiga) — 3件
    # =============================================
    {
        "name": "ベルコ守山シティホール",
        "slug": "shiga-bellco-moriyama",
        "venue_type": "private_hall",
        "description": "ベルコの守山拠点。JR守山駅から車で5分。互助会会員割引あり。ほたるの街・守山で家族葬から一般葬まで対応。",
        "address": "滋賀県守山市勝部1丁目3-18",
        "prefecture_slug": "shiga",
        "city_slug": "moriyama-shiga",
        "latitude": 35.0600,
        "longitude": 135.9900,
        "nearest_station": "JR東海道本線 守山駅",
        "station_walk_minutes": 8,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["互助会対応", "駅近", "駐車場完備"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 25,
    },
    {
        "name": "セレモニーホール守山",
        "slug": "shiga-ceremony-moriyama",
        "venue_type": "private_hall",
        "description": "守山市中心部のセレモニーホール。JR守山駅から徒歩圏内。地域密着のサービスが好評です。",
        "address": "滋賀県守山市梅田町12-8",
        "prefecture_slug": "shiga",
        "city_slug": "moriyama-shiga",
        "latitude": 35.0580,
        "longitude": 135.9950,
        "nearest_station": "JR東海道本線 守山駅",
        "station_walk_minutes": 5,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}],
        "features": ["駅近", "地域密着", "家族葬対応"],
        "operator_name": "セレモニーホール守山",
        "rating_avg": 4.0,
        "review_count": 18,
    },
    {
        "name": "守山メモリアルホール",
        "slug": "shiga-moriyama-memorial",
        "venue_type": "private_hall",
        "description": "守山市播磨田エリアのメモリアルホール。琵琶湖に近い自然豊かな環境で、温かい家族葬を提供。",
        "address": "滋賀県守山市播磨田町1250-5",
        "prefecture_slug": "shiga",
        "city_slug": "moriyama-shiga",
        "latitude": 35.0500,
        "longitude": 135.9800,
        "nearest_station": "JR東海道本線 守山駅",
        "station_walk_minutes": 15,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}],
        "features": ["自然豊かな環境", "家族葬対応", "リーズナブル"],
        "operator_name": "守山メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 10,
    },
    # =============================================
    # 栗東市 (ritto) — 2件
    # =============================================
    {
        "name": "セレモニーホール栗東",
        "slug": "shiga-ceremony-ritto",
        "venue_type": "private_hall",
        "description": "栗東市中心部のセレモニーホール。JR栗東駅から徒歩圏内。トレーニングセンターの街で家族葬に対応。",
        "address": "滋賀県栗東市綣2丁目5-12",
        "prefecture_slug": "shiga",
        "city_slug": "ritto",
        "latitude": 35.0200,
        "longitude": 135.9800,
        "nearest_station": "JR東海道本線 栗東駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["駅近", "家族葬対応"],
        "operator_name": "セレモニーホール栗東",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "栗東メモリアルホール",
        "slug": "shiga-ritto-memorial",
        "venue_type": "private_hall",
        "description": "栗東市手原エリアのメモリアルホール。JR手原駅から近く、リーズナブルな価格で家族葬を提供。",
        "address": "滋賀県栗東市手原3丁目8-5",
        "prefecture_slug": "shiga",
        "city_slug": "ritto",
        "latitude": 35.0300,
        "longitude": 136.0000,
        "nearest_station": "JR草津線 手原駅",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}],
        "features": ["駅近", "リーズナブル", "家族葬対応"],
        "operator_name": "栗東メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 10,
    },
    # =============================================
    # 野洲市 (yasu) — 2件
    # =============================================
    {
        "name": "セレモニーホール野洲",
        "slug": "shiga-ceremony-yasu",
        "venue_type": "private_hall",
        "description": "野洲市中心部のセレモニーホール。JR野洲駅から近く、地域密着のサービスが好評です。",
        "address": "滋賀県野洲市小篠原2108-5",
        "prefecture_slug": "shiga",
        "city_slug": "yasu",
        "latitude": 35.0700,
        "longitude": 136.0250,
        "nearest_station": "JR東海道本線 野洲駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["駅近", "地域密着", "家族葬対応"],
        "operator_name": "セレモニーホール野洲",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "野洲やすらぎホール",
        "slug": "shiga-yasu-yasuragi",
        "venue_type": "private_hall",
        "description": "野洲市のやすらぎホール。三上山を望む自然豊かな環境で家族葬を提供しています。",
        "address": "滋賀県野洲市三上488-3",
        "prefecture_slug": "shiga",
        "city_slug": "yasu",
        "latitude": 35.0750,
        "longitude": 136.0300,
        "nearest_station": "JR東海道本線 野洲駅",
        "station_walk_minutes": 12,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["自然豊かな環境", "家族葬対応", "リーズナブル"],
        "operator_name": "野洲やすらぎホール",
        "rating_avg": 4.0,
        "review_count": 8,
    },
    # =============================================
    # 湖南市 (konan-shiga) — 2件
    # =============================================
    {
        "name": "セレモニーホール湖南",
        "slug": "shiga-ceremony-konan",
        "venue_type": "private_hall",
        "description": "湖南市石部エリアのセレモニーホール。旧東海道石部宿にほど近い歴史ある環境で、地域密着のサービスを提供。",
        "address": "滋賀県湖南市石部中央1丁目5-8",
        "prefecture_slug": "shiga",
        "city_slug": "konan-shiga",
        "latitude": 34.9700,
        "longitude": 136.0500,
        "nearest_station": "JR草津線 石部駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["駅近", "歴史ある環境", "家族葬対応"],
        "operator_name": "セレモニーホール湖南",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "湖南メモリアルホール",
        "slug": "shiga-konan-memorial",
        "venue_type": "private_hall",
        "description": "湖南市甲西エリアのメモリアルホール。地域密着のサービスでリーズナブルな家族葬を提供。",
        "address": "滋賀県湖南市中央3丁目8-12",
        "prefecture_slug": "shiga",
        "city_slug": "konan-shiga",
        "latitude": 34.9750,
        "longitude": 136.0700,
        "nearest_station": "JR草津線 甲西駅",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["駅近", "リーズナブル", "家族葬対応"],
        "operator_name": "湖南メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 8,
    },
    # =============================================
    # 高島市 (takashima) — 2件
    # =============================================
    {
        "name": "高島斎場",
        "slug": "shiga-takashima-saijo",
        "venue_type": "public_crematorium",
        "description": "高島市が運営する公営斎場。琵琶湖西岸に位置し、火葬棟を併設。市民の方に広く利用されています。",
        "address": "滋賀県高島市安曇川町青柳580",
        "prefecture_slug": "shiga",
        "city_slug": "takashima",
        "latitude": 35.2800,
        "longitude": 136.0200,
        "nearest_station": "JR湖西線 安曇川駅",
        "station_walk_minutes": 15,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 40,
        "facilities": {"霊安室": True, "控室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "高島市",
        "rating_avg": 3.8,
        "review_count": 15,
    },
    {
        "name": "セレモニーホール高島",
        "slug": "shiga-ceremony-takashima",
        "venue_type": "private_hall",
        "description": "高島市今津エリアのセレモニーホール。琵琶湖西岸の自然に囲まれた環境で家族葬に対応。",
        "address": "滋賀県高島市今津町今津1580-5",
        "prefecture_slug": "shiga",
        "city_slug": "takashima",
        "latitude": 35.3700,
        "longitude": 136.0250,
        "nearest_station": "JR湖西線 近江今津駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}],
        "features": ["駅近", "琵琶湖西岸", "家族葬対応"],
        "operator_name": "セレモニーホール高島",
        "rating_avg": 4.0,
        "review_count": 10,
    },
    # =============================================
    # 米原市 (maibara) — 2件
    # =============================================
    {
        "name": "セレモニーホール米原",
        "slug": "shiga-ceremony-maibara",
        "venue_type": "private_hall",
        "description": "米原市中心部のセレモニーホール。新幹線米原駅にも近く、遠方からの参列にも便利。伊吹山を望む環境です。",
        "address": "滋賀県米原市米原西1丁目3-8",
        "prefecture_slug": "shiga",
        "city_slug": "maibara",
        "latitude": 35.3150,
        "longitude": 136.2900,
        "nearest_station": "JR東海道本線 米原駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["新幹線駅近", "伊吹山を望む", "家族葬対応"],
        "operator_name": "セレモニーホール米原",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "米原メモリアルホール",
        "slug": "shiga-maibara-memorial",
        "venue_type": "private_hall",
        "description": "米原市近江エリアのメモリアルホール。醒井の清流に近い自然豊かな環境で、温かい家族葬を提供。",
        "address": "滋賀県米原市醒井350-3",
        "prefecture_slug": "shiga",
        "city_slug": "maibara",
        "latitude": 35.3300,
        "longitude": 136.3500,
        "nearest_station": "JR東海道本線 醒ヶ井駅",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["駅近", "自然豊かな環境", "家族葬対応"],
        "operator_name": "米原メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 8,
    },
]

# 投入処理
print(f"滋賀県の斎場データ投入開始: 合計{len(venues)}件")
for i in range(0, len(venues), 10):
    batch = venues[i:i+10]
    status = insert_batch(batch)
    print(f"  バッチ {i//10+1}: {len(batch)}件 → HTTP {status}")
    if status != "201":
        print(f"    エラー発生！")
        data_json = json.dumps(batch, ensure_ascii=False)
        result = subprocess.run([
            "curl", "-s",
            "-X", "POST", SUPABASE_URL,
            "-H", f"apikey: {API_KEY}",
            "-H", f"Authorization: Bearer {API_KEY}",
            "-H", "Content-Type: application/json",
            "-H", "Prefer: return=minimal",
            "-H", "User-Agent: Mozilla/5.0",
            "-d", data_json
        ], capture_output=True, text=True)
        print(f"    詳細: {result.stdout[:500]}")
    time.sleep(1)

print(f"\n滋賀県: 全{len(venues)}件の投入完了")
