#!/usr/bin/env python3
"""
宮城県の斎場データ バッチ2（42件）- 仙台市 太白区・泉区
"""

import json
import urllib.request
import urllib.error
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

HEADERS = {
    "apikey": API_KEY,
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal",
}

venues = [
    # =============================================
    # 仙台市太白区 (20件)
    # =============================================
    {
        "name": "仙台太白斎場 清月記",
        "slug": "miyagi-seigetsuki-taihaku",
        "venue_type": "private_hall",
        "description": "仙台市太白区鹿野に位置する清月記の斎場。太白区の中心エリアに位置し、地域の方に広く利用されています。家族葬から一般葬まで対応可能で、JR長町駅からのアクセスも良好です。",
        "address": "宮城県仙台市太白区鹿野3-4-13",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.231, "longitude": 140.876,
        "nearest_station": "JR東北本線 長町駅", "station_walk_minutes": 10,
        "capacity_max": 100, "hall_count": 2, "has_crematorium": False, "parking_count": 40,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "バリアフリー", "大規模"],
        "operator_name": "株式会社清月記", "rating_avg": 4.2, "review_count": 23,
    },
    {
        "name": "仙台中田斎場 清月記",
        "slug": "miyagi-seigetsuki-nakata",
        "venue_type": "private_hall",
        "description": "仙台市太白区中田に位置する清月記の斎場。太白区南部の中田・名取エリアの方に広く利用されています。家族葬から一般葬まで対応。広い駐車場を完備し、車でのアクセスに便利です。",
        "address": "宮城県仙台市太白区中田5-13-21",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.208, "longitude": 140.885,
        "nearest_station": "JR東北本線 南仙台駅", "station_walk_minutes": 10,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 40,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "株式会社清月記", "rating_avg": 4.1, "review_count": 19,
    },
    {
        "name": "仙台八木山斎場 清月記",
        "slug": "miyagi-seigetsuki-yagiyama",
        "venue_type": "private_hall",
        "description": "仙台市太白区八木山エリアに位置する清月記の斎場。地下鉄東西線八木山動物公園駅からのアクセスが良好。八木山・青山・向山エリアの方に利用されています。",
        "address": "宮城県仙台市太白区八木山本町1-33-10",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.244, "longitude": 140.858,
        "nearest_station": "地下鉄東西線 八木山動物公園駅", "station_walk_minutes": 8,
        "capacity_max": 60, "hall_count": 2, "has_crematorium": False, "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "駅近", "バリアフリー"],
        "operator_name": "株式会社清月記", "rating_avg": 4.0, "review_count": 16,
    },
    {
        "name": "太白典礼会館",
        "slug": "miyagi-taihaku-tenrei",
        "venue_type": "private_hall",
        "description": "仙台市太白区鹿野に位置する典礼会館。太白区の主要道路沿いにあり、110台分の大駐車場を完備。大規模な一般葬から家族葬まで幅広く対応し、地域に根ざしたサービスを提供しています。",
        "address": "宮城県仙台市太白区鹿野2-19-20",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.232, "longitude": 140.874,
        "nearest_station": "JR東北本線 長町駅", "station_walk_minutes": 12,
        "capacity_max": 150, "hall_count": 3, "has_crematorium": False, "parking_count": 110,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 380000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 650000}],
        "features": ["家族葬対応", "大規模", "バリアフリー", "宿泊可能"],
        "operator_name": "株式会社博善社", "rating_avg": 4.1, "review_count": 22,
    },
    {
        "name": "セレモール太白",
        "slug": "miyagi-ceremor-taihaku",
        "venue_type": "private_hall",
        "description": "仙台市太白区に位置するセレモールの式場。太白区・長町エリアの方に広く利用されており、家族葬から一般葬まで対応可能。充実した設備と丁寧なサービスが好評です。",
        "address": "宮城県仙台市太白区長町5-3-20",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.228, "longitude": 140.879,
        "nearest_station": "JR東北本線 長町駅", "station_walk_minutes": 5,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["家族葬対応", "駅近", "バリアフリー"],
        "operator_name": "あいあーる葬祭会館", "rating_avg": 4.0, "review_count": 17,
    },
    {
        "name": "セレモール八木山",
        "slug": "miyagi-ceremor-yagiyama",
        "venue_type": "private_hall",
        "description": "仙台市太白区八木山に位置するセレモールの式場。八木山動物公園駅から車で5分の立地。八木山エリアの方に利用されており、家族葬を中心に温かみのあるサービスを提供。",
        "address": "宮城県仙台市太白区八木山南2-1-12",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.238, "longitude": 140.850,
        "nearest_station": "地下鉄東西線 八木山動物公園駅", "station_walk_minutes": 12,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "あいあーる葬祭会館", "rating_avg": 3.9, "review_count": 14,
    },
    {
        "name": "ファミーユたいはく",
        "slug": "miyagi-famille-taihaku",
        "venue_type": "private_hall",
        "description": "仙台市太白区大野田に位置する家族葬のファミーユ。清月記グループが運営する1日1組貸切の家族葬専用ホール。地下鉄南北線富沢駅から徒歩7分のアクセスの良さが魅力です。",
        "address": "宮城県仙台市太白区大野田5-17-3",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.218, "longitude": 140.872,
        "nearest_station": "地下鉄南北線 富沢駅", "station_walk_minutes": 7,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬対応", "1日1組貸切", "駅近"],
        "operator_name": "株式会社清月記", "rating_avg": 4.3, "review_count": 15,
    },
    {
        "name": "ファミーユながまち",
        "slug": "miyagi-famille-nagamachi",
        "venue_type": "private_hall",
        "description": "仙台市太白区八本松に位置する家族葬のファミーユ。清月記グループが運営する家族葬専用ホール。JR長町駅から車5分のアクセスで、1日1組貸切のプライベートな空間を提供。",
        "address": "宮城県仙台市太白区八本松1-13-6",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.225, "longitude": 140.883,
        "nearest_station": "JR東北本線 長町駅", "station_walk_minutes": 12,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬対応", "1日1組貸切"],
        "operator_name": "株式会社清月記", "rating_avg": 4.2, "review_count": 13,
    },
    {
        "name": "家族葬の仙和 仙台柳生ホール",
        "slug": "miyagi-senwa-yanagiu",
        "venue_type": "private_hall",
        "description": "仙台市太白区柳生に位置する家族葬の仙和の式場。太白区南東部の柳生・大野田エリアの方に利用されています。1日1組貸切で、静かな住宅街の中でゆっくりお別れの時間を過ごせます。",
        "address": "宮城県仙台市太白区柳生2-2-3",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.215, "longitude": 140.897,
        "nearest_station": "地下鉄南北線 富沢駅", "station_walk_minutes": 15,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["家族葬対応", "1日1組貸切"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.0, "review_count": 11,
    },
    {
        "name": "家族葬の仙和 仙台中田ホール",
        "slug": "miyagi-senwa-nakata",
        "venue_type": "private_hall",
        "description": "仙台市太白区中田に位置する家族葬の仙和の式場。南仙台駅からのアクセスが良好で、太白区南部エリアの方に利用されています。1日1組貸切の家族葬ホールです。",
        "address": "宮城県仙台市太白区中田4-8-12",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.209, "longitude": 140.886,
        "nearest_station": "JR東北本線 南仙台駅", "station_walk_minutes": 8,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 187000}],
        "features": ["家族葬対応", "1日1組貸切", "駅近"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.1, "review_count": 12,
    },
    {
        "name": "家族葬の仙和 仙台西多賀ホール",
        "slug": "miyagi-senwa-nishitaga",
        "venue_type": "private_hall",
        "description": "仙台市太白区西多賀に位置する家族葬の仙和の式場。太白区西部の閑静な住宅街にあり、西多賀・長町南エリアの方に利用されています。1日1組貸切の家族葬専用ホール。",
        "address": "宮城県仙台市太白区西多賀3-1-15",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.224, "longitude": 140.859,
        "nearest_station": "地下鉄南北線 長町南駅", "station_walk_minutes": 15,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["家族葬対応", "1日1組貸切"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.0, "review_count": 10,
    },
    {
        "name": "家族葬の仙和 仙台大野田ホール",
        "slug": "miyagi-senwa-onoda",
        "venue_type": "private_hall",
        "description": "仙台市太白区大野田に位置する家族葬の仙和の式場。富沢駅からアクセスしやすい立地で、太白区南西部の方に利用されています。1日1組貸切の家族葬ホールです。",
        "address": "宮城県仙台市太白区大野田4-20-8",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.219, "longitude": 140.874,
        "nearest_station": "地下鉄南北線 富沢駅", "station_walk_minutes": 8,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["家族葬対応", "1日1組貸切", "駅近"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.1, "review_count": 11,
    },
    {
        "name": "家族葬の仙和 仙台あすと長町ホール",
        "slug": "miyagi-senwa-asuto-nagamachi",
        "venue_type": "private_hall",
        "description": "仙台市太白区あすと長町に位置する家族葬の仙和の式場。JR長町駅前の再開発エリアにあり、アクセス抜群。1日1組貸切の家族葬ホールで、新しく清潔な空間が特長です。",
        "address": "宮城県仙台市太白区あすと長町1-5-15",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.227, "longitude": 140.882,
        "nearest_station": "JR東北本線 長町駅", "station_walk_minutes": 3,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 187000}],
        "features": ["家族葬対応", "1日1組貸切", "駅近"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.3, "review_count": 14,
    },
    {
        "name": "ごんきや太白ホール",
        "slug": "miyagi-gonkiya-taihaku",
        "venue_type": "private_hall",
        "description": "仙台市太白区に位置するごんきやの葬儀ホール。太白区の住宅街に位置し、家族葬を中心に地域の方に利用されています。温かみのある空間でアットホームな葬儀を提供。",
        "address": "宮城県仙台市太白区郡山4-5-15",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.221, "longitude": 140.867,
        "nearest_station": "JR東北本線 太子堂駅", "station_walk_minutes": 10,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "株式会社ごんきや", "rating_avg": 4.0, "review_count": 13,
    },
    {
        "name": "花さいだん長町",
        "slug": "miyagi-hanasaidan-nagamachi",
        "venue_type": "private_hall",
        "description": "仙台市太白区長町に位置する花さいだんの葬儀ホール。花祭壇を得意とし、美しい花に囲まれた温かいお見送りが特長。長町駅から近く、アクセスも良好です。",
        "address": "宮城県仙台市太白区長町3-7-25",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.229, "longitude": 140.878,
        "nearest_station": "JR東北本線 長町駅", "station_walk_minutes": 7,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["家族葬対応", "花祭壇", "駅近"],
        "operator_name": "花さいだん", "rating_avg": 4.1, "review_count": 15,
    },
    {
        "name": "南仙台メモリアルホール",
        "slug": "miyagi-minamisendai-memorial",
        "venue_type": "private_hall",
        "description": "仙台市太白区中田エリアに位置するメモリアルホール。南仙台駅から近く、太白区南部・名取市北部の方に便利な立地。家族葬を中心にリーズナブルな価格で葬儀を提供しています。",
        "address": "宮城県仙台市太白区中田町前沖143-1",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.204, "longitude": 140.889,
        "nearest_station": "JR東北本線 南仙台駅", "station_walk_minutes": 5,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 275000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 480000}],
        "features": ["家族葬対応", "駅近", "低価格"],
        "operator_name": "南仙台メモリアル", "rating_avg": 3.9, "review_count": 11,
    },
    {
        "name": "秋保メモリアルホール",
        "slug": "miyagi-akiu-memorial",
        "venue_type": "private_hall",
        "description": "仙台市太白区秋保町に位置する葬儀ホール。秋保温泉エリアの方を中心に利用されています。山間部の静かな環境で、自然に囲まれた穏やかなお見送りが可能です。",
        "address": "宮城県仙台市太白区秋保町長袋字大原30-2",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.244, "longitude": 140.736,
        "nearest_station": "JR仙山線 愛子駅", "station_walk_minutes": 30,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}],
        "features": ["家族葬対応", "少人数向け"],
        "operator_name": "秋保メモリアル", "rating_avg": 3.7, "review_count": 8,
    },
    {
        "name": "太白さくらホール",
        "slug": "miyagi-taihaku-sakura-hall",
        "venue_type": "private_hall",
        "description": "仙台市太白区に位置する家族葬向けの小規模な葬儀場。桜をモチーフにした優しい内装で、温かみのあるお見送りが可能。少人数の家族葬に特化した施設です。",
        "address": "宮城県仙台市太白区富沢南2-8-5",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.217, "longitude": 140.867,
        "nearest_station": "地下鉄南北線 富沢駅", "station_walk_minutes": 10,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 265000}],
        "features": ["家族葬対応", "少人数向け", "低価格"],
        "operator_name": "太白さくらホール", "rating_avg": 3.9, "review_count": 9,
    },
    {
        "name": "泉崎メモリアルホール",
        "slug": "miyagi-izumizaki-memorial",
        "venue_type": "private_hall",
        "description": "仙台市太白区泉崎に位置するメモリアルホール。長町南駅から車で5分の立地で、太白区西部エリアの方に利用されています。家族葬に対応した落ち着いた空間です。",
        "address": "宮城県仙台市太白区泉崎1-30-5",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.226, "longitude": 140.863,
        "nearest_station": "地下鉄南北線 長町南駅", "station_walk_minutes": 12,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 290000}],
        "features": ["家族葬対応"],
        "operator_name": "泉崎メモリアル", "rating_avg": 3.8, "review_count": 10,
    },
    # =============================================
    # 仙台市泉区 (22件)
    # =============================================
    {
        "name": "仙台泉斎場 清月記",
        "slug": "miyagi-seigetsuki-izumi",
        "venue_type": "private_hall",
        "description": "仙台市泉区泉中央に位置する清月記の斎場。地下鉄南北線泉中央駅から近い好立地で、泉区全域の方に広く利用されています。家族葬から大規模な一般葬まで対応可能な複数の式場を備えています。",
        "address": "宮城県仙台市泉区泉中央1-30-1",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.320, "longitude": 140.882,
        "nearest_station": "地下鉄南北線 泉中央駅", "station_walk_minutes": 5,
        "capacity_max": 120, "hall_count": 3, "has_crematorium": False, "parking_count": 50,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "駅近", "大規模", "宿泊可能"],
        "operator_name": "株式会社清月記", "rating_avg": 4.3, "review_count": 26,
    },
    {
        "name": "仙台東斎場 清月記",
        "slug": "miyagi-seigetsuki-higashi",
        "venue_type": "private_hall",
        "description": "仙台市泉区南光台南に位置する清月記の斎場。泉区南東部・宮城野区北部の方に利用されています。落ち着いた住宅街の中にあり、家族葬から一般葬まで幅広く対応。",
        "address": "宮城県仙台市泉区南光台南3-7-7",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.302, "longitude": 140.904,
        "nearest_station": "地下鉄南北線 旭ヶ丘駅", "station_walk_minutes": 15,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "株式会社清月記", "rating_avg": 4.0, "review_count": 18,
    },
    {
        "name": "仙台七北田斎場 清月記",
        "slug": "miyagi-seigetsuki-nanakita",
        "venue_type": "private_hall",
        "description": "仙台市泉区七北田に位置する清月記の斎場。泉区北部の七北田・根白石エリアの方に利用されています。自然豊かな環境の中で、心安らぐ葬儀を執り行えます。",
        "address": "宮城県仙台市泉区七北田字大沢烏谷10-1",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.340, "longitude": 140.882,
        "nearest_station": "地下鉄南北線 泉中央駅", "station_walk_minutes": 20,
        "capacity_max": 60, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "株式会社清月記", "rating_avg": 3.9, "review_count": 14,
    },
    {
        "name": "仙台つばめさわ斎場 清月記",
        "slug": "miyagi-seigetsuki-tsubamesawa",
        "venue_type": "private_hall",
        "description": "仙台市泉区つばめさわエリアに位置する清月記の斎場。泉パークタウンに近い住宅街にあり、泉区西部の方に利用されています。家族葬から一般葬まで対応しています。",
        "address": "宮城県仙台市泉区桂3-18-5",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.330, "longitude": 140.853,
        "nearest_station": "地下鉄南北線 泉中央駅", "station_walk_minutes": 20,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "株式会社清月記", "rating_avg": 4.0, "review_count": 12,
    },
    {
        "name": "泉典礼会館",
        "slug": "miyagi-izumi-tenrei",
        "venue_type": "private_hall",
        "description": "仙台市泉区松森に位置する典礼会館。70台分の広い駐車場を完備し、大規模な葬儀にも対応。泉区北部・利府町方面からのアクセスも良好で、家族葬から一般葬まで幅広く対応しています。",
        "address": "宮城県仙台市泉区松森字中道16",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.318, "longitude": 140.910,
        "nearest_station": "地下鉄南北線 八乙女駅", "station_walk_minutes": 15,
        "capacity_max": 150, "hall_count": 3, "has_crematorium": False, "parking_count": 70,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 380000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 650000}],
        "features": ["家族葬対応", "大規模", "バリアフリー", "宿泊可能"],
        "operator_name": "株式会社博善社", "rating_avg": 4.1, "review_count": 21,
    },
    {
        "name": "セレモール泉中央",
        "slug": "miyagi-ceremor-izumi-chuo",
        "venue_type": "private_hall",
        "description": "仙台市泉区泉中央に位置するセレモールの式場。泉中央駅から近い好立地で、泉区の方に広く利用されています。家族葬から一般葬まで対応可能な設備を備えています。",
        "address": "宮城県仙台市泉区泉中央3-20-5",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.322, "longitude": 140.879,
        "nearest_station": "地下鉄南北線 泉中央駅", "station_walk_minutes": 7,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["家族葬対応", "駅近", "バリアフリー"],
        "operator_name": "あいあーる葬祭会館", "rating_avg": 4.0, "review_count": 17,
    },
    {
        "name": "セレモール泉市名坂",
        "slug": "miyagi-ceremor-izumi-ichinazaka",
        "venue_type": "private_hall",
        "description": "仙台市泉区市名坂に位置するセレモールの式場。泉区南部の市名坂・八乙女エリアの方に利用されています。家族葬を中心に、温かみのあるサービスを提供しています。",
        "address": "宮城県仙台市泉区市名坂字町84-3",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.315, "longitude": 140.890,
        "nearest_station": "地下鉄南北線 八乙女駅", "station_walk_minutes": 8,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["家族葬対応", "駅近", "バリアフリー"],
        "operator_name": "あいあーる葬祭会館", "rating_avg": 4.0, "review_count": 15,
    },
    {
        "name": "セレモール南光台",
        "slug": "miyagi-ceremor-nankodai",
        "venue_type": "private_hall",
        "description": "仙台市泉区南光台に位置するセレモールの式場。南光台・旭ヶ丘エリアの方に利用されており、住宅街の中に位置する落ち着いた葬儀場。家族葬から一般葬まで対応しています。",
        "address": "宮城県仙台市泉区南光台4-10-3",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.301, "longitude": 140.898,
        "nearest_station": "地下鉄南北線 旭ヶ丘駅", "station_walk_minutes": 12,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "あいあーる葬祭会館", "rating_avg": 3.9, "review_count": 14,
    },
    {
        "name": "家族葬の仙和 仙台泉中央ホール",
        "slug": "miyagi-senwa-izumi-chuo",
        "venue_type": "private_hall",
        "description": "仙台市泉区泉中央に位置する家族葬の仙和の式場。泉中央駅から徒歩7分の好アクセスで、泉区の方に広く利用されています。1日1組貸切の家族葬ホールで、安置室完備。",
        "address": "宮城県仙台市泉区泉中央1-38-14",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.321, "longitude": 140.884,
        "nearest_station": "地下鉄南北線 泉中央駅", "station_walk_minutes": 7,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 187000}],
        "features": ["家族葬対応", "1日1組貸切", "駅近"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.2, "review_count": 16,
    },
    {
        "name": "家族葬の仙和 仙台南光台ホール",
        "slug": "miyagi-senwa-nankodai",
        "venue_type": "private_hall",
        "description": "仙台市泉区南光台に位置する家族葬の仙和の式場。南光台の閑静な住宅街にあり、1日1組貸切の家族葬ホール。旭ヶ丘駅からバスでもアクセス可能です。",
        "address": "宮城県仙台市泉区南光台7-3-28",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.303, "longitude": 140.901,
        "nearest_station": "地下鉄南北線 旭ヶ丘駅", "station_walk_minutes": 15,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["家族葬対応", "1日1組貸切"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.0, "review_count": 11,
    },
    {
        "name": "家族葬の仙和 仙台長命ヶ丘ホール",
        "slug": "miyagi-senwa-chomeigaoka",
        "venue_type": "private_hall",
        "description": "仙台市泉区長命ヶ丘に位置する家族葬の仙和の式場。泉区東部の長命ヶ丘・鶴ヶ丘エリアの方に利用されています。1日1組貸切の家族葬ホールで、安置室を完備。",
        "address": "宮城県仙台市泉区長命ヶ丘3-27-15",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.310, "longitude": 140.905,
        "nearest_station": "地下鉄南北線 八乙女駅", "station_walk_minutes": 15,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["家族葬対応", "1日1組貸切"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.1, "review_count": 12,
    },
    {
        "name": "家族葬の仙和 仙台北中山ホール",
        "slug": "miyagi-senwa-kitanakayama",
        "venue_type": "private_hall",
        "description": "仙台市泉区北中山に位置する家族葬の仙和の式場。泉区西部の北中山エリアの方に利用されています。1日1組貸切の家族葬ホールで、落ち着いた住宅街の中に位置しています。",
        "address": "宮城県仙台市泉区北中山3-10-5",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.313, "longitude": 140.857,
        "nearest_station": "地下鉄南北線 泉中央駅", "station_walk_minutes": 20,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}],
        "features": ["家族葬対応", "1日1組貸切"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.0, "review_count": 10,
    },
    {
        "name": "家族葬の仙和 仙台名坂ホール",
        "slug": "miyagi-senwa-nazaka",
        "venue_type": "private_hall",
        "description": "仙台市泉区市名坂に2026年1月オープンの家族葬の仙和の最新式場。1日1組貸切で安置室完備。新しく清潔な施設で、最新の設備を備えた家族葬ホールです。",
        "address": "宮城県仙台市泉区市名坂字石止4-1",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.316, "longitude": 140.893,
        "nearest_station": "地下鉄南北線 八乙女駅", "station_walk_minutes": 10,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 187000}],
        "features": ["家族葬対応", "1日1組貸切", "新規オープン"],
        "operator_name": "家族葬の仙和", "rating_avg": 4.4, "review_count": 8,
    },
    {
        "name": "ごんきや泉ホール",
        "slug": "miyagi-gonkiya-izumi",
        "venue_type": "private_hall",
        "description": "仙台市泉区に位置するごんきやの葬儀ホール。泉区の住宅街に位置し、家族葬を中心に地域の方に利用されています。温かみのあるサービスと適正価格が好評です。",
        "address": "宮城県仙台市泉区将監8-10-3",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.325, "longitude": 140.875,
        "nearest_station": "地下鉄南北線 泉中央駅", "station_walk_minutes": 12,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "バリアフリー"],
        "operator_name": "株式会社ごんきや", "rating_avg": 4.0, "review_count": 13,
    },
    {
        "name": "泉パークタウンメモリアル",
        "slug": "miyagi-izumi-parktown-memorial",
        "venue_type": "private_hall",
        "description": "仙台市泉区の泉パークタウンエリアに位置する葬儀場。高級住宅街にふさわしい上質な空間で、家族葬を中心にきめ細かいサービスを提供。緑豊かな環境が特長です。",
        "address": "宮城県仙台市泉区高森4-2-15",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.332, "longitude": 140.859,
        "nearest_station": "地下鉄南北線 泉中央駅", "station_walk_minutes": 25,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}],
        "features": ["家族葬対応", "少人数向け"],
        "operator_name": "泉パークタウンメモリアル", "rating_avg": 4.2, "review_count": 9,
    },
    {
        "name": "花さいだん泉",
        "slug": "miyagi-hanasaidan-izumi",
        "venue_type": "private_hall",
        "description": "仙台市泉区に位置する花さいだんの葬儀ホール。花祭壇を得意とし、美しい花に囲まれたお見送りが特長。泉中央駅からアクセスしやすい立地で、泉区の方に利用されています。",
        "address": "宮城県仙台市泉区松陵2-15-10",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.328, "longitude": 140.895,
        "nearest_station": "地下鉄南北線 泉中央駅", "station_walk_minutes": 15,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["家族葬対応", "花祭壇", "バリアフリー"],
        "operator_name": "花さいだん", "rating_avg": 4.1, "review_count": 14,
    },
    {
        "name": "泉ヶ丘セレモニーホール",
        "slug": "miyagi-izumigaoka-ceremony",
        "venue_type": "private_hall",
        "description": "仙台市泉区泉ヶ丘に位置するセレモニーホール。泉区東部の住宅街にあり、地域の方に利用されています。家族葬に適した小規模な式場で、リーズナブルな価格が魅力です。",
        "address": "宮城県仙台市泉区泉ヶ丘3-10-5",
        "prefecture_slug": "miyagi", "city_slug": "sendai",
        "latitude": 38.308, "longitude": 140.908,
        "nearest_station": "地下鉄南北線 八乙女駅", "station_walk_minutes": 15,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 270000}],
        "features": ["家族葬対応", "少人数向け", "低価格"],
        "operator_name": "泉ヶ丘セレモニー", "rating_avg": 3.8, "review_count": 9,
    },
]

def insert_batch(batch):
    data_json = json.dumps(batch, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(SUPABASE_URL, data=data_json, headers=HEADERS, method="POST")
    try:
        with urllib.request.urlopen(req) as resp:
            return resp.status
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"  HTTPError {e.code}: {body[:300]}")
        return e.code

total = 0
batch_size = 10
for i in range(0, len(venues), batch_size):
    batch = venues[i:i+batch_size]
    code = insert_batch(batch)
    total += len(batch)
    print(f"バッチ {i//batch_size+1}: {len(batch)}件 → HTTP {code} (累計 {total}件)")
    time.sleep(0.5)

print(f"\n完了: 合計 {total}件 投入")
