# -*- coding: utf-8 -*-
import json, subprocess, time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

venues = [
    # === 津市 残り13件 ===
    {"name":"セレモニーホール津","slug":"mie-ceremony-tsu","venue_type":"private_hall","description":"津市中心部のセレモニーホール。近鉄津新町駅近くの便利な立地で、地域の方に親しまれています。","address":"三重県津市新町3-1-25","prefecture_slug":"mie","city_slug":"tsu","latitude":34.713,"longitude":136.505,"nearest_station":"近鉄名古屋線 津新町駅","station_walk_minutes":5,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":100000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":365000},{"type":"ippanso","label":"一般葬プラン","priceFrom":660000}],"features":["家族葬対応","駅近"],"operator_name":"セレモニーホール","rating_avg":4.1,"review_count":30},
    {"name":"津市斎場","slug":"mie-tsu-saijo","venue_type":"public_crematorium","description":"津市が運営する公営火葬場・斎場。市民料金で火葬と告別式が行えます。","address":"三重県津市垂水字弁天山2867","prefecture_slug":"mie","city_slug":"tsu","latitude":34.730,"longitude":136.480,"nearest_station":"近鉄名古屋線 津駅","station_walk_minutes":25,"capacity_max":80,"hall_count":2,"has_crematorium":True,"parking_count":50,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":50000}],"features":["公営施設","火葬場併設","大駐車場"],"operator_name":"津市","rating_avg":3.7,"review_count":50},
    {"name":"家族葬のファミーユ津","slug":"mie-famillu-tsu","venue_type":"private_hall","description":"津市の家族葬専門ホール。少人数でのお見送りに特化した温かい空間です。","address":"三重県津市桜橋3-133","prefecture_slug":"mie","city_slug":"tsu","latitude":34.720,"longitude":136.515,"nearest_station":"近鉄名古屋線 津駅","station_walk_minutes":8,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":85000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":290000}],"features":["家族葬対応","少人数対応","低価格","駅近"],"operator_name":"家族葬のファミーユ","rating_avg":4.4,"review_count":18},
    {"name":"JA葬祭津","slug":"mie-ja-tsu","venue_type":"private_hall","description":"JA津安芸が運営する葬祭ホール。組合員割引があり、地域に根差したサービスが特徴です。","address":"三重県津市島崎町244","prefecture_slug":"mie","city_slug":"tsu","latitude":34.716,"longitude":136.512,"nearest_station":"近鉄名古屋線 津駅","station_walk_minutes":12,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":290000},{"type":"ippanso","label":"一般葬プラン","priceFrom":530000}],"features":["家族葬対応","低価格"],"operator_name":"JA津安芸","rating_avg":3.9,"review_count":22},
    {"name":"ティア津南","slug":"mie-tier-tsu-minami","venue_type":"private_hall","description":"津市南部のティア。久居エリアに位置し、松阪方面からのアクセスも便利です。","address":"三重県津市久居新町1128-3","prefecture_slug":"mie","city_slug":"tsu","latitude":34.685,"longitude":136.462,"nearest_station":"近鉄名古屋線 久居駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":18,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":92000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":340000}],"features":["家族葬対応","駅近"],"operator_name":"ティア","rating_avg":4.2,"review_count":22},
    {"name":"ベルコ津シティホール","slug":"mie-bellco-tsu","venue_type":"private_hall","description":"津市のベルコ葬儀会館。国道23号線沿いの便利な立地で広い駐車場を完備しています。","address":"三重県津市藤方512-3","prefecture_slug":"mie","city_slug":"tsu","latitude":34.710,"longitude":136.520,"nearest_station":"近鉄名古屋線 津駅","station_walk_minutes":15,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":98000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":355000},{"type":"ippanso","label":"一般葬プラン","priceFrom":670000}],"features":["家族葬対応","大駐車場"],"operator_name":"ベルコ","rating_avg":4.1,"review_count":28},
    {"name":"メモリアルホール津","slug":"mie-memorial-tsu","venue_type":"private_hall","description":"津市栄町エリアのメモリアルホール。清潔感のある設備で心のこもった葬儀をサポートします。","address":"三重県津市栄町3-225","prefecture_slug":"mie","city_slug":"tsu","latitude":34.722,"longitude":136.510,"nearest_station":"近鉄名古屋線 津駅","station_walk_minutes":10,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":360000},{"type":"ippanso","label":"一般葬プラン","priceFrom":650000}],"features":["家族葬対応","駅近"],"operator_name":"メモリアルホール","rating_avg":4.0,"review_count":20},
    {"name":"こころ斎苑津","slug":"mie-kokorosaien-tsu","venue_type":"private_hall","description":"津市河芸エリアのこころ斎苑。木のぬくもりを感じる温かい式場です。","address":"三重県津市河芸町東千里211-1","prefecture_slug":"mie","city_slug":"tsu","latitude":34.760,"longitude":136.540,"nearest_station":"近鉄名古屋線 千里駅","station_walk_minutes":8,"capacity_max":40,"hall_count":1,"has_crematorium":False,"parking_count":12,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":88000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":310000}],"features":["家族葬対応","少人数対応","駅近"],"operator_name":"こころ斎苑","rating_avg":4.3,"review_count":14},
    {"name":"紫雲殿津南","slug":"mie-shiunden-tsu-minami","venue_type":"private_hall","description":"津市南部の紫雲殿。国道165号線沿いで広い駐車場があります。","address":"三重県津市久居北口町9-8","prefecture_slug":"mie","city_slug":"tsu","latitude":34.690,"longitude":136.465,"nearest_station":"近鉄名古屋線 久居駅","station_walk_minutes":5,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":340000},{"type":"ippanso","label":"一般葬プラン","priceFrom":630000}],"features":["家族葬対応","駅近"],"operator_name":"紫雲殿","rating_avg":4.0,"review_count":18},
    {"name":"家族葬のファミーユ津南","slug":"mie-famillu-tsu-minami","venue_type":"private_hall","description":"津市久居エリアの家族葬専門ホール。少人数対応です。","address":"三重県津市久居野村町330-5","prefecture_slug":"mie","city_slug":"tsu","latitude":34.682,"longitude":136.458,"nearest_station":"近鉄名古屋線 久居駅","station_walk_minutes":10,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":82000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":280000}],"features":["家族葬対応","少人数対応","低価格"],"operator_name":"家族葬のファミーユ","rating_avg":4.3,"review_count":12},
    {"name":"やすらぎ会館津","slug":"mie-yasuragi-tsu","venue_type":"private_hall","description":"津市一身田エリアのやすらぎ会館。高田本山専修寺にほど近い立地です。","address":"三重県津市一身田町308","prefecture_slug":"mie","city_slug":"tsu","latitude":34.748,"longitude":136.508,"nearest_station":"JR紀勢本線 一身田駅","station_walk_minutes":5,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":345000},{"type":"ippanso","label":"一般葬プラン","priceFrom":630000}],"features":["家族葬対応","駅近"],"operator_name":"やすらぎ会館","rating_avg":4.0,"review_count":16},
    {"name":"津葬祭会館","slug":"mie-sousai-tsu","venue_type":"private_hall","description":"津市白塚エリアの葬祭会館。伊勢湾を望む立地で、穏やかな環境のお別れの場です。","address":"三重県津市白塚町5298","prefecture_slug":"mie","city_slug":"tsu","latitude":34.755,"longitude":136.545,"nearest_station":"近鉄名古屋線 白塚駅","station_walk_minutes":5,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":348000},{"type":"ippanso","label":"一般葬プラン","priceFrom":640000}],"features":["家族葬対応","駅近"],"operator_name":"津葬祭","rating_avg":3.9,"review_count":14},
    {"name":"法要殿津","slug":"mie-hoyoden-tsu","venue_type":"private_hall","description":"津市高茶屋エリアの法要殿。丁寧なサービスが地域の方に支持されています。","address":"三重県津市高茶屋小森上野町1068-2","prefecture_slug":"mie","city_slug":"tsu","latitude":34.695,"longitude":136.490,"nearest_station":"JR紀勢本線 高茶屋駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":18,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":355000},{"type":"ippanso","label":"一般葬プラン","priceFrom":640000}],"features":["家族葬対応","駅近"],"operator_name":"法要殿","rating_avg":4.0,"review_count":16},
    # === 鈴鹿市 7件（残り3件は次バッチ） ===
    {"name":"ティア鈴鹿","slug":"mie-tier-suzuka","venue_type":"private_hall","description":"鈴鹿市中心部のティア。近鉄白子駅から近く、鈴鹿サーキットにも近い便利な立地です。","address":"三重県鈴鹿市白子1-6-20","prefecture_slug":"mie","city_slug":"suzuka","latitude":34.825,"longitude":136.580,"nearest_station":"近鉄名古屋線 白子駅","station_walk_minutes":8,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":350000},{"type":"ippanso","label":"一般葬プラン","priceFrom":660000}],"features":["家族葬対応","駅近"],"operator_name":"ティア","rating_avg":4.2,"review_count":32},
    {"name":"紫雲殿鈴鹿","slug":"mie-shiunden-suzuka","venue_type":"private_hall","description":"鈴鹿市のメイン通り沿いの紫雲殿。広い駐車場を完備しています。","address":"三重県鈴鹿市神戸2-10-35","prefecture_slug":"mie","city_slug":"suzuka","latitude":34.833,"longitude":136.575,"nearest_station":"近鉄鈴鹿線 鈴鹿市駅","station_walk_minutes":8,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":92000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":340000},{"type":"ippanso","label":"一般葬プラン","priceFrom":640000}],"features":["家族葬対応","大駐車場"],"operator_name":"紫雲殿","rating_avg":4.1,"review_count":28},
    {"name":"セレモニーホール鈴鹿","slug":"mie-ceremony-suzuka","venue_type":"private_hall","description":"鈴鹿市平田エリアのセレモニーホール。国道23号線に近い便利な立地です。","address":"三重県鈴鹿市平田1-5-20","prefecture_slug":"mie","city_slug":"suzuka","latitude":34.820,"longitude":136.585,"nearest_station":"近鉄名古屋線 白子駅","station_walk_minutes":12,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":18,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":358000},{"type":"ippanso","label":"一般葬プラン","priceFrom":650000}],"features":["家族葬対応"],"operator_name":"セレモニーホール","rating_avg":4.0,"review_count":22},
    {"name":"鈴鹿市斎場","slug":"mie-suzuka-saijo","venue_type":"public_crematorium","description":"鈴鹿市が運営する公営火葬場・斎場。市民料金で利用できる公営施設です。","address":"三重県鈴鹿市加佐登町字西条1662","prefecture_slug":"mie","city_slug":"suzuka","latitude":34.865,"longitude":136.530,"nearest_station":"JR関西本線 加佐登駅","station_walk_minutes":15,"capacity_max":60,"hall_count":1,"has_crematorium":True,"parking_count":40,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":50000}],"features":["公営施設","火葬場併設"],"operator_name":"鈴鹿市","rating_avg":3.6,"review_count":35},
    {"name":"家族葬のファミーユ鈴鹿","slug":"mie-famillu-suzuka","venue_type":"private_hall","description":"鈴鹿市の家族葬専門ホール。少人数対応の温かい式場です。","address":"三重県鈴鹿市算所2-1-13","prefecture_slug":"mie","city_slug":"suzuka","latitude":34.830,"longitude":136.570,"nearest_station":"近鉄鈴鹿線 鈴鹿市駅","station_walk_minutes":5,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":85000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":288000}],"features":["家族葬対応","少人数対応","低価格","駅近"],"operator_name":"家族葬のファミーユ","rating_avg":4.4,"review_count":15},
    {"name":"ベルコ鈴鹿シティホール","slug":"mie-bellco-suzuka","venue_type":"private_hall","description":"鈴鹿市のベルコ葬儀会館。落ち着いた住宅街に位置しています。","address":"三重県鈴鹿市庄野羽山4-1-2","prefecture_slug":"mie","city_slug":"suzuka","latitude":34.845,"longitude":136.560,"nearest_station":"JR関西本線 加佐登駅","station_walk_minutes":10,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":18,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":348000}],"features":["家族葬対応"],"operator_name":"ベルコ","rating_avg":4.1,"review_count":20},
    {"name":"JA葬祭鈴鹿","slug":"mie-ja-suzuka","venue_type":"private_hall","description":"JA鈴鹿が運営する葬祭ホール。適正価格で地域の方に親しまれています。","address":"三重県鈴鹿市西条5-36","prefecture_slug":"mie","city_slug":"suzuka","latitude":34.838,"longitude":136.578,"nearest_station":"近鉄鈴鹿線 三日市駅","station_walk_minutes":8,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":290000},{"type":"ippanso","label":"一般葬プラン","priceFrom":530000}],"features":["家族葬対応","低価格"],"operator_name":"JA鈴鹿","rating_avg":3.9,"review_count":18},
]

for i in range(0, len(venues), 10):
    batch = venues[i:i+10]
    code = insert_batch(batch)
    print(f"バッチ {i//10+1}: {code} ({len(batch)}件)")
    time.sleep(1)

print(f"\n完了: 合計 {len(venues)} 件")
