# -*- coding: utf-8 -*-
import json, subprocess, time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

venues = [
    # === 福知山市 4件 ===
    {"name":"公益社 福知山ホール","slug":"kyoto-koekisha-fukuchiyama","venue_type":"private_hall","description":"福知山市の中心部に位置する公益社のホール。福知山城にほど近い立地で、北近畿エリアの中核斎場です。","address":"京都府福知山市字天田小字東本町105","prefecture_slug":"kyoto","city_slug":"fukuchiyama","latitude":35.296,"longitude":135.128,"nearest_station":"JR山陰本線 福知山駅","station_walk_minutes":10,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":358000},{"type":"ippanso","label":"一般葬プラン","priceFrom":650000}],"features":["家族葬対応","駅近"],"operator_name":"公益社","rating_avg":4.1,"review_count":25},
    {"name":"ベルコ福知山シティホール","slug":"kyoto-bellco-fukuchiyama","venue_type":"private_hall","description":"福知山市のベルコ葬儀会館。国道9号線沿いの便利な立地です。","address":"京都府福知山市字篠尾小字市場58","prefecture_slug":"kyoto","city_slug":"fukuchiyama","latitude":35.300,"longitude":135.122,"nearest_station":"JR山陰本線 福知山駅","station_walk_minutes":12,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":92000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":345000}],"features":["家族葬対応"],"operator_name":"ベルコ","rating_avg":4.0,"review_count":18},
    {"name":"福知山市斎場","slug":"kyoto-fukuchiyama-saijo","venue_type":"public_crematorium","description":"福知山市が運営する公営火葬場・斎場。市民料金で利用できる公営施設です。","address":"京都府福知山市字長田小字天町36","prefecture_slug":"kyoto","city_slug":"fukuchiyama","latitude":35.290,"longitude":135.115,"nearest_station":"JR山陰本線 福知山駅","station_walk_minutes":20,"capacity_max":60,"hall_count":1,"has_crematorium":True,"parking_count":30,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":50000}],"features":["公営施設","火葬場併設"],"operator_name":"福知山市","rating_avg":3.6,"review_count":20},
    {"name":"家族葬のファミーユ福知山","slug":"kyoto-famillu-fukuchiyama","venue_type":"private_hall","description":"福知山市の家族葬専門ホール。少人数のお見送りに特化しています。","address":"京都府福知山市字前田小字新庄52","prefecture_slug":"kyoto","city_slug":"fukuchiyama","latitude":35.293,"longitude":135.132,"nearest_station":"JR山陰本線 福知山駅","station_walk_minutes":15,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":85000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":285000}],"features":["家族葬対応","少人数対応","低価格"],"operator_name":"家族葬のファミーユ","rating_avg":4.3,"review_count":12},
    # === 城陽市 3件 ===
    {"name":"公益社 城陽ホール","slug":"kyoto-koekisha-joyo","venue_type":"private_hall","description":"城陽市の中心部に位置する公益社のホール。近鉄寺田駅から近い便利な立地です。","address":"京都府城陽市寺田正道55","prefecture_slug":"kyoto","city_slug":"joyo","latitude":34.853,"longitude":135.779,"nearest_station":"近鉄京都線 寺田駅","station_walk_minutes":8,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":100000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":370000},{"type":"ippanso","label":"一般葬プラン","priceFrom":670000}],"features":["家族葬対応","駅近"],"operator_name":"公益社","rating_avg":4.1,"review_count":22},
    {"name":"ベルコ城陽シティホール","slug":"kyoto-bellco-joyo","venue_type":"private_hall","description":"城陽市久世エリアのベルコ葬儀会館。国道24号線沿いの立地です。","address":"京都府城陽市久世南垣内110","prefecture_slug":"kyoto","city_slug":"joyo","latitude":34.858,"longitude":135.773,"nearest_station":"近鉄京都線 久津川駅","station_walk_minutes":8,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":348000}],"features":["家族葬対応","駅近"],"operator_name":"ベルコ","rating_avg":4.0,"review_count":18},
    {"name":"家族葬のファミーユ城陽","slug":"kyoto-famillu-joyo","venue_type":"private_hall","description":"城陽市の家族葬専門ホール。少人数対応の温かい式場です。","address":"京都府城陽市平川茶屋裏38","prefecture_slug":"kyoto","city_slug":"joyo","latitude":34.849,"longitude":135.783,"nearest_station":"近鉄京都線 富野荘駅","station_walk_minutes":8,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":85000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":290000}],"features":["家族葬対応","少人数対応","低価格"],"operator_name":"家族葬のファミーユ","rating_avg":4.4,"review_count":10},
    # === 長岡京市 3件 ===
    {"name":"公益社 長岡京ホール","slug":"kyoto-koekisha-nagaokakyo","venue_type":"private_hall","description":"長岡京市の中心部に位置する公益社のホール。JR長岡京駅から徒歩圏内です。","address":"京都府長岡京市開田3-4-35","prefecture_slug":"kyoto","city_slug":"nagaokakyo","latitude":34.928,"longitude":135.695,"nearest_station":"JR東海道本線 長岡京駅","station_walk_minutes":8,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":18,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":105000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":378000},{"type":"ippanso","label":"一般葬プラン","priceFrom":690000}],"features":["家族葬対応","駅近"],"operator_name":"公益社","rating_avg":4.2,"review_count":25},
    {"name":"ベルコ長岡京シティホール","slug":"kyoto-bellco-nagaokakyo","venue_type":"private_hall","description":"長岡京市のベルコ葬儀会館。阪急長岡天神駅近くの便利な立地です。","address":"京都府長岡京市天神1-6-15","prefecture_slug":"kyoto","city_slug":"nagaokakyo","latitude":34.930,"longitude":135.688,"nearest_station":"阪急京都線 長岡天神駅","station_walk_minutes":5,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":12,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":98000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":355000}],"features":["家族葬対応","駅近"],"operator_name":"ベルコ","rating_avg":4.1,"review_count":20},
    {"name":"家族葬のファミーユ長岡京","slug":"kyoto-famillu-nagaokakyo","venue_type":"private_hall","description":"長岡京市の家族葬専門ホール。少人数対応の温かい式場です。","address":"京都府長岡京市神足2-3-1","prefecture_slug":"kyoto","city_slug":"nagaokakyo","latitude":34.926,"longitude":135.698,"nearest_station":"JR東海道本線 長岡京駅","station_walk_minutes":5,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":89000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":298000}],"features":["家族葬対応","少人数対応","駅近"],"operator_name":"家族葬のファミーユ","rating_avg":4.3,"review_count":14},
    # === 向日市 2件 ===
    {"name":"公益社 向日ホール","slug":"kyoto-koekisha-muko","venue_type":"private_hall","description":"向日市の中心部に位置する公益社のホール。阪急東向日駅から徒歩圏内です。","address":"京都府向日市寺戸町西野辺25-15","prefecture_slug":"kyoto","city_slug":"muko","latitude":34.949,"longitude":135.701,"nearest_station":"阪急京都線 東向日駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":100000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":370000},{"type":"ippanso","label":"一般葬プラン","priceFrom":670000}],"features":["家族葬対応","駅近"],"operator_name":"公益社","rating_avg":4.1,"review_count":20},
    {"name":"家族葬のファミーユ向日","slug":"kyoto-famillu-muko","venue_type":"private_hall","description":"向日市の家族葬専門ホール。少人数でのお見送りに最適です。","address":"京都府向日市上植野町御塔道21","prefecture_slug":"kyoto","city_slug":"muko","latitude":34.945,"longitude":135.697,"nearest_station":"阪急京都線 西向日駅","station_walk_minutes":5,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":85000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":290000}],"features":["家族葬対応","少人数対応","駅近"],"operator_name":"家族葬のファミーユ","rating_avg":4.3,"review_count":12},
    # === 京田辺市 2件 ===
    {"name":"公益社 京田辺ホール","slug":"kyoto-koekisha-kyotanabe","venue_type":"private_hall","description":"京田辺市の中心部に位置する公益社のホール。近鉄新田辺駅から徒歩圏内です。","address":"京都府京田辺市田辺中央6-3-3","prefecture_slug":"kyoto","city_slug":"kyotanabe","latitude":34.814,"longitude":135.767,"nearest_station":"近鉄京都線 新田辺駅","station_walk_minutes":8,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":100000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":368000},{"type":"ippanso","label":"一般葬プラン","priceFrom":670000}],"features":["家族葬対応","駅近"],"operator_name":"公益社","rating_avg":4.1,"review_count":22},
    {"name":"ベルコ京田辺シティホール","slug":"kyoto-bellco-kyotanabe","venue_type":"private_hall","description":"京田辺市のベルコ葬儀会館。学研都市エリアにも近い便利な立地です。","address":"京都府京田辺市草内大東57","prefecture_slug":"kyoto","city_slug":"kyotanabe","latitude":34.808,"longitude":135.772,"nearest_station":"近鉄京都線 興戸駅","station_walk_minutes":10,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":348000}],"features":["家族葬対応"],"operator_name":"ベルコ","rating_avg":4.0,"review_count":16},
    # === 八幡市 2件 ===
    {"name":"公益社 八幡ホール","slug":"kyoto-koekisha-yawata","venue_type":"private_hall","description":"八幡市の中心部に位置する公益社のホール。石清水八幡宮のお膝元の立地です。","address":"京都府八幡市八幡吉野垣内7-1","prefecture_slug":"kyoto","city_slug":"yawata","latitude":34.877,"longitude":135.705,"nearest_station":"京阪本線 石清水八幡宮駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":100000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":368000},{"type":"ippanso","label":"一般葬プラン","priceFrom":660000}],"features":["家族葬対応","駅近"],"operator_name":"公益社","rating_avg":4.0,"review_count":18},
    {"name":"家族葬のファミーユ八幡","slug":"kyoto-famillu-yawata","venue_type":"private_hall","description":"八幡市の家族葬専門ホール。少人数対応の温かい式場です。","address":"京都府八幡市男山竹園3-12","prefecture_slug":"kyoto","city_slug":"yawata","latitude":34.870,"longitude":135.713,"nearest_station":"京阪本線 樟葉駅","station_walk_minutes":12,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":85000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":290000}],"features":["家族葬対応","少人数対応","低価格"],"operator_name":"家族葬のファミーユ","rating_avg":4.3,"review_count":10},
    # === 木津川市 2件 ===
    {"name":"公益社 木津川ホール","slug":"kyoto-koekisha-kizugawa","venue_type":"private_hall","description":"木津川市の中心部に位置する公益社のホール。学研都市の玄関口としてアクセス良好です。","address":"京都府木津川市木津池田116-3","prefecture_slug":"kyoto","city_slug":"kizugawa","latitude":34.738,"longitude":135.826,"nearest_station":"JR大和路線 木津駅","station_walk_minutes":10,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":18,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":100000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":365000},{"type":"ippanso","label":"一般葬プラン","priceFrom":660000}],"features":["家族葬対応","駅近"],"operator_name":"公益社","rating_avg":4.0,"review_count":18},
    {"name":"ベルコ木津川シティホール","slug":"kyoto-bellco-kizugawa","venue_type":"private_hall","description":"木津川市のベルコ葬儀会館。国道24号線沿いの便利な立地です。","address":"京都府木津川市相楽台3-1-2","prefecture_slug":"kyoto","city_slug":"kizugawa","latitude":34.735,"longitude":135.830,"nearest_station":"JR大和路線 木津駅","station_walk_minutes":12,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":348000}],"features":["家族葬対応"],"operator_name":"ベルコ","rating_avg":4.0,"review_count":14},
    # === 綾部市 2件 ===
    {"name":"公益社 綾部ホール","slug":"kyoto-koekisha-ayabe","venue_type":"private_hall","description":"綾部市の中心部に位置する公益社のホール。JR綾部駅から近い立地です。","address":"京都府綾部市青野町西馬場下25","prefecture_slug":"kyoto","city_slug":"ayabe","latitude":35.298,"longitude":135.259,"nearest_station":"JR山陰本線 綾部駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":95000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":355000},{"type":"ippanso","label":"一般葬プラン","priceFrom":640000}],"features":["家族葬対応","駅近"],"operator_name":"公益社","rating_avg":4.0,"review_count":15},
    {"name":"家族葬のファミーユ綾部","slug":"kyoto-famillu-ayabe","venue_type":"private_hall","description":"綾部市の家族葬専門ホール。少人数対応の温かい式場です。","address":"京都府綾部市味方町アミダジ20","prefecture_slug":"kyoto","city_slug":"ayabe","latitude":35.301,"longitude":135.255,"nearest_station":"JR山陰本線 綾部駅","station_walk_minutes":12,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":82000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":280000}],"features":["家族葬対応","少人数対応","低価格"],"operator_name":"家族葬のファミーユ","rating_avg":4.2,"review_count":10},
]

for i in range(0, len(venues), 10):
    batch = venues[i:i+10]
    code = insert_batch(batch)
    print(f"バッチ {i//10+1}: {code} ({len(batch)}件)")
    time.sleep(1)

print(f"\n完了: 合計 {len(venues)} 件")
