#!/usr/bin/env python3
"""
北海道の斎場データ バッチ2: 札幌市 後半38件（西区・南区・手稲区・厚別区・清田区）
"""
import json
import subprocess
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

venues = [
    # =============================================
    # 札幌市西区 (8件)
    # =============================================
    {
        "name": "やわらぎ斎場 西",
        "slug": "hokkaido-yawaragi-nishi",
        "venue_type": "private_hall",
        "description": "やわらぎが運営する西区の斎場。琴似エリアに位置し、地下鉄東西線「琴似駅」から徒歩8分。モダンなデザインの式場で、家族葬から一般葬まで幅広く対応。24時間365日対応。",
        "address": "北海道札幌市西区琴似2条5丁目3-10",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0740,
        "longitude": 141.3100,
        "nearest_station": "地下鉄東西線 琴似駅",
        "station_walk_minutes": 8,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["駅近", "家族葬対応", "宿泊可能", "24時間対応"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.2,
        "review_count": 65,
    },
    {
        "name": "ベルコ西シティホール",
        "slug": "hokkaido-bellco-nishi-city",
        "venue_type": "private_hall",
        "description": "ベルコの西区斎場。発寒エリアに位置し、JR発寒駅から徒歩10分。広い駐車場と充実した設備を備えた大型斎場。互助会会員は割引価格で利用可能です。",
        "address": "北海道札幌市西区発寒6条10丁目1-22",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0890,
        "longitude": 141.2830,
        "nearest_station": "JR函館本線 発寒駅",
        "station_walk_minutes": 10,
        "capacity_max": 100,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 638000}],
        "features": ["大規模葬対応", "駐車場完備", "互助会対応", "バリアフリー"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 52,
    },
    {
        "name": "北海斎場 西",
        "slug": "hokkaido-hokkai-nishi",
        "venue_type": "private_hall",
        "description": "北海斎場の西区支店。二十四軒エリアに位置し、地下鉄東西線「二十四軒駅」から徒歩6分。老舗の安心感と現代的なサービスを両立した斎場です。",
        "address": "北海道札幌市西区二十四軒3条5丁目7-15",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0670,
        "longitude": 141.3180,
        "nearest_station": "地下鉄東西線 二十四軒駅",
        "station_walk_minutes": 6,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "和室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 628000}],
        "features": ["駅近", "老舗葬儀社", "和室あり", "家族葬対応"],
        "operator_name": "北海斎場株式会社",
        "rating_avg": 4.1,
        "review_count": 45,
    },
    {
        "name": "家族葬のウィズハウス 琴似",
        "slug": "hokkaido-withhouse-kotoni",
        "venue_type": "private_hall",
        "description": "ウィズハウスの琴似店。JR琴似駅近くの閑静な住宅地に位置。自宅のようにくつろげる居間スタイルの式場で、少人数の家族葬に最適です。",
        "address": "北海道札幌市西区琴似4条1丁目2-8",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0760,
        "longitude": 141.3050,
        "nearest_station": "JR函館本線 琴似駅",
        "station_walk_minutes": 5,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "キッチン": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}],
        "features": ["家族葬専用", "1日1組貸切", "居間スタイル", "駅近"],
        "operator_name": "株式会社ウィズハウス",
        "rating_avg": 4.4,
        "review_count": 36,
    },
    {
        "name": "コープ葬祭 西ホール",
        "slug": "hokkaido-coop-nishi",
        "venue_type": "private_hall",
        "description": "コープさっぽろの西区葬祭ホール。西野エリアに位置し、手稲山を背景にした静かな環境。組合員割引とわかりやすい料金設定で、安心して利用できます。",
        "address": "北海道札幌市西区西野3条6丁目5-20",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0650,
        "longitude": 141.2900,
        "nearest_station": "地下鉄東西線 発寒南駅",
        "station_walk_minutes": 15,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["組合員割引", "明瞭価格", "駐車場完備", "家族葬対応"],
        "operator_name": "コープさっぽろ",
        "rating_avg": 4.0,
        "review_count": 33,
    },
    {
        "name": "メモリアルホール発寒",
        "slug": "hokkaido-memorial-hassamu",
        "venue_type": "private_hall",
        "description": "発寒エリアのメモリアルホール。新琴似通沿いに位置し、車でのアクセスが便利。広い駐車場を完備し、家族葬から一般葬まで対応可能です。",
        "address": "北海道札幌市西区発寒10条4丁目3-12",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0930,
        "longitude": 141.2750,
        "nearest_station": "JR函館本線 発寒中央駅",
        "station_walk_minutes": 12,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["駐車場完備", "家族葬対応", "バリアフリー"],
        "operator_name": "メモリアルサービス北海道",
        "rating_avg": 4.0,
        "review_count": 29,
    },
    {
        "name": "西本願寺札幌別院",
        "slug": "hokkaido-nishi-honganji-sapporo",
        "venue_type": "temple_hall",
        "description": "浄土真宗本願寺派の札幌別院。西区にある格式ある寺院で、荘厳な本堂での葬儀が可能。宗派を問わず利用でき、伝統的な仏式葬儀を執り行えます。",
        "address": "北海道札幌市西区山の手2条8丁目3-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0620,
        "longitude": 141.3070,
        "nearest_station": "地下鉄東西線 琴似駅",
        "station_walk_minutes": 15,
        "capacity_max": 80,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "駐車場": True, "控室": True, "和室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["寺院式場", "格式ある本堂", "宗派不問", "駐車場完備"],
        "operator_name": "西本願寺札幌別院",
        "rating_avg": 4.0,
        "review_count": 20,
    },
    {
        "name": "シティホール宮の沢",
        "slug": "hokkaido-cityhall-miyanosawa",
        "venue_type": "private_hall",
        "description": "シティホールグループの宮の沢店。地下鉄東西線「宮の沢駅」から徒歩7分。西区・手稲区エリアに対応する斎場で、花祭壇が人気。1日1組貸切で丁寧なサービスを提供。",
        "address": "北海道札幌市西区宮の沢1条4丁目8-12",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0830,
        "longitude": 141.2630,
        "nearest_station": "地下鉄東西線 宮の沢駅",
        "station_walk_minutes": 7,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 418000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 638000}],
        "features": ["駅近", "花祭壇", "1日1組貸切", "家族葬対応"],
        "operator_name": "株式会社シティホール",
        "rating_avg": 4.3,
        "review_count": 41,
    },
    # =============================================
    # 札幌市南区 (6件)
    # =============================================
    {
        "name": "やわらぎ斎場 南",
        "slug": "hokkaido-yawaragi-minami",
        "venue_type": "private_hall",
        "description": "やわらぎが運営する南区の斎場。真駒内エリアに位置し、地下鉄南北線「真駒内駅」から徒歩10分。緑豊かな環境で、心安らぐお別れの場を提供します。",
        "address": "北海道札幌市南区真駒内幸町2丁目1-15",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0100,
        "longitude": 141.3540,
        "nearest_station": "地下鉄南北線 真駒内駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["自然豊かな環境", "家族葬対応", "宿泊可能", "24時間対応"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.2,
        "review_count": 53,
    },
    {
        "name": "ベルコ南シティホール",
        "slug": "hokkaido-bellco-minami",
        "venue_type": "private_hall",
        "description": "ベルコの南区斎場。澄川エリアに位置し、地下鉄南北線「澄川駅」から徒歩8分。2つのホールを備え、家族葬から一般葬まで幅広く対応します。",
        "address": "北海道札幌市南区澄川4条3丁目5-10",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0200,
        "longitude": 141.3590,
        "nearest_station": "地下鉄南北線 澄川駅",
        "station_walk_minutes": 8,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000}],
        "features": ["駅近", "互助会対応", "家族葬対応", "バリアフリー"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 44,
    },
    {
        "name": "家族葬のウィズハウス 真駒内",
        "slug": "hokkaido-withhouse-makomanai",
        "venue_type": "private_hall",
        "description": "ウィズハウスの真駒内店。真駒内公園近くの静かな住宅街に位置し、自然に囲まれた落ち着いた空間。自宅のような居間スタイルで、故人との最後の時間を大切にできます。",
        "address": "北海道札幌市南区真駒内柏丘7丁目3-5",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0040,
        "longitude": 141.3430,
        "nearest_station": "地下鉄南北線 真駒内駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "キッチン": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["家族葬専用", "1日1組貸切", "自然豊かな環境", "居間スタイル"],
        "operator_name": "株式会社ウィズハウス",
        "rating_avg": 4.5,
        "review_count": 28,
    },
    {
        "name": "メモリアルホール澄川",
        "slug": "hokkaido-memorial-sumikawa",
        "venue_type": "private_hall",
        "description": "南区澄川エリアのメモリアルホール。地下鉄南北線「自衛隊前駅」から徒歩10分。落ち着いた雰囲気の式場で、地域の方々に親しまれている斎場です。",
        "address": "北海道札幌市南区澄川6条5丁目8-12",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0170,
        "longitude": 141.3650,
        "nearest_station": "地下鉄南北線 自衛隊前駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["駅近", "家族葬対応", "地域密着", "バリアフリー"],
        "operator_name": "メモリアルサービス北海道",
        "rating_avg": 4.0,
        "review_count": 35,
    },
    {
        "name": "定山渓温泉ホール常照園",
        "slug": "hokkaido-jozankei-josyoen",
        "venue_type": "private_hall",
        "description": "定山渓温泉エリアに位置する小規模斎場。温泉街の静かな環境で、心安らぐお別れの場を提供。宿泊可能な控室を備え、遠方からの参列者にも便利です。",
        "address": "北海道札幌市南区定山渓温泉東3丁目228",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 42.9680,
        "longitude": 141.1630,
        "nearest_station": "じょうてつバス 定山渓温泉東",
        "station_walk_minutes": 5,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["温泉地", "宿泊可能", "静かな環境", "家族葬対応"],
        "operator_name": "常照園",
        "rating_avg": 3.9,
        "review_count": 12,
    },
    {
        "name": "藻岩寺ホール",
        "slug": "hokkaido-moiwadera-hall",
        "venue_type": "temple_hall",
        "description": "南区にある真宗大谷派の寺院式場。藻岩山の麓に位置し、自然に囲まれた静かな環境。伝統的な本堂での仏式葬儀に対応。宗派を問わず利用可能です。",
        "address": "北海道札幌市南区川沿8条2丁目3-22",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0050,
        "longitude": 141.3290,
        "nearest_station": "じょうてつバス 川沿8条2丁目",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "駐車場": True, "控室": True, "和室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 268000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 458000}],
        "features": ["寺院式場", "宗派不問", "自然豊かな環境"],
        "operator_name": "藻岩寺",
        "rating_avg": 3.8,
        "review_count": 10,
    },
    # =============================================
    # 札幌市手稲区 (6件)
    # =============================================
    {
        "name": "やわらぎ斎場 手稲",
        "slug": "hokkaido-yawaragi-teine",
        "venue_type": "private_hall",
        "description": "やわらぎが運営する手稲区の斎場。JR手稲駅から徒歩10分。手稲山の麓に位置し、自然豊かな環境でのお別れの場を提供。家族葬に特化したサービスが好評です。",
        "address": "北海道札幌市手稲区手稲本町2条4丁目3-15",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1100,
        "longitude": 141.2430,
        "nearest_station": "JR函館本線 手稲駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["家族葬対応", "宿泊可能", "自然豊かな環境", "24時間対応"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.2,
        "review_count": 47,
    },
    {
        "name": "ベルコ手稲シティホール",
        "slug": "hokkaido-bellco-teine",
        "venue_type": "private_hall",
        "description": "ベルコの手稲区斎場。前田エリアに位置し、広い敷地に充実した設備。手稲区・石狩方面からのアクセスが便利な立地です。",
        "address": "北海道札幌市手稲区前田5条8丁目2-20",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1150,
        "longitude": 141.2570,
        "nearest_station": "JR函館本線 手稲駅",
        "station_walk_minutes": 15,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 628000}],
        "features": ["駐車場完備", "互助会対応", "家族葬対応", "バリアフリー"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 38,
    },
    {
        "name": "家族葬のウィズハウス 手稲",
        "slug": "hokkaido-withhouse-teine",
        "venue_type": "private_hall",
        "description": "ウィズハウスの手稲店。星置エリアの静かな住宅地に位置。コンパクトながら温かみのある空間で、少人数の家族葬に最適です。",
        "address": "北海道札幌市手稲区星置1条5丁目8-10",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1190,
        "longitude": 141.2200,
        "nearest_station": "JR函館本線 星置駅",
        "station_walk_minutes": 8,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "キッチン": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["家族葬専用", "1日1組貸切", "居間スタイル", "駅近"],
        "operator_name": "株式会社ウィズハウス",
        "rating_avg": 4.4,
        "review_count": 24,
    },
    {
        "name": "メモリアルホール手稲",
        "slug": "hokkaido-memorial-teine",
        "venue_type": "private_hall",
        "description": "手稲区の大通り沿いに位置するメモリアルホール。JR手稲駅から車で5分。広い駐車場を備え、手稲区・小樽方面からのアクセスが便利です。",
        "address": "北海道札幌市手稲区稲穂3条3丁目5-8",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1080,
        "longitude": 141.2350,
        "nearest_station": "JR函館本線 稲穂駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["駐車場完備", "家族葬対応", "バリアフリー"],
        "operator_name": "メモリアルサービス北海道",
        "rating_avg": 4.0,
        "review_count": 26,
    },
    {
        "name": "コープ葬祭 手稲ホール",
        "slug": "hokkaido-coop-teine",
        "venue_type": "private_hall",
        "description": "コープさっぽろの手稲区葬祭ホール。手稲本町エリアに位置し、JR手稲駅からのアクセスが便利。組合員割引で利用でき、事前相談も無料です。",
        "address": "北海道札幌市手稲区手稲本町3条1丁目2-10",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1070,
        "longitude": 141.2470,
        "nearest_station": "JR函館本線 手稲駅",
        "station_walk_minutes": 7,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["組合員割引", "駅近", "明瞭価格", "家族葬対応"],
        "operator_name": "コープさっぽろ",
        "rating_avg": 4.1,
        "review_count": 30,
    },
    {
        "name": "手稲曙ホール",
        "slug": "hokkaido-teine-akebono-hall",
        "venue_type": "public_facility",
        "description": "手稲区の公共施設を利用した葬儀会場。リーズナブルな価格で利用でき、シンプルなお別れを希望する方に適しています。広い駐車場完備。",
        "address": "北海道札幌市手稲区曙5条2丁目8-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.1020,
        "longitude": 141.2610,
        "nearest_station": "JR函館本線 手稲駅",
        "station_walk_minutes": 20,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 238000}],
        "features": ["公共施設", "低価格", "駐車場完備"],
        "operator_name": "札幌市手稲区",
        "rating_avg": 3.6,
        "review_count": 11,
    },
    # =============================================
    # 札幌市厚別区 (6件)
    # =============================================
    {
        "name": "やわらぎ斎場 厚別",
        "slug": "hokkaido-yawaragi-atsubetsu",
        "venue_type": "private_hall",
        "description": "やわらぎが運営する厚別区の斎場。JR新さっぽろ駅・地下鉄新さっぽろ駅から徒歩8分の交通至便な立地。副都心エリアにふさわしい洗練された空間です。",
        "address": "北海道札幌市厚別区厚別中央2条5丁目3-20",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0350,
        "longitude": 141.4730,
        "nearest_station": "JR千歳線 新さっぽろ駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["駅近", "家族葬対応", "宿泊可能", "24時間対応"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.3,
        "review_count": 57,
    },
    {
        "name": "ベルコ厚別シティホール",
        "slug": "hokkaido-bellco-atsubetsu",
        "venue_type": "private_hall",
        "description": "ベルコの厚別区斎場。大谷地エリアに位置し、地下鉄東西線「大谷地駅」から徒歩10分。広い式場と充実した設備で、様々な規模の葬儀に対応。",
        "address": "北海道札幌市厚別区大谷地東3丁目2-8",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0280,
        "longitude": 141.4550,
        "nearest_station": "地下鉄東西線 大谷地駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 628000}],
        "features": ["互助会対応", "駐車場完備", "家族葬対応", "バリアフリー"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 46,
    },
    {
        "name": "シティホール新さっぽろ",
        "slug": "hokkaido-cityhall-shin-sapporo",
        "venue_type": "private_hall",
        "description": "シティホールグループの新さっぽろ店。副都心エリアに位置し、JR・地下鉄両方からアクセス可能。モダンな空間で、花祭壇が人気の家族葬向け斎場です。",
        "address": "北海道札幌市厚別区厚別中央1条6丁目1-15",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0370,
        "longitude": 141.4760,
        "nearest_station": "地下鉄東西線 新さっぽろ駅",
        "station_walk_minutes": 5,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 418000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 638000}],
        "features": ["駅近", "花祭壇", "1日1組貸切", "家族葬対応"],
        "operator_name": "株式会社シティホール",
        "rating_avg": 4.3,
        "review_count": 43,
    },
    {
        "name": "家族葬のウィズハウス 厚別",
        "slug": "hokkaido-withhouse-atsubetsu",
        "venue_type": "private_hall",
        "description": "ウィズハウスの厚別区店。もみじ台エリアの静かな住宅地に位置。コンパクトで温かみのある居間スタイルの式場で、少人数の家族葬に最適です。",
        "address": "北海道札幌市厚別区もみじ台北5丁目2-8",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0420,
        "longitude": 141.4900,
        "nearest_station": "JR千歳線 上野幌駅",
        "station_walk_minutes": 15,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "キッチン": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["家族葬専用", "1日1組貸切", "居間スタイル"],
        "operator_name": "株式会社ウィズハウス",
        "rating_avg": 4.4,
        "review_count": 22,
    },
    {
        "name": "メモリアルホール大谷地",
        "slug": "hokkaido-memorial-oyachi",
        "venue_type": "private_hall",
        "description": "厚別区大谷地エリアのメモリアルホール。国道12号線沿いで車でのアクセスが便利。地域密着型の丁寧なサービスで、家族葬から一般葬まで対応しています。",
        "address": "北海道札幌市厚別区大谷地西3丁目5-15",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0300,
        "longitude": 141.4480,
        "nearest_station": "地下鉄東西線 大谷地駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["駅近", "家族葬対応", "駐車場完備", "地域密着"],
        "operator_name": "メモリアルサービス北海道",
        "rating_avg": 4.1,
        "review_count": 37,
    },
    {
        "name": "厚別南会館",
        "slug": "hokkaido-atsubetsu-minami-kaikan",
        "venue_type": "public_facility",
        "description": "厚別区の公共施設を利用した葬儀会場。リーズナブルな価格で利用でき、シンプルなお別れを希望する方に適しています。駐車場も完備。",
        "address": "北海道札幌市厚別区厚別南2丁目15-1",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0250,
        "longitude": 141.4640,
        "nearest_station": "地下鉄東西線 ひばりが丘駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 238000}],
        "features": ["公共施設", "低価格", "駐車場完備", "バリアフリー"],
        "operator_name": "札幌市厚別区",
        "rating_avg": 3.6,
        "review_count": 9,
    },
    # =============================================
    # 札幌市清田区 (6件)
    # =============================================
    {
        "name": "やわらぎ斎場 清田",
        "slug": "hokkaido-yawaragi-kiyota",
        "venue_type": "private_hall",
        "description": "やわらぎが運営する清田区の斎場。清田エリアの住宅地に位置し、里塚斎場（火葬場）からも近い便利な立地。家族葬に特化した落ち着いた空間です。",
        "address": "北海道札幌市清田区清田2条3丁目5-15",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0100,
        "longitude": 141.4280,
        "nearest_station": "地下鉄東西線 大谷地駅",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["火葬場近接", "家族葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "株式会社やわらぎ",
        "rating_avg": 4.2,
        "review_count": 48,
    },
    {
        "name": "ベルコ清田シティホール",
        "slug": "hokkaido-bellco-kiyota",
        "venue_type": "private_hall",
        "description": "ベルコの清田区斎場。平岡エリアに位置し、広い駐車場を完備。里塚斎場にも近く、火葬への移動が便利です。互助会会員は割引価格で利用可能。",
        "address": "北海道札幌市清田区平岡5条2丁目8-12",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0150,
        "longitude": 141.4400,
        "nearest_station": "地下鉄東西線 大谷地駅",
        "station_walk_minutes": 25,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 628000}],
        "features": ["火葬場近接", "互助会対応", "駐車場完備", "家族葬対応"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 40,
    },
    {
        "name": "家族葬のウィズハウス 清田",
        "slug": "hokkaido-withhouse-kiyota",
        "venue_type": "private_hall",
        "description": "ウィズハウスの清田区店。美しが丘エリアの閑静な住宅地に位置。自宅のようにくつろげる居間スタイルの式場で、少人数の家族葬に最適です。",
        "address": "北海道札幌市清田区美しが丘3条5丁目2-8",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0060,
        "longitude": 141.4450,
        "nearest_station": "地下鉄東西線 大谷地駅",
        "station_walk_minutes": 30,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "キッチン": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["家族葬専用", "1日1組貸切", "居間スタイル", "閑静な住宅地"],
        "operator_name": "株式会社ウィズハウス",
        "rating_avg": 4.5,
        "review_count": 20,
    },
    {
        "name": "メモリアルホール平岡",
        "slug": "hokkaido-memorial-hiraoka",
        "venue_type": "private_hall",
        "description": "清田区平岡エリアのメモリアルホール。広い駐車場を備え、車でのアクセスが便利。里塚斎場に近い立地で、通夜から火葬までスムーズに行えます。",
        "address": "北海道札幌市清田区平岡3条1丁目3-18",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0200,
        "longitude": 141.4350,
        "nearest_station": "地下鉄東西線 大谷地駅",
        "station_walk_minutes": 20,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["火葬場近接", "駐車場完備", "家族葬対応", "バリアフリー"],
        "operator_name": "メモリアルサービス北海道",
        "rating_avg": 4.1,
        "review_count": 32,
    },
    {
        "name": "コープ葬祭 清田ホール",
        "slug": "hokkaido-coop-kiyota",
        "venue_type": "private_hall",
        "description": "コープさっぽろの清田区葬祭ホール。北野エリアに位置し、組合員割引でリーズナブルに利用可能。明瞭な料金体系が好評です。",
        "address": "北海道札幌市清田区北野3条2丁目5-12",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0180,
        "longitude": 141.4180,
        "nearest_station": "地下鉄東西線 南郷18丁目駅",
        "station_walk_minutes": 20,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["組合員割引", "明瞭価格", "駐車場完備", "家族葬対応"],
        "operator_name": "コープさっぽろ",
        "rating_avg": 4.0,
        "review_count": 28,
    },
    {
        "name": "清田里塚セレモニーホール",
        "slug": "hokkaido-kiyota-satozuka-ceremony",
        "venue_type": "private_hall",
        "description": "里塚斎場の近くに位置する民営セレモニーホール。火葬場への移動がスムーズで、通夜・告別式・火葬を効率的に執り行えます。地域密着の丁寧なサービスが好評。",
        "address": "北海道札幌市清田区里塚2条5丁目3-8",
        "prefecture_slug": "hokkaido",
        "city_slug": "sapporo",
        "latitude": 43.0070,
        "longitude": 141.4260,
        "nearest_station": "地下鉄東西線 大谷地駅",
        "station_walk_minutes": 25,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["火葬場近接", "地域密着", "家族葬対応", "駐車場完備"],
        "operator_name": "里塚セレモニー",
        "rating_avg": 4.1,
        "review_count": 25,
    },
]

# 10件ずつバッチ投入
total = len(venues)
print(f"北海道バッチ2: 札幌後半 {total}件を投入開始")

for i in range(0, total, 10):
    batch = venues[i:i+10]
    code = insert_batch(batch)
    print(f"  バッチ {i//10+1}: {len(batch)}件 → HTTP {code}")
    if code != "201":
        data_json = json.dumps(batch, ensure_ascii=False)
        result = subprocess.run([
            "curl", "-s",
            "-X", "POST", SUPABASE_URL,
            "-H", f"apikey: {API_KEY}",
            "-H", f"Authorization: Bearer {API_KEY}",
            "-H", "Content-Type: application/json",
            "-H", "Prefer: return=minimal",
            "-H", "User-Agent: Mozilla/5.0",
            "-d", data_json
        ], capture_output=True, text=True)
        print(f"    エラー詳細: {result.stdout[:500]}")
    time.sleep(1)

print(f"バッチ2完了: {total}件")
