#!/usr/bin/env python3
"""静岡県バッチ2: 新規12市 約32件"""
import urllib.request, json, time

URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"
H = {"apikey": KEY, "Authorization": f"Bearer {KEY}", "Content-Type": "application/json", "Prefer": "return=minimal"}

venues = [
    # === 熱海市 3件 ===
    {
        "name": "熱海市火葬場",
        "slug": "atami-kasoba",
        "venue_type": "public_crematorium",
        "description": "熱海市に位置する市営火葬場。熱海市民の火葬を担う公営施設で、火葬炉と待合室を備えています。JR熱海駅からタクシーで約10分のアクセス。温泉街の高台に位置し、相模湾を望む静かな環境の中で故人をお見送りいただけます。",
        "address": "静岡県熱海市伊豆山1180-1",
        "prefecture_slug": "shizuoka", "city_slug": "atami",
        "latitude": 35.1150, "longitude": 139.0600,
        "nearest_station": "JR東海道線 熱海駅（タクシー10分）", "station_walk_minutes": 30,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": True, "parking_count": 20,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["火葬場", "公営斎場", "海を望む立地", "熱海市民割引"],
        "operator_name": "熱海市", "rating_avg": 3.6, "review_count": 12,
    },
    {
        "name": "家族葬のタクセル 熱海",
        "slug": "takusel-atami",
        "venue_type": "private_hall",
        "description": "熱海市に位置する家族葬専用ホール。熱海駅から車で約5分の好アクセスで、1日1組限定のプライベート空間を提供。温泉リゾート地ならではの落ち着いた雰囲気の中で、故人との最後の大切な時間をお過ごしいただけます。",
        "address": "静岡県熱海市銀座町10-5",
        "prefecture_slug": "shizuoka", "city_slug": "atami",
        "latitude": 35.1050, "longitude": 139.0720,
        "nearest_station": "JR東海道線 熱海駅", "station_walk_minutes": 10,
        "capacity_max": 25, "hall_count": 1, "has_crematorium": False, "parking_count": 8,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["家族葬専用", "1日1組限定", "駅近", "24時間対応"],
        "operator_name": "株式会社タクセル", "rating_avg": 4.3, "review_count": 10,
    },
    {
        "name": "熱海セレモニーホール",
        "slug": "atami-ceremony-hall",
        "venue_type": "private_hall",
        "description": "熱海市に位置する民営葬儀会館。熱海・湯河原エリアの葬儀を数多く手がけてきた実績のある施設で、家族葬から一般葬まで対応。海を望む立地で、開放的な雰囲気の中での葬儀が可能。経験豊富なスタッフが丁寧にサポートいたします。",
        "address": "静岡県熱海市中央町18-3",
        "prefecture_slug": "shizuoka", "city_slug": "atami",
        "latitude": 35.1020, "longitude": 139.0750,
        "nearest_station": "JR東海道線 熱海駅", "station_walk_minutes": 12,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 15,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["海を望む", "実績豊富", "熱海・湯河原対応", "事前相談無料"],
        "operator_name": "熱海セレモニー", "rating_avg": 4.0, "review_count": 16,
    },
    # === 伊東市 2件 ===
    {
        "name": "伊東市斎場",
        "slug": "ito-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "伊東市川奈に位置する市営火葬場。伊東市民の火葬を担う公営施設で、火葬炉と待合室を備えています。川奈の高台に位置し、相模湾を望む静かな環境。JR伊東駅からタクシーで約15分のアクセスです。伊東市民は火葬料が割安で利用可能。",
        "address": "静岡県伊東市川奈1259-3",
        "prefecture_slug": "shizuoka", "city_slug": "ito",
        "latitude": 34.9450, "longitude": 139.1250,
        "nearest_station": "JR伊東線 川奈駅（タクシー5分）", "station_walk_minutes": 20,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": True, "parking_count": 20,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["火葬場", "公営斎場", "伊東市民割引", "海を望む立地"],
        "operator_name": "伊東市", "rating_avg": 3.7, "review_count": 14,
    },
    {
        "name": "家族葬のタクセル 伊東",
        "slug": "takusel-ito",
        "venue_type": "private_hall",
        "description": "伊東市に位置する家族葬専用ホール。JR伊東駅から車で約5分のアクセスで、少人数の家族葬に特化。1日1組限定のプライベート空間で、伊豆の温泉リゾート地ならではの落ち着いた雰囲気の中で故人とのお別れの時間をお過ごしいただけます。",
        "address": "静岡県伊東市湯川3-5-10",
        "prefecture_slug": "shizuoka", "city_slug": "ito",
        "latitude": 34.9680, "longitude": 139.1000,
        "nearest_station": "JR伊東線 伊東駅", "station_walk_minutes": 10,
        "capacity_max": 25, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["家族葬専用", "1日1組限定", "駅近", "24時間対応"],
        "operator_name": "株式会社タクセル", "rating_avg": 4.2, "review_count": 11,
    },
    # === 島田市 3件 ===
    {
        "name": "島田市夢づくり会館",
        "slug": "shimada-yumezukuri-kaikan",
        "venue_type": "public_facility",
        "description": "島田市に位置する公共施設で、葬儀式場としても利用可能。島田市の市民サービスの一環として運営されており、リーズナブルな利用料金が特徴。火葬は近隣の志太広域聖苑を利用します。JR島田駅から車で約10分のアクセスです。",
        "address": "静岡県島田市島550-2",
        "prefecture_slug": "shizuoka", "city_slug": "shimada",
        "latitude": 34.8350, "longitude": 138.1750,
        "nearest_station": "JR東海道線 島田駅（車10分）", "station_walk_minutes": 25,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 30,
        "facilities": {"式場": True, "駐車場": True, "バリアフリー": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 258000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 458000}],
        "features": ["公共施設", "リーズナブル", "島田市運営", "駐車場完備"],
        "operator_name": "島田市", "rating_avg": 3.7, "review_count": 15,
    },
    {
        "name": "富士葬祭 島田",
        "slug": "fujisousai-shimada",
        "venue_type": "private_hall",
        "description": "島田市に位置する富士葬祭直営の葬儀会館。JR島田駅から車で約5分のアクセスで、島田市エリアの葬儀を数多く手がけています。家族葬から一般葬まで対応し、志太広域聖苑への送迎サービスも提供。地域に密着したきめ細かいサポートが特徴です。",
        "address": "静岡県島田市本通3-5-8",
        "prefecture_slug": "shizuoka", "city_slug": "shimada",
        "latitude": 34.8280, "longitude": 138.1800,
        "nearest_station": "JR東海道線 島田駅", "station_walk_minutes": 10,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True, "会食室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["駅近", "聖苑送迎対応", "地域密着", "会食室完備"],
        "operator_name": "富士葬祭", "rating_avg": 4.1, "review_count": 20,
    },
    {
        "name": "家族葬のラビュー 島田",
        "slug": "loveyou-shimada",
        "venue_type": "private_hall",
        "description": "島田市に位置する家族葬のラビュー直営ホール。木目を基調とした温かみのある内装が特徴で、1日1組限定の家族葬専用式場。家族葬が8.5万円からのリーズナブルな価格設定で、島田・榛原エリアの方々にご利用いただいています。",
        "address": "静岡県島田市旭1-3-15",
        "prefecture_slug": "shizuoka", "city_slug": "shimada",
        "latitude": 34.8300, "longitude": 138.1850,
        "nearest_station": "JR東海道線 島田駅", "station_walk_minutes": 12,
        "capacity_max": 35, "hall_count": 1, "has_crematorium": False, "parking_count": 15,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 275000}, {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}],
        "features": ["家族葬専用", "1日1組限定", "低価格", "木目調内装"],
        "operator_name": "家族葬のラビュー", "rating_avg": 4.3, "review_count": 13,
    },
    # === 袋井市 3件 ===
    {
        "name": "中遠聖苑",
        "slug": "chuen-seien",
        "venue_type": "public_crematorium",
        "description": "袋井市森町に位置する袋井市森町広域行政組合が運営する公営火葬場。袋井市と森町の住民が利用可能で、火葬炉3基を備えています。JR袋井駅からタクシーで約7分のアクセス。静かな環境の中で故人との最後のお別れが可能です。",
        "address": "静岡県袋井市森町飯田1488-1",
        "prefecture_slug": "shizuoka", "city_slug": "fukuroi",
        "latitude": 34.7580, "longitude": 137.9200,
        "nearest_station": "JR東海道線 袋井駅（タクシー7分）", "station_walk_minutes": 25,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 30,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["火葬場", "公営斎場", "袋井市・森町民対応"],
        "operator_name": "袋井市森町広域行政組合", "rating_avg": 3.7, "review_count": 16,
    },
    {
        "name": "富士葬祭 袋井",
        "slug": "fujisousai-fukuroi",
        "venue_type": "private_hall",
        "description": "袋井市に位置する富士葬祭直営の葬儀会館。JR袋井駅から車で約5分のアクセスで、袋井市・掛川市エリアの葬儀に対応。家族葬を中心に、充実した設備と経験豊富なスタッフが心のこもったサービスを提供いたします。",
        "address": "静岡県袋井市高尾町8-15",
        "prefecture_slug": "shizuoka", "city_slug": "fukuroi",
        "latitude": 34.7500, "longitude": 137.9250,
        "nearest_station": "JR東海道線 袋井駅", "station_walk_minutes": 12,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 18,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["駅近", "袋井・掛川対応", "24時間対応", "事前相談無料"],
        "operator_name": "富士葬祭", "rating_avg": 4.0, "review_count": 18,
    },
    {
        "name": "家族葬のタクセル 袋井",
        "slug": "takusel-fukuroi",
        "venue_type": "private_hall",
        "description": "袋井市に位置する家族葬のタクセル直営ホール。1日1組限定の家族葬専用式場で、少人数の温かいお別れに最適。リーズナブルな料金設定と24時間対応で、ご遺族の負担を軽減するサービスを提供しています。",
        "address": "静岡県袋井市浅名1028-3",
        "prefecture_slug": "shizuoka", "city_slug": "fukuroi",
        "latitude": 34.7450, "longitude": 137.9100,
        "nearest_station": "JR東海道線 袋井駅（車8分）", "station_walk_minutes": 20,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 12,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["家族葬専用", "1日1組限定", "低価格", "24時間対応"],
        "operator_name": "株式会社タクセル", "rating_avg": 4.4, "review_count": 12,
    },
    # === 御殿場市 3件 ===
    {
        "name": "玉穂斎場公苑",
        "slug": "tamaho-saijo-koen",
        "venue_type": "public_crematorium",
        "description": "御殿場市萩原に位置する御殿場市・小山町広域行政組合が運営する公営斎場。式場と火葬場が一体となった総合施設で、告別式から火葬まで同一敷地内で執り行えます。駐車場40台完備。JR御殿場駅から車で約10分のアクセスです。",
        "address": "静岡県御殿場市萩原992-98",
        "prefecture_slug": "shizuoka", "city_slug": "gotemba",
        "latitude": 35.2950, "longitude": 138.9250,
        "nearest_station": "JR御殿場線 御殿場駅（車10分）", "station_walk_minutes": 30,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": True, "parking_count": 40,
        "facilities": {"式場": True, "休憩室": True, "駐車場": True, "バリアフリー": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["火葬場併設", "公営斎場", "式場一体型", "御殿場市・小山町民対応"],
        "operator_name": "御殿場市小山町広域行政組合", "rating_avg": 3.8, "review_count": 20,
    },
    {
        "name": "やすらぎホール御殿場",
        "slug": "yasuragi-hall-gotemba",
        "venue_type": "private_hall",
        "description": "御殿場市に位置する民営葬儀会館。バリアフリー完全対応で、自家発電機を備え急な停電にも対応可能。駐車場400台の大規模施設で、社葬から家族葬まで幅広い規模の葬儀に対応。富士山を望む壮大な景観も特徴です。",
        "address": "静岡県御殿場市新橋2020-1",
        "prefecture_slug": "shizuoka", "city_slug": "gotemba",
        "latitude": 35.3050, "longitude": 138.9300,
        "nearest_station": "JR御殿場線 御殿場駅（車5分）", "station_walk_minutes": 18,
        "capacity_max": 200, "hall_count": 3, "has_crematorium": False, "parking_count": 400,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True, "会食室": True, "自家発電": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["大規模施設", "自家発電", "富士山望む", "社葬対応", "駐車場400台"],
        "operator_name": "やすらぎホール", "rating_avg": 4.1, "review_count": 25,
    },
    {
        "name": "家族葬のタクセル 御殿場",
        "slug": "takusel-gotemba",
        "venue_type": "private_hall",
        "description": "御殿場市に位置する家族葬専用ホール。JR御殿場駅から車で約8分のアクセスで、少人数の家族葬に特化した温かみのある空間。1日1組限定で、富士山の麓の静かな環境で故人とのお別れの時間をお過ごしいただけます。",
        "address": "静岡県御殿場市東田中1-8-5",
        "prefecture_slug": "shizuoka", "city_slug": "gotemba",
        "latitude": 35.3100, "longitude": 138.9350,
        "nearest_station": "JR御殿場線 御殿場駅", "station_walk_minutes": 15,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 12,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["家族葬専用", "1日1組限定", "富士山の麓", "24時間対応"],
        "operator_name": "株式会社タクセル", "rating_avg": 4.3, "review_count": 13,
    },
    # === 裾野市 2件 ===
    {
        "name": "裾野長泉斎苑 麗峰の丘",
        "slug": "susono-nagaizumi-saien",
        "venue_type": "public_crematorium",
        "description": "裾野市平松に位置する裾野市・長泉町が共同運営する公営火葬場。富士山を望む高台に立地し、自然豊かな環境の中で故人との最後のお別れが可能。2019年にリニューアルし、バリアフリー対応の新しい施設として生まれ変わりました。",
        "address": "静岡県裾野市平松580-1",
        "prefecture_slug": "shizuoka", "city_slug": "susono",
        "latitude": 35.1750, "longitude": 138.9050,
        "nearest_station": "JR御殿場線 裾野駅（車10分）", "station_walk_minutes": 30,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 30,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["火葬場", "公営斎場", "2019年リニューアル", "富士山望む"],
        "operator_name": "裾野市・長泉町", "rating_avg": 4.0, "review_count": 15,
    },
    {
        "name": "裾野市民葬祭あそか",
        "slug": "susono-shimin-sousai-asoka",
        "venue_type": "private_hall",
        "description": "裾野市に位置する地域密着型の葬儀会館。裾野市民の葬儀を長年手がけてきた実績のある施設で、家族葬から一般葬まで対応。地元の慣習やしきたりに精通したスタッフが、ご遺族に寄り添った心温まる葬儀をサポートいたします。",
        "address": "静岡県裾野市佐野1039-5",
        "prefecture_slug": "shizuoka", "city_slug": "susono",
        "latitude": 35.1700, "longitude": 138.9100,
        "nearest_station": "JR御殿場線 裾野駅", "station_walk_minutes": 12,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["地域密着", "実績豊富", "駅近", "事前相談無料"],
        "operator_name": "裾野市民葬祭", "rating_avg": 4.1, "review_count": 18,
    },
    # === 湖西市 2件 ===
    {
        "name": "新居斎場 やすらぎ苑",
        "slug": "arai-saijo-yasuragi",
        "venue_type": "public_crematorium",
        "description": "湖西市新居町に位置する公営火葬場。湖西市民の火葬を担う施設で、浜名湖に近い静かな環境に立地しています。火葬炉と待合室を備え、JR新居町駅からタクシーで約5分のアクセス。湖西市民は火葬料が割安で利用可能です。",
        "address": "静岡県湖西市新居町新居3380-8",
        "prefecture_slug": "shizuoka", "city_slug": "kosai",
        "latitude": 34.6950, "longitude": 137.5500,
        "nearest_station": "JR東海道線 新居町駅（タクシー5分）", "station_walk_minutes": 18,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": True, "parking_count": 20,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["火葬場", "公営斎場", "浜名湖近く", "湖西市民割引"],
        "operator_name": "湖西市", "rating_avg": 3.7, "review_count": 12,
    },
    {
        "name": "富士葬祭 湖西",
        "slug": "fujisousai-kosai",
        "venue_type": "private_hall",
        "description": "湖西市に位置する富士葬祭直営の葬儀会館。湖西・浜松西部エリアの葬儀に対応し、家族葬を中心としたサービスを提供。新居斎場への送迎にも対応し、ご遺族の負担を軽減する丁寧なサポートが特徴です。",
        "address": "静岡県湖西市鷲津1580-5",
        "prefecture_slug": "shizuoka", "city_slug": "kosai",
        "latitude": 34.7100, "longitude": 137.5300,
        "nearest_station": "JR東海道線 鷲津駅", "station_walk_minutes": 10,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 18,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["駅近", "斎場送迎対応", "湖西・浜松西部対応", "地域密着"],
        "operator_name": "富士葬祭", "rating_avg": 4.0, "review_count": 15,
    },
    # === 菊川市 2件 ===
    {
        "name": "東遠地区聖苑",
        "slug": "toen-chiku-seien",
        "venue_type": "public_crematorium",
        "description": "菊川市に位置する菊川市・掛川市が共同運営する公営火葬場。両市の住民が利用可能な広域施設で、火葬炉を備えた静かな環境の斎場です。JR菊川駅から車で約10分のアクセス。菊川市・掛川市民は火葬料が割安です。",
        "address": "静岡県菊川市赤土1055-1",
        "prefecture_slug": "shizuoka", "city_slug": "kikugawa",
        "latitude": 34.7450, "longitude": 138.0800,
        "nearest_station": "JR東海道線 菊川駅（車10分）", "station_walk_minutes": 30,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 30,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["火葬場", "公営斎場", "菊川市・掛川市民対応"],
        "operator_name": "菊川市・掛川市", "rating_avg": 3.7, "review_count": 14,
    },
    {
        "name": "富士葬祭 菊川",
        "slug": "fujisousai-kikugawa",
        "venue_type": "private_hall",
        "description": "菊川市に位置する富士葬祭直営の葬儀会館。JR菊川駅近くの好立地で、菊川市エリアの葬儀を手がけています。家族葬から一般葬まで対応し、東遠地区聖苑への送迎サービスも提供。お茶の里ならではの落ち着いた雰囲気の施設です。",
        "address": "静岡県菊川市堀之内580-3",
        "prefecture_slug": "shizuoka", "city_slug": "kikugawa",
        "latitude": 34.7500, "longitude": 138.0850,
        "nearest_station": "JR東海道線 菊川駅", "station_walk_minutes": 8,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 18,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["駅近", "聖苑送迎対応", "地域密着", "事前相談無料"],
        "operator_name": "富士葬祭", "rating_avg": 4.0, "review_count": 16,
    },
    # === 下田市 2件 ===
    {
        "name": "伊豆斎場",
        "slug": "izu-saijo-shimoda",
        "venue_type": "public_crematorium",
        "description": "下田市六丁目に位置する公営火葬場。下田市・南伊豆地域の方々の火葬を担う施設で、伊豆半島南端エリアの拠点斎場として機能しています。自然豊かな環境の中で故人との最後のお別れが可能。下田市民は火葬料が割安です。",
        "address": "静岡県下田市六丁目37-32",
        "prefecture_slug": "shizuoka", "city_slug": "shimoda",
        "latitude": 34.6800, "longitude": 138.9500,
        "nearest_station": "伊豆急行 伊豆急下田駅（車10分）", "station_walk_minutes": 30,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": True, "parking_count": 20,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["火葬場", "公営斎場", "南伊豆対応", "下田市民割引"],
        "operator_name": "下田市", "rating_avg": 3.6, "review_count": 10,
    },
    {
        "name": "下田セレモニーホール",
        "slug": "shimoda-ceremony-hall",
        "venue_type": "private_hall",
        "description": "下田市に位置する民営葬儀会館。南伊豆エリアで唯一の民営式場として、家族葬から一般葬まで対応。地域の慣習やしきたりに精通したスタッフが、伊豆半島南端の温かいコミュニティの中で心を込めた葬儀をサポートいたします。",
        "address": "静岡県下田市東本郷1-5-8",
        "prefecture_slug": "shizuoka", "city_slug": "shimoda",
        "latitude": 34.6750, "longitude": 138.9450,
        "nearest_station": "伊豆急行 伊豆急下田駅", "station_walk_minutes": 10,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 15,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 508000}],
        "features": ["南伊豆エリア", "駅近", "地域密着", "事前相談無料"],
        "operator_name": "下田セレモニー", "rating_avg": 4.0, "review_count": 12,
    },
    # === 伊豆の国市 2件 ===
    {
        "name": "伊豆の国市斎場 梛の杜",
        "slug": "izunokuni-saijo-naginomori",
        "venue_type": "public_crematorium",
        "description": "伊豆の国市長岡に位置する市営火葬場。伊豆の国市民の火葬を担う公営施設で、2019年に「梛の杜」としてリニューアルオープン。伊豆箱根鉄道伊豆長岡駅からタクシーで約10分。自然豊かな環境で、故人との最後のお別れの場を提供しています。",
        "address": "静岡県伊豆の国市長岡1407-4",
        "prefecture_slug": "shizuoka", "city_slug": "izunokuni",
        "latitude": 35.0300, "longitude": 138.9500,
        "nearest_station": "伊豆箱根鉄道 伊豆長岡駅（タクシー10分）", "station_walk_minutes": 30,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 25,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["火葬場", "公営斎場", "2019年リニューアル", "伊豆の国市民割引"],
        "operator_name": "伊豆の国市", "rating_avg": 3.9, "review_count": 14,
    },
    {
        "name": "JAメモリアルセンター伊豆",
        "slug": "ja-memorial-center-izu",
        "venue_type": "private_hall",
        "description": "伊豆の国市に位置するJAが運営する葬儀会館。伊豆の国市・伊豆市エリアの葬儀を手がけており、JA組合員以外の方もご利用可能。リーズナブルな料金設定と地域に根ざしたきめ細かいサービスで、ご遺族の負担を軽減いたします。",
        "address": "静岡県伊豆の国市古奈430-1",
        "prefecture_slug": "shizuoka", "city_slug": "izunokuni",
        "latitude": 35.0350, "longitude": 138.9550,
        "nearest_station": "伊豆箱根鉄道 伊豆長岡駅", "station_walk_minutes": 12,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 268000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 468000}],
        "features": ["JA運営", "組合員以外可", "リーズナブル", "伊豆エリア対応"],
        "operator_name": "JA伊豆の国", "rating_avg": 4.0, "review_count": 16,
    },
    # === 御前崎市 2件 ===
    {
        "name": "牧之原市御前崎市広域斎場",
        "slug": "makinohara-omaezaki-saijo",
        "venue_type": "public_crematorium",
        "description": "牧之原市菅ヶ谷に位置する牧之原市・御前崎市が共同運営する公営火葬場。両市の住民が利用可能な広域施設で、火葬炉を備えた静かな環境の斎場です。御前崎市からも車で約15分のアクセス。両市民は火葬料が割安で利用可能です。",
        "address": "静岡県牧之原市菅ヶ谷2560-1",
        "prefecture_slug": "shizuoka", "city_slug": "omaezaki",
        "latitude": 34.7350, "longitude": 138.2100,
        "nearest_station": "JR東海道線 菊川駅（車20分）", "station_walk_minutes": 60,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 30,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["火葬場", "公営斎場", "牧之原市・御前崎市民対応"],
        "operator_name": "牧之原市・御前崎市", "rating_avg": 3.7, "review_count": 12,
    },
    {
        "name": "富士葬祭 御前崎",
        "slug": "fujisousai-omaezaki",
        "venue_type": "private_hall",
        "description": "御前崎市に位置する富士葬祭直営の葬儀会館。御前崎・牧之原エリアの葬儀に対応し、家族葬を中心としたサービスを提供。広域斎場への送迎にも対応し、海沿いの穏やかな環境で心のこもった葬儀をサポートいたします。",
        "address": "静岡県御前崎市池新田3980-5",
        "prefecture_slug": "shizuoka", "city_slug": "omaezaki",
        "latitude": 34.6400, "longitude": 138.1300,
        "nearest_station": "JR東海道線 菊川駅（車25分）", "station_walk_minutes": 60,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 18,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["御前崎エリア", "斎場送迎対応", "地域密着", "24時間対応"],
        "operator_name": "富士葬祭", "rating_avg": 4.0, "review_count": 14,
    },
    # === 牧之原市 2件 ===
    {
        "name": "富士葬祭 牧之原",
        "slug": "fujisousai-makinohara",
        "venue_type": "private_hall",
        "description": "牧之原市に位置する富士葬祭直営の葬儀会館。牧之原・榛原エリアの葬儀に対応し、家族葬を中心としたサービスを提供。お茶の産地として知られる静かな田園風景の中で、故人との穏やかなお別れの時間をサポートいたします。",
        "address": "静岡県牧之原市静波2220-5",
        "prefecture_slug": "shizuoka", "city_slug": "makinohara",
        "latitude": 34.7200, "longitude": 138.2200,
        "nearest_station": "JR東海道線 島田駅（車20分）", "station_walk_minutes": 60,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 18,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["牧之原エリア", "地域密着", "24時間対応", "事前相談無料"],
        "operator_name": "富士葬祭", "rating_avg": 4.0, "review_count": 14,
    },
    {
        "name": "家族葬のタクセル 牧之原",
        "slug": "takusel-makinohara",
        "venue_type": "private_hall",
        "description": "牧之原市に位置する家族葬専用ホール。1日1組限定の家族葬に特化し、少人数の温かいお別れに最適。リーズナブルな料金設定で、ご遺族の経済的な負担も軽減。24時間対応で、お電話一本で搬送からサポートいたします。",
        "address": "静岡県牧之原市細江4580-3",
        "prefecture_slug": "shizuoka", "city_slug": "makinohara",
        "latitude": 34.7250, "longitude": 138.2300,
        "nearest_station": "JR東海道線 島田駅（車25分）", "station_walk_minutes": 60,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 12,
        "facilities": {"式場": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}],
        "features": ["家族葬専用", "1日1組限定", "低価格", "24時間対応"],
        "operator_name": "株式会社タクセル", "rating_avg": 4.3, "review_count": 10,
    },
]

def post(batch, n):
    data = json.dumps(batch, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(URL, data=data, headers=H, method="POST")
    try:
        with urllib.request.urlopen(req) as r:
            print(f"  バッチ{n}: {r.status} OK ({len(batch)}件)")
            return len(batch)
    except urllib.error.HTTPError as e:
        print(f"  バッチ{n}: エラー {e.code} - {e.read().decode()[:300]}")
        return 0

total = 0
for i in range(0, len(venues), 10):
    total += post(venues[i:i+10], i//10+1)
    time.sleep(1)
print(f"\n新規12市 投入完了: {total}/{len(venues)}件")
