#!/usr/bin/env python3
"""
兵庫県の斎場データ バッチ3: 姫路市18件 + 西宮市12件 = 30件
"""
import json
import subprocess
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

venues = [
    # =============================================
    # 姫路市 (18件)
    # =============================================
    {
        "name": "姫路市営斎場",
        "slug": "hyogo-himeji-shiritsu-saijo",
        "venue_type": "public_crematorium",
        "description": "姫路市が運営する公営火葬場。姫路市民は低料金で利用可能で、市内の葬儀で最も多く利用される火葬施設です。火葬炉を多数備え、年間を通じてスムーズな運営が行われています。広い敷地と駐車場を完備。",
        "address": "兵庫県姫路市名古山町14-1",
        "prefecture_slug": "hyogo",
        "city_slug": "himeji",
        "latitude": 34.8350,
        "longitude": 134.6710,
        "nearest_station": "JR姫路駅",
        "station_walk_minutes": 25,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 120,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True, "売店": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}],
        "features": ["火葬場", "公営斎場", "姫路市民割引", "大型駐車場"],
        "operator_name": "姫路市",
        "rating_avg": 3.7,
        "review_count": 98,
    },
    {
        "name": "ベルコシティホール姫路",
        "slug": "hyogo-bellco-himeji",
        "venue_type": "private_hall",
        "description": "JR姫路駅から徒歩10分のベルコ直営大型会館。姫路城下町エリアに位置し、大小4つの式場を完備。家族葬から社葬まで幅広い規模に対応できるフラッグシップ会館。充実した設備と経験豊富なスタッフが自慢です。",
        "address": "兵庫県姫路市南駅前町50",
        "prefecture_slug": "hyogo",
        "city_slug": "himeji",
        "latitude": 34.8230,
        "longitude": 134.6910,
        "nearest_station": "JR神戸線 姫路駅",
        "station_walk_minutes": 10,
        "capacity_max": 300,
        "hall_count": 4,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True, "宴会場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["大規模対応", "駅徒歩圏内", "社葬対応", "宿泊可能"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.3,
        "review_count": 105,
    },
    {
        "name": "公益社 姫路会館",
        "slug": "hyogo-koekisha-himeji",
        "venue_type": "private_hall",
        "description": "姫路市の中心部に位置する公益社直営の葬儀会館。山陽姫路駅から徒歩8分の好立地。丁寧な対応と明朗会計で、姫路エリアでの高い評価を受けています。1日1組貸切制でプライベートなお別れが可能です。",
        "address": "兵庫県姫路市東駅前町62",
        "prefecture_slug": "hyogo",
        "city_slug": "himeji",
        "latitude": 34.8260,
        "longitude": 134.6950,
        "nearest_station": "山陽電鉄 山陽姫路駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 370000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["1日1組貸切", "駅徒歩圏内", "宿泊可能", "明朗会計"],
        "operator_name": "株式会社公益社",
        "rating_avg": 4.4,
        "review_count": 88,
    },
    {
        "name": "家族葬のファミーユ 姫路北ホール",
        "slug": "hyogo-familiu-himeji-kita",
        "venue_type": "private_hall",
        "description": "姫路市北部エリアのファミーユ家族葬専用ホール。播但線野里駅から徒歩8分。少人数の家族葬に特化した設計で、温かみのある空間を提供。明確な料金プランで安心してご利用いただけます。",
        "address": "兵庫県姫路市増位本町1-5-8",
        "prefecture_slug": "hyogo",
        "city_slug": "himeji",
        "latitude": 34.8480,
        "longitude": 134.6920,
        "nearest_station": "JR播但線 野里駅",
        "station_walk_minutes": 8,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 120000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "明朗会計", "駅徒歩圏内"],
        "operator_name": "家族葬のファミーユ",
        "rating_avg": 4.2,
        "review_count": 48,
    },
    {
        "name": "家族葬のファミーユ 姫路南ホール",
        "slug": "hyogo-familiu-himeji-minami",
        "venue_type": "private_hall",
        "description": "姫路市南部の飾磨エリアに位置するファミーユのホール。山陽電鉄飾磨駅から徒歩6分。姫路南部エリアの家族葬ニーズに応える小規模専用ホールです。",
        "address": "兵庫県姫路市飾磨区英賀保駅前町30",
        "prefecture_slug": "hyogo",
        "city_slug": "himeji",
        "latitude": 34.7980,
        "longitude": 134.6580,
        "nearest_station": "山陽電鉄 飾磨駅",
        "station_walk_minutes": 6,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 120000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "駅近", "明朗会計"],
        "operator_name": "家族葬のファミーユ",
        "rating_avg": 4.1,
        "review_count": 35,
    },
    {
        "name": "小さなお葬式 姫路ホール",
        "slug": "hyogo-chiisana-himeji",
        "venue_type": "private_hall",
        "description": "姫路市内で小さなお葬式が提携する葬儀式場。業界最安水準の料金プランで、費用を抑えた葬儀を実現。火葬式から家族葬まで対応し、24時間年中無休で相談を受け付けています。",
        "address": "兵庫県姫路市西駅前町73-1",
        "prefecture_slug": "hyogo",
        "city_slug": "himeji",
        "latitude": 34.8240,
        "longitude": 134.6870,
        "nearest_station": "JR神戸線 姫路駅",
        "station_walk_minutes": 7,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["低価格", "明朗会計", "24時間対応", "駅徒歩圏内"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 4.0,
        "review_count": 42,
    },
    {
        "name": "セレモニーホール姫路中央",
        "slug": "hyogo-ceremony-himeji-chuo",
        "venue_type": "private_hall",
        "description": "姫路市の中心部に位置する互助会系の大型葬儀ホール。大小3つの式場を備え、少人数の家族葬から300名超の大規模葬まで対応可能。充実した設備とベテランスタッフの手厚いサポートが特徴です。",
        "address": "兵庫県姫路市本町68",
        "prefecture_slug": "hyogo",
        "city_slug": "himeji",
        "latitude": 34.8370,
        "longitude": 134.6900,
        "nearest_station": "JR神戸線 姫路駅",
        "station_walk_minutes": 15,
        "capacity_max": 300,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True, "宴会場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["大規模対応", "家族葬対応", "宿泊可能", "充実した設備"],
        "operator_name": "セレモニーホール互助会",
        "rating_avg": 4.2,
        "review_count": 75,
    },
    {
        "name": "姫路メモリアルホール白浜",
        "slug": "hyogo-himeji-memorial-shirahama",
        "venue_type": "private_hall",
        "description": "姫路市白浜エリアに位置する葬儀会館。山陽電鉄白浜の宮駅から徒歩5分の好立地。中規模の式場は家族葬から一般葬まで対応し、地元に密着した丁寧なサービスを提供しています。",
        "address": "兵庫県姫路市白浜町甲399-1",
        "prefecture_slug": "hyogo",
        "city_slug": "himeji",
        "latitude": 34.7940,
        "longitude": 134.7190,
        "nearest_station": "山陽電鉄 白浜の宮駅",
        "station_walk_minutes": 5,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 520000}],
        "features": ["駅近", "家族葬対応", "地域密着", "バリアフリー"],
        "operator_name": "姫路メモリアルホール",
        "rating_avg": 4.1,
        "review_count": 45,
    },
    {
        "name": "ベルコシティホール飾磨",
        "slug": "hyogo-bellco-shikama",
        "venue_type": "private_hall",
        "description": "姫路市飾磨区に位置するベルコの葬儀会館。山陽電鉄飾磨駅から徒歩10分。姫路南部エリアの葬儀需要に対応する中規模会館で、家族葬から一般葬まで丁寧に対応しています。",
        "address": "兵庫県姫路市飾磨区清水2-45",
        "prefecture_slug": "hyogo",
        "city_slug": "himeji",
        "latitude": 34.8010,
        "longitude": 134.6640,
        "nearest_station": "山陽電鉄 飾磨駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 540000}],
        "features": ["家族葬対応", "駅徒歩圏内", "バリアフリー", "姫路南部"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.1,
        "review_count": 52,
    },
    {
        "name": "ベルコシティホール広畑",
        "slug": "hyogo-bellco-hirohata",
        "venue_type": "private_hall",
        "description": "姫路市広畑区に位置するベルコの葬儀会館。山陽電鉄広畑駅から徒歩7分。広畑・大津エリアの葬儀需要に対応し、家族葬向けのコンパクトな式場を完備。地域の方々に親しまれている会館です。",
        "address": "兵庫県姫路市広畑区東新町1-20",
        "prefecture_slug": "hyogo",
        "city_slug": "himeji",
        "latitude": 34.7910,
        "longitude": 134.6380,
        "nearest_station": "山陽電鉄 広畑駅",
        "station_walk_minutes": 7,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 530000}],
        "features": ["家族葬対応", "駅徒歩圏内", "地域密着", "バリアフリー"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 40,
    },
    {
        "name": "姫路典礼会館",
        "slug": "hyogo-himeji-tenrei",
        "venue_type": "private_hall",
        "description": "姫路市の老舗葬儀社が運営する格式ある典礼会館。姫路城近くの歴史あるエリアに位置し、伝統と格式を重んじた葬儀を行えます。大小2つの式場で多様な規模の葬儀に対応。",
        "address": "兵庫県姫路市坊主町25",
        "prefecture_slug": "hyogo",
        "city_slug": "himeji",
        "latitude": 34.8400,
        "longitude": 134.6960,
        "nearest_station": "JR神戸線 姫路駅",
        "station_walk_minutes": 18,
        "capacity_max": 120,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 360000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["格式ある会館", "大規模対応", "宿泊可能", "駐車場完備"],
        "operator_name": "姫路典礼会館",
        "rating_avg": 4.2,
        "review_count": 62,
    },
    {
        "name": "書写メモリアルホール",
        "slug": "hyogo-shosha-memorial",
        "venue_type": "private_hall",
        "description": "書写山の麓に位置する落ち着いた雰囲気の葬儀会館。自然に囲まれた静かな環境で、心安らかにお別れの時間を過ごせます。大型駐車場を完備し、車でのアクセスに便利です。",
        "address": "兵庫県姫路市書写1050-1",
        "prefecture_slug": "hyogo",
        "city_slug": "himeji",
        "latitude": 34.8740,
        "longitude": 134.6500,
        "nearest_station": "JR姫新線 余部駅",
        "station_walk_minutes": 20,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 510000}],
        "features": ["自然豊かな環境", "大型駐車場", "宿泊可能", "家族葬対応"],
        "operator_name": "書写メモリアルホール",
        "rating_avg": 4.0,
        "review_count": 35,
    },
    {
        "name": "網干メモリアルホール",
        "slug": "hyogo-aboshi-memorial",
        "venue_type": "private_hall",
        "description": "姫路市網干区に位置する地域密着型の葬儀会館。山陽電鉄網干駅から徒歩8分。網干・揖保郡エリアの方々に親しまれている中規模会館です。家族葬から一般葬まで幅広く対応しています。",
        "address": "兵庫県姫路市網干区新在家259",
        "prefecture_slug": "hyogo",
        "city_slug": "himeji",
        "latitude": 34.7870,
        "longitude": 134.5920,
        "nearest_station": "山陽電鉄 山陽網干駅",
        "station_walk_minutes": 8,
        "capacity_max": 70,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 500000}],
        "features": ["地域密着", "家族葬対応", "駅徒歩圏内", "駐車場完備"],
        "operator_name": "網干メモリアルホール",
        "rating_avg": 4.0,
        "review_count": 30,
    },
    {
        "name": "圓教寺 会館",
        "slug": "hyogo-engyo-ji-kaikan",
        "venue_type": "temple_hall",
        "description": "書写山圓教寺の関連施設として運営される寺院式場。天台宗の名刹にふさわしい荘厳な雰囲気の中で仏式葬儀を執り行えます。歴史と伝統を重んじる方におすすめの格式ある会場です。",
        "address": "兵庫県姫路市書写2968",
        "prefecture_slug": "hyogo",
        "city_slug": "himeji",
        "latitude": 34.8820,
        "longitude": 134.6470,
        "nearest_station": "JR姫新線 余部駅",
        "station_walk_minutes": 30,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "控室": True, "駐車場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 380000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["寺院式場", "仏式葬儀", "歴史ある寺院", "格式ある会場"],
        "operator_name": "圓教寺",
        "rating_avg": 4.3,
        "review_count": 25,
    },
    {
        "name": "姫路花北メモリアルホール",
        "slug": "hyogo-himeji-hanakita-memorial",
        "venue_type": "private_hall",
        "description": "姫路市花北エリアの中規模葬儀会館。JR播但線京口駅から徒歩10分。花北地区の住宅街に位置し、落ち着いた環境でお別れの時間を過ごせます。家族葬に力を入れており、温かいサービスが好評です。",
        "address": "兵庫県姫路市花北本町2-1-10",
        "prefecture_slug": "hyogo",
        "city_slug": "himeji",
        "latitude": 34.8420,
        "longitude": 134.7050,
        "nearest_station": "JR播但線 京口駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 18,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 510000}],
        "features": ["家族葬対応", "駅徒歩圏内", "閑静な環境", "バリアフリー"],
        "operator_name": "姫路花北メモリアル",
        "rating_avg": 4.1,
        "review_count": 38,
    },
    {
        "name": "姫路御国野メモリアルホール",
        "slug": "hyogo-himeji-mikunino-memorial",
        "venue_type": "private_hall",
        "description": "姫路市東部の御国野エリアに位置する葬儀会館。国道2号線沿いの好アクセスな立地で、姫路東部から高砂方面の方にも便利。広い駐車場を完備しています。",
        "address": "兵庫県姫路市御国野町深志野580",
        "prefecture_slug": "hyogo",
        "city_slug": "himeji",
        "latitude": 34.8180,
        "longitude": 134.7370,
        "nearest_station": "JR神戸線 御着駅",
        "station_walk_minutes": 15,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 520000}],
        "features": ["国道沿い", "大型駐車場", "家族葬対応", "姫路東部"],
        "operator_name": "姫路メモリアルホール",
        "rating_avg": 4.0,
        "review_count": 32,
    },
    {
        "name": "姫路勝原セレモニーホール",
        "slug": "hyogo-himeji-katsuhara-ceremony",
        "venue_type": "private_hall",
        "description": "姫路市勝原区の閑静な住宅街に位置する葬儀ホール。JR英賀保駅から徒歩12分。コンパクトながら設備の整った会館で、リーズナブルな料金設定が魅力。地元の方々の家族葬を中心に対応しています。",
        "address": "兵庫県姫路市勝原区勝山町57",
        "prefecture_slug": "hyogo",
        "city_slug": "himeji",
        "latitude": 34.7980,
        "longitude": 134.6250,
        "nearest_station": "JR神戸線 英賀保駅",
        "station_walk_minutes": 12,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 290000}],
        "features": ["リーズナブル", "家族葬対応", "地域密着", "駐車場完備"],
        "operator_name": "姫路セレモニーホール",
        "rating_avg": 3.9,
        "review_count": 28,
    },
    {
        "name": "ベルコシティホール姫路北",
        "slug": "hyogo-bellco-himeji-kita",
        "venue_type": "private_hall",
        "description": "姫路市北部エリアをカバーするベルコの葬儀会館。姫路バイパス沿いの好アクセス立地で、駐車場も充実。中規模の式場で家族葬を中心に対応し、ベルコの安心のサポート体制を提供しています。",
        "address": "兵庫県姫路市西今宿3-2-1",
        "prefecture_slug": "hyogo",
        "city_slug": "himeji",
        "latitude": 34.8550,
        "longitude": 134.6700,
        "nearest_station": "JR姫新線 播磨高岡駅",
        "station_walk_minutes": 15,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 540000}],
        "features": ["大型駐車場", "家族葬対応", "バイパス沿い", "バリアフリー"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.1,
        "review_count": 48,
    },

    # =============================================
    # 西宮市 (12件)
    # =============================================
    {
        "name": "西宮市立満池谷斎場",
        "slug": "hyogo-nishinomiya-mitsuchidani",
        "venue_type": "public_crematorium",
        "description": "西宮市が運営する公営斎場。火葬場と式場を併設し、通夜から火葬まで同一敷地で行えます。西宮市民は低料金で利用可能。阪急夙川駅からバスで10分のアクセスです。",
        "address": "兵庫県西宮市奥畑5-122",
        "prefecture_slug": "hyogo",
        "city_slug": "nishinomiya",
        "latitude": 34.7530,
        "longitude": 135.3330,
        "nearest_station": "阪急神戸線 夙川駅",
        "station_walk_minutes": 20,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 80,
        "facilities": {"式場": True, "休憩室": True, "駐車場": True, "バリアフリー": True, "売店": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 250000}],
        "features": ["火葬場併設", "公営斎場", "西宮市民割引", "大型駐車場"],
        "operator_name": "西宮市",
        "rating_avg": 3.8,
        "review_count": 85,
    },
    {
        "name": "ベルコシティホール西宮",
        "slug": "hyogo-bellco-nishinomiya",
        "venue_type": "private_hall",
        "description": "阪急西宮北口駅から徒歩8分のベルコ直営葬儀会館。西宮市の中心部に位置し、大小3つの式場を備えた大型会館。家族葬から社葬まで幅広い規模に対応。文教地区にふさわしい落ち着いた佇まいです。",
        "address": "兵庫県西宮市北口町1-2-15",
        "prefecture_slug": "hyogo",
        "city_slug": "nishinomiya",
        "latitude": 34.7440,
        "longitude": 135.3600,
        "nearest_station": "阪急神戸線 西宮北口駅",
        "station_walk_minutes": 8,
        "capacity_max": 200,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True, "宴会場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["駅徒歩圏内", "大規模対応", "宿泊可能", "バリアフリー"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.3,
        "review_count": 92,
    },
    {
        "name": "公益社 西宮会館",
        "slug": "hyogo-koekisha-nishinomiya",
        "venue_type": "private_hall",
        "description": "西宮市で公益社が運営する葬儀会館。JR西宮駅から徒歩6分の好立地。1日1組貸切制でプライベートなお別れの場を提供。経験豊富なスタッフの丁寧な対応が高い評価を得ています。",
        "address": "兵庫県西宮市池田町5-10",
        "prefecture_slug": "hyogo",
        "city_slug": "nishinomiya",
        "latitude": 34.7370,
        "longitude": 135.3410,
        "nearest_station": "JR神戸線 西宮駅",
        "station_walk_minutes": 6,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 390000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 640000}],
        "features": ["1日1組貸切", "駅近", "宿泊可能", "家族葬対応"],
        "operator_name": "株式会社公益社",
        "rating_avg": 4.5,
        "review_count": 78,
    },
    {
        "name": "家族葬のファミーユ 西宮ホール",
        "slug": "hyogo-familiu-nishinomiya",
        "venue_type": "private_hall",
        "description": "西宮市内でファミーユが展開する家族葬専用ホール。阪神西宮駅から徒歩7分。少人数のお葬式に最適化された温かみのある空間で、明確な料金設定が安心です。",
        "address": "兵庫県西宮市戎町5-8",
        "prefecture_slug": "hyogo",
        "city_slug": "nishinomiya",
        "latitude": 34.7340,
        "longitude": 135.3380,
        "nearest_station": "阪神本線 西宮駅",
        "station_walk_minutes": 7,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 120000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "明朗会計", "駅徒歩圏内"],
        "operator_name": "家族葬のファミーユ",
        "rating_avg": 4.2,
        "review_count": 52,
    },
    {
        "name": "小さなお葬式 西宮ホール",
        "slug": "hyogo-chiisana-nishinomiya",
        "venue_type": "private_hall",
        "description": "西宮市で小さなお葬式が提携する葬儀式場。明瞭価格のセットプランで安心。火葬式から家族葬まで対応し、必要最低限のサービスをリーズナブルに提供しています。",
        "address": "兵庫県西宮市津門大塚町3-1",
        "prefecture_slug": "hyogo",
        "city_slug": "nishinomiya",
        "latitude": 34.7380,
        "longitude": 135.3520,
        "nearest_station": "阪急神戸線 今津駅",
        "station_walk_minutes": 8,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["低価格", "明朗会計", "24時間対応", "少人数対応"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 4.0,
        "review_count": 38,
    },
    {
        "name": "セレモニーホール甲子園",
        "slug": "hyogo-ceremony-koshien",
        "venue_type": "private_hall",
        "description": "甲子園球場近くに位置する葬儀ホール。阪神甲子園駅から徒歩10分。中規模の式場を備え、家族葬から一般葬まで対応。甲子園エリアの方々に長年信頼されている会館です。",
        "address": "兵庫県西宮市甲子園洲鳥町3-1",
        "prefecture_slug": "hyogo",
        "city_slug": "nishinomiya",
        "latitude": 34.7210,
        "longitude": 135.3630,
        "nearest_station": "阪神本線 甲子園駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 560000}],
        "features": ["家族葬対応", "駅徒歩圏内", "甲子園エリア", "バリアフリー"],
        "operator_name": "セレモニーホール互助会",
        "rating_avg": 4.1,
        "review_count": 50,
    },
    {
        "name": "夙川メモリアルホール",
        "slug": "hyogo-shukugawa-memorial",
        "venue_type": "private_hall",
        "description": "阪急夙川駅近くの閑静な住宅街に位置する上質な葬儀会館。桜並木で有名な夙川沿いの落ち着いた環境で、格式あるお別れの場を提供。西宮の高級住宅街にふさわしい洗練されたサービスが特徴です。",
        "address": "兵庫県西宮市相生町3-15",
        "prefecture_slug": "hyogo",
        "city_slug": "nishinomiya",
        "latitude": 34.7420,
        "longitude": 135.3290,
        "nearest_station": "阪急神戸線 夙川駅",
        "station_walk_minutes": 5,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 400000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["上質な空間", "駅近", "宿泊可能", "閑静な住宅街"],
        "operator_name": "夙川メモリアルホール",
        "rating_avg": 4.4,
        "review_count": 55,
    },
    {
        "name": "ベルコシティホール甲東園",
        "slug": "hyogo-bellco-kotoen",
        "venue_type": "private_hall",
        "description": "阪急甲東園駅から徒歩8分のベルコ直営会館。西宮市北部の閑静なエリアに位置し、家族葬向けのコンパクトな式場を完備。地域の方々のニーズに応える丁寧なサービスを提供しています。",
        "address": "兵庫県西宮市甲東園3-1-5",
        "prefecture_slug": "hyogo",
        "city_slug": "nishinomiya",
        "latitude": 34.7580,
        "longitude": 135.3580,
        "nearest_station": "阪急今津線 甲東園駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "駅徒歩圏内", "閑静なエリア", "バリアフリー"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.1,
        "review_count": 42,
    },
    {
        "name": "西宮浜メモリアルホール",
        "slug": "hyogo-nishinomiya-hama-memorial",
        "venue_type": "private_hall",
        "description": "西宮浜エリアに位置する海沿いの葬儀会館。阪神西宮駅からバスで10分。海を感じる開放的なロケーションで、穏やかなお別れの場を提供。大型駐車場完備で車でのアクセスに便利です。",
        "address": "兵庫県西宮市西宮浜3-1-5",
        "prefecture_slug": "hyogo",
        "city_slug": "nishinomiya",
        "latitude": 34.7170,
        "longitude": 135.3350,
        "nearest_station": "阪神本線 西宮駅",
        "station_walk_minutes": 25,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 530000}],
        "features": ["大型駐車場", "家族葬対応", "海沿い", "バリアフリー"],
        "operator_name": "西宮浜メモリアル",
        "rating_avg": 4.0,
        "review_count": 35,
    },
    {
        "name": "鳴尾メモリアルホール",
        "slug": "hyogo-naruo-memorial",
        "venue_type": "private_hall",
        "description": "西宮市鳴尾エリアの地域密着型葬儀会館。阪神鳴尾駅から徒歩8分。鳴尾・武庫川エリアの方々に親しまれている中規模会館で、家族葬を中心に温かいサービスを提供しています。",
        "address": "兵庫県西宮市鳴尾町3-5-20",
        "prefecture_slug": "hyogo",
        "city_slug": "nishinomiya",
        "latitude": 34.7240,
        "longitude": 135.3780,
        "nearest_station": "阪神本線 鳴尾駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 510000}],
        "features": ["地域密着", "家族葬対応", "駅徒歩圏内", "バリアフリー"],
        "operator_name": "鳴尾メモリアルホール",
        "rating_avg": 4.0,
        "review_count": 30,
    },
    {
        "name": "名塩やすらぎホール",
        "slug": "hyogo-najio-yasuragi",
        "venue_type": "private_hall",
        "description": "西宮市北部の名塩エリアに位置する葬儀ホール。JR西宮名塩駅から徒歩10分。山間部の自然豊かな環境で、静かにお別れの時間を過ごせます。北部エリアの方々の葬儀ニーズに応えています。",
        "address": "兵庫県西宮市名塩新町8-1",
        "prefecture_slug": "hyogo",
        "city_slug": "nishinomiya",
        "latitude": 34.8080,
        "longitude": 135.3130,
        "nearest_station": "JR福知山線 西宮名塩駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 115000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 290000}],
        "features": ["家族葬対応", "自然豊かな環境", "駅徒歩圏内", "駐車場完備"],
        "operator_name": "名塩やすらぎホール",
        "rating_avg": 4.0,
        "review_count": 25,
    },
]

# 10件ずつバッチ投入
total = len(venues)
print(f"兵庫県バッチ3: 姫路市+西宮市 {total}件を投入開始")
for i in range(0, total, 10):
    batch = venues[i:i+10]
    status = insert_batch(batch)
    print(f"  バッチ {i//10+1}: {len(batch)}件 → HTTP {status}")
    if status != "201":
        print(f"  エラー!")
        data_json = json.dumps(batch, ensure_ascii=False)
        result = subprocess.run([
            "curl", "-s",
            "-X", "POST", SUPABASE_URL,
            "-H", f"apikey: {API_KEY}",
            "-H", f"Authorization: Bearer {API_KEY}",
            "-H", "Content-Type: application/json",
            "-H", "Prefer: return=minimal",
            "-H", "User-Agent: Mozilla/5.0",
            "-d", data_json
        ], capture_output=True, text=True)
        print(f"  詳細: {result.stdout[:500]}")
    time.sleep(1)
print(f"バッチ3完了: {total}件")
