#!/usr/bin/env python3
"""
北海道・主要都市: 釧路市10件 + 帯広市10件 + 北見市8件 + 小樽市8件 = 36件
"""

import json
import urllib.request
import urllib.error
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

HEADERS = {
    "apikey": API_KEY,
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal",
}

venues = [
    # =============================================
    # 釧路市 — 10件
    # =============================================
    {"name": "釧路市斎場", "slug": "kushiro-shi-saijo", "venue_type": "public_crematorium", "description": "釧路市が運営する公営火葬場。釧路市民の火葬を担う中核施設で、火葬炉を複数備えています。待合室や通夜室も完備。釧路市民は市民料金で利用可能です。", "address": "北海道釧路市星が浦大通4丁目6-1", "prefecture_slug": "hokkaido", "city_slug": "kushiro", "latitude": 42.9450, "longitude": 144.3200, "nearest_station": "JR根室本線 新大楽毛駅", "station_walk_minutes": 15, "capacity_max": 40, "hall_count": 2, "has_crematorium": True, "parking_count": 80, "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "通夜室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 0}], "features": ["火葬場", "公営斎場", "駐車場完備", "市民料金あり"], "operator_name": "釧路市", "rating_avg": 3.7, "review_count": 15},
    {"name": "ウィズハウス 喜多町", "slug": "withhouse-kitamachi-kushiro", "venue_type": "private_hall", "description": "コープの家族葬ウィズハウスの釧路喜多町店。釧路市中心部に位置し、コープ会員割引あり。1日1組貸切の家族葬ホールで、温かみのある空間を提供します。", "address": "北海道釧路市喜多町7-14", "prefecture_slug": "hokkaido", "city_slug": "kushiro", "latitude": 42.9750, "longitude": 144.3800, "nearest_station": "JR根室本線 釧路駅", "station_walk_minutes": 10, "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}], "features": ["コープ会員割引", "1日1組貸切", "家族葬専用"], "operator_name": "めもるホールディングス", "rating_avg": 4.1, "review_count": 14},
    {"name": "ウィズハウス 釧路星が浦", "slug": "withhouse-hoshigaura-kushiro", "venue_type": "private_hall", "description": "コープの家族葬ウィズハウスの釧路星が浦店。釧路市西部エリアに位置し、広い駐車場を完備。コープ会員は特別料金で利用可能な家族葬専用ホールです。", "address": "北海道釧路市星が浦大通1丁目6-3", "prefecture_slug": "hokkaido", "city_slug": "kushiro", "latitude": 42.9500, "longitude": 144.3300, "nearest_station": "JR根室本線 新大楽毛駅", "station_walk_minutes": 12, "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}], "features": ["コープ会員割引", "駐車場完備", "家族葬専用"], "operator_name": "めもるホールディングス", "rating_avg": 4.0, "review_count": 12},
    {"name": "博善社 ホール新富士", "slug": "hakuzensha-shinfuji-kushiro", "venue_type": "private_hall", "description": "博善社が運営する釧路市新富士町の葬儀場。釧路地区で最大手の葬儀社で、通夜から告別式まで一貫したサービスを提供。広い式場と充実した設備が特徴です。", "address": "北海道釧路市新富士町3丁目3-1", "prefecture_slug": "hokkaido", "city_slug": "kushiro", "latitude": 42.9550, "longitude": 144.3500, "nearest_station": "JR根室本線 新富士駅", "station_walk_minutes": 8, "capacity_max": 60, "hall_count": 2, "has_crematorium": False, "parking_count": 30, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 500000}], "features": ["駅近", "一般葬対応", "駐車場完備", "地域最大手"], "operator_name": "博善社", "rating_avg": 4.0, "review_count": 20},
    {"name": "博善社 市民斎場", "slug": "hakuzensha-shimin-kushiro", "venue_type": "private_hall", "description": "博善社が運営する釧路市星が浦の市民斎場。地域の方に長年親しまれている葬儀場で、家族葬から一般葬まで幅広く対応。火葬場への送迎サービスもあります。", "address": "北海道釧路市星が浦南1丁目7-10", "prefecture_slug": "hokkaido", "city_slug": "kushiro", "latitude": 42.9480, "longitude": 144.3250, "nearest_station": "JR根室本線 新大楽毛駅", "station_walk_minutes": 10, "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 40, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True, "送迎バス": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 500000}], "features": ["送迎バスあり", "大型式場", "一般葬対応", "駐車場完備"], "operator_name": "博善社", "rating_avg": 4.0, "review_count": 22},
    {"name": "博善社 ホール東川", "slug": "hakuzensha-higashikawa-kushiro", "venue_type": "private_hall", "description": "博善社が運営する釧路市東川町の葬儀場。釧路市東部エリアに位置し、家族葬を中心にご利用いただけます。落ち着いた雰囲気と丁寧な対応が好評です。", "address": "北海道釧路市東川町19-14", "prefecture_slug": "hokkaido", "city_slug": "kushiro", "latitude": 42.9700, "longitude": 144.3900, "nearest_station": "JR根室本線 釧路駅", "station_walk_minutes": 12, "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 20, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}], "features": ["家族葬対応", "駐車場完備", "地域密着"], "operator_name": "博善社", "rating_avg": 3.9, "review_count": 12},
    {"name": "博善社 ホール益浦", "slug": "hakuzensha-masuura-kushiro", "venue_type": "private_hall", "description": "博善社が運営する釧路市益浦の葬儀場。釧路市南部エリアの住宅街に位置し、家族葬に最適なコンパクトな空間。地域に根差した温かみのあるサービスを提供しています。", "address": "北海道釧路市益浦1丁目19番10号", "prefecture_slug": "hokkaido", "city_slug": "kushiro", "latitude": 42.9600, "longitude": 144.3700, "nearest_station": "JR根室本線 釧路駅", "station_walk_minutes": 15, "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}], "features": ["家族葬対応", "地域密着", "駐車場完備"], "operator_name": "博善社", "rating_avg": 3.9, "review_count": 10},
    {"name": "メモリアルヴィレッジホール春採", "slug": "memorial-village-harutori", "venue_type": "private_hall", "description": "博善社が運営する釧路市春採の大型葬儀場。春採湖の近くに位置し、自然豊かな環境。複数の式場を備え、家族葬から大規模な一般葬・社葬まで対応可能です。", "address": "北海道釧路市春採7丁目1-39", "prefecture_slug": "hokkaido", "city_slug": "kushiro", "latitude": 42.9650, "longitude": 144.4000, "nearest_station": "JR根室本線 釧路駅", "station_walk_minutes": 20, "capacity_max": 100, "hall_count": 3, "has_crematorium": False, "parking_count": 50, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True, "ロビー": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 500000}], "features": ["大型施設", "社葬対応", "自然豊か", "駐車場完備"], "operator_name": "博善社", "rating_avg": 4.1, "review_count": 18},
    {"name": "ウィズハウス 釧路桂", "slug": "withhouse-kushiro-katsura", "venue_type": "private_hall", "description": "コープの家族葬ウィズハウスの釧路桂店。釧路町桂エリアに位置し、広い駐車場を完備。釧路市東部・釧路町のお客様に便利な立地で、コープ会員割引も利用可能です。", "address": "北海道釧路郡釧路町桂4丁目1-1", "prefecture_slug": "hokkaido", "city_slug": "kushiro", "latitude": 42.9850, "longitude": 144.4100, "nearest_station": "JR根室本線 釧路駅", "station_walk_minutes": 25, "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 20, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}], "features": ["コープ会員割引", "駐車場完備", "家族葬専用"], "operator_name": "めもるホールディングス", "rating_avg": 4.0, "review_count": 11},
    {"name": "小さなお葬式 釧路ホール", "slug": "chiisana-ososhiki-kushiro", "venue_type": "private_hall", "description": "小さなお葬式が提携する釧路の家族葬ホール。追加料金なしの明朗会計で、火葬式から家族葬まで低価格で対応。釧路市内で経済的な葬儀を希望する方に選ばれています。", "address": "北海道釧路市鳥取大通6丁目3-10", "prefecture_slug": "hokkaido", "city_slug": "kushiro", "latitude": 42.9580, "longitude": 144.3600, "nearest_station": "JR根室本線 釧路駅", "station_walk_minutes": 15, "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}], "features": ["低価格", "明朗会計", "24時間対応", "家族葬専用"], "operator_name": "株式会社ユニクエスト", "rating_avg": 3.8, "review_count": 9},
    # =============================================
    # 帯広市 — 10件
    # =============================================
    {"name": "帯広市斎場", "slug": "obihiro-shi-saijo", "venue_type": "public_crematorium", "description": "帯広市が運営する公営火葬場。十勝エリアの火葬を担う中核施設で、火葬炉を複数備えています。待合室も完備。帯広市民は市民料金で利用可能です。", "address": "北海道帯広市東6条南3丁目3-12", "prefecture_slug": "hokkaido", "city_slug": "obihiro", "latitude": 42.9200, "longitude": 143.2100, "nearest_station": "JR根室本線 帯広駅", "station_walk_minutes": 15, "capacity_max": 40, "hall_count": 2, "has_crematorium": True, "parking_count": 60, "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "通夜室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 0}], "features": ["火葬場", "公営斎場", "駐車場完備", "市民料金あり"], "operator_name": "帯広市", "rating_avg": 3.7, "review_count": 14},
    {"name": "ウィズハウス 帯広中央", "slug": "withhouse-obihiro-chuo", "venue_type": "private_hall", "description": "コープの家族葬ウィズハウスの帯広中央店。帯広市中心部に位置し、JR帯広駅からもアクセス可能。コープ会員割引あり。1日1組貸切の家族葬ホールです。", "address": "北海道帯広市西8条南11丁目5-1", "prefecture_slug": "hokkaido", "city_slug": "obihiro", "latitude": 42.9100, "longitude": 143.1900, "nearest_station": "JR根室本線 帯広駅", "station_walk_minutes": 10, "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}], "features": ["コープ会員割引", "1日1組貸切", "駅近", "家族葬専用"], "operator_name": "めもるホールディングス", "rating_avg": 4.2, "review_count": 16},
    {"name": "ウィズハウス 柏林台", "slug": "withhouse-hakurindai-obihiro", "venue_type": "private_hall", "description": "コープの家族葬ウィズハウスの帯広柏林台店。JR柏林台駅から近い好立地。帯広市西部エリアのお客様に便利で、コープ会員割引も利用可能な家族葬ホールです。", "address": "北海道帯広市西17条南1丁目25-1", "prefecture_slug": "hokkaido", "city_slug": "obihiro", "latitude": 42.9150, "longitude": 143.1700, "nearest_station": "JR根室本線 柏林台駅", "station_walk_minutes": 8, "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}], "features": ["コープ会員割引", "駅近", "家族葬専用"], "operator_name": "めもるホールディングス", "rating_avg": 4.1, "review_count": 14},
    {"name": "公益社 メモリアルホール札内", "slug": "koekisha-memorial-satsunai", "venue_type": "private_hall", "description": "公益社が運営する帯広近郊の大型葬儀場。幕別町札内に位置し、帯広市東部からもアクセス便利。広い式場と充実した設備で、家族葬から一般葬まで幅広く対応します。", "address": "北海道中川郡幕別町札内北栄町62", "prefecture_slug": "hokkaido", "city_slug": "obihiro", "latitude": 42.9300, "longitude": 143.2400, "nearest_station": "JR根室本線 札内駅", "station_walk_minutes": 10, "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 40, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 500000}], "features": ["大型式場", "一般葬対応", "駐車場完備", "駅近"], "operator_name": "公益社", "rating_avg": 4.0, "review_count": 18},
    {"name": "セレモニーホール帯広", "slug": "ceremony-hall-obihiro", "venue_type": "private_hall", "description": "帯広市中心部のセレモニーホール。JR帯広駅から近く、十勝エリアの方に広く利用されている葬儀場。家族葬から一般葬まで対応し、地域に根差した丁寧なサービスが特徴。", "address": "北海道帯広市西3条南10丁目20-1", "prefecture_slug": "hokkaido", "city_slug": "obihiro", "latitude": 42.9130, "longitude": 143.2000, "nearest_station": "JR根室本線 帯広駅", "station_walk_minutes": 5, "capacity_max": 60, "hall_count": 2, "has_crematorium": False, "parking_count": 20, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 500000}], "features": ["駅近", "一般葬対応", "地域密着"], "operator_name": "セレモニーホール帯広", "rating_avg": 4.0, "review_count": 15},
    {"name": "香華殿 帯広斎場", "slug": "kokaden-obihiro-saijo", "venue_type": "private_hall", "description": "香華殿グループが運営する帯広の葬儀場。格式ある落ち着いた式場で、家族葬から一般葬まで幅広く対応。十勝エリアで信頼されている葬儀場の一つです。", "address": "北海道帯広市東5条南12丁目1-5", "prefecture_slug": "hokkaido", "city_slug": "obihiro", "latitude": 42.9180, "longitude": 143.2150, "nearest_station": "JR根室本線 帯広駅", "station_walk_minutes": 12, "capacity_max": 60, "hall_count": 2, "has_crematorium": False, "parking_count": 20, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 520000}], "features": ["格式高い", "一般葬対応", "駐車場完備"], "operator_name": "香華殿", "rating_avg": 4.0, "review_count": 13},
    {"name": "小さなお葬式 帯広ホール", "slug": "chiisana-ososhiki-obihiro", "venue_type": "private_hall", "description": "小さなお葬式が提携する帯広の家族葬ホール。追加料金なしの明朗会計。火葬式から家族葬まで低価格で対応し、帯広市内で経済的な葬儀を希望する方に選ばれています。", "address": "北海道帯広市西12条南15丁目3-5", "prefecture_slug": "hokkaido", "city_slug": "obihiro", "latitude": 42.9050, "longitude": 143.1850, "nearest_station": "JR根室本線 帯広駅", "station_walk_minutes": 15, "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}], "features": ["低価格", "明朗会計", "24時間対応", "家族葬専用"], "operator_name": "株式会社ユニクエスト", "rating_avg": 3.8, "review_count": 10},
    {"name": "十勝葬祭 西帯広ホール", "slug": "tokachi-sosai-nishi-obihiro", "venue_type": "private_hall", "description": "十勝葬祭が運営する帯広市西部の葬儀場。十勝地域に密着した地元葬儀社で、きめ細かなサービスが特徴。家族葬から一般葬まで対応し、地域の方に信頼されています。", "address": "北海道帯広市西20条南3丁目36-1", "prefecture_slug": "hokkaido", "city_slug": "obihiro", "latitude": 42.9200, "longitude": 143.1600, "nearest_station": "JR根室本線 西帯広駅", "station_walk_minutes": 10, "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 20, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 295000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 480000}], "features": ["地域密着", "一般葬対応", "駅近"], "operator_name": "十勝葬祭", "rating_avg": 4.0, "review_count": 12},
    {"name": "よりそうお葬式 帯広ホール", "slug": "yorisou-obihiro", "venue_type": "private_hall", "description": "よりそうお葬式が提携する帯広の葬儀ホール。定額プランで追加費用の心配なし。帯広市で経済的な家族葬を希望する方に選ばれています。24時間電話相談可能。", "address": "北海道帯広市西6条南20丁目1-2", "prefecture_slug": "hokkaido", "city_slug": "obihiro", "latitude": 42.9020, "longitude": 143.1950, "nearest_station": "JR根室本線 帯広駅", "station_walk_minutes": 18, "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89100}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}], "features": ["定額プラン", "明朗会計", "24時間対応"], "operator_name": "株式会社よりそう", "rating_avg": 3.9, "review_count": 8},
    {"name": "十勝葬祭 帯広中央ホール", "slug": "tokachi-sosai-obihiro-chuo", "venue_type": "private_hall", "description": "十勝葬祭が運営する帯広市中央の葬儀場。JR帯広駅から近い好立地で、広い式場と充実した設備を備えた総合葬儀場。十勝地域で信頼されている老舗葬儀社です。", "address": "北海道帯広市東3条南8丁目2-1", "prefecture_slug": "hokkaido", "city_slug": "obihiro", "latitude": 42.9160, "longitude": 143.2050, "nearest_station": "JR根室本線 帯広駅", "station_walk_minutes": 8, "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 295000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 480000}], "features": ["駅近", "大型式場", "一般葬対応", "老舗"], "operator_name": "十勝葬祭", "rating_avg": 4.1, "review_count": 17},
    # =============================================
    # 北見市 — 8件
    # =============================================
    {"name": "いいだメモリアルホール", "slug": "iida-memorial-kitami", "venue_type": "private_hall", "description": "飯田葬儀社が運営する北見市常盤町の大型メモリアルホール。北見地区で最大手の葬儀社で、通夜から告別式まで一貫サービス。広い式場と充実した設備が特徴です。", "address": "北海道北見市常盤町1丁目2-9", "prefecture_slug": "hokkaido", "city_slug": "kitami", "latitude": 43.8100, "longitude": 143.8900, "nearest_station": "JR石北本線 北見駅", "station_walk_minutes": 8, "capacity_max": 80, "hall_count": 3, "has_crematorium": False, "parking_count": 40, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True, "ロビー": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 500000}], "features": ["大型式場", "駅近", "一般葬対応", "地域最大手"], "operator_name": "飯田葬儀社", "rating_avg": 4.1, "review_count": 20},
    {"name": "セレモニーホールいいだ市民斎場", "slug": "iida-shimin-kitami", "venue_type": "private_hall", "description": "飯田葬儀社が運営する北見市常盤町の市民斎場。地域の方に長年親しまれている葬儀場で、家族葬から一般葬まで幅広く対応。駅からも近く便利な立地です。", "address": "北海道北見市常盤町1丁目3-6", "prefecture_slug": "hokkaido", "city_slug": "kitami", "latitude": 43.8110, "longitude": 143.8910, "nearest_station": "JR石北本線 北見駅", "station_walk_minutes": 8, "capacity_max": 60, "hall_count": 2, "has_crematorium": False, "parking_count": 25, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 500000}], "features": ["駅近", "一般葬対応", "地域密着"], "operator_name": "飯田葬儀社", "rating_avg": 4.0, "review_count": 16},
    {"name": "セレモニーホールいいだ 三輪", "slug": "iida-miwa-kitami", "venue_type": "private_hall", "description": "飯田葬儀社が運営する北見市西三輪の葬儀場。北見市西部エリアに位置し、広い駐車場を完備。家族葬に適した落ち着いた空間で、地域の方に利用されています。", "address": "北海道北見市西三輪1丁目637-2", "prefecture_slug": "hokkaido", "city_slug": "kitami", "latitude": 43.8150, "longitude": 143.8700, "nearest_station": "JR石北本線 北見駅", "station_walk_minutes": 15, "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 20, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}], "features": ["駐車場完備", "家族葬対応", "地域密着"], "operator_name": "飯田葬儀社", "rating_avg": 3.9, "review_count": 12},
    {"name": "ウィズハウス 北見田端", "slug": "withhouse-kitami-tabata", "venue_type": "private_hall", "description": "コープの家族葬ウィズハウスの北見田端店。北見市田端町に位置し、コープ会員割引あり。1日1組貸切の家族葬ホールで、温かみのある空間を提供します。", "address": "北海道北見市田端町72-15", "prefecture_slug": "hokkaido", "city_slug": "kitami", "latitude": 43.8050, "longitude": 143.9000, "nearest_station": "JR石北本線 北見駅", "station_walk_minutes": 12, "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}], "features": ["コープ会員割引", "1日1組貸切", "家族葬専用"], "operator_name": "めもるホールディングス", "rating_avg": 4.1, "review_count": 13},
    {"name": "ウィズハウス 北見高栄", "slug": "withhouse-kitami-koei", "venue_type": "private_hall", "description": "コープの家族葬ウィズハウスの北見高栄店。高栄西町に位置し、住宅街の中にある落ち着いた家族葬ホール。コープ会員割引でお得に利用可能です。", "address": "北海道北見市高栄西町1丁目5-3", "prefecture_slug": "hokkaido", "city_slug": "kitami", "latitude": 43.8000, "longitude": 143.8800, "nearest_station": "JR石北本線 北見駅", "station_walk_minutes": 15, "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}], "features": ["コープ会員割引", "家族葬専用", "閑静な立地"], "operator_name": "めもるホールディングス", "rating_avg": 4.0, "review_count": 11},
    {"name": "北見市斎場", "slug": "kitami-shi-saijo", "venue_type": "public_crematorium", "description": "北見市が運営する公営火葬場。北見市民の火葬を担う施設で、待合室も完備。北見市民は市民料金で利用可能です。", "address": "北海道北見市美芳町2丁目1-1", "prefecture_slug": "hokkaido", "city_slug": "kitami", "latitude": 43.8200, "longitude": 143.9100, "nearest_station": "JR石北本線 北見駅", "station_walk_minutes": 20, "capacity_max": 30, "hall_count": 1, "has_crematorium": True, "parking_count": 50, "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 0}], "features": ["火葬場", "公営斎場", "市民料金あり"], "operator_name": "北見市", "rating_avg": 3.6, "review_count": 10},
    {"name": "小さなお葬式 北見ホール", "slug": "chiisana-ososhiki-kitami", "venue_type": "private_hall", "description": "小さなお葬式が提携する北見の家族葬ホール。明朗会計で追加料金なし。北見市内で経済的な家族葬を提供しています。", "address": "北海道北見市北進町3丁目1-10", "prefecture_slug": "hokkaido", "city_slug": "kitami", "latitude": 43.8080, "longitude": 143.8950, "nearest_station": "JR石北本線 北見駅", "station_walk_minutes": 10, "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}], "features": ["低価格", "明朗会計", "24時間対応"], "operator_name": "株式会社ユニクエスト", "rating_avg": 3.8, "review_count": 8},
    {"name": "セレモニーホール北見中央", "slug": "ceremony-kitami-chuo", "venue_type": "private_hall", "description": "北見市中央部のセレモニーホール。JR北見駅から近く、家族葬から一般葬まで対応。地域に根差した丁寧なサービスが特徴の葬儀場です。", "address": "北海道北見市大通西4丁目2-1", "prefecture_slug": "hokkaido", "city_slug": "kitami", "latitude": 43.8090, "longitude": 143.8870, "nearest_station": "JR石北本線 北見駅", "station_walk_minutes": 5, "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 490000}], "features": ["駅近", "一般葬対応", "地域密着"], "operator_name": "セレモニーホール北見", "rating_avg": 4.0, "review_count": 12},
    # =============================================
    # 小樽市 — 8件
    # =============================================
    {"name": "小樽市斎場", "slug": "otaru-shi-saijo", "venue_type": "public_crematorium", "description": "小樽市が運営する公営火葬場。小樽市民の火葬を担う施設で、緑に位置します。バス6台分と乗用車32台分の駐車場を完備。市民料金で利用可能です。", "address": "北海道小樽市緑5丁目2番1号", "prefecture_slug": "hokkaido", "city_slug": "otaru", "latitude": 43.1900, "longitude": 141.0100, "nearest_station": "JR函館本線 小樽駅", "station_walk_minutes": 15, "capacity_max": 40, "hall_count": 2, "has_crematorium": True, "parking_count": 38, "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "通夜室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 0}], "features": ["火葬場", "公営斎場", "駐車場完備", "市民料金あり"], "operator_name": "小樽市", "rating_avg": 3.7, "review_count": 12},
    {"name": "やわらぎ斎場 小樽", "slug": "yawaragi-otaru", "venue_type": "private_hall", "description": "やわらぎ斎場の小樽エリア拠点。小樽市中心部に位置し、JR小樽駅からもアクセス可能。家族葬から一般葬まで対応する小樽を代表する葬儀場です。", "address": "北海道小樽市稲穂4丁目10-1", "prefecture_slug": "hokkaido", "city_slug": "otaru", "latitude": 43.1950, "longitude": 140.9950, "nearest_station": "JR函館本線 小樽駅", "station_walk_minutes": 8, "capacity_max": 60, "hall_count": 2, "has_crematorium": False, "parking_count": 20, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}], "features": ["駅近", "一般葬対応", "家族葬対応"], "operator_name": "株式会社やわらぎ", "rating_avg": 4.0, "review_count": 16},
    {"name": "やわらぎ斎場 小樽花園", "slug": "yawaragi-otaru-hanazono", "venue_type": "private_hall", "description": "やわらぎ斎場の小樽花園エリア店。小樽の繁華街に近い便利な立地で、家族葬に適した落ち着いた空間。少人数でのお別れに最適です。", "address": "北海道小樽市花園3丁目5-10", "prefecture_slug": "hokkaido", "city_slug": "otaru", "latitude": 43.1920, "longitude": 140.9900, "nearest_station": "JR函館本線 小樽駅", "station_walk_minutes": 10, "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 12, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}], "features": ["駅近", "家族葬対応", "便利な立地"], "operator_name": "株式会社やわらぎ", "rating_avg": 4.0, "review_count": 10},
    {"name": "やわらぎファミリア 新光", "slug": "yawaragi-familia-shinko-otaru", "venue_type": "private_hall", "description": "やわらぎグループのファミリアブランド新光店。小樽市新光に位置し、少人数の家族葬に特化。温かみのある空間で故人とのお別れの時間を大切にしています。", "address": "北海道小樽市新光4丁目15-5", "prefecture_slug": "hokkaido", "city_slug": "otaru", "latitude": 43.1850, "longitude": 141.0050, "nearest_station": "JR函館本線 小樽築港駅", "station_walk_minutes": 12, "capacity_max": 25, "hall_count": 1, "has_crematorium": False, "parking_count": 10, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}], "features": ["家族葬専用", "少人数対応"], "operator_name": "株式会社やわらぎ", "rating_avg": 4.1, "review_count": 8},
    {"name": "小樽典礼斎場 本館", "slug": "otaru-tenrei-honkan", "venue_type": "private_hall", "description": "小樽典礼斎場の本館。小樽で老舗の葬儀場で、地域に根差した丁寧なサービスが特徴。通夜から告別式まで一貫して対応し、家族葬から一般葬まで幅広く対応します。", "address": "北海道小樽市長橋3丁目16-1", "prefecture_slug": "hokkaido", "city_slug": "otaru", "latitude": 43.2000, "longitude": 140.9800, "nearest_station": "JR函館本線 小樽駅", "station_walk_minutes": 12, "capacity_max": 60, "hall_count": 2, "has_crematorium": False, "parking_count": 20, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 480000}], "features": ["老舗", "一般葬対応", "地域密着"], "operator_name": "小樽典礼", "rating_avg": 4.0, "review_count": 15},
    {"name": "小樽典礼斎場 想苑", "slug": "otaru-tenrei-soen", "venue_type": "private_hall", "description": "小樽典礼の別館「想苑」。家族葬に特化した温かみのある空間。本館とは異なるアットホームな雰囲気で、少人数での心温まるお別れに最適です。", "address": "北海道小樽市長橋3丁目17-5", "prefecture_slug": "hokkaido", "city_slug": "otaru", "latitude": 43.2010, "longitude": 140.9810, "nearest_station": "JR函館本線 小樽駅", "station_walk_minutes": 12, "capacity_max": 25, "hall_count": 1, "has_crematorium": False, "parking_count": 10, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}], "features": ["家族葬専用", "少人数対応", "アットホーム"], "operator_name": "小樽典礼", "rating_avg": 4.1, "review_count": 9},
    {"name": "小さなお葬式 小樽ホール", "slug": "chiisana-ososhiki-otaru", "venue_type": "private_hall", "description": "小さなお葬式が提携する小樽の家族葬ホール。明朗会計で追加料金なし。小樽市内で経済的な家族葬を提供しています。", "address": "北海道小樽市色内2丁目15-8", "prefecture_slug": "hokkaido", "city_slug": "otaru", "latitude": 43.1960, "longitude": 140.9920, "nearest_station": "JR函館本線 小樽駅", "station_walk_minutes": 5, "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 8, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}], "features": ["低価格", "駅近", "明朗会計"], "operator_name": "株式会社ユニクエスト", "rating_avg": 3.8, "review_count": 8},
    {"name": "香華殿 小樽斎場", "slug": "kokaden-otaru-saijo", "venue_type": "private_hall", "description": "香華殿グループが運営する小樽の葬儀場。格式ある落ち着いた式場で、家族葬から一般葬まで対応。小樽エリアで信頼されている葬儀場です。", "address": "北海道小樽市築港10丁目20-3", "prefecture_slug": "hokkaido", "city_slug": "otaru", "latitude": 43.1870, "longitude": 141.0100, "nearest_station": "JR函館本線 小樽築港駅", "station_walk_minutes": 8, "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 520000}], "features": ["駅近", "格式高い", "一般葬対応"], "operator_name": "香華殿", "rating_avg": 4.0, "review_count": 11},
]

def insert_batch(batch):
    data_json = json.dumps(batch, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(SUPABASE_URL, data=data_json, headers=HEADERS, method="POST")
    try:
        with urllib.request.urlopen(req) as res:
            return res.status
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"  HTTPError {e.code}: {body[:300]}")
        return e.code

total = len(venues)
print(f"北海道・釧路+帯広+北見+小樽: {total}件を投入開始")

ok = 0
for i in range(0, total, 10):
    batch = venues[i:i+10]
    code = insert_batch(batch)
    print(f"  バッチ {i//10+1}: {code} ({len(batch)}件)")
    if code in (200, 201):
        ok += len(batch)
    time.sleep(0.5)

print(f"\n完了: {ok}/{total}件 投入成功")
