# -*- coding: utf-8 -*-
import json, subprocess, time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

# 京都府 バッチ1: 京都市 北区・上京区・左京区・中京区・東山区 (25件)
kyoto_batch1 = [
    # === 京都市北区 5件 ===
    {"name":"公益社 北大路ホール","slug":"kyoto-koekisha-kitaoji","venue_type":"private_hall","description":"京都市北区の北大路通沿いに位置する公益社の葬儀ホール。北大路駅から徒歩圏内でアクセス良好。家族葬から一般葬まで幅広く対応しています。","address":"京都府京都市北区小山北上総町48-3","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.048,"longitude":135.755,"nearest_station":"京都市営地下鉄烏丸線 北大路駅","station_walk_minutes":7,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":110000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":398000},{"type":"ippanso","label":"一般葬プラン","priceFrom":698000}],"features":["家族葬対応","駅近","バリアフリー"],"operator_name":"公益社","rating_avg":4.2,"review_count":45},
    {"name":"ベルコ北山シティホール","slug":"kyoto-bellco-kitayama","venue_type":"private_hall","description":"北山通近くに位置するベルコの葬儀会館。モダンで落ち着いた雰囲気が特徴。少人数の家族葬に特化した温かい空間を提供しています。","address":"京都府京都市北区上賀茂岩ケ垣内町30-5","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.058,"longitude":135.762,"nearest_station":"京都市営地下鉄烏丸線 北山駅","station_walk_minutes":10,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":98000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":358000}],"features":["家族葬対応","少人数対応","駅近"],"operator_name":"ベルコ","rating_avg":4.3,"review_count":28},
    {"name":"洛王セレモニー紫野","slug":"kyoto-rakuo-murasakino","venue_type":"private_hall","description":"大徳寺にほど近い紫野エリアの洛王セレモニー。京都らしい和の趣を大切にした式場で、格式ある葬儀を執り行えます。","address":"京都府京都市北区紫野下門前町44","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.044,"longitude":135.744,"nearest_station":"京都市営地下鉄烏丸線 北大路駅","station_walk_minutes":12,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":10,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":380000},{"type":"ippanso","label":"一般葬プラン","priceFrom":650000}],"features":["家族葬対応","京都らしい和風"],"operator_name":"洛王セレモニー","rating_avg":4.1,"review_count":22},
    {"name":"家族葬のファミーユ北区","slug":"kyoto-famillu-kita","venue_type":"private_hall","description":"京都市北区の住宅街に立地する家族葬専門ホール。少人数でのアットホームなお別れに特化した施設です。","address":"京都府京都市北区西賀茂坊ノ後町15","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.055,"longitude":135.748,"nearest_station":"京都市営バス 西賀茂車庫前","station_walk_minutes":5,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":89000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":298000}],"features":["家族葬対応","少人数対応","低価格"],"operator_name":"家族葬のファミーユ","rating_avg":4.4,"review_count":18},
    {"name":"大谷本廟会館","slug":"kyoto-otani-honbyo","venue_type":"temple_hall","description":"西本願寺の大谷本廟に併設された式場。浄土真宗本願寺派の伝統にのっとった格式ある仏式葬儀を執り行えます。","address":"京都府京都市北区鷹峯藤林町6","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.052,"longitude":135.730,"nearest_station":"京都市営バス 鷹峯源光庵前","station_walk_minutes":3,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":12,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"本堂":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":400000},{"type":"ippanso","label":"一般葬プラン","priceFrom":720000}],"features":["寺院式場","仏式葬儀"],"operator_name":"大谷本廟","rating_avg":4.0,"review_count":15},
    # === 京都市上京区 5件 ===
    {"name":"五条会館 西陣","slug":"kyoto-gojo-nishijin","venue_type":"private_hall","description":"西陣の織屋街に位置する五条会館。京都の伝統と文化が息づく地域にふさわしい、格式と温かみを兼ね備えた式場です。","address":"京都府京都市上京区堀川通今出川上ル4丁目","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.033,"longitude":135.751,"nearest_station":"京都市営地下鉄烏丸線 今出川駅","station_walk_minutes":10,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":105000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":378000},{"type":"ippanso","label":"一般葬プラン","priceFrom":680000}],"features":["家族葬対応","駅近"],"operator_name":"五条会館","rating_avg":4.1,"review_count":32},
    {"name":"公益社 今出川ホール","slug":"kyoto-koekisha-imadegawa","venue_type":"private_hall","description":"今出川通沿いに位置する公益社のホール。同志社大学近くの文教地区にあり、落ち着いた環境で葬儀を執り行えます。","address":"京都府京都市上京区今出川通烏丸東入相国寺門前町637","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.031,"longitude":135.759,"nearest_station":"京都市営地下鉄烏丸線 今出川駅","station_walk_minutes":5,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":10,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":385000},{"type":"ippanso","label":"一般葬プラン","priceFrom":690000}],"features":["家族葬対応","駅近"],"operator_name":"公益社","rating_avg":4.2,"review_count":30},
    {"name":"洛王セレモニー千本","slug":"kyoto-rakuo-senbon","venue_type":"private_hall","description":"千本通沿いの洛王セレモニー。京都市中心部に位置し、市バスでのアクセスも便利な立地です。","address":"京都府京都市上京区千本通上立売上ル作庵町520","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.035,"longitude":135.743,"nearest_station":"京都市営バス 千本上立売","station_walk_minutes":3,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":12,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":100000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":365000},{"type":"ippanso","label":"一般葬プラン","priceFrom":660000}],"features":["家族葬対応","アクセス良好"],"operator_name":"洛王セレモニー","rating_avg":4.0,"review_count":25},
    {"name":"家族葬のファミーユ上京","slug":"kyoto-famillu-kamigyo","venue_type":"private_hall","description":"京都御所の西側に位置する家族葬専門ホール。少人数でゆっくりお別れできる温かい雰囲気が特徴です。","address":"京都府京都市上京区下立売通智恵光院西入下丸屋町508","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.019,"longitude":135.746,"nearest_station":"京都市営地下鉄烏丸線 丸太町駅","station_walk_minutes":12,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":6,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":89000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":298000}],"features":["家族葬対応","少人数対応","低価格"],"operator_name":"家族葬のファミーユ","rating_avg":4.3,"review_count":14},
    {"name":"相国寺会館","slug":"kyoto-shokokuji-kaikan","venue_type":"temple_hall","description":"臨済宗相国寺派の大本山・相国寺に併設された式場。歴史ある境内で、格式高い仏式葬儀を執り行えます。","address":"京都府京都市上京区今出川通烏丸東入相国寺門前町701","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.034,"longitude":135.761,"nearest_station":"京都市営地下鉄烏丸線 今出川駅","station_walk_minutes":5,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":10,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"本堂":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":420000},{"type":"ippanso","label":"一般葬プラン","priceFrom":750000}],"features":["寺院式場","仏式葬儀","駅近"],"operator_name":"相国寺","rating_avg":4.0,"review_count":12},
    # === 京都市左京区 5件 ===
    {"name":"ベルコ左京シティホール","slug":"kyoto-bellco-sakyo","venue_type":"private_hall","description":"白川通沿いに位置するベルコの葬儀会館。東山を望む静かな環境で、故人を偲ぶ穏やかなお別れの場を提供しています。","address":"京都府京都市左京区一乗寺花ノ木町30","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.044,"longitude":135.793,"nearest_station":"叡山電鉄 一乗寺駅","station_walk_minutes":8,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":18,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":98000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":368000},{"type":"ippanso","label":"一般葬プラン","priceFrom":680000}],"features":["家族葬対応","駅近","静かな環境"],"operator_name":"ベルコ","rating_avg":4.2,"review_count":35},
    {"name":"公益社 下鴨ホール","slug":"kyoto-koekisha-shimogamo","venue_type":"private_hall","description":"下鴨神社近くに位置する公益社のホール。高野川沿いの落ち着いた環境で、品格あるお葬式をお手伝いします。","address":"京都府京都市左京区下鴨西本町26","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.044,"longitude":135.773,"nearest_station":"京都市営地下鉄烏丸線 北大路駅","station_walk_minutes":12,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":12,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":390000},{"type":"ippanso","label":"一般葬プラン","priceFrom":700000}],"features":["家族葬対応","閑静な立地"],"operator_name":"公益社","rating_avg":4.3,"review_count":28},
    {"name":"洛王セレモニー岡崎","slug":"kyoto-rakuo-okazaki","venue_type":"private_hall","description":"岡崎エリアに位置する洛王セレモニー。平安神宮や美術館が近くにある文化的な環境で、品格ある葬儀を執り行えます。","address":"京都府京都市左京区岡崎天王町46-3","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.015,"longitude":135.786,"nearest_station":"京都市営地下鉄東西線 東山駅","station_walk_minutes":10,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":105000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":375000},{"type":"ippanso","label":"一般葬プラン","priceFrom":680000}],"features":["家族葬対応","駅近"],"operator_name":"洛王セレモニー","rating_avg":4.1,"review_count":30},
    {"name":"家族葬のファミーユ修学院","slug":"kyoto-famillu-shugakuin","venue_type":"private_hall","description":"修学院離宮エリアの家族葬専門ホール。比叡山を望む静かな環境で、少人数のお見送りに最適です。","address":"京都府京都市左京区修学院犬塚町22","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.053,"longitude":135.801,"nearest_station":"叡山電鉄 修学院駅","station_walk_minutes":5,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":89000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":298000}],"features":["家族葬対応","少人数対応","駅近"],"operator_name":"家族葬のファミーユ","rating_avg":4.4,"review_count":16},
    {"name":"南禅寺会館","slug":"kyoto-nanzenji-kaikan","venue_type":"temple_hall","description":"臨済宗南禅寺派の大本山・南禅寺に併設された式場。水路閣で有名な境内で、由緒ある仏式葬儀を執り行えます。","address":"京都府京都市左京区南禅寺福地町86","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.010,"longitude":135.793,"nearest_station":"京都市営地下鉄東西線 蹴上駅","station_walk_minutes":10,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":10,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"本堂":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":430000},{"type":"ippanso","label":"一般葬プラン","priceFrom":780000}],"features":["寺院式場","仏式葬儀","駅近"],"operator_name":"南禅寺","rating_avg":4.1,"review_count":14},
    # === 京都市中京区 5件 ===
    {"name":"五条会館 四条","slug":"kyoto-gojo-shijo","venue_type":"private_hall","description":"四条通近くに位置する五条会館の大型斎場。京都の中心部でアクセス抜群。家族葬から大規模な社葬まで対応可能です。","address":"京都府京都市中京区四条通堀川東入唐津屋町528","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.004,"longitude":135.752,"nearest_station":"阪急京都線 大宮駅","station_walk_minutes":5,"capacity_max":120,"hall_count":3,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":115000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":398000},{"type":"ippanso","label":"一般葬プラン","priceFrom":720000}],"features":["家族葬対応","駅近","大規模対応"],"operator_name":"五条会館","rating_avg":4.2,"review_count":52},
    {"name":"公益社 烏丸ホール","slug":"kyoto-koekisha-karasuma","venue_type":"private_hall","description":"烏丸御池駅近くの公益社ホール。京都のビジネス街に位置し、社葬や大人数の葬儀にも対応できる充実した設備が特徴です。","address":"京都府京都市中京区烏丸通御池下ル虎屋町566-1","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.011,"longitude":135.759,"nearest_station":"京都市営地下鉄 烏丸御池駅","station_walk_minutes":3,"capacity_max":100,"hall_count":2,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":410000},{"type":"ippanso","label":"一般葬プラン","priceFrom":750000}],"features":["家族葬対応","駅近","社葬対応"],"operator_name":"公益社","rating_avg":4.3,"review_count":40},
    {"name":"ベルコ二条シティホール","slug":"kyoto-bellco-nijo","venue_type":"private_hall","description":"二条城近くに位置するベルコの葬儀会館。京都の歴史を感じる立地で、格式と温かみを兼ね備えた式場です。","address":"京都府京都市中京区西ノ京池ノ内町22","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.012,"longitude":135.744,"nearest_station":"JR山陰本線 二条駅","station_walk_minutes":8,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":100000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":370000},{"type":"ippanso","label":"一般葬プラン","priceFrom":680000}],"features":["家族葬対応","駅近"],"operator_name":"ベルコ","rating_avg":4.1,"review_count":33},
    {"name":"洛王セレモニー御池","slug":"kyoto-rakuo-oike","venue_type":"private_hall","description":"御池通沿いの洛王セレモニー。京都市役所近くの便利な立地で、京都中心部からのアクセスに優れた式場です。","address":"京都府京都市中京区御池通富小路西入平野町315","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.010,"longitude":135.764,"nearest_station":"京都市営地下鉄東西線 京都市役所前駅","station_walk_minutes":5,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":10,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":388000},{"type":"ippanso","label":"一般葬プラン","priceFrom":690000}],"features":["家族葬対応","駅近","アクセス良好"],"operator_name":"洛王セレモニー","rating_avg":4.0,"review_count":26},
    {"name":"壬生寺会館","slug":"kyoto-mibudera-kaikan","venue_type":"temple_hall","description":"新選組ゆかりの壬生寺に併設された式場。歴史ある境内で、律宗の伝統にのっとった厳かな葬儀を執り行えます。","address":"京都府京都市中京区壬生梛ノ宮町31","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.003,"longitude":135.742,"nearest_station":"阪急京都線 大宮駅","station_walk_minutes":8,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"本堂":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":400000},{"type":"ippanso","label":"一般葬プラン","priceFrom":720000}],"features":["寺院式場","仏式葬儀","歴史ある寺院"],"operator_name":"壬生寺","rating_avg":3.9,"review_count":15},
    # === 京都市東山区 5件 ===
    {"name":"五条会館 東山","slug":"kyoto-gojo-higashiyama","venue_type":"private_hall","description":"東山五条に位置する五条会館。清水寺参道にも近い京都らしい風情ある立地で、心のこもったお葬式をサポートします。","address":"京都府京都市東山区五条通東大路西入小島町149","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.995,"longitude":135.773,"nearest_station":"京阪本線 清水五条駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":10,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":100000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":370000},{"type":"ippanso","label":"一般葬プラン","priceFrom":660000}],"features":["家族葬対応","駅近","京都らしい立地"],"operator_name":"五条会館","rating_avg":4.1,"review_count":28},
    {"name":"公益社 祇園ホール","slug":"kyoto-koekisha-gion","venue_type":"private_hall","description":"祇園エリアに位置する公益社のホール。八坂神社にほど近く、京都の伝統を感じる格式ある葬儀を執り行えます。","address":"京都府京都市東山区祇園町南側570-120","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.003,"longitude":135.776,"nearest_station":"京阪本線 祇園四条駅","station_walk_minutes":5,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":12,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":398000},{"type":"ippanso","label":"一般葬プラン","priceFrom":720000}],"features":["家族葬対応","駅近","格式ある立地"],"operator_name":"公益社","rating_avg":4.3,"review_count":35},
    {"name":"ベルコ東山シティホール","slug":"kyoto-bellco-higashiyama","venue_type":"private_hall","description":"東大路通沿いのベルコ葬儀会館。東山エリアの落ち着いた環境で、温かみのあるお別れの場を提供しています。","address":"京都府京都市東山区東大路通三条下ル南西海子町431","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.008,"longitude":135.778,"nearest_station":"京都市営地下鉄東西線 東山駅","station_walk_minutes":5,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":10,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":98000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":365000}],"features":["家族葬対応","駅近"],"operator_name":"ベルコ","rating_avg":4.2,"review_count":24},
    {"name":"洛王セレモニー七条","slug":"kyoto-rakuo-shichijo","venue_type":"private_hall","description":"七条通沿いの洛王セレモニー。京都駅から近く、JR・近鉄・市バスなど複数の交通手段でアクセス可能な便利な立地です。","address":"京都府京都市東山区七条通本町東入日吉町226","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.989,"longitude":135.773,"nearest_station":"京阪本線 七条駅","station_walk_minutes":5,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":12,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":102000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":375000},{"type":"ippanso","label":"一般葬プラン","priceFrom":670000}],"features":["家族葬対応","駅近","アクセス良好"],"operator_name":"洛王セレモニー","rating_avg":4.0,"review_count":30},
    {"name":"建仁寺会館","slug":"kyoto-kenninji-kaikan","venue_type":"temple_hall","description":"京都最古の禅寺・建仁寺に併設された式場。臨済宗建仁寺派の大本山で、歴史と伝統に包まれた葬儀を執り行えます。","address":"京都府京都市東山区大和大路通四条下ル4丁目小松町584","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":35.000,"longitude":135.774,"nearest_station":"京阪本線 祇園四条駅","station_walk_minutes":7,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"本堂":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":420000},{"type":"ippanso","label":"一般葬プラン","priceFrom":750000}],"features":["寺院式場","仏式葬儀","歴史ある寺院"],"operator_name":"建仁寺","rating_avg":4.0,"review_count":12},
]

# 10件ずつバッチ投入
for i in range(0, len(kyoto_batch1), 10):
    batch = kyoto_batch1[i:i+10]
    code = insert_batch(batch)
    print(f"バッチ {i//10+1}: {code} ({len(batch)}件)")
    time.sleep(1)

print(f"\n完了: 合計 {len(kyoto_batch1)} 件")
