#!/usr/bin/env python3
"""
中部7県（愛知・静岡を除く）の斎場データをSupabase REST APIに投入するスクリプト
新潟県・長野県・岐阜県・富山県・石川県・福井県・山梨県
10件ずつバッチでPOSTする
"""

import json
import urllib.request
import urllib.error
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

HEADERS = {
    "apikey": API_KEY,
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal",
}

# 中部7県の全斎場データ（約50件）
venues = [
    # =============================================
    # 1. 新潟県 (niigata) — 10件
    # =============================================

    # --- 新潟市 (niigata-city) 5件 ---
    {
        "name": "新潟市青山斎場",
        "slug": "niigata-aoyama-saijo",
        "venue_type": "public_crematorium",
        "description": "新潟市が運営する公営斎場で、西区青山に位置します。火葬棟と式場を同一敷地内に備え、通夜から火葬まで一貫して執り行えます。JR越後線「青山駅」から徒歩16分。新潟市民は火葬料無料で利用でき、駐車場36台完備。日本海を望む静かな環境です。",
        "address": "新潟県新潟市西区青山1436-1209",
        "prefecture_slug": "niigata",
        "city_slug": "niigata-city",
        "latitude": 37.8870,
        "longitude": 138.9960,
        "nearest_station": "JR越後線 青山駅",
        "station_walk_minutes": 16,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 36,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応", "バリアフリー"],
        "operator_name": "新潟市",
        "rating_avg": 4.0,
        "review_count": 62,
    },
    {
        "name": "新潟市亀田斎場",
        "slug": "niigata-kameda-saijo",
        "venue_type": "public_crematorium",
        "description": "新潟市江南区にある公営火葬場。火葬炉3基を備え、新潟市民は火葬料無料で利用可能です。JR信越本線「亀田駅」からタクシー約10分。落ち着いた住宅街の中に位置し、静かな環境で故人を見送れます。待合室も完備しています。",
        "address": "新潟県新潟市江南区亀田中島2-6-1",
        "prefecture_slug": "niigata",
        "city_slug": "niigata-city",
        "latitude": 37.8810,
        "longitude": 139.1030,
        "nearest_station": "JR信越本線 亀田駅",
        "station_walk_minutes": 20,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["火葬場併設", "公営斎場", "家族葬対応", "バリアフリー"],
        "operator_name": "新潟市",
        "rating_avg": 3.8,
        "review_count": 28,
    },
    {
        "name": "セレモニーホール新潟",
        "slug": "ceremony-hall-niigata",
        "venue_type": "private_hall",
        "description": "アークベルが運営する新潟市中央区の大型葬儀会館。JR新潟駅南口から徒歩8分と抜群のアクセス。大規模な一般葬から少人数の家族葬まで幅広く対応。ホール内に調理場を備え、温かい料理を提供できるのが特長です。",
        "address": "新潟県新潟市中央区南笹口1-1-38",
        "prefecture_slug": "niigata",
        "city_slug": "niigata-city",
        "latitude": 37.9090,
        "longitude": 139.0570,
        "nearest_station": "JR上越新幹線 新潟駅",
        "station_walk_minutes": 8,
        "capacity_max": 150,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 80,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 278000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["駅近", "大規模葬対応", "家族葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "株式会社アークベル",
        "rating_avg": 4.3,
        "review_count": 45,
    },
    {
        "name": "家族葬のダビアス新潟中央",
        "slug": "davius-niigata-chuo",
        "venue_type": "private_hall",
        "description": "家族葬専用の温かみのあるホール。新潟市中央区に位置し、少人数でゆっくりとお別れできる空間を提供。リビングルームのような落ち着いた内装で、1日1組完全貸切対応。24時間365日相談可能です。",
        "address": "新潟県新潟市中央区女池上山2-15-6",
        "prefecture_slug": "niigata",
        "city_slug": "niigata-city",
        "latitude": 37.8950,
        "longitude": 139.0390,
        "nearest_station": "JR越後線 新潟駅",
        "station_walk_minutes": 20,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}],
        "features": ["家族葬専用", "1日1組貸切", "24時間対応", "バリアフリー"],
        "operator_name": "株式会社ダビアス新潟",
        "rating_avg": 4.5,
        "review_count": 32,
    },
    {
        "name": "青山セレモニーホール",
        "slug": "aoyama-ceremony-hall-niigata",
        "venue_type": "private_hall",
        "description": "アークベルが運営する新潟市西区青山のセレモニーホール。新潟市青山斎場に近く、火葬場へのアクセスが便利です。メモリアルルームを備え、少人数の家族葬にも対応。落ち着いた雰囲気の中でお別れの時間を過ごせます。",
        "address": "新潟県新潟市西区青山7-9-1",
        "prefecture_slug": "niigata",
        "city_slug": "niigata-city",
        "latitude": 37.8880,
        "longitude": 138.9980,
        "nearest_station": "JR越後線 青山駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["火葬場近隣", "家族葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "株式会社アークベル",
        "rating_avg": 4.2,
        "review_count": 38,
    },

    # --- 長岡市 (nagaoka) 2件 ---
    {
        "name": "長岡市斎場",
        "slug": "nagaoka-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "長岡市が運営する公営斎場。敷地内に葬儀式場と火葬施設を備え、通夜から火葬まで一貫して対応可能。長岡市民は火葬料が優遇されます。広い駐車場と充実した待合室を完備しており、大規模な葬儀にも対応できます。",
        "address": "新潟県長岡市寺泊野積8092-1",
        "prefecture_slug": "niigata",
        "city_slug": "nagaoka",
        "latitude": 37.6280,
        "longitude": 138.7820,
        "nearest_station": "JR越後線 寺泊駅",
        "station_walk_minutes": 25,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 60,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 235000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応", "バリアフリー"],
        "operator_name": "長岡市",
        "rating_avg": 3.9,
        "review_count": 35,
    },
    {
        "name": "VIPシティホール長岡",
        "slug": "vip-city-hall-nagaoka",
        "venue_type": "private_hall",
        "description": "長岡市内で実績のある民間葬儀会館。JR長岡駅から車で約10分の好立地。家族葬から一般葬まで幅広いプランに対応し、充実した控室と宿泊施設を完備。スタッフの丁寧な対応が評判の施設です。",
        "address": "新潟県長岡市喜多町707",
        "prefecture_slug": "niigata",
        "city_slug": "nagaoka",
        "latitude": 37.4560,
        "longitude": 138.8530,
        "nearest_station": "JR信越本線 長岡駅",
        "station_walk_minutes": 20,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["家族葬対応", "宿泊可能", "駐車場完備", "24時間対応"],
        "operator_name": "VIPシティホール",
        "rating_avg": 4.1,
        "review_count": 27,
    },

    # --- 上越市 (joetsu) 2件 ---
    {
        "name": "上越斎場",
        "slug": "joetsu-saijo",
        "venue_type": "public_crematorium",
        "description": "上越市が運営する公営斎場。日本海ひすいライン直江津駅からタクシー約6分の好アクセス。火葬施設と式場を備え、通夜から火葬まで対応可能。上越市民は火葬料が優遇されます。広い駐車場とバリアフリー設備を完備しています。",
        "address": "新潟県上越市大字居多776",
        "prefecture_slug": "niigata",
        "city_slug": "joetsu",
        "latitude": 37.1290,
        "longitude": 138.2310,
        "nearest_station": "日本海ひすいライン 直江津駅",
        "station_walk_minutes": 15,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 50,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 488000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "上越市",
        "rating_avg": 3.8,
        "review_count": 22,
    },
    {
        "name": "セレモニーホール上越",
        "slug": "ceremony-hall-joetsu",
        "venue_type": "private_hall",
        "description": "上越市内の民間葬儀会館。JR高田駅から車で約10分。家族葬から大規模な一般葬まで対応可能な複数のホールを備えています。24時間対応の相談窓口があり、急な場合にも安心。充実した控室と宿泊設備も完備。",
        "address": "新潟県上越市春日野1-2-5",
        "prefecture_slug": "niigata",
        "city_slug": "joetsu",
        "latitude": 37.1000,
        "longitude": 138.2450,
        "nearest_station": "えちごトキめき鉄道 高田駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "宿泊可能", "24時間対応", "駐車場完備"],
        "operator_name": "上越セレモニー",
        "rating_avg": 4.0,
        "review_count": 18,
    },

    # --- 三条市 (sanjo) 1件 ---
    {
        "name": "三条市槻の森斎苑",
        "slug": "sanjo-tsukinomori-saien",
        "venue_type": "public_crematorium",
        "description": "三条市が運営する公営の火葬場。三条市月岡に位置し、緑豊かな環境の中で故人を見送れます。火葬炉を完備し、待合室も備えています。三条市民は火葬料が優遇されます。広い駐車場を備え、アクセスも良好です。",
        "address": "新潟県三条市月岡3722",
        "prefecture_slug": "niigata",
        "city_slug": "sanjo",
        "latitude": 37.6070,
        "longitude": 138.9570,
        "nearest_station": "JR弥彦線 燕三条駅",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 40,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "三条市",
        "rating_avg": 3.7,
        "review_count": 15,
    },

    # =============================================
    # 2. 長野県 (nagano) — 8件
    # =============================================

    # --- 長野市 (nagano-city) 3件 ---
    {
        "name": "長野市大峰斎場",
        "slug": "nagano-omine-saijo",
        "venue_type": "public_crematorium",
        "description": "長野市が運営する公営火葬場。箱清水の高台に位置し、善光寺を見下ろす静かな環境です。JR信越本線「長野駅」からタクシー約20分。火葬炉を備えた市内最大の火葬場で、長野市民は火葬料が優遇されます。式場は併設されていないため、近隣のセレモニーホールとの併用が一般的です。",
        "address": "新潟県長野市大字長野箱清水1612-1",
        "prefecture_slug": "nagano",
        "city_slug": "nagano-city",
        "latitude": 36.6690,
        "longitude": 138.1860,
        "nearest_station": "JR北陸新幹線 長野駅",
        "station_walk_minutes": 30,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "長野市",
        "rating_avg": 3.7,
        "review_count": 30,
    },
    {
        "name": "ベルホール吉池 長野本店",
        "slug": "bellhall-yoshiike-nagano",
        "venue_type": "private_hall",
        "description": "長野市の老舗葬儀社・吉池が運営する葬儀ホール。JR長野駅から車で約10分。大規模な一般葬から少人数の家族葬まで対応可能。経験豊富なスタッフによる丁寧なサポートが特長で、地元で高い信頼を得ています。宿泊施設も完備。",
        "address": "長野県長野市大字鶴賀権堂町2201",
        "prefecture_slug": "nagano",
        "city_slug": "nagano-city",
        "latitude": 36.6550,
        "longitude": 138.1910,
        "nearest_station": "長野電鉄 権堂駅",
        "station_walk_minutes": 5,
        "capacity_max": 100,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 278000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["駅近", "大規模葬対応", "家族葬対応", "宿泊可能", "老舗葬儀社"],
        "operator_name": "株式会社吉池",
        "rating_avg": 4.4,
        "review_count": 52,
    },
    {
        "name": "家族葬ホールSHION若槻",
        "slug": "shion-wakatsuki-nagano",
        "venue_type": "private_hall",
        "description": "長野市若槻エリアの家族葬専用ホール。少人数の家族葬に特化した温かみのある空間。1日1組完全貸切で、ご家族だけの時間をゆっくりと過ごせます。24時間365日対応の相談窓口があり、急な場合にも安心です。",
        "address": "長野県長野市若槻東条812-1",
        "prefecture_slug": "nagano",
        "city_slug": "nagano-city",
        "latitude": 36.6810,
        "longitude": 138.2020,
        "nearest_station": "長野電鉄 信濃吉田駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}],
        "features": ["家族葬専用", "1日1組貸切", "24時間対応", "バリアフリー"],
        "operator_name": "SHION",
        "rating_avg": 4.5,
        "review_count": 25,
    },

    # --- 松本市 (matsumoto) 3件 ---
    {
        "name": "松本市営葬祭センター",
        "slug": "matsumoto-shiee-sousai-center",
        "venue_type": "public_crematorium",
        "description": "松本市が運営する公営の葬祭センター。北アルプス線「北松本駅」から徒歩13分と駅近の好立地。火葬施設と式場を備え、通夜から火葬まで一貫して対応可能。松本市民は利用料が優遇されます。北アルプスを望む静かな環境です。",
        "address": "長野県松本市蟻ケ崎4-10-1",
        "prefecture_slug": "nagano",
        "city_slug": "matsumoto",
        "latitude": 36.2480,
        "longitude": 137.9580,
        "nearest_station": "アルピコ交通上高地線 北松本駅",
        "station_walk_minutes": 13,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 50,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 488000}],
        "features": ["火葬場併設", "公営斎場", "駅近", "駐車場完備", "バリアフリー"],
        "operator_name": "松本市",
        "rating_avg": 4.0,
        "review_count": 40,
    },
    {
        "name": "コスモール・コイデ松本",
        "slug": "cosmall-koide-matsumoto",
        "venue_type": "private_hall",
        "description": "松本市内で人気の高い民間葬儀会館。家族葬から一般葬まで幅広く対応し、モダンで温かみのある空間が特長です。充実した控室と宿泊設備を完備。経験豊富なスタッフが24時間体制でサポートします。",
        "address": "長野県松本市渚3-8-25",
        "prefecture_slug": "nagano",
        "city_slug": "matsumoto",
        "latitude": 36.2320,
        "longitude": 137.9620,
        "nearest_station": "JR篠ノ井線 松本駅",
        "station_walk_minutes": 12,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["家族葬対応", "宿泊可能", "24時間対応", "駐車場完備"],
        "operator_name": "コスモール・コイデ",
        "rating_avg": 4.3,
        "review_count": 35,
    },
    {
        "name": "セレモニーホール松本南",
        "slug": "ceremony-hall-matsumoto-minami",
        "venue_type": "private_hall",
        "description": "松本市南部の家族葬対応ホール。JR南松本駅から車で約5分の好立地。少人数の家族葬に特化した落ち着いた空間で、1日1組貸切対応。安置室も備え、ご家族だけのプライベートな時間を大切にできます。",
        "address": "長野県松本市南松本1-3-12",
        "prefecture_slug": "nagano",
        "city_slug": "matsumoto",
        "latitude": 36.2220,
        "longitude": 137.9700,
        "nearest_station": "JR篠ノ井線 南松本駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}],
        "features": ["家族葬専用", "1日1組貸切", "駅近", "バリアフリー"],
        "operator_name": "松本南セレモニー",
        "rating_avg": 4.2,
        "review_count": 18,
    },

    # --- 上田市 (ueda) 1件 ---
    {
        "name": "上田地域広域連合大星斎場",
        "slug": "ueda-ooboshi-saijo",
        "venue_type": "public_crematorium",
        "description": "上田地域広域連合が運営する公営火葬場。しなの鉄道線「上田駅」からタクシー約10分。火葬炉を備え、上田市民は利用料が優遇されます。広い待合室と駐車場を完備し、落ち着いた環境で故人を見送れる施設です。",
        "address": "長野県上田市大字上田2548-2",
        "prefecture_slug": "nagano",
        "city_slug": "ueda",
        "latitude": 36.4010,
        "longitude": 138.2490,
        "nearest_station": "しなの鉄道線 上田駅",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 40,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "上田地域広域連合",
        "rating_avg": 3.8,
        "review_count": 20,
    },

    # --- 飯田市 (iida) 1件 ---
    {
        "name": "飯田市斎苑",
        "slug": "iida-shi-saien",
        "venue_type": "public_crematorium",
        "description": "飯田市が運営する公営の斎場。南アルプスを望む静かな環境に位置し、火葬施設と待合室を備えています。飯田市民は火葬料が優遇されます。伊那谷の自然に囲まれた穏やかな場所で、故人を静かに見送れる施設です。",
        "address": "長野県飯田市上郷別府3507-1",
        "prefecture_slug": "nagano",
        "city_slug": "iida",
        "latitude": 35.4950,
        "longitude": 137.8310,
        "nearest_station": "JR飯田線 元善光寺駅",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 72000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "飯田市",
        "rating_avg": 3.8,
        "review_count": 16,
    },

    # =============================================
    # 3. 岐阜県 (gifu) — 8件
    # =============================================

    # --- 岐阜市 (gifu-city) 3件 ---
    {
        "name": "岐阜市斎苑",
        "slug": "gifu-shi-saien",
        "venue_type": "public_crematorium",
        "description": "岐阜市が運営する公営の総合斎場。火葬棟・待合棟・斎場棟が回廊で結ばれた近代的な施設です。1階に大・小2つの式場を備え、通夜から火葬まで対応可能。2階には有料の待合室もあります。名鉄岐阜駅から車で約5分の好立地です。",
        "address": "岐阜県岐阜市上加納山4717-4",
        "prefecture_slug": "gifu",
        "city_slug": "gifu-city",
        "latitude": 35.4210,
        "longitude": 136.7680,
        "nearest_station": "名鉄各務原線 田神駅",
        "station_walk_minutes": 16,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 80,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応", "バリアフリー"],
        "operator_name": "岐阜市",
        "rating_avg": 4.1,
        "review_count": 55,
    },
    {
        "name": "メモリア岐阜東",
        "slug": "memoria-gifu-higashi",
        "venue_type": "private_hall",
        "description": "メモリアグループが運営する岐阜市東部の家族葬対応ホール。少人数からの家族葬に特化し、温かみのある空間を提供。1日1組完全貸切で、プライベートな時間を大切にできます。24時間365日相談可能です。",
        "address": "岐阜県岐阜市日野東3-13-20",
        "prefecture_slug": "gifu",
        "city_slug": "gifu-city",
        "latitude": 35.3980,
        "longitude": 136.8020,
        "nearest_station": "名鉄名古屋本線 名鉄岐阜駅",
        "station_walk_minutes": 25,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}],
        "features": ["家族葬専用", "1日1組貸切", "24時間対応", "バリアフリー"],
        "operator_name": "メモリアホールディングス",
        "rating_avg": 4.4,
        "review_count": 30,
    },
    {
        "name": "葬儀斎場メモワール岐阜",
        "slug": "memoir-gifu",
        "venue_type": "private_hall",
        "description": "メモワールが運営する岐阜市の葬儀会館。岐阜市斎苑の近くに位置し、火葬場へのアクセスが便利です。大規模な一般葬から家族葬まで幅広く対応。モダンなデザインの式場と充実した設備が特長の施設です。",
        "address": "岐阜県岐阜市加納上本町4-1-1",
        "prefecture_slug": "gifu",
        "city_slug": "gifu-city",
        "latitude": 35.4080,
        "longitude": 136.7580,
        "nearest_station": "JR東海道本線 岐阜駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 578000}],
        "features": ["火葬場近隣", "大規模葬対応", "家族葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "株式会社メモワール",
        "rating_avg": 4.2,
        "review_count": 38,
    },

    # --- 大垣市 (ogaki) 2件 ---
    {
        "name": "大垣市鶴見斎場",
        "slug": "ogaki-tsurumi-saijo",
        "venue_type": "public_crematorium",
        "description": "大垣市が運営する公営斎場。JR大垣駅からタクシー約10分。火葬施設と式場を備え、通夜から火葬まで一貫して対応可能。大垣市民は火葬料が優遇されます。広い駐車場を完備し、バリアフリーにも対応しています。",
        "address": "岐阜県大垣市鶴見町581",
        "prefecture_slug": "gifu",
        "city_slug": "ogaki",
        "latitude": 35.3640,
        "longitude": 136.6120,
        "nearest_station": "JR東海道本線 大垣駅",
        "station_walk_minutes": 20,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 60,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 232000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応", "バリアフリー"],
        "operator_name": "大垣市",
        "rating_avg": 4.0,
        "review_count": 32,
    },
    {
        "name": "メモリア大垣",
        "slug": "memoria-ogaki",
        "venue_type": "private_hall",
        "description": "メモリアグループが運営する大垣市の家族葬対応ホール。JR大垣駅から車で約8分。家族葬から一般葬まで幅広いプランに対応。温かみのあるモダンな内装と充実した設備が特長。24時間対応の相談窓口があります。",
        "address": "岐阜県大垣市林町5-80-2",
        "prefecture_slug": "gifu",
        "city_slug": "ogaki",
        "latitude": 35.3580,
        "longitude": 136.6250,
        "nearest_station": "JR東海道本線 大垣駅",
        "station_walk_minutes": 15,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000}],
        "features": ["家族葬対応", "24時間対応", "バリアフリー", "駐車場完備"],
        "operator_name": "メモリアホールディングス",
        "rating_avg": 4.3,
        "review_count": 22,
    },

    # --- 各務原市 (kakamigahara) 1件 ---
    {
        "name": "各務原市斎場",
        "slug": "kakamigahara-saijo",
        "venue_type": "public_crematorium",
        "description": "各務原市が運営する公営火葬場。JR高山本線「那加駅」からタクシー約10分。火葬施設を備え、各務原市民は火葬料が優遇されます。静かな環境に位置し、待合室と駐車場を完備。バリアフリー対応の施設です。",
        "address": "岐阜県各務原市鵜沼朝日町7-55",
        "prefecture_slug": "gifu",
        "city_slug": "kakamigahara",
        "latitude": 35.4050,
        "longitude": 136.8790,
        "nearest_station": "JR高山本線 那加駅",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "各務原市",
        "rating_avg": 3.8,
        "review_count": 18,
    },

    # --- 多治見市 (tajimi) 1件 ---
    {
        "name": "多治見市営斎場",
        "slug": "tajimi-shiee-saijo",
        "venue_type": "public_crematorium",
        "description": "多治見市が運営する公営火葬場。JR中央本線「多治見駅」からタクシー約15分。火葬炉を備え、多治見市民は火葬料が優遇されます。焼き物の街・多治見らしい落ち着いた佇まいの施設で、待合室と駐車場を完備しています。",
        "address": "岐阜県多治見市廿原町232-1",
        "prefecture_slug": "gifu",
        "city_slug": "tajimi",
        "latitude": 35.3230,
        "longitude": 137.1320,
        "nearest_station": "JR中央本線 多治見駅",
        "station_walk_minutes": 25,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 25,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "多治見市",
        "rating_avg": 3.7,
        "review_count": 14,
    },

    # --- 高山市 (takayama) 1件 ---
    {
        "name": "フローラメモリアルホール高山",
        "slug": "flora-memorial-takayama",
        "venue_type": "private_hall",
        "description": "飛騨高山エリアの民間葬儀会館。JR高山本線「高山駅」から車で約10分。飛騨の伝統に配慮した落ち着いた佇まいの式場で、家族葬から一般葬まで幅広く対応。地元の風習に精通したスタッフが丁寧にサポートします。",
        "address": "岐阜県高山市花里町5-18",
        "prefecture_slug": "gifu",
        "city_slug": "takayama",
        "latitude": 36.1440,
        "longitude": 137.2510,
        "nearest_station": "JR高山本線 高山駅",
        "station_walk_minutes": 12,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["家族葬対応", "宿泊可能", "駐車場完備", "地域密着"],
        "operator_name": "JAグリーン株式会社",
        "rating_avg": 4.1,
        "review_count": 20,
    },

    # =============================================
    # 4. 富山県 (toyama) — 6件
    # =============================================

    # --- 富山市 (toyama-city) 3件 ---
    {
        "name": "富山市北斎場",
        "slug": "toyama-kita-saijo",
        "venue_type": "public_crematorium",
        "description": "富山市が運営する北部地区の公営火葬場。あいの風とやま鉄道「富山駅」からタクシー約15分。火葬炉を備え、富山市民は火葬料が優遇されます。近代的な設備と広い駐車場を完備。立山連峰を望む静かな環境にある施設です。",
        "address": "富山県富山市古沢501",
        "prefecture_slug": "toyama",
        "city_slug": "toyama-city",
        "latitude": 36.7020,
        "longitude": 137.1680,
        "nearest_station": "あいの風とやま鉄道 富山駅",
        "station_walk_minutes": 25,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 50,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "富山市",
        "rating_avg": 3.9,
        "review_count": 35,
    },
    {
        "name": "ティア富山大泉",
        "slug": "tear-toyama-oizumi",
        "venue_type": "private_hall",
        "description": "ティアが運営する富山市の家族葬専用ホール。富山地方鉄道「大泉駅」から徒歩7分と駅近の好立地。少人数の家族葬に特化した温かみのある空間で、1日1組完全貸切対応。コンパクトながら充実した設備を備えています。",
        "address": "富山県富山市大泉東町1-9-5",
        "prefecture_slug": "toyama",
        "city_slug": "toyama-city",
        "latitude": 36.6850,
        "longitude": 137.2180,
        "nearest_station": "富山地方鉄道 大泉駅",
        "station_walk_minutes": 7,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}],
        "features": ["駅近", "家族葬専用", "1日1組貸切", "バリアフリー"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.5,
        "review_count": 28,
    },
    {
        "name": "オークスセレモニーホール富山",
        "slug": "oarks-ceremony-toyama",
        "venue_type": "private_hall",
        "description": "オークスが運営する富山市の大型葬儀会館。家族葬から大規模な一般葬まで対応可能な複数のホールを備え、充実した設備と宿泊施設を完備。経験豊富なスタッフによる丁寧なサポートが評判です。駐車場も十分に確保しています。",
        "address": "富山県富山市新庄町2-6-33",
        "prefecture_slug": "toyama",
        "city_slug": "toyama-city",
        "latitude": 36.6920,
        "longitude": 137.2290,
        "nearest_station": "富山地方鉄道 東新庄駅",
        "station_walk_minutes": 8,
        "capacity_max": 100,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 60,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 115000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 578000}],
        "features": ["大規模葬対応", "家族葬対応", "宿泊可能", "駐車場完備", "駅近"],
        "operator_name": "オークス株式会社",
        "rating_avg": 4.2,
        "review_count": 42,
    },

    # --- 高岡市 (takaoka) 2件 ---
    {
        "name": "高岡斎場",
        "slug": "takaoka-saijo",
        "venue_type": "public_crematorium",
        "description": "高岡市が運営する公営の総合斎場。グリーンパーク内に位置し、広大な敷地と充実した駐車スペースを誇ります。乗用車210台・バス10台の駐車が可能。火葬場と式場を備え、通夜から火葬まで一貫対応。バリアフリー設計で安心です。",
        "address": "富山県高岡市グリーンパーク1",
        "prefecture_slug": "toyama",
        "city_slug": "takaoka",
        "latitude": 36.7580,
        "longitude": 137.0130,
        "nearest_station": "JR城端線 新高岡駅",
        "station_walk_minutes": 30,
        "capacity_max": 120,
        "hall_count": 3,
        "has_crematorium": True,
        "parking_count": 210,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True, "マイクロバス駐車": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 235000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "大規模葬対応", "バリアフリー"],
        "operator_name": "高岡市",
        "rating_avg": 4.1,
        "review_count": 48,
    },
    {
        "name": "オークスセレモニーホール高岡",
        "slug": "oarks-ceremony-takaoka",
        "venue_type": "private_hall",
        "description": "オークスが運営する高岡市の葬儀会館。JR高岡駅から車で約8分。家族葬から一般葬まで対応可能な式場を備え、充実した控室と宿泊設備を完備。地元に根差した丁寧なサービスで、高岡市民に親しまれています。",
        "address": "富山県高岡市中曽根2208",
        "prefecture_slug": "toyama",
        "city_slug": "takaoka",
        "latitude": 36.7420,
        "longitude": 137.0260,
        "nearest_station": "JR北陸新幹線 新高岡駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["家族葬対応", "宿泊可能", "駐車場完備", "バリアフリー"],
        "operator_name": "オークス株式会社",
        "rating_avg": 4.2,
        "review_count": 25,
    },

    # --- 射水市 (imizu) 1件 ---
    {
        "name": "射水市斎場",
        "slug": "imizu-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "射水市が運営する公営火葬場。JR「越中大門駅」からタクシー約10分。火葬炉を備え、射水市民は火葬料が優遇されます。静かな環境に位置し、待合室と駐車場を完備。バリアフリー対応の近代的な施設です。",
        "address": "富山県射水市沖塚原128-1",
        "prefecture_slug": "toyama",
        "city_slug": "imizu",
        "latitude": 36.7210,
        "longitude": 137.0830,
        "nearest_station": "あいの風とやま鉄道 越中大門駅",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "射水市",
        "rating_avg": 3.8,
        "review_count": 15,
    },

    # =============================================
    # 5. 石川県 (ishikawa) — 6件
    # =============================================

    # --- 金沢市 (kanazawa) 3件 ---
    {
        "name": "金沢市東斎場",
        "slug": "kanazawa-higashi-saijo",
        "venue_type": "public_crematorium",
        "description": "金沢市が運営する東部地区の公営斎場。鳴和台に位置し、火葬施設と待合室を備えています。金沢市民は火葬料が優遇されます。火葬から収骨まで約2時間。近代的な設備とバリアフリー対応で、安心して利用できる施設です。",
        "address": "石川県金沢市鳴和台360",
        "prefecture_slug": "ishikawa",
        "city_slug": "kanazawa",
        "latitude": 36.5840,
        "longitude": 136.6780,
        "nearest_station": "JR北陸本線 金沢駅",
        "station_walk_minutes": 20,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 50,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "金沢市",
        "rating_avg": 3.9,
        "review_count": 40,
    },
    {
        "name": "金沢市南斎場",
        "slug": "kanazawa-minami-saijo",
        "venue_type": "public_crematorium",
        "description": "金沢市が運営する南部地区の公営斎場。西泉に位置し、金沢西ICからのアクセスが便利です。火葬施設を備え、金沢市民は火葬料が優遇されます。近代的な設備と充実した待合室を完備。落ち着いた環境で故人を見送れます。",
        "address": "石川県金沢市西泉6-64",
        "prefecture_slug": "ishikawa",
        "city_slug": "kanazawa",
        "latitude": 36.5550,
        "longitude": 136.6310,
        "nearest_station": "北陸鉄道石川線 野町駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 40,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "金沢市",
        "rating_avg": 3.9,
        "review_count": 35,
    },
    {
        "name": "セレモニーハウス金沢神宮寺",
        "slug": "ceremony-house-kanazawa-jinguji",
        "venue_type": "private_hall",
        "description": "らくおう・セレモニーハウスが運営する金沢市の家族葬対応ホール。金沢市神宮寺に位置し、少人数の家族葬に特化。1日1組完全貸切で、プライベートな空間でお別れの時間を過ごせます。24時間365日相談可能です。",
        "address": "石川県金沢市神宮寺1-16-23",
        "prefecture_slug": "ishikawa",
        "city_slug": "kanazawa",
        "latitude": 36.5710,
        "longitude": 136.6450,
        "nearest_station": "JR北陸本線 金沢駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}],
        "features": ["家族葬専用", "1日1組貸切", "24時間対応", "バリアフリー"],
        "operator_name": "家族葬のらくおう・セレモニーハウス",
        "rating_avg": 4.4,
        "review_count": 22,
    },

    # --- 白山市 (hakusan) 1件 ---
    {
        "name": "白山市松任斎場",
        "slug": "hakusan-mattou-saijo",
        "venue_type": "public_crematorium",
        "description": "白山市が運営する公営火葬場。JR北陸本線「松任駅」からタクシー約10分。火葬施設を備え、白山市民は火葬料が優遇されます。白山の麓に位置する静かな環境で、広い駐車場と待合室を完備しています。",
        "address": "石川県白山市幸明町280",
        "prefecture_slug": "ishikawa",
        "city_slug": "hakusan",
        "latitude": 36.5250,
        "longitude": 136.5680,
        "nearest_station": "JR北陸本線 松任駅",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "白山市",
        "rating_avg": 3.8,
        "review_count": 18,
    },

    # --- 小松市 (komatsu) 1件 ---
    {
        "name": "小松加賀斎場さざなみ",
        "slug": "komatsu-kaga-sazanami",
        "venue_type": "public_crematorium",
        "description": "小松市・加賀市・能美市・川北町の広域で運営される公営斎場。近代的な設備を備えた火葬場で、地域住民は火葬料が優遇されます。広い駐車場と充実した待合室を完備。バリアフリー対応で安心して利用できます。",
        "address": "石川県小松市長谷町ヨ75",
        "prefecture_slug": "ishikawa",
        "city_slug": "komatsu",
        "latitude": 36.3920,
        "longitude": 136.4450,
        "nearest_station": "JR北陸本線 小松駅",
        "station_walk_minutes": 25,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 60,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 488000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー", "広域利用可能"],
        "operator_name": "小松加賀広域事務組合",
        "rating_avg": 4.0,
        "review_count": 25,
    },

    # --- 加賀市 (kaga) 1件 ---
    {
        "name": "加賀市セレモニーホール",
        "slug": "kaga-ceremony-hall",
        "venue_type": "private_hall",
        "description": "加賀温泉郷に近い民間葬儀会館。JR北陸本線「加賀温泉駅」から車で約8分。家族葬から一般葬まで対応可能な式場を備え、充実した控室と駐車場を完備。温泉街の落ち着いた雰囲気の中、丁寧なサービスを提供しています。",
        "address": "石川県加賀市山代温泉18-120",
        "prefecture_slug": "ishikawa",
        "city_slug": "kaga",
        "latitude": 36.2980,
        "longitude": 136.3620,
        "nearest_station": "JR北陸本線 加賀温泉駅",
        "station_walk_minutes": 15,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "駐車場完備", "バリアフリー", "24時間対応"],
        "operator_name": "加賀セレモニー",
        "rating_avg": 4.0,
        "review_count": 12,
    },

    # =============================================
    # 6. 福井県 (fukui) — 6件
    # =============================================

    # --- 福井市 (fukui-city) 3件 ---
    {
        "name": "福井市聖苑",
        "slug": "fukui-shi-seien",
        "venue_type": "public_crematorium",
        "description": "福井市が運営する公営の火葬場。火葬棟に火葬炉10基・小型炉1基を備え、待合棟には複数の和室・洋室と待合ロビーを完備。えちぜん鉄道「日華化学前駅」からタクシー約16分。福井市民は火葬料が優遇されます。喫茶コーナーもあります。",
        "address": "福井県福井市安田町11-1",
        "prefecture_slug": "fukui",
        "city_slug": "fukui-city",
        "latitude": 36.0720,
        "longitude": 136.1850,
        "nearest_station": "えちぜん鉄道 日華化学前駅",
        "station_walk_minutes": 25,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 50,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "福井市",
        "rating_avg": 3.9,
        "review_count": 38,
    },
    {
        "name": "オームラ福井ホール",
        "slug": "oomura-fukui-hall",
        "venue_type": "private_hall",
        "description": "福井の老舗葬儀社・オームラが運営する葬儀会館。JR福井駅から車で約10分。家族葬から一般葬まで幅広く対応。安置室・宿泊施設を完備し、付き添いも可能。地元で長年の実績を持つ信頼の葬儀社です。",
        "address": "福井県福井市花堂南1-1-20",
        "prefecture_slug": "fukui",
        "city_slug": "fukui-city",
        "latitude": 36.0460,
        "longitude": 136.2180,
        "nearest_station": "JR北陸本線 福井駅",
        "station_walk_minutes": 20,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["家族葬対応", "宿泊可能", "安置付添い可", "駐車場完備", "老舗葬儀社"],
        "operator_name": "株式会社オームラ",
        "rating_avg": 4.3,
        "review_count": 32,
    },
    {
        "name": "セレモニー福井会館",
        "slug": "ceremony-fukui-kaikan",
        "venue_type": "private_hall",
        "description": "福井市内の民間葬儀会館。JR福井駅から車で約8分の好立地。モダンな内装の式場を備え、少人数の家族葬から大規模な一般葬まで対応。24時間対応の相談窓口があり、急な場合にも安心です。",
        "address": "福井県福井市文京4-15-22",
        "prefecture_slug": "fukui",
        "city_slug": "fukui-city",
        "latitude": 36.0580,
        "longitude": 136.2080,
        "nearest_station": "JR北陸本線 福井駅",
        "station_walk_minutes": 15,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "24時間対応", "駐車場完備", "バリアフリー"],
        "operator_name": "株式会社セレモニー福井",
        "rating_avg": 4.1,
        "review_count": 20,
    },

    # --- 坂井市 (sakai-fukui) 1件 ---
    {
        "name": "赤坂聖苑",
        "slug": "akasaka-seien-sakai",
        "venue_type": "public_crematorium",
        "description": "坂井市が運営する公営の火葬場。坂井市丸岡に位置し、北陸自動車道丸岡ICからのアクセスが便利。火葬炉を備え、坂井市民は火葬料が優遇されます。静かな環境で、待合室と広い駐車場を完備しています。",
        "address": "福井県坂井市丸岡町山口60-8",
        "prefecture_slug": "fukui",
        "city_slug": "sakai-fukui",
        "latitude": 36.1510,
        "longitude": 136.2650,
        "nearest_station": "JR北陸本線 丸岡駅",
        "station_walk_minutes": 25,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "坂井市",
        "rating_avg": 3.7,
        "review_count": 14,
    },

    # --- 越前市 (echizen) 1件 ---
    {
        "name": "越前市斎場",
        "slug": "echizen-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "越前市が運営する公営火葬場。JR北陸本線「武生駅」からタクシー約15分。火葬施設と待合室を備え、越前市民は火葬料が優遇されます。越前の自然に囲まれた静かな環境で、故人を穏やかに見送れる施設です。",
        "address": "福井県越前市余田町52-25-1",
        "prefecture_slug": "fukui",
        "city_slug": "echizen",
        "latitude": 35.9020,
        "longitude": 136.1690,
        "nearest_station": "JR北陸本線 武生駅",
        "station_walk_minutes": 25,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 25,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 72000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "越前市",
        "rating_avg": 3.7,
        "review_count": 12,
    },

    # --- 敦賀市 (tsuruga) 1件 ---
    {
        "name": "敦賀斎苑",
        "slug": "tsuruga-saien",
        "venue_type": "public_crematorium",
        "description": "敦賀市が運営する公営の火葬場。北陸新幹線「敦賀駅」からタクシー約10分。火葬施設と待合室を備え、敦賀市民は火葬料が優遇されます。敦賀湾を望む丘の上に位置し、穏やかな雰囲気の中で故人を見送れます。",
        "address": "福井県敦賀市沓見71-7",
        "prefecture_slug": "fukui",
        "city_slug": "tsuruga",
        "latitude": 35.6550,
        "longitude": 136.0720,
        "nearest_station": "北陸新幹線 敦賀駅",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "敦賀市",
        "rating_avg": 3.8,
        "review_count": 16,
    },

    # =============================================
    # 7. 山梨県 (yamanashi) — 6件
    # =============================================

    # --- 甲府市 (kofu) 3件 ---
    {
        "name": "甲府市斎場",
        "slug": "kofu-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "甲府市が運営する公営の火葬場。JR中央本線「甲府駅」からタクシー約7分の好アクセス。火葬施設と待合室を備え、甲府市民は火葬料が優遇されます。富士山と南アルプスを望む静かな環境で、故人を穏やかに見送れる施設です。",
        "address": "山梨県甲府市古府中町5079-6",
        "prefecture_slug": "yamanashi",
        "city_slug": "kofu",
        "latitude": 35.6750,
        "longitude": 138.5590,
        "nearest_station": "JR中央本線 甲府駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 40,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "甲府市",
        "rating_avg": 3.9,
        "review_count": 35,
    },
    {
        "name": "アピオセレモニーホール天昇殿",
        "slug": "apio-tensyouden-kofu",
        "venue_type": "private_hall",
        "description": "甲府市の老舗葬儀会館。JR身延線「南甲府駅」から徒歩1分と抜群のアクセス。大規模な一般葬から少人数の家族葬まで幅広く対応。モダンな内装と充実した設備が特長で、経験豊富なスタッフが丁寧にサポートします。",
        "address": "山梨県甲府市住吉5-20-1",
        "prefecture_slug": "yamanashi",
        "city_slug": "kofu",
        "latitude": 35.6440,
        "longitude": 138.5710,
        "nearest_station": "JR身延線 南甲府駅",
        "station_walk_minutes": 1,
        "capacity_max": 100,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 278000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["駅近", "大規模葬対応", "家族葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "アピオ株式会社",
        "rating_avg": 4.4,
        "review_count": 48,
    },
    {
        "name": "ささごん中央ホール",
        "slug": "sasagon-chuo-hall-kofu",
        "venue_type": "private_hall",
        "description": "甲府市中心部の民間葬儀会館。JR甲府駅から車で約8分。家族葬に特化した温かみのある空間で、少人数でゆっくりとお別れの時間を過ごせます。安置室と控室を完備し、24時間365日対応の相談窓口があります。",
        "address": "山梨県甲府市中央4-7-15",
        "prefecture_slug": "yamanashi",
        "city_slug": "kofu",
        "latitude": 35.6600,
        "longitude": 138.5680,
        "nearest_station": "JR中央本線 甲府駅",
        "station_walk_minutes": 12,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}],
        "features": ["家族葬専用", "24時間対応", "駐車場完備", "バリアフリー"],
        "operator_name": "株式会社ささごん",
        "rating_avg": 4.2,
        "review_count": 22,
    },

    # --- 甲斐市 (kai) 1件 ---
    {
        "name": "やすらぎ聖苑",
        "slug": "yasuragi-seien-kai",
        "venue_type": "public_crematorium",
        "description": "甲斐市が運営する公営の火葬場。甲斐市竜王に位置し、JR中央本線「竜王駅」からタクシー約10分。火葬施設と待合室を備え、甲斐市民は火葬料が優遇されます。富士山を望む静かな環境の近代的な施設です。",
        "address": "山梨県甲斐市竜王新町2028",
        "prefecture_slug": "yamanashi",
        "city_slug": "kai",
        "latitude": 35.6530,
        "longitude": 138.5230,
        "nearest_station": "JR中央本線 竜王駅",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "甲斐市",
        "rating_avg": 3.8,
        "review_count": 18,
    },

    # --- 南アルプス市 (minami-alps) 1件 ---
    {
        "name": "ふじかわ聖苑",
        "slug": "fujikawa-seien-minami-alps",
        "venue_type": "public_crematorium",
        "description": "三郡衛生組合が運営する公営の火葬場。南アルプス市・中央市・昭和町の住民が利用可能。南アルプスの山々を望む静かな環境に位置し、近代的な火葬施設と充実した待合室を備えています。広い駐車場も完備。",
        "address": "山梨県南アルプス市小笠原1310",
        "prefecture_slug": "yamanashi",
        "city_slug": "minami-alps",
        "latitude": 35.6090,
        "longitude": 138.4820,
        "nearest_station": "JR身延線 東花輪駅",
        "station_walk_minutes": 30,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 40,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "広域利用可能", "バリアフリー"],
        "operator_name": "三郡衛生組合",
        "rating_avg": 3.8,
        "review_count": 15,
    },

    # --- 富士吉田市 (fujiyoshida) 1件 ---
    {
        "name": "シティホール富士吉田",
        "slug": "city-hall-fujiyoshida",
        "venue_type": "private_hall",
        "description": "富士吉田市の民間葬儀会館。富士急行線「富士山駅」から車で約5分。富士山の麓に位置する落ち着いた雰囲気の式場で、家族葬から一般葬まで対応。地元の風習に精通したスタッフが丁寧にサポートします。",
        "address": "山梨県富士吉田市上吉田5521",
        "prefecture_slug": "yamanashi",
        "city_slug": "fujiyoshida",
        "latitude": 35.4870,
        "longitude": 138.7980,
        "nearest_station": "富士急行線 富士山駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["家族葬対応", "宿泊可能", "駐車場完備", "地域密着"],
        "operator_name": "シティホール",
        "rating_avg": 4.1,
        "review_count": 20,
    },
]


def post_batch(batch, batch_num):
    """10件ずつバッチでPOSTする"""
    data = json.dumps(batch, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(SUPABASE_URL, data=data, headers=HEADERS, method="POST")
    try:
        with urllib.request.urlopen(req) as resp:
            print(f"  バッチ {batch_num}: {resp.status} — {len(batch)}件投入成功")
            return True
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"  バッチ {batch_num}: エラー {e.code} — {body}")
        return False


def count_by_prefecture():
    """県別の件数を確認する"""
    prefectures = ["niigata", "nagano", "gifu", "toyama", "ishikawa", "fukui", "yamanashi"]
    pref_names = {
        "niigata": "新潟県", "nagano": "長野県", "gifu": "岐阜県",
        "toyama": "富山県", "ishikawa": "石川県", "fukui": "福井県", "yamanashi": "山梨県"
    }
    for pref in prefectures:
        url = f"{SUPABASE_URL}?prefecture_slug=eq.{pref}&select=id"
        req = urllib.request.Request(url, headers={
            "apikey": API_KEY,
            "Authorization": f"Bearer {API_KEY}",
            "Prefer": "count=exact",
        })
        try:
            with urllib.request.urlopen(req) as resp:
                # countヘッダーから取得
                content_range = resp.headers.get("Content-Range", "")
                body = json.loads(resp.read().decode())
                count = len(body)
                print(f"  {pref_names[pref]} ({pref}): {count}件")
        except urllib.error.HTTPError as e:
            print(f"  {pref_names[pref]} ({pref}): エラー {e.code}")


def main():
    print(f"=== 中部7県 斎場データ投入 ===")
    print(f"総件数: {len(venues)}件")
    print()

    # 県別の件数をカウント
    pref_count = {}
    for v in venues:
        pref = v["prefecture_slug"]
        pref_count[pref] = pref_count.get(pref, 0) + 1
    pref_names = {
        "niigata": "新潟県", "nagano": "長野県", "gifu": "岐阜県",
        "toyama": "富山県", "ishikawa": "石川県", "fukui": "福井県", "yamanashi": "山梨県"
    }
    for pref, count in pref_count.items():
        print(f"  {pref_names.get(pref, pref)}: {count}件")
    print()

    # 10件ずつバッチ投入
    batch_size = 10
    success_count = 0
    fail_count = 0
    for i in range(0, len(venues), batch_size):
        batch = venues[i:i + batch_size]
        batch_num = i // batch_size + 1
        print(f"バッチ {batch_num} ({len(batch)}件) 投入中...")
        if post_batch(batch, batch_num):
            success_count += len(batch)
        else:
            fail_count += len(batch)
        time.sleep(1)

    print()
    print(f"=== 投入結果 ===")
    print(f"成功: {success_count}件 / 失敗: {fail_count}件")
    print()

    # 県別件数を検証
    print("=== 県別件数検証 ===")
    count_by_prefecture()


if __name__ == "__main__":
    main()
