#!/usr/bin/env python3
"""
千葉県の斎場データをSupabase REST APIに投入するスクリプト
10件ずつバッチでPOSTする
"""

import json
import urllib.request
import urllib.error
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

HEADERS = {
    "apikey": API_KEY,
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal",
}

# 千葉県の全斎場データ（40件）
venues = [
    # =============================================
    # 1. 千葉市 (chiba-city) — 8件
    # =============================================
    {
        "name": "千葉市斎場",
        "slug": "chiba-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "千葉市が運営する公営の総合斎場。火葬棟と式場棟を備え、通夜から火葬まで同一敷地内で執り行えます。JR外房線「鎌取駅」からバス5分。駐車場200台と広く、大規模な葬儀にも対応可能。千葉市民は火葬料無料で利用できます。",
        "address": "千葉県千葉市緑区平山町1762-2",
        "prefecture_slug": "chiba",
        "city_slug": "chiba-city",
        "latitude": 35.5690,
        "longitude": 140.1670,
        "nearest_station": "JR外房線 鎌取駅",
        "station_walk_minutes": 15,
        "capacity_max": 100,
        "hall_count": 3,
        "has_crematorium": True,
        "parking_count": 200,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True, "マイクロバス駐車": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応", "バリアフリー"],
        "operator_name": "千葉市",
        "rating_avg": 4.1,
        "review_count": 58,
    },
    {
        "name": "セレモ千葉駅北口ホール",
        "slug": "ceremo-chiba-ekikitaguchi",
        "venue_type": "private_hall",
        "description": "セレモが運営する千葉駅至近の家族葬専用ホール。JR千葉駅北口から徒歩3分と抜群のアクセス。少人数の家族葬に特化した温かみのある空間で、1日1組貸切対応。24時間365日相談可能です。",
        "address": "千葉県千葉市中央区弁天1-15-1",
        "prefecture_slug": "chiba",
        "city_slug": "chiba-city",
        "latitude": 35.6130,
        "longitude": 140.1130,
        "nearest_station": "JR総武線 千葉駅",
        "station_walk_minutes": 3,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}],
        "features": ["駅近", "家族葬専用", "1日1組貸切", "24時間対応"],
        "operator_name": "株式会社セレモ",
        "rating_avg": 4.3,
        "review_count": 35,
    },
    {
        "name": "セレモ千葉寺駅ホール",
        "slug": "ceremo-chibadera",
        "venue_type": "private_hall",
        "description": "セレモが運営する千葉寺エリアの葬儀ホール。京成千原線「千葉寺駅」から徒歩5分。広々とした式場と充実した控室を備え、家族葬から一般葬まで幅広く対応。静かな住宅街に位置し落ち着いた雰囲気です。",
        "address": "千葉県千葉市中央区千葉寺町1208-2",
        "prefecture_slug": "chiba",
        "city_slug": "chiba-city",
        "latitude": 35.5920,
        "longitude": 140.1260,
        "nearest_station": "京成千原線 千葉寺駅",
        "station_walk_minutes": 5,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 278000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["駅近", "家族葬対応", "宿泊可能", "バリアフリー"],
        "operator_name": "株式会社セレモ",
        "rating_avg": 4.2,
        "review_count": 28,
    },
    {
        "name": "千葉中央メモリアルホール",
        "slug": "chiba-chuo-memorial",
        "venue_type": "private_hall",
        "description": "千葉市中央区の大型葬儀会館。JR千葉駅から車で10分の好立地。最大80名収容の式場を含む3つのホールを備え、少人数の家族葬から大規模な一般葬まで対応。モダンな内装と充実した設備が特長です。",
        "address": "千葉県千葉市中央区松波3-12-5",
        "prefecture_slug": "chiba",
        "city_slug": "chiba-city",
        "latitude": 35.6090,
        "longitude": 140.1020,
        "nearest_station": "JR総武線 西千葉駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 128000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 298000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 418000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["大規模葬対応", "家族葬対応", "駐車場完備", "バリアフリー"],
        "operator_name": "千葉メモリアルサービス株式会社",
        "rating_avg": 4.0,
        "review_count": 22,
    },
    {
        "name": "博全社千葉ホール",
        "slug": "hakuzensha-chiba",
        "venue_type": "private_hall",
        "description": "千葉の老舗葬儀社・博全社が運営する葬儀会館。千葉市稲毛区に位置し、JR稲毛駅からバスで約10分。伝統と格式を重視した葬儀に対応。経験豊富なスタッフによる丁寧なサポートが評判です。",
        "address": "千葉県千葉市稲毛区小仲台7-1-3",
        "prefecture_slug": "chiba",
        "city_slug": "chiba-city",
        "latitude": 35.6310,
        "longitude": 140.1050,
        "nearest_station": "JR総武線 稲毛駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 138000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 428000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000}],
        "features": ["老舗葬儀社", "家族葬対応", "丁寧なサポート"],
        "operator_name": "株式会社博全社",
        "rating_avg": 4.2,
        "review_count": 31,
    },
    {
        "name": "家族葬のファミーユ千葉花見川",
        "slug": "famillu-chiba-hanamigawa",
        "venue_type": "private_hall",
        "description": "ファミーユが運営する家族葬専用ホール。千葉市花見川区の閑静な住宅地に位置し、1日1組貸切のプライベート空間を提供。少人数でゆっくりとお別れができる温かみのある空間です。",
        "address": "千葉県千葉市花見川区幕張町5-220",
        "prefecture_slug": "chiba",
        "city_slug": "chiba-city",
        "latitude": 35.6590,
        "longitude": 140.0480,
        "nearest_station": "JR総武線 幕張駅",
        "station_walk_minutes": 8,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}],
        "features": ["家族葬専用", "1日1組貸切", "バリアフリー"],
        "operator_name": "株式会社家族葬のファミーユ",
        "rating_avg": 4.4,
        "review_count": 19,
    },
    {
        "name": "西願寺会館",
        "slug": "saiganji-kaikan-chiba",
        "venue_type": "temple_hall",
        "description": "浄土宗の寺院が運営する式場。千葉市若葉区に位置し、古き良き日本の伝統を感じる落ち着いた空間です。宗派を問わず利用可能で、寺院ならではの厳粛な雰囲気の中で故人を送ることができます。",
        "address": "千葉県千葉市若葉区桜木4-16-11",
        "prefecture_slug": "chiba",
        "city_slug": "chiba-city",
        "latitude": 35.6210,
        "longitude": 140.1420,
        "nearest_station": "千葉都市モノレール 桜木駅",
        "station_walk_minutes": 7,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["寺院式場", "宗派不問", "伝統的な雰囲気"],
        "operator_name": "西願寺",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "千葉美浜セレモニーホール",
        "slug": "chiba-mihama-ceremony",
        "venue_type": "private_hall",
        "description": "千葉市美浜区の海浜幕張エリアに位置する近代的な葬儀会館。JR京葉線「海浜幕張駅」から徒歩12分。明るく開放的な雰囲気の式場で、故人らしいお別れをプロデュースします。",
        "address": "千葉県千葉市美浜区打瀬2-5-1",
        "prefecture_slug": "chiba",
        "city_slug": "chiba-city",
        "latitude": 35.6480,
        "longitude": 140.0400,
        "nearest_station": "JR京葉線 海浜幕張駅",
        "station_walk_minutes": 12,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 288000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 408000}],
        "features": ["近代的設備", "家族葬対応", "バリアフリー", "駐車場完備"],
        "operator_name": "美浜セレモニー株式会社",
        "rating_avg": 4.1,
        "review_count": 17,
    },
    # =============================================
    # 2. 船橋市 (funabashi) — 5件
    # =============================================
    {
        "name": "馬込斎場",
        "slug": "magome-saijo",
        "venue_type": "public_crematorium",
        "description": "船橋市・習志野市・八千代市・鎌ケ谷市の四市複合事務組合が運営する公営斎場。火葬業務と霊柩車運行業務を行っています。駐車場は普通車200台・マイクロバス4台と広大。関係4市民は火葬料が無料です。",
        "address": "千葉県船橋市馬込町1102-1",
        "prefecture_slug": "chiba",
        "city_slug": "funabashi",
        "latitude": 35.7570,
        "longitude": 139.9910,
        "nearest_station": "東武アーバンパークライン 馬込沢駅",
        "station_walk_minutes": 20,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 200,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "マイクロバス駐車": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応"],
        "operator_name": "四市複合事務組合",
        "rating_avg": 4.0,
        "review_count": 45,
    },
    {
        "name": "セレモ船橋駅北口ホール",
        "slug": "ceremo-funabashi-ekikitaguchi",
        "venue_type": "private_hall",
        "description": "セレモが運営する船橋駅至近の葬儀ホール。JR船橋駅北口から徒歩3分の好立地。家族葬に特化した温かみのある空間で、1日1組貸切対応。遠方からの参列者もアクセスしやすい立地が魅力です。",
        "address": "千葉県船橋市北本町1-3-11",
        "prefecture_slug": "chiba",
        "city_slug": "funabashi",
        "latitude": 35.7050,
        "longitude": 139.9860,
        "nearest_station": "JR総武線 船橋駅",
        "station_walk_minutes": 3,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}],
        "features": ["駅近", "家族葬専用", "1日1組貸切"],
        "operator_name": "株式会社セレモ",
        "rating_avg": 4.3,
        "review_count": 27,
    },
    # =============================================
    # ここからバッチ2に分割
    # =============================================
    {
        "name": "船橋メモリアルホール",
        "slug": "funabashi-memorial",
        "venue_type": "private_hall",
        "description": "船橋市の中心部に位置する大型葬儀会館。3つの式場を備え、家族葬から一般葬まで幅広く対応。最大100名収容可能なホールは社葬にも対応。充実した設備と経験豊富なスタッフが安心の葬儀をサポートします。",
        "address": "千葉県船橋市本町6-18-10",
        "prefecture_slug": "chiba",
        "city_slug": "funabashi",
        "latitude": 35.7010,
        "longitude": 139.9830,
        "nearest_station": "JR総武線 船橋駅",
        "station_walk_minutes": 8,
        "capacity_max": 100,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 128000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 288000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 418000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["大規模葬対応", "家族葬対応", "駐車場完備", "バリアフリー"],
        "operator_name": "船橋メモリアルサービス株式会社",
        "rating_avg": 4.1,
        "review_count": 33,
    },
    {
        "name": "家族葬のファミーユ船橋",
        "slug": "famillu-funabashi",
        "venue_type": "private_hall",
        "description": "ファミーユが運営する船橋の家族葬専用ホール。東武アーバンパークライン「塚田駅」から徒歩6分。少人数向けの温かみのある空間で、故人との最期の時間をゆっくりと過ごすことができます。",
        "address": "千葉県船橋市行田2-8-1",
        "prefecture_slug": "chiba",
        "city_slug": "funabashi",
        "latitude": 35.7200,
        "longitude": 139.9640,
        "nearest_station": "東武アーバンパークライン 塚田駅",
        "station_walk_minutes": 6,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}],
        "features": ["家族葬専用", "1日1組貸切", "駅近"],
        "operator_name": "株式会社家族葬のファミーユ",
        "rating_avg": 4.4,
        "review_count": 21,
    },
    {
        "name": "常光閣船橋",
        "slug": "jokokaku-funabashi",
        "venue_type": "temple_hall",
        "description": "日蓮宗寺院に併設された式場。船橋市の閑静な住宅地に位置し、伝統的な雰囲気の中で厳粛な葬儀が執り行えます。宗派を問わず利用可能で、駐車場も完備しています。",
        "address": "千葉県船橋市夏見台3-15-7",
        "prefecture_slug": "chiba",
        "city_slug": "funabashi",
        "latitude": 35.7150,
        "longitude": 139.9740,
        "nearest_station": "JR総武線 船橋駅",
        "station_walk_minutes": 15,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 18,
        "facilities": {"安置室": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 508000}],
        "features": ["寺院式場", "宗派不問", "駐車場完備"],
        "operator_name": "常光閣",
        "rating_avg": 3.9,
        "review_count": 14,
    },
    # =============================================
    # 3. 松戸市 (matsudo) — 4件
    # =============================================
    {
        "name": "松戸市斎場",
        "slug": "matsudo-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "松戸市が運営する公営の総合斎場。火葬場と式場を併設し、通夜から火葬まで一括して執り行えます。大式場56席・小式場30席を完備。松戸市民は火葬料無料。八柱霊園に隣接する静かな環境です。",
        "address": "千葉県松戸市串崎新田63-1",
        "prefecture_slug": "chiba",
        "city_slug": "matsudo",
        "latitude": 35.7930,
        "longitude": 139.9420,
        "nearest_station": "新京成線 五香駅",
        "station_walk_minutes": 25,
        "capacity_max": 56,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 80,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応"],
        "operator_name": "松戸市",
        "rating_avg": 4.0,
        "review_count": 42,
    },
    {
        "name": "セレモ松戸駅前ホール",
        "slug": "ceremo-matsudo-ekimae",
        "venue_type": "private_hall",
        "description": "セレモが運営する松戸駅前の家族葬対応ホール。JR常磐線「松戸駅」から徒歩5分。コンパクトながら充実した設備を備え、少人数でのお別れに最適。アクセスの良さから遠方の参列者にも好評です。",
        "address": "千葉県松戸市松戸1228-1",
        "prefecture_slug": "chiba",
        "city_slug": "matsudo",
        "latitude": 35.7840,
        "longitude": 139.9010,
        "nearest_station": "JR常磐線 松戸駅",
        "station_walk_minutes": 5,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}],
        "features": ["駅近", "家族葬対応", "1日1組貸切"],
        "operator_name": "株式会社セレモ",
        "rating_avg": 4.2,
        "review_count": 24,
    },
    {
        "name": "松戸中央メモリアルホール",
        "slug": "matsudo-chuo-memorial",
        "venue_type": "private_hall",
        "description": "松戸市中心部の大型葬儀会館。最大80名収容の式場を含む2つのホールを備え、家族葬から一般葬まで幅広く対応。新京成線「上本郷駅」から徒歩8分の好立地です。",
        "address": "千葉県松戸市上本郷3501",
        "prefecture_slug": "chiba",
        "city_slug": "matsudo",
        "latitude": 35.7930,
        "longitude": 139.9100,
        "nearest_station": "新京成線 上本郷駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 128000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 288000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 408000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 578000}],
        "features": ["大規模葬対応", "家族葬対応", "駐車場完備", "バリアフリー"],
        "operator_name": "松戸メモリアルサービス株式会社",
        "rating_avg": 4.1,
        "review_count": 26,
    },
    {
        "name": "善照寺式場",
        "slug": "zenshoji-shikijo-matsudo",
        "venue_type": "temple_hall",
        "description": "松戸市にある浄土真宗寺院の式場。歴史ある境内の落ち着いた雰囲気の中、心のこもったお別れができます。宗派を問わず利用可能。JR武蔵野線「東松戸駅」から徒歩10分。",
        "address": "千葉県松戸市紙敷588",
        "prefecture_slug": "chiba",
        "city_slug": "matsudo",
        "latitude": 35.7660,
        "longitude": 139.9310,
        "nearest_station": "JR武蔵野線 東松戸駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 488000}],
        "features": ["寺院式場", "宗派不問", "落ち着いた雰囲気"],
        "operator_name": "善照寺",
        "rating_avg": 4.0,
        "review_count": 11,
    },
    # =============================================
    # 4. 市川市 (ichikawa) — 4件
    # =============================================
    {
        "name": "市川市斎場",
        "slug": "ichikawa-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "市川市が運営する公営の総合斎場。市川市唯一の火葬場と葬儀式場が併設された施設です。JR武蔵野線「市川大野駅」からバス10分。市川市民は火葬料無料。式場は和室と洋室があり、ご希望に合わせて選べます。",
        "address": "千葉県市川市大野町4-2610-1",
        "prefecture_slug": "chiba",
        "city_slug": "ichikawa",
        "latitude": 35.7590,
        "longitude": 139.9330,
        "nearest_station": "JR武蔵野線 市川大野駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 60,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応"],
        "operator_name": "市川市",
        "rating_avg": 4.0,
        "review_count": 38,
    },
    # =============================================
    # ここからバッチ3に分割
    # =============================================
    {
        "name": "セレモ市川本八幡ホール",
        "slug": "ceremo-ichikawa-motoyawata",
        "venue_type": "private_hall",
        "description": "セレモが運営する本八幡駅至近の家族葬対応ホール。JR総武線「本八幡駅」から徒歩4分。東京都心からのアクセスも良好で、遠方からの参列者にも便利です。少人数でゆっくりとお別れできる空間が好評。",
        "address": "千葉県市川市南八幡4-2-12",
        "prefecture_slug": "chiba",
        "city_slug": "ichikawa",
        "latitude": 35.7210,
        "longitude": 139.9280,
        "nearest_station": "JR総武線 本八幡駅",
        "station_walk_minutes": 4,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}],
        "features": ["駅近", "家族葬対応", "東京からアクセス良好"],
        "operator_name": "株式会社セレモ",
        "rating_avg": 4.3,
        "review_count": 30,
    },
    {
        "name": "市川グランドホール",
        "slug": "ichikawa-grand-hall",
        "venue_type": "private_hall",
        "description": "市川市北部の大型葬儀会館。2つの式場を備え、家族葬から一般葬まで対応。広い駐車場と充実した設備で大人数の参列にも安心。閑静な住宅街に位置し、落ち着いた雰囲気の中でお別れができます。",
        "address": "千葉県市川市大野町2-1056",
        "prefecture_slug": "chiba",
        "city_slug": "ichikawa",
        "latitude": 35.7530,
        "longitude": 139.9380,
        "nearest_station": "JR武蔵野線 市川大野駅",
        "station_walk_minutes": 10,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 128000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 278000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 408000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 578000}],
        "features": ["大規模葬対応", "家族葬対応", "駐車場完備", "バリアフリー"],
        "operator_name": "市川グランドサービス株式会社",
        "rating_avg": 4.0,
        "review_count": 20,
    },
    {
        "name": "法華経寺式場",
        "slug": "hokekyoji-shikijo",
        "venue_type": "temple_hall",
        "description": "日蓮宗の大本山・法華経寺に隣接する式場。JR総武線「下総中山駅」から徒歩10分。歴史ある寺院の荘厳な雰囲気の中、格式高い葬儀が執り行えます。伝統的な仏式葬儀を希望される方に特におすすめです。",
        "address": "千葉県市川市中山2-10-1",
        "prefecture_slug": "chiba",
        "city_slug": "ichikawa",
        "latitude": 35.7270,
        "longitude": 139.9500,
        "nearest_station": "JR総武線 下総中山駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["寺院式場", "格式高い", "伝統的な仏式"],
        "operator_name": "法華経寺",
        "rating_avg": 4.1,
        "review_count": 15,
    },
    # =============================================
    # 5. 柏市 (kashiwa) — 4件
    # =============================================
    {
        "name": "ウイングホール柏斎場",
        "slug": "winghall-kashiwa-saijo",
        "venue_type": "public_crematorium",
        "description": "柏市・我孫子市・流山市が共同運営する公営の総合斎場。火葬場と式場を備え、通夜から火葬・法要まで一貫して執り行えます。関係市民は火葬料が減免。広い敷地と充実した設備が特長です。",
        "address": "千葉県柏市布施281-1",
        "prefecture_slug": "chiba",
        "city_slug": "kashiwa",
        "latitude": 35.8700,
        "longitude": 139.9560,
        "nearest_station": "JR常磐線 北柏駅",
        "station_walk_minutes": 30,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 100,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True, "法要室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "法要室完備", "家族葬対応"],
        "operator_name": "柏・我孫子・流山聖苑組合",
        "rating_avg": 4.1,
        "review_count": 52,
    },
    {
        "name": "セレモ柏旭町ホール",
        "slug": "ceremo-kashiwa-asahicho",
        "venue_type": "private_hall",
        "description": "セレモが運営する柏市の葬儀ホール。JR常磐線「柏駅」南口から徒歩8分。落ち着いた雰囲気のホールで家族葬に対応。柏駅からのアクセスが良好で、遠方からの参列にも便利です。",
        "address": "千葉県柏市旭町4-1-2",
        "prefecture_slug": "chiba",
        "city_slug": "kashiwa",
        "latitude": 35.8550,
        "longitude": 139.9660,
        "nearest_station": "JR常磐線 柏駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}],
        "features": ["駅近", "家族葬対応", "アクセス良好"],
        "operator_name": "株式会社セレモ",
        "rating_avg": 4.2,
        "review_count": 23,
    },
    {
        "name": "柏斎苑柏の葉家族葬ホール",
        "slug": "kashiwa-saien-kashiwanoha",
        "venue_type": "private_hall",
        "description": "柏の葉エリアに位置する家族葬専用ホール。つくばエクスプレス「柏の葉キャンパス駅」から車で5分。明るく開放的な空間で、少人数でゆっくりとお別れの時間を過ごせます。1日1組貸切の完全プライベート空間です。",
        "address": "千葉県柏市十余二380-61",
        "prefecture_slug": "chiba",
        "city_slug": "kashiwa",
        "latitude": 35.8810,
        "longitude": 139.9430,
        "nearest_station": "つくばエクスプレス 柏の葉キャンパス駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}],
        "features": ["家族葬専用", "1日1組貸切", "明るい空間"],
        "operator_name": "株式会社柏斎苑",
        "rating_avg": 4.4,
        "review_count": 18,
    },
    {
        "name": "博全社柏ホール",
        "slug": "hakuzensha-kashiwa",
        "venue_type": "private_hall",
        "description": "千葉の老舗葬儀社・博全社が運営する柏市の葬儀会館。2つの式場を備え、家族葬から一般葬まで幅広く対応。経験豊富なスタッフによる手厚いサポートが評判です。",
        "address": "千葉県柏市柏3-6-12",
        "prefecture_slug": "chiba",
        "city_slug": "kashiwa",
        "latitude": 35.8620,
        "longitude": 139.9720,
        "nearest_station": "JR常磐線 柏駅",
        "station_walk_minutes": 6,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 138000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 298000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 428000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000}],
        "features": ["老舗葬儀社", "家族葬対応", "駅近", "丁寧なサポート"],
        "operator_name": "株式会社博全社",
        "rating_avg": 4.2,
        "review_count": 29,
    },
    # =============================================
    # 6. 市原市 (ichihara) — 3件
    # =============================================
    {
        "name": "いちはら聖苑",
        "slug": "ichihara-seien",
        "venue_type": "public_crematorium",
        "description": "市原市が運営する公営の火葬場。市原市今富に位置し、自然に囲まれた静かな環境です。市原市民は火葬料が減免。待合室や安置室を完備し、火葬のみのご利用にも対応しています。",
        "address": "千葉県市原市今富1088-8",
        "prefecture_slug": "chiba",
        "city_slug": "ichihara",
        "latitude": 35.4780,
        "longitude": 140.1250,
        "nearest_station": "JR内房線 五井駅",
        "station_walk_minutes": 30,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 50,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "市原市",
        "rating_avg": 3.8,
        "review_count": 25,
    },
    {
        "name": "市原斎場",
        "slug": "ichihara-saijo",
        "venue_type": "private_hall",
        "description": "市原市能満に位置する葬儀会館。JR内房線「五井駅」からバスで15分。家族葬から一般葬まで対応可能な2つの式場を備えています。地域に根差した丁寧なサービスが評判です。",
        "address": "千葉県市原市能満1548",
        "prefecture_slug": "chiba",
        "city_slug": "ichihara",
        "latitude": 35.5110,
        "longitude": 140.1260,
        "nearest_station": "JR内房線 五井駅",
        "station_walk_minutes": 20,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["家族葬対応", "駐車場完備", "地域密着"],
        "operator_name": "市原斎場運営株式会社",
        "rating_avg": 4.0,
        "review_count": 18,
    },
    # =============================================
    # ここからバッチ4に分割
    # =============================================
    {
        "name": "セレモ市原五井駅ホール",
        "slug": "ceremo-ichihara-goi",
        "venue_type": "private_hall",
        "description": "セレモが運営する市原市の葬儀ホール。JR内房線「五井駅」から徒歩5分の好立地。家族葬に特化した温かみのあるホールで、少人数のお別れに最適です。",
        "address": "千葉県市原市五井中央東1-14-6",
        "prefecture_slug": "chiba",
        "city_slug": "ichihara",
        "latitude": 35.5190,
        "longitude": 140.0990,
        "nearest_station": "JR内房線 五井駅",
        "station_walk_minutes": 5,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}],
        "features": ["駅近", "家族葬対応", "1日1組貸切"],
        "operator_name": "株式会社セレモ",
        "rating_avg": 4.2,
        "review_count": 16,
    },
    # =============================================
    # 7. 八千代市 (yachiyo) — 2件
    # =============================================
    {
        "name": "八千代セレモニーホール",
        "slug": "yachiyo-ceremony-hall",
        "venue_type": "private_hall",
        "description": "八千代市の中心部に位置する葬儀会館。東葉高速鉄道「八千代中央駅」から徒歩10分。2つの式場を備え、家族葬から一般葬まで対応。火葬は四市複合事務組合の馬込斎場を利用します。",
        "address": "千葉県八千代市ゆりのき台3-5-2",
        "prefecture_slug": "chiba",
        "city_slug": "yachiyo",
        "latitude": 35.7320,
        "longitude": 140.0810,
        "nearest_station": "東葉高速鉄道 八千代中央駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 278000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 568000}],
        "features": ["家族葬対応", "駐車場完備", "バリアフリー"],
        "operator_name": "八千代セレモニーサービス株式会社",
        "rating_avg": 4.1,
        "review_count": 20,
    },
    {
        "name": "家族葬のファミーユ八千代",
        "slug": "famillu-yachiyo",
        "venue_type": "private_hall",
        "description": "ファミーユが運営する八千代市の家族葬専用ホール。京成本線「八千代台駅」から徒歩7分。1日1組貸切の完全プライベート空間で、少人数でゆっくりとお別れの時間を過ごせます。",
        "address": "千葉県八千代市八千代台北1-12-3",
        "prefecture_slug": "chiba",
        "city_slug": "yachiyo",
        "latitude": 35.7190,
        "longitude": 140.0750,
        "nearest_station": "京成本線 八千代台駅",
        "station_walk_minutes": 7,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}],
        "features": ["家族葬専用", "1日1組貸切", "駅近"],
        "operator_name": "株式会社家族葬のファミーユ",
        "rating_avg": 4.3,
        "review_count": 15,
    },
    # =============================================
    # 8. 習志野市 (narashino) — 2件
    # =============================================
    {
        "name": "しおかぜホール茜浜",
        "slug": "shiokaze-hall-akanehama",
        "venue_type": "public_crematorium",
        "description": "船橋市・習志野市・八千代市・鎌ケ谷市の四市複合事務組合が運営する公営の式場・火葬場。習志野市茜浜に位置し、式場と火葬場を併設。海沿いの立地で開放的な雰囲気。関係4市民は利用料が減免されます。",
        "address": "千葉県習志野市茜浜3-7-6",
        "prefecture_slug": "chiba",
        "city_slug": "narashino",
        "latitude": 35.6710,
        "longitude": 140.0260,
        "nearest_station": "JR京葉線 新習志野駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 80,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応"],
        "operator_name": "四市複合事務組合",
        "rating_avg": 4.0,
        "review_count": 32,
    },
    {
        "name": "習志野メモリアルホール",
        "slug": "narashino-memorial",
        "venue_type": "private_hall",
        "description": "習志野市の葬儀会館。JR総武線「津田沼駅」から徒歩10分。家族葬から一般葬まで対応可能な式場を備えています。津田沼駅からのアクセスも良く、東京方面からの参列者にも便利です。",
        "address": "千葉県習志野市谷津3-8-1",
        "prefecture_slug": "chiba",
        "city_slug": "narashino",
        "latitude": 35.6870,
        "longitude": 140.0110,
        "nearest_station": "JR総武線 津田沼駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 288000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 408000}],
        "features": ["駅近", "家族葬対応", "アクセス良好"],
        "operator_name": "習志野メモリアルサービス株式会社",
        "rating_avg": 4.1,
        "review_count": 17,
    },
    # =============================================
    # 9. 浦安市 (urayasu) — 2件
    # =============================================
    {
        "name": "浦安市斎場",
        "slug": "urayasu-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "浦安市が運営する公営の総合斎場。火葬場と式場を備え、通夜から火葬まで一貫して執り行えます。JR京葉線「舞浜駅」からバス15分。駐車場は乗用車100台・マイクロバス6台と充実。浦安市民は火葬料無料です。",
        "address": "千葉県浦安市千鳥15-3",
        "prefecture_slug": "chiba",
        "city_slug": "urayasu",
        "latitude": 35.6370,
        "longitude": 139.9330,
        "nearest_station": "JR京葉線 舞浜駅",
        "station_walk_minutes": 20,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 100,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True, "マイクロバス駐車": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応"],
        "operator_name": "浦安市",
        "rating_avg": 4.1,
        "review_count": 35,
    },
    {
        "name": "浦安フェアウェルホール",
        "slug": "urayasu-farewell-hall",
        "venue_type": "private_hall",
        "description": "浦安市の家族葬対応ホール。東京メトロ東西線「浦安駅」から徒歩8分。東京都心からのアクセスが抜群で、遠方からの参列者にも好評。明るく清潔感のある式場で、心のこもったお別れができます。",
        "address": "千葉県浦安市北栄1-16-5",
        "prefecture_slug": "chiba",
        "city_slug": "urayasu",
        "latitude": 35.6610,
        "longitude": 139.9050,
        "nearest_station": "東京メトロ東西線 浦安駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 128000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 408000}],
        "features": ["駅近", "家族葬対応", "東京からアクセス良好"],
        "operator_name": "浦安フェアウェルサービス株式会社",
        "rating_avg": 4.3,
        "review_count": 22,
    },
    # =============================================
    # 10. 流山市 (nagareyama) — 2件
    # =============================================
    {
        "name": "流山セレモニーホール",
        "slug": "nagareyama-ceremony-hall",
        "venue_type": "private_hall",
        "description": "流山市の葬儀会館。つくばエクスプレス「流山おおたかの森駅」から車で10分。2つの式場を備え、家族葬から一般葬まで対応。火葬はウイングホール柏斎場を利用。子育て世代が多いエリアならではの配慮ある対応が好評です。",
        "address": "千葉県流山市西初石3-98-29",
        "prefecture_slug": "chiba",
        "city_slug": "nagareyama",
        "latitude": 35.8670,
        "longitude": 139.9310,
        "nearest_station": "つくばエクスプレス 流山おおたかの森駅",
        "station_walk_minutes": 12,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 278000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 568000}],
        "features": ["家族葬対応", "駐車場完備", "バリアフリー"],
        "operator_name": "流山セレモニーサービス株式会社",
        "rating_avg": 4.1,
        "review_count": 19,
    },
    {
        "name": "家族葬のファミーユ流山",
        "slug": "famillu-nagareyama",
        "venue_type": "private_hall",
        "description": "ファミーユが運営する流山市の家族葬専用ホール。つくばエクスプレス「南流山駅」から徒歩8分。1日1組貸切のプライベート空間で、少人数のお別れに最適。JR武蔵野線との乗り換えもスムーズです。",
        "address": "千葉県流山市南流山2-26-8",
        "prefecture_slug": "chiba",
        "city_slug": "nagareyama",
        "latitude": 35.8400,
        "longitude": 139.8980,
        "nearest_station": "つくばエクスプレス 南流山駅",
        "station_walk_minutes": 8,
        "capacity_max": 25,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}],
        "features": ["家族葬専用", "1日1組貸切", "駅近"],
        "operator_name": "株式会社家族葬のファミーユ",
        "rating_avg": 4.4,
        "review_count": 14,
    },
    # =============================================
    # 11. 木更津市 (kisarazu) — 2件
    # =============================================
    {
        "name": "きみさらず聖苑",
        "slug": "kimisarazu-seien",
        "venue_type": "public_crematorium",
        "description": "木更津市・君津市・富津市・袖ケ浦市が共同運営する公営の火葬場。令和4年に供用開始された新しい施設で、火葬炉10基を備えています。お別れ室や霊安室、待合室を完備。関係市民は火葬料が減免されます。",
        "address": "千葉県木更津市大久保843-1",
        "prefecture_slug": "chiba",
        "city_slug": "kisarazu",
        "latitude": 35.3690,
        "longitude": 139.9670,
        "nearest_station": "JR内房線 木更津駅",
        "station_walk_minutes": 30,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 90,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "お別れ室": True, "マイクロバス駐車": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}],
        "features": ["火葬場併設", "公営斎場", "新しい施設", "駐車場完備"],
        "operator_name": "かずさ四市広域事務組合",
        "rating_avg": 4.2,
        "review_count": 28,
    },
    {
        "name": "かじま斎場芙蓉会館",
        "slug": "kajima-fuyo-kaikan",
        "venue_type": "private_hall",
        "description": "木更津市の老舗葬儀社が運営する葬儀会館。JR内房線「木更津駅」から徒歩14分の好立地。家族葬から一般葬まで対応可能な式場を備え、地域に根差した丁寧なサービスが特長です。",
        "address": "千葉県木更津市請西1-11-12",
        "prefecture_slug": "chiba",
        "city_slug": "kisarazu",
        "latitude": 35.3780,
        "longitude": 139.9510,
        "nearest_station": "JR内房線 木更津駅",
        "station_walk_minutes": 14,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["地域密着", "家族葬対応", "老舗葬儀社"],
        "operator_name": "株式会社かじま",
        "rating_avg": 4.0,
        "review_count": 16,
    },
    # =============================================
    # 12. 野田市 (noda) — 2件
    # =============================================
    {
        "name": "野田市斎場",
        "slug": "noda-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "野田市が運営する公営の総合斎場。火葬場と式場を併設し、大式場56席・小式場30席を完備。通夜から火葬まで一貫して執り行えます。駐車場は一般107台・バス3台と充実。野田市民は火葬料無料です。",
        "address": "千葉県野田市目吹7",
        "prefecture_slug": "chiba",
        "city_slug": "noda",
        "latitude": 35.9620,
        "longitude": 139.8750,
        "nearest_station": "東武アーバンパークライン 野田市駅",
        "station_walk_minutes": 15,
        "capacity_max": 56,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 107,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応"],
        "operator_name": "野田市",
        "rating_avg": 4.0,
        "review_count": 30,
    },
    {
        "name": "野田清風セレモニーホール",
        "slug": "noda-seifu-ceremony",
        "venue_type": "private_hall",
        "description": "野田市の家族葬対応ホール。東武アーバンパークライン「愛宕駅」から徒歩6分。少人数でゆっくりとお別れできるアットホームな空間。1日1組貸切で、プライベートなお別れが可能です。",
        "address": "千葉県野田市野田534-1",
        "prefecture_slug": "chiba",
        "city_slug": "noda",
        "latitude": 35.9570,
        "longitude": 139.8680,
        "nearest_station": "東武アーバンパークライン 愛宕駅",
        "station_walk_minutes": 6,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}],
        "features": ["家族葬対応", "1日1組貸切", "駅近", "アットホーム"],
        "operator_name": "清風セレモニー株式会社",
        "rating_avg": 4.2,
        "review_count": 13,
    },
]


def post_batch(batch, batch_num):
    """10件ずつバッチでPOSTする"""
    data = json.dumps(batch, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(
        SUPABASE_URL,
        data=data,
        headers=HEADERS,
        method="POST",
    )
    try:
        with urllib.request.urlopen(req) as resp:
            status = resp.getcode()
            print(f"  バッチ {batch_num}: {status} OK ({len(batch)}件)")
            return True
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8")
        print(f"  バッチ {batch_num}: エラー {e.code}")
        print(f"  レスポンス: {body}")
        return False


def count_venues():
    """千葉県のvenue件数を取得"""
    url = SUPABASE_URL + "?prefecture_slug=eq.chiba&select=id"
    req = urllib.request.Request(url, headers={
        "apikey": API_KEY,
        "Authorization": f"Bearer {API_KEY}",
        "Prefer": "count=exact",
    })
    try:
        with urllib.request.urlopen(req) as resp:
            # content-rangeヘッダから件数を取得
            content_range = resp.headers.get("content-range", "")
            print(f"  Content-Range: {content_range}")
            body = resp.read().decode("utf-8")
            items = json.loads(body)
            return len(items)
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8")
        print(f"  カウントエラー: {e.code} - {body}")
        return -1


def main():
    print(f"=== 千葉県 斎場データ投入 ===")
    print(f"合計: {len(venues)} 件")
    print()

    # 10件ずつバッチに分割
    batch_size = 10
    batches = [venues[i:i + batch_size] for i in range(0, len(venues), batch_size)]
    print(f"バッチ数: {len(batches)}")
    print()

    success_count = 0
    for i, batch in enumerate(batches, 1):
        ok = post_batch(batch, i)
        if ok:
            success_count += len(batch)
        time.sleep(0.5)  # API制限対策

    print()
    print(f"投入完了: {success_count}/{len(venues)} 件")
    print()

    # 件数確認
    print("=== 千葉県venue件数確認 ===")
    count = count_venues()
    if count >= 0:
        print(f"  千葉県のvenue件数: {count} 件")


if __name__ == "__main__":
    main()
