# -*- coding: utf-8 -*-
import json, subprocess, time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

# 京都府 バッチ3: 伏見区追加・山科区・西京区・宇治市 (25件)
kyoto_batch3 = [
    # === 京都市伏見区 追加5件 ===
    {"name":"洛王セレモニー伏見桃山","slug":"kyoto-rakuo-fushimi-momoyama","venue_type":"private_hall","description":"伏見桃山城跡近くの洛王セレモニー。歴史ある桃山エリアで、落ち着いた雰囲気の中でお別れを行えます。","address":"京都府京都市伏見区桃山町松平武蔵23","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.940,"longitude":135.775,"nearest_station":"JR奈良線 桃山駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":365000},{"type":"ippanso","label":"一般葬プラン","priceFrom":660000}],"features":["家族葬対応","駅近"],"operator_name":"洛王セレモニー","rating_avg":4.0,"review_count":22},
    {"name":"ベルコ淀シティホール","slug":"kyoto-bellco-yodo","venue_type":"private_hall","description":"伏見区淀エリアのベルコ葬儀会館。京阪淀駅から徒歩圏内で、京都競馬場近くの便利な立地です。","address":"京都府京都市伏見区淀池上町173","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.904,"longitude":135.728,"nearest_station":"京阪本線 淀駅","station_walk_minutes":7,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":98000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":355000}],"features":["家族葬対応","駅近"],"operator_name":"ベルコ","rating_avg":4.1,"review_count":20},
    {"name":"公益社 竹田ホール","slug":"kyoto-koekisha-takeda","venue_type":"private_hall","description":"伏見区竹田エリアの公益社ホール。近鉄竹田駅近くで地下鉄烏丸線も利用可能。南京都エリアの拠点斎場です。","address":"京都府京都市伏見区竹田西桶ノ井町43","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.958,"longitude":135.755,"nearest_station":"近鉄京都線 竹田駅","station_walk_minutes":5,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":105000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":385000},{"type":"ippanso","label":"一般葬プラン","priceFrom":700000}],"features":["家族葬対応","駅近","2路線利用可"],"operator_name":"公益社","rating_avg":4.2,"review_count":35},
    {"name":"家族葬のファミーユ向島","slug":"kyoto-famillu-mukaijima","venue_type":"private_hall","description":"伏見区向島エリアの家族葬専門ホール。宇治川沿いの静かな環境で、少人数のお見送りに最適です。","address":"京都府京都市伏見区向島二ノ丸町151-25","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.916,"longitude":135.779,"nearest_station":"近鉄京都線 向島駅","station_walk_minutes":8,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":89000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":298000}],"features":["家族葬対応","少人数対応","低価格"],"operator_name":"家族葬のファミーユ","rating_avg":4.3,"review_count":14},
    {"name":"醍醐寺会館","slug":"kyoto-daigoji-kaikan","venue_type":"temple_hall","description":"世界遺産・醍醐寺に併設された式場。真言宗醍醐派の総本山で、桜の名所としても知られる境内で厳かな葬儀を執り行えます。","address":"京都府京都市伏見区醍醐東大路町22","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.951,"longitude":135.822,"nearest_station":"京都市営地下鉄東西線 醍醐駅","station_walk_minutes":10,"capacity_max":50,"hall_count":1,"has_crematorium":False,"parking_count":10,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"本堂":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":420000},{"type":"ippanso","label":"一般葬プラン","priceFrom":750000}],"features":["寺院式場","仏式葬儀","世界遺産"],"operator_name":"醍醐寺","rating_avg":4.0,"review_count":12},
    # === 京都市山科区 5件 ===
    {"name":"公益社 山科ホール","slug":"kyoto-koekisha-yamashina","venue_type":"private_hall","description":"山科駅近くに位置する公益社のホール。JR・地下鉄・京阪の3路線利用可能で、アクセス抜群の立地です。","address":"京都府京都市山科区竹鼻竹ノ街道町56","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.976,"longitude":135.813,"nearest_station":"JR東海道本線 山科駅","station_walk_minutes":5,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":108000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":385000},{"type":"ippanso","label":"一般葬プラン","priceFrom":700000}],"features":["家族葬対応","駅近","3路線利用可"],"operator_name":"公益社","rating_avg":4.2,"review_count":38},
    {"name":"ベルコ山科シティホール","slug":"kyoto-bellco-yamashina","venue_type":"private_hall","description":"山科区東野エリアのベルコ葬儀会館。外環状線沿いでお車でのアクセスが便利です。","address":"京都府京都市山科区東野門口町12-5","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.973,"longitude":135.822,"nearest_station":"京都市営地下鉄東西線 東野駅","station_walk_minutes":5,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":98000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":358000}],"features":["家族葬対応","駅近"],"operator_name":"ベルコ","rating_avg":4.1,"review_count":25},
    {"name":"洛王セレモニー山科","slug":"kyoto-rakuo-yamashina","venue_type":"private_hall","description":"山科区椥辻エリアの洛王セレモニー。地下鉄東西線椥辻駅から近く、通勤途中のお参りにも便利な立地です。","address":"京都府京都市山科区椥辻草海道町38-1","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.969,"longitude":135.826,"nearest_station":"京都市営地下鉄東西線 椥辻駅","station_walk_minutes":5,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":370000},{"type":"ippanso","label":"一般葬プラン","priceFrom":670000}],"features":["家族葬対応","駅近"],"operator_name":"洛王セレモニー","rating_avg":4.0,"review_count":22},
    {"name":"家族葬のファミーユ山科","slug":"kyoto-famillu-yamashina","venue_type":"private_hall","description":"山科区の家族葬専門ホール。小野エリアの閑静な住宅街に位置し、少人数での温かいお別れに最適です。","address":"京都府京都市山科区小野弓田町3","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.960,"longitude":135.830,"nearest_station":"京都市営地下鉄東西線 小野駅","station_walk_minutes":5,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":89000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":298000}],"features":["家族葬対応","少人数対応","低価格","駅近"],"operator_name":"家族葬のファミーユ","rating_avg":4.4,"review_count":16},
    {"name":"五条会館 山科","slug":"kyoto-gojo-yamashina","venue_type":"private_hall","description":"山科区大宅エリアの五条会館。名神高速山科インター近くでお車でのアクセスが便利。広い駐車場を完備しています。","address":"京都府京都市山科区大宅細田町66","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.964,"longitude":135.835,"nearest_station":"京都市営地下鉄東西線 椥辻駅","station_walk_minutes":12,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":100000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":375000},{"type":"ippanso","label":"一般葬プラン","priceFrom":680000}],"features":["家族葬対応","大駐車場","インター近く"],"operator_name":"五条会館","rating_avg":4.0,"review_count":28},
    # === 京都市西京区 5件 ===
    {"name":"公益社 桂ホール","slug":"kyoto-koekisha-katsura","venue_type":"private_hall","description":"桂駅近くに位置する公益社のホール。阪急京都線の拠点駅から徒歩圏内で、西京区・向日市方面からのアクセスに便利です。","address":"京都府京都市西京区桂南巽町90","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.985,"longitude":135.710,"nearest_station":"阪急京都線 桂駅","station_walk_minutes":7,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":108000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":388000},{"type":"ippanso","label":"一般葬プラン","priceFrom":700000}],"features":["家族葬対応","駅近"],"operator_name":"公益社","rating_avg":4.2,"review_count":35},
    {"name":"ベルコ洛西シティホール","slug":"kyoto-bellco-rakusai","venue_type":"private_hall","description":"洛西ニュータウン近くのベルコ葬儀会館。新興住宅地に位置し、広い駐車場を完備しています。","address":"京都府京都市西京区大枝沓掛町26-380","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.972,"longitude":135.679,"nearest_station":"阪急京都線 洛西口駅","station_walk_minutes":15,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":98000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":355000}],"features":["家族葬対応","大駐車場"],"operator_name":"ベルコ","rating_avg":4.1,"review_count":22},
    {"name":"洛王セレモニー桂","slug":"kyoto-rakuo-katsura","venue_type":"private_hall","description":"桂川エリアの洛王セレモニー。桂離宮にほど近い風情ある立地で、京都らしいお別れの場を提供しています。","address":"京都府京都市西京区桂畑ケ田町88","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.981,"longitude":135.705,"nearest_station":"阪急京都線 桂駅","station_walk_minutes":10,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":12,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":368000},{"type":"ippanso","label":"一般葬プラン","priceFrom":660000}],"features":["家族葬対応","駅近"],"operator_name":"洛王セレモニー","rating_avg":4.0,"review_count":20},
    {"name":"家族葬のファミーユ西京","slug":"kyoto-famillu-nishikyo","venue_type":"private_hall","description":"西京区の家族葬専門ホール。松尾エリアの閑静な住宅街に位置し、少人数のお見送りに特化しています。","address":"京都府京都市西京区嵐山朝月町3","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.998,"longitude":135.693,"nearest_station":"阪急嵐山線 松尾大社駅","station_walk_minutes":5,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":89000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":298000}],"features":["家族葬対応","少人数対応","低価格","駅近"],"operator_name":"家族葬のファミーユ","rating_avg":4.3,"review_count":15},
    {"name":"五条会館 桂川","slug":"kyoto-gojo-katsuragawa","venue_type":"private_hall","description":"JR桂川駅近くの五条会館。イオンモール京都桂川にも近い便利な立地で、向日市・長岡京市からもアクセスしやすい式場です。","address":"京都府京都市西京区牛ケ瀬奥ノ防町24","prefecture_slug":"kyoto","city_slug":"kyoto-city","latitude":34.963,"longitude":135.718,"nearest_station":"JR東海道本線 桂川駅","station_walk_minutes":8,"capacity_max":70,"hall_count":2,"has_crematorium":False,"parking_count":20,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":100000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":378000},{"type":"ippanso","label":"一般葬プラン","priceFrom":680000}],"features":["家族葬対応","駅近","大駐車場"],"operator_name":"五条会館","rating_avg":4.1,"review_count":25},
    # === 宇治市 8件 ===
    {"name":"公益社 宇治ホール","slug":"kyoto-koekisha-uji","venue_type":"private_hall","description":"宇治市の中心部に位置する公益社のホール。世界遺産・平等院のある宇治エリアの中核斎場として多くの方に利用されています。","address":"京都府宇治市宇治妙楽156","prefecture_slug":"kyoto","city_slug":"uji","latitude":34.889,"longitude":135.808,"nearest_station":"JR奈良線 宇治駅","station_walk_minutes":8,"capacity_max":80,"hall_count":2,"has_crematorium":False,"parking_count":25,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":105000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":380000},{"type":"ippanso","label":"一般葬プラン","priceFrom":690000}],"features":["家族葬対応","駅近"],"operator_name":"公益社","rating_avg":4.1,"review_count":35},
    {"name":"ベルコ宇治シティホール","slug":"kyoto-bellco-uji","venue_type":"private_hall","description":"宇治市大久保エリアのベルコ葬儀会館。近鉄大久保駅から徒歩圏内で、城陽市方面からのアクセスも便利です。","address":"京都府宇治市大久保町田中18","prefecture_slug":"kyoto","city_slug":"uji","latitude":34.875,"longitude":135.785,"nearest_station":"近鉄京都線 大久保駅","station_walk_minutes":8,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":18,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":98000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":358000}],"features":["家族葬対応","駅近"],"operator_name":"ベルコ","rating_avg":4.2,"review_count":28},
    {"name":"洛王セレモニー宇治","slug":"kyoto-rakuo-uji","venue_type":"private_hall","description":"宇治市小倉エリアの洛王セレモニー。小倉駅近くの便利な立地で、温かみのある式場です。","address":"京都府宇治市小倉町南浦30","prefecture_slug":"kyoto","city_slug":"uji","latitude":34.882,"longitude":135.790,"nearest_station":"近鉄京都線 小倉駅","station_walk_minutes":5,"capacity_max":60,"hall_count":1,"has_crematorium":False,"parking_count":15,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"安置室":True},"price_plans":[{"type":"kazokuso","label":"家族葬プラン","priceFrom":365000},{"type":"ippanso","label":"一般葬プラン","priceFrom":660000}],"features":["家族葬対応","駅近"],"operator_name":"洛王セレモニー","rating_avg":4.0,"review_count":22},
    {"name":"家族葬のファミーユ宇治","slug":"kyoto-famillu-uji","venue_type":"private_hall","description":"宇治市の家族葬専門ホール。宇治茶の名産地で知られるエリアに位置し、少人数のお見送りに最適です。","address":"京都府宇治市五ケ庄三番割36","prefecture_slug":"kyoto","city_slug":"uji","latitude":34.903,"longitude":135.802,"nearest_station":"JR奈良線 黄檗駅","station_walk_minutes":5,"capacity_max":30,"hall_count":1,"has_crematorium":False,"parking_count":8,"facilities":{"式場":True,"親族控室":True,"駐車場":True,"バリアフリー":True,"安置室":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":89000},{"type":"kazokuso","label":"家族葬プラン","priceFrom":298000}],"features":["家族葬対応","少人数対応","低価格","駅近"],"operator_name":"家族葬のファミーユ","rating_avg":4.4,"review_count":16},
    {"name":"宇治市斎場","slug":"kyoto-uji-saijo","venue_type":"public_crematorium","description":"宇治市が運営する公営斎場。天ケ瀬ダム近くの自然豊かな環境に位置し、市民料金で火葬・告別式が行えます。","address":"京都府宇治市宇治金井戸7-52","prefecture_slug":"kyoto","city_slug":"uji","latitude":34.894,"longitude":135.832,"nearest_station":"JR奈良線 宇治駅","station_walk_minutes":20,"capacity_max":80,"hall_count":2,"has_crematorium":True,"parking_count":40,"facilities":{"式場":True,"親族控室":True,"お清め所":True,"駐車場":True,"バリアフリー":True,"火葬場":True},"price_plans":[{"type":"kasoshiki","label":"火葬式プラン","priceFrom":65000}],"features":["公営施設","火葬場併設","大駐車場"],"operator_name":"宇治市","rating_avg":3.7,"review_count":40},
]

for i in range(0, len(kyoto_batch3), 10):
    batch = kyoto_batch3[i:i+10]
    code = insert_batch(batch)
    print(f"バッチ {i//10+1}: {code} ({len(batch)}件)")
    time.sleep(1)

print(f"\n完了: 合計 {len(kyoto_batch3)} 件")
