#!/usr/bin/env python3
"""
岩手県の斎場データをSupabase REST APIに投入するスクリプト
50件を10件ずつバッチでPOSTする
"""

import json
import subprocess
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

# 岩手県の全斎場データ（50件）
venues = [
    # =============================================
    # 盛岡市 (morioka) — 15件
    # =============================================
    {
        "name": "盛岡市斎場やすらぎの丘",
        "slug": "iwate-morioka-yasuragi-no-oka",
        "venue_type": "public_crematorium",
        "description": "盛岡市が運営する公営斎場で、三ツ割寺山に位置します。火葬棟と式場を同一敷地内に備え、通夜から火葬まで一貫して執り行えます。上盛岡駅から徒歩約11分。盛岡市民は火葬料無料で利用でき、広い駐車場も完備しています。",
        "address": "岩手県盛岡市三ツ割字寺山46-4",
        "prefecture_slug": "iwate",
        "city_slug": "morioka",
        "latitude": 39.7280,
        "longitude": 141.1490,
        "nearest_station": "JR山田線 上盛岡駅",
        "station_walk_minutes": 11,
        "capacity_max": 100,
        "hall_count": 3,
        "has_crematorium": True,
        "parking_count": 80,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応", "バリアフリー"],
        "operator_name": "盛岡市（指定管理：株式会社不来方やすらぎの丘）",
        "rating_avg": 4.0,
        "review_count": 28,
    },
    {
        "name": "北山浄光会館",
        "slug": "iwate-kitayama-joko-kaikan",
        "venue_type": "private_hall",
        "description": "盛岡市北山に位置する民営の葬儀会館。霊安室・安置施設を完備し、家族葬から一般葬まで幅広く対応します。上盛岡駅より車4分の好アクセス。北山の閑静な環境で故人を偲ぶことができます。",
        "address": "岩手県盛岡市北山2-2-40",
        "prefecture_slug": "iwate",
        "city_slug": "morioka",
        "latitude": 39.7230,
        "longitude": 141.1380,
        "nearest_station": "JR山田線 上盛岡駅",
        "station_walk_minutes": 15,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"霊安室": True, "安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["安置施設あり", "家族葬対応", "駐車場完備", "バリアフリー"],
        "operator_name": "北山浄光会館",
        "rating_avg": 4.2,
        "review_count": 22,
    },
    {
        "name": "浄光の間",
        "slug": "iwate-joko-no-ma",
        "venue_type": "private_hall",
        "description": "盛岡市内の民営葬儀式場。小規模の家族葬から中規模の葬儀まで対応する、アットホームな雰囲気の式場です。安置施設を備え、故人を身近に感じながらお別れの時間を過ごせます。",
        "address": "岩手県盛岡市本宮5-3-12",
        "prefecture_slug": "iwate",
        "city_slug": "morioka",
        "latitude": 39.6920,
        "longitude": 141.1280,
        "nearest_station": "JR東北本線 仙北町駅",
        "station_walk_minutes": 18,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}],
        "features": ["安置施設あり", "少人数葬対応", "家族葬対応", "駐車場完備"],
        "operator_name": "浄光の間",
        "rating_avg": 4.1,
        "review_count": 15,
    },
    {
        "name": "メモリアルホールもりおか長安殿",
        "slug": "iwate-morioka-choan-den",
        "venue_type": "private_hall",
        "description": "さがみ典礼が運営する盛岡市愛宕町の大型葬儀会館。盛岡駅より車15分。大規模な一般葬から少人数の家族葬まで幅広く対応。ファミラルもりおかとしても知られ、充実した設備と経験豊富なスタッフが丁寧にサポートします。",
        "address": "岩手県盛岡市愛宕町7-8",
        "prefecture_slug": "iwate",
        "city_slug": "morioka",
        "latitude": 39.7050,
        "longitude": 141.1520,
        "nearest_station": "JR東北新幹線 盛岡駅",
        "station_walk_minutes": 25,
        "capacity_max": 150,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 60,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["大規模葬対応", "家族葬対応", "宿泊可能", "駐車場完備", "バリアフリー"],
        "operator_name": "株式会社アルファクラブ東北（さがみ典礼）",
        "rating_avg": 4.3,
        "review_count": 25,
    },
    {
        "name": "家族葬のファミラル都南",
        "slug": "iwate-familal-tonan",
        "venue_type": "private_hall",
        "description": "盛岡市都南地区にある家族葬専用ホール。少人数でのアットホームな葬儀に特化し、1日1組限定で利用できます。安置施設完備で、故人と最後の時間をゆっくり過ごせる温かみのある空間です。",
        "address": "岩手県盛岡市津志田南2-15-30",
        "prefecture_slug": "iwate",
        "city_slug": "morioka",
        "latitude": 39.6750,
        "longitude": 141.1400,
        "nearest_station": "JR東北本線 岩手飯岡駅",
        "station_walk_minutes": 12,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬専用", "1日1組限定", "安置施設あり", "少人数葬対応"],
        "operator_name": "株式会社アルファクラブ東北",
        "rating_avg": 4.4,
        "review_count": 18,
    },
    {
        "name": "家族葬のファミラル中屋敷",
        "slug": "iwate-familal-nakayashiki",
        "venue_type": "private_hall",
        "description": "盛岡市中屋敷にある家族葬専用ホール。1日1組貸切で、少人数の家族葬に最適な空間を提供。安置施設を完備し、通夜から葬儀まで同じ場所で執り行えます。落ち着いた住宅街に位置し、静かな環境です。",
        "address": "岩手県盛岡市中屋敷町3-18",
        "prefecture_slug": "iwate",
        "city_slug": "morioka",
        "latitude": 39.7150,
        "longitude": 141.1250,
        "nearest_station": "JR東北本線 盛岡駅",
        "station_walk_minutes": 20,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬専用", "1日1組限定", "安置施設あり", "少人数葬対応"],
        "operator_name": "株式会社アルファクラブ東北",
        "rating_avg": 4.3,
        "review_count": 14,
    },
    {
        "name": "家族葬のファミラル三ツ割",
        "slug": "iwate-familal-mitsuwari",
        "venue_type": "private_hall",
        "description": "盛岡市三ツ割にある家族葬専用ホール。やすらぎの丘に近く、火葬場へのアクセスも良好。1日1組限定の貸切空間で、故人との最後の時間を大切にできます。安置施設も完備しています。",
        "address": "岩手県盛岡市三ツ割2-8-15",
        "prefecture_slug": "iwate",
        "city_slug": "morioka",
        "latitude": 39.7260,
        "longitude": 141.1530,
        "nearest_station": "JR山田線 上盛岡駅",
        "station_walk_minutes": 14,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬専用", "1日1組限定", "安置施設あり", "火葬場近い"],
        "operator_name": "株式会社アルファクラブ東北",
        "rating_avg": 4.2,
        "review_count": 12,
    },
    {
        "name": "仙北長安殿（ファミラル仙北）",
        "slug": "iwate-senboku-choan-den",
        "venue_type": "private_hall",
        "description": "さがみ典礼が運営する盛岡市仙北地区の葬儀会館。中規模の一般葬から家族葬まで対応。仙北町駅から車5分の好アクセスで、充実した設備と温かなおもてなしで故人を見送ります。",
        "address": "岩手県盛岡市仙北2-24-5",
        "prefecture_slug": "iwate",
        "city_slug": "morioka",
        "latitude": 39.6880,
        "longitude": 141.1450,
        "nearest_station": "JR東北本線 仙北町駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["家族葬対応", "一般葬対応", "宿泊可能", "駐車場完備", "バリアフリー"],
        "operator_name": "株式会社アルファクラブ東北（さがみ典礼）",
        "rating_avg": 4.1,
        "review_count": 20,
    },
    {
        "name": "盛岡西典礼会館",
        "slug": "iwate-morioka-nishi-tenrei",
        "venue_type": "private_hall",
        "description": "盛岡市西部に位置する典礼会館。家族葬から一般葬まで対応し、広い駐車場を完備。盛岡西バイパス沿いの好立地で、車でのアクセスが便利です。経験豊富なスタッフが心を込めてお手伝いします。",
        "address": "岩手県盛岡市西仙北1-18-50",
        "prefecture_slug": "iwate",
        "city_slug": "morioka",
        "latitude": 39.6950,
        "longitude": 141.1100,
        "nearest_station": "JR東北本線 仙北町駅",
        "station_walk_minutes": 25,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 265000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 568000}],
        "features": ["家族葬対応", "一般葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "盛岡西典礼会館",
        "rating_avg": 4.0,
        "review_count": 16,
    },
    {
        "name": "セリオホールみたけ",
        "slug": "iwate-serio-mitake",
        "venue_type": "private_hall",
        "description": "いわて生協が運営するみたけ地区の葬儀ホール。組合員価格で利用でき、家族葬から一般葬まで対応。地域に根差したサービスで、安心の料金体系が魅力です。バリアフリー設計で高齢者も安心。",
        "address": "岩手県盛岡市みたけ3-38-38",
        "prefecture_slug": "iwate",
        "city_slug": "morioka",
        "latitude": 39.7350,
        "longitude": 141.1200,
        "nearest_station": "JR田沢湖線 大釜駅",
        "station_walk_minutes": 30,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["生協運営", "家族葬対応", "組合員割引", "バリアフリー"],
        "operator_name": "いわて生協",
        "rating_avg": 4.1,
        "review_count": 19,
    },
    {
        "name": "いわて生協セリオホール中野",
        "slug": "iwate-serio-nakano",
        "venue_type": "private_hall",
        "description": "いわて生協が運営する中野地区の葬儀ホール。組合員価格で利用でき、家族葬に適した落ち着いた空間。盛岡市中野地区の閑静な住宅街に位置し、アットホームな雰囲気で故人を見送れます。",
        "address": "岩手県盛岡市中野1-20-7",
        "prefecture_slug": "iwate",
        "city_slug": "morioka",
        "latitude": 39.7180,
        "longitude": 141.1650,
        "nearest_station": "JR山田線 上盛岡駅",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["生協運営", "家族葬対応", "組合員割引", "少人数葬対応"],
        "operator_name": "いわて生協",
        "rating_avg": 4.0,
        "review_count": 13,
    },
    {
        "name": "駒木葬祭セレモニーホール",
        "slug": "iwate-komaki-ceremony-hall",
        "venue_type": "private_hall",
        "description": "盛岡市の老舗葬儀社・駒木葬祭が運営するセレモニーホール。地元密着の丁寧なサービスで、盛岡市民から厚い信頼を得ています。家族葬から一般葬まで柔軟に対応し、心温まるお別れの場を提供します。",
        "address": "岩手県盛岡市大通3-6-12",
        "prefecture_slug": "iwate",
        "city_slug": "morioka",
        "latitude": 39.7020,
        "longitude": 141.1340,
        "nearest_station": "JR東北新幹線 盛岡駅",
        "station_walk_minutes": 10,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["老舗葬儀社", "家族葬対応", "駅近", "宿泊可能", "駐車場完備"],
        "operator_name": "株式会社駒木葬祭",
        "rating_avg": 4.2,
        "review_count": 24,
    },
    {
        "name": "サンセルモ玉泉院盛岡会館",
        "slug": "iwate-sunselmo-morioka",
        "venue_type": "private_hall",
        "description": "全国展開のサンセルモ玉泉院が盛岡で運営する葬儀会館。大規模な一般葬から家族葬まで、豊富な経験とノウハウで対応。充実した設備と落ち着いた空間で、故人にふさわしいお別れの場を提供します。",
        "address": "岩手県盛岡市上田1-12-18",
        "prefecture_slug": "iwate",
        "city_slug": "morioka",
        "latitude": 39.7120,
        "longitude": 141.1320,
        "nearest_station": "JR東北新幹線 盛岡駅",
        "station_walk_minutes": 15,
        "capacity_max": 120,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 115000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 278000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 408000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000}],
        "features": ["大規模葬対応", "家族葬対応", "宿泊可能", "駐車場完備", "バリアフリー"],
        "operator_name": "株式会社サンセルモ",
        "rating_avg": 4.1,
        "review_count": 17,
    },
    {
        "name": "永遠の杜盛岡ホール",
        "slug": "iwate-towa-no-mori-morioka",
        "venue_type": "private_hall",
        "description": "盛岡市南部に位置する家族葬対応のセレモニーホール。自然に囲まれた落ち着いた環境で、故人との最後の時間をゆっくりと過ごせます。小規模から中規模の葬儀に最適な広さの式場を備えています。",
        "address": "岩手県盛岡市永井12-5-8",
        "prefecture_slug": "iwate",
        "city_slug": "morioka",
        "latitude": 39.6680,
        "longitude": 141.1350,
        "nearest_station": "JR東北本線 岩手飯岡駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["家族葬対応", "自然環境", "駐車場完備", "バリアフリー"],
        "operator_name": "永遠の杜",
        "rating_avg": 4.0,
        "review_count": 11,
    },
    {
        "name": "やすらぎホール盛岡",
        "slug": "iwate-yasuragi-hall-morioka",
        "venue_type": "private_hall",
        "description": "盛岡市内の葬儀ホール。家族葬から一般葬まで幅広く対応し、経験豊富なスタッフが心のこもったサポートを提供。バリアフリー設計で高齢の参列者にも配慮した施設です。",
        "address": "岩手県盛岡市月が丘2-3-15",
        "prefecture_slug": "iwate",
        "city_slug": "morioka",
        "latitude": 39.7400,
        "longitude": 141.1150,
        "nearest_station": "IGRいわて銀河鉄道 厨川駅",
        "station_walk_minutes": 12,
        "capacity_max": 70,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000}],
        "features": ["家族葬対応", "一般葬対応", "駐車場完備", "バリアフリー"],
        "operator_name": "やすらぎホール盛岡",
        "rating_avg": 3.9,
        "review_count": 10,
    },

    # =============================================
    # 一関市 (ichinoseki) — 6件
    # =============================================
    {
        "name": "一関市舞川斎場",
        "slug": "iwate-ichinoseki-maikawa-saijo",
        "venue_type": "public_crematorium",
        "description": "一関市が運営する公営の火葬場。舞川地区に位置し、一関市民の火葬を担っています。静かな環境の中で故人を見送ることができ、駐車場も完備。一関市民は低料金で利用できます。",
        "address": "岩手県一関市舞川字向山1-10",
        "prefecture_slug": "iwate",
        "city_slug": "ichinoseki",
        "latitude": 38.9100,
        "longitude": 141.1200,
        "nearest_station": "JR東北本線 一ノ関駅",
        "station_walk_minutes": 30,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 40,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応"],
        "operator_name": "一関市",
        "rating_avg": 3.8,
        "review_count": 15,
    },
    {
        "name": "一関長安殿",
        "slug": "iwate-ichinoseki-choan-den",
        "venue_type": "private_hall",
        "description": "さがみ典礼が運営する一関市の葬儀会館。JR一ノ関駅から車で5分、東北自動車道一関ICより車で10分の好アクセス。浴室付きのお部屋で仮眠もとることができ、通夜から葬儀まで快適に過ごせます。",
        "address": "岩手県一関市山目字中野62-1",
        "prefecture_slug": "iwate",
        "city_slug": "ichinoseki",
        "latitude": 38.9250,
        "longitude": 141.1080,
        "nearest_station": "JR東北新幹線 一ノ関駅",
        "station_walk_minutes": 20,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "浴室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["宿泊可能", "浴室完備", "家族葬対応", "駐車場完備", "バリアフリー"],
        "operator_name": "株式会社アルファクラブ東北（さがみ典礼）",
        "rating_avg": 4.2,
        "review_count": 20,
    },
    {
        "name": "セレモニーゆずり葉一関",
        "slug": "iwate-yuzuriha-ichinoseki",
        "venue_type": "private_hall",
        "description": "一関市花泉町にある葬儀ホール。地域に密着したサービスで、家族葬から一般葬まで幅広く対応。自然に囲まれた静かな環境で、心安らぐお別れの場を提供します。",
        "address": "岩手県一関市花泉町涌津字二ノ町53",
        "prefecture_slug": "iwate",
        "city_slug": "ichinoseki",
        "latitude": 38.8750,
        "longitude": 141.1550,
        "nearest_station": "JR東北本線 花泉駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["家族葬対応", "一般葬対応", "駐車場完備", "地域密着"],
        "operator_name": "セレモニーゆずり葉",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "家族葬ホール禮賓館一関",
        "slug": "iwate-reibinkan-ichinoseki",
        "venue_type": "private_hall",
        "description": "一関市花泉町にある家族葬専門ホール。少人数でのアットホームな葬儀に特化し、故人と家族の大切な時間を守ります。丁寧なサポートと温かい空間が特徴の式場です。",
        "address": "岩手県一関市花泉町涌津一ノ町58-2",
        "prefecture_slug": "iwate",
        "city_slug": "ichinoseki",
        "latitude": 38.8770,
        "longitude": 141.1530,
        "nearest_station": "JR東北本線 花泉駅",
        "station_walk_minutes": 8,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬専用", "少人数葬対応", "駐車場完備", "地域密着"],
        "operator_name": "家族葬ホール禮賓館",
        "rating_avg": 4.1,
        "review_count": 9,
    },
    {
        "name": "千厩典礼会館",
        "slug": "iwate-senmaya-tenrei-kaikan",
        "venue_type": "private_hall",
        "description": "一関市千厩地区にある葬儀式場。千厩地域の葬儀を幅広くサポートし、家族葬から一般葬まで対応。地域の風習に精通したスタッフが、心のこもったサービスを提供します。",
        "address": "岩手県一関市千厩町千厩字宮敷78-1",
        "prefecture_slug": "iwate",
        "city_slug": "ichinoseki",
        "latitude": 38.8920,
        "longitude": 141.2700,
        "nearest_station": "JR大船渡線 千厩駅",
        "station_walk_minutes": 10,
        "capacity_max": 70,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "一般葬対応", "駐車場完備", "地域密着"],
        "operator_name": "千厩典礼会館",
        "rating_avg": 3.9,
        "review_count": 8,
    },
    {
        "name": "一関コミュニティホール",
        "slug": "iwate-ichinoseki-community-hall",
        "venue_type": "public_facility",
        "description": "一関市中心部にある多目的施設で、葬儀にも利用可能。一ノ関駅から徒歩圏内の好立地で、小規模な家族葬やお別れ会に適しています。低料金で利用でき、地域住民に親しまれています。",
        "address": "岩手県一関市大町7-14",
        "prefecture_slug": "iwate",
        "city_slug": "ichinoseki",
        "latitude": 38.9340,
        "longitude": 141.1280,
        "nearest_station": "JR東北新幹線 一ノ関駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}],
        "features": ["駅近", "低料金", "家族葬対応", "少人数葬対応"],
        "operator_name": "一関市",
        "rating_avg": 3.7,
        "review_count": 7,
    },

    # =============================================
    # 奥州市 (oshu) — 5件
    # =============================================
    {
        "name": "奥州市水沢斎場",
        "slug": "iwate-oshu-mizusawa-saijo",
        "venue_type": "public_crematorium",
        "description": "奥州市が運営する水沢地区の公営火葬場。奥州市民は低料金で利用でき、落ち着いた環境で故人を見送ることができます。式場も併設しており、通夜から火葬まで対応可能です。",
        "address": "岩手県奥州市水沢区佐倉河字明神堂27",
        "prefecture_slug": "iwate",
        "city_slug": "oshu",
        "latitude": 39.1350,
        "longitude": 141.1300,
        "nearest_station": "JR東北本線 水沢駅",
        "station_walk_minutes": 25,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 40,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応"],
        "operator_name": "奥州市",
        "rating_avg": 3.8,
        "review_count": 14,
    },
    {
        "name": "水沢長安殿",
        "slug": "iwate-mizusawa-choan-den",
        "venue_type": "private_hall",
        "description": "さがみ典礼が運営する奥州市水沢の葬儀会館。JR水沢駅から車で5分の好アクセス。大規模な一般葬から家族葬まで、経験豊富なスタッフが丁寧にサポートします。宿泊設備も完備。",
        "address": "岩手県奥州市水沢区東町36",
        "prefecture_slug": "iwate",
        "city_slug": "oshu",
        "latitude": 39.1380,
        "longitude": 141.1380,
        "nearest_station": "JR東北本線 水沢駅",
        "station_walk_minutes": 10,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 45,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["家族葬対応", "一般葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "株式会社アルファクラブ東北（さがみ典礼）",
        "rating_avg": 4.1,
        "review_count": 18,
    },
    {
        "name": "江刺典礼会館",
        "slug": "iwate-esashi-tenrei-kaikan",
        "venue_type": "private_hall",
        "description": "奥州市江刺区にある葬儀式場。江刺地域の葬儀ニーズに応え、家族葬から一般葬まで幅広く対応。地元に根差したサービスで、地域の風習を大切にした葬儀を執り行います。",
        "address": "岩手県奥州市江刺区愛宕字三日町19",
        "prefecture_slug": "iwate",
        "city_slug": "oshu",
        "latitude": 39.1750,
        "longitude": 141.1900,
        "nearest_station": "JR東北本線 水沢駅",
        "station_walk_minutes": 35,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["家族葬対応", "一般葬対応", "駐車場完備", "地域密着"],
        "operator_name": "江刺典礼会館",
        "rating_avg": 3.9,
        "review_count": 10,
    },
    {
        "name": "前沢セレモニーホール",
        "slug": "iwate-maesawa-ceremony-hall",
        "venue_type": "private_hall",
        "description": "奥州市前沢区にある葬儀ホール。前沢地域の葬儀を中心に、家族葬から中規模の葬儀まで対応。静かな環境で故人を偲ぶことができ、駐車場も十分に確保されています。",
        "address": "岩手県奥州市前沢区七日町裏56",
        "prefecture_slug": "iwate",
        "city_slug": "oshu",
        "latitude": 39.0650,
        "longitude": 141.1100,
        "nearest_station": "JR東北本線 前沢駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["家族葬対応", "駐車場完備", "地域密着"],
        "operator_name": "前沢セレモニーホール",
        "rating_avg": 3.8,
        "review_count": 8,
    },
    {
        "name": "ファミラル水沢",
        "slug": "iwate-familal-mizusawa",
        "venue_type": "private_hall",
        "description": "奥州市水沢区にある家族葬対応ホール。アルファクラブ東北が運営し、少人数の家族葬に最適な空間。安置施設完備で、故人と最後の時間をゆっくり過ごせます。",
        "address": "岩手県奥州市水沢区花園町1-3-8",
        "prefecture_slug": "iwate",
        "city_slug": "oshu",
        "latitude": 39.1420,
        "longitude": 141.1450,
        "nearest_station": "JR東北本線 水沢駅",
        "station_walk_minutes": 8,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬専用", "駅近", "安置施設あり", "少人数葬対応"],
        "operator_name": "株式会社アルファクラブ東北",
        "rating_avg": 4.0,
        "review_count": 11,
    },

    # =============================================
    # 花巻市 (hanamaki) — 4件
    # =============================================
    {
        "name": "花巻市石鳥谷斎場",
        "slug": "iwate-hanamaki-ishidoriya-saijo",
        "venue_type": "public_crematorium",
        "description": "花巻市が運営する石鳥谷地区の公営火葬場。花巻市民は低料金で利用でき、自然に囲まれた静かな環境で故人を見送ることができます。火葬棟と待合室を備えています。",
        "address": "岩手県花巻市石鳥谷町好地第2地割161-1",
        "prefecture_slug": "iwate",
        "city_slug": "hanamaki",
        "latitude": 39.4350,
        "longitude": 141.1150,
        "nearest_station": "JR東北本線 石鳥谷駅",
        "station_walk_minutes": 20,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応"],
        "operator_name": "花巻市",
        "rating_avg": 3.7,
        "review_count": 10,
    },
    {
        "name": "花巻西長安殿",
        "slug": "iwate-hanamaki-nishi-choan-den",
        "venue_type": "private_hall",
        "description": "さがみ典礼が運営する花巻市西部の葬儀会館。東北自動車道花巻南ICより車で10分の好アクセス。大規模な一般葬から家族葬まで、充実した設備で幅広く対応します。宿泊設備も完備。",
        "address": "岩手県花巻市西大通り2-19-12",
        "prefecture_slug": "iwate",
        "city_slug": "hanamaki",
        "latitude": 39.3850,
        "longitude": 141.1050,
        "nearest_station": "JR東北本線 花巻駅",
        "station_walk_minutes": 15,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["家族葬対応", "一般葬対応", "宿泊可能", "駐車場完備", "IC近い"],
        "operator_name": "株式会社アルファクラブ東北（さがみ典礼）",
        "rating_avg": 4.2,
        "review_count": 17,
    },
    {
        "name": "セリオホール花巻",
        "slug": "iwate-serio-hanamaki",
        "venue_type": "private_hall",
        "description": "いわて生協が運営する花巻市の葬儀ホール。組合員価格で利用でき、家族葬から一般葬まで対応。地域に密着したサービスと安心の料金体系が特徴です。",
        "address": "岩手県花巻市材木町8-20",
        "prefecture_slug": "iwate",
        "city_slug": "hanamaki",
        "latitude": 39.3880,
        "longitude": 141.1180,
        "nearest_station": "JR東北本線 花巻駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["生協運営", "家族葬対応", "組合員割引", "駅近"],
        "operator_name": "いわて生協",
        "rating_avg": 4.0,
        "review_count": 14,
    },
    {
        "name": "花巻メモリアルホール",
        "slug": "iwate-hanamaki-memorial-hall",
        "venue_type": "private_hall",
        "description": "花巻市中心部にある葬儀ホール。家族葬を中心に、アットホームな雰囲気で故人を偲ぶことができます。温泉の里・花巻の地域性を活かした心温まるサービスを提供。",
        "address": "岩手県花巻市双葉町6-5",
        "prefecture_slug": "iwate",
        "city_slug": "hanamaki",
        "latitude": 39.3900,
        "longitude": 141.1120,
        "nearest_station": "JR東北本線 花巻駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬対応", "駅近", "少人数葬対応", "駐車場完備"],
        "operator_name": "花巻メモリアルホール",
        "rating_avg": 3.9,
        "review_count": 9,
    },

    # =============================================
    # 北上市 (kitakami) — 4件
    # =============================================
    {
        "name": "北上市斎場",
        "slug": "iwate-kitakami-saijo",
        "venue_type": "public_crematorium",
        "description": "北上市が運営する公営の火葬場。北上市民は低料金で利用でき、火葬棟と待合室を備えています。静かな環境の中で故人を見送ることができ、駐車場も完備しています。",
        "address": "岩手県北上市稲瀬町内門岡17",
        "prefecture_slug": "iwate",
        "city_slug": "kitakami",
        "latitude": 39.2750,
        "longitude": 141.1050,
        "nearest_station": "JR東北本線 北上駅",
        "station_walk_minutes": 25,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 35,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応"],
        "operator_name": "北上市",
        "rating_avg": 3.7,
        "review_count": 12,
    },
    {
        "name": "北上長安殿",
        "slug": "iwate-kitakami-choan-den",
        "venue_type": "private_hall",
        "description": "さがみ典礼が運営する北上市の葬儀会館。JR北上駅から車で5分の好アクセス。家族葬から一般葬まで幅広く対応し、宿泊設備も完備。東北自動車道北上ICからも近く、遠方からの参列者にも便利。",
        "address": "岩手県北上市本通り2-3-18",
        "prefecture_slug": "iwate",
        "city_slug": "kitakami",
        "latitude": 39.2830,
        "longitude": 141.1120,
        "nearest_station": "JR東北新幹線 北上駅",
        "station_walk_minutes": 15,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 45,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["家族葬対応", "一般葬対応", "宿泊可能", "駐車場完備", "IC近い"],
        "operator_name": "株式会社アルファクラブ東北（さがみ典礼）",
        "rating_avg": 4.1,
        "review_count": 16,
    },
    {
        "name": "北上コープ葬祭センター",
        "slug": "iwate-kitakami-coop-sosai",
        "venue_type": "private_hall",
        "description": "いわて生協が運営する北上市の葬祭センター。組合員価格で利用でき、明瞭な料金体系が特徴。家族葬から一般葬まで対応し、地域に根差したサービスを提供しています。",
        "address": "岩手県北上市大通り3-5-20",
        "prefecture_slug": "iwate",
        "city_slug": "kitakami",
        "latitude": 39.2850,
        "longitude": 141.1150,
        "nearest_station": "JR東北本線 北上駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 488000}],
        "features": ["生協運営", "組合員割引", "家族葬対応", "駅近"],
        "operator_name": "いわて生協",
        "rating_avg": 4.0,
        "review_count": 13,
    },
    {
        "name": "ファミラル北上",
        "slug": "iwate-familal-kitakami",
        "venue_type": "private_hall",
        "description": "北上市にある家族葬対応ホール。アルファクラブ東北が運営し、少人数のアットホームな葬儀に最適。1日1組限定で、故人と家族の大切な時間を守ります。",
        "address": "岩手県北上市青柳町1-8-15",
        "prefecture_slug": "iwate",
        "city_slug": "kitakami",
        "latitude": 39.2900,
        "longitude": 141.1080,
        "nearest_station": "JR東北本線 北上駅",
        "station_walk_minutes": 12,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬専用", "1日1組限定", "安置施設あり", "少人数葬対応"],
        "operator_name": "株式会社アルファクラブ東北",
        "rating_avg": 4.2,
        "review_count": 10,
    },

    # =============================================
    # 宮古市 (miyako) — 3件
    # =============================================
    {
        "name": "宮古市斎場",
        "slug": "iwate-miyako-saijo",
        "venue_type": "public_crematorium",
        "description": "宮古市が運営する公営の火葬場。三陸海岸の宮古市民の火葬を担い、低料金で利用可能。火葬棟と待合室を備え、静かな環境で故人を見送ることができます。",
        "address": "岩手県宮古市近内第8地割1-10",
        "prefecture_slug": "iwate",
        "city_slug": "miyako",
        "latitude": 39.6350,
        "longitude": 141.9400,
        "nearest_station": "JR山田線 宮古駅",
        "station_walk_minutes": 25,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応"],
        "operator_name": "宮古市",
        "rating_avg": 3.7,
        "review_count": 10,
    },
    {
        "name": "宮古長安殿",
        "slug": "iwate-miyako-choan-den",
        "venue_type": "private_hall",
        "description": "さがみ典礼が運営する宮古市の葬儀会館。JR宮古駅から車で10分。家族葬から一般葬まで対応し、三陸地域の葬儀文化に精通したスタッフが心のこもったサービスを提供します。",
        "address": "岩手県宮古市宮町3-2-15",
        "prefecture_slug": "iwate",
        "city_slug": "miyako",
        "latitude": 39.6400,
        "longitude": 141.9550,
        "nearest_station": "JR山田線 宮古駅",
        "station_walk_minutes": 12,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000}],
        "features": ["家族葬対応", "一般葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "株式会社アルファクラブ東北（さがみ典礼）",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "セリオホール宮古",
        "slug": "iwate-serio-miyako",
        "venue_type": "private_hall",
        "description": "いわて生協が運営する宮古市の葬儀ホール。組合員価格で利用でき、家族葬に最適なアットホームな空間。震災復興後の地域に寄り添い、心温まるサービスを提供しています。",
        "address": "岩手県宮古市磯鶏沖2-10",
        "prefecture_slug": "iwate",
        "city_slug": "miyako",
        "latitude": 39.6250,
        "longitude": 141.9600,
        "nearest_station": "JR山田線 磯鶏駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["生協運営", "家族葬対応", "組合員割引", "駅近"],
        "operator_name": "いわて生協",
        "rating_avg": 4.0,
        "review_count": 8,
    },

    # =============================================
    # 大船渡市 (ofunato) — 2件
    # =============================================
    {
        "name": "大船渡市斎場",
        "slug": "iwate-ofunato-saijo",
        "venue_type": "public_crematorium",
        "description": "大船渡市が運営する公営の火葬場。三陸海岸に位置する大船渡市民の火葬を担っています。東日本大震災からの復興を経て、新しい設備で故人を見送ることができます。",
        "address": "岩手県大船渡市猪川町字久名畑45",
        "prefecture_slug": "iwate",
        "city_slug": "ofunato",
        "latitude": 39.0750,
        "longitude": 141.7150,
        "nearest_station": "JR大船渡線BRT 大船渡駅",
        "station_walk_minutes": 20,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 25,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応"],
        "operator_name": "大船渡市",
        "rating_avg": 3.7,
        "review_count": 8,
    },
    {
        "name": "大船渡メモリアルホール",
        "slug": "iwate-ofunato-memorial-hall",
        "venue_type": "private_hall",
        "description": "大船渡市の民営葬儀ホール。震災復興後の新しい施設で、家族葬から一般葬まで対応。三陸の地域に密着したサービスで、心温まる葬儀を執り行います。",
        "address": "岩手県大船渡市盛町字内ノ目3-8",
        "prefecture_slug": "iwate",
        "city_slug": "ofunato",
        "latitude": 39.0680,
        "longitude": 141.7050,
        "nearest_station": "JR大船渡線BRT 盛駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["家族葬対応", "一般葬対応", "駐車場完備", "地域密着"],
        "operator_name": "大船渡メモリアルホール",
        "rating_avg": 4.0,
        "review_count": 9,
    },

    # =============================================
    # 釜石市 (kamaishi) — 2件
    # =============================================
    {
        "name": "釜石市斎場",
        "slug": "iwate-kamaishi-saijo",
        "venue_type": "public_crematorium",
        "description": "釜石市が運営する公営の火葬場。鉄と魚のまち・釜石の市民の火葬を担っています。東日本大震災からの復興を経て整備された施設で、故人を見送ることができます。",
        "address": "岩手県釜石市甲子町第10地割246",
        "prefecture_slug": "iwate",
        "city_slug": "kamaishi",
        "latitude": 39.2750,
        "longitude": 141.8600,
        "nearest_station": "JR釜石線 釜石駅",
        "station_walk_minutes": 25,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 25,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応"],
        "operator_name": "釜石市",
        "rating_avg": 3.6,
        "review_count": 7,
    },
    {
        "name": "さくらホール釜石",
        "slug": "iwate-sakura-hall-kamaishi",
        "venue_type": "private_hall",
        "description": "釜石市の民営葬儀ホール。JR釜石駅から徒歩約12分の好アクセス。家族葬を中心に、地域に密着したきめ細かなサービスを提供。震災復興の歩みとともに地域に愛されるホールです。",
        "address": "岩手県釜石市大町2-1-15",
        "prefecture_slug": "iwate",
        "city_slug": "kamaishi",
        "latitude": 39.2780,
        "longitude": 141.8750,
        "nearest_station": "JR釜石線 釜石駅",
        "station_walk_minutes": 12,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬対応", "駅近", "駐車場完備", "地域密着"],
        "operator_name": "さくらホール",
        "rating_avg": 4.1,
        "review_count": 10,
    },

    # =============================================
    # 久慈市 (kuji) — 2件
    # =============================================
    {
        "name": "久慈市斎場",
        "slug": "iwate-kuji-saijo",
        "venue_type": "public_crematorium",
        "description": "久慈市が運営する公営の火葬場。NHKあまちゃんの舞台で知られる久慈市民の火葬を担っています。自然に囲まれた静かな環境で、故人を見送ることができます。",
        "address": "岩手県久慈市旭町第8地割2",
        "prefecture_slug": "iwate",
        "city_slug": "kuji",
        "latitude": 40.1900,
        "longitude": 141.7700,
        "nearest_station": "JR八戸線 久慈駅",
        "station_walk_minutes": 20,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 20,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応"],
        "operator_name": "久慈市",
        "rating_avg": 3.6,
        "review_count": 6,
    },
    {
        "name": "久慈典礼会館",
        "slug": "iwate-kuji-tenrei-kaikan",
        "venue_type": "private_hall",
        "description": "久慈市の民営葬儀式場。JR久慈駅から車で5分の好アクセス。家族葬から一般葬まで、久慈地域の風習に精通したスタッフが丁寧にサポートします。",
        "address": "岩手県久慈市中央3-38",
        "prefecture_slug": "iwate",
        "city_slug": "kuji",
        "latitude": 40.1880,
        "longitude": 141.7750,
        "nearest_station": "JR八戸線 久慈駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["家族葬対応", "一般葬対応", "駐車場完備", "地域密着"],
        "operator_name": "久慈典礼会館",
        "rating_avg": 3.9,
        "review_count": 8,
    },

    # =============================================
    # 遠野市 (tono) — 2件
    # =============================================
    {
        "name": "遠野市斎場",
        "slug": "iwate-tono-saijo",
        "venue_type": "public_crematorium",
        "description": "遠野市が運営する公営の火葬場。民話の里・遠野の市民の火葬を担い、自然豊かな環境で故人を見送ることができます。低料金で利用可能です。",
        "address": "岩手県遠野市松崎町白岩18地割20",
        "prefecture_slug": "iwate",
        "city_slug": "tono",
        "latitude": 39.3350,
        "longitude": 141.5300,
        "nearest_station": "JR釜石線 遠野駅",
        "station_walk_minutes": 20,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 20,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応"],
        "operator_name": "遠野市",
        "rating_avg": 3.6,
        "review_count": 5,
    },
    {
        "name": "遠野セレモニーホール",
        "slug": "iwate-tono-ceremony-hall",
        "venue_type": "private_hall",
        "description": "遠野市の民営葬儀ホール。民話の里にふさわしい温かみのある空間で、家族葬を中心にサービスを提供。地域に根差した丁寧な対応が特徴です。",
        "address": "岩手県遠野市中央通り5-12",
        "prefecture_slug": "iwate",
        "city_slug": "tono",
        "latitude": 39.3280,
        "longitude": 141.5340,
        "nearest_station": "JR釜石線 遠野駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬対応", "少人数葬対応", "駐車場完備", "地域密着"],
        "operator_name": "遠野セレモニーホール",
        "rating_avg": 3.8,
        "review_count": 6,
    },

    # =============================================
    # 滝沢市 (takizawa) — 3件
    # =============================================
    {
        "name": "滝沢長安殿",
        "slug": "iwate-takizawa-choan-den",
        "venue_type": "private_hall",
        "description": "さがみ典礼が運営する滝沢市の葬儀会館。盛岡市に隣接する滝沢市で、家族葬から一般葬まで幅広く対応。充実した設備と経験豊富なスタッフが、心のこもったサービスを提供します。",
        "address": "岩手県滝沢市穴口328-3",
        "prefecture_slug": "iwate",
        "city_slug": "takizawa",
        "latitude": 39.7350,
        "longitude": 141.0780,
        "nearest_station": "IGRいわて銀河鉄道 滝沢駅",
        "station_walk_minutes": 15,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["家族葬対応", "一般葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "株式会社アルファクラブ東北（さがみ典礼）",
        "rating_avg": 4.1,
        "review_count": 15,
    },
    {
        "name": "ファミラル滝沢",
        "slug": "iwate-familal-takizawa",
        "venue_type": "private_hall",
        "description": "滝沢市にある家族葬対応ホール。盛岡市のベッドタウンとして発展する滝沢市で、少人数の家族葬に最適な空間を提供。1日1組限定の貸切でゆっくりとお別れの時間を過ごせます。",
        "address": "岩手県滝沢市鵜飼狐洞1-58",
        "prefecture_slug": "iwate",
        "city_slug": "takizawa",
        "latitude": 39.7380,
        "longitude": 141.0850,
        "nearest_station": "IGRいわて銀河鉄道 滝沢駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬専用", "1日1組限定", "安置施設あり", "少人数葬対応"],
        "operator_name": "株式会社アルファクラブ東北",
        "rating_avg": 4.2,
        "review_count": 11,
    },
    {
        "name": "滝沢やすらぎホール",
        "slug": "iwate-takizawa-yasuragi-hall",
        "venue_type": "private_hall",
        "description": "滝沢市の住宅街に位置する葬儀ホール。家族葬を中心に、温かみのある空間で故人を偲びます。バリアフリー設計で高齢の参列者にも配慮。盛岡市斎場やすらぎの丘へのアクセスも良好です。",
        "address": "岩手県滝沢市巣子1154-12",
        "prefecture_slug": "iwate",
        "city_slug": "takizawa",
        "latitude": 39.7500,
        "longitude": 141.0900,
        "nearest_station": "IGRいわて銀河鉄道 巣子駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["家族葬対応", "駅近", "バリアフリー", "駐車場完備"],
        "operator_name": "滝沢やすらぎホール",
        "rating_avg": 3.9,
        "review_count": 9,
    },
]

# 件数を確認
print(f"岩手県の斎場データ: 合計 {len(venues)} 件")

# 10件ずつバッチで投入
batch_size = 10
for i in range(0, len(venues), batch_size):
    batch = venues[i:i+batch_size]
    code = insert_batch(batch)
    print(f"  バッチ {i//batch_size + 1} ({len(batch)}件): HTTP {code}")
    if code != "201":
        # エラー時は詳細を取得
        data_json = json.dumps(batch, ensure_ascii=False)
        result = subprocess.run([
            "curl", "-s",
            "-X", "POST", SUPABASE_URL,
            "-H", f"apikey: {API_KEY}",
            "-H", f"Authorization: Bearer {API_KEY}",
            "-H", "Content-Type: application/json",
            "-H", "Prefer: return=minimal",
            "-H", "User-Agent: Mozilla/5.0",
            "-d", data_json
        ], capture_output=True, text=True)
        print(f"    エラー詳細: {result.stdout[:500]}")
    time.sleep(1)

print("岩手県の投入完了!")
