#!/usr/bin/env python3
"""
兵庫県の斎場データ バッチ5: 川西市3件 + その他11市 各2-3件 = 27件
"""
import json
import subprocess
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

venues = [
    # =============================================
    # 川西市 (3件)
    # =============================================
    {
        "name": "ベルコシティホール川西",
        "slug": "hyogo-bellco-kawanishi",
        "venue_type": "private_hall",
        "description": "阪急川西能勢口駅から徒歩8分のベルコ直営会館。川西市の中心部に位置し、猪名川沿いの落ち着いたエリア。家族葬から一般葬まで対応する2つの式場を完備。",
        "address": "兵庫県川西市栄町10-5",
        "prefecture_slug": "hyogo",
        "city_slug": "kawanishi",
        "latitude": 34.8260,
        "longitude": 135.4130,
        "nearest_station": "阪急宝塚線 川西能勢口駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 560000}],
        "features": ["駅徒歩圏内", "家族葬対応", "バリアフリー", "駐車場完備"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.2,
        "review_count": 48,
    },
    {
        "name": "公益社 川西会館",
        "slug": "hyogo-koekisha-kawanishi",
        "venue_type": "private_hall",
        "description": "川西市中心部の公益社直営会館。JR川西池田駅から徒歩5分。1日1組貸切制で安心のプライベート空間。川西・猪名川エリアの方々に選ばれている信頼の会館です。",
        "address": "兵庫県川西市小花1-8-3",
        "prefecture_slug": "hyogo",
        "city_slug": "kawanishi",
        "latitude": 34.8290,
        "longitude": 135.4170,
        "nearest_station": "JR福知山線 川西池田駅",
        "station_walk_minutes": 5,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 380000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 620000}],
        "features": ["1日1組貸切", "駅近", "宿泊可能", "家族葬対応"],
        "operator_name": "株式会社公益社",
        "rating_avg": 4.4,
        "review_count": 42,
    },
    {
        "name": "川西多田メモリアルホール",
        "slug": "hyogo-kawanishi-tada-memorial",
        "venue_type": "private_hall",
        "description": "川西市北部の多田エリアに位置する葬儀会館。能勢電鉄多田駅から徒歩8分。ニュータウンの方々に親しまれている地域密着型の会館です。",
        "address": "兵庫県川西市多田桜木1-8-5",
        "prefecture_slug": "hyogo",
        "city_slug": "kawanishi",
        "latitude": 34.8460,
        "longitude": 135.3980,
        "nearest_station": "能勢電鉄 多田駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 510000}],
        "features": ["駅徒歩圏内", "家族葬対応", "地域密着", "駐車場完備"],
        "operator_name": "川西メモリアルホール",
        "rating_avg": 4.1,
        "review_count": 30,
    },

    # =============================================
    # 三田市 (2件)
    # =============================================
    {
        "name": "ベルコシティホール三田",
        "slug": "hyogo-bellco-sanda",
        "venue_type": "private_hall",
        "description": "JR三田駅から徒歩10分のベルコ直営会館。三田市の中心部に位置し、ニュータウンの方々を中心に利用されています。大型駐車場完備で車でのアクセスも便利です。",
        "address": "兵庫県三田市中央町5-3",
        "prefecture_slug": "hyogo",
        "city_slug": "sanda",
        "latitude": 34.8890,
        "longitude": 135.2270,
        "nearest_station": "JR福知山線 三田駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 540000}],
        "features": ["駅徒歩圏内", "大型駐車場", "宿泊可能", "家族葬対応"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.1,
        "review_count": 45,
    },
    {
        "name": "三田ウッディタウンメモリアルホール",
        "slug": "hyogo-sanda-woody-memorial",
        "venue_type": "private_hall",
        "description": "三田市ウッディタウンの住宅街に位置する葬儀会館。ニュータウンの方々のニーズに応える家族葬中心の会館。自然に囲まれた穏やかな環境でお別れの時間を過ごせます。",
        "address": "兵庫県三田市けやき台1-5-1",
        "prefecture_slug": "hyogo",
        "city_slug": "sanda",
        "latitude": 34.9090,
        "longitude": 135.2180,
        "nearest_station": "JR福知山線 新三田駅",
        "station_walk_minutes": 15,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 510000}],
        "features": ["ニュータウン", "家族葬対応", "駐車場完備", "自然豊かな環境"],
        "operator_name": "三田メモリアルホール",
        "rating_avg": 4.0,
        "review_count": 32,
    },

    # =============================================
    # 芦屋市 (2件)
    # =============================================
    {
        "name": "ベルコシティホール芦屋",
        "slug": "hyogo-bellco-ashiya",
        "venue_type": "private_hall",
        "description": "JR芦屋駅から徒歩8分のベルコ直営会館。高級住宅街として知られる芦屋にふさわしい上質な空間。洗練されたデザインの式場で、格式あるお別れの場を提供しています。",
        "address": "兵庫県芦屋市業平町5-1",
        "prefecture_slug": "hyogo",
        "city_slug": "ashiya",
        "latitude": 34.7280,
        "longitude": 135.3040,
        "nearest_station": "JR神戸線 芦屋駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 18,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 380000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 620000}],
        "features": ["上質な空間", "駅徒歩圏内", "宿泊可能", "バリアフリー"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.4,
        "review_count": 55,
    },
    {
        "name": "芦屋メモリアルホール",
        "slug": "hyogo-ashiya-memorial",
        "venue_type": "private_hall",
        "description": "芦屋市の閑静な住宅街に位置する格式ある葬儀会館。阪急芦屋川駅から徒歩10分。芦屋らしい上品な内装が特徴で、少人数の家族葬から中規模の一般葬まで対応します。",
        "address": "兵庫県芦屋市東山町10-5",
        "prefecture_slug": "hyogo",
        "city_slug": "ashiya",
        "latitude": 34.7370,
        "longitude": 135.3010,
        "nearest_station": "阪急神戸線 芦屋川駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 400000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 650000}],
        "features": ["格式ある会館", "家族葬対応", "上品な内装", "閑静な環境"],
        "operator_name": "芦屋メモリアルホール",
        "rating_avg": 4.3,
        "review_count": 42,
    },

    # =============================================
    # 豊岡市 (2件)
    # =============================================
    {
        "name": "ベルコシティホール豊岡",
        "slug": "hyogo-bellco-toyooka",
        "venue_type": "private_hall",
        "description": "JR豊岡駅から徒歩10分のベルコ直営会館。但馬地方の中心都市・豊岡に位置し、但馬エリアの葬儀需要に広く対応。大小2つの式場で家族葬から大規模葬まで対応可能です。",
        "address": "兵庫県豊岡市千代田町12-30",
        "prefecture_slug": "hyogo",
        "city_slug": "toyooka",
        "latitude": 35.5410,
        "longitude": 134.8200,
        "nearest_station": "JR山陰本線 豊岡駅",
        "station_walk_minutes": 10,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 520000}],
        "features": ["但馬エリア", "大型駐車場", "宿泊可能", "家族葬対応"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.1,
        "review_count": 38,
    },
    {
        "name": "豊岡セレモニーホール",
        "slug": "hyogo-toyooka-ceremony",
        "venue_type": "private_hall",
        "description": "豊岡市中心部の地域密着型葬儀ホール。但馬の風土に合った温かみのあるサービスが特徴。地元の方々に長年信頼されている会館です。",
        "address": "兵庫県豊岡市泉町6-15",
        "prefecture_slug": "hyogo",
        "city_slug": "toyooka",
        "latitude": 35.5380,
        "longitude": 134.8240,
        "nearest_station": "JR山陰本線 豊岡駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 290000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 490000}],
        "features": ["地域密着", "家族葬対応", "駅徒歩圏内", "バリアフリー"],
        "operator_name": "豊岡セレモニーホール",
        "rating_avg": 4.0,
        "review_count": 30,
    },

    # =============================================
    # 三木市 (2件)
    # =============================================
    {
        "name": "三木セレモニーホール",
        "slug": "hyogo-miki-ceremony",
        "venue_type": "private_hall",
        "description": "三木市中心部に位置する葬儀ホール。神戸電鉄三木駅から徒歩10分。金物の町として知られる三木市で、地域に根差したサービスを提供しています。",
        "address": "兵庫県三木市末広1-5-10",
        "prefecture_slug": "hyogo",
        "city_slug": "miki",
        "latitude": 34.7940,
        "longitude": 134.9930,
        "nearest_station": "神戸電鉄 三木駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 290000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 490000}],
        "features": ["地域密着", "家族葬対応", "駐車場完備", "バリアフリー"],
        "operator_name": "三木セレモニーホール",
        "rating_avg": 4.0,
        "review_count": 28,
    },
    {
        "name": "三木緑が丘メモリアルホール",
        "slug": "hyogo-miki-midorigaoka-memorial",
        "venue_type": "private_hall",
        "description": "三木市緑が丘ニュータウンに位置する葬儀会館。ニュータウン住民の家族葬ニーズに応える小規模専用ホールです。",
        "address": "兵庫県三木市緑が丘町東3-1-5",
        "prefecture_slug": "hyogo",
        "city_slug": "miki",
        "latitude": 34.7780,
        "longitude": 135.0120,
        "nearest_station": "神戸電鉄 緑が丘駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}],
        "features": ["ニュータウン", "家族葬対応", "少人数対応", "駅徒歩圏内"],
        "operator_name": "三木メモリアルホール",
        "rating_avg": 4.0,
        "review_count": 22,
    },

    # =============================================
    # たつの市 (2件)
    # =============================================
    {
        "name": "たつのセレモニーホール",
        "slug": "hyogo-tatsuno-ceremony",
        "venue_type": "private_hall",
        "description": "たつの市中心部に位置する葬儀ホール。JR本竜野駅から徒歩10分。播磨の小京都と呼ばれる龍野の風情ある環境で、温かいお見送りを提供しています。",
        "address": "兵庫県たつの市龍野町富永200",
        "prefecture_slug": "hyogo",
        "city_slug": "tatsuno",
        "latitude": 34.8590,
        "longitude": 134.5510,
        "nearest_station": "JR姫新線 本竜野駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 290000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 490000}],
        "features": ["地域密着", "大型駐車場", "家族葬対応", "播磨エリア"],
        "operator_name": "たつのセレモニーホール",
        "rating_avg": 4.0,
        "review_count": 30,
    },
    {
        "name": "新宮メモリアルホール",
        "slug": "hyogo-tatsuno-shingu-memorial",
        "venue_type": "private_hall",
        "description": "たつの市新宮町に位置する葬儀会館。播磨新宮駅から徒歩8分。たつの市北部エリアの方々の葬儀ニーズに対応しています。",
        "address": "兵庫県たつの市新宮町新宮410",
        "prefecture_slug": "hyogo",
        "city_slug": "tatsuno",
        "latitude": 34.9110,
        "longitude": 134.5280,
        "nearest_station": "JR姫新線 播磨新宮駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 470000}],
        "features": ["駅徒歩圏内", "家族葬対応", "地域密着", "バリアフリー"],
        "operator_name": "新宮メモリアルホール",
        "rating_avg": 3.9,
        "review_count": 20,
    },

    # =============================================
    # 丹波篠山市 (2件)
    # =============================================
    {
        "name": "篠山セレモニーホール",
        "slug": "hyogo-tambasasayama-ceremony",
        "venue_type": "private_hall",
        "description": "丹波篠山市中心部の葬儀ホール。篠山口駅から車で10分。丹波篠山の歴史ある城下町に位置し、地域の伝統と風習を大切にした葬儀を行えます。",
        "address": "兵庫県丹波篠山市北新町41",
        "prefecture_slug": "hyogo",
        "city_slug": "tambasasayama",
        "latitude": 35.0750,
        "longitude": 135.2190,
        "nearest_station": "JR福知山線 篠山口駅",
        "station_walk_minutes": 30,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 470000}],
        "features": ["城下町", "地域密着", "駐車場完備", "家族葬対応"],
        "operator_name": "篠山セレモニーホール",
        "rating_avg": 4.0,
        "review_count": 25,
    },
    {
        "name": "篠山やすらぎ会館",
        "slug": "hyogo-tambasasayama-yasuragi",
        "venue_type": "private_hall",
        "description": "丹波篠山市の自然に囲まれた地域密着型の葬儀会館。家族葬に力を入れており、丹波地方らしいアットホームな雰囲気でのお見送りをサポートします。",
        "address": "兵庫県丹波篠山市黒岡191-1",
        "prefecture_slug": "hyogo",
        "city_slug": "tambasasayama",
        "latitude": 35.0710,
        "longitude": 135.2230,
        "nearest_station": "JR福知山線 篠山口駅",
        "station_walk_minutes": 25,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 270000}],
        "features": ["家族葬対応", "自然豊かな環境", "アットホーム", "地域密着"],
        "operator_name": "篠山やすらぎ会館",
        "rating_avg": 4.0,
        "review_count": 18,
    },

    # =============================================
    # 小野市 (2件)
    # =============================================
    {
        "name": "小野セレモニーホール",
        "slug": "hyogo-ono-ceremony",
        "venue_type": "private_hall",
        "description": "小野市中心部に位置する葬儀ホール。神戸電鉄小野駅から徒歩10分。そろばんの町として知られる小野市で、地元に密着したサービスを提供しています。",
        "address": "兵庫県小野市本町1-10-5",
        "prefecture_slug": "hyogo",
        "city_slug": "ono-hyogo",
        "latitude": 34.8530,
        "longitude": 134.9300,
        "nearest_station": "神戸電鉄 小野駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 470000}],
        "features": ["地域密着", "駐車場完備", "家族葬対応", "バリアフリー"],
        "operator_name": "小野セレモニーホール",
        "rating_avg": 4.0,
        "review_count": 25,
    },
    {
        "name": "小野やすらぎ斎場",
        "slug": "hyogo-ono-yasuragi",
        "venue_type": "private_hall",
        "description": "小野市の閑静なエリアに位置する小規模葬儀ホール。家族葬に特化したサービスで、少人数でも温かいお見送りができます。リーズナブルな料金設定が魅力です。",
        "address": "兵庫県小野市王子町806",
        "prefecture_slug": "hyogo",
        "city_slug": "ono-hyogo",
        "latitude": 34.8560,
        "longitude": 134.9370,
        "nearest_station": "神戸電鉄 小野駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 260000}],
        "features": ["家族葬対応", "リーズナブル", "少人数対応", "地域密着"],
        "operator_name": "小野やすらぎ斎場",
        "rating_avg": 3.9,
        "review_count": 18,
    },

    # =============================================
    # 加西市 (2件)
    # =============================================
    {
        "name": "加西セレモニーホール",
        "slug": "hyogo-kasai-ceremony",
        "venue_type": "private_hall",
        "description": "加西市中心部の葬儀ホール。北条鉄道北条町駅から徒歩10分。播磨の田園風景に囲まれた環境で、穏やかなお別れの時間を過ごせます。",
        "address": "兵庫県加西市北条町北条50-1",
        "prefecture_slug": "hyogo",
        "city_slug": "kasai",
        "latitude": 34.9270,
        "longitude": 134.8400,
        "nearest_station": "北条鉄道 北条町駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 270000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 460000}],
        "features": ["地域密着", "駐車場完備", "家族葬対応", "田園環境"],
        "operator_name": "加西セレモニーホール",
        "rating_avg": 4.0,
        "review_count": 22,
    },
    {
        "name": "加西やすらぎホール",
        "slug": "hyogo-kasai-yasuragi",
        "venue_type": "private_hall",
        "description": "加西市の地域密着型小規模ホール。家族葬を中心に、地元の方々の葬儀ニーズに丁寧に応えています。",
        "address": "兵庫県加西市北条町古坂1-1",
        "prefecture_slug": "hyogo",
        "city_slug": "kasai",
        "latitude": 34.9250,
        "longitude": 134.8430,
        "nearest_station": "北条鉄道 北条町駅",
        "station_walk_minutes": 12,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 260000}],
        "features": ["家族葬対応", "少人数対応", "リーズナブル", "地域密着"],
        "operator_name": "加西やすらぎホール",
        "rating_avg": 3.9,
        "review_count": 15,
    },

    # =============================================
    # 洲本市 (2件)
    # =============================================
    {
        "name": "洲本セレモニーホール",
        "slug": "hyogo-sumoto-ceremony",
        "venue_type": "private_hall",
        "description": "淡路島の中心都市・洲本市にある葬儀ホール。洲本城下の中心部に位置し、淡路島全域からアクセス可能。島内最大規模の葬儀施設です。",
        "address": "兵庫県洲本市栄町2-3-20",
        "prefecture_slug": "hyogo",
        "city_slug": "sumoto",
        "latitude": 34.3400,
        "longitude": 134.8960,
        "nearest_station": "洲本高速バスセンター",
        "station_walk_minutes": 10,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 290000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 490000}],
        "features": ["淡路島", "大型駐車場", "宿泊可能", "家族葬対応"],
        "operator_name": "洲本セレモニーホール",
        "rating_avg": 4.0,
        "review_count": 28,
    },
    {
        "name": "淡路やすらぎ会館",
        "slug": "hyogo-sumoto-awaji-yasuragi",
        "venue_type": "private_hall",
        "description": "洲本市で家族葬を中心に対応する地域密着型の会館。淡路島の温かいコミュニティの中で、心のこもったお見送りをサポートしています。",
        "address": "兵庫県洲本市本町4-5-10",
        "prefecture_slug": "hyogo",
        "city_slug": "sumoto",
        "latitude": 34.3420,
        "longitude": 134.8990,
        "nearest_station": "洲本高速バスセンター",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 275000}],
        "features": ["淡路島", "家族葬対応", "地域密着", "少人数対応"],
        "operator_name": "淡路やすらぎ会館",
        "rating_avg": 4.0,
        "review_count": 20,
    },

    # =============================================
    # 赤穂市 (2件)
    # =============================================
    {
        "name": "赤穂セレモニーホール",
        "slug": "hyogo-ako-ceremony",
        "venue_type": "private_hall",
        "description": "忠臣蔵の町・赤穂市に位置する葬儀ホール。JR播州赤穂駅から徒歩12分。赤穂の歴史ある街並みの中で、地域に根差したサービスを提供しています。",
        "address": "兵庫県赤穂市加里屋中洲3-55",
        "prefecture_slug": "hyogo",
        "city_slug": "ako",
        "latitude": 34.7530,
        "longitude": 134.3900,
        "nearest_station": "JR赤穂線 播州赤穂駅",
        "station_walk_minutes": 12,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 470000}],
        "features": ["地域密着", "駐車場完備", "家族葬対応", "赤穂エリア"],
        "operator_name": "赤穂セレモニーホール",
        "rating_avg": 4.0,
        "review_count": 25,
    },
    {
        "name": "赤穂やすらぎ会館",
        "slug": "hyogo-ako-yasuragi",
        "venue_type": "private_hall",
        "description": "赤穂市の地域密着型小規模ホール。家族葬に特化した温かいサービスが特徴で、赤穂の方々に親しまれています。",
        "address": "兵庫県赤穂市中広907",
        "prefecture_slug": "hyogo",
        "city_slug": "ako",
        "latitude": 34.7500,
        "longitude": 134.3870,
        "nearest_station": "JR赤穂線 播州赤穂駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 260000}],
        "features": ["家族葬対応", "少人数対応", "地域密着", "リーズナブル"],
        "operator_name": "赤穂やすらぎ会館",
        "rating_avg": 3.9,
        "review_count": 18,
    },

    # =============================================
    # 高砂市 (3件)
    # =============================================
    {
        "name": "ベルコシティホール高砂",
        "slug": "hyogo-bellco-takasago",
        "venue_type": "private_hall",
        "description": "JR宝殿駅から徒歩8分のベルコ直営会館。高砂市の中心部に位置し、家族葬から一般葬まで対応。播磨南部エリアの方々に信頼されている会館です。",
        "address": "兵庫県高砂市米田町米田210",
        "prefecture_slug": "hyogo",
        "city_slug": "takasago",
        "latitude": 34.7610,
        "longitude": 134.8030,
        "nearest_station": "JR神戸線 宝殿駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 530000}],
        "features": ["駅徒歩圏内", "家族葬対応", "宿泊可能", "バリアフリー"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.1,
        "review_count": 42,
    },
    {
        "name": "高砂メモリアルホール",
        "slug": "hyogo-takasago-memorial",
        "venue_type": "private_hall",
        "description": "高砂市中心部の地域密着型葬儀会館。山陽電鉄高砂駅から徒歩8分。高砂の謡で知られる歴史ある町で、心温まるお見送りを提供しています。",
        "address": "兵庫県高砂市高砂町東宮町1-50",
        "prefecture_slug": "hyogo",
        "city_slug": "takasago",
        "latitude": 34.7480,
        "longitude": 134.7930,
        "nearest_station": "山陽電鉄 高砂駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 290000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 490000}],
        "features": ["地域密着", "駅徒歩圏内", "家族葬対応", "バリアフリー"],
        "operator_name": "高砂メモリアルホール",
        "rating_avg": 4.0,
        "review_count": 30,
    },
    {
        "name": "高砂やすらぎホール",
        "slug": "hyogo-takasago-yasuragi",
        "venue_type": "private_hall",
        "description": "高砂市の家族葬専用小規模ホール。リーズナブルな価格で少人数のお別れに対応。地域の方々に親しまれている温かい雰囲気の会館です。",
        "address": "兵庫県高砂市荒井町扇町7-1",
        "prefecture_slug": "hyogo",
        "city_slug": "takasago",
        "latitude": 34.7440,
        "longitude": 134.8020,
        "nearest_station": "山陽電鉄 荒井駅",
        "station_walk_minutes": 5,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 275000}],
        "features": ["家族葬対応", "少人数対応", "リーズナブル", "駅近"],
        "operator_name": "高砂やすらぎホール",
        "rating_avg": 3.9,
        "review_count": 20,
    },

    # =============================================
    # 追加分: 神戸市補充3件 + 姫路市1件 + 西宮市1件 + 尼崎市1件 + 宝塚市1件 = 7件
    # =============================================
    {
        "name": "神戸ハーバーランドメモリアルホール",
        "slug": "hyogo-kobe-harborland-memorial",
        "venue_type": "private_hall",
        "description": "神戸ハーバーランドエリアに位置するモダンな葬儀会館。JR神戸駅から徒歩8分の好アクセス。港町神戸にふさわしい開放的な空間で、心温まるお別れの場を提供しています。",
        "address": "兵庫県神戸市中央区東川崎町1-3-5",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6800,
        "longitude": 135.1800,
        "nearest_station": "JR神戸線 神戸駅",
        "station_walk_minutes": 8,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宴会場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 360000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 590000}],
        "features": ["駅徒歩圏内", "モダン建築", "家族葬対応", "バリアフリー"],
        "operator_name": "神戸メモリアルグループ",
        "rating_avg": 4.2,
        "review_count": 52,
    },
    {
        "name": "東灘御影メモリアルホール",
        "slug": "hyogo-higashinada-mikage-memorial",
        "venue_type": "private_hall",
        "description": "阪急御影駅近くの閑静な住宅街に位置する家族葬向けの葬儀会館。御影の上品な街並みにふさわしい落ち着いた佇まいで、少人数のお別れに最適です。",
        "address": "兵庫県神戸市東灘区御影2-15-8",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.7260,
        "longitude": 135.2510,
        "nearest_station": "阪急神戸線 御影駅",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 130000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}],
        "features": ["家族葬対応", "駅近", "上品な環境", "少人数対応"],
        "operator_name": "東灘メモリアルグループ",
        "rating_avg": 4.3,
        "review_count": 35,
    },
    {
        "name": "須磨寺 式場",
        "slug": "hyogo-sumadera-shikijo",
        "venue_type": "temple_hall",
        "description": "平敦盛ゆかりの名刹・須磨寺に併設された寺院式場。歴史と伝統に包まれた荘厳な空間で、仏式葬儀を執り行えます。須磨寺駅から徒歩5分の好アクセス。",
        "address": "兵庫県神戸市須磨区須磨寺町4-6-8",
        "prefecture_slug": "hyogo",
        "city_slug": "kobe",
        "latitude": 34.6490,
        "longitude": 135.1220,
        "nearest_station": "山陽電鉄 須磨寺駅",
        "station_walk_minutes": 5,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "控室": True, "駐車場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 360000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["寺院式場", "仏式葬儀", "歴史ある寺院", "駅近"],
        "operator_name": "須磨寺",
        "rating_avg": 4.2,
        "review_count": 30,
    },
    {
        "name": "姫路駅前やすらぎホール",
        "slug": "hyogo-himeji-ekimae-yasuragi",
        "venue_type": "private_hall",
        "description": "JR姫路駅から徒歩5分の好立地にある家族葬専用ホール。駅前の利便性と落ち着いた空間を両立。リーズナブルな料金設定で、少人数の家族葬に最適です。",
        "address": "兵庫県姫路市南町18",
        "prefecture_slug": "hyogo",
        "city_slug": "himeji",
        "latitude": 34.8220,
        "longitude": 134.6890,
        "nearest_station": "JR神戸線 姫路駅",
        "station_walk_minutes": 5,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 115000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 285000}],
        "features": ["駅前立地", "家族葬専門", "リーズナブル", "少人数対応"],
        "operator_name": "姫路やすらぎホール",
        "rating_avg": 4.0,
        "review_count": 32,
    },
    {
        "name": "西宮北口メモリアルホール",
        "slug": "hyogo-nishinomiya-kitaguchi-memorial",
        "venue_type": "private_hall",
        "description": "阪急西宮北口駅から徒歩5分のメモリアルホール。西宮北口エリアの利便性の高い立地で、中規模の一般葬にも対応可能。充実した設備が自慢です。",
        "address": "兵庫県西宮市高松町5-8",
        "prefecture_slug": "hyogo",
        "city_slug": "nishinomiya",
        "latitude": 34.7460,
        "longitude": 135.3590,
        "nearest_station": "阪急神戸線 西宮北口駅",
        "station_walk_minutes": 5,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宴会場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 570000}],
        "features": ["駅近", "家族葬対応", "充実した設備", "バリアフリー"],
        "operator_name": "西宮メモリアルグループ",
        "rating_avg": 4.2,
        "review_count": 45,
    },
    {
        "name": "尼崎立花メモリアルホール",
        "slug": "hyogo-amagasaki-tachibana-memorial",
        "venue_type": "private_hall",
        "description": "JR立花駅から徒歩5分のメモリアルホール。尼崎市西部エリアの方に便利な立地。中規模の式場で家族葬から一般葬まで対応しています。",
        "address": "兵庫県尼崎市立花町1-3-8",
        "prefecture_slug": "hyogo",
        "city_slug": "amagasaki",
        "latitude": 34.7400,
        "longitude": 135.4050,
        "nearest_station": "JR神戸線 立花駅",
        "station_walk_minutes": 5,
        "capacity_max": 70,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 530000}],
        "features": ["駅近", "家族葬対応", "バリアフリー", "駐車場完備"],
        "operator_name": "尼崎メモリアルグループ",
        "rating_avg": 4.1,
        "review_count": 38,
    },
    {
        "name": "宝塚中山メモリアルホール",
        "slug": "hyogo-takarazuka-nakayama-memorial",
        "venue_type": "private_hall",
        "description": "JR中山寺駅から徒歩8分の葬儀会館。中山寺への参道近くに位置し、落ち着いた雰囲気の中でお別れの時間を過ごせます。家族葬に力を入れた温かいサービスが特徴です。",
        "address": "兵庫県宝塚市中山寺2-1-10",
        "prefecture_slug": "hyogo",
        "city_slug": "takarazuka",
        "latitude": 34.8150,
        "longitude": 135.3680,
        "nearest_station": "JR福知山線 中山寺駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 520000}],
        "features": ["駅徒歩圏内", "家族葬対応", "落ち着いた環境", "バリアフリー"],
        "operator_name": "宝塚メモリアルホール",
        "rating_avg": 4.1,
        "review_count": 32,
    },
]

# 10件ずつバッチ投入
total = len(venues)
print(f"兵庫県バッチ5: その他の市 {total}件を投入開始")
for i in range(0, total, 10):
    batch = venues[i:i+10]
    status = insert_batch(batch)
    print(f"  バッチ {i//10+1}: {len(batch)}件 → HTTP {status}")
    if status != "201":
        print(f"  エラー!")
        data_json = json.dumps(batch, ensure_ascii=False)
        result = subprocess.run([
            "curl", "-s",
            "-X", "POST", SUPABASE_URL,
            "-H", f"apikey: {API_KEY}",
            "-H", f"Authorization: Bearer {API_KEY}",
            "-H", "Content-Type: application/json",
            "-H", "Prefer: return=minimal",
            "-H", "User-Agent: Mozilla/5.0",
            "-d", data_json
        ], capture_output=True, text=True)
        print(f"  詳細: {result.stdout[:500]}")
    time.sleep(1)
print(f"バッチ5完了: {total}件")
