#!/usr/bin/env python3
"""
大阪府の斎場データ バッチ1: 大阪市 前半50件
"""
import json
import subprocess
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

venues = [
    # =============================================
    # 公営火葬場 (5件)
    # =============================================
    {
        "name": "大阪市立北斎場",
        "slug": "osaka-kita-saijo",
        "venue_type": "public_crematorium",
        "description": "大阪市北区にある市営の総合斎場。火葬棟と式場を備え、通夜から告別式・火葬まで同一敷地内で執り行えます。大阪メトロ天神橋筋六丁目駅から徒歩8分と交通アクセスが良好。大阪市民は火葬料が大幅に減額されます。2017年にリニューアルされ、清潔で近代的な設備が整っています。",
        "address": "大阪府大阪市北区長柄西1-7-13",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7090,
        "longitude": 135.5120,
        "nearest_station": "大阪メトロ谷町線・堺筋線 天神橋筋六丁目駅",
        "station_walk_minutes": 8,
        "capacity_max": 100,
        "hall_count": 3,
        "has_crematorium": True,
        "parking_count": 60,
        "facilities": {"式場": True, "休憩室": True, "駐車場": True, "バリアフリー": True, "売店": True, "霊安室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}],
        "features": ["火葬場併設", "公営斎場", "駅近", "バリアフリー", "大阪市民割引"],
        "operator_name": "大阪市",
        "rating_avg": 4.0,
        "review_count": 128
    },
    {
        "name": "大阪市立瓜破斎場",
        "slug": "osaka-uriwari-saijo",
        "venue_type": "public_crematorium",
        "description": "大阪市平野区にある市営の大規模斎場。火葬炉18基を備え、大阪市南部エリアの葬儀需要を担う中核施設です。式場3室を完備し、通夜・告別式・火葬まで一貫して行えます。大阪メトロ谷町線喜連瓜破駅から徒歩15分。広い駐車場を完備し、大規模な葬儀にも対応可能です。",
        "address": "大阪府大阪市平野区瓜破東4-4-146",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6050,
        "longitude": 135.5580,
        "nearest_station": "大阪メトロ谷町線 喜連瓜破駅",
        "station_walk_minutes": 15,
        "capacity_max": 150,
        "hall_count": 3,
        "has_crematorium": True,
        "parking_count": 150,
        "facilities": {"式場": True, "休憩室": True, "駐車場": True, "バリアフリー": True, "売店": True, "霊安室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}],
        "features": ["火葬場併設", "公営斎場", "大規模施設", "駐車場完備", "大阪市民割引"],
        "operator_name": "大阪市",
        "rating_avg": 3.9,
        "review_count": 105
    },
    {
        "name": "大阪市立佃斎場",
        "slug": "osaka-tsukuda-saijo",
        "venue_type": "public_crematorium",
        "description": "大阪市西淀川区にある市営火葬場。大阪市北西部エリアの火葬需要を担う公営施設です。火葬炉12基を備え、市民は低額の使用料で利用可能。JR東西線御幣島駅から徒歩約12分。駐車場を完備し、車でのアクセスも便利です。",
        "address": "大阪府大阪市西淀川区佃6-4-18",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7150,
        "longitude": 135.4530,
        "nearest_station": "JR東西線 御幣島駅",
        "station_walk_minutes": 12,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 40,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True, "霊安室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}],
        "features": ["火葬場併設", "公営斎場", "大阪市民割引"],
        "operator_name": "大阪市",
        "rating_avg": 3.7,
        "review_count": 62
    },
    {
        "name": "大阪市立鶴見斎場",
        "slug": "osaka-tsurumi-saijo",
        "venue_type": "public_crematorium",
        "description": "大阪市鶴見区にある市営の火葬場。大阪市東部エリアの火葬需要を支える施設で、火葬炉を備えた近代的な建物です。大阪メトロ長堀鶴見緑地線横堤駅から徒歩約10分。周辺は住宅地で落ち着いた環境にあります。",
        "address": "大阪府大阪市鶴見区鶴見4-10-6",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7010,
        "longitude": 135.5780,
        "nearest_station": "大阪メトロ長堀鶴見緑地線 横堤駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 35,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}],
        "features": ["火葬場併設", "公営斎場", "駅近", "大阪市民割引"],
        "operator_name": "大阪市",
        "rating_avg": 3.8,
        "review_count": 48
    },
    {
        "name": "大阪市立小林斎場",
        "slug": "osaka-kobayashi-saijo",
        "venue_type": "public_crematorium",
        "description": "大阪市大正区にある市営の火葬場。大阪市南西部の火葬を担当し、火葬炉を備えた施設です。JR大阪環状線大正駅からバスでアクセス可能。駐車場も完備されています。",
        "address": "大阪府大阪市大正区小林東3-12-8",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6420,
        "longitude": 135.4720,
        "nearest_station": "JR大阪環状線 大正駅",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 30,
        "facilities": {"休憩室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}],
        "features": ["火葬場併設", "公営斎場", "大阪市民割引"],
        "operator_name": "大阪市",
        "rating_avg": 3.6,
        "review_count": 33
    },

    # =============================================
    # 大阪市北区・中央区・都島区・福島区 (10件)
    # =============================================
    {
        "name": "公益社 大阪中央ホール",
        "slug": "osaka-koeisha-chuo-hall",
        "venue_type": "private_hall",
        "description": "大阪市中央区に位置する公益社の旗艦ホール。地下鉄谷町四丁目駅から徒歩3分の好立地。家族葬から社葬まで幅広く対応できる大小複数の式場を完備。格式ある空間と手厚いスタッフ対応で、大阪でもトップクラスの評価を受けています。",
        "address": "大阪府大阪市中央区谷町3-1-18",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6810,
        "longitude": 135.5180,
        "nearest_station": "大阪メトロ谷町線 谷町四丁目駅",
        "station_walk_minutes": 3,
        "capacity_max": 200,
        "hall_count": 4,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True, "僧侶控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "一般葬対応", "社葬対応", "駅近", "大阪最大手", "1日1組貸切"],
        "operator_name": "公益社（燦ホールディングス）",
        "rating_avg": 4.4,
        "review_count": 215
    },
    {
        "name": "ベルコシティホール天満",
        "slug": "osaka-bellco-tenma",
        "venue_type": "private_hall",
        "description": "大阪市北区天満に位置するベルコグループの葬儀会館。JR大阪天満宮駅から徒歩5分。家族葬・一般葬に対応し、清潔感のある式場と充実した設備を備えています。スタッフの対応が丁寧で口コミ評価も高い施設です。",
        "address": "大阪府大阪市北区天満3-4-13",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6920,
        "longitude": 135.5140,
        "nearest_station": "JR東西線 大阪天満宮駅",
        "station_walk_minutes": 5,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "駅近", "ベルコグループ", "宿泊可能"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.1,
        "review_count": 87
    },
    {
        "name": "家族葬のファミーユ 都島ホール",
        "slug": "osaka-famille-miyakojima",
        "venue_type": "private_hall",
        "description": "大阪市都島区にある家族葬専門の葬儀会館。大阪メトロ谷町線都島駅から徒歩6分。10名から50名程度の少人数葬儀に特化し、温かみのあるアットホームな空間で故人を偲ぶ時間を提供します。明朗会計で追加料金の心配がありません。",
        "address": "大阪府大阪市都島区都島本通3-23-15",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7060,
        "longitude": 135.5280,
        "nearest_station": "大阪メトロ谷町線 都島駅",
        "station_walk_minutes": 6,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "駅近", "明朗会計"],
        "operator_name": "株式会社ファミーユ",
        "rating_avg": 4.3,
        "review_count": 102
    },
    {
        "name": "小さなお葬式 大阪北ホール",
        "slug": "osaka-chiisana-kita",
        "venue_type": "private_hall",
        "description": "大阪市北区にある小さなお葬式の提携ホール。全国展開するユニクエストが大阪発祥の地に構える拠点の一つ。火葬式から一般葬まで明朗価格で提供。JR大阪駅から徒歩圏内でアクセス抜群。シンプルながら必要十分な設備を備えています。",
        "address": "大阪府大阪市北区中崎西2-4-12",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7070,
        "longitude": 135.5070,
        "nearest_station": "大阪メトロ谷町線 中崎町駅",
        "station_walk_minutes": 3,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 189000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["火葬式対応", "家族葬対応", "駅近", "明朗会計", "大阪発祥"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 4.0,
        "review_count": 156
    },
    {
        "name": "公益社 北区ホール",
        "slug": "osaka-koeisha-kita",
        "venue_type": "private_hall",
        "description": "大阪市北区にある公益社の会館。梅田エリアからのアクセスが良く、都市型の洗練された空間で葬儀を執り行えます。少人数の家族葬から中規模の一般葬まで柔軟に対応。公益社ならではの手厚いサポートが魅力です。",
        "address": "大阪府大阪市北区豊崎3-15-5",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7110,
        "longitude": 135.5020,
        "nearest_station": "大阪メトロ御堂筋線 中津駅",
        "station_walk_minutes": 5,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "公益社ブランド"],
        "operator_name": "公益社（燦ホールディングス）",
        "rating_avg": 4.3,
        "review_count": 92
    },
    {
        "name": "セレモニーホール福島",
        "slug": "osaka-ceremony-fukushima",
        "venue_type": "private_hall",
        "description": "大阪市福島区にある互助会系の葬儀会館。JR福島駅から徒歩7分。落ち着いた雰囲気の式場で家族葬・一般葬に対応。経験豊富なスタッフが丁寧にサポートし、ご遺族の負担を軽減します。控室や宿泊設備も充実しています。",
        "address": "大阪府大阪市福島区福島5-13-18",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6940,
        "longitude": 135.4870,
        "nearest_station": "JR大阪環状線 福島駅",
        "station_walk_minutes": 7,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "宿泊可能", "互助会系"],
        "operator_name": "セレモニーホール",
        "rating_avg": 4.0,
        "review_count": 65
    },
    {
        "name": "ティア北区",
        "slug": "osaka-tier-kitaku",
        "venue_type": "private_hall",
        "description": "大阪市北区にあるティアの葬儀会館。ティアは名古屋発の葬儀社で、明朗会計と質の高いサービスで全国展開中。大阪メトロ天神橋筋六丁目駅から徒歩4分の好立地。1日1組貸切の家族葬に特化した温かみのある空間です。",
        "address": "大阪府大阪市北区天神橋7-3-2",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7100,
        "longitude": 135.5130,
        "nearest_station": "大阪メトロ谷町線・堺筋線 天神橋筋六丁目駅",
        "station_walk_minutes": 4,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "駅近", "1日1組貸切", "明朗会計"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.2,
        "review_count": 78
    },
    {
        "name": "イオンのお葬式 大阪梅田ホール",
        "slug": "osaka-aeon-umeda",
        "venue_type": "private_hall",
        "description": "大阪市北区にあるイオンライフの提携葬儀会館。イオンブランドの安心感と明朗な価格設定が特徴。火葬式から家族葬まで幅広いプランを用意。JR大阪駅エリアからアクセスしやすく、必要最低限の設備を清潔に整えた施設です。",
        "address": "大阪府大阪市北区芝田1-1-35",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7060,
        "longitude": 135.4980,
        "nearest_station": "JR大阪駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 5,
        "facilities": {"式場": True, "親族控室": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 83000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["火葬式対応", "家族葬対応", "イオンブランド", "明朗会計"],
        "operator_name": "イオンライフ株式会社",
        "rating_avg": 3.9,
        "review_count": 112
    },
    {
        "name": "メモリアルホール都島",
        "slug": "osaka-memorial-miyakojima",
        "venue_type": "private_hall",
        "description": "大阪市都島区にある地域密着型の葬儀会館。京橋エリアからのアクセスが良く、家族葬を中心に地域の方々に愛されています。アットホームな雰囲気の中で、心のこもった葬儀を執り行えます。",
        "address": "大阪府大阪市都島区東野田町4-6-20",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6990,
        "longitude": 135.5350,
        "nearest_station": "JR大阪環状線 京橋駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}],
        "features": ["家族葬対応", "地域密着", "駅近"],
        "operator_name": "メモリアルホール",
        "rating_avg": 4.1,
        "review_count": 54
    },
    {
        "name": "泉屋 梅田ホール",
        "slug": "osaka-izumiya-umeda",
        "venue_type": "private_hall",
        "description": "大阪市北区にある泉屋の葬儀会館。大阪で長年の実績を持つ老舗葬儀社が運営。梅田エリアの便利な立地で、都市型の洗練された葬儀を提供。家族葬から一般葬まで、きめ細やかなサービスが特徴です。",
        "address": "大阪府大阪市北区中津1-11-1",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7080,
        "longitude": 135.4960,
        "nearest_station": "大阪メトロ御堂筋線 中津駅",
        "station_walk_minutes": 4,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "老舗葬儀社", "駅近"],
        "operator_name": "泉屋",
        "rating_avg": 4.2,
        "review_count": 73
    },

    # =============================================
    # 大阪市天王寺区・阿倍野区 (8件)
    # =============================================
    {
        "name": "公益社 天王寺ホール",
        "slug": "osaka-koeisha-tennoji",
        "venue_type": "private_hall",
        "description": "大阪市天王寺区にある公益社の格式高い葬儀会館。JR天王寺駅から徒歩7分の好立地。大小の式場を備え、家族葬から大規模な一般葬まで対応。公益社の高品質なサービスと細やかな心遣いが評判です。",
        "address": "大阪府大阪市天王寺区堂ヶ芝1-3-27",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6550,
        "longitude": 135.5250,
        "nearest_station": "JR大阪環状線 天王寺駅",
        "station_walk_minutes": 7,
        "capacity_max": 120,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True, "僧侶控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "公益社ブランド", "大規模対応"],
        "operator_name": "公益社（燦ホールディングス）",
        "rating_avg": 4.4,
        "review_count": 142
    },
    {
        "name": "ベルコシティホール阿倍野",
        "slug": "osaka-bellco-abeno",
        "venue_type": "private_hall",
        "description": "大阪市阿倍野区にあるベルコの葬儀会館。大阪メトロ御堂筋線昭和町駅から徒歩6分。あべのエリアの落ち着いた住宅街に位置し、家族葬・一般葬に対応。清潔で落ち着いた館内と丁寧なスタッフ対応が好評です。",
        "address": "大阪府大阪市阿倍野区阪南町1-46-7",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6330,
        "longitude": 135.5170,
        "nearest_station": "大阪メトロ御堂筋線 昭和町駅",
        "station_walk_minutes": 6,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "ベルコグループ"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 68
    },
    {
        "name": "家族葬のファミーユ 天王寺ホール",
        "slug": "osaka-famille-tennoji",
        "venue_type": "private_hall",
        "description": "大阪市天王寺区にある家族葬専門ホール。四天王寺にほど近い落ち着いた環境で、少人数の温かいお見送りを提供。明朗会計で安心のプラン設定が特徴です。",
        "address": "大阪府大阪市天王寺区四天王寺1-10-15",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6520,
        "longitude": 135.5180,
        "nearest_station": "大阪メトロ谷町線 四天王寺前夕陽ヶ丘駅",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "駅近", "明朗会計"],
        "operator_name": "株式会社ファミーユ",
        "rating_avg": 4.2,
        "review_count": 88
    },
    {
        "name": "阿倍野セレモニーホール",
        "slug": "osaka-abeno-ceremony",
        "venue_type": "private_hall",
        "description": "大阪市阿倍野区にある地域密着型の葬儀会館。あべの筋沿いの便利な立地で、家族葬から一般葬まで幅広く対応。地元の方々に長年親しまれており、きめ細やかなサービスが特徴の施設です。",
        "address": "大阪府大阪市阿倍野区阿倍野筋4-19-8",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6370,
        "longitude": 135.5150,
        "nearest_station": "大阪メトロ御堂筋線 天王寺駅",
        "station_walk_minutes": 10,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "一般葬対応", "地域密着"],
        "operator_name": "阿倍野セレモニー",
        "rating_avg": 3.9,
        "review_count": 47
    },
    {
        "name": "ティア天王寺",
        "slug": "osaka-tier-tennoji",
        "venue_type": "private_hall",
        "description": "大阪市天王寺区にあるティアの家族葬ホール。天王寺エリアの利便性の高い場所に位置し、1日1組貸切で心ゆくまでお別れの時間を過ごせます。明朗会計と手厚いサポートが魅力です。",
        "address": "大阪府大阪市天王寺区上本町6-2-14",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6600,
        "longitude": 135.5230,
        "nearest_station": "近鉄大阪線 大阪上本町駅",
        "station_walk_minutes": 5,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "1日1組貸切", "駅近", "明朗会計"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.1,
        "review_count": 63
    },
    {
        "name": "天王寺メモリアルホール",
        "slug": "osaka-tennoji-memorial",
        "venue_type": "private_hall",
        "description": "大阪市天王寺区の寺町エリアに位置する葬儀会館。数多くの寺院が集まる歴史ある地域で、伝統的な葬儀から現代的な家族葬まで幅広く対応しています。",
        "address": "大阪府大阪市天王寺区下寺町1-3-62",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6580,
        "longitude": 135.5120,
        "nearest_station": "大阪メトロ谷町線 四天王寺前夕陽ヶ丘駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "一般葬対応", "寺町エリア"],
        "operator_name": "天王寺メモリアル",
        "rating_avg": 3.8,
        "review_count": 39
    },
    {
        "name": "四天王寺前 花の葬儀場",
        "slug": "osaka-shitennoji-hana",
        "venue_type": "temple_hall",
        "description": "大阪市天王寺区の四天王寺門前に位置する寺院式場。四天王寺の荘厳な雰囲気の中で、伝統的な仏式葬儀を執り行えます。僧侶の手配も含めたトータルサポートが特徴です。",
        "address": "大阪府大阪市天王寺区四天王寺2-3-8",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6530,
        "longitude": 135.5190,
        "nearest_station": "大阪メトロ谷町線 四天王寺前夕陽ヶ丘駅",
        "station_walk_minutes": 3,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 5,
        "facilities": {"式場": True, "控室": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["寺院式場", "仏式葬儀", "駅近", "四天王寺"],
        "operator_name": "四天王寺",
        "rating_avg": 4.0,
        "review_count": 42
    },
    {
        "name": "公益社 阿倍野ホール",
        "slug": "osaka-koeisha-abeno",
        "venue_type": "private_hall",
        "description": "大阪市阿倍野区にある公益社の葬儀会館。あべのハルカスにも近い都市部に位置し、交通アクセス良好。格式ある式場で家族葬・一般葬に対応。公益社ならではの安定したサービス品質が魅力です。",
        "address": "大阪府大阪市阿倍野区旭町1-4-16",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6460,
        "longitude": 135.5140,
        "nearest_station": "JR大阪環状線 天王寺駅",
        "station_walk_minutes": 5,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "公益社ブランド"],
        "operator_name": "公益社（燦ホールディングス）",
        "rating_avg": 4.3,
        "review_count": 98
    },

    # =============================================
    # 大阪市住吉区・東住吉区・住之江区 (8件)
    # =============================================
    {
        "name": "ベルコシティホール住吉",
        "slug": "osaka-bellco-sumiyoshi",
        "venue_type": "private_hall",
        "description": "大阪市住吉区にあるベルコの葬儀会館。南海高野線住吉東駅から徒歩5分。住吉大社にも近い閑静な住宅街に立地し、家族葬から一般葬まで対応。地域に根差した丁寧なサービスが特徴です。",
        "address": "大阪府大阪市住吉区住吉2-3-8",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6110,
        "longitude": 135.4940,
        "nearest_station": "南海高野線 住吉東駅",
        "station_walk_minutes": 5,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "駅近", "ベルコグループ", "地域密着"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 56
    },
    {
        "name": "家族葬のファミーユ 東住吉ホール",
        "slug": "osaka-famille-higashisumiyoshi",
        "venue_type": "private_hall",
        "description": "大阪市東住吉区にある家族葬専門ホール。近鉄南大阪線矢田駅から徒歩8分。少人数のお葬式に特化し、温かみのある空間で故人を偲ぶことができます。駐車場完備で車でのアクセスも便利です。",
        "address": "大阪府大阪市東住吉区矢田3-14-7",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6180,
        "longitude": 135.5350,
        "nearest_station": "近鉄南大阪線 矢田駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "駐車場完備"],
        "operator_name": "株式会社ファミーユ",
        "rating_avg": 4.1,
        "review_count": 52
    },
    {
        "name": "住之江メモリアルホール",
        "slug": "osaka-suminoe-memorial",
        "venue_type": "private_hall",
        "description": "大阪市住之江区にある葬儀会館。ニュートラム住之江公園駅から徒歩10分。住之江エリアの葬儀需要に応える地域密着型の施設で、家族葬を中心に対応しています。",
        "address": "大阪府大阪市住之江区御崎3-8-15",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6170,
        "longitude": 135.4700,
        "nearest_station": "ニュートラム 住之江公園駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬対応", "地域密着", "駐車場完備"],
        "operator_name": "住之江メモリアル",
        "rating_avg": 3.8,
        "review_count": 34
    },
    {
        "name": "小さなお葬式 住吉ホール",
        "slug": "osaka-chiisana-sumiyoshi",
        "venue_type": "private_hall",
        "description": "大阪市住吉区にある小さなお葬式の提携ホール。シンプルで明朗な価格設定が特徴。火葬式・一日葬・家族葬に対応し、必要なサービスを適正価格で提供しています。",
        "address": "大阪府大阪市住吉区長居東4-1-18",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6090,
        "longitude": 135.5210,
        "nearest_station": "JR阪和線 長居駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 189000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["火葬式対応", "家族葬対応", "明朗会計"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 3.9,
        "review_count": 71
    },
    {
        "name": "東住吉やすらぎホール",
        "slug": "osaka-higashisumiyoshi-yasuragi",
        "venue_type": "private_hall",
        "description": "大阪市東住吉区にある地域密着型の葬儀会館。近鉄南大阪線針中野駅から徒歩7分。落ち着いた住宅街に位置し、家族葬・一般葬に対応。地元の方々に長年信頼されている施設です。",
        "address": "大阪府大阪市東住吉区駒川4-6-12",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6240,
        "longitude": 135.5310,
        "nearest_station": "近鉄南大阪線 針中野駅",
        "station_walk_minutes": 7,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "地域密着"],
        "operator_name": "やすらぎホール",
        "rating_avg": 4.0,
        "review_count": 44
    },
    {
        "name": "公益社 住吉ホール",
        "slug": "osaka-koeisha-sumiyoshi",
        "venue_type": "private_hall",
        "description": "大阪市住吉区にある公益社の葬儀会館。住吉大社エリアに位置し、格式ある葬儀を執り行えます。家族葬から一般葬まで対応し、公益社の確かなサービスを提供しています。",
        "address": "大阪府大阪市住吉区帝塚山中3-5-12",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6150,
        "longitude": 135.4980,
        "nearest_station": "南海高野線 帝塚山駅",
        "station_walk_minutes": 4,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "公益社ブランド"],
        "operator_name": "公益社（燦ホールディングス）",
        "rating_avg": 4.3,
        "review_count": 76
    },
    {
        "name": "ティア住之江",
        "slug": "osaka-tier-suminoe",
        "venue_type": "private_hall",
        "description": "大阪市住之江区にあるティアの葬儀会館。住之江エリアの閑静な場所に位置し、1日1組貸切の家族葬に対応。明朗会計のプラン設定と温かみのあるスタッフ対応が好評です。",
        "address": "大阪府大阪市住之江区安立4-2-8",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6060,
        "longitude": 135.4830,
        "nearest_station": "阪堺電車 安立町停留場",
        "station_walk_minutes": 3,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "1日1組貸切", "駅近", "明朗会計"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.1,
        "review_count": 48
    },
    {
        "name": "住吉会館",
        "slug": "osaka-sumiyoshi-kaikan",
        "venue_type": "public_facility",
        "description": "大阪市住吉区にある公共施設の一室を葬儀に利用できる施設。使用料が安く、地域の方々に利用されています。住吉大社近くの落ち着いた環境です。",
        "address": "大阪府大阪市住吉区長居西1-5-20",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6120,
        "longitude": 135.5060,
        "nearest_station": "JR阪和線 長居駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "控室": True, "駐車場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 250000}],
        "features": ["公共施設", "低価格", "地域密着"],
        "operator_name": "大阪市",
        "rating_avg": 3.5,
        "review_count": 18
    },

    # =============================================
    # 大阪市平野区・生野区 (6件)
    # =============================================
    {
        "name": "ベルコシティホール平野",
        "slug": "osaka-bellco-hirano",
        "venue_type": "private_hall",
        "description": "大阪市平野区にあるベルコの葬儀会館。大阪メトロ谷町線平野駅から徒歩7分。大阪市南東部エリアの葬儀需要に対応し、家族葬・一般葬ともに充実した設備で執り行えます。",
        "address": "大阪府大阪市平野区平野東1-8-26",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6130,
        "longitude": 135.5640,
        "nearest_station": "大阪メトロ谷町線 平野駅",
        "station_walk_minutes": 7,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "ベルコグループ"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 58
    },
    {
        "name": "平野メモリアルホール",
        "slug": "osaka-hirano-memorial",
        "venue_type": "private_hall",
        "description": "大阪市平野区にある地域密着型の葬儀会館。瓜破斎場にもほど近い場所に位置し、通夜・葬儀から火葬場への移動もスムーズ。家族葬を中心に地域の方々に利用されています。",
        "address": "大阪府大阪市平野区瓜破2-1-13",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6080,
        "longitude": 135.5530,
        "nearest_station": "大阪メトロ谷町線 喜連瓜破駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}],
        "features": ["家族葬対応", "瓜破斎場近く", "地域密着"],
        "operator_name": "平野メモリアル",
        "rating_avg": 3.9,
        "review_count": 37
    },
    {
        "name": "家族葬のファミーユ 生野ホール",
        "slug": "osaka-famille-ikuno",
        "venue_type": "private_hall",
        "description": "大阪市生野区にある家族葬専門ホール。JR大阪環状線桃谷駅から徒歩10分。コリアンタウンにも近い多文化な地域で、様々な文化・宗教に対応した葬儀を提供しています。",
        "address": "大阪府大阪市生野区桃谷3-5-17",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6510,
        "longitude": 135.5350,
        "nearest_station": "JR大阪環状線 桃谷駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "多文化対応"],
        "operator_name": "株式会社ファミーユ",
        "rating_avg": 4.0,
        "review_count": 45
    },
    {
        "name": "生野セレモニーホール",
        "slug": "osaka-ikuno-ceremony",
        "venue_type": "private_hall",
        "description": "大阪市生野区にある地域密着型の葬儀会館。大阪メトロ千日前線小路駅から徒歩6分。家族葬から一般葬まで対応し、地域の方々に長年親しまれています。",
        "address": "大阪府大阪市生野区小路東3-7-22",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6570,
        "longitude": 135.5490,
        "nearest_station": "大阪メトロ千日前線 小路駅",
        "station_walk_minutes": 6,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "地域密着"],
        "operator_name": "生野セレモニー",
        "rating_avg": 3.8,
        "review_count": 32
    },
    {
        "name": "公益社 平野ホール",
        "slug": "osaka-koeisha-hirano",
        "venue_type": "private_hall",
        "description": "大阪市平野区にある公益社の葬儀会館。大阪市最大の人口を抱える平野区で、家族葬から一般葬まで幅広く対応。公益社の確かなサービスと安心のサポート体制が魅力です。",
        "address": "大阪府大阪市平野区平野西5-1-8",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6200,
        "longitude": 135.5510,
        "nearest_station": "大阪メトロ谷町線 平野駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "一般葬対応", "公益社ブランド"],
        "operator_name": "公益社（燦ホールディングス）",
        "rating_avg": 4.2,
        "review_count": 67
    },
    {
        "name": "ティア平野",
        "slug": "osaka-tier-hirano",
        "venue_type": "private_hall",
        "description": "大阪市平野区にあるティアの家族葬ホール。1日1組貸切で、ゆったりとしたお別れの時間を過ごせます。明朗会計で追加料金の心配がなく、安心して利用できます。",
        "address": "大阪府大阪市平野区長吉長原2-8-6",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.5980,
        "longitude": 135.5620,
        "nearest_station": "大阪メトロ谷町線 長原駅",
        "station_walk_minutes": 6,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "1日1組貸切", "駅近", "明朗会計"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.1,
        "review_count": 42
    },

    # =============================================
    # 大阪市城東区・鶴見区・旭区 (6件)
    # =============================================
    {
        "name": "ベルコシティホール城東",
        "slug": "osaka-bellco-joto",
        "venue_type": "private_hall",
        "description": "大阪市城東区にあるベルコの葬儀会館。大阪メトロ長堀鶴見緑地線蒲生四丁目駅から徒歩6分。家族葬・一般葬に対応した清潔感のある施設です。",
        "address": "大阪府大阪市城東区蒲生3-15-20",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6940,
        "longitude": 135.5460,
        "nearest_station": "大阪メトロ長堀鶴見緑地線 蒲生四丁目駅",
        "station_walk_minutes": 6,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "ベルコグループ"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 52
    },
    {
        "name": "家族葬のファミーユ 鶴見ホール",
        "slug": "osaka-famille-tsurumi",
        "venue_type": "private_hall",
        "description": "大阪市鶴見区にある家族葬専門ホール。大阪メトロ長堀鶴見緑地線今福鶴見駅から徒歩8分。鶴見緑地にも近い緑豊かなエリアで、温かなお見送りを提供しています。",
        "address": "大阪府大阪市鶴見区鶴見3-6-18",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7000,
        "longitude": 135.5720,
        "nearest_station": "大阪メトロ長堀鶴見緑地線 今福鶴見駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "駐車場完備"],
        "operator_name": "株式会社ファミーユ",
        "rating_avg": 4.2,
        "review_count": 48
    },
    {
        "name": "旭区セレモニーホール",
        "slug": "osaka-asahi-ceremony",
        "venue_type": "private_hall",
        "description": "大阪市旭区にある地域密着型の葬儀会館。大阪メトロ谷町線千林大宮駅から徒歩5分。古くから商店街で賑わう地域で、地元の方々に親しまれている施設です。",
        "address": "大阪府大阪市旭区千林2-12-5",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7200,
        "longitude": 135.5480,
        "nearest_station": "大阪メトロ谷町線 千林大宮駅",
        "station_walk_minutes": 5,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 530000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "地域密着"],
        "operator_name": "旭セレモニー",
        "rating_avg": 3.9,
        "review_count": 35
    },
    {
        "name": "城東やすらぎホール",
        "slug": "osaka-joto-yasuragi",
        "venue_type": "private_hall",
        "description": "大阪市城東区にある家族葬対応のホール。城東区の住宅街に位置し、落ち着いた環境でお別れの時間を過ごせます。少人数から中規模の葬儀まで柔軟に対応しています。",
        "address": "大阪府大阪市城東区関目5-14-8",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7080,
        "longitude": 135.5550,
        "nearest_station": "京阪本線 関目駅",
        "station_walk_minutes": 5,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "駅近", "少人数対応"],
        "operator_name": "やすらぎホール",
        "rating_avg": 3.8,
        "review_count": 29
    },
    {
        "name": "ティア城東",
        "slug": "osaka-tier-joto",
        "venue_type": "private_hall",
        "description": "大阪市城東区にあるティアの葬儀会館。京橋エリアからもアクセスしやすい立地。1日1組貸切の家族葬対応で、明朗会計が安心のポイントです。",
        "address": "大阪府大阪市城東区今福東2-7-15",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6960,
        "longitude": 135.5580,
        "nearest_station": "大阪メトロ長堀鶴見緑地線 今福鶴見駅",
        "station_walk_minutes": 7,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "1日1組貸切", "明朗会計"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.0,
        "review_count": 38
    },
    {
        "name": "鶴見メモリアルホール",
        "slug": "osaka-tsurumi-memorial",
        "venue_type": "private_hall",
        "description": "大阪市鶴見区にある葬儀会館。鶴見緑地公園に近い緑豊かなエリアに位置。家族葬を中心に、温かみのある葬儀を提供しています。駐車場完備で車でのアクセスも便利。",
        "address": "大阪府大阪市鶴見区諸口5-2-11",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7060,
        "longitude": 135.5830,
        "nearest_station": "大阪メトロ長堀鶴見緑地線 横堤駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬対応", "駐車場完備", "緑豊かなエリア"],
        "operator_name": "鶴見メモリアル",
        "rating_avg": 3.9,
        "review_count": 31
    },

    # =============================================
    # 大阪市淀川区・東淀川区・西淀川区 (7件)
    # =============================================
    {
        "name": "公益社 淀川ホール",
        "slug": "osaka-koeisha-yodogawa",
        "venue_type": "private_hall",
        "description": "大阪市淀川区にある公益社の葬儀会館。新大阪駅からも近い利便性の高い立地。出張や遠方からの参列者にも便利で、家族葬から一般葬まで幅広く対応しています。",
        "address": "大阪府大阪市淀川区西中島4-3-15",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7230,
        "longitude": 135.5000,
        "nearest_station": "大阪メトロ御堂筋線 西中島南方駅",
        "station_walk_minutes": 5,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "一般葬対応", "新大阪近く", "公益社ブランド"],
        "operator_name": "公益社（燦ホールディングス）",
        "rating_avg": 4.3,
        "review_count": 89
    },
    {
        "name": "ベルコシティホール淀川",
        "slug": "osaka-bellco-yodogawa",
        "venue_type": "private_hall",
        "description": "大阪市淀川区にあるベルコの葬儀会館。阪急十三駅から徒歩8分。大阪キタエリアの北側で、家族葬・一般葬に対応した充実の設備を備えています。",
        "address": "大阪府大阪市淀川区十三本町2-5-8",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7190,
        "longitude": 135.4810,
        "nearest_station": "阪急各線 十三駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "ベルコグループ"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 55
    },
    {
        "name": "東淀川メモリアルホール",
        "slug": "osaka-higashiyodogawa-memorial",
        "venue_type": "private_hall",
        "description": "大阪市東淀川区にある葬儀会館。阪急京都線上新庄駅から徒歩6分。東淀川エリアの住宅街に位置し、家族葬を中心に地域の方々に利用されている施設です。",
        "address": "大阪府大阪市東淀川区上新庄2-24-15",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7360,
        "longitude": 135.5330,
        "nearest_station": "阪急京都線 上新庄駅",
        "station_walk_minutes": 6,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}],
        "features": ["家族葬対応", "駅近", "地域密着"],
        "operator_name": "東淀川メモリアル",
        "rating_avg": 3.9,
        "review_count": 38
    },
    {
        "name": "家族葬のファミーユ 淀川ホール",
        "slug": "osaka-famille-yodogawa",
        "venue_type": "private_hall",
        "description": "大阪市淀川区にある家族葬専門ホール。新大阪エリアからのアクセスも良く、少人数のお葬式に特化した温かみのある空間です。明朗会計で安心のプラン設定。",
        "address": "大阪府大阪市淀川区木川東3-8-5",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7180,
        "longitude": 135.4920,
        "nearest_station": "JR東海道本線 新大阪駅",
        "station_walk_minutes": 12,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "明朗会計"],
        "operator_name": "株式会社ファミーユ",
        "rating_avg": 4.1,
        "review_count": 52
    },
    {
        "name": "西淀川セレモニーホール",
        "slug": "osaka-nishiyodogawa-ceremony",
        "venue_type": "private_hall",
        "description": "大阪市西淀川区にある葬儀会館。JR東西線御幣島駅から徒歩7分。佃斎場にも近い立地で、通夜から火葬場への移動がスムーズです。家族葬・一般葬に対応しています。",
        "address": "大阪府大阪市西淀川区御幣島3-8-12",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7120,
        "longitude": 135.4580,
        "nearest_station": "JR東西線 御幣島駅",
        "station_walk_minutes": 7,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 315000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 540000}],
        "features": ["家族葬対応", "一般葬対応", "佃斎場近く", "駅近"],
        "operator_name": "西淀川セレモニー",
        "rating_avg": 3.8,
        "review_count": 33
    },
    {
        "name": "ティア東淀川",
        "slug": "osaka-tier-higashiyodogawa",
        "venue_type": "private_hall",
        "description": "大阪市東淀川区にあるティアの家族葬ホール。阪急淡路駅からも近い場所に位置し、1日1組貸切のゆったりとした空間で家族葬を執り行えます。",
        "address": "大阪府大阪市東淀川区淡路3-12-8",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7400,
        "longitude": 135.5200,
        "nearest_station": "阪急京都線 淡路駅",
        "station_walk_minutes": 5,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "1日1組貸切", "駅近", "明朗会計"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.1,
        "review_count": 41
    },
    {
        "name": "東淀川区民ホール",
        "slug": "osaka-higashiyodogawa-kumin",
        "venue_type": "public_facility",
        "description": "大阪市東淀川区にある公共施設。区民向けに低価格で利用できる多目的ホールで、小規模な家族葬・お別れの会にも対応しています。",
        "address": "大阪府大阪市東淀川区東淡路1-4-53",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7380,
        "longitude": 135.5280,
        "nearest_station": "阪急京都線 淡路駅",
        "station_walk_minutes": 8,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "控室": True, "駐車場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 220000}],
        "features": ["公共施設", "低価格", "少人数対応"],
        "operator_name": "大阪市",
        "rating_avg": 3.5,
        "review_count": 15
    },
]

# 10件ずつバッチ投入
total = len(venues)
print(f"大阪市 バッチ1: 合計 {total} 件を投入開始")

for i in range(0, total, 10):
    batch = venues[i:i+10]
    status = insert_batch(batch)
    end = min(i+10, total)
    print(f"  [{i+1}-{end}] HTTP {status}")
    if status != "201":
        # エラー時は詳細を表示
        data_json = json.dumps(batch, ensure_ascii=False)
        result = subprocess.run([
            "curl", "-s",
            "-X", "POST", SUPABASE_URL,
            "-H", f"apikey: {API_KEY}",
            "-H", f"Authorization: Bearer {API_KEY}",
            "-H", "Content-Type: application/json",
            "-H", "Prefer: return=minimal",
            "-H", "User-Agent: Mozilla/5.0",
            "-d", data_json
        ], capture_output=True, text=True)
        print(f"  エラー詳細: {result.stdout[:500]}")
    time.sleep(0.5)

print(f"\nバッチ1完了: {total}件")
