#!/usr/bin/env python3
"""
新潟県の斎場データ（追加分40件）をSupabase REST APIに投入するスクリプト
"""

import json
import urllib.request
import urllib.error
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

HEADERS = {
    "apikey": API_KEY,
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal",
}

venues = [
    # =============================================
    # 新潟市 追加10件
    # =============================================
    {
        "name": "新潟市新津斎場",
        "slug": "niigata-niitsu-saijo",
        "venue_type": "public_crematorium",
        "description": "新潟市秋葉区にある公営火葬場。新津駅から車で約7分の立地です。新潟市民は火葬料無料で利用可能。落ち着いた環境の中で故人をお見送りできます。待合室や控室も完備しており、火葬式にも対応しています。",
        "address": "新潟県新潟市秋葉区古田ノ内大野開33-4",
        "prefecture_slug": "niigata", "city_slug": "niigata-city",
        "latitude": 37.797, "longitude": 139.119,
        "nearest_station": "JR信越本線 新津駅", "station_walk_minutes": 20,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": True, "parking_count": 25,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}],
        "features": ["火葬場併設", "公営斎場", "家族葬対応", "バリアフリー"],
        "operator_name": "新潟市", "rating_avg": 3.7, "review_count": 22,
    },
    {
        "name": "新潟市白根斎場",
        "slug": "niigata-shirone-saijo",
        "venue_type": "public_crematorium",
        "description": "新潟市南区にある公営斎場。白根地域の方を中心に利用されています。火葬炉を備え、新潟市民は火葬料無料。静かな田園地帯に位置し、穏やかな雰囲気の中で故人を見送れます。",
        "address": "新潟県新潟市南区鍋潟638-1",
        "prefecture_slug": "niigata", "city_slug": "niigata-city",
        "latitude": 37.784, "longitude": 139.023,
        "nearest_station": "JR信越本線 矢代田駅", "station_walk_minutes": 30,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 20,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}],
        "features": ["火葬場併設", "公営斎場", "バリアフリー"],
        "operator_name": "新潟市", "rating_avg": 3.6, "review_count": 15,
    },
    {
        "name": "巻斎場",
        "slug": "niigata-maki-saijo",
        "venue_type": "public_crematorium",
        "description": "新潟市西蒲区にある公営火葬場。岩室駅から車で約5分のアクセス。新潟市民は火葬料無料で利用できます。西蒲区の方を中心に利用されており、周囲は自然に囲まれた静かな環境です。",
        "address": "新潟県新潟市西蒲区和納5770",
        "prefecture_slug": "niigata", "city_slug": "niigata-city",
        "latitude": 37.785, "longitude": 138.917,
        "nearest_station": "JR越後線 岩室駅", "station_walk_minutes": 15,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": True, "parking_count": 15,
        "facilities": {"霊安室": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "新潟市", "rating_avg": 3.5, "review_count": 12,
    },
    {
        "name": "セレモニーホール亀田",
        "slug": "ceremony-hall-kameda",
        "venue_type": "private_hall",
        "description": "アークベルが運営する新潟市江南区の葬儀会館。JR亀田駅から徒歩3分と抜群のアクセスが特長です。家族葬から一般葬まで対応可能で、温かみのある内装が好評。駐車場も完備しています。",
        "address": "新潟県新潟市江南区東船場2-1-23",
        "prefecture_slug": "niigata", "city_slug": "niigata-city",
        "latitude": 37.885, "longitude": 139.109,
        "nearest_station": "JR信越本線 亀田駅", "station_walk_minutes": 3,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 265000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 565000}],
        "features": ["駅近", "家族葬対応", "宿泊可能", "駐車場完備", "バリアフリー"],
        "operator_name": "株式会社アークベル", "rating_avg": 4.2, "review_count": 35,
    },
    {
        "name": "VIPシティホール青山",
        "slug": "vip-city-hall-aoyama",
        "venue_type": "private_hall",
        "description": "新潟市西区の民間葬儀会館。JR青山駅から徒歩5分の好立地。家族葬から大規模な一般葬まで幅広く対応。火葬場に近い便利な立地で、清潔感のある館内と丁寧なスタッフの対応が評判です。",
        "address": "新潟県新潟市西区浦山2-3-7",
        "prefecture_slug": "niigata", "city_slug": "niigata-city",
        "latitude": 37.890, "longitude": 138.997,
        "nearest_station": "JR越後線 青山駅", "station_walk_minutes": 5,
        "capacity_max": 100, "hall_count": 2, "has_crematorium": False, "parking_count": 60,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 115000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 275000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 395000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["駅近", "火葬場近隣", "家族葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "株式会社VIPシティホール", "rating_avg": 4.1, "review_count": 28,
    },
    {
        "name": "新津セレモニーホール",
        "slug": "niitsu-ceremony-hall",
        "venue_type": "private_hall",
        "description": "アークベルが運営する新潟市秋葉区のセレモニーホール。新津地区を中心にご利用いただいています。家族葬にも対応した小規模ホールを備え、地域に密着した温かいサービスを提供しています。",
        "address": "新潟県新潟市秋葉区新津4550-1",
        "prefecture_slug": "niigata", "city_slug": "niigata-city",
        "latitude": 37.800, "longitude": 139.120,
        "nearest_station": "JR信越本線 新津駅", "station_walk_minutes": 10,
        "capacity_max": 60, "hall_count": 2, "has_crematorium": False, "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000}],
        "features": ["家族葬対応", "宿泊可能", "駐車場完備", "バリアフリー"],
        "operator_name": "株式会社アークベル", "rating_avg": 4.0, "review_count": 25,
    },
    {
        "name": "家族葬のダビアス新潟東",
        "slug": "davius-niigata-higashi",
        "venue_type": "private_hall",
        "description": "新潟市東区にある家族葬専用ホール。少人数での温かいお別れの場を提供します。1日1組完全貸切で、リビングのような落ち着いた空間。24時間365日相談可能で、急なご依頼にも対応しています。",
        "address": "新潟県新潟市東区中山7-23-15",
        "prefecture_slug": "niigata", "city_slug": "niigata-city",
        "latitude": 37.925, "longitude": 139.082,
        "nearest_station": "JR白新線 東新潟駅", "station_walk_minutes": 15,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}],
        "features": ["家族葬専用", "1日1組貸切", "24時間対応", "バリアフリー"],
        "operator_name": "株式会社ダビアス新潟", "rating_avg": 4.4, "review_count": 20,
    },
    {
        "name": "サラきたまち",
        "slug": "sala-kitamachi-niigata",
        "venue_type": "private_hall",
        "description": "新潟市北区にある家族葬向けの葬儀ホール。「サラ」ブランドとして新潟市内に展開する施設の一つ。少人数から中規模の葬儀に対応し、モダンで温かみのある空間が特長。駐車場も十分に確保されています。",
        "address": "新潟県新潟市北区木崎880-1",
        "prefecture_slug": "niigata", "city_slug": "niigata-city",
        "latitude": 37.942, "longitude": 139.069,
        "nearest_station": "JR白新線 豊栄駅", "station_walk_minutes": 15,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 355000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "駐車場完備", "バリアフリー"],
        "operator_name": "株式会社サラ", "rating_avg": 4.1, "review_count": 18,
    },
    {
        "name": "小さなお葬式 新潟西ホール",
        "slug": "chiisana-ososhiki-niigata-nishi",
        "venue_type": "private_hall",
        "description": "全国展開の「小さなお葬式」提携ホール。新潟市西区に位置し、低価格ながら質の高いサービスを提供。火葬式から家族葬まで明朗会計のプランが揃い、追加料金なしの安心感が好評です。",
        "address": "新潟県新潟市西区小針8-14-1",
        "prefecture_slug": "niigata", "city_slug": "niigata-city",
        "latitude": 37.897, "longitude": 138.985,
        "nearest_station": "JR越後線 小針駅", "station_walk_minutes": 10,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬対応", "低価格", "明朗会計", "バリアフリー"],
        "operator_name": "株式会社ユニクエスト", "rating_avg": 4.0, "review_count": 15,
    },
    {
        "name": "メモリアルホール新潟中央",
        "slug": "memorial-hall-niigata-chuo",
        "venue_type": "private_hall",
        "description": "新潟市中央区の総合葬儀会館。中央区の中心部に位置し、アクセスの良さが魅力です。100名規模の大ホールから少人数向けの和室まで多彩な式場を備え、通夜から告別式まで一貫して対応。バリアフリー設計で車椅子の方も安心です。",
        "address": "新潟県新潟市中央区関屋大川前2-1-15",
        "prefecture_slug": "niigata", "city_slug": "niigata-city",
        "latitude": 37.910, "longitude": 139.028,
        "nearest_station": "JR越後線 関屋駅", "station_walk_minutes": 8,
        "capacity_max": 100, "hall_count": 3, "has_crematorium": False, "parking_count": 45,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 115000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 270000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 568000}],
        "features": ["駅近", "大規模葬対応", "家族葬対応", "宿泊可能", "駐車場完備", "バリアフリー"],
        "operator_name": "メモリアルホール株式会社", "rating_avg": 4.2, "review_count": 30,
    },

    # =============================================
    # 長岡市 追加6件
    # =============================================
    {
        "name": "セレモニーホール四郎丸",
        "slug": "ceremony-hall-shiromaru-nagaoka",
        "venue_type": "private_hall",
        "description": "アークベルが運営する長岡市四郎丸のセレモニーホール。メモリアルルームを備え、少人数の家族葬にも対応。長岡市内でも利便性の高い立地で、通夜から告別式まで一貫してサポートします。",
        "address": "新潟県長岡市四郎丸1-5-35",
        "prefecture_slug": "niigata", "city_slug": "nagaoka",
        "latitude": 37.434, "longitude": 138.863,
        "nearest_station": "JR上越線 宮内駅", "station_walk_minutes": 10,
        "capacity_max": 60, "hall_count": 2, "has_crematorium": False, "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000}],
        "features": ["家族葬対応", "宿泊可能", "駐車場完備", "バリアフリー"],
        "operator_name": "株式会社アークベル", "rating_avg": 4.1, "review_count": 25,
    },
    {
        "name": "セレモニーホール長岡会堂",
        "slug": "ceremony-hall-nagaoka-kaido",
        "venue_type": "private_hall",
        "description": "長岡市南町にあるアークベルの大規模セレモニーホール。JR長岡駅から徒歩圏内の好立地。大ホールと小ホールを備え、大規模な一般葬から少人数の家族葬まで幅広く対応。充実した設備と丁寧なサービスが評判です。",
        "address": "新潟県長岡市南町1-1-11",
        "prefecture_slug": "niigata", "city_slug": "nagaoka",
        "latitude": 37.440, "longitude": 138.852,
        "nearest_station": "JR上越新幹線 長岡駅", "station_walk_minutes": 12,
        "capacity_max": 120, "hall_count": 3, "has_crematorium": False, "parking_count": 60,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 112000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 578000}],
        "features": ["駅近", "大規模葬対応", "家族葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "株式会社アークベル", "rating_avg": 4.3, "review_count": 40,
    },
    {
        "name": "ラソ平安",
        "slug": "raso-heian-nagaoka",
        "venue_type": "private_hall",
        "description": "長岡市西神田町にある家族葬専用ホール。アークベルが展開する「ラソ」ブランドの施設で、少人数でゆっくりとお別れできる空間を提供。リビングルームのような温かみのある内装が特長です。",
        "address": "新潟県長岡市西神田町1-7-4",
        "prefecture_slug": "niigata", "city_slug": "nagaoka",
        "latitude": 37.448, "longitude": 138.848,
        "nearest_station": "JR上越新幹線 長岡駅", "station_walk_minutes": 15,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}],
        "features": ["家族葬専用", "1日1組貸切", "駐車場完備", "バリアフリー"],
        "operator_name": "株式会社アークベル", "rating_avg": 4.4, "review_count": 22,
    },
    {
        "name": "喜多町ホール",
        "slug": "kitamachi-hall-nagaoka",
        "venue_type": "private_hall",
        "description": "長岡市喜多町にある総合葬儀会館。VIPシティホールグループの施設で、大規模な一般葬から家族葬まで対応可能。FUNERAL HOUSE想やサラきたまちなど多彩なホールを併設し、ご要望に合わせた空間を選べます。",
        "address": "新潟県長岡市喜多町1162-1",
        "prefecture_slug": "niigata", "city_slug": "nagaoka",
        "latitude": 37.468, "longitude": 138.866,
        "nearest_station": "JR信越本線 北長岡駅", "station_walk_minutes": 12,
        "capacity_max": 150, "hall_count": 4, "has_crematorium": False, "parking_count": 80,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 118000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 278000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["大規模葬対応", "家族葬対応", "宿泊可能", "駐車場完備", "バリアフリー"],
        "operator_name": "株式会社VIPシティホール", "rating_avg": 4.2, "review_count": 35,
    },
    {
        "name": "VIPシティホール大島",
        "slug": "vip-city-hall-oshima-nagaoka",
        "venue_type": "private_hall",
        "description": "長岡市大島新町にある民間葬儀会館。VIPシティホールグループとして長岡市内に複数展開する施設の一つ。家族葬から一般葬まで幅広く対応し、明るく清潔な館内が特長です。",
        "address": "新潟県長岡市大島新町4-1-8",
        "prefecture_slug": "niigata", "city_slug": "nagaoka",
        "latitude": 37.444, "longitude": 138.880,
        "nearest_station": "JR信越本線 長岡駅", "station_walk_minutes": 20,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 265000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["家族葬対応", "宿泊可能", "駐車場完備", "バリアフリー"],
        "operator_name": "株式会社VIPシティホール", "rating_avg": 4.0, "review_count": 20,
    },
    {
        "name": "セレモニーホール蔵王",
        "slug": "ceremony-hall-zao-nagaoka",
        "venue_type": "private_hall",
        "description": "長岡市東蔵王にあるアークベルのセレモニーホール。長岡市東部エリアを中心にサービスを提供。落ち着いた雰囲気の中で、家族葬から一般葬までご要望に合わせた式を執り行えます。",
        "address": "新潟県長岡市東蔵王2-4-3",
        "prefecture_slug": "niigata", "city_slug": "nagaoka",
        "latitude": 37.454, "longitude": 138.876,
        "nearest_station": "JR信越本線 長岡駅", "station_walk_minutes": 18,
        "capacity_max": 70, "hall_count": 2, "has_crematorium": False, "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 260000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 375000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["家族葬対応", "宿泊可能", "駐車場完備", "バリアフリー"],
        "operator_name": "株式会社アークベル", "rating_avg": 4.0, "review_count": 22,
    },

    # =============================================
    # 上越市 追加4件
    # =============================================
    {
        "name": "上越斎場",
        "slug": "joetsu-saijo",
        "venue_type": "public_crematorium",
        "description": "上越市が運営する公営斎場。上越市大字居多に位置し、火葬施設と式場を備えています。上越市民は火葬料が優遇されます。日本海を望む高台に立地し、静かな環境の中で故人を見送れます。",
        "address": "新潟県上越市大字居多776",
        "prefecture_slug": "niigata", "city_slug": "joetsu",
        "latitude": 37.105, "longitude": 138.223,
        "nearest_station": "えちごトキめき鉄道 直江津駅", "station_walk_minutes": 20,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": True, "parking_count": 50,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 345000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 510000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応", "バリアフリー"],
        "operator_name": "上越市", "rating_avg": 3.8, "review_count": 30,
    },
    {
        "name": "セレモニーホール上越",
        "slug": "ceremony-hall-joetsu",
        "venue_type": "private_hall",
        "description": "上越市の大型民間葬儀会館。JR高田駅からのアクセスが良く、大規模な葬儀にも対応可能。上越地域で長年の実績を持ち、地域に密着したきめ細かいサービスを提供しています。",
        "address": "新潟県上越市西城町3-5-12",
        "prefecture_slug": "niigata", "city_slug": "joetsu",
        "latitude": 37.100, "longitude": 138.237,
        "nearest_station": "えちごトキめき鉄道 高田駅", "station_walk_minutes": 10,
        "capacity_max": 100, "hall_count": 2, "has_crematorium": False, "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 262000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}],
        "features": ["駅近", "大規模葬対応", "家族葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "上越セレモニー株式会社", "rating_avg": 4.1, "review_count": 28,
    },
    {
        "name": "家族葬のウィズハウス上越",
        "slug": "with-house-joetsu",
        "venue_type": "private_hall",
        "description": "上越市にある家族葬専用ホール。ウィズハウスブランドとして展開する邸宅型の葬儀場で、自宅にいるような温かい空間の中でお別れができます。少人数に特化した設計で、プライバシーが守られています。",
        "address": "新潟県上越市春日新田3-8-15",
        "prefecture_slug": "niigata", "city_slug": "joetsu",
        "latitude": 37.112, "longitude": 138.248,
        "nearest_station": "えちごトキめき鉄道 春日山駅", "station_walk_minutes": 12,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 15,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["家族葬専用", "1日1組貸切", "24時間対応", "バリアフリー"],
        "operator_name": "株式会社ウィズハウス", "rating_avg": 4.5, "review_count": 18,
    },
    {
        "name": "直江津セレモニーホール",
        "slug": "naoetsu-ceremony-hall",
        "venue_type": "private_hall",
        "description": "上越市直江津地区にある葬儀会館。JR直江津駅から車で約8分のアクセス。直江津地区を中心に長年の実績があり、地域の皆様に親しまれています。家族葬から一般葬まで幅広く対応します。",
        "address": "新潟県上越市五智国分3-5-8",
        "prefecture_slug": "niigata", "city_slug": "joetsu",
        "latitude": 37.115, "longitude": 138.215,
        "nearest_station": "JR信越本線 直江津駅", "station_walk_minutes": 18,
        "capacity_max": 70, "hall_count": 2, "has_crematorium": False, "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 255000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 365000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 535000}],
        "features": ["家族葬対応", "宿泊可能", "駐車場完備", "バリアフリー"],
        "operator_name": "直江津セレモニー株式会社", "rating_avg": 3.9, "review_count": 20,
    },

    # =============================================
    # 三条市 追加3件
    # =============================================
    {
        "name": "槻の森斎苑",
        "slug": "tsukinomori-saien-sanjo",
        "venue_type": "public_crematorium",
        "description": "三条市が運営する公営斎場。三条市月岡に位置し、火葬施設を備えています。緑に囲まれた静かな環境で、故人を穏やかにお見送りできます。三条市民は火葬料の優遇措置があります。",
        "address": "新潟県三条市月岡3722",
        "prefecture_slug": "niigata", "city_slug": "sanjo",
        "latitude": 37.620, "longitude": 139.000,
        "nearest_station": "JR弥彦線 燕三条駅", "station_walk_minutes": 25,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": True, "parking_count": 40,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 325000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "三条市", "rating_avg": 3.7, "review_count": 20,
    },
    {
        "name": "セレモニーホール三条",
        "slug": "ceremony-hall-sanjo",
        "venue_type": "private_hall",
        "description": "アークベルが運営する三条市の葬儀会館。燕三条駅からのアクセスが良い立地にあり、家族葬から一般葬まで幅広く対応。三条・燕エリアで長年の信頼と実績を持つ施設です。",
        "address": "新潟県三条市興野3-13-45",
        "prefecture_slug": "niigata", "city_slug": "sanjo",
        "latitude": 37.632, "longitude": 138.963,
        "nearest_station": "JR弥彦線 燕三条駅", "station_walk_minutes": 12,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000}],
        "features": ["家族葬対応", "宿泊可能", "駐車場完備", "バリアフリー"],
        "operator_name": "株式会社アークベル", "rating_avg": 4.1, "review_count": 25,
    },
    {
        "name": "ラソ三条",
        "slug": "raso-sanjo",
        "venue_type": "private_hall",
        "description": "アークベルの家族葬専用ブランド「ラソ」の三条ホール。少人数でのお別れに特化した空間で、リビング感覚の温かい内装が好評。1日1組完全貸切で、ゆったりとお過ごしいただけます。",
        "address": "新潟県三条市東裏館1-5-20",
        "prefecture_slug": "niigata", "city_slug": "sanjo",
        "latitude": 37.625, "longitude": 138.960,
        "nearest_station": "JR弥彦線 北三条駅", "station_walk_minutes": 8,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["家族葬専用", "1日1組貸切", "駅近", "バリアフリー"],
        "operator_name": "株式会社アークベル", "rating_avg": 4.3, "review_count": 15,
    },

    # =============================================
    # 新発田市 追加3件
    # =============================================
    {
        "name": "新発田広域葬斎センター願文院",
        "slug": "ganmonin-shibata",
        "venue_type": "public_crematorium",
        "description": "新発田広域事務組合が運営する公営斎場。火葬施設と式場を備え、新発田市・胎内市・聖籠町の住民が利用可能。広々とした敷地と充実した設備が特長で、通夜から火葬まで一貫して対応できます。",
        "address": "新潟県新発田市古楯495",
        "prefecture_slug": "niigata", "city_slug": "shibata",
        "latitude": 37.953, "longitude": 139.336,
        "nearest_station": "JR白新線 新発田駅", "station_walk_minutes": 20,
        "capacity_max": 100, "hall_count": 2, "has_crematorium": True, "parking_count": 80,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 345000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 515000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応", "バリアフリー"],
        "operator_name": "新発田地域広域事務組合", "rating_avg": 3.9, "review_count": 35,
    },
    {
        "name": "セレモニーホール新発田",
        "slug": "ceremony-hall-shibata",
        "venue_type": "private_hall",
        "description": "アークベルが運営する新発田市の葬儀会館。新発田市大栄町に位置し、家族葬から一般葬まで幅広く対応。地域に密着したサービスを提供し、新発田エリアで信頼を集めています。",
        "address": "新潟県新発田市大栄町3-3-24",
        "prefecture_slug": "niigata", "city_slug": "shibata",
        "latitude": 37.948, "longitude": 139.328,
        "nearest_station": "JR白新線 新発田駅", "station_walk_minutes": 12,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000}],
        "features": ["駅近", "家族葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "株式会社アークベル", "rating_avg": 4.0, "review_count": 22,
    },
    {
        "name": "ファミリーホール四季しんえい",
        "slug": "family-hall-shiki-shinei-shibata",
        "venue_type": "private_hall",
        "description": "花安グループが運営する新発田市の葬儀会館。新発田市日渡に位置し、家族葬に特化した温かみのある施設。花安は新発田市で長年の実績を持つ地域密着型の葬儀社で、丁寧な対応が評判です。",
        "address": "新潟県新発田市日渡85-1",
        "prefecture_slug": "niigata", "city_slug": "shibata",
        "latitude": 37.935, "longitude": 139.315,
        "nearest_station": "JR白新線 新発田駅", "station_walk_minutes": 18,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}],
        "features": ["家族葬対応", "地域密着", "駐車場完備", "バリアフリー"],
        "operator_name": "株式会社花安", "rating_avg": 4.2, "review_count": 18,
    },

    # =============================================
    # その他新潟県の市 追加14件
    # =============================================
    {
        "name": "柏崎市斎場",
        "slug": "kashiwazaki-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "柏崎市が運営する公営斎場。火葬施設と待合室を備え、柏崎市民は火葬料の優遇措置があります。静かな環境の中で穏やかにお見送りできる施設です。",
        "address": "新潟県柏崎市松波4-13-36",
        "prefecture_slug": "niigata", "city_slug": "kashiwazaki",
        "latitude": 37.372, "longitude": 138.556,
        "nearest_station": "JR信越本線 柏崎駅", "station_walk_minutes": 15,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": True, "parking_count": 30,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "柏崎市", "rating_avg": 3.7, "review_count": 18,
    },
    {
        "name": "セレモニーホール柏崎",
        "slug": "ceremony-hall-kashiwazaki",
        "venue_type": "private_hall",
        "description": "柏崎市にあるアークベルのセレモニーホール。柏崎駅から車で約10分のアクセス。家族葬から一般葬まで対応可能で、柏崎地域に密着したサービスを提供しています。",
        "address": "新潟県柏崎市田中18-15",
        "prefecture_slug": "niigata", "city_slug": "kashiwazaki",
        "latitude": 37.368, "longitude": 138.549,
        "nearest_station": "JR信越本線 柏崎駅", "station_walk_minutes": 15,
        "capacity_max": 70, "hall_count": 2, "has_crematorium": False, "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 255000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 365000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 535000}],
        "features": ["家族葬対応", "宿泊可能", "駐車場完備", "バリアフリー"],
        "operator_name": "株式会社アークベル", "rating_avg": 4.0, "review_count": 20,
    },
    {
        "name": "燕市営斎場",
        "slug": "tsubame-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "燕市が運営する公営の火葬場。燕市民は火葬料の優遇措置があります。燕三条地域の交通の要衝に位置し、アクセスも便利。シンプルながら必要な設備を備えた施設です。",
        "address": "新潟県燕市花見1465",
        "prefecture_slug": "niigata", "city_slug": "tsubame",
        "latitude": 37.668, "longitude": 138.925,
        "nearest_station": "JR弥彦線 燕駅", "station_walk_minutes": 20,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 20,
        "facilities": {"霊安室": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "燕市", "rating_avg": 3.5, "review_count": 12,
    },
    {
        "name": "十日町市斎場",
        "slug": "tokamachi-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "十日町市が運営する公営斎場。豪雪地帯の十日町市にあり、冬期でも安心して利用できる設備を整えています。十日町市民は火葬料の優遇措置があります。",
        "address": "新潟県十日町市中条己2858",
        "prefecture_slug": "niigata", "city_slug": "tokamachi",
        "latitude": 37.128, "longitude": 138.756,
        "nearest_station": "JR飯山線 十日町駅", "station_walk_minutes": 20,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 25,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 315000}],
        "features": ["火葬場併設", "公営斎場", "バリアフリー"],
        "operator_name": "十日町市", "rating_avg": 3.6, "review_count": 14,
    },
    {
        "name": "セレモニーホール十日町",
        "slug": "ceremony-hall-tokamachi",
        "venue_type": "private_hall",
        "description": "十日町市にある民間葬儀会館。雪国ならではの配慮が行き届いた設備で、冬期でも安心して利用できます。家族葬から一般葬まで対応し、地域の皆様に愛されている施設です。",
        "address": "新潟県十日町市本町5-39-2",
        "prefecture_slug": "niigata", "city_slug": "tokamachi",
        "latitude": 37.129, "longitude": 138.761,
        "nearest_station": "JR飯山線 十日町駅", "station_walk_minutes": 10,
        "capacity_max": 60, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["駅近", "家族葬対応", "宿泊可能", "駐車場完備"],
        "operator_name": "十日町セレモニー株式会社", "rating_avg": 4.0, "review_count": 16,
    },
    {
        "name": "見附市斎場",
        "slug": "mitsuke-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "見附市が運営する公営火葬場。コンパクトながら必要な設備を備え、見附市民は火葬料の優遇があります。見附市中心部からのアクセスも良好です。",
        "address": "新潟県見附市新幸町7-25",
        "prefecture_slug": "niigata", "city_slug": "mitsuke",
        "latitude": 37.530, "longitude": 138.920,
        "nearest_station": "JR信越本線 見附駅", "station_walk_minutes": 15,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": True, "parking_count": 15,
        "facilities": {"霊安室": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "見附市", "rating_avg": 3.5, "review_count": 10,
    },
    {
        "name": "村上市斎場",
        "slug": "murakami-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "村上市が運営する公営斎場。村上市の北部に位置し、火葬施設を備えています。城下町・村上の静かな環境の中で、故人を穏やかにお見送りできる施設です。",
        "address": "新潟県村上市岩船上大町3-18",
        "prefecture_slug": "niigata", "city_slug": "murakami",
        "latitude": 38.225, "longitude": 139.468,
        "nearest_station": "JR羽越本線 村上駅", "station_walk_minutes": 20,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": True, "parking_count": 25,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "村上市", "rating_avg": 3.6, "review_count": 12,
    },
    {
        "name": "小千谷市斎場",
        "slug": "ojiya-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "小千谷市が運営する公営火葬場。信濃川沿いの静かな環境に位置し、小千谷市民は火葬料の優遇があります。コンパクトながら必要な設備を備えた施設です。",
        "address": "新潟県小千谷市大字薭生甲1854-2",
        "prefecture_slug": "niigata", "city_slug": "ojiya",
        "latitude": 37.311, "longitude": 138.795,
        "nearest_station": "JR上越線 小千谷駅", "station_walk_minutes": 15,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 20,
        "facilities": {"霊安室": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 76000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "小千谷市", "rating_avg": 3.5, "review_count": 10,
    },
    {
        "name": "加茂市斎場",
        "slug": "kamo-niigata-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "加茂市が運営する公営火葬場。「北越の小京都」と呼ばれる加茂市に位置し、周囲は自然に囲まれた穏やかな環境です。加茂市民は火葬料の優遇措置があります。",
        "address": "新潟県加茂市大字上条830",
        "prefecture_slug": "niigata", "city_slug": "kamo-niigata",
        "latitude": 37.668, "longitude": 139.050,
        "nearest_station": "JR信越本線 加茂駅", "station_walk_minutes": 18,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": True, "parking_count": 15,
        "facilities": {"霊安室": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "加茂市", "rating_avg": 3.5, "review_count": 8,
    },
    {
        "name": "妙高市斎場",
        "slug": "myoko-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "妙高市が運営する公営斎場。妙高山を望む自然豊かな環境にあり、静かに故人をお見送りできます。妙高市民は火葬料の優遇があります。冬期も除雪が行き届いています。",
        "address": "新潟県妙高市大字上百々1680",
        "prefecture_slug": "niigata", "city_slug": "myoko",
        "latitude": 36.988, "longitude": 138.248,
        "nearest_station": "えちごトキめき鉄道 新井駅", "station_walk_minutes": 20,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 20,
        "facilities": {"霊安室": True, "駐車場": True, "控室": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["火葬場併設", "公営斎場", "バリアフリー"],
        "operator_name": "妙高市", "rating_avg": 3.6, "review_count": 10,
    },
    {
        "name": "五泉市斎場",
        "slug": "gosen-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "五泉市が運営する公営火葬場。五泉市の豊かな自然に囲まれた静かな環境に位置します。五泉市民は火葬料の優遇があり、地域に根ざした施設として利用されています。",
        "address": "新潟県五泉市論瀬6270",
        "prefecture_slug": "niigata", "city_slug": "gosen",
        "latitude": 37.738, "longitude": 139.182,
        "nearest_station": "JR磐越西線 五泉駅", "station_walk_minutes": 20,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": True, "parking_count": 15,
        "facilities": {"霊安室": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "五泉市", "rating_avg": 3.5, "review_count": 8,
    },
    {
        "name": "阿賀野市斎場",
        "slug": "agano-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "阿賀野市が運営する公営火葬場。白鳥の飛来地として知られる瓢湖にほど近い静かな環境に位置しています。阿賀野市民は火葬料の優遇措置があります。",
        "address": "新潟県阿賀野市山崎77",
        "prefecture_slug": "niigata", "city_slug": "agano",
        "latitude": 37.831, "longitude": 139.226,
        "nearest_station": "JR羽越本線 水原駅", "station_walk_minutes": 15,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": True, "parking_count": 15,
        "facilities": {"霊安室": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "阿賀野市", "rating_avg": 3.5, "review_count": 8,
    },
    {
        "name": "佐渡市斎場",
        "slug": "sado-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "佐渡市が運営する公営斎場。佐渡島内で利用される主要な火葬施設です。島ならではの温かいコミュニティの中で、故人を穏やかにお見送りできます。佐渡市民は火葬料の優遇があります。",
        "address": "新潟県佐渡市中興乙2600",
        "prefecture_slug": "niigata", "city_slug": "sado",
        "latitude": 38.018, "longitude": 138.380,
        "nearest_station": "佐渡汽船 両津港", "station_walk_minutes": 30,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 20,
        "facilities": {"霊安室": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "佐渡市", "rating_avg": 3.6, "review_count": 10,
    },
    {
        "name": "セレモニーホール佐渡",
        "slug": "ceremony-hall-sado",
        "venue_type": "private_hall",
        "description": "佐渡島内にある民間葬儀会館。佐渡汽船両津港から車で約15分のアクセス。島内では数少ない本格的な葬儀会館として、家族葬から一般葬まで幅広く対応しています。",
        "address": "新潟県佐渡市河原田本町394",
        "prefecture_slug": "niigata", "city_slug": "sado",
        "latitude": 38.010, "longitude": 138.325,
        "nearest_station": "佐渡汽船 両津港", "station_walk_minutes": 35,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 345000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}],
        "features": ["家族葬対応", "駐車場完備", "バリアフリー"],
        "operator_name": "佐渡セレモニー株式会社", "rating_avg": 3.9, "review_count": 15,
    },
]

def insert_batch(batch, batch_num):
    """バッチでSupabaseに投入"""
    data_json = json.dumps(batch, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(SUPABASE_URL, data=data_json, headers=HEADERS, method="POST")
    try:
        with urllib.request.urlopen(req) as resp:
            print(f"  バッチ{batch_num}: {resp.status} — {len(batch)}件投入成功")
            return True
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"  バッチ{batch_num}: エラー {e.code} — {body}")
        return False

def main():
    BATCH_SIZE = 10
    total = len(venues)
    success = 0
    print(f"新潟県 追加分: 合計{total}件を投入開始")
    for i in range(0, total, BATCH_SIZE):
        batch = venues[i:i+BATCH_SIZE]
        batch_num = i // BATCH_SIZE + 1
        if insert_batch(batch, batch_num):
            success += len(batch)
        time.sleep(1)
    print(f"\n完了: {success}/{total}件 投入成功")

if __name__ == "__main__":
    main()
