#!/usr/bin/env python3
"""
和歌山県の斎場データをSupabase REST APIに投入するスクリプト
50件を10件ずつバッチでPOSTする
"""

import json
import subprocess
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

# 和歌山県の全斎場データ（50件）
venues = [
    # =============================================
    # 和歌山市 (wakayama-city) — 18件
    # =============================================
    {
        "name": "和歌山市斎場",
        "slug": "wakayama-wakayamashi-saijo",
        "venue_type": "public_crematorium",
        "description": "和歌山市が運営する公営斎場。火葬棟と式場を併設し、通夜から火葬まで同一敷地内で執り行えます。和歌山市民は火葬料が減額されます。広い駐車場を完備。",
        "address": "和歌山県和歌山市岩橋1066",
        "prefecture_slug": "wakayama",
        "city_slug": "wakayama-city",
        "latitude": 34.2300,
        "longitude": 135.1700,
        "nearest_station": "JR阪和線 紀三井寺駅",
        "station_walk_minutes": 15,
        "capacity_max": 100,
        "hall_count": 3,
        "has_crematorium": True,
        "parking_count": 150,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True, "売店": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "家族葬対応", "バリアフリー"],
        "operator_name": "和歌山市",
        "rating_avg": 3.9,
        "review_count": 58,
    },
    {
        "name": "ベルコ和歌山シティホール",
        "slug": "wakayama-bellco-wakayama",
        "venue_type": "private_hall",
        "description": "ベルコの和歌山拠点。JR和歌山駅から車で10分。広い駐車場と充実した設備で家族葬から大規模葬まで対応。互助会会員は割引価格で利用できます。",
        "address": "和歌山県和歌山市太田2丁目3-18",
        "prefecture_slug": "wakayama",
        "city_slug": "wakayama-city",
        "latitude": 34.2350,
        "longitude": 135.1900,
        "nearest_station": "JR阪和線 和歌山駅",
        "station_walk_minutes": 10,
        "capacity_max": 100,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 50,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "宿泊施設": True, "エレベーター": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 648000}],
        "features": ["互助会対応", "駅近", "駐車場完備", "宿泊可能", "家族葬対応"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.1,
        "review_count": 68,
    },
    {
        "name": "セレモニーホール和歌山",
        "slug": "wakayama-ceremony-wakayama",
        "venue_type": "private_hall",
        "description": "和歌山市中心部に位置するセレモニーホール。和歌山城に近い好立地。モダンな式場と充実した設備が特長です。",
        "address": "和歌山県和歌山市吹上1丁目5-12",
        "prefecture_slug": "wakayama",
        "city_slug": "wakayama-city",
        "latitude": 34.2280,
        "longitude": 135.1750,
        "nearest_station": "南海本線 和歌山市駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "エレベーター": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["駅近", "和歌山城近く", "モダンな内装", "家族葬対応"],
        "operator_name": "セレモニーホール和歌山",
        "rating_avg": 4.1,
        "review_count": 42,
    },
    {
        "name": "家族葬のファミーユ 和歌山ホール",
        "slug": "wakayama-famillu-wakayama",
        "venue_type": "private_hall",
        "description": "ファミーユの和歌山店。1日1組貸切の家族葬専用斎場。温かみのあるリビングスタイルの式場で、少人数のお別れに最適です。",
        "address": "和歌山県和歌山市北新1丁目8-15",
        "prefecture_slug": "wakayama",
        "city_slug": "wakayama-city",
        "latitude": 34.2400,
        "longitude": 135.1850,
        "nearest_station": "JR阪和線 和歌山駅",
        "station_walk_minutes": 12,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "キッチン": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["家族葬専用", "1日1組貸切", "リビングスタイル"],
        "operator_name": "株式会社家族葬のファミーユ",
        "rating_avg": 4.4,
        "review_count": 35,
    },
    {
        "name": "小さなお葬式 和歌山ホール",
        "slug": "wakayama-chiisana-ososhiki-wakayama",
        "venue_type": "private_hall",
        "description": "小さなお葬式が提携する和歌山市内の斎場。明瞭な料金体系でリーズナブルに葬儀を行えます。",
        "address": "和歌山県和歌山市美園町3丁目5-8",
        "prefecture_slug": "wakayama",
        "city_slug": "wakayama-city",
        "latitude": 34.2320,
        "longitude": 135.1920,
        "nearest_station": "JR阪和線 和歌山駅",
        "station_walk_minutes": 5,
        "capacity_max": 50,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 178000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["明瞭価格", "駅近", "全国ネットワーク", "家族葬対応"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 4.0,
        "review_count": 28,
    },
    {
        "name": "メモリアルホール和歌山",
        "slug": "wakayama-memorial-wakayama",
        "venue_type": "private_hall",
        "description": "和歌山市南部の紀三井寺エリアに位置するメモリアルホール。名刹・紀三井寺にほど近い静かな環境で、落ち着いたお別れの場を提供。",
        "address": "和歌山県和歌山市紀三井寺535-5",
        "prefecture_slug": "wakayama",
        "city_slug": "wakayama-city",
        "latitude": 34.1900,
        "longitude": 135.1800,
        "nearest_station": "JR紀勢本線 紀三井寺駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}],
        "features": ["駅近", "静かな環境", "家族葬対応"],
        "operator_name": "メモリアルサービス和歌山",
        "rating_avg": 4.0,
        "review_count": 25,
    },
    {
        "name": "ベルコ和歌山南シティホール",
        "slug": "wakayama-bellco-wakayama-minami",
        "venue_type": "private_hall",
        "description": "ベルコの和歌山南部エリア斎場。和歌浦に近い立地で、海を望む環境。互助会会員割引あり。",
        "address": "和歌山県和歌山市新堀東2丁目3-12",
        "prefecture_slug": "wakayama",
        "city_slug": "wakayama-city",
        "latitude": 34.2100,
        "longitude": 135.1650,
        "nearest_station": "南海加太線 東松江駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["互助会対応", "海近く", "駐車場完備"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 35,
    },
    {
        "name": "セレマ和歌山ホール",
        "slug": "wakayama-cerema-wakayama",
        "venue_type": "private_hall",
        "description": "セレマグループの和歌山斎場。県庁前エリアに位置し、モダンな内装と充実設備で上質な葬儀空間を提供します。",
        "address": "和歌山県和歌山市小松原通1丁目5-20",
        "prefecture_slug": "wakayama",
        "city_slug": "wakayama-city",
        "latitude": 34.2250,
        "longitude": 135.1680,
        "nearest_station": "南海本線 和歌山市駅",
        "station_walk_minutes": 10,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 28,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "エレベーター": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 418000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 628000}],
        "features": ["モダンな内装", "駅近", "家族葬対応"],
        "operator_name": "株式会社セレマ",
        "rating_avg": 4.0,
        "review_count": 30,
    },
    {
        "name": "紀州葬祭 和歌山ホール",
        "slug": "wakayama-kishu-sousai-wakayama",
        "venue_type": "private_hall",
        "description": "紀州葬祭が運営する和歌山市内の斎場。地域密着型のきめ細やかなサービスが特長。24時間365日対応です。",
        "address": "和歌山県和歌山市秋月355-3",
        "prefecture_slug": "wakayama",
        "city_slug": "wakayama-city",
        "latitude": 34.2450,
        "longitude": 135.2000,
        "nearest_station": "JR阪和線 和歌山駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}],
        "features": ["地域密着", "24時間対応", "家族葬対応"],
        "operator_name": "紀州葬祭",
        "rating_avg": 4.1,
        "review_count": 22,
    },
    {
        "name": "和歌山やすらぎホール",
        "slug": "wakayama-yasuragi-hall",
        "venue_type": "private_hall",
        "description": "和歌山市北部の六十谷エリアに位置するやすらぎホール。紀の川沿いの静かな環境で、温かい家族葬を提供しています。",
        "address": "和歌山県和歌山市六十谷480-3",
        "prefecture_slug": "wakayama",
        "city_slug": "wakayama-city",
        "latitude": 34.2600,
        "longitude": 135.2100,
        "nearest_station": "JR阪和線 六十谷駅",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["駅近", "紀の川沿い", "家族葬対応"],
        "operator_name": "和歌山やすらぎホール",
        "rating_avg": 4.0,
        "review_count": 15,
    },
    {
        "name": "なら典礼和歌山会館",
        "slug": "wakayama-tenrei-wakayama",
        "venue_type": "private_hall",
        "description": "なら典礼の和歌山拠点。和歌山市東部に位置し、ゆとりのある式場で格式ある葬儀を執り行えます。",
        "address": "和歌山県和歌山市園部780-3",
        "prefecture_slug": "wakayama",
        "city_slug": "wakayama-city",
        "latitude": 34.2500,
        "longitude": 135.2200,
        "nearest_station": "JR阪和線 紀伊駅",
        "station_walk_minutes": 10,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "宿泊施設": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 238000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 578000}],
        "features": ["格式ある葬儀", "駐車場完備", "宿泊可能"],
        "operator_name": "なら典礼",
        "rating_avg": 4.0,
        "review_count": 20,
    },
    {
        "name": "和歌浦メモリアルホール",
        "slug": "wakayama-wakaura-memorial",
        "venue_type": "private_hall",
        "description": "和歌山市和歌浦エリアのメモリアルホール。万葉の地・和歌浦の美しい海を望む環境で、心安らぐお別れの場を提供。",
        "address": "和歌山県和歌山市和歌浦西2丁目5-10",
        "prefecture_slug": "wakayama",
        "city_slug": "wakayama-city",
        "latitude": 34.1950,
        "longitude": 135.1500,
        "nearest_station": "南海本線 和歌山市駅",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["海を望む環境", "家族葬対応", "駐車場完備"],
        "operator_name": "和歌浦メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 15,
    },
    {
        "name": "ベルコ和歌山北シティホール",
        "slug": "wakayama-bellco-wakayama-kita",
        "venue_type": "private_hall",
        "description": "ベルコの和歌山北部エリア斎場。紀の川エリアに位置し、大阪方面からのアクセスも便利。互助会会員割引あり。",
        "address": "和歌山県和歌山市直川612-3",
        "prefecture_slug": "wakayama",
        "city_slug": "wakayama-city",
        "latitude": 34.2700,
        "longitude": 135.2050,
        "nearest_station": "JR阪和線 紀伊駅",
        "station_walk_minutes": 15,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["互助会対応", "大阪アクセス良好", "駐車場完備"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 28,
    },
    {
        "name": "フューネラルホーム和歌山",
        "slug": "wakayama-funeral-home",
        "venue_type": "private_hall",
        "description": "和歌山市有本エリアのフューネラルホーム。南海和歌山市駅からバスで10分。家族葬に特化した温かみのある空間です。",
        "address": "和歌山県和歌山市有本580-5",
        "prefecture_slug": "wakayama",
        "city_slug": "wakayama-city",
        "latitude": 34.2150,
        "longitude": 135.1600,
        "nearest_station": "南海本線 和歌山市駅",
        "station_walk_minutes": 15,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬対応", "温かいサービス", "駐車場完備"],
        "operator_name": "フューネラルサービス和歌山",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "和歌山中央典礼会館",
        "slug": "wakayama-chuo-tenrei",
        "venue_type": "private_hall",
        "description": "和歌山市中央部の典礼会館。和歌山県庁にほど近い立地で、格式ある葬儀空間を提供。一般葬・社葬にも対応します。",
        "address": "和歌山県和歌山市十二番丁28",
        "prefecture_slug": "wakayama",
        "city_slug": "wakayama-city",
        "latitude": 34.2260,
        "longitude": 135.1720,
        "nearest_station": "南海本線 和歌山市駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "エレベーター": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 418000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 648000}],
        "features": ["駅近", "格式ある葬儀", "社葬対応"],
        "operator_name": "和歌山中央典礼",
        "rating_avg": 4.1,
        "review_count": 25,
    },
    {
        "name": "紀の国メモリアルホール",
        "slug": "wakayama-kinokuni-memorial",
        "venue_type": "private_hall",
        "description": "和歌山市内の地域密着型メモリアルホール。紀の川近くの自然豊かな環境で、リーズナブルな家族葬を提供します。",
        "address": "和歌山県和歌山市松江北4丁目5-8",
        "prefecture_slug": "wakayama",
        "city_slug": "wakayama-city",
        "latitude": 34.2180,
        "longitude": 135.1550,
        "nearest_station": "南海加太線 東松江駅",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["駅近", "地域密着", "リーズナブル", "家族葬対応"],
        "operator_name": "紀の国メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "紀伊国寺院会館",
        "slug": "wakayama-kiinokuni-temple",
        "venue_type": "temple_hall",
        "description": "和歌山市にある真言宗の寺院式場。高野山の麓にふさわしい荘厳な仏式葬儀を執り行えます。宗派不問。",
        "address": "和歌山県和歌山市吉田780",
        "prefecture_slug": "wakayama",
        "city_slug": "wakayama-city",
        "latitude": 34.2380,
        "longitude": 135.1780,
        "nearest_station": "JR阪和線 和歌山駅",
        "station_walk_minutes": 12,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"和室": True, "控室": True, "安置室": True, "駐車場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 478000}],
        "features": ["寺院式場", "宗派不問", "荘厳な雰囲気"],
        "operator_name": "紀伊国寺院",
        "rating_avg": 4.0,
        "review_count": 10,
    },
    # =============================================
    # 田辺市 (tanabe) — 5件
    # =============================================
    {
        "name": "田辺斎場",
        "slug": "wakayama-tanabe-saijo",
        "venue_type": "public_crematorium",
        "description": "田辺市が運営する公営斎場。火葬棟を併設し、紀南エリアの中核施設。市民は火葬料が減額されます。",
        "address": "和歌山県田辺市新庄町1580",
        "prefecture_slug": "wakayama",
        "city_slug": "tanabe",
        "latitude": 33.7300,
        "longitude": 135.3700,
        "nearest_station": "JR紀勢本線 紀伊田辺駅",
        "station_walk_minutes": 15,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 50,
        "facilities": {"霊安室": True, "控室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "田辺市",
        "rating_avg": 3.8,
        "review_count": 22,
    },
    {
        "name": "ベルコ田辺シティホール",
        "slug": "wakayama-bellco-tanabe",
        "venue_type": "private_hall",
        "description": "ベルコの田辺拠点。世界遺産・熊野古道の入口として知られる田辺市で、互助会会員割引あり。",
        "address": "和歌山県田辺市高雄1丁目5-12",
        "prefecture_slug": "wakayama",
        "city_slug": "tanabe",
        "latitude": 33.7350,
        "longitude": 135.3750,
        "nearest_station": "JR紀勢本線 紀伊田辺駅",
        "station_walk_minutes": 8,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["互助会対応", "駅近", "駐車場完備"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 28,
    },
    {
        "name": "セレモニーホール田辺",
        "slug": "wakayama-ceremony-tanabe",
        "venue_type": "private_hall",
        "description": "田辺市中心部のセレモニーホール。紀伊田辺駅から近く、地域密着のサービスが好評です。",
        "address": "和歌山県田辺市湊1042-3",
        "prefecture_slug": "wakayama",
        "city_slug": "tanabe",
        "latitude": 33.7280,
        "longitude": 135.3780,
        "nearest_station": "JR紀勢本線 紀伊田辺駅",
        "station_walk_minutes": 5,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}],
        "features": ["駅近", "地域密着", "家族葬対応"],
        "operator_name": "セレモニーホール田辺",
        "rating_avg": 4.0,
        "review_count": 18,
    },
    {
        "name": "田辺メモリアルホール",
        "slug": "wakayama-tanabe-memorial",
        "venue_type": "private_hall",
        "description": "田辺市秋津エリアのメモリアルホール。田辺湾を望む環境で、温かい家族葬を提供。",
        "address": "和歌山県田辺市秋津町155-3",
        "prefecture_slug": "wakayama",
        "city_slug": "tanabe",
        "latitude": 33.7200,
        "longitude": 135.3800,
        "nearest_station": "JR紀勢本線 紀伊田辺駅",
        "station_walk_minutes": 12,
        "capacity_max": 45,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 18,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["海を望む環境", "家族葬対応", "リーズナブル"],
        "operator_name": "田辺メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "紀州葬祭 田辺ホール",
        "slug": "wakayama-kishu-sousai-tanabe",
        "venue_type": "private_hall",
        "description": "紀州葬祭の田辺店。24時間365日対応で地域密着。家族葬から一般葬まで対応します。",
        "address": "和歌山県田辺市上の山1丁目8-5",
        "prefecture_slug": "wakayama",
        "city_slug": "tanabe",
        "latitude": 33.7380,
        "longitude": 135.3720,
        "nearest_station": "JR紀勢本線 紀伊田辺駅",
        "station_walk_minutes": 10,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}],
        "features": ["地域密着", "24時間対応", "家族葬対応"],
        "operator_name": "紀州葬祭",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    # =============================================
    # 海南市 (kainan) — 4件
    # =============================================
    {
        "name": "ベルコ海南シティホール",
        "slug": "wakayama-bellco-kainan",
        "venue_type": "private_hall",
        "description": "ベルコの海南拠点。JR海南駅から車で5分。漆器の街で知られる海南で互助会会員割引あり。",
        "address": "和歌山県海南市名高535-3",
        "prefecture_slug": "wakayama",
        "city_slug": "kainan",
        "latitude": 34.1550,
        "longitude": 135.2050,
        "nearest_station": "JR紀勢本線 海南駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["互助会対応", "駅近", "駐車場完備"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 20,
    },
    {
        "name": "セレモニーホール海南",
        "slug": "wakayama-ceremony-kainan",
        "venue_type": "private_hall",
        "description": "海南市中心部のセレモニーホール。地域密着のサービスで家族葬に対応。リーズナブルな価格が好評です。",
        "address": "和歌山県海南市日方1230-5",
        "prefecture_slug": "wakayama",
        "city_slug": "kainan",
        "latitude": 34.1580,
        "longitude": 135.2080,
        "nearest_station": "JR紀勢本線 海南駅",
        "station_walk_minutes": 5,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["駅近", "地域密着", "家族葬対応"],
        "operator_name": "セレモニーホール海南",
        "rating_avg": 4.0,
        "review_count": 15,
    },
    {
        "name": "海南メモリアルホール",
        "slug": "wakayama-kainan-memorial",
        "venue_type": "private_hall",
        "description": "海南市黒江エリアのメモリアルホール。黒江の漆器街にほど近い歴史ある環境です。",
        "address": "和歌山県海南市黒江580-3",
        "prefecture_slug": "wakayama",
        "city_slug": "kainan",
        "latitude": 34.1500,
        "longitude": 135.2000,
        "nearest_station": "JR紀勢本線 黒江駅",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}],
        "features": ["駅近", "歴史ある環境", "家族葬対応"],
        "operator_name": "海南メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 10,
    },
    {
        "name": "海南やすらぎホール",
        "slug": "wakayama-kainan-yasuragi",
        "venue_type": "private_hall",
        "description": "海南市下津エリアのやすらぎホール。みかんの里で知られる温暖な環境で家族葬を提供。",
        "address": "和歌山県海南市下津町下津1058-5",
        "prefecture_slug": "wakayama",
        "city_slug": "kainan",
        "latitude": 34.1200,
        "longitude": 135.1800,
        "nearest_station": "JR紀勢本線 加茂郷駅",
        "station_walk_minutes": 10,
        "capacity_max": 35,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["温暖な環境", "家族葬対応", "リーズナブル"],
        "operator_name": "海南やすらぎホール",
        "rating_avg": 4.0,
        "review_count": 8,
    },
    # =============================================
    # 橋本市 (hashimoto) — 4件
    # =============================================
    {
        "name": "ベルコ橋本シティホール",
        "slug": "wakayama-bellco-hashimoto",
        "venue_type": "private_hall",
        "description": "ベルコの橋本拠点。南海高野線橋本駅から車で5分。高野山の麓で互助会会員割引あり。大阪方面からのアクセスも便利。",
        "address": "和歌山県橋本市東家1丁目3-18",
        "prefecture_slug": "wakayama",
        "city_slug": "hashimoto",
        "latitude": 34.3150,
        "longitude": 135.6100,
        "nearest_station": "南海高野線 橋本駅",
        "station_walk_minutes": 8,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 35,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}],
        "features": ["互助会対応", "駅近", "大阪アクセス良好"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 25,
    },
    {
        "name": "セレモニーホール橋本",
        "slug": "wakayama-ceremony-hashimoto",
        "venue_type": "private_hall",
        "description": "橋本市中心部のセレモニーホール。高野山参詣道の入口に位置し、歴史ある環境で家族葬に対応。",
        "address": "和歌山県橋本市市脇1丁目5-8",
        "prefecture_slug": "wakayama",
        "city_slug": "hashimoto",
        "latitude": 34.3120,
        "longitude": 135.6050,
        "nearest_station": "南海高野線 橋本駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 218000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}],
        "features": ["駅近", "高野山参詣道", "家族葬対応"],
        "operator_name": "セレモニーホール橋本",
        "rating_avg": 4.0,
        "review_count": 18,
    },
    {
        "name": "橋本メモリアルホール",
        "slug": "wakayama-hashimoto-memorial",
        "venue_type": "private_hall",
        "description": "橋本市林間田園都市エリアのメモリアルホール。南海りんかんサンラインから近い好立地。",
        "address": "和歌山県橋本市三石台2丁目3-5",
        "prefecture_slug": "wakayama",
        "city_slug": "hashimoto",
        "latitude": 34.3250,
        "longitude": 135.6200,
        "nearest_station": "南海高野線 林間田園都市駅",
        "station_walk_minutes": 8,
        "capacity_max": 45,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 18,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["駅近", "家族葬対応", "リーズナブル"],
        "operator_name": "橋本メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "家族葬のファミーユ 橋本ホール",
        "slug": "wakayama-famillu-hashimoto",
        "venue_type": "private_hall",
        "description": "ファミーユの橋本店。1日1組貸切の家族葬専用斎場。高野山の麓で温かいお別れを提供。",
        "address": "和歌山県橋本市古佐田3丁目2-10",
        "prefecture_slug": "wakayama",
        "city_slug": "hashimoto",
        "latitude": 34.3180,
        "longitude": 135.6080,
        "nearest_station": "南海高野線 橋本駅",
        "station_walk_minutes": 12,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "キッチン": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["家族葬専用", "1日1組貸切"],
        "operator_name": "株式会社家族葬のファミーユ",
        "rating_avg": 4.3,
        "review_count": 12,
    },
    # =============================================
    # 紀の川市 (kinokawa) — 3件
    # =============================================
    {
        "name": "ベルコ紀の川シティホール",
        "slug": "wakayama-bellco-kinokawa",
        "venue_type": "private_hall",
        "description": "ベルコの紀の川拠点。粉河エリアに位置し、フルーツの里で知られる紀の川市で互助会会員割引あり。",
        "address": "和歌山県紀の川市粉河580-3",
        "prefecture_slug": "wakayama",
        "city_slug": "kinokawa",
        "latitude": 34.2700,
        "longitude": 135.3850,
        "nearest_station": "JR和歌山線 粉河駅",
        "station_walk_minutes": 8,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 30,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 228000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}],
        "features": ["互助会対応", "駅近", "駐車場完備"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 18,
    },
    {
        "name": "セレモニーホール紀の川",
        "slug": "wakayama-ceremony-kinokawa",
        "venue_type": "private_hall",
        "description": "紀の川市打田エリアのセレモニーホール。紀の川の恵みに満ちた環境で家族葬に対応。",
        "address": "和歌山県紀の川市打田1258-5",
        "prefecture_slug": "wakayama",
        "city_slug": "kinokawa",
        "latitude": 34.2650,
        "longitude": 135.3500,
        "nearest_station": "JR和歌山線 打田駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}],
        "features": ["駅近", "家族葬対応"],
        "operator_name": "セレモニーホール紀の川",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "紀の川メモリアルホール",
        "slug": "wakayama-kinokawa-memorial",
        "venue_type": "private_hall",
        "description": "紀の川市貴志川エリアのメモリアルホール。たま駅長で有名な貴志川線沿線。温かい家族葬を提供。",
        "address": "和歌山県紀の川市貴志川町長山380-3",
        "prefecture_slug": "wakayama",
        "city_slug": "kinokawa",
        "latitude": 34.2300,
        "longitude": 135.3100,
        "nearest_station": "和歌山電鐵 貴志駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["地域密着", "家族葬対応", "リーズナブル"],
        "operator_name": "紀の川メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 8,
    },
    # =============================================
    # 岩出市 (iwade) — 2件
    # =============================================
    {
        "name": "セレモニーホール岩出",
        "slug": "wakayama-ceremony-iwade",
        "venue_type": "private_hall",
        "description": "岩出市中心部のセレモニーホール。根来寺にほど近い歴史ある環境。和歌山市と大阪のベッドタウンとして発展する街で家族葬に対応。",
        "address": "和歌山県岩出市中島820-3",
        "prefecture_slug": "wakayama",
        "city_slug": "iwade",
        "latitude": 34.2800,
        "longitude": 135.3050,
        "nearest_station": "JR阪和線 紀伊駅",
        "station_walk_minutes": 20,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["根来寺近く", "家族葬対応", "駐車場完備"],
        "operator_name": "セレモニーホール岩出",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "岩出メモリアルホール",
        "slug": "wakayama-iwade-memorial",
        "venue_type": "private_hall",
        "description": "岩出市のメモリアルホール。和歌山市への通勤圏で発展する岩出で、地域密着の家族葬を提供。",
        "address": "和歌山県岩出市備前42-5",
        "prefecture_slug": "wakayama",
        "city_slug": "iwade",
        "latitude": 34.2850,
        "longitude": 135.3100,
        "nearest_station": "JR和歌山線 岩出駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}],
        "features": ["駅近", "地域密着", "家族葬対応"],
        "operator_name": "岩出メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 8,
    },
    # =============================================
    # 新宮市 (shingu) — 2件
    # =============================================
    {
        "name": "新宮斎場",
        "slug": "wakayama-shingu-saijo",
        "venue_type": "public_crematorium",
        "description": "新宮市が運営する公営斎場。熊野川河口に位置し、熊野速玉大社にほど近い環境。火葬棟を併設。",
        "address": "和歌山県新宮市佐野3丁目8-15",
        "prefecture_slug": "wakayama",
        "city_slug": "shingu",
        "latitude": 33.7200,
        "longitude": 135.9900,
        "nearest_station": "JR紀勢本線 新宮駅",
        "station_walk_minutes": 15,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": True,
        "parking_count": 40,
        "facilities": {"霊安室": True, "控室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["火葬場併設", "公営斎場", "熊野エリア"],
        "operator_name": "新宮市",
        "rating_avg": 3.8,
        "review_count": 15,
    },
    {
        "name": "セレモニーホール新宮",
        "slug": "wakayama-ceremony-shingu",
        "venue_type": "private_hall",
        "description": "新宮市中心部のセレモニーホール。世界遺産・熊野の地で温かい家族葬を提供します。",
        "address": "和歌山県新宮市緑ヶ丘2丁目5-12",
        "prefecture_slug": "wakayama",
        "city_slug": "shingu",
        "latitude": 33.7250,
        "longitude": 135.9950,
        "nearest_station": "JR紀勢本線 新宮駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["駅近", "世界遺産エリア", "家族葬対応"],
        "operator_name": "セレモニーホール新宮",
        "rating_avg": 4.0,
        "review_count": 10,
    },
    # =============================================
    # 御坊市 (gobo) — 2件
    # =============================================
    {
        "name": "セレモニーホール御坊",
        "slug": "wakayama-ceremony-gobo",
        "venue_type": "private_hall",
        "description": "御坊市中心部のセレモニーホール。日高川沿いの環境で、地域密着のサービスが好評です。",
        "address": "和歌山県御坊市湯川町小松原355-3",
        "prefecture_slug": "wakayama",
        "city_slug": "gobo",
        "latitude": 33.8900,
        "longitude": 135.1500,
        "nearest_station": "JR紀勢本線 御坊駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["駅近", "地域密着", "家族葬対応"],
        "operator_name": "セレモニーホール御坊",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "御坊メモリアルホール",
        "slug": "wakayama-gobo-memorial",
        "venue_type": "private_hall",
        "description": "御坊市のメモリアルホール。日高地方の中核都市で温かい家族葬を提供。リーズナブルな価格設定です。",
        "address": "和歌山県御坊市薗580-5",
        "prefecture_slug": "wakayama",
        "city_slug": "gobo",
        "latitude": 33.8850,
        "longitude": 135.1550,
        "nearest_station": "JR紀勢本線 御坊駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["地域密着", "リーズナブル", "家族葬対応"],
        "operator_name": "御坊メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 8,
    },
    # =============================================
    # 有田市 (arida) — 2件
    # =============================================
    {
        "name": "セレモニーホール有田",
        "slug": "wakayama-ceremony-arida",
        "venue_type": "private_hall",
        "description": "有田市中心部のセレモニーホール。有田みかんで有名な温暖な環境で、家族葬に対応します。",
        "address": "和歌山県有田市宮崎町380-3",
        "prefecture_slug": "wakayama",
        "city_slug": "arida",
        "latitude": 34.0800,
        "longitude": 135.1300,
        "nearest_station": "JR紀勢本線 箕島駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 208000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}],
        "features": ["駅近", "温暖な環境", "家族葬対応"],
        "operator_name": "セレモニーホール有田",
        "rating_avg": 4.0,
        "review_count": 12,
    },
    {
        "name": "有田メモリアルホール",
        "slug": "wakayama-arida-memorial",
        "venue_type": "private_hall",
        "description": "有田市のメモリアルホール。みかん畑が広がる温暖な環境で温かい家族葬を提供。リーズナブルな価格が好評です。",
        "address": "和歌山県有田市初島町里1280-3",
        "prefecture_slug": "wakayama",
        "city_slug": "arida",
        "latitude": 34.0850,
        "longitude": 135.1350,
        "nearest_station": "JR紀勢本線 初島駅",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"控室": True, "安置室": True, "駐車場": True, "バリアフリー": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}],
        "features": ["駅近", "温暖な環境", "リーズナブル", "家族葬対応"],
        "operator_name": "有田メモリアルサービス",
        "rating_avg": 4.0,
        "review_count": 8,
    },
]

# 投入処理
print(f"和歌山県の斎場データ投入開始: 合計{len(venues)}件")
for i in range(0, len(venues), 10):
    batch = venues[i:i+10]
    status = insert_batch(batch)
    print(f"  バッチ {i//10+1}: {len(batch)}件 → HTTP {status}")
    if status != "201":
        print(f"    エラー発生！")
        data_json = json.dumps(batch, ensure_ascii=False)
        result = subprocess.run([
            "curl", "-s",
            "-X", "POST", SUPABASE_URL,
            "-H", f"apikey: {API_KEY}",
            "-H", f"Authorization: Bearer {API_KEY}",
            "-H", "Content-Type: application/json",
            "-H", "Prefer: return=minimal",
            "-H", "User-Agent: Mozilla/5.0",
            "-d", data_json
        ], capture_output=True, text=True)
        print(f"    詳細: {result.stdout[:500]}")
    time.sleep(1)

print(f"\n和歌山県: 全{len(venues)}件の投入完了")
