#!/usr/bin/env python3
"""
北海道・残り都市: 苫小牧8件 + 江別5件 + 千歳5件 + 室蘭5件 + その他都市31件 = 54件
"""

import json
import urllib.request
import urllib.error
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

HEADERS = {
    "apikey": API_KEY,
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal",
}

venues = [
    # =============================================
    # 苫小牧市 — 8件
    # =============================================
    {"name": "苫小牧市高丘霊葬場", "slug": "tomakomai-takaoka-reisojo", "venue_type": "public_crematorium", "description": "苫小牧市が運営する公営火葬場。高丘エリアに位置し、苫小牧市民の火葬を担う施設。市民料金で利用可能で、待合室も完備しています。", "address": "北海道苫小牧市字高丘41番地の1", "prefecture_slug": "hokkaido", "city_slug": "tomakomai", "latitude": 42.6550, "longitude": 141.6000, "nearest_station": "JR室蘭本線 苫小牧駅", "station_walk_minutes": 25, "capacity_max": 30, "hall_count": 1, "has_crematorium": True, "parking_count": 60, "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 0}], "features": ["火葬場", "公営斎場", "市民料金あり"], "operator_name": "苫小牧市", "rating_avg": 3.6, "review_count": 10},
    {"name": "ウィズハウス 苫小牧東", "slug": "withhouse-tomakomai-higashi", "venue_type": "private_hall", "description": "コープの家族葬ウィズハウスの苫小牧東店。三光町に位置し、コープ会員割引あり。1日1組貸切の家族葬ホールで温かみのある空間を提供します。", "address": "北海道苫小牧市三光町2丁目3-6", "prefecture_slug": "hokkaido", "city_slug": "tomakomai", "latitude": 42.6350, "longitude": 141.6200, "nearest_station": "JR室蘭本線 苫小牧駅", "station_walk_minutes": 10, "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}], "features": ["コープ会員割引", "1日1組貸切", "家族葬専用"], "operator_name": "めもるホールディングス", "rating_avg": 4.1, "review_count": 14},
    {"name": "ウィズハウス 苫小牧西", "slug": "withhouse-tomakomai-nishi", "venue_type": "private_hall", "description": "コープの家族葬ウィズハウスの苫小牧西店。澄川町に位置し、苫小牧市西部エリアのお客様に便利。コープ会員割引あり。", "address": "北海道苫小牧市澄川町2丁目1-7", "prefecture_slug": "hokkaido", "city_slug": "tomakomai", "latitude": 42.6300, "longitude": 141.5800, "nearest_station": "JR室蘭本線 苫小牧駅", "station_walk_minutes": 15, "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}], "features": ["コープ会員割引", "家族葬専用", "駐車場完備"], "operator_name": "めもるホールディングス", "rating_avg": 4.0, "review_count": 12},
    {"name": "苫小牧市民斎場 明野ホール", "slug": "tomakomai-akeno-hall", "venue_type": "private_hall", "description": "めもりあるグループが運営する苫小牧市民斎場の明野ホール。広い式場と充実した設備で、家族葬から一般葬まで幅広く対応します。", "address": "北海道苫小牧市明野新町3丁目7-26", "prefecture_slug": "hokkaido", "city_slug": "tomakomai", "latitude": 42.6400, "longitude": 141.6100, "nearest_station": "JR室蘭本線 苫小牧駅", "station_walk_minutes": 18, "capacity_max": 60, "hall_count": 2, "has_crematorium": False, "parking_count": 30, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 500000}], "features": ["一般葬対応", "駐車場完備", "大型式場"], "operator_name": "めもりあるグループ", "rating_avg": 4.0, "review_count": 16},
    {"name": "美原メモリアルホール苫小牧市民斎場", "slug": "mihara-memorial-tomakomai", "venue_type": "private_hall", "description": "めもりあるグループが運営する苫小牧市美原の大型斎場。広い駐車場と複数の式場を備え、家族葬から社葬まで対応可能。苫小牧を代表する葬儀場の一つです。", "address": "北海道苫小牧市美原町3丁目19-1", "prefecture_slug": "hokkaido", "city_slug": "tomakomai", "latitude": 42.6450, "longitude": 141.6050, "nearest_station": "JR室蘭本線 苫小牧駅", "station_walk_minutes": 15, "capacity_max": 100, "hall_count": 3, "has_crematorium": False, "parking_count": 50, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True, "ロビー": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 500000}], "features": ["大型施設", "社葬対応", "駐車場完備"], "operator_name": "めもりあるグループ", "rating_avg": 4.1, "review_count": 22},
    {"name": "家族葬の星光館 花園町", "slug": "seikokukan-hanazono-tomakomai", "venue_type": "private_hall", "description": "めもりあるグループの家族葬ブランド「星光館」の花園町店。少人数の家族葬に特化した温かみのある空間。苫小牧で人気の家族葬専用ホールです。", "address": "北海道苫小牧市花園町4丁目14番17号", "prefecture_slug": "hokkaido", "city_slug": "tomakomai", "latitude": 42.6320, "longitude": 141.6150, "nearest_station": "JR室蘭本線 苫小牧駅", "station_walk_minutes": 12, "capacity_max": 25, "hall_count": 1, "has_crematorium": False, "parking_count": 10, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}], "features": ["家族葬専用", "少人数対応", "アットホーム"], "operator_name": "めもりあるグループ", "rating_avg": 4.2, "review_count": 11},
    {"name": "小さなお葬式 苫小牧ホール", "slug": "chiisana-ososhiki-tomakomai", "venue_type": "private_hall", "description": "小さなお葬式が提携する苫小牧の家族葬ホール。明朗会計で経済的な葬儀を提供しています。24時間相談受付。", "address": "北海道苫小牧市表町3丁目2-15", "prefecture_slug": "hokkaido", "city_slug": "tomakomai", "latitude": 42.6330, "longitude": 141.6050, "nearest_station": "JR室蘭本線 苫小牧駅", "station_walk_minutes": 8, "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}], "features": ["低価格", "駅近", "明朗会計"], "operator_name": "株式会社ユニクエスト", "rating_avg": 3.8, "review_count": 9},
    {"name": "香華殿 苫小牧斎場", "slug": "kokaden-tomakomai-saijo", "venue_type": "private_hall", "description": "香華殿グループが運営する苫小牧の葬儀場。格式ある式場で家族葬から一般葬まで対応。苫小牧エリアで信頼されている葬儀場です。", "address": "北海道苫小牧市日新町2丁目5-10", "prefecture_slug": "hokkaido", "city_slug": "tomakomai", "latitude": 42.6380, "longitude": 141.5950, "nearest_station": "JR室蘭本線 苫小牧駅", "station_walk_minutes": 12, "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 18, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 520000}], "features": ["格式高い", "一般葬対応", "駐車場完備"], "operator_name": "香華殿", "rating_avg": 4.0, "review_count": 12},
    # =============================================
    # 江別市 — 5件
    # =============================================
    {"name": "やわらぎ斎場 江別", "slug": "yawaragi-ebetsu", "venue_type": "private_hall", "description": "やわらぎ斎場の江別エリア拠点。江別市高砂町に位置し、JR江別駅からもアクセス可能。家族葬を中心に、江別市民に広く利用されています。", "address": "北海道江別市高砂町4-1", "prefecture_slug": "hokkaido", "city_slug": "ebetsu", "latitude": 43.1050, "longitude": 141.5300, "nearest_station": "JR函館本線 江別駅", "station_walk_minutes": 10, "capacity_max": 50, "hall_count": 2, "has_crematorium": False, "parking_count": 20, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}], "features": ["駅近", "家族葬対応", "一般葬対応"], "operator_name": "株式会社やわらぎ", "rating_avg": 4.0, "review_count": 14},
    {"name": "ウィズハウス 江別中央", "slug": "withhouse-ebetsu-chuo", "venue_type": "private_hall", "description": "コープの家族葬ウィズハウスの江別中央店。江別市弥生町に位置し、コープ会員割引あり。家族葬専用の温かみのある空間です。", "address": "北海道江別市弥生町34-15", "prefecture_slug": "hokkaido", "city_slug": "ebetsu", "latitude": 43.1070, "longitude": 141.5350, "nearest_station": "JR函館本線 江別駅", "station_walk_minutes": 8, "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 12, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}], "features": ["コープ会員割引", "駅近", "家族葬専用"], "operator_name": "めもるホールディングス", "rating_avg": 4.1, "review_count": 12},
    {"name": "ウィズハウス 江別大麻", "slug": "withhouse-ebetsu-oasa", "venue_type": "private_hall", "description": "コープの家族葬ウィズハウスの江別大麻店。JR大麻駅に近く、江別市西部のお客様に便利。コープ会員割引でお得に利用可能です。", "address": "北海道江別市大麻桜木町28-11", "prefecture_slug": "hokkaido", "city_slug": "ebetsu", "latitude": 43.0800, "longitude": 141.4700, "nearest_station": "JR函館本線 大麻駅", "station_walk_minutes": 8, "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 12, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}], "features": ["コープ会員割引", "駅近", "家族葬専用"], "operator_name": "めもるホールディングス", "rating_avg": 4.0, "review_count": 10},
    {"name": "江別市斎場", "slug": "ebetsu-shi-saijo", "venue_type": "public_crematorium", "description": "江別市が運営する公営火葬場。江別市民の火葬を担う施設で、市民料金で利用可能。待合室完備。", "address": "北海道江別市工栄町15-1", "prefecture_slug": "hokkaido", "city_slug": "ebetsu", "latitude": 43.1100, "longitude": 141.5500, "nearest_station": "JR函館本線 豊幌駅", "station_walk_minutes": 20, "capacity_max": 30, "hall_count": 1, "has_crematorium": True, "parking_count": 40, "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 0}], "features": ["火葬場", "公営斎場", "市民料金あり"], "operator_name": "江別市", "rating_avg": 3.6, "review_count": 8},
    {"name": "香華殿 江別斎場", "slug": "kokaden-ebetsu-saijo", "venue_type": "private_hall", "description": "香華殿グループが運営する江別の葬儀場。家族葬から一般葬まで対応し、江別市民に信頼されている葬儀場です。", "address": "北海道江別市野幌代々木町52-5", "prefecture_slug": "hokkaido", "city_slug": "ebetsu", "latitude": 43.0900, "longitude": 141.5200, "nearest_station": "JR函館本線 野幌駅", "station_walk_minutes": 10, "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}], "features": ["駅近", "家族葬対応"], "operator_name": "香華殿", "rating_avg": 3.9, "review_count": 10},
    # =============================================
    # 千歳市 — 5件
    # =============================================
    {"name": "ちとせ市民斎場 千歳葬殿", "slug": "chitose-shimin-soden", "venue_type": "private_hall", "description": "千歳市の市民斎場として親しまれている千歳葬殿。清流に位置し、通夜から告別式まで一貫して対応。千歳市民に広く利用されている地域密着型の葬儀場です。", "address": "北海道千歳市清流2丁目2-3", "prefecture_slug": "hokkaido", "city_slug": "chitose", "latitude": 42.8200, "longitude": 141.6500, "nearest_station": "JR千歳線 千歳駅", "station_walk_minutes": 12, "capacity_max": 60, "hall_count": 2, "has_crematorium": False, "parking_count": 30, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 500000}], "features": ["地域密着", "一般葬対応", "駐車場完備"], "operator_name": "千歳葬殿", "rating_avg": 4.0, "review_count": 15},
    {"name": "ウィズハウス 南千歳", "slug": "withhouse-minami-chitose", "venue_type": "private_hall", "description": "コープの家族葬ウィズハウスの南千歳店。千歳市朝日町に位置し、コープ会員割引あり。家族葬専用の温かな空間です。", "address": "北海道千歳市朝日町8丁目1206-219", "prefecture_slug": "hokkaido", "city_slug": "chitose", "latitude": 42.8100, "longitude": 141.6600, "nearest_station": "JR千歳線 南千歳駅", "station_walk_minutes": 10, "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 12, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}], "features": ["コープ会員割引", "駅近", "家族葬専用"], "operator_name": "めもるホールディングス", "rating_avg": 4.1, "review_count": 12},
    {"name": "ウィズハウス 千歳北斗", "slug": "withhouse-chitose-hokuto", "venue_type": "private_hall", "description": "コープの家族葬ウィズハウスの千歳北斗店。北斗エリアに位置し、広い駐車場を完備。コープ会員はお得に利用可能です。", "address": "北海道千歳市北斗2丁目10-16", "prefecture_slug": "hokkaido", "city_slug": "chitose", "latitude": 42.8300, "longitude": 141.6550, "nearest_station": "JR千歳線 千歳駅", "station_walk_minutes": 10, "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}], "features": ["コープ会員割引", "駐車場完備", "家族葬専用"], "operator_name": "めもるホールディングス", "rating_avg": 4.0, "review_count": 10},
    {"name": "千歳市斎場", "slug": "chitose-shi-saijo", "venue_type": "public_crematorium", "description": "千歳市が運営する公営火葬場。千歳市民の火葬を担う施設で、市民料金で利用可能です。", "address": "北海道千歳市泉沢1007-5", "prefecture_slug": "hokkaido", "city_slug": "chitose", "latitude": 42.8000, "longitude": 141.6700, "nearest_station": "JR千歳線 千歳駅", "station_walk_minutes": 30, "capacity_max": 30, "hall_count": 1, "has_crematorium": True, "parking_count": 40, "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 0}], "features": ["火葬場", "公営斎場", "市民料金あり"], "operator_name": "千歳市", "rating_avg": 3.6, "review_count": 8},
    {"name": "香華殿 千歳斎場", "slug": "kokaden-chitose-saijo", "venue_type": "private_hall", "description": "香華殿グループが運営する千歳の葬儀場。格式ある式場で家族葬から一般葬まで対応。千歳市で信頼されている葬儀場です。", "address": "北海道千歳市花園4丁目3-1", "prefecture_slug": "hokkaido", "city_slug": "chitose", "latitude": 42.8250, "longitude": 141.6550, "nearest_station": "JR千歳線 千歳駅", "station_walk_minutes": 8, "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}], "features": ["駅近", "家族葬対応", "格式高い"], "operator_name": "香華殿", "rating_avg": 4.0, "review_count": 10},
    # =============================================
    # 室蘭市 — 5件
    # =============================================
    {"name": "室蘭市斎場", "slug": "muroran-shi-saijo", "venue_type": "public_crematorium", "description": "室蘭市が運営する公営火葬場。室蘭市民の火葬を担う施設。市民料金で利用可能で、待合室も完備しています。", "address": "北海道室蘭市神代町143-2", "prefecture_slug": "hokkaido", "city_slug": "muroran", "latitude": 42.3500, "longitude": 141.0100, "nearest_station": "JR室蘭本線 母恋駅", "station_walk_minutes": 15, "capacity_max": 30, "hall_count": 1, "has_crematorium": True, "parking_count": 30, "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 0}], "features": ["火葬場", "公営斎場", "市民料金あり"], "operator_name": "室蘭市", "rating_avg": 3.6, "review_count": 8},
    {"name": "室蘭市民斎場 雲上閣メモリアルホール", "slug": "unjokaku-memorial-muroran", "venue_type": "private_hall", "description": "めもりあるグループが運営する室蘭の大型メモリアルホール。寿町に位置し、通夜から告別式まで一貫対応。室蘭市を代表する葬儀場の一つです。", "address": "北海道室蘭市寿町3丁目16-3", "prefecture_slug": "hokkaido", "city_slug": "muroran", "latitude": 42.3400, "longitude": 141.0300, "nearest_station": "JR室蘭本線 東室蘭駅", "station_walk_minutes": 12, "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "僧侶控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 500000}], "features": ["大型式場", "一般葬対応", "駐車場完備"], "operator_name": "めもりあるグループ", "rating_avg": 4.0, "review_count": 16},
    {"name": "メモリアルハウス星光館 室蘭", "slug": "seikokukan-muroran", "venue_type": "private_hall", "description": "めもりあるグループの家族葬ブランド「星光館」の室蘭店。少人数の家族葬に特化した温かみのある空間です。", "address": "北海道室蘭市寿町3丁目13-10", "prefecture_slug": "hokkaido", "city_slug": "muroran", "latitude": 42.3410, "longitude": 141.0310, "nearest_station": "JR室蘭本線 東室蘭駅", "station_walk_minutes": 12, "capacity_max": 25, "hall_count": 1, "has_crematorium": False, "parking_count": 10, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}], "features": ["家族葬専用", "少人数対応", "アットホーム"], "operator_name": "めもりあるグループ", "rating_avg": 4.1, "review_count": 10},
    {"name": "香華殿 室蘭斎場", "slug": "kokaden-muroran-saijo", "venue_type": "private_hall", "description": "香華殿グループが運営する室蘭の葬儀場。格式ある式場で家族葬から一般葬まで対応します。", "address": "北海道室蘭市中島町2丁目20-5", "prefecture_slug": "hokkaido", "city_slug": "muroran", "latitude": 42.3350, "longitude": 141.0350, "nearest_station": "JR室蘭本線 東室蘭駅", "station_walk_minutes": 8, "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 520000}], "features": ["駅近", "一般葬対応", "格式高い"], "operator_name": "香華殿", "rating_avg": 4.0, "review_count": 11},
    {"name": "小さなお葬式 室蘭ホール", "slug": "chiisana-ososhiki-muroran", "venue_type": "private_hall", "description": "小さなお葬式が提携する室蘭の家族葬ホール。明朗会計で低価格な葬儀を提供。", "address": "北海道室蘭市中島町3丁目8-10", "prefecture_slug": "hokkaido", "city_slug": "muroran", "latitude": 42.3360, "longitude": 141.0360, "nearest_station": "JR室蘭本線 東室蘭駅", "station_walk_minutes": 10, "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 8, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}], "features": ["低価格", "明朗会計", "家族葬専用"], "operator_name": "株式会社ユニクエスト", "rating_avg": 3.8, "review_count": 7},
    # =============================================
    # その他の市（各1〜3件）
    # =============================================
    {"name": "やわらぎ斎場 恵庭", "slug": "yawaragi-eniwa", "venue_type": "private_hall", "description": "やわらぎ斎場の恵庭エリア拠点。恵庭市に位置し、家族葬を中心に地域のお客様に利用されています。", "address": "北海道恵庭市有明町6丁目1-25", "prefecture_slug": "hokkaido", "city_slug": "eniwa", "latitude": 42.8800, "longitude": 141.5800, "nearest_station": "JR千歳線 恵庭駅", "station_walk_minutes": 10, "capacity_max": 50, "hall_count": 2, "has_crematorium": False, "parking_count": 20, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}], "features": ["駅近", "家族葬対応"], "operator_name": "株式会社やわらぎ", "rating_avg": 4.0, "review_count": 12},
    {"name": "ウィズハウス 恵庭", "slug": "withhouse-eniwa", "venue_type": "private_hall", "description": "コープの家族葬ウィズハウスの恵庭店。別邸タイプも併設。コープ会員割引あり。", "address": "北海道恵庭市駒場町6丁目4-1", "prefecture_slug": "hokkaido", "city_slug": "eniwa", "latitude": 42.8850, "longitude": 141.5750, "nearest_station": "JR千歳線 恵庭駅", "station_walk_minutes": 12, "capacity_max": 30, "hall_count": 2, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}], "features": ["コープ会員割引", "別邸タイプ", "家族葬専用"], "operator_name": "めもるホールディングス", "rating_avg": 4.1, "review_count": 11},
    {"name": "香華殿 恵庭斎場", "slug": "kokaden-eniwa-saijo", "venue_type": "private_hall", "description": "香華殿グループが運営する恵庭の葬儀場。恵庭市柏木町に位置し、家族葬から一般葬まで対応。", "address": "北海道恵庭市柏木町3丁目3番16号", "prefecture_slug": "hokkaido", "city_slug": "eniwa", "latitude": 42.8900, "longitude": 141.5700, "nearest_station": "JR千歳線 恵庭駅", "station_walk_minutes": 8, "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}], "features": ["駅近", "家族葬対応"], "operator_name": "香華殿", "rating_avg": 4.0, "review_count": 10},
    {"name": "やわらぎ斎場 北広島", "slug": "yawaragi-kitahiroshima", "venue_type": "private_hall", "description": "やわらぎ斎場の北広島エリア拠点。JR北広島駅近くに位置し、家族葬を中心に対応。", "address": "北海道北広島市新富町東1丁目4-4", "prefecture_slug": "hokkaido", "city_slug": "kitahiroshima", "latitude": 43.0300, "longitude": 141.5600, "nearest_station": "JR千歳線 北広島駅", "station_walk_minutes": 8, "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}], "features": ["駅近", "家族葬対応"], "operator_name": "株式会社やわらぎ", "rating_avg": 4.0, "review_count": 10},
    {"name": "ウィズハウス 北広島", "slug": "withhouse-kitahiroshima", "venue_type": "private_hall", "description": "コープの家族葬ウィズハウスの北広島店。北広島市中央に位置。コープ会員割引あり。", "address": "北海道北広島市中央2丁目4番地", "prefecture_slug": "hokkaido", "city_slug": "kitahiroshima", "latitude": 43.0320, "longitude": 141.5580, "nearest_station": "JR千歳線 北広島駅", "station_walk_minutes": 5, "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 12, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}], "features": ["コープ会員割引", "駅近", "家族葬専用"], "operator_name": "めもるホールディングス", "rating_avg": 4.1, "review_count": 9},
    {"name": "やわらぎ斎場 石狩", "slug": "yawaragi-ishikari", "venue_type": "private_hall", "description": "やわらぎ斎場の石狩エリア拠点。石狩市花川南に位置し、石狩市民に利用されています。", "address": "北海道石狩市花川南8条3丁目146番1", "prefecture_slug": "hokkaido", "city_slug": "ishikari", "latitude": 43.1400, "longitude": 141.3150, "nearest_station": "JR学園都市線 あいの里教育大駅", "station_walk_minutes": 25, "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 20, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}], "features": ["駐車場完備", "家族葬対応"], "operator_name": "株式会社やわらぎ", "rating_avg": 3.9, "review_count": 10},
    {"name": "ウィズハウス 石狩", "slug": "withhouse-ishikari", "venue_type": "private_hall", "description": "コープの家族葬ウィズハウスの石狩店。石狩市樽川エリアに位置。コープ会員割引あり。", "address": "北海道石狩市樽川8条1丁目6番地", "prefecture_slug": "hokkaido", "city_slug": "ishikari", "latitude": 43.1350, "longitude": 141.3100, "nearest_station": "JR学園都市線 あいの里教育大駅", "station_walk_minutes": 20, "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}], "features": ["コープ会員割引", "家族葬専用"], "operator_name": "めもるホールディングス", "rating_avg": 4.0, "review_count": 8},
    {"name": "ウィズハウス 網走", "slug": "withhouse-abashiri", "venue_type": "private_hall", "description": "コープの家族葬ウィズハウスの網走店。網走市駒場南に位置し、コープ会員割引あり。オホーツクエリアの家族葬に対応。", "address": "北海道網走市駒場南7丁目1-8", "prefecture_slug": "hokkaido", "city_slug": "abashiri", "latitude": 43.9900, "longitude": 144.2600, "nearest_station": "JR石北本線 網走駅", "station_walk_minutes": 15, "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 297000}], "features": ["コープ会員割引", "家族葬専用"], "operator_name": "めもるホールディングス", "rating_avg": 4.0, "review_count": 8},
    {"name": "網走市斎場", "slug": "abashiri-shi-saijo", "venue_type": "public_crematorium", "description": "網走市が運営する公営火葬場。市民料金で利用可能。オホーツクエリアの火葬施設です。", "address": "北海道網走市字呼人84番地", "prefecture_slug": "hokkaido", "city_slug": "abashiri", "latitude": 43.9800, "longitude": 144.2400, "nearest_station": "JR石北本線 呼人駅", "station_walk_minutes": 10, "capacity_max": 30, "hall_count": 1, "has_crematorium": True, "parking_count": 30, "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 0}], "features": ["火葬場", "公営斎場", "市民料金あり"], "operator_name": "網走市", "rating_avg": 3.5, "review_count": 6},
    {"name": "むとう市民斎場 稚内", "slug": "muto-shimin-wakkanai", "venue_type": "private_hall", "description": "むとう葬儀社が運営する稚内の市民斎場。日本最北の地で地域密着型の葬儀サービスを提供。家族葬から一般葬まで対応しています。", "address": "北海道稚内市港5丁目1-27", "prefecture_slug": "hokkaido", "city_slug": "wakkanai", "latitude": 45.4100, "longitude": 141.6800, "nearest_station": "JR宗谷本線 稚内駅", "station_walk_minutes": 10, "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 20, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 480000}], "features": ["地域密着", "一般葬対応", "駅近"], "operator_name": "むとう葬儀社", "rating_avg": 4.0, "review_count": 10},
    {"name": "登別市葬祭場", "slug": "noboribetsu-shi-sosaijo", "venue_type": "public_facility", "description": "登別市が運営する公営葬祭場。登別市民向けの施設で、通夜・告別式に利用可能。市民料金で利用できます。", "address": "北海道登別市中央町5丁目22-1", "prefecture_slug": "hokkaido", "city_slug": "noboribetsu", "latitude": 42.4100, "longitude": 141.1100, "nearest_station": "JR室蘭本線 幌別駅", "station_walk_minutes": 10, "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 20, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 250000}], "features": ["公営施設", "市民料金あり", "駅近"], "operator_name": "登別市", "rating_avg": 3.7, "review_count": 8},
    {"name": "伊達市斎場", "slug": "date-hokkaido-shi-saijo", "venue_type": "public_crematorium", "description": "伊達市が運営する公営火葬場。伊達市民の火葬を担う施設で、市民料金で利用可能です。", "address": "北海道伊達市末永町44-6", "prefecture_slug": "hokkaido", "city_slug": "date-hokkaido", "latitude": 42.4700, "longitude": 140.8600, "nearest_station": "JR室蘭本線 伊達紋別駅", "station_walk_minutes": 15, "capacity_max": 30, "hall_count": 1, "has_crematorium": True, "parking_count": 20, "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 0}], "features": ["火葬場", "公営斎場", "市民料金あり"], "operator_name": "伊達市", "rating_avg": 3.5, "review_count": 6},
    {"name": "やわらぎ斎場 岩見沢", "slug": "yawaragi-iwamizawa", "venue_type": "private_hall", "description": "やわらぎ斎場の岩見沢エリア拠点。岩見沢市中心部に位置し、家族葬から一般葬まで対応しています。", "address": "北海道岩見沢市3条西6丁目10-1", "prefecture_slug": "hokkaido", "city_slug": "iwamizawa", "latitude": 43.2000, "longitude": 141.7700, "nearest_station": "JR函館本線 岩見沢駅", "station_walk_minutes": 8, "capacity_max": 50, "hall_count": 2, "has_crematorium": False, "parking_count": 20, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}], "features": ["駅近", "家族葬対応"], "operator_name": "株式会社やわらぎ", "rating_avg": 4.0, "review_count": 12},
    {"name": "やわらぎ斎場 名寄", "slug": "yawaragi-nayoro", "venue_type": "private_hall", "description": "やわらぎ斎場の名寄エリア拠点。名寄市に位置し、道北エリアの家族葬に対応しています。", "address": "北海道名寄市西4条南5丁目14", "prefecture_slug": "hokkaido", "city_slug": "nayoro", "latitude": 44.3500, "longitude": 142.4600, "nearest_station": "JR宗谷本線 名寄駅", "station_walk_minutes": 8, "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}], "features": ["駅近", "家族葬対応", "地域密着"], "operator_name": "株式会社やわらぎ", "rating_avg": 3.9, "review_count": 8},
    {"name": "根室市斎場", "slug": "nemuro-shi-saijo", "venue_type": "public_crematorium", "description": "根室市が運営する公営火葬場。日本最東端の火葬施設で、根室市民の火葬を担っています。", "address": "北海道根室市牧の内149", "prefecture_slug": "hokkaido", "city_slug": "nemuro", "latitude": 43.3300, "longitude": 145.5800, "nearest_station": "JR根室本線 根室駅", "station_walk_minutes": 20, "capacity_max": 20, "hall_count": 1, "has_crematorium": True, "parking_count": 20, "facilities": {"霊安室": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 0}], "features": ["火葬場", "公営斎場"], "operator_name": "根室市", "rating_avg": 3.5, "review_count": 5},
    {"name": "やわらぎ斎場 滝川", "slug": "yawaragi-takikawa", "venue_type": "private_hall", "description": "やわらぎ斎場の滝川エリア拠点。滝川市に位置し、中空知エリアの家族葬に対応。", "address": "北海道滝川市本町3丁目6-38", "prefecture_slug": "hokkaido", "city_slug": "takikawa", "latitude": 43.5600, "longitude": 141.9100, "nearest_station": "JR函館本線 滝川駅", "station_walk_minutes": 8, "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}], "features": ["駅近", "家族葬対応"], "operator_name": "株式会社やわらぎ", "rating_avg": 3.9, "review_count": 8},
    {"name": "吉野斎苑 砂川", "slug": "yoshino-saien-sunagawa", "venue_type": "public_crematorium", "description": "砂川市が運営する公営斎場「吉野斎苑」。砂川市民の火葬と通夜・告別式に対応。市民料金で利用可能。", "address": "北海道砂川市吉野4条南6丁目1-1", "prefecture_slug": "hokkaido", "city_slug": "sunagawa", "latitude": 43.4900, "longitude": 141.9000, "nearest_station": "JR函館本線 砂川駅", "station_walk_minutes": 15, "capacity_max": 30, "hall_count": 1, "has_crematorium": True, "parking_count": 20, "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 0}], "features": ["火葬場", "公営斎場", "市民料金あり"], "operator_name": "砂川市", "rating_avg": 3.6, "review_count": 6},
    {"name": "やわらぎ斎場 深川", "slug": "yawaragi-fukagawa", "venue_type": "private_hall", "description": "やわらぎ斎場の深川エリア拠点。深川市に位置し、北空知エリアの葬儀に対応しています。", "address": "北海道深川市3条10番20号", "prefecture_slug": "hokkaido", "city_slug": "fukagawa", "latitude": 43.7200, "longitude": 142.0500, "nearest_station": "JR函館本線 深川駅", "station_walk_minutes": 8, "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}], "features": ["駅近", "家族葬対応"], "operator_name": "株式会社やわらぎ", "rating_avg": 3.9, "review_count": 7},
    {"name": "セレモニーホール富良野", "slug": "ceremony-hall-furano", "venue_type": "private_hall", "description": "富良野市中心部のセレモニーホール。富良野・上富良野エリアの葬儀に対応。地域に根差した丁寧なサービスが特徴です。", "address": "北海道富良野市日の出町3-20", "prefecture_slug": "hokkaido", "city_slug": "furano", "latitude": 43.3400, "longitude": 142.3800, "nearest_station": "JR根室本線 富良野駅", "station_walk_minutes": 10, "capacity_max": 40, "hall_count": 1, "has_crematorium": False, "parking_count": 15, "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}], "features": ["地域密着", "家族葬対応", "駅近"], "operator_name": "セレモニーホール富良野", "rating_avg": 3.9, "review_count": 8},
    {"name": "やすらぎ聖苑 留萌", "slug": "yasuragi-seien-rumoi", "venue_type": "public_crematorium", "description": "留萌市が運営する公営斎場「やすらぎ聖苑」。留萌市民の火葬と式場利用に対応。市民料金で利用可能です。", "address": "北海道留萌市沖見町3丁目56", "prefecture_slug": "hokkaido", "city_slug": "rumoi", "latitude": 43.9400, "longitude": 141.6400, "nearest_station": "JR留萌本線 留萌駅", "station_walk_minutes": 15, "capacity_max": 30, "hall_count": 1, "has_crematorium": True, "parking_count": 20, "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 0}], "features": ["火葬場", "公営斎場", "市民料金あり"], "operator_name": "留萌市", "rating_avg": 3.5, "review_count": 5},
    {"name": "紋別市斎場", "slug": "monbetsu-shi-saijo", "venue_type": "public_crematorium", "description": "紋別市が運営する公営火葬場。オホーツクエリア北部の火葬施設として紋別市民に利用されています。", "address": "北海道紋別市花園町8丁目1-53", "prefecture_slug": "hokkaido", "city_slug": "monbetsu", "latitude": 44.3500, "longitude": 143.3500, "nearest_station": "紋別バスターミナル", "station_walk_minutes": 15, "capacity_max": 20, "hall_count": 1, "has_crematorium": True, "parking_count": 15, "facilities": {"霊安室": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 0}], "features": ["火葬場", "公営斎場"], "operator_name": "紋別市", "rating_avg": 3.5, "review_count": 5},
    {"name": "美唄斎苑", "slug": "bibai-saien", "venue_type": "public_crematorium", "description": "美唄市が運営する公営火葬場。美唄市民の火葬に対応する施設で、市民料金で利用可能です。", "address": "北海道美唄市東4条北2丁目1-1", "prefecture_slug": "hokkaido", "city_slug": "bibai", "latitude": 43.3300, "longitude": 141.8600, "nearest_station": "JR函館本線 美唄駅", "station_walk_minutes": 12, "capacity_max": 20, "hall_count": 1, "has_crematorium": True, "parking_count": 15, "facilities": {"霊安室": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 0}], "features": ["火葬場", "公営斎場", "市民料金あり"], "operator_name": "美唄市", "rating_avg": 3.5, "review_count": 5},
    {"name": "芦別市斎場", "slug": "ashibetsu-shi-saijo", "venue_type": "public_crematorium", "description": "芦別市が運営する公営火葬場。芦別市民の火葬に対応しています。", "address": "北海道芦別市北3条東1丁目8", "prefecture_slug": "hokkaido", "city_slug": "ashibetsu", "latitude": 43.5200, "longitude": 142.1900, "nearest_station": "JR根室本線 芦別駅", "station_walk_minutes": 10, "capacity_max": 20, "hall_count": 1, "has_crematorium": True, "parking_count": 10, "facilities": {"霊安室": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 0}], "features": ["火葬場", "公営斎場"], "operator_name": "芦別市", "rating_avg": 3.5, "review_count": 5},
    {"name": "赤平市斎場", "slug": "akabira-shi-saijo", "venue_type": "public_crematorium", "description": "赤平市が運営する公営火葬場。赤平市民の火葬に対応する小規模な施設です。", "address": "北海道赤平市泉町4丁目1", "prefecture_slug": "hokkaido", "city_slug": "akabira", "latitude": 43.5600, "longitude": 142.0400, "nearest_station": "JR根室本線 赤平駅", "station_walk_minutes": 12, "capacity_max": 20, "hall_count": 1, "has_crematorium": True, "parking_count": 10, "facilities": {"霊安室": True, "駐車場": True, "控室": True}, "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 0}], "features": ["火葬場", "公営斎場"], "operator_name": "赤平市", "rating_avg": 3.5, "review_count": 5},
]

def insert_batch(batch):
    data_json = json.dumps(batch, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(SUPABASE_URL, data=data_json, headers=HEADERS, method="POST")
    try:
        with urllib.request.urlopen(req) as res:
            return res.status
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"  HTTPError {e.code}: {body[:300]}")
        return e.code

total = len(venues)
print(f"北海道・残り都市: {total}件を投入開始")

ok = 0
for i in range(0, total, 10):
    batch = venues[i:i+10]
    code = insert_batch(batch)
    print(f"  バッチ {i//10+1}: {code} ({len(batch)}件)")
    if code in (200, 201):
        ok += len(batch)
    time.sleep(0.5)

print(f"\n完了: {ok}/{total}件 投入成功")
