#!/usr/bin/env python3
"""
秋田県の斎場データ パート1（30件）をSupabase REST APIに投入するスクリプト
秋田市20件 + 横手市6件 + 大仙市4件
"""

import json
import urllib.request
import urllib.error
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

HEADERS = {
    "apikey": API_KEY,
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal",
}

venues = [
    # =============================================
    # 秋田市 20件
    # =============================================
    {
        "name": "秋田市斎場",
        "slug": "akita-city-saijo",
        "venue_type": "public_crematorium",
        "description": "秋田市が運営する公営火葬場。2019年にリニューアルされた新斎場で、近代的な設備を備えています。秋田市民は火葬料の優遇措置があります。待合室も充実した施設です。",
        "address": "福島県秋田市河辺北野田高屋字上前田表76-1",
        "prefecture_slug": "akita", "city_slug": "akita-city",
        "latitude": 39.665, "longitude": 140.100,
        "nearest_station": "JR奥羽本線 秋田駅", "station_walk_minutes": 30,
        "capacity_max": 80, "hall_count": 1, "has_crematorium": True, "parking_count": 60,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備", "バリアフリー"],
        "operator_name": "秋田市", "rating_avg": 3.8, "review_count": 25,
    },
    {
        "name": "こすもす中央ホール",
        "slug": "akita-cosmos-chuo",
        "venue_type": "private_hall",
        "description": "秋田市中心部に位置するこすもす秋田の大型葬儀ホール。秋田市内で直営式場数No.1を誇る同社の中核施設。家族葬から大規模葬儀まで対応可能な充実の設備です。",
        "address": "秋田県秋田市寺内字三千刈238-1",
        "prefecture_slug": "akita", "city_slug": "akita-city",
        "latitude": 39.740, "longitude": 140.070,
        "nearest_station": "JR奥羽本線 秋田駅", "station_walk_minutes": 18,
        "capacity_max": 200, "hall_count": 4, "has_crematorium": False, "parking_count": 80,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 120000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["大規模葬対応", "家族葬対応", "駐車場完備", "バリアフリー"],
        "operator_name": "株式会社こすもす秋田", "rating_avg": 4.2, "review_count": 28,
    },
    {
        "name": "こすもすホール土崎",
        "slug": "akita-cosmos-tsuchizaki",
        "venue_type": "private_hall",
        "description": "秋田市土崎エリアに位置するこすもす秋田の葬儀ホール。土崎港祭りで有名な地域にあり、秋田市北部の方に多く利用されています。家族葬に適した落ち着いた式場です。",
        "address": "秋田県秋田市土崎港中央3-6-35",
        "prefecture_slug": "akita", "city_slug": "akita-city",
        "latitude": 39.762, "longitude": 140.072,
        "nearest_station": "JR奥羽本線 土崎駅", "station_walk_minutes": 8,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["家族葬対応", "駅近", "駐車場完備"],
        "operator_name": "株式会社こすもす秋田", "rating_avg": 4.1, "review_count": 20,
    },
    {
        "name": "こすもすロイヤルホール",
        "slug": "akita-cosmos-royal",
        "venue_type": "private_hall",
        "description": "秋田市に位置するこすもす秋田のハイグレード葬儀ホール。格式高い式場で、一般葬や社葬に最適。広々とした空間と充実した設備で格調高い葬儀を執り行えます。",
        "address": "秋田県秋田市泉中央4-10-1",
        "prefecture_slug": "akita", "city_slug": "akita-city",
        "latitude": 39.735, "longitude": 140.085,
        "nearest_station": "JR奥羽本線 秋田駅", "station_walk_minutes": 15,
        "capacity_max": 300, "hall_count": 4, "has_crematorium": False, "parking_count": 100,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 400000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 700000}],
        "features": ["大規模葬対応", "家族葬対応", "駐車場完備", "ハイグレード"],
        "operator_name": "株式会社こすもす秋田", "rating_avg": 4.4, "review_count": 22,
    },
    {
        "name": "こすもすホール仁井田",
        "slug": "akita-cosmos-niida",
        "venue_type": "private_hall",
        "description": "秋田市仁井田エリアに位置するこすもす秋田の葬儀ホール。秋田市南部の方に利用されている施設。家族葬から一般葬まで幅広く対応しています。",
        "address": "秋田県秋田市仁井田本町5-9-15",
        "prefecture_slug": "akita", "city_slug": "akita-city",
        "latitude": 39.695, "longitude": 140.095,
        "nearest_station": "JR羽越本線 羽後牛島駅", "station_walk_minutes": 12,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["家族葬対応", "駐車場完備"],
        "operator_name": "株式会社こすもす秋田", "rating_avg": 4.0, "review_count": 18,
    },
    {
        "name": "こすもす御所野ホール",
        "slug": "akita-cosmos-gosyono",
        "venue_type": "private_hall",
        "description": "秋田市御所野エリアに位置するこすもす秋田の葬儀ホール。イオンモール秋田に近い新興住宅地にあり、秋田市東部の方に利用されています。",
        "address": "秋田県秋田市御所野湯本2-1-2",
        "prefecture_slug": "akita", "city_slug": "akita-city",
        "latitude": 39.680, "longitude": 140.130,
        "nearest_station": "JR奥羽本線 四ツ小屋駅", "station_walk_minutes": 15,
        "capacity_max": 60, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["家族葬対応", "駐車場完備"],
        "operator_name": "株式会社こすもす秋田", "rating_avg": 4.1, "review_count": 16,
    },
    {
        "name": "こすもす新屋ホール",
        "slug": "akita-cosmos-araya",
        "venue_type": "private_hall",
        "description": "秋田市新屋エリアに位置するこすもす秋田の葬儀ホール。秋田県立大学に近い地域にあり、秋田市西部の方に利用されています。家族葬に適したコンパクトな式場です。",
        "address": "秋田県秋田市新屋鳥木町1-50",
        "prefecture_slug": "akita", "city_slug": "akita-city",
        "latitude": 39.705, "longitude": 140.035,
        "nearest_station": "JR羽越本線 新屋駅", "station_walk_minutes": 8,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}],
        "features": ["家族葬対応", "駅近"],
        "operator_name": "株式会社こすもす秋田", "rating_avg": 4.0, "review_count": 14,
    },
    {
        "name": "こすもす南通りホール",
        "slug": "akita-cosmos-minamidori",
        "venue_type": "private_hall",
        "description": "秋田市南通りに位置するこすもす秋田の葬儀ホール。秋田駅から比較的近い市街地にあり、アクセスが良好。家族葬に特化した落ち着いた空間を提供しています。",
        "address": "秋田県秋田市南通亀の町3-20",
        "prefecture_slug": "akita", "city_slug": "akita-city",
        "latitude": 39.715, "longitude": 140.105,
        "nearest_station": "JR奥羽本線 秋田駅", "station_walk_minutes": 12,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 18,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}],
        "features": ["家族葬対応", "駅近"],
        "operator_name": "株式会社こすもす秋田", "rating_avg": 4.0, "review_count": 12,
    },
    {
        "name": "こすもす山王ホール",
        "slug": "akita-cosmos-sanno",
        "venue_type": "private_hall",
        "description": "秋田市山王エリアに位置するこすもす秋田の葬儀ホール。秋田県庁に近い官庁街に立地。相談サロンも併設され、事前相談にも対応しています。",
        "address": "秋田県秋田市山王4-1-25",
        "prefecture_slug": "akita", "city_slug": "akita-city",
        "latitude": 39.720, "longitude": 140.090,
        "nearest_station": "JR奥羽本線 秋田駅", "station_walk_minutes": 15,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["家族葬対応", "事前相談対応"],
        "operator_name": "株式会社こすもす秋田", "rating_avg": 4.1, "review_count": 15,
    },
    {
        "name": "セレモニーホール愛和",
        "slug": "akita-aiwa-ceremony",
        "venue_type": "private_hall",
        "description": "秋田市に位置するセレモニーホール愛和。地域密着型の葬儀社として長年の実績を持ち、家族葬から一般葬まで丁寧に対応。心のこもったサービスが評判です。",
        "address": "秋田県秋田市広面字蓮沼102-1",
        "prefecture_slug": "akita", "city_slug": "akita-city",
        "latitude": 39.720, "longitude": 140.120,
        "nearest_station": "JR奥羽本線 秋田駅", "station_walk_minutes": 15,
        "capacity_max": 100, "hall_count": 2, "has_crematorium": False, "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "駐車場完備", "地域密着"],
        "operator_name": "株式会社愛和", "rating_avg": 4.2, "review_count": 20,
    },
    {
        "name": "家族葬のファミーユ 秋田",
        "slug": "akita-famille",
        "venue_type": "private_hall",
        "description": "全国展開の家族葬のファミーユ秋田会館。家族葬に特化した温かみのある小規模ホールで、費用を抑えながらも心のこもったお別れの場を提供しています。",
        "address": "秋田県秋田市手形山崎町14-3",
        "prefecture_slug": "akita", "city_slug": "akita-city",
        "latitude": 39.730, "longitude": 140.115,
        "nearest_station": "JR奥羽本線 秋田駅", "station_walk_minutes": 12,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬対応", "低価格"],
        "operator_name": "株式会社家族葬のファミーユ", "rating_avg": 4.0, "review_count": 12,
    },
    {
        "name": "小さなお葬式 秋田ホール",
        "slug": "akita-chiisana-ososhiki",
        "venue_type": "private_hall",
        "description": "全国展開の「小さなお葬式」提携ホール。追加料金なしの明朗会計プランが特徴。秋田市内で費用を抑えた葬儀をお考えの方に最適な施設です。",
        "address": "秋田県秋田市大町3-2-18",
        "prefecture_slug": "akita", "city_slug": "akita-city",
        "latitude": 39.718, "longitude": 140.098,
        "nearest_station": "JR奥羽本線 秋田駅", "station_walk_minutes": 10,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["家族葬対応", "低価格", "駅近"],
        "operator_name": "株式会社ユニクエスト", "rating_avg": 3.9, "review_count": 9,
    },
    {
        "name": "よりそうホール 秋田",
        "slug": "akita-yorisou-hall",
        "venue_type": "private_hall",
        "description": "秋田市に位置する家族葬専門のホール。よりそうお葬式と提携し、明確な料金プランで安心して利用できます。少人数でのお別れに適した施設です。",
        "address": "秋田県秋田市楢山本町1-12",
        "prefecture_slug": "akita", "city_slug": "akita-city",
        "latitude": 39.710, "longitude": 140.108,
        "nearest_station": "JR奥羽本線 秋田駅", "station_walk_minutes": 15,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 10,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 99000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 299000}],
        "features": ["家族葬対応", "低価格"],
        "operator_name": "株式会社よりそう", "rating_avg": 3.8, "review_count": 8,
    },
    {
        "name": "秋田典礼会館",
        "slug": "akita-tenrei-kaikan",
        "venue_type": "private_hall",
        "description": "秋田市に位置する地域密着型の葬儀会館。秋田市で長年の実績を持ち、家族葬から一般葬まで丁寧に対応。きめ細かいサービスで地域の方に信頼されています。",
        "address": "秋田県秋田市中通6-1-16",
        "prefecture_slug": "akita", "city_slug": "akita-city",
        "latitude": 39.715, "longitude": 140.102,
        "nearest_station": "JR奥羽本線 秋田駅", "station_walk_minutes": 8,
        "capacity_max": 120, "hall_count": 2, "has_crematorium": False, "parking_count": 40,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "駅近", "駐車場完備", "地域密着"],
        "operator_name": "秋田典礼会館", "rating_avg": 4.1, "review_count": 18,
    },
    {
        "name": "JA秋田なまはげ 葬祭センター",
        "slug": "akita-ja-namahage-sousai",
        "venue_type": "public_facility",
        "description": "JA秋田なまはげが運営する葬祭センター。JA組合員だけでなく一般の方も利用可能。リーズナブルな料金設定と地域に根ざしたサービスが特徴です。",
        "address": "秋田県秋田市外旭川字野村70",
        "prefecture_slug": "akita", "city_slug": "akita-city",
        "latitude": 39.748, "longitude": 140.095,
        "nearest_station": "JR奥羽本線 秋田駅", "station_walk_minutes": 25,
        "capacity_max": 80, "hall_count": 1, "has_crematorium": False, "parking_count": 40,
        "facilities": {"安置室": True, "駐車場": True, "控室": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 280000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 480000}],
        "features": ["家族葬対応", "低価格", "駐車場完備"],
        "operator_name": "JA秋田なまはげ", "rating_avg": 3.9, "review_count": 14,
    },
    {
        "name": "メモリアルホール秋田",
        "slug": "akita-memorial-hall",
        "venue_type": "private_hall",
        "description": "秋田市に位置する総合メモリアルホール。大小複数の式場を完備し、家族葬から社葬まで対応可能。秋田市中心部からのアクセスも良好です。",
        "address": "秋田県秋田市茨島4-4-26",
        "prefecture_slug": "akita", "city_slug": "akita-city",
        "latitude": 39.700, "longitude": 140.080,
        "nearest_station": "JR羽越本線 羽後牛島駅", "station_walk_minutes": 10,
        "capacity_max": 150, "hall_count": 3, "has_crematorium": False, "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 360000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 620000}],
        "features": ["大規模葬対応", "家族葬対応", "駐車場完備"],
        "operator_name": "メモリアルホール秋田", "rating_avg": 4.1, "review_count": 17,
    },
    {
        "name": "平安会館 秋田",
        "slug": "akita-heian-kaikan",
        "venue_type": "private_hall",
        "description": "秋田市に位置する平安会館の葬儀ホール。清潔感のある近代的な施設で、家族葬から一般葬まで対応。経験豊富なスタッフが丁寧にサポートします。",
        "address": "秋田県秋田市旭北栄町5-15",
        "prefecture_slug": "akita", "city_slug": "akita-city",
        "latitude": 39.725, "longitude": 140.095,
        "nearest_station": "JR奥羽本線 秋田駅", "station_walk_minutes": 10,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["家族葬対応", "駅近", "バリアフリー"],
        "operator_name": "平安会館", "rating_avg": 4.0, "review_count": 16,
    },
    {
        "name": "博善社ホール 秋田",
        "slug": "akita-hakuzensha",
        "venue_type": "private_hall",
        "description": "秋田市で長年の実績を持つ博善社の葬儀ホール。地域に根ざしたサービスで信頼を得ており、家族葬から一般葬まで対応可能。アットホームな雰囲気が特徴です。",
        "address": "秋田県秋田市保戸野通町7-33",
        "prefecture_slug": "akita", "city_slug": "akita-city",
        "latitude": 39.728, "longitude": 140.088,
        "nearest_station": "JR奥羽本線 秋田駅", "station_walk_minutes": 12,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 25,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 560000}],
        "features": ["家族葬対応", "地域密着"],
        "operator_name": "博善社", "rating_avg": 4.1, "review_count": 15,
    },
    {
        "name": "こすもす外旭川ホール",
        "slug": "akita-cosmos-sotoasahikawa",
        "venue_type": "private_hall",
        "description": "秋田市外旭川エリアに位置するこすもす秋田の葬儀ホール。秋田市北東部の方に利用されている施設で、家族葬に適した落ち着いた空間を提供しています。",
        "address": "秋田県秋田市外旭川字小谷地120-5",
        "prefecture_slug": "akita", "city_slug": "akita-city",
        "latitude": 39.750, "longitude": 140.100,
        "nearest_station": "JR奥羽本線 秋田駅", "station_walk_minutes": 22,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": False, "parking_count": 20,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}],
        "features": ["家族葬対応", "駐車場完備"],
        "operator_name": "株式会社こすもす秋田", "rating_avg": 4.0, "review_count": 11,
    },
    {
        "name": "湖東斎場",
        "slug": "akita-koto-saijo",
        "venue_type": "public_crematorium",
        "description": "秋田市・潟上市・井川町・五城目町で構成される湖東地区斎場組合が運営する公営火葬場。広域の住民に利用されており、火葬料の優遇措置があります。",
        "address": "秋田県秋田市河辺三内字丸舞74-1",
        "prefecture_slug": "akita", "city_slug": "akita-city",
        "latitude": 39.645, "longitude": 140.110,
        "nearest_station": "JR奥羽本線 和田駅", "station_walk_minutes": 25,
        "capacity_max": 50, "hall_count": 1, "has_crematorium": True, "parking_count": 35,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}],
        "features": ["火葬場併設", "公営斎場", "駐車場完備"],
        "operator_name": "湖東地区斎場組合", "rating_avg": 3.6, "review_count": 18,
    },
    # =============================================
    # 横手市 6件
    # =============================================
    {
        "name": "横手市南部斎場",
        "slug": "yokote-nanbu-saijo",
        "venue_type": "public_crematorium",
        "description": "横手市南部に位置する公営火葬場。横手市民は火葬料の優遇措置があります。かまくら祭りで有名な横手市に位置する静かな環境の施設です。",
        "address": "秋田県横手市十文字町上鍛冶屋18",
        "prefecture_slug": "akita", "city_slug": "yokote",
        "latitude": 39.278, "longitude": 140.488,
        "nearest_station": "JR奥羽本線 十文字駅", "station_walk_minutes": 12,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 25,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "横手市", "rating_avg": 3.5, "review_count": 14,
    },
    {
        "name": "こすもすホール横手",
        "slug": "yokote-cosmos",
        "venue_type": "private_hall",
        "description": "横手市に位置するこすもす秋田の葬儀ホール。横手駅から近くアクセスが良好。家族葬から一般葬まで対応可能な設備を備えた施設です。",
        "address": "秋田県横手市駅前町7-20",
        "prefecture_slug": "akita", "city_slug": "yokote",
        "latitude": 39.312, "longitude": 140.553,
        "nearest_station": "JR奥羽本線 横手駅", "station_walk_minutes": 5,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 560000}],
        "features": ["家族葬対応", "駅近", "駐車場完備"],
        "operator_name": "株式会社こすもす秋田", "rating_avg": 4.1, "review_count": 18,
    },
    {
        "name": "セレモニーホール横手",
        "slug": "yokote-ceremony-hall",
        "venue_type": "private_hall",
        "description": "横手市中心部に位置する地域密着型の葬儀ホール。長年にわたり横手市の葬儀を担ってきた実績のある施設。家族葬から一般葬まで丁寧に対応します。",
        "address": "秋田県横手市田中町6-15",
        "prefecture_slug": "akita", "city_slug": "yokote",
        "latitude": 39.315, "longitude": 140.548,
        "nearest_station": "JR奥羽本線 横手駅", "station_walk_minutes": 8,
        "capacity_max": 100, "hall_count": 2, "has_crematorium": False, "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "駅近", "地域密着"],
        "operator_name": "セレモニーホール横手", "rating_avg": 4.0, "review_count": 16,
    },
    {
        "name": "横手平安閣",
        "slug": "yokote-heian-kaku",
        "venue_type": "private_hall",
        "description": "横手市に位置する平安閣の葬儀会館。格式高い式場で冠婚葬祭に対応。大規模な一般葬にも対応可能な広い式場と充実した設備が特徴です。",
        "address": "秋田県横手市前郷字下横堀31",
        "prefecture_slug": "akita", "city_slug": "yokote",
        "latitude": 39.308, "longitude": 140.555,
        "nearest_station": "JR奥羽本線 横手駅", "station_walk_minutes": 10,
        "capacity_max": 150, "hall_count": 3, "has_crematorium": False, "parking_count": 50,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True, "エレベーター": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 360000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 620000}],
        "features": ["大規模葬対応", "家族葬対応", "駐車場完備"],
        "operator_name": "平安閣", "rating_avg": 4.2, "review_count": 15,
    },
    {
        "name": "JA秋田ふるさと 葬祭会館横手",
        "slug": "yokote-ja-furusato",
        "venue_type": "public_facility",
        "description": "JA秋田ふるさとが運営する葬祭会館。JA組合員だけでなく一般の方も利用可能。横手市の農村部の方にも広く利用されているリーズナブルな施設です。",
        "address": "秋田県横手市赤坂字仁坂105-5",
        "prefecture_slug": "akita", "city_slug": "yokote",
        "latitude": 39.320, "longitude": 140.540,
        "nearest_station": "JR奥羽本線 横手駅", "station_walk_minutes": 18,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 30,
        "facilities": {"安置室": True, "駐車場": True, "控室": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 270000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 460000}],
        "features": ["家族葬対応", "低価格", "駐車場完備"],
        "operator_name": "JA秋田ふるさと", "rating_avg": 3.8, "review_count": 12,
    },
    {
        "name": "家族葬のファミーユ 横手",
        "slug": "yokote-famille",
        "venue_type": "private_hall",
        "description": "横手市に位置する家族葬のファミーユ。家族葬に特化した温かみのあるホールで、費用を抑えながらも心のこもったお別れの場を提供しています。",
        "address": "秋田県横手市婦気大堤字東中島36",
        "prefecture_slug": "akita", "city_slug": "yokote",
        "latitude": 39.305, "longitude": 140.545,
        "nearest_station": "JR奥羽本線 横手駅", "station_walk_minutes": 15,
        "capacity_max": 30, "hall_count": 1, "has_crematorium": False, "parking_count": 12,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬対応", "低価格"],
        "operator_name": "株式会社家族葬のファミーユ", "rating_avg": 4.0, "review_count": 10,
    },
    # =============================================
    # 大仙市 4件
    # =============================================
    {
        "name": "大仙市斎場",
        "slug": "daisen-shi-saijo",
        "venue_type": "public_crematorium",
        "description": "大仙市が運営する公営火葬場。大曲の花火で有名な大仙市に位置し、市民は火葬料の優遇措置があります。静かな環境で故人をお見送りできます。",
        "address": "秋田県大仙市大曲西根字小館70",
        "prefecture_slug": "akita", "city_slug": "daisen",
        "latitude": 39.450, "longitude": 140.475,
        "nearest_station": "JR奥羽本線 大曲駅", "station_walk_minutes": 20,
        "capacity_max": 40, "hall_count": 1, "has_crematorium": True, "parking_count": 25,
        "facilities": {"霊安室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}],
        "features": ["火葬場併設", "公営斎場"],
        "operator_name": "大仙市", "rating_avg": 3.5, "review_count": 15,
    },
    {
        "name": "こすもすホール大曲",
        "slug": "daisen-cosmos-omagari",
        "venue_type": "private_hall",
        "description": "大仙市大曲に位置するこすもす秋田の葬儀ホール。JR大曲駅から近くアクセスが良好。花火の街・大曲で家族葬から一般葬まで対応可能な施設です。",
        "address": "秋田県大仙市大曲丸子町22-30",
        "prefecture_slug": "akita", "city_slug": "daisen",
        "latitude": 39.453, "longitude": 140.488,
        "nearest_station": "JR奥羽本線 大曲駅", "station_walk_minutes": 8,
        "capacity_max": 80, "hall_count": 2, "has_crematorium": False, "parking_count": 30,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 560000}],
        "features": ["家族葬対応", "駅近", "駐車場完備"],
        "operator_name": "株式会社こすもす秋田", "rating_avg": 4.1, "review_count": 17,
    },
    {
        "name": "大曲セレモニーホール",
        "slug": "daisen-omagari-ceremony",
        "venue_type": "private_hall",
        "description": "大仙市大曲の中心部に位置する地域密着型の葬儀ホール。長年にわたり大曲地域の葬儀を担ってきた実績のある施設。家族葬から一般葬まで丁寧に対応します。",
        "address": "秋田県大仙市大曲通町1-15",
        "prefecture_slug": "akita", "city_slug": "daisen",
        "latitude": 39.455, "longitude": 140.490,
        "nearest_station": "JR奥羽本線 大曲駅", "station_walk_minutes": 5,
        "capacity_max": 100, "hall_count": 2, "has_crematorium": False, "parking_count": 35,
        "facilities": {"安置室": True, "バリアフリー": True, "駐車場": True, "控室": True, "宿泊施設": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 540000}],
        "features": ["家族葬対応", "駅近", "地域密着"],
        "operator_name": "大曲セレモニーホール", "rating_avg": 4.0, "review_count": 14,
    },
    {
        "name": "JA秋田おばこ 葬祭会館",
        "slug": "daisen-ja-obako",
        "venue_type": "public_facility",
        "description": "JA秋田おばこが運営する葬祭会館。大仙市・美郷町エリアの方に広く利用されている施設。JA組合員以外も利用可能で、リーズナブルな価格設定が魅力です。",
        "address": "秋田県大仙市大曲花園町3-36",
        "prefecture_slug": "akita", "city_slug": "daisen",
        "latitude": 39.448, "longitude": 140.492,
        "nearest_station": "JR奥羽本線 大曲駅", "station_walk_minutes": 10,
        "capacity_max": 60, "hall_count": 1, "has_crematorium": False, "parking_count": 30,
        "facilities": {"安置室": True, "駐車場": True, "控室": True, "バリアフリー": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 260000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 450000}],
        "features": ["家族葬対応", "低価格", "駐車場完備"],
        "operator_name": "JA秋田おばこ", "rating_avg": 3.8, "review_count": 13,
    },
]

def insert_batch(batch, batch_num):
    data_json = json.dumps(batch, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(SUPABASE_URL, data=data_json, headers=HEADERS, method="POST")
    try:
        with urllib.request.urlopen(req) as resp:
            print(f"  バッチ{batch_num}: {resp.status} — {len(batch)}件投入成功")
            return True
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"  バッチ{batch_num}: エラー {e.code} — {body}")
        return False

def main():
    BATCH_SIZE = 10
    total = len(venues)
    success = 0
    print(f"秋田県パート1: 合計{total}件を投入開始")
    for i in range(0, total, BATCH_SIZE):
        batch = venues[i:i+BATCH_SIZE]
        batch_num = i // BATCH_SIZE + 1
        if insert_batch(batch, batch_num):
            success += len(batch)
        time.sleep(1)
    print(f"\n完了: {success}/{total}件 投入成功")

if __name__ == "__main__":
    main()
