#!/usr/bin/env python3
"""
大阪府の斎場データ バッチ3: 大阪市残り22件 + 堺市25件 = 47件
"""
import json
import subprocess
import time

SUPABASE_URL = "https://zlcwbcajhrtndockwqcb.supabase.co/rest/v1/venues"
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsY3diY2FqaHJ0bmRvY2t3cWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE1NDgzNiwiZXhwIjoyMDg3NzMwODM2fQ.4GcRFiM40y214WcuHnKuqp_Ut1LMt12AgonXNv5MibY"

def insert_batch(venues):
    data_json = json.dumps(venues, ensure_ascii=False)
    result = subprocess.run([
        "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
        "-X", "POST", SUPABASE_URL,
        "-H", f"apikey: {API_KEY}",
        "-H", f"Authorization: Bearer {API_KEY}",
        "-H", "Content-Type: application/json",
        "-H", "Prefer: return=minimal",
        "-H", "User-Agent: Mozilla/5.0",
        "-d", data_json
    ], capture_output=True, text=True)
    return result.stdout.strip()

venues = [
    # =============================================
    # 大阪市 残り22件
    # =============================================
    # 城東区追加
    {
        "name": "小さなお葬式 城東ホール",
        "slug": "osaka-chiisana-joto",
        "venue_type": "private_hall",
        "description": "大阪市城東区にある小さなお葬式の提携ホール。大阪メトロ長堀鶴見緑地線蒲生四丁目駅から徒歩8分。明朗会計の火葬式・家族葬プランが人気の施設です。",
        "address": "大阪府大阪市城東区蒲生2-8-15",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6930,
        "longitude": 135.5420,
        "nearest_station": "大阪メトロ長堀鶴見緑地線 蒲生四丁目駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 6,
        "facilities": {"式場": True, "親族控室": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["火葬式対応", "家族葬対応", "明朗会計"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 3.9,
        "review_count": 55
    },
    # 都島区追加
    {
        "name": "都島セレモニーホール",
        "slug": "osaka-miyakojima-ceremony",
        "venue_type": "private_hall",
        "description": "大阪市都島区にある地域密着型の葬儀会館。大阪メトロ谷町線野江内代駅から徒歩7分。都島区の住宅街に位置し、家族葬を中心に地域の方々にご利用いただいています。",
        "address": "大阪府大阪市都島区内代町2-6-18",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7130,
        "longitude": 135.5360,
        "nearest_station": "大阪メトロ谷町線 野江内代駅",
        "station_walk_minutes": 7,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 530000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "地域密着"],
        "operator_name": "都島セレモニー",
        "rating_avg": 3.8,
        "review_count": 32
    },
    # 中央区追加
    {
        "name": "泉屋 本町ホール",
        "slug": "osaka-izumiya-honmachi",
        "venue_type": "private_hall",
        "description": "大阪市中央区にある泉屋の本町エリアの葬儀会館。大阪メトロ御堂筋線本町駅から徒歩5分。ビジネス街に位置し、社葬やお別れの会にも適した洗練された空間です。",
        "address": "大阪府大阪市中央区安土町2-3-13",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6830,
        "longitude": 135.5100,
        "nearest_station": "大阪メトロ御堂筋線 本町駅",
        "station_walk_minutes": 5,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "社葬対応", "駅近", "老舗葬儀社"],
        "operator_name": "泉屋",
        "rating_avg": 4.1,
        "review_count": 63
    },
    # 住吉区追加（寺院）
    {
        "name": "住吉大社 式場",
        "slug": "osaka-sumiyoshi-taisha-shikijo",
        "venue_type": "temple_hall",
        "description": "大阪市住吉区の住吉大社近くの式場。全国的に有名な住吉大社の荘厳な雰囲気のもと、神式・仏式の葬儀を執り行えます。南海本線住吉大社駅から徒歩3分と好立地。",
        "address": "大阪府大阪市住吉区住吉2-9-89",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6130,
        "longitude": 135.4930,
        "nearest_station": "南海本線 住吉大社駅",
        "station_walk_minutes": 3,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "控室": True, "駐車場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 380000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 620000}],
        "features": ["寺院式場", "神式対応", "名社", "駅近"],
        "operator_name": "住吉大社",
        "rating_avg": 4.3,
        "review_count": 48
    },
    # 淀川区追加
    {
        "name": "小さなお葬式 新大阪ホール",
        "slug": "osaka-chiisana-shin-osaka",
        "venue_type": "private_hall",
        "description": "大阪市淀川区にある小さなお葬式の提携ホール。新大阪駅から徒歩10分で、遠方からの参列者にも便利。火葬式から家族葬まで明朗会計で提供しています。",
        "address": "大阪府大阪市淀川区宮原3-5-24",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7330,
        "longitude": 135.5020,
        "nearest_station": "JR東海道新幹線 新大阪駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 5,
        "facilities": {"式場": True, "親族控室": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 189000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["火葬式対応", "家族葬対応", "新大阪近く", "明朗会計"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 4.0,
        "review_count": 82
    },
    # 東淀川区追加
    {
        "name": "ベルコシティホール東淀川",
        "slug": "osaka-bellco-higashiyodogawa",
        "venue_type": "private_hall",
        "description": "大阪市東淀川区にあるベルコの葬儀会館。阪急京都線相川駅から徒歩8分。東淀川区の住宅街に位置し、家族葬・一般葬に対応した設備を完備しています。",
        "address": "大阪府大阪市東淀川区相川1-3-18",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7440,
        "longitude": 135.5310,
        "nearest_station": "阪急京都線 相川駅",
        "station_walk_minutes": 8,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "ベルコグループ"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 44
    },
    # 鶴見区追加
    {
        "name": "小さなお葬式 鶴見ホール",
        "slug": "osaka-chiisana-tsurumi",
        "venue_type": "private_hall",
        "description": "大阪市鶴見区にある小さなお葬式の提携ホール。鶴見緑地公園に近い環境で、明朗会計の火葬式・家族葬プランが充実。鶴見斎場へのアクセスも良好です。",
        "address": "大阪府大阪市鶴見区今津中2-1-15",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7030,
        "longitude": 135.5760,
        "nearest_station": "大阪メトロ長堀鶴見緑地線 横堤駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["火葬式対応", "家族葬対応", "鶴見斎場近く", "明朗会計"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 3.8,
        "review_count": 45
    },
    # 此花区寺院
    {
        "name": "正蓮寺 式場",
        "slug": "osaka-shorenji-shikijo",
        "venue_type": "temple_hall",
        "description": "大阪市此花区にある浄土真宗本願寺派の寺院式場。静かな境内の中で、伝統的な仏式葬儀を執り行えます。此花区の地域に根差した寺院で、檀家以外の方も利用可能です。",
        "address": "大阪府大阪市此花区伝法3-1-6",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6900,
        "longitude": 135.4420,
        "nearest_station": "阪神なんば線 伝法駅",
        "station_walk_minutes": 5,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 5,
        "facilities": {"式場": True, "控室": True, "駐車場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 320000}],
        "features": ["寺院式場", "仏式葬儀", "檀家以外可", "駅近"],
        "operator_name": "正蓮寺",
        "rating_avg": 3.8,
        "review_count": 15
    },
    # 北区追加
    {
        "name": "北斎場前メモリアルホール",
        "slug": "osaka-kitasaijo-mae-memorial",
        "venue_type": "private_hall",
        "description": "大阪市北区の北斎場のすぐ近くにある民営葬儀会館。北斎場での火葬を利用する方に便利な立地。通夜・告別式から火葬場への移動がスムーズです。",
        "address": "大阪府大阪市北区長柄西1-5-8",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7080,
        "longitude": 135.5110,
        "nearest_station": "大阪メトロ谷町線 天神橋筋六丁目駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 310000}],
        "features": ["家族葬対応", "北斎場近く", "火葬場アクセス良好"],
        "operator_name": "北斎場前メモリアル",
        "rating_avg": 4.0,
        "review_count": 58
    },
    # 阿倍野区追加
    {
        "name": "ティア阿倍野",
        "slug": "osaka-tier-abeno",
        "venue_type": "private_hall",
        "description": "大阪市阿倍野区にあるティアの家族葬ホール。あべのハルカス南側エリアの落ち着いた場所に位置。1日1組貸切で、温かみのある空間でお別れの時間を過ごせます。",
        "address": "大阪府大阪市阿倍野区松崎町2-5-12",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6410,
        "longitude": 135.5170,
        "nearest_station": "JR阪和線 美章園駅",
        "station_walk_minutes": 5,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "1日1組貸切", "駅近", "明朗会計"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.1,
        "review_count": 46
    },
    # 西成区追加
    {
        "name": "家族葬のファミーユ 西成ホール",
        "slug": "osaka-famille-nishinari",
        "venue_type": "private_hall",
        "description": "大阪市西成区にある家族葬専門ホール。天下茶屋駅から徒歩6分の立地。少人数のお葬式に特化し、低価格で温かなお見送りを提供しています。",
        "address": "大阪府大阪市西成区天下茶屋2-8-12",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6320,
        "longitude": 135.4920,
        "nearest_station": "南海本線 天下茶屋駅",
        "station_walk_minutes": 6,
        "capacity_max": 35,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 6,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "駅近", "低価格"],
        "operator_name": "株式会社ファミーユ",
        "rating_avg": 4.0,
        "review_count": 33
    },
    # 大正区寺院
    {
        "name": "大正寺院式場",
        "slug": "osaka-taisho-temple",
        "venue_type": "temple_hall",
        "description": "大阪市大正区にある寺院式場。沖縄文化が息づく大正区で、伝統的な仏式葬儀を地域に寄り添って執り行っています。少人数の家族葬に適した落ち着いた空間です。",
        "address": "大阪府大阪市大正区千島2-4-15",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6500,
        "longitude": 135.4680,
        "nearest_station": "JR大阪環状線 大正駅",
        "station_walk_minutes": 15,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 5,
        "facilities": {"式場": True, "控室": True, "駐車場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 300000}],
        "features": ["寺院式場", "仏式葬儀", "少人数対応"],
        "operator_name": "大正寺院",
        "rating_avg": 3.6,
        "review_count": 12
    },
    # 東住吉区追加
    {
        "name": "ベルコシティホール東住吉",
        "slug": "osaka-bellco-higashisumiyoshi",
        "venue_type": "private_hall",
        "description": "大阪市東住吉区にあるベルコの葬儀会館。JR阪和線鶴ヶ丘駅から徒歩8分。長居公園にも近い閑静なエリアで、家族葬・一般葬に対応しています。",
        "address": "大阪府大阪市東住吉区鷹合1-5-18",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6210,
        "longitude": 135.5240,
        "nearest_station": "JR阪和線 鶴ヶ丘駅",
        "station_walk_minutes": 8,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "ベルコグループ"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 42
    },
    # 住之江区追加
    {
        "name": "公益社 住之江ホール",
        "slug": "osaka-koeisha-suminoe",
        "venue_type": "private_hall",
        "description": "大阪市住之江区にある公益社の葬儀会館。南港エリアに近い場所に位置し、家族葬から一般葬まで公益社の安定したサービスを提供しています。",
        "address": "大阪府大阪市住之江区新北島1-2-8",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6080,
        "longitude": 135.4750,
        "nearest_station": "ニュートラム 住之江公園駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "一般葬対応", "公益社ブランド"],
        "operator_name": "公益社（燦ホールディングス）",
        "rating_avg": 4.2,
        "review_count": 52
    },
    # 浪速区追加
    {
        "name": "イオンのお葬式 なんばホール",
        "slug": "osaka-aeon-namba",
        "venue_type": "private_hall",
        "description": "大阪市浪速区のなんばエリアにあるイオンライフの提携葬儀会館。JR難波駅から徒歩5分。イオンブランドの安心感と明朗な価格設定で、火葬式から家族葬まで提供しています。",
        "address": "大阪府大阪市浪速区湊町1-4-1",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6610,
        "longitude": 135.4990,
        "nearest_station": "JR関西本線 JR難波駅",
        "station_walk_minutes": 5,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 5,
        "facilities": {"式場": True, "親族控室": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 83000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["火葬式対応", "家族葬対応", "駅近", "イオンブランド"],
        "operator_name": "イオンライフ株式会社",
        "rating_avg": 3.9,
        "review_count": 75
    },
    # 大阪市残り: 北区追加
    {
        "name": "梅田メモリアルホール",
        "slug": "osaka-umeda-memorial",
        "venue_type": "private_hall",
        "description": "大阪市北区にある都市型の葬儀会館。梅田エリアのアクセスの良さを生かし、小規模な家族葬やお別れの会に対応。洗練された空間で都心にいながら故人を偲べます。",
        "address": "大阪府大阪市北区堂山町1-5",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7040,
        "longitude": 135.5030,
        "nearest_station": "阪急各線 大阪梅田駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 3,
        "facilities": {"式場": True, "親族控室": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}],
        "features": ["家族葬対応", "都市型", "梅田エリア"],
        "operator_name": "梅田メモリアル",
        "rating_avg": 4.0,
        "review_count": 43
    },
    # 住吉区追加
    {
        "name": "イオンのお葬式 住吉ホール",
        "slug": "osaka-aeon-sumiyoshi",
        "venue_type": "private_hall",
        "description": "大阪市住吉区にあるイオンライフの提携葬儀会館。JR阪和線我孫子町駅から徒歩8分。イオンブランドの安心感と明朗会計で、火葬式から家族葬まで提供しています。",
        "address": "大阪府大阪市住吉区我孫子東2-5-8",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6050,
        "longitude": 135.5180,
        "nearest_station": "JR阪和線 我孫子町駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 83000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["火葬式対応", "家族葬対応", "イオンブランド", "明朗会計"],
        "operator_name": "イオンライフ株式会社",
        "rating_avg": 3.8,
        "review_count": 48
    },
    # 生野区追加
    {
        "name": "泉屋 生野ホール",
        "slug": "osaka-izumiya-ikuno",
        "venue_type": "private_hall",
        "description": "大阪市生野区にある泉屋の葬儀会館。老舗葬儀社ならではの伝統と経験を活かし、生野区の多文化な地域性にも配慮した葬儀サービスを提供しています。",
        "address": "大阪府大阪市生野区田島5-8-12",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6430,
        "longitude": 135.5460,
        "nearest_station": "JR大阪環状線 東部市場前駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "老舗葬儀社", "多文化対応"],
        "operator_name": "泉屋",
        "rating_avg": 4.0,
        "review_count": 38
    },
    # 東成区追加
    {
        "name": "ティア東成",
        "slug": "osaka-tier-higashinari",
        "venue_type": "private_hall",
        "description": "大阪市東成区にあるティアの家族葬ホール。大阪メトロ中央線深江橋駅から徒歩6分。1日1組貸切の家族葬に対応し、明朗会計と温かなスタッフ対応が好評です。",
        "address": "大阪府大阪市東成区深江南1-12-5",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.6660,
        "longitude": 135.5540,
        "nearest_station": "大阪メトロ中央線 深江橋駅",
        "station_walk_minutes": 6,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "1日1組貸切", "駅近", "明朗会計"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.1,
        "review_count": 39
    },
    # 西淀川区追加 (公共施設)
    {
        "name": "西淀川区民ホール",
        "slug": "osaka-nishiyodogawa-kumin",
        "venue_type": "public_facility",
        "description": "大阪市西淀川区にある公共施設。区民向けの多目的ホールで、小規模な家族葬やお別れの会に低価格で利用できます。佃斎場にもアクセスしやすい立地です。",
        "address": "大阪府大阪市西淀川区佃2-5-18",
        "prefecture_slug": "osaka",
        "city_slug": "osaka-city",
        "latitude": 34.7130,
        "longitude": 135.4510,
        "nearest_station": "JR東西線 御幣島駅",
        "station_walk_minutes": 10,
        "capacity_max": 30,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "控室": True, "駐車場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 220000}],
        "features": ["公共施設", "低価格", "少人数対応", "佃斎場近く"],
        "operator_name": "大阪市",
        "rating_avg": 3.5,
        "review_count": 10
    },

    # =============================================
    # 堺市（sakai）: 25件
    # =============================================
    {
        "name": "堺市立斎場",
        "slug": "osaka-sakai-shiritsu-saijo",
        "venue_type": "public_crematorium",
        "description": "堺市堺区にある公営の斎場・火葬場。堺市民の方は使用料が大幅に減額されます。火葬炉を備え、式場も併設。南海高野線堺東駅からバスでアクセス可能。広い駐車場を完備しています。",
        "address": "大阪府堺市堺区田出井町8-36",
        "prefecture_slug": "osaka",
        "city_slug": "sakai",
        "latitude": 34.5700,
        "longitude": 135.4830,
        "nearest_station": "南海高野線 堺東駅",
        "station_walk_minutes": 15,
        "capacity_max": 100,
        "hall_count": 2,
        "has_crematorium": True,
        "parking_count": 100,
        "facilities": {"式場": True, "休憩室": True, "駐車場": True, "バリアフリー": True, "売店": True, "霊安室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}],
        "features": ["火葬場併設", "公営斎場", "堺市民割引", "大型駐車場"],
        "operator_name": "堺市",
        "rating_avg": 3.9,
        "review_count": 82
    },
    {
        "name": "公益社 堺中央ホール",
        "slug": "osaka-koeisha-sakai-chuo",
        "venue_type": "private_hall",
        "description": "堺市堺区にある公益社の大型葬儀会館。南海本線堺駅から徒歩8分。家族葬から大規模な一般葬まで対応可能な複数の式場を備え、格式ある葬儀を執り行えます。",
        "address": "大阪府堺市堺区市之町東3-2-1",
        "prefecture_slug": "osaka",
        "city_slug": "sakai",
        "latitude": 34.5770,
        "longitude": 135.4800,
        "nearest_station": "南海本線 堺駅",
        "station_walk_minutes": 8,
        "capacity_max": 150,
        "hall_count": 3,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True, "僧侶控室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "一般葬対応", "大規模対応", "駅近", "公益社ブランド"],
        "operator_name": "公益社（燦ホールディングス）",
        "rating_avg": 4.3,
        "review_count": 112
    },
    {
        "name": "ベルコシティホール堺",
        "slug": "osaka-bellco-sakai",
        "venue_type": "private_hall",
        "description": "堺市堺区にあるベルコの葬儀会館。堺東駅から徒歩7分の好立地。家族葬・一般葬に対応した充実した設備を備え、ベルコグループの安定したサービスを提供しています。",
        "address": "大阪府堺市堺区北瓦町2-4-16",
        "prefecture_slug": "osaka",
        "city_slug": "sakai",
        "latitude": 34.5730,
        "longitude": 135.4840,
        "nearest_station": "南海高野線 堺東駅",
        "station_walk_minutes": 7,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "ベルコグループ"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.1,
        "review_count": 72
    },
    {
        "name": "家族葬のファミーユ 堺ホール",
        "slug": "osaka-famille-sakai",
        "venue_type": "private_hall",
        "description": "堺市堺区にある家族葬専門ホール。少人数のお葬式に特化し、温かみのある空間で故人を偲ぶ時間を提供。明朗会計で安心のプラン設定が特徴です。",
        "address": "大阪府堺市堺区熊野町東4-3-15",
        "prefecture_slug": "osaka",
        "city_slug": "sakai",
        "latitude": 34.5690,
        "longitude": 135.4870,
        "nearest_station": "南海高野線 堺東駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "明朗会計"],
        "operator_name": "株式会社ファミーユ",
        "rating_avg": 4.2,
        "review_count": 65
    },
    {
        "name": "ティア堺",
        "slug": "osaka-tier-sakai",
        "venue_type": "private_hall",
        "description": "堺市堺区にあるティアの葬儀会館。1日1組貸切の家族葬に対応し、明朗会計と温かなスタッフ対応が好評。堺エリアの家族葬ニーズに応えています。",
        "address": "大阪府堺市堺区向陵西町1-2-8",
        "prefecture_slug": "osaka",
        "city_slug": "sakai",
        "latitude": 34.5650,
        "longitude": 135.4920,
        "nearest_station": "JR阪和線 三国ヶ丘駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "1日1組貸切", "明朗会計"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.1,
        "review_count": 55
    },
    {
        "name": "小さなお葬式 堺ホール",
        "slug": "osaka-chiisana-sakai",
        "venue_type": "private_hall",
        "description": "堺市堺区にある小さなお葬式の提携ホール。火葬式から家族葬まで明朗価格で提供。堺市民の方にリーズナブルな葬儀プランが好評です。",
        "address": "大阪府堺市堺区南花田口町2-3-20",
        "prefecture_slug": "osaka",
        "city_slug": "sakai",
        "latitude": 34.5740,
        "longitude": 135.4860,
        "nearest_station": "南海高野線 堺東駅",
        "station_walk_minutes": 5,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 189000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["火葬式対応", "家族葬対応", "駅近", "明朗会計"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 3.9,
        "review_count": 68
    },
    {
        "name": "泉屋 堺ホール",
        "slug": "osaka-izumiya-sakai",
        "venue_type": "private_hall",
        "description": "堺市堺区にある泉屋の葬儀会館。堺の歴史ある商人の町にふさわしい格式と温かみのあるサービスを提供。家族葬から一般葬まで対応しています。",
        "address": "大阪府堺市堺区甲斐町東1-1-10",
        "prefecture_slug": "osaka",
        "city_slug": "sakai",
        "latitude": 34.5780,
        "longitude": 135.4780,
        "nearest_station": "阪堺電車 宿院停留場",
        "station_walk_minutes": 5,
        "capacity_max": 70,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 12,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 340000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "老舗葬儀社", "駅近"],
        "operator_name": "泉屋",
        "rating_avg": 4.0,
        "review_count": 48
    },
    # 堺市中区
    {
        "name": "ベルコシティホール堺中",
        "slug": "osaka-bellco-sakai-naka",
        "venue_type": "private_hall",
        "description": "堺市中区にあるベルコの葬儀会館。泉北エリアの住宅街に位置し、家族葬・一般葬に対応。駐車場が広く、車でのアクセスが便利です。",
        "address": "大阪府堺市中区深井沢町2420",
        "prefecture_slug": "osaka",
        "city_slug": "sakai",
        "latitude": 34.5370,
        "longitude": 135.4890,
        "nearest_station": "泉北高速鉄道 深井駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "駐車場完備", "ベルコグループ"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 45
    },
    {
        "name": "家族葬のファミーユ 深井ホール",
        "slug": "osaka-famille-fukai",
        "venue_type": "private_hall",
        "description": "堺市中区深井にある家族葬専門ホール。泉北高速鉄道深井駅から徒歩10分。泉北ニュータウンエリアの方々にご利用いただいている施設です。",
        "address": "大阪府堺市中区深井清水町3750",
        "prefecture_slug": "osaka",
        "city_slug": "sakai",
        "latitude": 34.5340,
        "longitude": 135.4920,
        "nearest_station": "泉北高速鉄道 深井駅",
        "station_walk_minutes": 10,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "泉北エリア"],
        "operator_name": "株式会社ファミーユ",
        "rating_avg": 4.1,
        "review_count": 38
    },
    # 堺市東区
    {
        "name": "公益社 堺東ホール",
        "slug": "osaka-koeisha-sakai-higashi",
        "venue_type": "private_hall",
        "description": "堺市東区にある公益社の葬儀会館。初芝エリアの閑静な住宅街に位置し、家族葬から一般葬まで対応。公益社の確かなサービスを提供しています。",
        "address": "大阪府堺市東区日置荘西町1-35-12",
        "prefecture_slug": "osaka",
        "city_slug": "sakai",
        "latitude": 34.5440,
        "longitude": 135.5130,
        "nearest_station": "南海高野線 初芝駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "一般葬対応", "公益社ブランド"],
        "operator_name": "公益社（燦ホールディングス）",
        "rating_avg": 4.2,
        "review_count": 56
    },
    # 堺市西区
    {
        "name": "ベルコシティホール堺西",
        "slug": "osaka-bellco-sakai-nishi",
        "venue_type": "private_hall",
        "description": "堺市西区にあるベルコの葬儀会館。JR阪和線鳳駅から徒歩10分。堺市西部エリアの家族葬・一般葬に対応した施設です。",
        "address": "大阪府堺市西区鳳中町5-120",
        "prefecture_slug": "osaka",
        "city_slug": "sakai",
        "latitude": 34.5420,
        "longitude": 135.4590,
        "nearest_station": "JR阪和線 鳳駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "駐車場完備", "ベルコグループ"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 42
    },
    {
        "name": "小さなお葬式 鳳ホール",
        "slug": "osaka-chiisana-otori",
        "venue_type": "private_hall",
        "description": "堺市西区にある小さなお葬式の提携ホール。JR阪和線鳳駅から徒歩8分。火葬式から家族葬まで明朗価格で提供しています。",
        "address": "大阪府堺市西区鳳東町2-15-8",
        "prefecture_slug": "osaka",
        "city_slug": "sakai",
        "latitude": 34.5410,
        "longitude": 135.4620,
        "nearest_station": "JR阪和線 鳳駅",
        "station_walk_minutes": 8,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 89000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 289000}],
        "features": ["火葬式対応", "家族葬対応", "駅近", "明朗会計"],
        "operator_name": "株式会社ユニクエスト",
        "rating_avg": 3.9,
        "review_count": 35
    },
    # 堺市南区
    {
        "name": "泉北メモリアルホール",
        "slug": "osaka-senboku-memorial",
        "venue_type": "private_hall",
        "description": "堺市南区の泉北ニュータウンエリアにある葬儀会館。泉北高速鉄道泉ヶ丘駅から徒歩10分。ニュータウンの高齢化に伴う葬儀需要に応え、家族葬を中心にサービスを提供しています。",
        "address": "大阪府堺市南区竹城台1-1-5",
        "prefecture_slug": "osaka",
        "city_slug": "sakai",
        "latitude": 34.5050,
        "longitude": 135.4810,
        "nearest_station": "泉北高速鉄道 泉ヶ丘駅",
        "station_walk_minutes": 10,
        "capacity_max": 60,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}],
        "features": ["家族葬対応", "駐車場完備", "泉北ニュータウン"],
        "operator_name": "泉北メモリアル",
        "rating_avg": 4.0,
        "review_count": 38
    },
    {
        "name": "公益社 泉北ホール",
        "slug": "osaka-koeisha-senboku",
        "venue_type": "private_hall",
        "description": "堺市南区にある公益社の葬儀会館。泉北高速鉄道栂・美木多駅から徒歩12分。泉北エリアの方々に公益社の高品質なサービスを提供しています。",
        "address": "大阪府堺市南区原山台2-3-5",
        "prefecture_slug": "osaka",
        "city_slug": "sakai",
        "latitude": 34.4980,
        "longitude": 135.4780,
        "nearest_station": "泉北高速鉄道 栂・美木多駅",
        "station_walk_minutes": 12,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 20,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 385000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 660000}],
        "features": ["家族葬対応", "一般葬対応", "公益社ブランド", "泉北エリア"],
        "operator_name": "公益社（燦ホールディングス）",
        "rating_avg": 4.2,
        "review_count": 48
    },
    {
        "name": "ティア泉ヶ丘",
        "slug": "osaka-tier-izumigaoka",
        "venue_type": "private_hall",
        "description": "堺市南区にあるティアの家族葬ホール。泉北高速鉄道泉ヶ丘駅から徒歩8分。泉北ニュータウンの方々に明朗会計の家族葬プランを提供しています。",
        "address": "大阪府堺市南区茶山台1-2-1",
        "prefecture_slug": "osaka",
        "city_slug": "sakai",
        "latitude": 34.5020,
        "longitude": 135.4830,
        "nearest_station": "泉北高速鉄道 泉ヶ丘駅",
        "station_walk_minutes": 8,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 550000}],
        "features": ["家族葬対応", "1日1組貸切", "駅近", "明朗会計"],
        "operator_name": "株式会社ティア",
        "rating_avg": 4.1,
        "review_count": 42
    },
    # 堺市北区
    {
        "name": "ベルコシティホール堺北",
        "slug": "osaka-bellco-sakai-kita",
        "venue_type": "private_hall",
        "description": "堺市北区にあるベルコの葬儀会館。大阪メトロ御堂筋線北花田駅から徒歩8分。大阪市内からのアクセスも良好で、家族葬・一般葬に対応しています。",
        "address": "大阪府堺市北区北花田町3-18-15",
        "prefecture_slug": "osaka",
        "city_slug": "sakai",
        "latitude": 34.5620,
        "longitude": 135.4970,
        "nearest_station": "大阪メトロ御堂筋線 北花田駅",
        "station_walk_minutes": 8,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 330000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 580000}],
        "features": ["家族葬対応", "一般葬対応", "駅近", "ベルコグループ"],
        "operator_name": "株式会社ベルコ",
        "rating_avg": 4.0,
        "review_count": 52
    },
    {
        "name": "家族葬のファミーユ 北花田ホール",
        "slug": "osaka-famille-kitahanada",
        "venue_type": "private_hall",
        "description": "堺市北区にある家族葬専門ホール。北花田エリアの住宅街に位置し、少人数の温かな葬儀を提供しています。イオンモール堺北花田にも近い便利な立地です。",
        "address": "大阪府堺市北区北花田町2-126",
        "prefecture_slug": "osaka",
        "city_slug": "sakai",
        "latitude": 34.5600,
        "longitude": 135.4990,
        "nearest_station": "大阪メトロ御堂筋線 北花田駅",
        "station_walk_minutes": 6,
        "capacity_max": 35,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 8,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬専門", "少人数対応", "駅近"],
        "operator_name": "株式会社ファミーユ",
        "rating_avg": 4.2,
        "review_count": 40
    },
    # 堺市美原区
    {
        "name": "美原メモリアルホール",
        "slug": "osaka-mihara-memorial",
        "venue_type": "private_hall",
        "description": "堺市美原区にある地域密着型の葬儀会館。緑豊かな美原区の住宅街に位置し、家族葬を中心に地域の方々にご利用いただいています。駐車場が広く車でのアクセスに便利です。",
        "address": "大阪府堺市美原区黒山167-1",
        "prefecture_slug": "osaka",
        "city_slug": "sakai",
        "latitude": 34.5180,
        "longitude": 135.5240,
        "nearest_station": "南海バス 美原区役所前",
        "station_walk_minutes": 15,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 25,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["家族葬対応", "駐車場完備", "地域密着"],
        "operator_name": "美原メモリアル",
        "rating_avg": 3.8,
        "review_count": 22
    },
    # 堺区追加（寺院）
    {
        "name": "南宗寺 式場",
        "slug": "osaka-nanshuji-shikijo",
        "venue_type": "temple_hall",
        "description": "堺市堺区にある臨済宗の名刹・南宗寺の式場。千利休ゆかりの茶の湯文化が息づく歴史ある寺院で、格式高い仏式葬儀を執り行えます。堺の文化と伝統を感じる空間です。",
        "address": "大阪府堺市堺区南旅篭町東3-1-2",
        "prefecture_slug": "osaka",
        "city_slug": "sakai",
        "latitude": 34.5680,
        "longitude": 135.4850,
        "nearest_station": "阪堺電車 御陵前停留場",
        "station_walk_minutes": 5,
        "capacity_max": 50,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "控室": True, "駐車場": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 380000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 620000}],
        "features": ["寺院式場", "仏式葬儀", "名刹", "歴史的寺院"],
        "operator_name": "南宗寺",
        "rating_avg": 4.1,
        "review_count": 28
    },
    # 堺市堺区追加
    {
        "name": "セレモニーホール堺",
        "slug": "osaka-ceremony-sakai",
        "venue_type": "private_hall",
        "description": "堺市堺区にある互助会系の葬儀会館。堺東駅から徒歩10分。経験豊富なスタッフが丁寧にサポートし、伝統的な葬儀から家族葬まで幅広く対応しています。",
        "address": "大阪府堺市堺区中瓦町1-4-5",
        "prefecture_slug": "osaka",
        "city_slug": "sakai",
        "latitude": 34.5760,
        "longitude": 135.4820,
        "nearest_station": "南海高野線 堺東駅",
        "station_walk_minutes": 10,
        "capacity_max": 80,
        "hall_count": 2,
        "has_crematorium": False,
        "parking_count": 15,
        "facilities": {"式場": True, "親族控室": True, "お清め所": True, "駐車場": True, "バリアフリー": True, "安置室": True, "宿泊可": True},
        "price_plans": [{"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 350000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 600000}],
        "features": ["家族葬対応", "一般葬対応", "互助会系"],
        "operator_name": "セレモニーホール",
        "rating_avg": 3.9,
        "review_count": 42
    },
    # 堺市中区追加
    {
        "name": "イオンのお葬式 堺中ホール",
        "slug": "osaka-aeon-sakai-naka",
        "venue_type": "private_hall",
        "description": "堺市中区にあるイオンライフの提携葬儀会館。泉北エリアの住宅街に位置し、イオンブランドの安心感と明朗会計で葬儀を提供しています。",
        "address": "大阪府堺市中区土塔町3065",
        "prefecture_slug": "osaka",
        "city_slug": "sakai",
        "latitude": 34.5300,
        "longitude": 135.4950,
        "nearest_station": "泉北高速鉄道 深井駅",
        "station_walk_minutes": 12,
        "capacity_max": 40,
        "hall_count": 1,
        "has_crematorium": False,
        "parking_count": 10,
        "facilities": {"式場": True, "親族控室": True, "バリアフリー": True, "安置室": True, "駐車場": True},
        "price_plans": [{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 83000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 198000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}],
        "features": ["火葬式対応", "家族葬対応", "イオンブランド", "明朗会計"],
        "operator_name": "イオンライフ株式会社",
        "rating_avg": 3.8,
        "review_count": 32
    },
]

# 10件ずつバッチ投入
total = len(venues)
print(f"大阪 バッチ3（大阪市残り+堺市）: 合計 {total} 件を投入開始")

for i in range(0, total, 10):
    batch = venues[i:i+10]
    status = insert_batch(batch)
    end = min(i+10, total)
    print(f"  [{i+1}-{end}] HTTP {status}")
    if status != "201":
        data_json = json.dumps(batch, ensure_ascii=False)
        result = subprocess.run([
            "curl", "-s",
            "-X", "POST", SUPABASE_URL,
            "-H", f"apikey: {API_KEY}",
            "-H", f"Authorization: Bearer {API_KEY}",
            "-H", "Content-Type: application/json",
            "-H", "Prefer: return=minimal",
            "-H", "User-Agent: Mozilla/5.0",
            "-d", data_json
        ], capture_output=True, text=True)
        print(f"  エラー詳細: {result.stdout[:500]}")
    time.sleep(0.5)

print(f"\nバッチ3完了: {total}件")
