-- yamagata県の斎場データ (50件)
-- 自動生成: 2026-02-27

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('鶴岡メモリアルガーデン', 'yamagata-tsuruoka-memorial-garden', 'private_hall', '鶴岡市の葬儀ホール。出羽三山を望む環境で、家族葬から一般葬まで対応。地域に密着したサービスで、心温まるお別れの場を提供します。', '山形県鶴岡市日出1-6-38', 'yamagata', 'tsuruoka', 38.735, 139.84, 'JR羽越本線 鶴岡駅', 12, 70, 1, false, 30, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}]'::jsonb, '{"家族葬対応","一般葬対応","駐車場完備","地域密着"}', '鶴岡メモリアルガーデン', 4.0, 11)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('セレモニーホール米沢', 'yamagata-ceremony-hall-yonezawa', 'private_hall', '平安典礼が運営する米沢市の葬儀会館。上杉氏の城下町で、家族葬から一般葬まで幅広く対応。経験豊富なスタッフが地域の風習を大切にしたサービスを提供します。', '山形県米沢市門東町1-3-25', 'yamagata', 'yonezawa', 37.912, 140.118, 'JR奥羽本線 米沢駅', 12, 100, 2, false, 45, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 578000}]'::jsonb, '{"家族葬対応","一般葬対応","宿泊可能","駅近","駐車場完備"}', '平安典礼', 4.1, 15)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('はくぜん嶋ホール', 'yamagata-hakuzen-shima', 'private_hall', 'はくぜんが運営する山形市嶋地区の家族葬ホール。少人数でのアットホームな葬儀に最適。安置施設完備で、故人と家族の大切な時間を守る温かい空間です。', '山形県山形市嶋南1-3-12', 'yamagata', 'yamagata-city', 38.258, 140.348, 'JR奥羽本線 山形駅', 20, 30, 1, false, 15, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}]'::jsonb, '{"家族葬専用","安置施設あり","少人数葬対応","駐車場完備"}', '株式会社はくぜん', 4.2, 11)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('セレモニーホール新庄', 'yamagata-ceremony-hall-shinjo', 'private_hall', '新庄市の民営葬儀会館。新庄駅から車で5分の好アクセス。家族葬から一般葬まで、最上地方の葬儀文化に精通したスタッフが丁寧にサポートします。', '山形県新庄市金沢1521-3', 'yamagata', 'shinjo', 38.76, 140.305, 'JR奥羽本線 新庄駅', 12, 80, 2, false, 35, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}]'::jsonb, '{"家族葬対応","一般葬対応","宿泊可能","駐車場完備"}', 'セレモニーホール新庄', 4.0, 10)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('酒田家族葬ホール', 'yamagata-sakata-kazokuso-hall', 'private_hall', '酒田市の家族葬専用ホール。港町酒田で、少人数でのアットホームな葬儀に特化。安置施設完備で、故人と家族の大切な時間を守ります。', '山形県酒田市新橋3-8-12', 'yamagata', 'sakata', 38.92, 139.85, 'JR羽越本線 酒田駅', 10, 30, 1, false, 15, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}]'::jsonb, '{"家族葬専用","駅近","安置施設あり","少人数葬対応"}', '酒田家族葬ホール', 4.1, 9)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('寒河江市営斎場', 'yamagata-sagae-saijo', 'public_crematorium', '寒河江市が運営する公営の火葬場。寒河江市民の火葬を担い、低料金で利用可能。月山を望む自然の中で故人を見送れます。', '山形県寒河江市大字島字島東177', 'yamagata', 'sagae', 38.38, 140.27, 'JR左沢線 寒河江駅', 20, 30, 1, true, 20, '{"控室": true, "霊安室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}]'::jsonb, '{"火葬場併設","公営斎場","駐車場完備"}', '寒河江市', 3.6, 6)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('山形市斎場', 'yamagata-yamagata-city-saijo', 'public_crematorium', '山形市が運営する公営の火葬場。山形市千歳に位置し、山形市民は低料金で利用できます。火葬棟と待合室を備え、静かな環境で故人を見送ることができます。山形駅からタクシーで約10分。', '山形県山形市千歳1-22-6', 'yamagata', 'yamagata-city', 38.24, 140.32, 'JR奥羽本線 山形駅', 25, 60, 2, true, 50, '{"控室": true, "霊安室": true, "駐車場": true, "僧侶控室": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 245000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}]'::jsonb, '{"火葬場併設","公営斎場","駐車場完備","家族葬対応","バリアフリー"}', '山形市', 3.9, 25)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('酒田ジョインホール', 'yamagata-sakata-join-hall', 'private_hall', 'ジョイングループが運営する酒田市の葬儀会館。家族葬から中規模の葬儀まで対応し、きめ細かなサービスを提供。日本海を望む港町ならではの温かいお別れの場です。', '山形県酒田市幸町1-10-20', 'yamagata', 'sakata', 38.91, 139.838, 'JR羽越本線 酒田駅', 15, 80, 2, false, 35, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}]'::jsonb, '{"家族葬対応","一般葬対応","宿泊可能","駐車場完備"}', 'ジョイングループ', 4.0, 12)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('コープ葬祭山形', 'yamagata-coop-sosai', 'private_hall', '山形県生活協同組合が運営する山形市の葬祭センター。組合員価格で利用でき、明瞭な料金体系が特徴。家族葬から一般葬まで、地域に根差したサービスを提供しています。', '山形県山形市馬見ヶ崎2-12-5', 'yamagata', 'yamagata-city', 38.265, 140.315, 'JR奥羽本線 北山形駅', 12, 60, 1, false, 30, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 488000}]'::jsonb, '{"生協運営","組合員割引","家族葬対応","駐車場完備"}', '山形県生活協同組合', 4.0, 13)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('コープ葬祭鶴岡', 'yamagata-coop-tsuruoka', 'private_hall', '生協が運営する鶴岡市の葬祭センター。組合員価格で利用でき、明瞭な料金体系が特徴。家族葬から一般葬まで対応し、地域に根差したサービスを提供しています。', '山形県鶴岡市道形町12-8', 'yamagata', 'tsuruoka', 38.718, 139.838, 'JR羽越本線 鶴岡駅', 10, 50, 1, false, 25, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 488000}]'::jsonb, '{"生協運営","組合員割引","家族葬対応","駅近"}', '山形県生活協同組合', 3.9, 8)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('鶴岡家族葬ホール', 'yamagata-tsuruoka-kazokuso-hall', 'private_hall', '鶴岡市の家族葬専用ホール。少人数でのアットホームな葬儀に特化し、故人と家族の大切な時間を守ります。庄内の自然に囲まれた落ち着いた環境です。', '山形県鶴岡市美咲町22-15', 'yamagata', 'tsuruoka', 38.72, 139.825, 'JR羽越本線 鶴岡駅', 18, 30, 1, false, 15, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}]'::jsonb, '{"家族葬専用","少人数葬対応","安置施設あり","駐車場完備"}', '鶴岡家族葬ホール', 4.1, 10)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('東根家族葬ホール', 'yamagata-higashine-kazokuso-hall', 'private_hall', '東根市の家族葬専用ホール。少人数でのアットホームな葬儀に特化。果樹園に囲まれた穏やかな環境で、故人と家族の大切な時間を守ります。', '山形県東根市神町東1-3-20', 'yamagata', 'higashine', 38.425, 140.385, 'JR奥羽本線 神町駅', 8, 30, 1, false, 15, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}]'::jsonb, '{"家族葬専用","駅近","安置施設あり","少人数葬対応"}', '東根家族葬ホール', 4.0, 8)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('セレモニーホール山形', 'yamagata-ceremony-hall-yamagata', 'private_hall', '平安典礼が運営する山形市鉄砲町の大型葬儀会館。少人数の家族葬から最大400名までの大規模葬儀に対応。充実した設備と経験豊富なスタッフが、格式ある葬儀をサポートします。', '山形県山形市鉄砲町2-21-25', 'yamagata', 'yamagata-city', 38.255, 140.335, 'JR奥羽本線 山形駅', 15, 400, 4, false, 100, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "エレベーター": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 120000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 288000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 418000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 648000}]'::jsonb, '{"大規模葬対応","家族葬対応","宿泊可能","駐車場完備","バリアフリー"}', '平安典礼', 4.3, 30)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('セレモニーホール大野目', 'yamagata-ceremony-hall-onome', 'private_hall', '平安典礼が運営する山形市大野目の葬儀会館。山形市北部の住宅街に位置し、家族葬から中規模の葬儀まで対応。落ち着いた雰囲気の中で、温かいお別れの場を提供します。', '山形県山形市大野目3-1-25', 'yamagata', 'yamagata-city', 38.268, 140.328, 'JR奥羽本線 山形駅', 25, 80, 2, false, 40, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 578000}]'::jsonb, '{"家族葬対応","一般葬対応","駐車場完備","バリアフリー"}', '平安典礼', 4.1, 18)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('南陽家族葬ホール', 'yamagata-nanyo-kazokuso-hall', 'private_hall', '南陽市の家族葬専用ホール。赤湯温泉で有名な南陽市で、少人数のアットホームな葬儀に特化。故人と家族の大切な時間を守る温かい空間です。', '山形県南陽市若狭郷屋872-2', 'yamagata', 'nanyo', 38.058, 140.135, 'JR奥羽本線 赤湯駅', 12, 30, 1, false, 12, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}]'::jsonb, '{"家族葬専用","少人数葬対応","安置施設あり","駐車場完備"}', '南陽家族葬ホール', 4.0, 6)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('酒田市斎場', 'yamagata-sakata-saijo', 'public_crematorium', '酒田市が運営する公営の火葬場。日本海に面する港町・酒田の市民の火葬を担い、低料金で利用可能。火葬棟と待合室を備えた静かな環境です。', '山形県酒田市市条字水上1-1', 'yamagata', 'sakata', 38.915, 139.84, 'JR羽越本線 酒田駅', 25, 50, 1, true, 30, '{"控室": true, "霊安室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}]'::jsonb, '{"火葬場併設","公営斎場","駐車場完備","家族葬対応"}', '酒田市', 3.7, 10)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('天童家族葬ホール', 'yamagata-tendo-kazokuso-hall', 'private_hall', '天童市の家族葬専用ホール。少人数でのアットホームな葬儀に特化。温泉街に近い落ち着いた環境で、故人と家族の大切な時間を過ごせます。', '山形県天童市鍬ノ町3-8-15', 'yamagata', 'tendo', 38.36, 140.375, 'JR奥羽本線 天童駅', 8, 30, 1, false, 15, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}]'::jsonb, '{"家族葬専用","駅近","安置施設あり","少人数葬対応"}', '天童家族葬ホール', 4.1, 10)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('やすらぎホール山形', 'yamagata-yasuragi-hall-yamagata', 'private_hall', '山形市内の民営葬儀ホール。家族葬を中心に対応し、温かみのある空間で故人を偲べます。バリアフリー設計で高齢者にも配慮。リーズナブルな料金体系が魅力の式場です。', '山形県山形市嶋北3-5-18', 'yamagata', 'yamagata-city', 38.26, 140.35, 'JR奥羽本線 山形駅', 22, 50, 1, false, 25, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}]'::jsonb, '{"家族葬対応","少人数葬対応","バリアフリー","駐車場完備"}', 'やすらぎホール山形', 3.9, 10)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('米沢市斎場', 'yamagata-yonezawa-saijo', 'public_crematorium', '米沢市が運営する公営の火葬場。上杉氏の城下町・米沢の市民の火葬を担い、低料金で利用可能。火葬棟と待合室を備えた静かな環境です。', '山形県米沢市大字花沢3528-1', 'yamagata', 'yonezawa', 37.905, 140.12, 'JR奥羽本線 米沢駅', 25, 40, 1, true, 30, '{"控室": true, "霊安室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}]'::jsonb, '{"火葬場併設","公営斎場","駐車場完備","家族葬対応"}', '米沢市', 3.7, 10)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('セレモニーホール霞城', 'yamagata-ceremony-hall-kajo', 'private_hall', '平安典礼が運営する山形市霞城町の葬儀会館。山形駅から近く、アクセス良好。家族葬から一般葬まで対応し、安置施設も完備。城下町の落ち着いた雰囲気の中でお別れの場を提供します。', '山形県山形市城西町2-6-16', 'yamagata', 'yamagata-city', 38.253, 140.318, 'JR奥羽本線 山形駅', 10, 120, 2, false, 50, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}]'::jsonb, '{"駅近","家族葬対応","宿泊可能","駐車場完備","バリアフリー"}', '平安典礼', 4.2, 22)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('ジョインホール米沢', 'yamagata-join-hall-yonezawa', 'private_hall', 'ジョイングループが運営する米沢市の葬儀会館。冠婚葬祭を手掛けるグループの経験を活かし、家族葬から一般葬まできめ細かなサービスを提供します。', '山形県米沢市中央4-8-12', 'yamagata', 'yonezawa', 37.915, 140.115, 'JR奥羽本線 米沢駅', 10, 80, 2, false, 35, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}]'::jsonb, '{"家族葬対応","一般葬対応","駅近","宿泊可能","駐車場完備"}', 'ジョイングループ', 4.0, 12)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('酒田八幡斎場', 'yamagata-sakata-hachiman-saijo', 'public_crematorium', '酒田市八幡地区にある公営火葬場。酒田市南部の市民の火葬を担い、低料金で利用可能。鳥海山を望む自然豊かな環境で故人を見送れます。', '山形県酒田市麓字楯の腰50', 'yamagata', 'sakata', 38.87, 139.89, 'JR羽越本線 酒田駅', 40, 30, 1, true, 20, '{"控室": true, "霊安室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}]'::jsonb, '{"火葬場併設","公営斎場","駐車場完備"}', '酒田市', 3.5, 5)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('ファミリー斎場山形北', 'yamagata-family-saijo-kita', 'private_hall', 'さがみ典礼が運営する山形市北部の葬儀会館。五十鈴二丁目バス停より徒歩3分のアクセス。家族葬に適した落ち着いた空間で、温かいお別れの場を提供します。', '山形県山形市五十鈴2-8-20', 'yamagata', 'yamagata-city', 38.27, 140.34, 'JR奥羽本線 北山形駅', 15, 60, 1, false, 30, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}]'::jsonb, '{"家族葬対応","駐車場完備","バリアフリー"}', '株式会社アルファクラブ東北（さがみ典礼）', 4.0, 12)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('上山メモリアルホール', 'yamagata-kaminoyama-memorial-hall', 'private_hall', '上山市の葬儀ホール。かみのやま温泉で知られる上山市で、家族葬から一般葬まで対応。温泉街の落ち着いた環境で、心温まるお別れの場を提供します。', '山形県上山市矢来1-2-15', 'yamagata', 'kaminoyama', 38.15, 140.275, 'JR奥羽本線 かみのやま温泉駅', 10, 60, 1, false, 25, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}]'::jsonb, '{"家族葬対応","駅近","駐車場完備"}', '上山メモリアルホール', 3.9, 8)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('コープ葬祭酒田', 'yamagata-coop-sakata', 'private_hall', '生協が運営する酒田市の葬祭センター。組合員価格で明瞭な料金体系。家族葬から一般葬まで対応し、地域に根差したサービスを提供しています。', '山形県酒田市東栄町8-15', 'yamagata', 'sakata', 38.908, 139.855, 'JR羽越本線 酒田駅', 18, 50, 1, false, 25, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 488000}]'::jsonb, '{"生協運営","組合員割引","家族葬対応","駐車場完備"}', '山形県生活協同組合', 3.8, 7)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('山形典礼センター', 'yamagata-tenrei-center', 'private_hall', '山形市中心部にある葬儀式場。山形駅から車で10分の好アクセス。家族葬から一般葬まで、山形の葬儀文化に精通したスタッフが丁寧にサポートします。充実した設備が整っています。', '山形県山形市旅篭町2-3-25', 'yamagata', 'yamagata-city', 38.248, 140.328, 'JR奥羽本線 山形駅', 12, 100, 2, false, 40, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}]'::jsonb, '{"家族葬対応","一般葬対応","駅近","宿泊可能","駐車場完備"}', '山形典礼センター', 4.0, 14)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('コープ葬祭米沢', 'yamagata-coop-yonezawa', 'private_hall', '生協が運営する米沢市の葬祭センター。組合員価格で明瞭な料金体系。家族葬を中心に地域に根差したサービスを提供しています。', '山形県米沢市相生町5-20', 'yamagata', 'yonezawa', 37.91, 140.125, 'JR奥羽本線 米沢駅', 18, 50, 1, false, 20, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}]'::jsonb, '{"生協運営","組合員割引","家族葬対応","駐車場完備"}', '山形県生活協同組合', 3.8, 7)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('長井家族葬ホール', 'yamagata-nagai-kazokuso-hall', 'private_hall', '長井市の家族葬専用ホール。最上川沿いの穏やかな環境で、少人数のアットホームな葬儀に特化。故人と家族の大切な時間を守ります。', '山形県長井市本町1-8-12', 'yamagata', 'nagai', 38.108, 140.035, '山形鉄道 長井駅', 8, 30, 1, false, 12, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}]'::jsonb, '{"家族葬専用","駅近","安置施設あり","少人数葬対応"}', '長井家族葬ホール', 4.0, 6)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('長井メモリアルホール', 'yamagata-nagai-memorial-hall', 'private_hall', '長井市の葬儀ホール。あやめの里で知られる長井市で、家族葬から一般葬まで対応。白鷹山を望む自然豊かな環境で、心温まるお別れの場を提供します。', '山形県長井市栄町5-3', 'yamagata', 'nagai', 38.105, 140.04, '山形鉄道 長井駅', 10, 60, 1, false, 25, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}]'::jsonb, '{"家族葬対応","駅近","駐車場完備","地域密着"}', '長井メモリアルホール', 3.9, 8)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('上山家族葬ホール', 'yamagata-kaminoyama-kazokuso-hall', 'private_hall', '上山市の家族葬専用ホール。少人数のアットホームな葬儀に特化。温泉の里で故人と家族の大切な時間を守ります。', '山形県上山市新湯6-8', 'yamagata', 'kaminoyama', 38.148, 140.27, 'JR奥羽本線 かみのやま温泉駅', 12, 30, 1, false, 12, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}]'::jsonb, '{"家族葬専用","少人数葬対応","安置施設あり"}', '上山家族葬ホール', 4.0, 6)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('家族葬のはくぜん南館ホール', 'yamagata-hakuzen-nankan', 'private_hall', 'はくぜんが運営する山形市南部の家族葬ホール。自然光が入る明るい空間で、温かみのある家族葬を執り行えます。安置施設完備で、少人数のアットホームなお別れに最適です。', '山形県山形市南館5-8-20', 'yamagata', 'yamagata-city', 38.228, 140.325, 'JR奥羽本線 蔵王駅', 15, 30, 1, false, 15, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}]'::jsonb, '{"家族葬専用","1日1組限定","安置施設あり","少人数葬対応"}', '株式会社はくぜん', 4.3, 16)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('セレモニーホール天童', 'yamagata-ceremony-hall-tendo', 'private_hall', '平安典礼が運営する天童市の葬儀会館。将棋の駒の街・天童で、家族葬から一般葬まで幅広く対応。安置施設完備で、充実した設備のもとサービスを提供します。', '山形県天童市東本町2-5-18', 'yamagata', 'tendo', 38.355, 140.38, 'JR奥羽本線 天童駅', 10, 80, 2, false, 40, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 568000}]'::jsonb, '{"家族葬対応","一般葬対応","駅近","宿泊可能","駐車場完備"}', '平安典礼', 4.2, 15)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('寒河江やすらぎホール', 'yamagata-sagae-yasuragi-hall', 'private_hall', '寒河江市の民営葬儀ホール。家族葬を中心に、温かみのある空間でお別れの場を提供。地域に密着した丁寧なサービスが特徴です。', '山形県寒河江市新山3-2-10', 'yamagata', 'sagae', 38.378, 140.28, 'JR左沢線 寒河江駅', 8, 40, 1, false, 15, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}]'::jsonb, '{"家族葬対応","駅近","少人数葬対応","駐車場完備"}', '寒河江やすらぎホール', 3.9, 7)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('南陽セレモニーホール', 'yamagata-nanyo-ceremony-hall', 'private_hall', '南陽市の葬儀ホール。菊まつりで知られる南陽市で、家族葬から一般葬まで対応。赤湯温泉に近い落ち着いた環境で、心温まるお別れの場を提供します。', '山形県南陽市赤湯780-5', 'yamagata', 'nanyo', 38.055, 140.14, 'JR奥羽本線 赤湯駅', 10, 60, 1, false, 25, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}]'::jsonb, '{"家族葬対応","一般葬対応","駅近","駐車場完備"}', '南陽セレモニーホール', 3.9, 9)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('天童メモリアルガーデン', 'yamagata-tendo-memorial-garden', 'private_hall', '天童市の葬儀ホール。月山を望む自然豊かな環境で、家族葬から中規模の葬儀まで対応。地域に密着したサービスで、温かいお別れの場を提供します。', '山形県天童市北目1-5-20', 'yamagata', 'tendo', 38.365, 140.37, 'JR奥羽本線 天童駅', 12, 50, 1, false, 25, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}]'::jsonb, '{"家族葬対応","一般葬対応","駐車場完備","地域密着"}', '天童メモリアルガーデン', 3.9, 8)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('ファミリー斎場山形南', 'yamagata-family-saijo-minami', 'private_hall', 'さがみ典礼が運営する山形市南部の葬儀会館。山形大学病院前バス停より徒歩3分の好アクセス。家族葬から一般葬まで対応し、経験豊富なスタッフが丁寧にサポートします。', '山形県山形市飯田西3-2-15', 'yamagata', 'yamagata-city', 38.232, 140.315, 'JR奥羽本線 山形駅', 22, 80, 2, false, 35, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 568000}]'::jsonb, '{"家族葬対応","一般葬対応","宿泊可能","駐車場完備"}', '株式会社アルファクラブ東北（さがみ典礼）', 4.0, 15)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('新庄家族葬ホール', 'yamagata-shinjo-kazokuso-hall', 'private_hall', '新庄市の家族葬専用ホール。最上地方で少人数のアットホームな葬儀に特化。故人と家族の大切な時間を守る温かい空間です。', '山形県新庄市常葉町3-5', 'yamagata', 'shinjo', 38.758, 140.31, 'JR奥羽本線 新庄駅', 8, 30, 1, false, 12, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}]'::jsonb, '{"家族葬専用","駅近","安置施設あり","少人数葬対応"}', '新庄家族葬ホール', 4.0, 7)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('東根セレモニーホール', 'yamagata-higashine-ceremony-hall', 'private_hall', '東根市の民営葬儀式場。家族葬から中規模の葬儀まで対応し、地域に密着したサービスを提供。さくらんぼ東根駅からのアクセスも良好です。', '山形県東根市温泉町2-12-5', 'yamagata', 'higashine', 38.435, 140.395, 'JR奥羽本線 さくらんぼ東根駅', 12, 60, 1, false, 25, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}]'::jsonb, '{"家族葬対応","一般葬対応","駐車場完備"}', '東根セレモニーホール', 3.9, 7)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('ジョイングループ山形ホール', 'yamagata-joining-yamagata-hall', 'private_hall', 'ジョイングループが運営する山形市の総合葬儀会館。冠婚葬祭を幅広く手掛けるグループの強みを活かし、きめ細かなサービスを提供。家族葬から大規模な社葬まで対応可能です。', '山形県山形市あかねヶ丘1-10-3', 'yamagata', 'yamagata-city', 38.238, 140.308, 'JR奥羽本線 山形駅', 18, 150, 3, false, 60, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "エレベーター": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 115000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 278000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 408000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000}]'::jsonb, '{"大規模葬対応","家族葬対応","宿泊可能","駐車場完備","バリアフリー"}', 'ジョイングループ', 4.2, 19)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('メモリアルホール東根', 'yamagata-memorial-hall-higashine', 'private_hall', '東根市の葬儀ホール。さくらんぼの里で知られる東根市で、家族葬から一般葬まで対応。安置施設完備で、温かみのある空間でお別れの場を提供します。', '山形県東根市中央2-8-15', 'yamagata', 'higashine', 38.43, 140.39, 'JR奥羽本線 さくらんぼ東根駅', 10, 80, 2, false, 40, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}]'::jsonb, '{"家族葬対応","一般葬対応","駅近","駐車場完備"}', 'メモリアルホール東根', 4.1, 13)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('山形南メモリアルホール', 'yamagata-minami-memorial-hall', 'private_hall', '山形市南部に位置する葬儀ホール。蔵王連峰を望む環境で、家族葬を中心にサービスを提供。アットホームな雰囲気で、故人との最後の時間を大切にできる空間です。', '山形県山形市南原町1-15-8', 'yamagata', 'yamagata-city', 38.22, 140.33, 'JR奥羽本線 蔵王駅', 12, 40, 1, false, 20, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}]'::jsonb, '{"家族葬対応","少人数葬対応","駐車場完備","バリアフリー"}', '山形南メモリアルホール', 3.9, 9)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('藤島斎場', 'yamagata-fujishima-saijo', 'public_crematorium', '鶴岡市藤島地区にある公営火葬場。鶴岡市北東部の市民の火葬を担い、低料金で利用可能。自然に囲まれた静かな環境で故人を見送れます。', '山形県鶴岡市藤島字古楯跡120', 'yamagata', 'tsuruoka', 38.805, 139.91, 'JR羽越本線 藤島駅', 15, 30, 1, true, 20, '{"控室": true, "霊安室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}]'::jsonb, '{"火葬場併設","公営斎場","駐車場完備"}', '鶴岡市', 3.6, 7)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('メモリアルホール寒河江', 'yamagata-memorial-hall-sagae', 'private_hall', '寒河江市の葬儀ホール。さくらんぼの産地として知られる寒河江市で、安置施設完備の充実した葬儀施設。家族葬から一般葬まで対応します。', '山形県寒河江市本町2-5-8', 'yamagata', 'sagae', 38.375, 140.275, 'JR左沢線 寒河江駅', 10, 80, 2, false, 40, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}]'::jsonb, '{"家族葬対応","一般葬対応","駅近","安置施設あり"}', 'メモリアルホール寒河江', 4.0, 12)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('米沢家族葬ホール', 'yamagata-yonezawa-kazokuso-hall', 'private_hall', '米沢市の家族葬専用ホール。少人数でのアットホームな葬儀に特化。城下町の落ち着いた環境で、故人と家族の大切な時間を過ごせます。', '山形県米沢市金池5-3-18', 'yamagata', 'yonezawa', 37.908, 140.11, 'JR奥羽本線 米沢駅', 15, 30, 1, false, 15, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}]'::jsonb, '{"家族葬専用","少人数葬対応","安置施設あり","駐車場完備"}', '米沢家族葬ホール', 4.0, 9)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('新庄市斎場', 'yamagata-shinjo-saijo', 'public_crematorium', '新庄市が運営する公営の火葬場。新庄まつりで有名な新庄市民の火葬を担い、低料金で利用可能。最上地方の中心都市として広域からの利用にも対応しています。', '山形県新庄市大字鳥越1773', 'yamagata', 'shinjo', 38.755, 140.3, 'JR奥羽本線 新庄駅', 20, 40, 1, true, 25, '{"控室": true, "霊安室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}]'::jsonb, '{"火葬場併設","公営斎場","駐車場完備"}', '新庄市', 3.6, 7)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('セレモニーホール鶴岡', 'yamagata-ceremony-hall-tsuruoka', 'private_hall', '平安典礼が運営する鶴岡市の大型葬儀会館。JR鶴岡駅から車で10分。家族葬から一般葬まで幅広く対応し、庄内地方の葬儀文化に精通したスタッフが丁寧にサポートします。', '山形県鶴岡市本町1-8-30', 'yamagata', 'tsuruoka', 38.728, 139.835, 'JR羽越本線 鶴岡駅', 15, 120, 2, false, 50, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}]'::jsonb, '{"大規模葬対応","家族葬対応","宿泊可能","駐車場完備"}', '平安典礼', 4.2, 18)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('鶴岡斎場', 'yamagata-tsuruoka-saijo', 'public_crematorium', '鶴岡市が運営する公営の火葬場。庄内地方の中心都市・鶴岡市民の火葬を担い、低料金で利用可能。式場も併設しており、通夜から火葬まで対応できます。', '山形県鶴岡市馬場町5-34', 'yamagata', 'tsuruoka', 38.725, 139.83, 'JR羽越本線 鶴岡駅', 20, 50, 1, true, 35, '{"控室": true, "霊安室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}]'::jsonb, '{"火葬場併設","公営斎場","駐車場完備","家族葬対応"}', '鶴岡市', 3.7, 12)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('セレモニーホール酒田', 'yamagata-ceremony-hall-sakata', 'private_hall', '平安典礼が運営する酒田市の大型葬儀会館。JR酒田駅から車で10分。家族葬から一般葬まで幅広く対応し、充実した設備で心のこもったサービスを提供します。', '山形県酒田市日吉町2-5-30', 'yamagata', 'sakata', 38.918, 139.845, 'JR羽越本線 酒田駅', 12, 120, 2, false, 50, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}]'::jsonb, '{"大規模葬対応","家族葬対応","宿泊可能","駐車場完備"}', '平安典礼', 4.2, 16)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('家族葬のはくぜん桜田ホール', 'yamagata-hakuzen-sakurada', 'private_hall', 'はくぜんが運営する山形市桜田東の家族葬専用ホール。少人数の家族葬に特化した落ち着いた空間。安置施設完備で、故人と最後の時間をゆっくりと過ごせます。1日1組限定の貸切対応。', '山形県山形市桜田東2-13-18', 'yamagata', 'yamagata-city', 38.235, 140.34, 'JR奥羽本線 山形駅', 20, 30, 1, false, 20, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}]'::jsonb, '{"家族葬専用","1日1組限定","安置施設あり","少人数葬対応"}', '株式会社はくぜん', 4.4, 20)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('ファミリー斎場山形西', 'yamagata-family-saijo-nishi', 'private_hall', 'さがみ典礼が運営する山形市西部の葬儀会館。閑静な住宅地に立地し、駐車場も完備。家族葬から一般葬まで対応し、充実した設備で心のこもったサービスを提供します。', '山形県山形市西田4-15-8', 'yamagata', 'yamagata-city', 38.245, 140.305, 'JR奥羽本線 山形駅', 20, 80, 2, false, 40, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 568000}]'::jsonb, '{"家族葬対応","一般葬対応","宿泊可能","駐車場完備"}', '株式会社アルファクラブ東北（さがみ典礼）', 4.1, 17)
ON CONFLICT (slug) DO NOTHING;
