-- iwate県の斎場データ (50件)
-- 自動生成: 2026-02-27

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('ファミラル北上', 'iwate-familal-kitakami', 'private_hall', '北上市にある家族葬対応ホール。アルファクラブ東北が運営し、少人数のアットホームな葬儀に最適。1日1組限定で、故人と家族の大切な時間を守ります。', '岩手県北上市青柳町1-8-15', 'iwate', 'kitakami', 39.29, 141.108, 'JR東北本線 北上駅', 12, 30, 1, false, 15, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}]'::jsonb, '{"家族葬専用","1日1組限定","安置施設あり","少人数葬対応"}', '株式会社アルファクラブ東北', 4.2, 10)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('セリオホールみたけ', 'iwate-serio-mitake', 'private_hall', 'いわて生協が運営するみたけ地区の葬儀ホール。組合員価格で利用でき、家族葬から一般葬まで対応。地域に根差したサービスで、安心の料金体系が魅力です。バリアフリー設計で高齢者も安心。', '岩手県盛岡市みたけ3-38-38', 'iwate', 'morioka', 39.735, 141.12, 'JR田沢湖線 大釜駅', 30, 60, 1, false, 30, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}]'::jsonb, '{"生協運営","家族葬対応","組合員割引","バリアフリー"}', 'いわて生協', 4.1, 19)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('セリオホール花巻', 'iwate-serio-hanamaki', 'private_hall', 'いわて生協が運営する花巻市の葬儀ホール。組合員価格で利用でき、家族葬から一般葬まで対応。地域に密着したサービスと安心の料金体系が特徴です。', '岩手県花巻市材木町8-20', 'iwate', 'hanamaki', 39.388, 141.118, 'JR東北本線 花巻駅', 8, 60, 1, false, 25, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 498000}]'::jsonb, '{"生協運営","家族葬対応","組合員割引","駅近"}', 'いわて生協', 4.0, 14)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('大船渡市斎場', 'iwate-ofunato-saijo', 'public_crematorium', '大船渡市が運営する公営の火葬場。三陸海岸に位置する大船渡市民の火葬を担っています。東日本大震災からの復興を経て、新しい設備で故人を見送ることができます。', '岩手県大船渡市猪川町字久名畑45', 'iwate', 'ofunato', 39.075, 141.715, 'JR大船渡線BRT 大船渡駅', 20, 40, 1, true, 25, '{"控室": true, "霊安室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}]'::jsonb, '{"火葬場併設","公営斎場","駐車場完備","家族葬対応"}', '大船渡市', 3.7, 8)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('遠野市斎場', 'iwate-tono-saijo', 'public_crematorium', '遠野市が運営する公営の火葬場。民話の里・遠野の市民の火葬を担い、自然豊かな環境で故人を見送ることができます。低料金で利用可能です。', '岩手県遠野市松崎町白岩18地割20', 'iwate', 'tono', 39.335, 141.53, 'JR釜石線 遠野駅', 20, 30, 1, true, 20, '{"控室": true, "霊安室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 278000}]'::jsonb, '{"火葬場併設","公営斎場","駐車場完備","家族葬対応"}', '遠野市', 3.6, 5)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('釜石市斎場', 'iwate-kamaishi-saijo', 'public_crematorium', '釜石市が運営する公営の火葬場。鉄と魚のまち・釜石の市民の火葬を担っています。東日本大震災からの復興を経て整備された施設で、故人を見送ることができます。', '岩手県釜石市甲子町第10地割246', 'iwate', 'kamaishi', 39.275, 141.86, 'JR釜石線 釜石駅', 25, 40, 1, true, 25, '{"控室": true, "霊安室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}]'::jsonb, '{"火葬場併設","公営斎場","駐車場完備","家族葬対応"}', '釜石市', 3.6, 7)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('北上長安殿', 'iwate-kitakami-choan-den', 'private_hall', 'さがみ典礼が運営する北上市の葬儀会館。JR北上駅から車で5分の好アクセス。家族葬から一般葬まで幅広く対応し、宿泊設備も完備。東北自動車道北上ICからも近く、遠方からの参列者にも便利。', '岩手県北上市本通り2-3-18', 'iwate', 'kitakami', 39.283, 141.112, 'JR東北新幹線 北上駅', 15, 100, 2, false, 45, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}]'::jsonb, '{"家族葬対応","一般葬対応","宿泊可能","駐車場完備","IC近い"}', '株式会社アルファクラブ東北（さがみ典礼）', 4.1, 16)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('セリオホール宮古', 'iwate-serio-miyako', 'private_hall', 'いわて生協が運営する宮古市の葬儀ホール。組合員価格で利用でき、家族葬に最適なアットホームな空間。震災復興後の地域に寄り添い、心温まるサービスを提供しています。', '岩手県宮古市磯鶏沖2-10', 'iwate', 'miyako', 39.625, 141.96, 'JR山田線 磯鶏駅', 8, 40, 1, false, 20, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}]'::jsonb, '{"生協運営","家族葬対応","組合員割引","駅近"}', 'いわて生協', 4.0, 8)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('やすらぎホール盛岡', 'iwate-yasuragi-hall-morioka', 'private_hall', '盛岡市内の葬儀ホール。家族葬から一般葬まで幅広く対応し、経験豊富なスタッフが心のこもったサポートを提供。バリアフリー設計で高齢の参列者にも配慮した施設です。', '岩手県盛岡市月が丘2-3-15', 'iwate', 'morioka', 39.74, 141.115, 'IGRいわて銀河鉄道 厨川駅', 12, 70, 1, false, 35, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000}]'::jsonb, '{"家族葬対応","一般葬対応","駐車場完備","バリアフリー"}', 'やすらぎホール盛岡', 3.9, 10)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('盛岡東典礼会館', 'iwate-morioka-higashi-tenrei', 'private_hall', '盛岡市東部に位置する葬儀式場。家族葬から一般葬まで対応し、東北自動車道盛岡ICからも近い好アクセス。清潔感のある明るい施設で、心安らぐお別れの場を提供します。', '岩手県盛岡市東見前6-45-3', 'iwate', 'morioka', 39.68, 141.155, 'JR東北本線 岩手飯岡駅', 18, 80, 2, false, 40, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 260000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 568000}]'::jsonb, '{"家族葬対応","一般葬対応","宿泊可能","IC近い","駐車場完備"}', '盛岡東典礼会館', 4.0, 13)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('千厩典礼会館', 'iwate-senmaya-tenrei-kaikan', 'private_hall', '一関市千厩地区にある葬儀式場。千厩地域の葬儀を幅広くサポートし、家族葬から一般葬まで対応。地域の風習に精通したスタッフが、心のこもったサービスを提供します。', '岩手県一関市千厩町千厩字宮敷78-1', 'iwate', 'ichinoseki', 38.892, 141.27, 'JR大船渡線 千厩駅', 10, 70, 1, false, 30, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}]'::jsonb, '{"家族葬対応","一般葬対応","駐車場完備","地域密着"}', '千厩典礼会館', 3.9, 8)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('水沢長安殿', 'iwate-mizusawa-choan-den', 'private_hall', 'さがみ典礼が運営する奥州市水沢の葬儀会館。JR水沢駅から車で5分の好アクセス。大規模な一般葬から家族葬まで、経験豊富なスタッフが丁寧にサポートします。宿泊設備も完備。', '岩手県奥州市水沢区東町36', 'iwate', 'oshu', 39.138, 141.138, 'JR東北本線 水沢駅', 10, 100, 2, false, 45, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}]'::jsonb, '{"家族葬対応","一般葬対応","宿泊可能","駐車場完備"}', '株式会社アルファクラブ東北（さがみ典礼）', 4.1, 18)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('永遠の杜盛岡ホール', 'iwate-towa-no-mori-morioka', 'private_hall', '盛岡市南部に位置する家族葬対応のセレモニーホール。自然に囲まれた落ち着いた環境で、故人との最後の時間をゆっくりと過ごせます。小規模から中規模の葬儀に最適な広さの式場を備えています。', '岩手県盛岡市永井12-5-8', 'iwate', 'morioka', 39.668, 141.135, 'JR東北本線 岩手飯岡駅', 15, 60, 1, false, 30, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}]'::jsonb, '{"家族葬対応","自然環境","駐車場完備","バリアフリー"}', '永遠の杜', 4.0, 11)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('滝沢長安殿', 'iwate-takizawa-choan-den', 'private_hall', 'さがみ典礼が運営する滝沢市の葬儀会館。盛岡市に隣接する滝沢市で、家族葬から一般葬まで幅広く対応。充実した設備と経験豊富なスタッフが、心のこもったサービスを提供します。', '岩手県滝沢市穴口328-3', 'iwate', 'takizawa', 39.735, 141.078, 'IGRいわて銀河鉄道 滝沢駅', 15, 80, 2, false, 40, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}]'::jsonb, '{"家族葬対応","一般葬対応","宿泊可能","駐車場完備"}', '株式会社アルファクラブ東北（さがみ典礼）', 4.1, 15)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('セレモニーゆずり葉一関', 'iwate-yuzuriha-ichinoseki', 'private_hall', '一関市花泉町にある葬儀ホール。地域に密着したサービスで、家族葬から一般葬まで幅広く対応。自然に囲まれた静かな環境で、心安らぐお別れの場を提供します。', '岩手県一関市花泉町涌津字二ノ町53', 'iwate', 'ichinoseki', 38.875, 141.155, 'JR東北本線 花泉駅', 10, 60, 1, false, 30, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}]'::jsonb, '{"家族葬対応","一般葬対応","駐車場完備","地域密着"}', 'セレモニーゆずり葉', 4.0, 12)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('ファミラル水沢', 'iwate-familal-mizusawa', 'private_hall', '奥州市水沢区にある家族葬対応ホール。アルファクラブ東北が運営し、少人数の家族葬に最適な空間。安置施設完備で、故人と最後の時間をゆっくり過ごせます。', '岩手県奥州市水沢区花園町1-3-8', 'iwate', 'oshu', 39.142, 141.145, 'JR東北本線 水沢駅', 8, 30, 1, false, 15, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}]'::jsonb, '{"家族葬専用","駅近","安置施設あり","少人数葬対応"}', '株式会社アルファクラブ東北', 4.0, 11)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('一関市舞川斎場', 'iwate-ichinoseki-maikawa-saijo', 'public_crematorium', '一関市が運営する公営の火葬場。舞川地区に位置し、一関市民の火葬を担っています。静かな環境の中で故人を見送ることができ、駐車場も完備。一関市民は低料金で利用できます。', '岩手県一関市舞川字向山1-10', 'iwate', 'ichinoseki', 38.91, 141.12, 'JR東北本線 一ノ関駅', 30, 50, 1, true, 40, '{"控室": true, "霊安室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}]'::jsonb, '{"火葬場併設","公営斎場","駐車場完備","家族葬対応"}', '一関市', 3.8, 15)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('家族葬のファミラル都南', 'iwate-familal-tonan', 'private_hall', '盛岡市都南地区にある家族葬専用ホール。少人数でのアットホームな葬儀に特化し、1日1組限定で利用できます。安置施設完備で、故人と最後の時間をゆっくり過ごせる温かみのある空間です。', '岩手県盛岡市津志田南2-15-30', 'iwate', 'morioka', 39.675, 141.14, 'JR東北本線 岩手飯岡駅', 12, 30, 1, false, 20, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}]'::jsonb, '{"家族葬専用","1日1組限定","安置施設あり","少人数葬対応"}', '株式会社アルファクラブ東北', 4.4, 18)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('奥州市水沢斎場', 'iwate-oshu-mizusawa-saijo', 'public_crematorium', '奥州市が運営する水沢地区の公営火葬場。奥州市民は低料金で利用でき、落ち着いた環境で故人を見送ることができます。式場も併設しており、通夜から火葬まで対応可能です。', '岩手県奥州市水沢区佐倉河字明神堂27', 'iwate', 'oshu', 39.135, 141.13, 'JR東北本線 水沢駅', 25, 60, 1, true, 40, '{"控室": true, "霊安室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}]'::jsonb, '{"火葬場併設","公営斎場","駐車場完備","家族葬対応"}', '奥州市', 3.8, 14)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('さくらホール釜石', 'iwate-sakura-hall-kamaishi', 'private_hall', '釜石市の民営葬儀ホール。JR釜石駅から徒歩約12分の好アクセス。家族葬を中心に、地域に密着したきめ細かなサービスを提供。震災復興の歩みとともに地域に愛されるホールです。', '岩手県釜石市大町2-1-15', 'iwate', 'kamaishi', 39.278, 141.875, 'JR釜石線 釜石駅', 12, 50, 1, false, 20, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}]'::jsonb, '{"家族葬対応","駅近","駐車場完備","地域密着"}', 'さくらホール', 4.1, 10)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('一関コミュニティホール', 'iwate-ichinoseki-community-hall', 'public_facility', '一関市中心部にある多目的施設で、葬儀にも利用可能。一ノ関駅から徒歩圏内の好立地で、小規模な家族葬やお別れ会に適しています。低料金で利用でき、地域住民に親しまれています。', '岩手県一関市大町7-14', 'iwate', 'ichinoseki', 38.934, 141.128, 'JR東北新幹線 一ノ関駅', 8, 40, 1, false, 20, '{"控室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 80000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}]'::jsonb, '{"駅近","低料金","家族葬対応","少人数葬対応"}', '一関市', 3.7, 7)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('花巻市石鳥谷斎場', 'iwate-hanamaki-ishidoriya-saijo', 'public_crematorium', '花巻市が運営する石鳥谷地区の公営火葬場。花巻市民は低料金で利用でき、自然に囲まれた静かな環境で故人を見送ることができます。火葬棟と待合室を備えています。', '岩手県花巻市石鳥谷町好地第2地割161-1', 'iwate', 'hanamaki', 39.435, 141.115, 'JR東北本線 石鳥谷駅', 20, 40, 1, true, 30, '{"控室": true, "霊安室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}]'::jsonb, '{"火葬場併設","公営斎場","駐車場完備","家族葬対応"}', '花巻市', 3.7, 10)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('浄光の間', 'iwate-joko-no-ma', 'private_hall', '盛岡市内の民営葬儀式場。小規模の家族葬から中規模の葬儀まで対応する、アットホームな雰囲気の式場です。安置施設を備え、故人を身近に感じながらお別れの時間を過ごせます。', '岩手県盛岡市本宮5-3-12', 'iwate', 'morioka', 39.692, 141.128, 'JR東北本線 仙北町駅', 18, 50, 1, false, 25, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 95000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 348000}]'::jsonb, '{"安置施設あり","少人数葬対応","家族葬対応","駐車場完備"}', '浄光の間', 4.1, 15)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('盛岡西典礼会館', 'iwate-morioka-nishi-tenrei', 'private_hall', '盛岡市西部に位置する典礼会館。家族葬から一般葬まで対応し、広い駐車場を完備。盛岡西バイパス沿いの好立地で、車でのアクセスが便利です。経験豊富なスタッフが心を込めてお手伝いします。', '岩手県盛岡市西仙北1-18-50', 'iwate', 'morioka', 39.695, 141.11, 'JR東北本線 仙北町駅', 25, 100, 2, false, 50, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 108000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 265000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 388000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 568000}]'::jsonb, '{"家族葬対応","一般葬対応","宿泊可能","駐車場完備"}', '盛岡西典礼会館', 4.0, 16)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('北上市斎場', 'iwate-kitakami-saijo', 'public_crematorium', '北上市が運営する公営の火葬場。北上市民は低料金で利用でき、火葬棟と待合室を備えています。静かな環境の中で故人を見送ることができ、駐車場も完備しています。', '岩手県北上市稲瀬町内門岡17', 'iwate', 'kitakami', 39.275, 141.105, 'JR東北本線 北上駅', 25, 50, 1, true, 35, '{"控室": true, "霊安室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}]'::jsonb, '{"火葬場併設","公営斎場","駐車場完備","家族葬対応"}', '北上市', 3.7, 12)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('久慈典礼会館', 'iwate-kuji-tenrei-kaikan', 'private_hall', '久慈市の民営葬儀式場。JR久慈駅から車で5分の好アクセス。家族葬から一般葬まで、久慈地域の風習に精通したスタッフが丁寧にサポートします。', '岩手県久慈市中央3-38', 'iwate', 'kuji', 40.188, 141.775, 'JR八戸線 久慈駅', 10, 60, 1, false, 25, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}]'::jsonb, '{"家族葬対応","一般葬対応","駐車場完備","地域密着"}', '久慈典礼会館', 3.9, 8)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('大船渡メモリアルホール', 'iwate-ofunato-memorial-hall', 'private_hall', '大船渡市の民営葬儀ホール。震災復興後の新しい施設で、家族葬から一般葬まで対応。三陸の地域に密着したサービスで、心温まる葬儀を執り行います。', '岩手県大船渡市盛町字内ノ目3-8', 'iwate', 'ofunato', 39.068, 141.705, 'JR大船渡線BRT 盛駅', 10, 60, 1, false, 25, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 338000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}]'::jsonb, '{"家族葬対応","一般葬対応","駐車場完備","地域密着"}', '大船渡メモリアルホール', 4.0, 9)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('紫波長安殿', 'iwate-shiwa-choan-den', 'private_hall', 'さがみ典礼が運営する紫波郡の葬儀会館。盛岡市と花巻市の中間に位置し、広域からのアクセスが良好。家族葬から一般葬まで対応し、地域の葬儀文化を大切にしたサービスを提供します。滝沢市からも利用可能です。', '岩手県紫波郡紫波町日詰字下丸森36-2', 'iwate', 'takizawa', 39.555, 141.148, 'JR東北本線 紫波中央駅', 10, 80, 2, false, 40, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}]'::jsonb, '{"家族葬対応","一般葬対応","宿泊可能","駅近","駐車場完備"}', '株式会社アルファクラブ東北（さがみ典礼）', 4.1, 14)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('北上コープ葬祭センター', 'iwate-kitakami-coop-sosai', 'private_hall', 'いわて生協が運営する北上市の葬祭センター。組合員価格で利用でき、明瞭な料金体系が特徴。家族葬から一般葬まで対応し、地域に根差したサービスを提供しています。', '岩手県北上市大通り3-5-20', 'iwate', 'kitakami', 39.285, 141.115, 'JR東北本線 北上駅', 10, 60, 1, false, 25, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 82000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 488000}]'::jsonb, '{"生協運営","組合員割引","家族葬対応","駅近"}', 'いわて生協', 4.0, 13)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('メモリアルホールもりおか長安殿', 'iwate-morioka-choan-den', 'private_hall', 'さがみ典礼が運営する盛岡市愛宕町の大型葬儀会館。盛岡駅より車15分。大規模な一般葬から少人数の家族葬まで幅広く対応。ファミラルもりおかとしても知られ、充実した設備と経験豊富なスタッフが丁寧にサポートします。', '岩手県盛岡市愛宕町7-8', 'iwate', 'morioka', 39.705, 141.152, 'JR東北新幹線 盛岡駅', 25, 150, 3, false, 60, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "エレベーター": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 110000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 268000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 398000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 598000}]'::jsonb, '{"大規模葬対応","家族葬対応","宿泊可能","駐車場完備","バリアフリー"}', '株式会社アルファクラブ東北（さがみ典礼）', 4.3, 25)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('宮古長安殿', 'iwate-miyako-choan-den', 'private_hall', 'さがみ典礼が運営する宮古市の葬儀会館。JR宮古駅から車で10分。家族葬から一般葬まで対応し、三陸地域の葬儀文化に精通したスタッフが心のこもったサービスを提供します。', '岩手県宮古市宮町3-2-15', 'iwate', 'miyako', 39.64, 141.955, 'JR山田線 宮古駅', 12, 80, 2, false, 35, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 538000}]'::jsonb, '{"家族葬対応","一般葬対応","宿泊可能","駐車場完備"}', '株式会社アルファクラブ東北（さがみ典礼）', 4.0, 12)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('江刺典礼会館', 'iwate-esashi-tenrei-kaikan', 'private_hall', '奥州市江刺区にある葬儀式場。江刺地域の葬儀ニーズに応え、家族葬から一般葬まで幅広く対応。地元に根差したサービスで、地域の風習を大切にした葬儀を執り行います。', '岩手県奥州市江刺区愛宕字三日町19', 'iwate', 'oshu', 39.175, 141.19, 'JR東北本線 水沢駅', 35, 60, 1, false, 25, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 518000}]'::jsonb, '{"家族葬対応","一般葬対応","駐車場完備","地域密着"}', '江刺典礼会館', 3.9, 10)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('家族葬ホール禮賓館一関', 'iwate-reibinkan-ichinoseki', 'private_hall', '一関市花泉町にある家族葬専門ホール。少人数でのアットホームな葬儀に特化し、故人と家族の大切な時間を守ります。丁寧なサポートと温かい空間が特徴の式場です。', '岩手県一関市花泉町涌津一ノ町58-2', 'iwate', 'ichinoseki', 38.877, 141.153, 'JR東北本線 花泉駅', 8, 30, 1, false, 15, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}]'::jsonb, '{"家族葬専用","少人数葬対応","駐車場完備","地域密着"}', '家族葬ホール禮賓館', 4.1, 9)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('一関長安殿', 'iwate-ichinoseki-choan-den', 'private_hall', 'さがみ典礼が運営する一関市の葬儀会館。JR一ノ関駅から車で5分、東北自動車道一関ICより車で10分の好アクセス。浴室付きのお部屋で仮眠もとることができ、通夜から葬儀まで快適に過ごせます。', '岩手県一関市山目字中野62-1', 'iwate', 'ichinoseki', 38.925, 141.108, 'JR東北新幹線 一ノ関駅', 20, 100, 2, false, 50, '{"控室": true, "浴室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}]'::jsonb, '{"宿泊可能","浴室完備","家族葬対応","駐車場完備","バリアフリー"}', '株式会社アルファクラブ東北（さがみ典礼）', 4.2, 20)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('盛岡市斎場やすらぎの丘', 'iwate-morioka-yasuragi-no-oka', 'public_crematorium', '盛岡市が運営する公営斎場で、三ツ割寺山に位置します。火葬棟と式場を同一敷地内に備え、通夜から火葬まで一貫して執り行えます。上盛岡駅から徒歩約11分。盛岡市民は火葬料無料で利用でき、広い駐車場も完備しています。', '岩手県盛岡市三ツ割字寺山46-4', 'iwate', 'morioka', 39.728, 141.149, 'JR山田線 上盛岡駅', 11, 100, 3, true, 80, '{"控室": true, "霊安室": true, "駐車場": true, "僧侶控室": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 248000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 358000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 528000}]'::jsonb, '{"火葬場併設","公営斎場","駐車場完備","家族葬対応","バリアフリー"}', '盛岡市（指定管理：株式会社不来方やすらぎの丘）', 4.0, 28)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('花巻西長安殿', 'iwate-hanamaki-nishi-choan-den', 'private_hall', 'さがみ典礼が運営する花巻市西部の葬儀会館。東北自動車道花巻南ICより車で10分の好アクセス。大規模な一般葬から家族葬まで、充実した設備で幅広く対応します。宿泊設備も完備。', '岩手県花巻市西大通り2-19-12', 'iwate', 'hanamaki', 39.385, 141.105, 'JR東北本線 花巻駅', 15, 100, 2, false, 50, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}]'::jsonb, '{"家族葬対応","一般葬対応","宿泊可能","駐車場完備","IC近い"}', '株式会社アルファクラブ東北（さがみ典礼）', 4.2, 17)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('家族葬のファミラル三ツ割', 'iwate-familal-mitsuwari', 'private_hall', '盛岡市三ツ割にある家族葬専用ホール。やすらぎの丘に近く、火葬場へのアクセスも良好。1日1組限定の貸切空間で、故人との最後の時間を大切にできます。安置施設も完備しています。', '岩手県盛岡市三ツ割2-8-15', 'iwate', 'morioka', 39.726, 141.153, 'JR山田線 上盛岡駅', 14, 30, 1, false, 15, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}]'::jsonb, '{"家族葬専用","1日1組限定","安置施設あり","火葬場近い"}', '株式会社アルファクラブ東北', 4.2, 12)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('家族葬のファミラル中屋敷', 'iwate-familal-nakayashiki', 'private_hall', '盛岡市中屋敷にある家族葬専用ホール。1日1組貸切で、少人数の家族葬に最適な空間を提供。安置施設を完備し、通夜から葬儀まで同じ場所で執り行えます。落ち着いた住宅街に位置し、静かな環境です。', '岩手県盛岡市中屋敷町3-18', 'iwate', 'morioka', 39.715, 141.125, 'JR東北本線 盛岡駅', 20, 30, 1, false, 15, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}]'::jsonb, '{"家族葬専用","1日1組限定","安置施設あり","少人数葬対応"}', '株式会社アルファクラブ東北', 4.3, 14)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('花巻メモリアルホール', 'iwate-hanamaki-memorial-hall', 'private_hall', '花巻市中心部にある葬儀ホール。家族葬を中心に、アットホームな雰囲気で故人を偲ぶことができます。温泉の里・花巻の地域性を活かした心温まるサービスを提供。', '岩手県花巻市双葉町6-5', 'iwate', 'hanamaki', 39.39, 141.112, 'JR東北本線 花巻駅', 10, 50, 1, false, 20, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}]'::jsonb, '{"家族葬対応","駅近","少人数葬対応","駐車場完備"}', '花巻メモリアルホール', 3.9, 9)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('ファミラル滝沢', 'iwate-familal-takizawa', 'private_hall', '滝沢市にある家族葬対応ホール。盛岡市のベッドタウンとして発展する滝沢市で、少人数の家族葬に最適な空間を提供。1日1組限定の貸切でゆっくりとお別れの時間を過ごせます。', '岩手県滝沢市鵜飼狐洞1-58', 'iwate', 'takizawa', 39.738, 141.085, 'IGRいわて銀河鉄道 滝沢駅', 10, 30, 1, false, 15, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 92000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 328000}]'::jsonb, '{"家族葬専用","1日1組限定","安置施設あり","少人数葬対応"}', '株式会社アルファクラブ東北', 4.2, 11)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('仙北長安殿（ファミラル仙北）', 'iwate-senboku-choan-den', 'private_hall', 'さがみ典礼が運営する盛岡市仙北地区の葬儀会館。中規模の一般葬から家族葬まで対応。仙北町駅から車5分の好アクセスで、充実した設備と温かなおもてなしで故人を見送ります。', '岩手県盛岡市仙北2-24-5', 'iwate', 'morioka', 39.688, 141.145, 'JR東北本線 仙北町駅', 10, 80, 2, false, 40, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 105000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}]'::jsonb, '{"家族葬対応","一般葬対応","宿泊可能","駐車場完備","バリアフリー"}', '株式会社アルファクラブ東北（さがみ典礼）', 4.1, 20)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('宮古市斎場', 'iwate-miyako-saijo', 'public_crematorium', '宮古市が運営する公営の火葬場。三陸海岸の宮古市民の火葬を担い、低料金で利用可能。火葬棟と待合室を備え、静かな環境で故人を見送ることができます。', '岩手県宮古市近内第8地割1-10', 'iwate', 'miyako', 39.635, 141.94, 'JR山田線 宮古駅', 25, 40, 1, true, 30, '{"控室": true, "霊安室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 78000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}]'::jsonb, '{"火葬場併設","公営斎場","駐車場完備","家族葬対応"}', '宮古市', 3.7, 10)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('前沢セレモニーホール', 'iwate-maesawa-ceremony-hall', 'private_hall', '奥州市前沢区にある葬儀ホール。前沢地域の葬儀を中心に、家族葬から中規模の葬儀まで対応。静かな環境で故人を偲ぶことができ、駐車場も十分に確保されています。', '岩手県奥州市前沢区七日町裏56', 'iwate', 'oshu', 39.065, 141.11, 'JR東北本線 前沢駅', 10, 50, 1, false, 25, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}]'::jsonb, '{"家族葬対応","駐車場完備","地域密着"}', '前沢セレモニーホール', 3.8, 8)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('遠野セレモニーホール', 'iwate-tono-ceremony-hall', 'private_hall', '遠野市の民営葬儀ホール。民話の里にふさわしい温かみのある空間で、家族葬を中心にサービスを提供。地域に根差した丁寧な対応が特徴です。', '岩手県遠野市中央通り5-12', 'iwate', 'tono', 39.328, 141.534, 'JR釜石線 遠野駅', 10, 40, 1, false, 15, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 88000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 308000}]'::jsonb, '{"家族葬対応","少人数葬対応","駐車場完備","地域密着"}', '遠野セレモニーホール', 3.8, 6)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('サンセルモ玉泉院盛岡会館', 'iwate-sunselmo-morioka', 'private_hall', '全国展開のサンセルモ玉泉院が盛岡で運営する葬儀会館。大規模な一般葬から家族葬まで、豊富な経験とノウハウで対応。充実した設備と落ち着いた空間で、故人にふさわしいお別れの場を提供します。', '岩手県盛岡市上田1-12-18', 'iwate', 'morioka', 39.712, 141.132, 'JR東北新幹線 盛岡駅', 15, 120, 2, false, 50, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "エレベーター": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 115000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 278000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 408000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 618000}]'::jsonb, '{"大規模葬対応","家族葬対応","宿泊可能","駐車場完備","バリアフリー"}', '株式会社サンセルモ', 4.1, 17)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('駒木葬祭セレモニーホール', 'iwate-komaki-ceremony-hall', 'private_hall', '盛岡市の老舗葬儀社・駒木葬祭が運営するセレモニーホール。地元密着の丁寧なサービスで、盛岡市民から厚い信頼を得ています。家族葬から一般葬まで柔軟に対応し、心温まるお別れの場を提供します。', '岩手県盛岡市大通3-6-12', 'iwate', 'morioka', 39.702, 141.134, 'JR東北新幹線 盛岡駅', 10, 100, 2, false, 35, '{"控室": true, "安置室": true, "駐車場": true, "宿泊施設": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 100000}, {"type": "ichinichiso", "label": "一日葬プラン", "priceFrom": 258000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 378000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 558000}]'::jsonb, '{"老舗葬儀社","家族葬対応","駅近","宿泊可能","駐車場完備"}', '株式会社駒木葬祭', 4.2, 24)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('滝沢やすらぎホール', 'iwate-takizawa-yasuragi-hall', 'private_hall', '滝沢市の住宅街に位置する葬儀ホール。家族葬を中心に、温かみのある空間で故人を偲びます。バリアフリー設計で高齢の参列者にも配慮。盛岡市斎場やすらぎの丘へのアクセスも良好です。', '岩手県滝沢市巣子1154-12', 'iwate', 'takizawa', 39.75, 141.09, 'IGRいわて銀河鉄道 巣子駅', 8, 40, 1, false, 20, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 90000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 318000}]'::jsonb, '{"家族葬対応","駅近","バリアフリー","駐車場完備"}', '滝沢やすらぎホール', 3.9, 9)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('北山浄光会館', 'iwate-kitayama-joko-kaikan', 'private_hall', '盛岡市北山に位置する民営の葬儀会館。霊安室・安置施設を完備し、家族葬から一般葬まで幅広く対応します。上盛岡駅より車4分の好アクセス。北山の閑静な環境で故人を偲ぶことができます。', '岩手県盛岡市北山2-2-40', 'iwate', 'morioka', 39.723, 141.138, 'JR山田線 上盛岡駅', 15, 80, 2, false, 40, '{"控室": true, "安置室": true, "霊安室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 98000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 368000}, {"type": "ippanso", "label": "一般葬プラン", "priceFrom": 548000}]'::jsonb, '{"安置施設あり","家族葬対応","駐車場完備","バリアフリー"}', '北山浄光会館', 4.2, 22)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('久慈市斎場', 'iwate-kuji-saijo', 'public_crematorium', '久慈市が運営する公営の火葬場。NHKあまちゃんの舞台で知られる久慈市民の火葬を担っています。自然に囲まれた静かな環境で、故人を見送ることができます。', '岩手県久慈市旭町第8地割2', 'iwate', 'kuji', 40.19, 141.77, 'JR八戸線 久慈駅', 20, 30, 1, true, 20, '{"控室": true, "霊安室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 75000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 288000}]'::jsonb, '{"火葬場併設","公営斎場","駐車場完備","家族葬対応"}', '久慈市', 3.6, 6)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO venues (name, slug, venue_type, description, address, prefecture_slug, city_slug, latitude, longitude, nearest_station, station_walk_minutes, capacity_max, hall_count, has_crematorium, parking_count, facilities, price_plans, features, operator_name, rating_avg, review_count)
VALUES ('いわて生協セリオホール中野', 'iwate-serio-nakano', 'private_hall', 'いわて生協が運営する中野地区の葬儀ホール。組合員価格で利用でき、家族葬に適した落ち着いた空間。盛岡市中野地区の閑静な住宅街に位置し、アットホームな雰囲気で故人を見送れます。', '岩手県盛岡市中野1-20-7', 'iwate', 'morioka', 39.718, 141.165, 'JR山田線 上盛岡駅', 20, 50, 1, false, 25, '{"控室": true, "安置室": true, "駐車場": true, "バリアフリー": true}'::jsonb, '[{"type": "kasoshiki", "label": "火葬式プラン", "priceFrom": 85000}, {"type": "kazokuso", "label": "家族葬プラン", "priceFrom": 298000}]'::jsonb, '{"生協運営","家族葬対応","組合員割引","少人数葬対応"}', 'いわて生協', 4.0, 13)
ON CONFLICT (slug) DO NOTHING;
