-- =============================================
-- 斎場データ: 静岡県 バッチ2（追加71件）
-- 既存30件 + 追加71件 = 合計101件
--
-- 浜松市+15件, 静岡市+15件, 沼津市+5件, 富士市+5件,
-- 磐田市+2件, 掛川市+1件, 富士宮市+1件,
-- 熱海市+3件(新規), 伊東市+2件(新規), 島田市+3件(新規),
-- 袋井市+3件(新規), 御殿場市+3件(新規), 裾野市+2件(新規),
-- 湖西市+2件(新規), 菊川市+2件(新規), 下田市+2件(新規),
-- 伊豆の国市+2件(新規), 御前崎市+2件(新規), 牧之原市+2件(新規)
--
-- 投入日: 2026-02-27
-- 投入方法: Pythonスクリプトで10件ずつバッチPOST
--   insert_shizuoka_batch2_hamamatsu.py (15件)
--   insert_shizuoka_batch2_shizuoka_city.py (15件)
--   insert_shizuoka_batch2_others.py (10件: 沼津5+富士5)
--   insert_shizuoka_batch2_newcities.py (28件: 新規12市)
--   curl直接投入 (3件: 掛川1+磐田2)
-- =============================================

-- このSQLは記録用です。実際の投入はPythonスクリプト経由で行いました。
-- 以下は投入データのSQL表現です。

-- =============================================
-- 新規エリア追加（12市）
-- =============================================
-- INSERT INTO areas (name, slug, level, parent_slug, region, code) VALUES
-- ('熱海市', 'atami', 2, 'shizuoka', '中部', '22205'),
-- ('伊東市', 'ito', 2, 'shizuoka', '中部', '22208'),
-- ('島田市', 'shimada', 2, 'shizuoka', '中部', '22209'),
-- ('袋井市', 'fukuroi', 2, 'shizuoka', '中部', '22219'),
-- ('下田市', 'shimoda', 2, 'shizuoka', '中部', '22219'),
-- ('裾野市', 'susono', 2, 'shizuoka', '中部', '22220'),
-- ('湖西市', 'kosai', 2, 'shizuoka', '中部', '22221'),
-- ('御殿場市', 'gotemba', 2, 'shizuoka', '中部', '22215'),
-- ('菊川市', 'kikugawa', 2, 'shizuoka', '中部', '22224'),
-- ('伊豆の国市', 'izunokuni', 2, 'shizuoka', '中部', '22225'),
-- ('御前崎市', 'omaezaki', 2, 'shizuoka', '中部', '22223'),
-- ('牧之原市', 'makinohara', 2, 'shizuoka', '中部', '22226');

-- =============================================
-- 最終集計（22市区町村 合計101件）
-- =============================================
-- shizuoka-city: 23件
-- hamamatsu: 21件
-- numazu: 8件
-- fuji: 7件
-- iwata: 4件
-- atami: 3件
-- shimada: 3件
-- fukuroi: 3件
-- gotemba: 3件
-- fujieda: 2件
-- yaizu: 2件
-- kakegawa: 2件
-- mishima: 2件
-- fujinomiya: 2件
-- ito: 2件
-- susono: 2件
-- kosai: 2件
-- kikugawa: 2件
-- shimoda: 2件
-- izunokuni: 2件
-- omaezaki: 2件
-- makinohara: 2件
